### ISSUE TITLE
EXC_BAD_ACCESS during internal realm query

### ISSUE THREAD

**Issue by asjesset** [realm/realm-cocoa#4515] opened 2017-01-06 18:10 UTC
Running Realm 2.1.1

Not at all sure what's going on here. Grabbed this crash off Fabric. It appears another thread is trying to query realm. There might be some nested behavior going on.

Two models involved, Activity and Account. An Activity is being created, which tells the account to update. At this point the activity is unmanaged, but the account is probably (?) managed already.

```
#4
Crashed: RLMRealm notification listener
EXC_BAD_ACCESS KERN_PROTECTION_FAILURE 0x00000001742d1410
 Raw Text
0	libswiftContacts.dylib	
(Missing)
1	Realm	
void realm::Columns<bool>::evaluate_internal<realm::Column<long long> >(unsigned long, realm::ValueBase&) + 752
2
Realm	
realm::Compare<realm::Equal, bool, realm::Subexpr, realm::Subexpr>::find_first(unsigned long, unsigned long) const + 124
3	Realm	
bool realm::ColumnNodeBase::match_callback<(realm::Action)5, realm::Column<long long> >(long long) + 116
4	Realm	
bool realm::Array::find_optimized<realm::Equal, (realm::Action)7, 2ul, std::__1::__bind<std::__1::__mem_fn<bool (realm::ColumnNodeBase::*)(long long)>, realm::IntegerNodeBase<realm::Column<realm::util::Optional<long long> > >*, std::__1::placeholders::__ph<1>&> >(long long, unsigned long, unsigned long, unsigned long, realm::QueryState<long long>*, std::__1::__bind<std::__1::__mem_fn<bool (realm::ColumnNodeBase::*)(long long)>, realm::IntegerNodeBase<realm::Column<realm::util::Optional<long long> > >*, std::__1::placeholders::__ph<1>&>, bool, bool) const + 384
5	Realm	
bool realm::Array::find<realm::Equal, (realm::Action)7, std::__1::__bind<std::__1::__mem_fn<bool (realm::ColumnNodeBase::*)(long long)>, realm::IntegerNodeBase<realm::Column<realm::util::Optional<long long> > >*, std::__1::placeholders::__ph<1>&> >(long long, unsigned long, unsigned long, unsigned long, realm::QueryState<long long>*, std::__1::__bind<std::__1::__mem_fn<bool (realm::ColumnNodeBase::*)(long long)>, realm::IntegerNodeBase<realm::Column<realm::util::Optional<long long> > >*, std::__1::placeholders::__ph<1>&>, bool, bool) const + 288
6	Realm	
bool realm::IntegerNodeBase<realm::Column<realm::util::Optional<long long> > >::find_callback_specialization<realm::Equal, (realm::Action)5, (realm::DataType)0, false>(unsigned long, unsigned long) + 156
7	Realm	
realm::IntegerNodeBase<realm::Column<realm::util::Optional<long long> > >::aggregate_local_impl(realm::QueryStateBase*, unsigned long, unsigned long, unsigned long, realm::SequentialGetterBase*, int) + 452
8	Realm	
realm::Query::aggregate_internal(realm::Action, realm::DataType, bool, realm::ParentNode*, realm::QueryStateBase*, unsigned long, unsigned long, realm::SequentialGetterBase*) const + 312
9	Realm	
realm::Query::find_all(realm::TableViewBase&, unsigned long, unsigned long, unsigned long) const + 432
10	Realm	
realm::Query::find_all(unsigned long, unsigned long, unsigned long) + 108
11	Realm	
realm::_impl::ResultsNotifier::run() + 72
12	Realm	
realm::_impl::RealmCoordinator::run_async_notifiers() + 1180
13	Realm	
realm::_impl::RealmCoordinator::on_change() + 24
14	Realm	
realm::_impl::ExternalCommitHelper::listen() + 172
15	Realm	
std::__1::__async_func<realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0>::operator()() + 28
16	Realm	
std::__1::__async_assoc_state<void, std::__1::__async_func<realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0> >::__execute() + 28
17	Realm	
std::__1::__thread_proxy<std::__1::tuple<void (std::__1::__async_assoc_state<void, std::__1::__async_func<realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0> >::*)(), std::__1::__async_assoc_state<void, std::__1::__async_func<realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0> >*> >(void*, void*) + 84
18	libsystem_pthread.dylib	
_pthread_body + 240
19	libsystem_pthread.dylib	
_pthread_body + 282
20
libsystem_pthread.dylib	
thread_start + 4
```
```
#12
com.apple.root.default-qos
 Raw Text
0
Realm	
(anonymous namespace)::is_nsnull(objc_object*) + 84
1	Realm	
void (anonymous namespace)::QueryBuilder::add_constraint<(anonymous namespace)::ColumnReference, objc_object* __strong>(RLMPropertyType, NSPredicateOperatorType, unsigned long, (anonymous namespace)::ColumnReference, objc_object* __strong) + 180
2	Realm	
(anonymous namespace)::QueryBuilder::apply_value_expression(RLMObjectSchema*, NSString*, objc_object*, NSComparisonPredicate*) + 1996
3	Realm	
(anonymous namespace)::QueryBuilder::apply_predicate(NSPredicate*, RLMObjectSchema*) + 2320
4	Realm	
(anonymous namespace)::QueryBuilder::apply_predicate(NSPredicate*, RLMObjectSchema*) + 1520
5	Realm	
RLMPredicateToQuery(NSPredicate*, RLMObjectSchema*, RLMSchema*, realm::Group&) + 144
6	Realm	
-[RLMResults objectsWithPredicate:] + 156
7	Realm	
-[RLMResults objectsWhere:args:] + 68
8
Realm	
-[RLMResults objectsWhere:] + 36
<snip to protect interior code>
```

Feel free to ignore if this is gibberish. I have nothing reproducible at this time.

**Comment by istx25** [comment] 2017-01-10 17:26
Hey @asjesset. Thank you for filing this issue. We will look into this problem further. It would be greatly appreciated if you would be able to share any source code or projects with this problem that we can also try to reproduce the problem with.

**Comment by asjesset** [comment] 2017-01-10 19:38
At this time we have not recreated and don't have any code to share :(. If it recreates and I can narrow it down I'll share a pared down example. Thanks for the interest!

**Comment by istx25** [comment] 2017-01-10 19:39
Sounds good. :)

**Comment by austinzheng** [comment] 2017-06-01 18:33
I'm going to close this ticket since it hasn't been touched for a while. If you have further questions please feel free to file new tickets against us. If you do create a repro case feel free to either file a new ticket or re-open this one.

**Closed by austinzheng** 2017-06-01 18:33 UTC
Labels: Reproduction Required, S:On Hold, T:Bug-Crash
