### ISSUE TITLE
Private property is exposed in filter query

### ISSUE THREAD

**Issue by liuxuan30** [realm/realm-cocoa#5573] opened 2018-01-16 07:16 UTC
## Goals
Can Realm come up a solution to support proxying the filter query to its getter for private ones?

**The assumption here is we don't want to add a method as setter,  but stick to computed properties's getter and setter, and add it as ignored properties**

Private properties are exposed while there are public getter and setter for them. If we want to make a query, I have to use the private property name to do the filter, I hope Realm can hide info more flexible.

I understand Realm does not support compound key, so I will create it. And I want to hide other properties as well. For example:

I have `Quality` Object, which has several properties. I created a private `_compoundKey` to hide this from others and serve as compound key. 

When `datetime` and `city` get updated, I need to update compounKey as well, so I have to create getter and setter for them (didSet does not work with manged objects, due to the doc), and add these two computed properties into ignored proerties.

But when trying to do a query like 
`realm.objects(Quality.self).filter("city=\(city.rawValue)")`

Xcode throws error saying and crash:
>Terminating app due to uncaught exception 'Invalid property name', reason: 'Property 'city' not found in object of type 'Quality''

So I have to use the private name `_city` to do the query, which looses the purpose of `private`.

Can Realm come up a solution to support proxying the filter query to its getter for private ones?

Or, how can I achieve my goal with my scenario? addtional setter is just a kind of lame workaround, because we still need to expose the property name to do the filter query, plus additional setter still will get people confused which to use.

```swift
class Quality: Object
{
    @objc private dynamic var _datetime = ""
    @objc dynamic var concentration = 0.0
    @objc private dynamic var _city = 0
    @objc private dynamic var _compoundKey = "0-"
    
    var datetime: String
    {
        get { return _datetime }
        set
        {
            _datetime = newValue
            _compoundKey = computeCompoundKey()
        }
    }
    
    var city: Int
    {
        get { return _city }
        set
        {
            _city = newValue
            _compoundKey = computeCompoundKey()
        }
    }

    convenience init(city: Int, datetime: String, concentration: Double)
    {
        self.init()
        _city = city
        _datetime = datetime
        self.concentration = concentration
        _compoundKey = computeCompoundKey()
    }
    
    override static func primaryKey() -> String?
    {
        return "_compoundKey"
    }
    
    private func computeCompoundKey() -> String
    {
        return "\(_city)-\(_datetime)"
    }
    
    override static func ignoredProperties() -> [String]
    {
        return ["city", "datetime"]
    }
}
```
## Expected Results
Better support hiding private properties

## Actual Results
exposed

## Steps to Reproduce
see above

## Version of Realm and Tooling
Realm framework version: Latest master
Xcode version: ? 9.2
iOS/OSX version: ? iOS 11

**Comment by waner11** [comment] 2018-01-16 12:58
For Int properties you must to do this `realm.objects(Quality.self).filter("city == (city.rawValue)")` with two equal sign, for String properties is `realm.objects(Quality.self).filter("city = '(String)'")`

**Comment by liuxuan30** [comment] 2018-01-17 00:56
what? I have been using `"city=\(city.rawValue)"` all the time, and it gives me the right results.

**Comment by bdash** [comment] 2018-01-17 00:59
I'd strongly suggest avoiding Swift's string interpolation when building predicates. Instead you should rely on `NSPredicate`'s object substitution syntax:
```swift
realm.objects(AirQuality.self).filter("_city=%@", city.rawValue)
```

This will ensure that the predicate is parsed correctly even if the value in question contains characters with special meaning to `NSPredicate` (for instance, quotation marks).

**Comment by bdash** [comment] 2018-01-17 01:00
This issue appears to be a duplicate of https://github.com/realm/realm-cocoa/issues/4423.

**Comment by liuxuan30** [comment] 2018-01-17 01:10
@bdash thanks, but how about the `=` and `==` for Int and String? like what @waner11 said

**Comment by bdash** [comment] 2018-01-17 01:15
`=` and `==` are equivalent in NSPredicate's syntax. Whichever you use is a matter of preference.

**Closed by bdash** 2018-01-17 01:15 UTC
