### ISSUE TITLE
RealmSwift: List and LinkingObjects in Realm object causes memory leaks.

### ISSUE THREAD

**Issue by aKentaroIchima** [realm/realm-cocoa#5277] opened 2017-08-31 06:35 UTC
## Goals

Remove memory leaks in app. 

## Expected Results

Memory must be freed including List or LinkingObjects.

## Actual Results

When I profile our app with Xcode 8.3.3 Profiler, many leaks is reported.
Actually, our app crashes by memory allocation failure in Realm.

## Steps to Reproduce

Make object written in Code Sample and instantiate those objects from Realm query results.
Leaked object is List<> object self. It is constructed from Objective-C and used in Swift.

## Code Sample

Following Objects cause leaks.
```swift
class UnitObject: Object {
    let users = List<UserObject>()
}
class UserObject: Object {
    let units = LinkingObjects(fromType: UnitObject.self, property: "users")
}
```
## Version of Realm and Tooling

Swift version: 3.1

Realm framework version: 
  - Realm (2.8.3):
    - Realm/Headers (= 2.8.3)
  - Realm/Headers (2.8.3)
  - RealmSwift (2.8.3):
    - Realm (= 2.8.3)

Xcode version: 8.3.3

iOS/OSX version: 8-10

**Comment by austinzheng** [comment] 2017-09-05 19:40
Thanks for getting in touch with us. Can you provide us with a reproduction case that we can run in Instruments to see instances where the types you mentioned are leaking memory?

**Comment by aKentaroIchima** [comment] 2017-09-06 02:31
I found the similar issue: https://github.com/realm/realm-cocoa/issues/4334
The sample code in that issue causes the same leaks.
Please see https://github.com/joninsky/Realm-Memory-Test

You can see the leaks by Xcode memory profiler.
List<Friends> and LinkingObjects<User> are target.
It seems that objects in Realm object is not freed even if Realm object was freed.

**Comment by bdash** [comment] 2017-09-09 15:44
Duplicate of #4334.

**Closed by bdash** 2017-09-09 15:44 UTC
Labels: T:Help
