### ISSUE TITLE
Crash when writing to realm object

### ISSUE THREAD

**Issue by jabberwalky** [realm/realm-cocoa#4336] opened 2016-11-17 10:16 UTC
Hi, i have AlbumRealm that inherits RLMObject, and when i try to do 
`RLMResults <AlbumRealm *> *albums = [AlbumRealm allObjects];`
in debugger i see provided stacktrace

```
/Users/StasTomych/Projects/personal_photos_ios/Pods/Realm/include/core/realm/table.hpp:1842: [realm-core-2.1.4] Assertion failed: row_ndx < size() [942748213, 6343]
0   MyApp                          0x00000001005aad9c _ZN5realm4utilL18terminate_internalERNSt3__118basic_stringstreamIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE + 44
1   MyApp                          0x00000001005aafe4 _ZN5realm4util9terminateEPKcS2_lOSt16initializer_listINS0_9PrintableEE + 368
2   MyApp                          0x00000001004674e4 -[RLMAuthResponseModel initWithDictionary:requireAccessToken:requireRefreshToken:] + 0
3   MyApp                          0x000000010049c528 _ZN5realm5ValueINS_8RowIndexEEC2Ev + 0
4   MyApp                          0x0000000100441ac0 _ZNK5realm4List13get_uncheckedEm + 16
5   MyApp                          0x0000000100468c90 -[RLMFastEnumerator countByEnumeratingWithState:count:] + 304
6   MyApp                          0x00000001004695f4 _Z26RLMDescriptionWithMaxDepthP8NSStringPU24objcproto13RLMCollection11objc_objectm + 176
7   MyApp                          0x00000001004734e8 -[RLMObjectBase descriptionWithMaxDepth:] + 528
8   MyApp                          0x00000001004696b4 _Z26RLMDescriptionWithMaxDepthP8NSStringPU24objcproto13RLMCollection11objc_objectm + 368
9   Foundation                          0x0000000187639a80 _NSPrintForDebugger + 152
10  ???                                 0x00000001047348a4 0x0 + 4369631396
11  MyApp                          0x0000000100151828 main + 0
12  MyApp                          0x00000001001b973c -[ExternalPhotosCell userPressedFacebookSwitch:] + 452
13  UIKit                               0x000000018ca46484 <redacted> + 96
14  UIKit                               0x000000018ca46404 <redacted> + 80
15  UIKit                               0x000000018ca308b8 <redacted> + 452
16  UIKit                               0x000000018d42c60c <redacted> + 80
17  UIKit                               0x000000018d0233f8 <redacted> + 84
18  UIKit                               0x000000018d42ccf8 <redacted> + 796
19  UIKit                               0x000000018cfdf59c <redacted> + 64
20  UIKit                               0x000000018cfe2ca4 <redacted> + 124
21  UIKit                               0x000000018cba42e8 <redacted> + 260
22  UIKit                               0x000000018ca42828 <redacted> + 764
23  UIKit                               0x000000018cfd2ce8 <redacted> + 1100
24  UIKit                               0x000000018cfd2848 <redacted> + 408
25  UIKit                               0x000000018cfd1b04 <redacted> + 268
26  UIKit                               0x000000018ca40a44 <redacted> + 2960
27  UIKit                               0x000000018ca1152c <redacted> + 340
28  MyApp                          0x000000010075a3f4 uvSendEvents + 120
29  UIKit                               0x000000018d1fea54 <redacted> + 2736
30  UIKit                               0x000000018d1f84bc <redacted> + 784
31  CoreFoundation                      0x0000000186b64278 <redacted> + 24
32  CoreFoundation                      0x0000000186b63bc0 <redacted> + 524
33  CoreFoundation                      0x0000000186b617c0 <redacted> + 804
34  CoreFoundation                      0x0000000186a90048 CFRunLoopRunSpecific + 444
35  GraphicsServices                    0x0000000188516198 GSEventRunModal + 180
36  UIKit                               0x000000018ca7c2fc <redacted> + 684
37  UIKit                               0x000000018ca77034 UIApplicationMain + 208
38  MyApp                          0x00000001001518a4 main + 124
39  libdyld.dylib                       0x0000000185a745b8 <redacted> + 4
IMPORTANT: if you see this error, please send this log to help@realm.io.0x00000001015d33e0

after write transaction to [albums firstObject] app crashes, and then crashes each time when launched with this stacktrace

spec.cpp:40: [realm-core-2.1.4] Assertion failed: top_size >= 3 && top_size <= 5
0   MyApp                          0x000000010051ed9c _ZN5realm4utilL18terminate_internalERNSt3__118basic_stringstreamIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE + 44
1   MyApp                          0x000000010051efe4 _ZN5realm4util9terminateEPKcS2_lOSt16initializer_listINS0_9PrintableEE + 368
2   MyApp                          0x000000010064a780 _ZN5realm4Spec4initENS_6MemRefE + 664
3   MyApp                          0x000000010064e858 _ZN5realm5Table4initEmPNS_11ArrayParentEmb + 164
4   MyApp                          0x00000001005cef9c _ZN5realm5_impl11TableFriend26create_incomplete_accessorERNS_9AllocatorEmPNS_5Table6ParentEm + 516
5   MyApp                          0x00000001005ca7b8 _ZN5realm5Group21create_table_accessorEm + 228
6   MyApp                          0x00000001005ca648 _ZN5realm5Group12do_get_tableEmPFbRKNS_4SpecEE + 220
7   MyApp                          0x00000001003b7850 _ZN5realm12ObjectSchemaC2ERKNS_5GroupENS_10StringDataEm + 148
8   MyApp                          0x00000001003bbe9c _ZN5realm11ObjectStore17schema_from_groupERKNS_5GroupE + 284
9   MyApp                          0x0000000100472f30 _ZN5realm5Realm4initENSt3__110shared_ptrINS_5_impl16RealmCoordinatorEEE + 128
10  MyApp                          0x00000001003c0a80 _ZN5realm5_impl16RealmCoordinator9get_realmENS_5Realm6ConfigE + 560
11  MyApp                          0x00000001004742ec _ZN5realm5Realm16get_shared_realmENS0_6ConfigE + 244
12  MyApp                          0x0000000100454f34 +[RLMRealm realmWithConfiguration:error:] + 568
13  MyApp                          0x00000001004545c0 +[RLMRealm defaultRealm] + 76
14  MyApp                          0x000000010006fbf0 -[Migration migrateDB] + 196
15  MyApp                          0x0000000100070db4 -[Migration init] + 136
16  MyApp                          0x000000010005726c -[ServiceManager init] + 152
17  MyApp                          0x000000010005718c __32+[ServiceManager sharedInstance]_block_invoke + 60
18  libdispatch.dylib                   0x00000001013b921c _dispatch_client_callout + 16
19  libdispatch.dylib                   0x00000001013ba04c dispatch_once_f + 116
20  MyApp                          0x000000010005712c +[ServiceManager sharedInstance] + 144
21  MyApp                          0x00000001000a0a64 -[AppDelegate application:didFinishLaunchingWithOptions:] + 1936
22  UIKit                               0x000000018ca83100 <redacted> + 400
23  UIKit                               0x000000018cc93858 <redacted> + 3524
24  UIKit                               0x000000018cc995c8 <redacted> + 1656
25  UIKit                               0x000000018ccade60 <redacted> + 48
26  UIKit                               0x000000018cc965ac <redacted> + 168
27  FrontBoardServices                  0x000000018875d8bc <redacted> + 36
28  FrontBoardServices                  0x000000018875d728 <redacted> + 176
29  FrontBoardServices                  0x000000018875dad0 <redacted> + 56
30  CoreFoundation                      0x0000000186b64278 <redacted> + 24
31  CoreFoundation                      0x0000000186b63bc0 <redacted> + 524
32  CoreFoundation                      0x0000000186b617c0 <redacted> + 804
33  CoreFoundation                      0x0000000186a90048 CFRunLoopRunSpecific + 444
34  UIKit                               0x000000018ca7c2b0 <redacted> + 608
35  UIKit                               0x000000018ca77034 UIApplicationMain + 208
36  MyApp                          0x00000001000c58a4 main + 124
37  libdyld.dylib                       0x0000000185a745b8 <redacted> + 4
IMPORTANT: if you see this error, please send this log to help@realm.io.
```

Realm version: 2.0.2
Xcode version: 8.1

iOS/OSX version: 10.02

Dependency manager + version: cocoapods-1.1.0.rc.3

**Comment by austinzheng** [comment] 2016-11-22 00:27
Thanks for getting in touch with us. Is it possible for you to provide a reproduction case? It's difficult to determine exactly what is going on just by looking at the stacktrace.

**Comment by jpsim** [comment] 2016-12-07 02:15
We just released Realm 2.1.1 which includes several bug fixes, including one for a critical bug that could have caused file corruption. This looks like the issue you reported.

Please update to this version as soon as possible. https://github.com/realm/realm-cocoa/releases/tag/v2.1.1

Updating to this version won't automatically repair already corrupt files, so existing users who have experienced corruption will need to delete their affected Realm files. You can send these Realm files to us for forensic recovery if the data is critical.

Thanks.

**Comment by kishikawakatsumi** [comment] 2016-12-17 14:04
@jabberwalky Have you seen the same crash again on the latest version? Please let me know it seems resolved or not, thanks.

**Comment by TimOliver** [comment] 2016-12-24 01:12
This issue appears resolved due to fixes in a later release of Realm.

I'm going to close this issue. @jabberwalky, if you're still experiencing the crash, even on the latest release, please feel free to re-open this issue and follow up.

Happy holidays!

**Closed by TimOliver** 2016-12-24 01:12 UTC
Labels: Reproduction Required, S:Waiting For User, T:Bug-Crash
