### ISSUE TITLE
Even if list is effectively not modified in a transaction, change notifications still fire

### ISSUE THREAD

**Issue by winstondu** [realm/realm-cocoa#7449] opened 2021-09-23 00:49 UTC
### How frequently does the bug occur?

All the time

### Description

If a realm object has a realmlist as a property, and then within the transaction there are modifications to that realmlist (but the modifications cancel each other out), that is different 

```
// define the person class
class Person: Object {
@Persisted var ID: String!
@Persisted var name = ""
let friends = List<Person>()
}
```

Now if we we have two `Person` objects in the realm database, where `person1` has friend `person2`:
```
try? realm.write { \
  let person1 = Person(ID: "id1")
  person1.name = "Alex"
  let person2 = Person(ID: "id2")
  person2.name = "Bella"
  realm.add([person1, person2], update: .modified) 
  person1.friends.append(person2)
}
```

Now consider if we began observe change notifications for `person1`
```
let token = person1.observe { change in
   print("Change Notification Fired!")
}
```

The following realm transactions, which are equivalent, actually trigger different numbers of change notifications.

**Variation1:**
```
try? realm.write {
  // note the friends list is the same before and after this transaction. Yet a change notification is fired.
  person1.friends.removeAll()
  person1.friends.append(person2)
  person2.name = "Isabella" // no change notification
}
```

**Variation2**
```
try? realm.write {
  person2.name = "Isabella" // no change notification
}
```

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

See above code.

### Version

10.15.1

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

iOS 14.8

### Build environment

Xcode version: 13 GM
Dependency manager and version: Cocoapods, 1.10

**Comment by tgoyne** [comment] 2021-09-23 05:49
This is working as intended. Change notifications report what operations you performed on the thing being observed, and not by diffing the values.

**Comment by winstondu** [comment] 2021-09-23 18:00
@tgoyne , but is there a guarantee that at most one change notification is fired for each write transaction (no matter how many times the object being observed is modified in the transaction)?

**Comment by tgoyne** [comment] 2021-09-23 21:00
Yes, at most one notification is sent per write transaction committed.

**Closed** 2021-10-20 09:54 UTC
Labels: T-Bug, O-Community
