### ISSUE TITLE
Filter unmanaged object List by managed object property

### ISSUE THREAD

**Issue by visdyn** [realm/realm-cocoa#7116] opened 2021-02-14 14:15 UTC
## Goals
We are attempting to create a unique Set() of object _id's (or a filter) based on property's property e.g. an Object that has a property which is a managed object

In other words, we have a Person Class (unmanaged) and each person has a single Dog Class (managed) property. We want to get a list of those dogs' _id's - and want to ultimately have a Set (no duplicates) of dog _id's.

Note the _id's are created with `ObjectId.generate()` which may have something to do with the issue - but we also tested with `_id.stringValue` and had the same results.

If all of these objects are managed, then the issue is resolved. However, that does not fit the use case - the user must be able to create unmanaged PersonClass objects with an associated managed DogClass object until they are ready to save the data.

## Expected Results
Have a Set which includes unique dogs _id's

## Actual Results
Even though it appears the Array is successfully populated with dog _id's retrieved from the Realm objects, which can be iterated over, when casting it to a Set, we get an error

`This method may only be called on RLMArray instances retrieved from an RLMRealm`

## Steps for others to Reproduce
In a nutshell, this code produces the desired Array object of dog _id's

`let dogIdArray = personList.map { $0.myDog._id }` //it's a Swift array - not concerned about not being Live objects

and can actually be iterated over and printed, however, casting it to a Set throws the error

`let uniqueIdArray = Set(dogIdArray)`

In fact this code also throws the error; it attempts to return the dogs's owner, Jay by the dog _id

```
let idToFind = "d0"
let jayOwner = peopleList.filter("myDog._id == %@", idToFind).first!
```

## Code Sample

Start with the the Person and Dog class - each person has one dog

```
class PersonClass: Object {
    @objc dynamic var _id = ObjectId.generate()
    @objc dynamic var name = ""
    @objc dynamic myDog: DogClass!
}

class DogClass() {
   @objc dynamic var _id = ObjectId.generate()
   @objc dynamic var name = ""
}
```

Let's craft a person (in memory) and assign a (managed) dog to them - the dog _id's are d0, d1 ,d2 etc for simplicity

```
let jaysDog = realm.objects(DogClass.self).filter("_id == 'd0').first! //assume this dog exists

let p0 = PersonClass()
p0.name = "Jay"
p0.myDog = jaysDog
```

from there we craft a number of other person objects and assign a dog (managed) to each. We then store all the people in a Realm List object

```
let peopleList = List<PersonClass>()
peopleList.append(objectsIn: [p0, p1, p2, p3, p4, p5, p6, p7]) //people could be duplicates in real world use
```

From that List we create a Swift Array of the dog _id's, iterate over them and print to console - everything works as expected to this point. 

```
let dogIdArray = personList.map { $0.myDog._id }
dogIdArray.forEach { print($0) }
d0
d1
d2
d3
d4
d5
d6
d7
```

Even though what's shown are unique, in some cases there may be a duplicates, so we want to leverage a Set operation to generate a Set of unique dog _id's

`let uniqueIdArray = Set(dogIdArray)`

which then crashes with an error

**This method may only be called on RLMArray instances retrieved from an RLMRealm**

Noting that trying to Realm filter on that personList also crashes with the same error

```
let idToFind = "d0"
let jayOwner = peopleList.filter("myDog._id == %@", idToFind).first!
```

## Version of Realm and Tooling
Realm 10.5.0
XCode Version 12.4 (12D4e)
macOS 11.2.1 (20D74
This is a macOS App

**Comment by dianaafanador3** [comment] 2021-02-15 20:30
Hi @visdyn I don't seem to reproduce your error when you are trying to get an array of unique dogs ids `Set(dogIdArray)`. On the other hand the error you get when trying to fetch a `PersonClass` object, is because filter is trying to query data from Realm and cannot be done on and unmanaged object. Instead you can use ` let jayOwner = peopleList.filter { $0.myDog._id ==  "idToFind") }.first!` to use Swift array native filter to get it.

**Comment by visdyn** [comment] 2021-02-16 15:10
@dianaafanador3 Thanks for taking  a look.

I could have sworn at some point there was a filter on an unmanaged List but perhaps not as your comment says.

The Set() issue is not reproducing at the moment. We will continue to work on it to attempt to make it happen again - if it doesn't, we will close.

Thank  you again.

**Comment by dianaafanador3** [comment] 2021-02-16 16:03
@visdyn If you do have issues with this again, let me know.

**Comment by dianaafanador3** [comment] 2021-02-26 15:08
Closing this after the user cannot reproduce the issue any more.

**Closed by dianaafanador3** 2021-02-26 15:08 UTC
Labels: O-Community
