### ISSUE TITLE
[Xcode 12] ld: warning: direct access in function to global weak symbol means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.

### ISSUE THREAD

**Issue by reggian** [realm/realm-cocoa#6812] opened 2020-09-28 09:22 UTC
Building Realm 5.4.4 on Xcode 12 produces 32 warnings of such sort:

```
ld: warning: direct access in function 'auto realm::sync::Instruction::visit<(anonymous namespace)::RecoverLocalChangesetsHandler&>((anonymous namespace)::RecoverLocalChangesetsHandler&)' from file '/.../Pods/Realm/core/librealmcore-ios.a(client_reset.o)' to global weak symbol 'typeinfo for realm::Lst<realm::Timestamp>' from file '/.../Pods/Realm/core/librealmcore-ios.a(list.o)' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in function 'realm::sync::InstructionApplier::operator()(realm::sync::Instruction::ArraySet const&)' from file '/.../Pods/Realm/core/librealmcore-ios.a(instruction_applier.o)' to global weak symbol 'typeinfo for realm::Lst<realm::Timestamp>' from file '/.../Pods/Realm/core/librealmcore-ios.a(list.o)' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in function 'realm::sync::InstructionApplier::operator()(realm::sync::Instruction::ArrayInsert const&)' from file '/.../Pods/Realm/core/librealmcore-ios.a(instruction_applier.o)' to global weak symbol 'typeinfo for realm::Lst<realm::Timestamp>' from file '/.../Pods/Realm/core/librealmcore-ios.a(list.o)' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
...
```

Tested with Realm 5.2.0 on the same system and there are no such problems.

## Version of Realm and Tooling

Mac OS X 10.15.5 (19F101)
Xcode 12.0 (12A7209)
CocoaPods 1.9.3
Realm 5.4.4

**Comment by tgoyne** [comment] 2020-09-28 18:43
Duplicate of #6688.

**Closed by tgoyne** 2020-09-28 18:43 UTC
Labels: O-Community
