### ISSUE TITLE
Inconsistent Crash - Hard to replicate - Possibly backlink

### ISSUE THREAD

**Issue by sehajc** [realm/realm-cocoa#4071] opened 2016-09-08 19:28 UTC
## Goals

Crash-free write transaction

## Expected Results

No crash. Successful write transaction

## Actual Results

Saw a crash once so far. Unable to replicate. Maybe something to do with backlinks. Crash report and stacktrace attached below

## Steps to Reproduce

Unable to reproduce

## Code Sample

`try! realm.write {`
`uplodadFile.entryBacklink.first?.engagementBacklink.first?.uploadsComplete = false`
`}`

Crashed: NSOperationQueue 0x18209920 :: NSOperation 0x182c5e30 (QOS: USER_INITIATED)
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000000
0  Realm                          0x634606 realm::Table::get_backlink_view(unsigned long, realm::Table*, unsigned long) + 41
[stacktrace.txt](https://github.com/realm/realm-cocoa/files/462486/stacktrace.txt)

## Version of Realm and Tooling

```
ProductName:	Mac OS X
ProductVersion:	10.11.5
BuildVersion:	15F34

/Applications/Xcode.app/Contents/Developer
Xcode 7.3.1
Build version 7D1014

/usr/local/bin/pod
0.39.0
(not in use here)

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)


(not in use here)

/usr/bin/git
git version 2.7.4 (Apple Git-66)
```
Realm version: 1.0.2
iOS/OSX version: 9.3.2
Dependency manager + version: None

**Comment by TimOliver** [comment] 2016-09-09 07:58
Hi  @sehajc! Thanks for the report, and sorry to hear you're getting this intermittent crash

Could you please give us some more information on what your code is doing when this crash occurs? It looks like you're doing some work on a background thread; would you be able to post some snippets of that code so we can see how you've gone about implementing this?

Unfortunately, if this issue only happens intermittently and it's not possible to reliably trigger it, it's going to be very tricky for us to nail it down. The more information we can get about it, the better. :)

Thanks a lot!

*NB: Here's the top part of the stack trace so it's a bit quicker to see than downloading that text file:*
```
 # Crashlytics - plaintext stacktrace downloaded by Sehaj Chawla at Thu, 08 Sep 2016 14:54:41 GMT
# URL: https://fabric.io/limelight-platform/ios/apps/com.limelightplatform.limelightnew/issues/57d12d170aeb16625be390f3/sessions/a379ca052f7d412c9fcf49ca64d8ae3e
# Organization: Limelight Platform
# Platform: ios
# Application: Limelight
# Version: 2.1.5 (3)
# Bundle Identifier: com.limelightplatform.LimelightNew
# Issue #: 38
# Issue ID: 57d12d170aeb16625be390f3
# Session ID: a379ca052f7d412c9fcf49ca64d8ae3e
# Date: 2016-09-07T20:20:58Z
# OS Version: 9.3.2 (13F69)
# Device: iPad 3
# RAM Free: 42.2%
# Disk Free: 94%

#17. Crashed: NSOperationQueue 0x18209920 :: NSOperation 0x182c5e30 (QOS: USER_INITIATED)
0  Realm                          0x634606 realm::Table::get_backlink_view(unsigned long, realm::Table*, unsigned long) + 41
1  Realm                          0x43a1ab RLMGetLinkingObjects(RLMObjectBase*, RLMProperty*) (RLMAccessor.mm:381)
2  Realm                          0x43a1ab RLMGetLinkingObjects(RLMObjectBase*, RLMProperty*) (RLMAccessor.mm:381)
3  Realm                          0x4398df RLMDynamicGet (RLMAccessor.mm:901)
4  RealmSwift                     0x7d59bc LinkingObjects.first.getter (LinkingObjects.swift:491)
5  Limelight                      0x1709c0 UploadOperation.((markAsUploading in _0BF3821BD123B7A4A2D9BC95F8BE1EAC)() -> ()).(closure #1) (UploadOperation.swift:60)
6  RealmSwift                     0x7f2784 Realm.write(() throws -> ()) throws -> () (Realm.swift:776)
7  Limelight                      0x1703cc UploadOperation.main() -> () (UploadOperation.swift:61)
8  Limelight                      0x170910 @objc UploadOperation.main() -> () (UploadOperation.swift)
9  Limelight                      0x16b568 @objc ConcurrentOperation.start() -> () (ConcurrentOperation.swift)
10 Foundation                     0x2287f931 __NSOQSchedule_f + 192
11 libdispatch.dylib              0x21be6423 _dispatch_queue_drain$VARIANT$mp + 1758
12 libdispatch.dylib              0x21be5a61 _dispatch_queue_invoke$VARIANT$mp + 284
13 libdispatch.dylib              0x21be815d _dispatch_root_queue_drain + 396
14 libdispatch.dylib              0x21be7fcd _dispatch_worker_thread3 + 96
15 libsystem_pthread.dylib        0x21d9db29 _pthread_wqthread + 1024
16 libsystem_pthread.dylib        0x21d9d718 start_wqthread + 8

--

#0. com.apple.main-thread
0  libsystem_kernel.dylib         0x21ce2a00 syscall_thread_switch + 8
1  libsystem_platform.dylib       0x21d9975f _os_lock_handoff_lock_slow + 78
2  libobjc.A.dylib                0x21820e57 objc_object::sidetable_release_slow((anonymous namespace)::SideTable&, bool) + 22
3  libobjc.A.dylib                0x21820f37 objc_object::sidetable_release(bool) + 102
4  RealmSwift                     0x7df898 Object.init(realm : RLMRealm, schema : RLMObjectSchema) -> Object + 144
5  Limelight                      0x193a08 @objc EngagementFieldDefinition.init(realm : RLMRealm, schema : RLMObjectSchema) -> EngagementFieldDefinition (EngagementFieldDefinition.swift)
6  Realm                          0x449f87 -[RLMFastEnumerator countByEnumeratingWithState:count:] (RLMCollection.mm:97)
7  Realm                          0x44625b -[RLMArrayLinkView countByEnumeratingWithState:objects:count:] (RLMArrayLinkView.mm:214)
8  libswiftFoundation.dylib       0xd47088 NSFastGenerator.next() -> AnyObject? (__hidden#1408_:704)
9  RealmSwift                     0x7f5d2c RLMGenerator.next() -> A? (RealmCollectionType.swift:995)
10 RealmSwift                     0x7caf10 protocol witness for GeneratorType.next() -> A.Element? in conformance <A where ...> RLMGenerator<A> (Aliases.swift:994)
11 Limelight                      0xf8ed0 specialized AttendeeListViewModel.determineColumnTypes([String]) -> [Column]? (AttendeeListViewModel.swift)
12 Limelight                      0xf4108 AttendeeListViewModel.valueForCells(Engagement, columns : [String]) -> [String] (AttendeeListViewModel.swift:84)
13 Limelight                      0x2412e8 specialized AttendeeListVC.tableView(UITableView, cellForRowAtIndexPath : NSIndexPath) -> UITableViewCell (AttendeeListVC + Tableview.swift:29)
14 Limelight                      0x240e90 @objc AttendeeListVC.tableView(UITableView, cellForRowAtIndexPath : NSIndexPath) -> UITableViewCell (AttendeeListVC + Tableview.swift)
15 UIKit                          0x2692b465 -[UITableView _createPreparedCellForGlobalRow:withIndexPath:willDisplay:] + 672
16 UIKit                          0x2692b5a5 -[UITableView _createPreparedCellForGlobalRow:willDisplay:] + 68
17 UIKit                          0x2691ab51 -[UITableView _updateVisibleCellsNow:isRecursive:] + 2272
18 UIKit                          0x2692fd1b -[UITableView _performWithCachedTraitCollection:] + 78
19 UIKit                          0x266cf23b -[UITableView layoutSubviews] + 178
20 UIKit                          0x265e0a73 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 714
21 QuartzCore                     0x24679bdd -[CALayer layoutSublayers] + 128
22 QuartzCore                     0x24675385 CA::Layer::layout_if_needed(CA::Transaction*) + 348
23 QuartzCore                     0x24675219 CA::Layer::layout_and_display_if_needed(CA::Transaction*) + 16
24 QuartzCore                     0x246746e1 CA::Context::commit_transaction(CA::Transaction*) + 368
25 QuartzCore                     0x246743b5 CA::Transaction::commit() + 520
26 QuartzCore                     0x2466db3b CA::Transaction::observer_callback(__CFRunLoopObserver*, unsigned long, void*) + 138
27 CoreFoundation                 0x2202d6c9 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 20
28 CoreFoundation                 0x2202b9cd __CFRunLoopDoObservers + 280
29 CoreFoundation                 0x2202bdff __CFRunLoopRun + 958
30 CoreFoundation                 0x21f7b229 CFRunLoopRunSpecific + 520
31 CoreFoundation                 0x21f7b015 CFRunLoopRunInMode + 108
32 GraphicsServices               0x2356bac9 GSEventRunModal + 160
33 UIKit                          0x2664d189 UIApplicationMain + 144
34 Limelight                      0x23a6f0 main (AppDelegate.swift:19)
35 libdispatch.dylib              0x21c23873 (Missing)

```

**Comment by jpsim** [comment] 2016-10-17 23:53
Hi @sehajc, I'm just following up on @TimOliver's last comment. Have you seen this again since your initial report? Is there any more you could share that could help us reproduce this crash?

Specifically, if you've enabled logging support in Crashlytics, you should be able to recover the log and share the assertion failure that caused this, which may help shed some light on the situation.

Another thing to try is to upgrade to the latest version of Realm ([2.0.2](https://github.com/realm/realm-cocoa/releases/tag/v2.0.2) as of this writing) to see if this issue still occurs. Thanks!

**Comment by sehajc** [comment] 2016-10-20 20:38
Hi @jpsim Sorry for the late reply. That was the only time I saw that crash. Haven't been able to replicate it.

**Comment by jpsim** [comment] 2016-10-25 23:28
I'll close this because we landed several bug fixes to backlinks since the version you reported was affected (1.0.2). Please reopen if you see this again with the latest version of Realm.

**Closed by jpsim** 2016-10-25 23:28 UTC
Labels: T:Help
