### ISSUE TITLE
Carthage Error

### ISSUE THREAD

**Issue by UNIQUEXJ** [realm/realm-cocoa#6011] opened 2018-11-21 01:44 UTC
Xcode version: 10.1

Build version low

"Incompatible Swift version - framework was built with 4.1.2 (swiftlang-902.0.54 clang-902.0.39.2) and the local version is 4.2.1 (swiftlang-1000.11.42 clang-1000.11.45.1)."

**Comment by DavidObfuscator** [comment] 2018-11-21 14:03
duplicate of #5949

**Closed** 2018-11-21 15:41 UTC
Labels: T:Duplicate
