### ISSUE TITLE
App crashes on launch with encrypted Realm

### ISSUE THREAD

**Issue by dismory** [realm/realm-cocoa#1516] opened 2015-02-18 08:52 UTC
Realm 0.90.5
http://d.pr/n/12wdy/2X6EPZxd

**Comment by masterrr** [comment] 2015-02-18 13:44
Related? https://github.com/realm/realm-cocoa/issues/1472

**Comment by dismory** [comment] 2015-02-18 13:46
@tgoyne

**Comment by issue2k** [comment] 2015-02-20 17:47
Got the same issue when accessing the realm the first time after app launch.

```
Thread : Crashed: com.apple.main-thread
0  Foo                  0x000000010031ae10 tightdb::Array::init_from_mem(tightdb::MemRef) + 336
1  Foo                  0x0000000100393dd4 tightdb::SharedGroup::open(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, tightdb::SharedGroup::DurabilityLevel, bool, char const*) + 2504
2  Foo                  0x0000000100393dd4 tightdb::SharedGroup::open(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, tightdb::SharedGroup::DurabilityLevel, bool, char const*) + 2504
3  Foo                  0x0000000100395134 tightdb::SharedGroup::open(tightdb::Replication&, tightdb::SharedGroup::DurabilityLevel, char const*) + 7464
4  Foo                  0x000000010025f954 tightdb::SharedGroup::SharedGroup(tightdb::Replication&, tightdb::SharedGroup::DurabilityLevel, char const*) (group_shared.hpp:610)
5  Foo                  0x000000010025a5bc -[RLMRealm initWithPath:key:readOnly:inMemory:dynamic:error:] (RLMRealm.mm:303)
6  Foo                  0x000000010025b540 +[RLMRealm realmWithPath:key:readOnly:inMemory:dynamic:schema:error:] (RLMRealm.mm:483)
7  Foo                  0x000000010025b170 +[RLMRealm realmWithPath:readOnly:error:] (RLMRealm.mm:408)
8  Foo                  0x000000010025b0d0 +[RLMRealm defaultRealm] (RLMRealm.mm:396)
9  Foo                  0x00000001001306dc -[SFLPersistenceManager setupPrimaryKeyAccessor] (SFLPersistenceManager.m:180)
10 Foo                  0x000000010012fba0 -[SFLPersistenceManager init] (SFLPersistenceManager.m:54)
11 Foo                  0x000000010012fb04 __39+[SFLPersistenceManager sharedInstance]_block_invoke (SFLPersistenceManager.m:39)
12 libdispatch.dylib              0x000000019480d36c _dispatch_client_callout + 16
13 libdispatch.dylib              0x000000019480e244 dispatch_once_f + 96
14 Foo                  0x000000010012fad4 +[SFLPersistenceManager sharedInstance] (once.h:68)
```

**Comment by tgoyne** [comment] 2015-02-20 20:39
This may be fixed in 0.90.6.

**Comment by issue2k** [comment] 2015-02-21 06:21
@tgoyne great thanks, we will check that asap.

**Comment by anlaital** [comment] 2015-02-23 13:00
There is still some crash related to the encrypted database (0.90.6):

```
Thread : com.apple.main-thread
0  libsystem_platform.dylib       0x00000001975652b0 _platform_memmove + 96
1  *                           0x00000001004a493c tightdb::_impl::WriteLogCollector::internal_submit_log(char const*, unsigned long long) + 1356
2  *                           0x00000001004a493c tightdb::_impl::WriteLogCollector::internal_submit_log(char const*, unsigned long long) + 1356
3  *                           0x00000001004a5958 tightdb::_impl::WriteLogCollector::do_commit_write_transact(tightdb::SharedGroup&, unsigned long long) + 5480
4  *                           0x00000001004b1fc8 tightdb::SharedGroup::do_commit() + 10960
5  *                           0x00000001004b2098 tightdb::SharedGroup::commit_and_continue_as_read() + 11168
6  *                           0x00000001003664a0 -[RLMRealm commitWriteTransaction] (RLMRealm.mm:645)
7  *                           0x00000001003667f0 -[RLMRealm transactionWithBlock:] (RLMRealm.mm:672)
```

**Comment by issue2k** [comment] 2015-02-26 13:54
We even see still errors because of the encryption. 

iOS7
```
Thread : Crashed: Thread
0  libsystem_kernel.dylib         0x3b2621f0 __pthread_kill + 8
1  libsystem_pthread.dylib        0x3b2cc797 pthread_kill + 58
2  libsystem_c.dylib              0x3b212fdd abort + 76
3  Game of Roads                  0x00299111 tightdb::util::terminate(char const*, char const*, long, bool, long long, long long) + 648
4  Game of Roads                  0x00299487 tightdb::util::terminate(char const*, char const*, long, bool, long long, long long) + 1534
5  Game of Roads                  0x0029519d tightdb::util::EncryptedFileMapping::read_page(unsigned long) + 552964
6  Game of Roads                  0x0029884b (anonymous namespace)::exception_handler_loop() + 13014
7  Game of Roads                  0x00298ed9 void* tightdb::util::Thread::entry_point<void (*)()>(void*) + 80
8  libsystem_pthread.dylib        0x3b2cb919 _pthread_body + 140
9  libsystem_pthread.dylib        0x3b2cb88b _pthread_start + 102
```

**Comment by issue2k** [comment] 2015-02-26 13:55
We even still see crashes related to the encryption.

iOS 7

```
Thread : Crashed: Thread
0  libsystem_kernel.dylib         0x3b2621f0 __pthread_kill + 8
1  libsystem_pthread.dylib        0x3b2cc797 pthread_kill + 58
2  libsystem_c.dylib              0x3b212fdd abort + 76
3  *                  0x00299111 tightdb::util::terminate(char const*, char const*, long, bool, long long, long long) + 648
4  *                  0x00299487 tightdb::util::terminate(char const*, char const*, long, bool, long long, long long) + 1534
5  *                  0x0029519d tightdb::util::EncryptedFileMapping::read_page(unsigned long) + 552964
6  *                  0x0029884b (anonymous namespace)::exception_handler_loop() + 13014
7  *                  0x00298ed9 void* tightdb::util::Thread::entry_point<void (*)()>(void*) + 80
8  libsystem_pthread.dylib        0x3b2cb919 _pthread_body + 140
9  libsystem_pthread.dylib        0x3b2cb88b _pthread_start + 102
```

**Comment by anlaital** [comment] 2015-02-27 09:29
@tgoyne this still happens a lot on release builds where encryption is enabled, making it kind of impossible to ship anything with encryption enabled. No crashes are observed if encryption is not used.

I have the exact same call stacks as @issue2k when the crashes are reported. I am using the 0.90.6 Realm and the crashes occur on all iPhones and on both iOS 7 and iOS 8.

**Comment by dismory** [comment] 2015-02-27 10:16
Yes, what @anlaital says is true.

**Comment by issue2k** [comment] 2015-02-27 10:19
@anlaital @dismory i sent example code to help@realm.io so that they are able to reproduce the issue maybe you can even try to do that.

**Comment by tgoyne** [comment] 2015-02-27 17:17
Addition repro code would be very useful, as I've been unable to reproduce any issues.

**Comment by tgoyne** [comment] 2015-03-02 19:23
Replacing Pods/Realm/core/libtightdb-ios.a with http://static.realm.io/downloads/temp/realm-core-encryption-crash-fix.tar.gz fixes the crash in the repro crash @issue2k sent me. Note that you need to be using Realm 0.90.6 to have the right headers to go with that library.

**Comment by anlaital** [comment] 2015-03-03 05:07
Thanks. I will try this out as well and distribute a new build using it for our internal pilot.

**Comment by issue2k** [comment] 2015-03-03 05:29
Thanks a lot we will try this for our next testing release

**Comment by anlaital** [comment] 2015-03-04 04:39
I haven't had any crash reports coming in from the pilot with the fix, so most likely whatever you did fixed the issues we've been having with encrypted Realm. @tgoyne will this be included in your next release and if so, when will that release happen?

Thank you for the fixes for these crashes, since encryption is kind of a priority for us. :+1:

**Comment by issue2k** [comment] 2015-03-06 06:49
Even for us this solves the problem. We tested the app sind tuesday with > 100 testers now and got not a single crash anymore.

Thanks a lot @tgoyne for fixing this!

**Comment by tgoyne** [comment] 2015-03-06 21:27
The fix is now merged to master, so it should be present in the next release.

**Closed** 2015-03-07 01:01 UTC
