### ISSUE TITLE
realm crashed when adding object to realm

### ISSUE THREAD

**Issue by unchartedworks** [realm/realm-cocoa#1227] opened 2014-12-15 12:57 UTC
Thread : Crashed: defectmodel.realm
0  ist                         0x00000001003252f8 RLMAddObjectToRealm(RLMObject*, RLMRealm*, unsigned long) (table.hpp:1523)
1  ist                         0x00000001003251a4 RLMAddObjectToRealm(RLMObject*, RLMRealm*, unsigned long) (RLMObjectStore.mm:212)
2  ist                         0x0000000100341604 -[RLMRealm addObject:] (RLMRealm.mm:572)
3  ist                         0x000000010034171c -[RLMRealm addObjects:] (RLMRealm.mm:581)

**Comment by yoshyosh** [comment] 2015-01-07 17:37
Thanks @unchartedworks can you share the code where you make the object and where you use saveObjects?

**Comment by alazier** [comment] 2015-01-12 19:22
Are you still experiencing this issue? Can you try updating to the latest version if you haven't already?

**Comment by unchartedworks** [comment] 2015-01-16 10:20
I have updated to the latest version. I haven't found any new crash reports related to this issue. Hopefully it works. Thanks!

**Comment by jpsim** [comment] 2015-01-16 18:28
Closing since this issue was never reproduced.

**Closed by jpsim** 2015-01-16 18:28 UTC
