### ISSUE TITLE
RLMException when partially update objects with RealmOptional

### ISSUE THREAD

**Issue by Dwar3xwar** [realm/realm-cocoa#5079] opened 2017-06-28 19:40 UTC
## Goals

I want to partially update `Realm` objects with `RealmOptional`.
## Expected Results

The values get updated.
## Actual Results

```
2017-06-28 15:35:23.595 RealmBugCodeSample[76811:292245] *** Terminating app due to uncaught exception 'RLMException', reason: 'Invalid value '<_TtGC10RealmSwift13RealmOptionalSb_: 0x61000002da80>' of type '_TtGC10RealmSwift13RealmOptionalSb_' for expected type 'bool''
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001046cfb0b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x0000000101ef9141 objc_exception_throw + 48
	2   Realm                               0x0000000100e15c39 _ZL9checkTypebP11objc_objectP8NSString + 121
	3   Realm                               0x0000000100e15e3b _ZN18RLMAccessorContext5unboxIbEET_P11objc_objectbb + 107
	4   Realm                               0x0000000100e234d4 _ZN5realm6Object23set_property_value_implIU8__strongP11objc_object18RLMAccessorContextEEvRT0_RKNS_8PropertyET_bb + 484
	5   Realm                               0x0000000100e5ff50 _ZN5realm6Object6createIU8__strongP11objc_object18RLMAccessorContextEES0_RT0_RKNSt3__110shared_ptrINS_5RealmEEERKNS_12ObjectSchemaET_bPNS_8BasicRowINS_5TableEEE + 3984
	6   Realm                               0x0000000100e60670 RLMCreateObjectInRealmWithValue + 1520
	7   RealmSwift                          0x0000000101892688 _TFC10RealmSwift5Realm6createuRxCS_6ObjectrfTMx5valueP_6updateSb_x + 1128
	8   RealmBugCodeSample                  0x0000000100c6253b _TFFC18RealmBugCodeSample14ViewController11viewDidLoadFT_T_U1_FT_T_ + 315
	9   RealmSwift                          0x0000000101891ad7 _TFC10RealmSwift5Realm5writefzFzT_T_T_ + 71
	10  RealmBugCodeSample                  0x0000000100c61f07 _TFC18RealmBugCodeSample14ViewController11viewDidLoadfT_T_ + 1463
	11  RealmBugCodeSample                  0x0000000100c62582 _TToFC18RealmBugCodeSample14ViewController11viewDidLoadfT_T_ + 34
	12  UIKit                               0x000000010256dcca -[UIViewController loadViewIfRequired] + 1235
	13  UIKit                               0x000000010256e10a -[UIViewController view] + 27
	14  UIKit                               0x000000010243663a -[UIWindow addRootViewControllerViewIfPossible] + 65
	15  UIKit                               0x0000000102436d20 -[UIWindow _setHidden:forced:] + 294
	16  UIKit                               0x0000000102449b6e -[UIWindow makeKeyAndVisible] + 42
	17  UIKit                               0x00000001023c331f -[UIApplication _callInitializationDelegatesForMainScene:transitionContext:] + 4346
	18  UIKit                               0x00000001023c9584 -[UIApplication _runWithMainScene:transitionContext:completion:] + 1709
	19  UIKit                               0x00000001023c6793 -[UIApplication workspaceDidEndTransaction:] + 182
	20  FrontBoardServices                  0x000000010ab055f6 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 24
	21  FrontBoardServices                  0x000000010ab0546d -[FBSSerialQueue _performNext] + 186
	22  FrontBoardServices                  0x000000010ab057f6 -[FBSSerialQueue _performNextFromRunLoopSource] + 45
	23  CoreFoundation                      0x0000000104675c01 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	24  CoreFoundation                      0x000000010465b0cf __CFRunLoopDoSources0 + 527
	25  CoreFoundation                      0x000000010465a5ff __CFRunLoopRun + 911
	26  CoreFoundation                      0x000000010465a016 CFRunLoopRunSpecific + 406
	27  UIKit                               0x00000001023c502f -[UIApplication _run] + 468
	28  UIKit                               0x00000001023cb0d4 UIApplicationMain + 159
	29  RealmBugCodeSample                  0x0000000100c63707 main + 55
	30  libdyld.dylib                       0x0000000104d5665d start + 1
	31  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

```
This was not happening on the previous version of `Realm` my app was using, `2.6.1`. As far as I know this started to happen when I updated the latest version, `2.8.3`.
## Code Sample

[RealmBugCodeSample.zip](https://github.com/realm/realm-cocoa/files/1110008/RealmBugCodeSample.zip)

Everything of importance can be found in `ViewController.swift`.

## Version of Realm and Tooling

Realm framework version:  2.8.3

Xcode version:  8.3.2

Dependency manager + version: Cocoapods 1.2.0

**Comment by bdash** [comment] 2017-06-28 20:09
Thanks for getting in touch, @Dwar3xwar. Your app includes code that looks like so:

```swift
// Crash happens here
try! realm.write {
    realm.create(ObjectA.self,
                 value: ["id": "1",
                         "optionalBool": RealmOptional<Bool>(nil)],
                 update: true)
}
```

You're correct that this code throws an exception. The underlying cause is that `RealmOptional<Bool>` properties expect to be initialized with a value of type `Bool?`, not with instances of `RealmOptional`, in the same way that you cannot assign a `RealmOptional<Bool>` to the `value` property of `RealmOptional<Bool>`. `RealmOptional` itself is intended only to be used as a property type, not passed around as a value type.

Changing your code to pass a `Bool?` instead avoids the exception:

```swift
try! realm.write {
    realm.create(ObjectA.self,
                 value: ["id": "1",
                         "optionalBool": nil,
                 update: true)
}
```

It is possible that initializing the property with `RealmOptional<Bool>` instances worked in earlier releases, but I suspect it worked by coincidence rather than by design.

**Comment by Dwar3xwar** [comment] 2017-06-28 21:09
Thanks for the quick response @bdash. 

Thinking about it now, You are totally right about the it working by coincidence rather than by design. There is a difference between `RealmOptional<Bool>` and `Bool?`. 

My original thinking was that because a model's property was defined as `RealmOptional`, it would need a `RealmOptional` object.

Do you think it would be helpful to add this to the docs to provide clarification?

**Comment by bdash** [comment] 2017-06-28 21:13
> My original thinking was that because a model's property was defined as `RealmOptional`, it would need a `RealmOptional` object.

I can understand this line of reasoning.

Do keep in mind though that `RealmOptional` properties should be declared using `let` as they can only usefully be mutated in place (by modifying their `.value` property), not assigned to. 

> Do you think it would be helpful to add this to the docs to provide clarification?

It might be, though I'm not clear what the best way would be to clarify this. Perhaps tweaking the code example under [Optional Properties](https://realm.io/docs/swift/latest/#optional-properties) to call out that a value of the underlying type is what is passed to `Realm.create(…)`?

**Comment by jpsim** [comment] 2017-07-17 03:58
Closing as there are no actionable next steps for this.

**Closed by jpsim** 2017-07-17 03:58 UTC
Labels: S:Waiting For User, T:Help
