### ISSUE TITLE
Compiling fails because of _objectSchema for Realm 0.90.6

### ISSUE THREAD

**Issue by OlegAnghelov** [realm/realm-cocoa#3476] opened 2016-04-25 11:05 UTC
## Goals

We have DB logical migration problems. To properly debug, I want to go back in time and start installing one version after another to see where things go wrong. For that, I need to run older versions of our app.

## Actual Results
The project doesn't compile with the following message:
https://www.dropbox.com/s/9i59njt4bzuooqj/Screenshot%202016-04-25%2013.57.34.png?dl=0

```
/Users/oanghelov/Projects/namshi-2.3/Pods/Realm/Realm/RLMObject_Private.h:32:42: Existing instance variable '_objectSchema' for strong property 'objectSchema' may not be __unsafe_unretained
```

## Version of Realm and Tooling

Realm version: 0.90.6

Xcode version: 7.3

Dependency manager + version: cocoapods 0.35.0.

------
### My comments

I did try to pod install with 0.39.0, but i was getting errors of duplication of enums in Realm.
I saw lots of stackoverflow and Realm issues that were saying that duplciations are because of the cocoapods 0.38.0 version, and that 0.38.2 fixed that. But it doesn't seem to work anyway.

Is there a way to compile my project with given setup?

**Comment by mrackwitz** [comment] 2016-04-26 14:40
Try to use CocoaPods 0.36.0, clear the cache ` rm -rf ~/Library/Caches/CocoaPods`), run `pod install` again and make sure that you nuke DerivedData before trying to build. That worked locally for me.

**Comment by OlegAnghelov** [comment] 2016-04-29 07:51
Thanks for the answer!

How critical do you find this warning?
```
dyld: warning, LC_RPATH @executable_path/../Frameworks in /Applications/Xcode.app/Contents/PlugIns/Xcode3Core.ideplugin/Contents/MacOS/Xcode3Core being ignored in restricted program because of @executable_path
```

**Comment by jpsim** [comment] 2016-04-29 16:24
That looks like an Xcode bug, @OlegAnghelov... have you filed a radar? In any case, your realm issue here seems resolved, so I'll close this.

**Closed by jpsim** 2016-04-29 16:24 UTC
Labels: T:Help

**Comment by augard** [comment] 2016-05-10 14:13
I have same issue, i never used Realm before. I trying to setup it on brand new OS X project. I also tried to clear cache and DerivedData. (pods 0.39.0)

**Comment by jpsim** [comment] 2016-05-10 14:23
@augard please open a new issue with full steps to reproduce and I'll be happy to take a closer look!
