### ISSUE TITLE
Realm configuration schema issue

### ISSUE THREAD

**Issue by kevinmlong** [realm/realm-cocoa#3167] opened 2016-02-02 03:05 UTC
We have a singleton that manages getting stuff from a realm db. To avoid threading issues, the singleton uses a variable like so for getting a reference to a realm instance.

```swift
/// Returns a realm point to mydb.realm
var realmInstance : Realm? {
    get {
            return try! Realm(configuration: self.config)
    }
}

let config = Realm.Configuration(
   schemaVersion: 1,
   migrationBlock: { migration, oldSchemaVersion in
            // Do nothing right now....
   },
   // Get the path to the bundled file
  path: NSBundle.mainBundle().pathForResource("mydb", ofType:"realm"),
  // Open the file in read-only mode as application bundles are not writeable
  readOnly: true)
```

Then when the singleton instance needs to get a something out of the database, it does something like this:

```swift
self.realmInstance!.objects(ObjectClass)
```

Inconsistently, we get an error thrown having to do with schema mismatch.

```
fatal error: 'try!' expression unexpectedly raised an error: 
Error Domain=io.realm Code=1 "Realm at path already opened with different schema version." 
UserInfo={NSLocalizedDescription=Realm at path already opened with different schema version., 
Error Code=1}: file /Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-
700.1.101.15/src/swift/stdlib/public/core/ErrorType.swift, line 50
```

Since the schema version is set in the configuration and that configuration is always used, I guess I'm confused what's going on behind the scenes that the schema would be different.

Thoughts?

**Comment by kevinmlong** [comment] 2016-02-02 03:28
So... I just changed the realmInstance var to the following:

```swift
var realmInstance : Realm? {
        get {
            let version = schemaVersionAtPath(NSBundle.mainBundle().pathForResource("myDb", ofType:"realm")!)
            print("#### Schema version is \(version) #####")
            return try! Realm(configuration: self.config)
        }
    }
```

Now, I'm seeing that the version is changing....

```
#### Schema version is Optional(6) #####
#### Schema version is Optional(6) #####
#### Schema version is Optional(1) #####
#### Schema version is Optional(1) #####
```

Right before it crashes I see...

```
#### Schema version is Optional(6) #####
#### Schema version is Optional(6) #####
#### Schema version is Optional(6) #####
#### Schema version is Optional(6) #####
#### Schema version is Optional(6) #####
#### Schema version is Optional(6) #####
#### Schema version is Optional(6) #####
fatal error: 'try!' expression unexpectedly raised an error: Error Domain=io.realm Code=1 "Realm at path already opened with different schema version." UserInfo={NSLocalizedDescription=Realm at path already opened with different schema version., Error Code=1}: file /Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-700.1.101.15/src/swift/stdlib/public/core/ErrorType.swift, line 50
#### Schema version is Optional(6) #####
```

I'm confused...

**Comment by kevinmlong** [comment] 2016-02-02 03:42
Seems this was an issue related to creating the db with a desktop where the schema version was 6. I guess realm got confused between the schema version in the .realm file and the schema version provided in the configuration. Changing the schemaVersion in the configuration to 6 seems too have alleviated the issue. The question still remains...how was it able to open and read, but then randomly crash?

**Comment by mrackwitz** [comment] 2016-02-02 09:32
Is `self.config` a computed variable or do you initialize it anywhere later in the program? From what you report, it seems like that's used unexpectedly without being properly initialized. Or is there any specific reason for which you want to do a migration while your app is running?

**Comment by kevinmlong** [comment] 2016-02-02 13:36
@mrackwitz  `self.config` is an immutable variable defined as depicted in the snippet above. `self.realmInstance` is a computed variable (getter only) that uses self.config in retrieving the instance of the realm.

**Comment by mrackwitz** [comment] 2016-02-05 15:09
Sorry, that you didn't heard from me since then, but I'm quite stumped. We never came across such a problem so far and would definitively need more information, in the best case a sample project which reproduces this problem to figure out, where it's originates in. You can share code privately with us to help@realm.io.

**Comment by kreeger** [comment] 2016-02-09 18:15
@mrackwitz We're getting this now in an app where I've _just_ updated our `RealmSwift` pod from 0.97.0 to 0.98.0. This happens on **a fresh install of the app**, as well.

We're calling a method on a struct to set our default Realm configuration straight from our `applicationDidFinishLaunching...` method in our application delegate. It's the second thing to get called after setting up our logger.

```swift
DataCoordinator.setupRealmAndMigrateIfNecessary()
// which calls...
struct DataCoordinator {
    static func setupRealmAndMigrateIfNecessary() {
        // Database migrations, if needed
        Realm.Configuration.defaultConfiguration = Realm.Configuration(
            // Update this number for each change to the schema.
            schemaVersion: 7,
            migrationBlock: { migration, oldSchemaVersion in
                // ... migrations and stuff
            })
    }
}
```

This part executes fine, but the moment we try to `.write` something to our Realm (from a background thread; this is the first time anything hits our Realm on any thread), we get the same error as @kevinmlong.

```swift
    // On something like Thread 20
    let realm = try Realm()
    try realm.write {
        realm.add(ourRealmObject, update: true)
    }
```

```
Error Domain=io.realm Code=1 "Realm at path already opened with different schema version." UserInfo={NSLocalizedDescription=Realm at path already opened with different schema version., Error Code=1}
```

This happens well after we setup our default Realm configuration — in fact, we don't write anything to the Realm until _after_ a user initiated action (in our case, a login event).

I hope this helps — let me know if I can help do more troubleshooting. I'm going to keep poking around to see if I can circumvent this somehow.

**Comment by GreatApe** [comment] 2016-02-21 21:26
I am having a similar issue. With an older version it works fine, but with 98.2 I get the same error. `Realm at path already opened with different schema version`. It seems that releasing the reference is not enough anymore? Is there a way to "close" a realm?

**Comment by mrackwitz** [comment] 2016-02-22 11:55
@kreeger: Thanks for the thorough description.
@bdash: Do you have any ideas why this could occur?

**Comment by mrackwitz** [comment] 2016-02-22 11:55
@GreatApe:

>It seems that releasing the reference is not enough anymore? Is there a way to "close" a realm?

Releasing the reference is still enough, but you might want to make sure that you put the initialization into an explicit autoreleasepool so that the release happens more predictable. There is no other way to close a Realm.

**Comment by GreatApe** [comment] 2016-02-22 12:09
@mrackwitz 

Thanks for the reply. In my actual use case I have the realm reference as an instance variable, so I suppose autoreleasepool won't work in that case, but I'll have a go at it. The curious thing is that the behaviour changed from 96 to 98, I suddenly need to use autoreleasepools and also `RLMRealm.migrateRealm(config)` doesn't seem to work anymore, as mentioned in my issue https://github.com/realm/realm-cocoa/issues/3244.

**Comment by jeeftor** [comment] 2016-03-07 13:23
Anybody make progress on this one yet?

**Comment by jpsim** [comment] 2016-03-10 00:04
As far as I can tell, there are 3 or 4 different people in this thread with potentially separate issues, what seems to be common is the exception thrown ("Realm at path already opened with different schema version.").

---

@kevinmlong let's start with your issue, and what you've shared of your project with us, first:

```swift
var realmInstance : Realm? {
    get {
        let version = schemaVersionAtPath(NSBundle.mainBundle().pathForResource("myDb", ofType:"realm")!)
        print("#### Schema version is \(version) #####")
        return try! Realm(configuration: self.config)
    }
}
```

You say this logs the following:

```
#### Schema version is Optional(6) #####
#### Schema version is Optional(6) #####
#### Schema version is Optional(1) #####
#### Schema version is Optional(1) #####
```

which would seem to me is impossible given that passing a lower version number than what's currently set in the Realm file on disk will throw an exception at runtime, which is then converted to a Swift error in the `Realm` initializer, preventing that version from being set: https://github.com/realm/realm-cocoa/blob/v0.98.3/Realm/ObjectStore/object_store.cpp#L364

My limited testing confirms that setting a lower schema version number than set on disk throws a Swift error. If you were to share with us a complete sample project that can trigger this strange behavior you're experiencing, we'd be able to troubleshoot further. Otherwise, we're stuck here.

---

@kreeger I think something else is happening in your case.

> We're calling a method on a struct to set our default Realm configuration straight from our `applicationDidFinishLaunching`... method in our application delegate, which fires on the main thread. It's the second thing to get called after setting up our logger.

Note that `applicationDidFinishLaunching` is often not the first part of your code that runs in a Swift app. If you have any code that touches a Realm in properties with default values of view controllers that are loaded by storyboards, those will access the Realm before `applicationDidFinishLaunching` has a chance to run.

This could explain the `Realm at path already opened with different schema version.` exception you're seeing, as those properties with default values could be accessing the Realm prior to the `setupRealmAndMigrateIfNecessary` function being called, so when you come around to making the migration, the Realm is already open with a different schema version.

If this is not the case, we'll need more information to troubleshoot with you.

---

@GreatApe from recent comments made in your other issue (#3244), it seems like the original issue reported here is only tangentially related to yours. Let's continue the conversation in #3244.

---

@jeeftor hi! Can you please share more information about the issue you're experiencing? It's very difficult to help you without more information.

**Comment by mrackwitz** [comment] 2016-04-20 13:12
As we didn't heard back here in a while and we were unable to reproduce the originally reported issue, I'm going to close this now. Please feel free though to comment back or even better create a new issue, if you're experiencing a related issue.

**Closed by mrackwitz** 2016-04-20 13:12 UTC
Labels: Reproduction Required, S:Waiting For User, T:Help

**Comment by kreeger** [comment] 2016-04-20 13:14
Sorry I'm just now getting back to this one: @jpsim thanks to you, I've learned something new about Storyboards today! I haven't had the chance to circle back around to the app where I was having this issue, but I'll make sure to avoid this pitfall in the future.

**Comment by vbklv** [comment] 2018-01-04 15:05
I am having the same issue, have described it here:
https://stackoverflow.com/questions/48093517/random-realm-already-opened-with-a-different-schema-mode-errors
