### ISSUE TITLE
Crash only when running on device

### ISSUE THREAD

**Issue by jpmcglone** [realm/realm-cocoa#4128] opened 2016-09-22 16:58 UTC
## Goals

I'm calling the method: `public func object<T: Object, K>(ofType type: T.Type, forPrimaryKey key: K) -> T?`
And for some reason it works fine in all the simulators, but on my iPhone 7 Plus (running iOS 10), it crashes 100% of the time.

I get a EXC_BAD_ACCESS on the first line of the method:

```
public func object<T: Object, K>(ofType type: T.Type, forPrimaryKey key: K) -> T? {
    return unsafeBitCast(RLMGetObject(rlmRealm, (type as Object.Type).className(),
                                      dynamicBridgeCast(fromSwift: key)) as! RLMObjectBase?,
                         to: Optional<T>.self)
}
```

## Expected Results

What did you expected to happen?

Don't crash. On device nor on simulator.

What did happened instead?  
e.g. the stack trace of a crash

It crashed. EXC_BAD_ACCESS

## Steps to Reproduce

What are steps we can follow to reproduce this issue?

Here is a code sample:
```
if  let primaryKey = obj.value(forKey: primaryKeyName),
    let oldObject = object(ofType: type(of: obj),
                          forPrimaryKey: primaryKey) {    // It crashes on this line
    for property in obj.objectSchema.properties {
        if property != obj.objectSchema.primaryKeyProperty {
            if let obj = obj[property.name] as? Object {
                obj.sync()
            }
            obj[property.name] = obj[property.name] ?? oldObject[property.name]
        }
    }
    obj.willFinishSync(oldObject)
}
```

Provide a code sample or test case that highlights the issue.
If relevant, include your model definitions.
For larger code samples, links to external gists/repositories are preferred.
Alternatively share confidentially via mail to help@realm.io.
Full Xcode projects that we can compile ourselves are ideal!

## Version of Realm and Tooling

[In the CONTRIBUTING guidelines](https://git.io/vgxJO), you will find a script,
which will help determining these versions.

Realm version: 1.1.0

Xcode version: 8.0

iOS/OSX version: 10.12

Dependency manager + version: Cocoapods 1.1.0.rc.2

**Comment by jpsim** [comment] 2016-09-22 17:06
What does your model look like?

**Comment by jpmcglone** [comment] 2016-09-22 17:10
So I narrowed it down a bit, and I tried printing type(of: obj)

```
print(type(of: obj))
```

^ And now that is exactly where the crash is.

So I'm a little confused how the stack trace went into object(_, forPrimaryKey)

@jpsim Here's the model:

```
import ObjectMapper
import RealmSwift
import Realm

class Auth: Object, Mappable {
    dynamic var clientId: String = Config.AnglerAPI.clientId
    
    dynamic var createdAt: String? // TODO date
    dynamic var accessToken: String?
    var expiresIn: RealmOptional<Int>?
    dynamic var refreshToken: String?
    dynamic var userId: String?
    
    var scopes: List<RealmString>?
    
    dynamic var tokenType: String? // TODO enum
    dynamic var user: User?
    
    func mapping(map: Map) {
        createdAt <- map["created_at"]
        
        accessToken <- map["access_token"]
        
        var eI: Int?
        eI <- map["expires_in"]
        if let expiresIn = eI {
            self.expiresIn = RealmOptional<Int>(expiresIn)
        }
        
        refreshToken <- map["refresh_token"]
        userId <- map["resource_owner_id"]
        
        var s: [String]?
        s <- map["scopes"]
        if let scopes = s {
            let scopesList = List<RealmString>()
            for scope in scopes {
                let scopeString = RealmString(name: scope)
                scopesList.append(scopeString)
            }
            self.scopes = scopesList
        }
        
        tokenType <- map["token_type"]
        
        user <- map["user"]
    }
    
    // MARK: - Realm
    override static func primaryKey() -> String? {
        return "clientId"
    }
    
    static func ==(lhs: Auth, rhs: Auth) -> Bool {
        return lhs.clientId == rhs.clientId
    }
    
    // MARK: -
    required init?(map: Map) { super.init() }
    required init() { super.init() }
    required init(value: Any, schema: RLMSchema) { super.init(value: value, schema: schema) }
    required init(realm: RLMRealm, schema: RLMObjectSchema) { super.init(realm: realm, schema: schema)}
}
```

**Comment by jpmcglone** [comment] 2016-09-22 17:12
It's also probably important to note that 'obj' in this situation is type T

Here's the method it's in
```
func sync<T: RealmSwift.Object>(_ obj: T, recursive: Bool = true)
```

So, I'm using `sync<Auth>(auth)`

**Comment by jpsim** [comment] 2016-09-22 17:14
Looks like [SR-537](https://bugs.swift.org/browse/SR-537) to me.

**Comment by jpmcglone** [comment] 2016-09-22 17:18
Hmm it does look related. But someone commented that 
`latest snapshot 8-04 where syntax has been changed to type(of works fine`

Is he suggesting that type(of: works but dynamicType does not? 

Because I have it where type(of: doesn't work :(

**Comment by jpmcglone** [comment] 2016-09-22 17:22
Looking at it more, my issue is in an extension on `Realm`, in a generic method (not in a protocol extension like SR-537)

**Comment by jpsim** [comment] 2016-09-22 17:24
It's still the same issue, but with a slightly different repro case. I just confirmed SR-537 is still not fixed as of Xcode 8 GM (8A218a) and commented as such on the JIRA ticket.

**Comment by jpmcglone** [comment] 2016-09-22 17:24
Any workaround suggestions?

**Comment by jpsim** [comment] 2016-09-22 17:25
Instead of `func sync<T: RealmSwift.Object>(_ obj: T, recursive: Bool = true)` on a `Realm` extension, can you convert it to an extension on `RealmSwift.Object`?

**Comment by jpmcglone** [comment] 2016-09-22 17:27
I will try that!

Also, any ideas as to why this is not an issue on simulator but is on device? That bit worries me a lot

**Comment by jpsim** [comment] 2016-09-22 17:30
Well they're entirely different architectures for starters, x86_64 vs arm. Maybe you can ask on the SR for more information or to help nudge it along?

**Comment by jpmcglone** [comment] 2016-09-22 17:32
@jpsim moving it to an extension on Object works! You are a hero. Thank you so much :)

**Comment by jpsim** [comment] 2016-09-22 17:34
Glad you worked this out. Please do nudge that SR issue along though. Or file a radar. Best way to move it forward is to make sure the people who can fix it are aware of it!

**Closed by jpsim** 2016-09-22 17:34 UTC
Labels: T:Help
