### ISSUE TITLE
Realm 2.7.0 - IOS 10.0 - Error during compiling but run

### ISSUE THREAD

**Issue by ormaa** [realm/realm-cocoa#4962] opened 2017-05-17 15:20 UTC
Hi,

here are my system infos
OSX 10.12.14
Xcode 8.3.2 Swift 3.1
Application IOS 9.0 for iPad.
Realm Swift 2.7.0
(same problem with Realm Swift 2.5.1)

problem : I can use Realm Swift, read data in default.realm, save datas, insert data.
But Xcode report error during compiling.
example of error :
xyz.swift:20:19: Use of unresolved identifier 'RealmOptional'
xyz.swift:18:18: Use of unresolved identifier 'List'
ect.

I have this error since I put Realm framework in a subfolder, at the same level than the project folder.
if I put Realm inside the Xcode project folder : no error at all.

here is the folder structure : 
folderRoot/Project/ my sources
folderRoot/myProject.xcWorkspace ( I use an internal company graphic framework in this workspace)
folderRoot/Lib/ all my frameworks : Realm.framework and realmSwift.framework, ,Swift json, Crashlytics...
folderRoot/Framework : the internal company graphic framework.

Note : 
I can put Crashlytics framework, or Swift json framework, outside the Xcode project folder, without any issue.

I have updated, in build settings, the framework search path.
I have added Realm framework to Embedded binaries

I believe that Realm framework need to declare something ? any file to specify somewhere ? any parameter in my settings ?
I cannot use cocoa pods, nor carthage, nor swift package ( I am working for a customer who don't want them)

because I can work like this without issue, I think (but not sure) than it comes from something inside Realm Framework.

any idea would be appreciated.

Thanks
Olivier

**Comment by stel** [comment] 2017-05-18 11:23
If you're able to compile your code and run your app most likely Xcode just cached some error messages and continues showing it. Try to perform Clean/Clean build directory/restart Xcode and rebuild your app again.

**Comment by ormaa** [comment] 2017-05-18 11:28
no I did it several time, cleared the derivated folder, etc.
it does not changed anything.

**Comment by stel** [comment] 2017-05-18 11:40
You don't need to configure Realm framework in any point. Please make sure you fallow all steps from [Installation instructions](https://realm.io/docs/swift/latest/#installation). I've just tried to create an example Xcode project and wasn't able to reproduce this issue.

**Comment by ormaa** [comment] 2017-05-18 12:03
I followed that instructions, except that step :  Copy items if needed 

because the framework is already copied in another folder, on the same level than the project folder...

**Comment by stel** [comment] 2017-05-18 12:06
Well without a way to reproduce this the only thing I'd suggest is to remove the framework from the Xcode project completely, copy it to the destination folder and add it again.

**Comment by austinzheng** [comment] 2017-06-01 18:31
I'm going to close this ticket since it hasn't been touched for a while. If you have further questions please feel free to file new tickets against us.

**Closed by austinzheng** 2017-06-01 18:31 UTC
Labels: S:Waiting For User, T:Help
