### ISSUE TITLE
Realm module not found; 'Realm/Realm.h' file not found

### ISSUE THREAD

**Issue by crazyguyonabike** [realm/realm-cocoa#7025] opened 2021-01-04 23:40 UTC
## Goals
Realm module and headers found when using Cocoapod

## Expected Results
Realm module and headers found XCode 12

## Actual Results
Realm module not found; Realm/Realm.h not found 

## Steps for others to Reproduce
Existing project worked with XCode9, does not work with XCode11/12

## Code Sample
Podfile:

```
# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for App
  pod 'Stripe'
end

target 'AppExtension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AppExtension
end

target 'AppShared' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AppShared
  pod 'Realm'
  pod 'sqlite3'
end

## Version of Realm and Tooling

Realm (10.5.0)

Xcode version: Version 12.3 (12C33)

iOS/OSX version: 11.0

Dependency manager + version: /usr/local/bin/pod
1.10.0

**Comment by crazyguyonabike** [comment] 2021-01-04 23:41
Been struggling with this for a week. Realm is not found. I tried the sqlite3 Cocoapod and it works as expected i.e. includes are found, module is found, completion works as expected.

**Comment by DominicFrei** [comment] 2021-01-06 14:22
Hi @crazyguyonabike,

I could not reproduce the issue with the given Podfile, it seems fine on my side given your configuration (Cocoapods, Xcode, etc.).

Would you be able to provide an example project to reproduce the issue?

**Comment by michael-s-wu** [comment] 2021-01-22 07:02
@DominicFrei not OP but having similar issues. the issue arises when i try to archive the mac version. it builds and runs fine but fails on the archive. i tried it on a bare app and the same thing was still happening. i have the latest versions of cocoapods and realm.

**Comment by DominicFrei** [comment] 2021-01-22 09:35
@michael-s-wu Thank you for creating a sample app to showcase this. Can you post a link to that app here or send me the repository so that I can reproduce it one. my side?

**Comment by michael-s-wu** [comment] 2021-01-23 02:14
@DominicFrei test project: https://github.com/michael-s-wu/testProject
you'll have to install the pod since github was upset about me trying to upload that many files. 

literally a new project with 1 label and Mac added as a target. builds and runs fine on my Mac but the errors crop up once i go to archive it.

**Comment by michael-s-wu** [comment] 2021-01-26 06:12
@DominicFrei hi, any update on tracking down the issue?

**Comment by DominicFrei** [comment] 2021-01-26 15:19
@michael-s-wu Not yet, unfortunately. I've been working on some critical issues that I have to tackle first. But this issue is on the list as well.

**Comment by DominicFrei** [comment] 2021-02-19 16:33
@michael-s-wu I did look into the example today. The result is the same on my site with your example.

Interesting: It works when I use `use_modular_headers!`instead of `use_frameworks!` which is what I did in my above mentioned example.

This is not a solution for everyone though, I'm sure.

While this is not a solution it's at least a good first step: being able to reproduce the problem.
Maybe the fact mentioned by @crazyguyonabike will be a good start.

I will look further into this.

**Comment by michael-s-wu** [comment] 2021-02-20 08:01
@DominicFrei thanks for the update! im glad it wasn't just something weird happening with my computer/app. i tried "use_modular_headers!" instead but still got the same error. 🤷

**Comment by DominicFrei** [comment] 2021-02-23 11:11
@michael-s-wu While I'm looking into the issue, here is my version where it works with `use_modular_headers!`
https://github.com/DominicFrei/Playground/tree/realm-cocoa/issues/7025
Like yours, you have to do a `pod install` then you can archive the Mac OS version.

**Comment by DominicFrei** [comment] 2021-02-25 12:16
Here are my findings after further research:
- When creating a multi-platform app with the current version of Xcode you will get two targets, one for iOS and one for Mac OS.
- Maybe some Xcode version had this bundled into one target, I did not test it with older versions though. The current Xcode version suggests (simply by doing it that way) that having two targets is the way to go.
- Even though you can actually add Mac OS as a deployment target to an existing iOS target it does not really seem to work that way - at least not in combination with Cocoapods.
- Another issue is the fact that only `platform :ios` is specified in your `Podfile`. So I would almost expect it to not work with Mac OS at all (not even building and running).

Possible solutions:
- I would suggest creating a second target and then specifying this in the `Podfile` with `platform :ios` and `platform :osx`. According to Xcode and Cocoapods this seems to be the correct way. You cannot add `platform :ios` and `platform :osx` at the same time while only having one target.
- Alternatively, if you want to keep one target, the above mentioned way with `use_modular_headers!` seem to work too.

Is one of those ways sufficient for your needs? @michael-s-wu

**Comment by michael-s-wu** [comment] 2021-02-26 02:28
@DominicFrei yes, i was able to use modular headers and get it to work that way! everything seems to be working. i'll let you know if there's any other issues. thanks for your help!!

**Comment by DominicFrei** [comment] 2021-02-26 12:45
@michael-s-wu Glad I could help. Going to close this issue for now. If it turns out it's not solved please let me know and I'll re-open it. 👍

**Closed by DominicFrei** 2021-02-26 12:45 UTC
Labels: O-Community
