### ISSUE TITLE
Crash upgrading 5.5.0 to 10.6.0 on older iPhone Model

### ISSUE THREAD

**Issue by bb-git** [realm/realm-cocoa#7124] opened 2021-02-19 05:47 UTC
After releasing a TestFlight build with Realm 10.6.0 (before I used 5.5.0) there is a crash happening on my colleagues iPhone 6s. On my iPhone X  the app shows the splash screen a little longer, but then proceeds. The iPhone 6s shows the splash for around 20s and then quits to the home screen. After downgrading to 5.5.0 the problem disappeard. My guess is a **RAM issue** while upgrading. I have a quite large database on the device, upgrading it to the new format may exceed the older devices RAM and crash, while on devices with more RAM this doesn't happen

## Goals
Upgrade for all devices to 10.0+ without issues, so people don't get stuck in a crash loop.

## Expected Results
Upgrade of Realm happening without crash

## Actual Results
The app crashes on older devices during migration of the database. I acutally don't have physical access to my colleagues iPhone. And the crash tools don't catch the crash.

## Steps for others to Reproduce
Try migrating a rather large database (100k entries) on an older device like iPhone 6s.

## Code Sample
I don't have one

## Version of Realm and Tooling
Realm framework version: ?
10.6.0

Realm Object Server version: ?
none

Xcode version: ?
12.4

iOS/OSX version: ?
14.4 / 11.2.1

Dependency manager + version: ?
cocoapods 1.10.1

**Comment by DominicFrei** [comment] 2021-02-25 13:54
@bb-git Thank you for submitting this issue. Your assumption might be right.

Maybe the single, large realm cannot be mapped to the new version on old hardware.
One solution would be to bump your minimum deployment target if the old devices can actually not handle your database.

But I'd like to test other ideas first:

Does your schema allow to separate that single realm into multiple realms?
Would you be able to test that with your specific database?

**Comment by bb-git** [comment] 2021-02-25 14:16
@DominicFrei Thanks for your reply! I actually already use multiple realms. One for the user inputs and one for a large nutrition database. The last one hold most of the entries (only one model). So I can't split it. What I could do, is delete all entries of this nutrition database before migrating and redownload them, but I don't know how to make this operation happen before migration. Is there any place to put code to be executed before migration?

**Comment by DominicFrei** [comment] 2021-02-26 12:38
@bb-git You mean something like a pre-migration-block?
When you open the app with the new version of the framework, the old one does not exist anymore.
As soon as you try to open the new realm the migration happens. You can apply changes within the migration block but not before.

Therefore I'd like to look at your problem a bit more again:
I tried to reproduce your issue with an iPhone SE (which is the same as a 6S in terms of  CPU, RAM, etc.) using [a Playground](https://github.com/DominicFrei/Playground/tree/realm/realm-cocoa/issues/7124) I created for that. I ran it three times (500k items per run is the maximum those 2GB RAM can take) and ended up with 1,500,000 entries.
Then I jumped from Realm 5.5.0 to 10.6.0. The app opened within 10s and everything seems fine.

Can you maybe provide us with your specific example so that we can reproduce this case and maybe come up with a solution? NDAs are possible in case the code cannot be publicly shown btw.

**Comment by bb-git** [comment] 2021-03-01 07:31
@DominicFrei I managed to get a crash log from my colleague, so it seems, that the app is terminated due to reaching the max time allowance. So I guess, there is not a lot to fix there :(.
`Exception Type:  EXC_CRASH (SIGKILL)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Reason: Namespace SPRINGBOARD, Code 0x8badf00d
Termination Description: SPRINGBOARD, <RBSTerminateContext| domain:10 code:0x8BADF00D explanation:scene-create watchdog transgression: application<xxx>:48668 exhausted real (wall clock) time allowance of 18.94 seconds | ProcessVisibility: Foreground | ProcessState: Running | WatchdogEvent: scene-create | WatchdogVisibility: Foreground | WatchdogCPUStatistics: ( | "Elapsed total CPU time (seconds): 21.740 (user 21.740, system 0.000), 57% CPU", | "Elapsed application CPU time (seconds): 18.798, 50% CPU" | ) reportType:CrashLog maxTerminationResistance:Interactive>
Triggered by Thread:  0`

**Comment by DominicFrei** [comment] 2021-03-01 11:56
@bb-git Unfortunately yes. Realm is a very efficient and performance oriented database but depending on the size and complexity of your database some old devices (while still supported due to the fact that they support one of the iOS version we support) might not be able to handle that anymore. As shown above, creating 1,500,000 entries at the same time is simply too much for the RAM in my iPhone SE.
Splitting this up into three batches of 500,000 did help eventually. This is not always possible though.

Were you able to get more details on how these 18.94s are spent?
You mentioned you already use multiple realms. Would you be able to split them further?
We might not be able to reduce the complexity to a level that an iPhone 6 is able to handle but I thought we might at least think about as many options as we can. :)

**Comment by bb-git** [comment] 2021-03-01 17:57
@DominicFrei Thanks a lot for your help! I can't split the realms any further and I only found out that it happens while accessing the largest realm database for the first time. I will try to erase this largest realm file from the device before migration and recreate it afterwards.

**Comment by DominicFrei** [comment] 2021-03-02 12:08
Glad I could help (in a way).
Let me know if it worked and if you have any further questions.
I'll close this issue for now but we can re-open it at any time if necessary.

**Closed by DominicFrei** 2021-03-02 12:08 UTC
Labels: O-Community
