### ISSUE TITLE
Unable to update to realm 0.92.1

### ISSUE THREAD

**Issue by plusmancn** [realm/realm-cocoa#1875] opened 2015-05-08 07:30 UTC
Installing Realm (0.92.1)
    [!] /bin/bash -c '
    'set\ -e'
    'sh\ build.sh\ cocoapods-setup

    core is not a symlink. Deleting...

    Downloading dependency: core 0.89.1

    Archive:  /var/folders/8m/kw9d2d6s5_3_x591wmwbr1dh0000gn/T//core_bin/core-0.89.1.zip

       creating: core/

       creating: core/include/

       creating: core/include/realm/

      inflating: core/include/realm/alloc.hpp  

      inflating: core/include/realm/alloc_slab.hpp  

      inflating: core/include/realm/array.hpp  

      inflating: core/include/realm/array_basic.hpp  

      inflating: core/include/realm/array_basic_tpl.hpp  

      inflating: core/include/realm/array_binary.hpp  

      inflating: core/include/realm/array_blob.hpp  

      inflating: core/include/realm/array_blobs_big.hpp  

      inflating: core/include/realm/array_integer.hpp  

      inflating: core/include/realm/array_string.hpp  

      inflating: core/include/realm/array_string_long.hpp  

      inflating: core/include/realm/binary_data.hpp  

      inflating: core/include/realm/column.hpp  

      inflating: core/include/realm/column_backlink.hpp  

      inflating: core/include/realm/column_basic.hpp  

      inflating: core/include/realm/column_basic_tpl.hpp  

      inflating: core/include/realm/column_binary.hpp  

      inflating: core/include/realm/column_fwd.hpp  

      inflating: core/include/realm/column_link.hpp  

      inflating: core/include/realm/column_linkbase.hpp  

      inflating: core/include/realm/column_linklist.hpp  

      inflating: core/include/realm/column_mixed.hpp  

      inflating: core/include/realm/column_mixed_tpl.hpp  

      inflating: core/include/realm/column_string.hpp  

      inflating: core/include/realm/column_string_enum.hpp  

      inflating: core/include/realm/column_table.hpp  

      inflating: core/include/realm/column_tpl.hpp  

      inflating: core/include/realm/column_type.hpp  

      inflating: core/include/realm/commit_log.hpp  

      inflating: core/include/realm/data_type.hpp  

      inflating: core/include/realm/datetime.hpp  

      inflating: core/include/realm/descriptor.hpp  

      inflating: core/include/realm/descriptor_fwd.hpp  

      inflating: core/include/realm/exceptions.hpp  

      inflating: core/include/realm/group.hpp  

      inflating: core/include/realm/group_shared.hpp  

      inflating: core/include/realm/group_writer.hpp  

       creating: core/include/realm/impl/

      inflating: core/include/realm/impl/array_writer.hpp  

      inflating: core/include/realm/impl/destroy_guard.hpp  

      inflating: core/include/realm/impl/input_stream.hpp  

      inflating: core/include/realm/impl/output_stream.hpp  

      inflating: core/include/realm/impl/transact_log.hpp  

      inflating: core/include/realm/importer.hpp  

      inflating: core/include/realm/index_string.hpp  

      inflating: core/include/realm/lang_bind_helper.hpp  

      inflating: core/include/realm/link_view.hpp  

      inflating: core/include/realm/link_view_fwd.hpp  

      inflating: core/include/realm/mixed.hpp  

      inflating: core/include/realm/query.hpp  

      inflating: core/include/realm/query_conditions.hpp  

      inflating: core/include/realm/query_engine.hpp  

      inflating: core/include/realm/query_expression.hpp  

      inflating: core/include/realm/realm_nmmintrin.h  

      inflating: core/include/realm/replication.hpp  

      inflating: core/include/realm/row.hpp  

      inflating: core/include/realm/spec.hpp  

      inflating: core/include/realm/string_data.hpp  

      inflating: core/include/realm/table.hpp  

      inflating: core/include/realm/table_accessors.hpp  

      inflating: core/include/realm/table_basic.hpp  

      inflating: core/include/realm/table_basic_fwd.hpp  

      inflating: core/include/realm/table_macros.hpp  

      inflating: core/include/realm/table_ref.hpp  

      inflating: core/include/realm/table_view.hpp  

      inflating: core/include/realm/table_view_basic.hpp  

      inflating: core/include/realm/unicode.hpp  

       creating: core/include/realm/util/

      inflating: core/include/realm/util/assert.hpp  

      inflating: core/include/realm/util/bind.hpp  

      inflating: core/include/realm/util/bind_ptr.hpp  

      inflating: core/include/realm/util/buffer.hpp  

      inflating: core/include/realm/util/config.h  

      inflating: core/include/realm/util/features.h  

      inflating: core/include/realm/util/file.hpp  

      inflating: core/include/realm/util/logger.hpp  

      inflating: core/include/realm/util/memory_stream.hpp  

      inflating: core/include/realm/util/meta.hpp  

      inflating: core/include/realm/util/platform_specific_condvar.hpp  

      inflating: core/include/realm/util/safe_int_ops.hpp  

      inflating: core/include/realm/util/shared_ptr.hpp  

      inflating: core/include/realm/util/string_buffer.hpp  

      inflating: core/include/realm/util/terminate.hpp  

      inflating: core/include/realm/util/thread.hpp  

      inflating: core/include/realm/util/tuple.hpp  

      inflating: core/include/realm/util/type_list.hpp  

      inflating: core/include/realm/util/type_traits.hpp  

      inflating: core/include/realm/util/utf8.hpp  

      inflating: core/include/realm/utilities.hpp  

      inflating: core/include/realm/version.hpp  

      inflating: core/include/realm/views.hpp  

      inflating: core/include/realm.hpp  

      inflating: core/librealm-dbg.a     

      inflating: core/librealm-ios-dbg.a  

      inflating: core/librealm-ios.a     

      inflating: core/librealm.a         

      inflating: core/LICENSE            

      inflating: core/release_notes.txt  
    cp: Realm/*.h: No such file or directory

    cp: Realm/*.hpp: No such file or directory

**Comment by segiddins** [comment] 2015-05-08 14:26
@plusmancn are you using CocoaPods 0.37.1?

**Comment by shmidt** [comment] 2015-05-08 20:40
Carthage also can't install it.

**Comment by segiddins** [comment] 2015-05-08 20:44
@shmidt I believe the carthage issue is being tracked at https://github.com/Carthage/Carthage/issues/444

**Comment by shmidt** [comment] 2015-05-08 20:54
@segiddins Good to know, thank you.

**Comment by jpsim** [comment] 2015-05-26 22:37
The Carthage issue mentioned here was resolved by https://github.com/Carthage/Carthage/pull/446, whereas the original issue of `cp: Realm/*.h: No such file or directory` was likely caused by a corrupt .zip download of realm-core, which can be solved by deleting `$TMPDIR/core_bin`.

**Closed by jpsim** 2015-05-26 22:37 UTC
