### ISSUE TITLE
Error when running on ios device: dyld: Library not loaded: @rpath/Pods.framework/Pods

### ISSUE THREAD

**Issue by imran20487** [realm/realm-cocoa#2106] opened 2015-06-21 17:02 UTC
When I run my App on iOS device which uses Realm with swift 2.0 support installed using cocoapods, it gives this error and crashes the app:
Error: dyld: Library not loaded: @rpath/Pods.framework/Pods

**Comment by natemann** [comment] 2015-06-22 13:50
I think you need to turn of bitcode support.  That worked for me.

**Comment by segiddins** [comment] 2015-06-22 22:59
@imran20487, @natemann is correct that this is caused by Xcode 7 enabling bit code support by default. Bit code support precludes weak-linking frameworks, which cocoapods currently does. Until https://github.com/CocoaPods/CocoaPods/issues/3661 gets addressed, you can either disable bit code generation on your app or go into the target dependencies section of your target in your Xcode project, and change `Pods.framework` from optional to required.

**Comment by jpsim** [comment] 2015-06-25 21:58
Closing this issue, as it's quite likely the case that lack of bitcode support is to blame here. @imran20487 please reopen if that's not the case.

**Closed by jpsim** 2015-06-25 21:58 UTC
Labels: pending
