### ISSUE TITLE
ld: library not found for -lrealm-ios 

### ISSUE THREAD

**Issue by skander300** [realm/realm-cocoa#4333] opened 2016-11-16 10:43 UTC
Realm pod is successfuly installed but i am always having this error while building , any solution ?

**Comment by jpsim** [comment] 2016-11-17 00:30
Could you please fill out the [new issue template](https://github.com/realm/realm-cocoa/blob/master/.github/ISSUE_TEMPLATE.md)? It will help you share relevant information to help us help you. Thanks!

**Comment by skander300** [comment] 2016-11-17 09:09
**Goals :** 
my project must recognize that i have already installed realm-cocoa
**Expected results :** 
my project should be building successfully seeing that i installed realm cocoa through cocoapods
**Actual results :** 
ld: library not found for -lrealm-ios
**Code Sample :** 
it's a dependency problem

**Comment by jpsim** [comment] 2016-11-17 18:38
@skander300 there are several items from the issue template that you forgot to include. This is necessary to help us figure out why things aren't working for you.

Please share:

1. Version of CocoaPods used
2. Version of Xcode used
3. Structure of your project: what kinds of targets are there, how are they interconnected, which build and link Realm?
4. Output from running `pod install --verbose`
5. Which _version_ of Realm Objective-C and Realm Swift you're trying to install
6. Steps that we can take to reproduce this scenario on our end

**Comment by stel** [comment] 2016-11-28 10:39
@skander300 do you still experience this problem? If so please provide the info requested in the previous comment to help us identify it or feel free to close this issue.

**Comment by jpsim** [comment] 2016-11-29 18:24
Closing since we never got enough information from @skander300 and haven't heard back in two weeks.

**Closed by jpsim** 2016-11-29 18:24 UTC
Labels: S:Waiting For User, T:Help
