### ISSUE TITLE
Realm() call not returning neither throwing error

### ISSUE THREAD

**Issue by gonzula** [realm/realm-cocoa#5533] opened 2017-12-21 18:56 UTC
In some devices, runing iOS 10.3.3, when I make the first call, on main thread, to Relam(), something like `let realm = try! Realm()`, this call doesn't return. The execution of the app stops there and CPU usage stays at 0%

I'm using Realm 3.0.2 but I tested with 2.10.2 and got the same issue. The device i'm testing has 600 Mb free storage, but this occours even with a fresh install of the app, without any data stored in the realm.

I've installed realm using cocoa pods and my xcode version is 9.2

**Comment by ceafdc** [comment] 2017-12-21 19:02
Following the execution step by step, the execution stops at this line `let rlmRealm = try RLMRealm(configuration: RLMRealmConfiguration.default())` after getting `RLMRealmConfiguration.default()`.

**Comment by ceafdc** [comment] 2017-12-21 20:39
Discovered what was causing this, was a `didSet` on a variable in a model. I still don't know if it's an issue with realm or a documented thing that I missed, but moving this code to a separate function and calling when necessary solved my problem.

**Comment by waitwalker** [comment] 2017-12-23 04:17
Encountered the same problem +1

**Comment by bdash** [comment] 2018-01-17 05:13
@ceafdc, would it be possible for you to reconstruct a reproducible case of this? If so, we may be able to detect this and generate an error. I know we've done similar things in the past. Without a reproducible case it'll be difficult for us to handle it.

**Comment by stennie** [comment] 2019-09-18 20:20
Closing this issue due to no response. Feel free to reopen if additional information can be provided.

**Closed by stennie** 2019-09-18 20:20 UTC
Labels: O-Community
