### ISSUE TITLE
'try!' expression unexpectedly raised an error: Error Domain=io.realm Code=2 "Unable to open a realm at path '/var/mobile/Containers/Data/Application/A3689AC4-1E6E-4DCD-95B0-2A396281B79B/Documents/default.realm.lock': open() failed: Operation not permitte

### ISSUE THREAD

**Issue by RajAggrawal0507** [realm/realm-cocoa#6748] opened 2020-09-10 07:48 UTC
Complete crashlytics crash log given below.

iOS devices: All device or most of the device
iOS version: iOS 12.2 to 13.6 (Most of the versions in between)
Realm version: 4.4.1

Fatal error: 'try!' expression unexpectedly raised an error: Error Domain=io.realm Code=2 "Unable to open a realm at path '/var/mobile/Containers/Data/Application/A3689AC4-1E6E-4DCD-95B0-2A396281B79B/Documents/default.realm.lock': open() failed: Operation not permitted Path: /var/mobile/Containers/Data/Application/A3689AC4-1E6E-4DCD-95B0-2A396281B79B/Documents/default.realm.lock Exception backtrace: 0 Realm 0x0000000101e73bc4 _ZN5realm4util4File13open_internalERKNSt3__112basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEENS1_10AccessModeENS1_10CreateModeEiPb + 712 1 Realm 0x0000000101d7a52c _ZN5realm11SharedGroup7do_openERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEbbNS_18SharedGroupOptionsE + 1272 2 Realm 0x0000000101c99dec _ZN5realm5_impl11RealmFriend13read_group_toERNS_5RealmENS_9VersionIDE + 4712 3 Realm 0x0000000101c99a80 _ZN5realm5_impl11RealmFriend13re

**Comment by pavel-ship-it** [comment] 2020-09-10 12:36
Hi @RajAggrawal0507 
It looks like a duplicate of [existing issue](https://github.com/realm/realm-cocoa/issues/6096), so any details could help.
Do you have steps to reproduce? Maybe you have a sample code?

**Comment by RajAggrawal0507** [comment] 2020-09-10 12:45
Not get the exact help.
I also do not have steps to reproduce it.
It is crashing in Production builds not in dev or QA builds.

Also It crashed when I am accessing the first object from the realm after launch

**Comment by pavel-ship-it** [comment] 2020-09-10 12:56
@RajAggrawal0507 thank you for getting back to me. It seems the symptoms are same as in mentioned case.
I'll close this issue as a Duplicate of #6096. 
Please follow the mentioned issue for updates.

**Closed by pavel-ship-it** 2020-09-10 12:56 UTC
Labels: O-Community

**Comment by RajAggrawal0507** [comment] 2020-09-11 04:51
Thanks.
But not getting an appropriate solution in [#6096](https://github.com/realm/realm-cocoa/issues/6096)

**Comment by mbosoft** [comment] 2023-03-08 23:43
**Just change Simulator and work again ?**
Or delete Log Realm from your system, maybe u have already changed your Model Realm Class
