### ISSUE TITLE
Generic field

### ISSUE THREAD

**Issue by brokeniceinteractive** [realm/realm-cocoa#3093] opened 2016-01-12 15:02 UTC
Hi, i have this model:

import Foundation
import RealmSwift

    class Event: Object {
    
    dynamic var id              = 0
    dynamic var start_date      = NSDate()
    dynamic var end_date        = NSDate()
    dynamic var owner_id        = 0
    dynamic var subject         = ""
    
    // Specify properties to ignore (Realm won't persist these)
    
    //  override static func ignoredProperties() -> [String] {
    //    return []
    //  }
    }

i would like to add a field like this:

    dynamic var detail:Object?

and then set this field with another model between (person, meeting, ecc...) but id does not work, so than i tried to do this:

    class A : Object{
    }

    class B:A{

    }

    class C:A{

    }

and the field is:

    dynamic var detail:A?

but if i set:

event.detail = C or event.detail = B i obtain no error but in the record i have an empty array (), how can i fix this?

**Comment by jpsim** [comment] 2016-01-13 22:09
It looks like you're asking for more advanced polymorphism support in Realm, as described in #1109.

Please read our docs on [Model Inheritance](https://realm.io/docs/swift/latest/#model-inheritance) for what inheritance features Realm supports, and how to work around the lack of polymorphic behavior. Several options are discussed in #1109 too.

**Comment by jpsim** [comment] 2016-01-16 00:51
Closing as a duplicate of #1109.

**Closed by jpsim** 2016-01-16 00:51 UTC
Labels: Help, pending
