### ISSUE TITLE
3.1.0 prebuilt framework is not built with swift 4.0.3

### ISSUE THREAD

**Issue by liuxuan30** [realm/realm-cocoa#5580] opened 2018-01-18 03:25 UTC
@bdash 
carthage version: 0.27.0
Trying to update Realm to 3.1.0.
My project previously was building  directly from master source code for swift 4.0.3
However when running carthage update:
```
*** Downloading realm-cocoa.framework binary at "v3.1.0"
*** Skipped installing realm-cocoa.framework binary due to the error:
	"Incompatible Swift version - framework was built with 4.0.2 (swiftlang-900.0.69.2 clang-900.0.38) and the local version is 4.0.3 (swiftlang-900.0.74.1 clang-900.0.39.2)."
*** Checking out realm-cocoa at "v3.1.0"
```

**Comment by bdash** [comment] 2018-01-18 03:34
Why intentionally file a duplicate of an existing issue that you've already been involved with?

**Closed by bdash** 2018-01-18 03:34 UTC

**Comment by liuxuan30** [comment] 2018-01-18 03:35
what you mean? This is a different issue as 3.1.0 prebuilt framework is supposed to be on swift 4.0.3, while it is not.

**Comment by bdash** [comment] 2018-01-18 03:36
https://github.com/realm/realm-cocoa/issues/5538#issuecomment-354408556

**Comment by liuxuan30** [comment] 2018-01-18 03:36
oh I didn't see that notification.
