### ISSUE TITLE
Fine grained notifications crash on UICollectionView when modifying cells

### ISSUE THREAD

**Issue by CedricVanAsch** [realm/realm-cocoa#4750] opened 2017-03-20 14:54 UTC
## Goals

What do you want to achieve?
Every time a modification has been done to the realm, the corresponding fine grained notificationblock should update it and show a heart icon because the selected object is now favorised.

## Expected Results

What did you expected to happen?
updated uicollectionview to show a heart icon, since the selected model now has a favorite = true in its object 

## Actual Results
My cells calls for 1 self?.collectionView.reloadItems on the selected cell, after it crashes with the following error about deleting (while i don't delete a single thing in Realm during these actions).

```
2017-03-20 15:43:17.915998 promobutler-ios[8685:2721456] *** Assertion failure in -[UICollectionView _endItemAnimationsWithInvalidationContext:tentativelyForReordering:animator:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit/UIKit-3600.6.22/UICollectionView.m:5422
2017-03-20 15:43:17.972122 promobutler-ios[8685:2721456] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'attempt to delete item 33 from section 0 which only contains 4 items before the update'
*** First throw call stack:
(0x1886b51b8 0x1870ec55c 0x1886b508c 0x18916d02c 0x18ee62064 0x18ee67c98 0x18ee67f78 0x18ee67dd8 0x18ee67d5c 0x18e744618 0x1001851f4 0x10298f708 0x10295efe8 0x102161970 0x1021614d8 0x1020b3094 0x1020b2ff0 0x1020a50d4 0x1020a4fdc 0x10210c294 0x1022a60cc 0x10232bb14 0x10232c684 0x10232c65c 0x188662b5c 0x1886624a4 0x1886600a4 0x18858e2b8 0x18a042198 0x18e5d57fc 0x18e5d0534 0x100143f6c 0x1875715b8)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

## Steps to Reproduce

What are steps we can follow to reproduce this issue?
I'm hoping my Code Sample will clear it out. To reproduce, you just need to push a collectionviewcell, it will make changes in the realm database.

## Code Sample
```swift
class StepTwo : UIViewController, UICollectionViewDelegate, UICollectionViewDataSource{
    
    @IBOutlet weak var textLabel: UILabel!
    @IBOutlet weak var collectionView: UICollectionView!
    
    let producers: Results<Producer> = {
        ProducersRealm().getAllProducers()
    }()

    // receive notification
    var token: NotificationToken?  = nil
    
    override func viewDidLoad() {
        super.viewDidLoad()
        collectionView.delegate = self
        collectionView.dataSource = self
        registerViewCell()
            
        token = producers.addNotificationBlock { [weak self] (changes: RealmCollectionChange) in
            
            guard (self?.collectionView) != nil else { return }
            
            // MARK: - Switch on State
            
            switch changes {
                
            case .initial:
                self?.collectionView.reloadData()
                break
            case .update(_, let deletions, let insertions, let modifications):
                weak var weakSelf = self
                self?.collectionView.performBatchUpdates({
                    self?.collectionView.insertItems(at: insertions.map({ IndexPath(row: $0, section: 0)}))
                    self?.collectionView.deleteItems(at: deletions.map({ IndexPath(row: $0, section: 0)}))
                    self?.collectionView.reloadItems(at: modifications.map({ IndexPath(row: $0, section: 0)}))
                    
                }, completion: nil)
                break
            case .error(let error):
                print(error.localizedDescription)
                break
            }
        }
    }
    
    deinit {
        token?.stop()
    }

    fileprivate func registerViewCell() {
        collectionView?.register(UINib(nibName: "ProducerViewCell", bundle: nil), forCellWithReuseIdentifier: ProducerViewCellIdentifier)
    }
   
    // MARK: UICollectionViewDataSource
    
    func numberOfSections(in collectionView: UICollectionView) -> Int {
        return 1
    }
    
    func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
        return producers.count
    }
    
    func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        let cell = collectionView.dequeueReusableCell(withReuseIdentifier: ProducerViewCellIdentifier, for: indexPath) as? ProducerViewCell
        cell!.configure(producers[indexPath.row])
        return cell!;
    }

    func collectionView(_ collectionView: UICollectionView, didSelectItemAt indexPath: IndexPath) {
        // check connection
            let realmProducer = producers[indexPath.row]
            favoriseItemRealm(realmProducer, textAdded: "addedRetailer", textDeleted: "deletedRetailer", view: self, button: nil)
            print("data from didSelectItem -> \(producers[indexPath.row])")
        }
    }
}
 ```
    
```swift
// My Model
open class Producer: Object, Mappable {
    
    dynamic open var id: Int = 0
    dynamic open var name: String?
    dynamic open var logo: String?
    dynamic open var favorite = false
    
    required public convenience init?(map: Map) {
        self.init()
    }
    
    override open class func primaryKey() -> String {
        return "id"
    }
    
    open func mapping(map: Map) {
        id <- map["id"]
        name <- map["name"]
        logo <- map["logo"]
    }
}
```

## Version of Realm and Tooling

- Realm version: 2.4.4
- Xcode version: 8.2.1 (8C1002)
- iOS/OSX version: 10.2.1
- Dependency manager + version:

**Comment by istx25** [comment] 2017-03-20 16:51
Hi @CedricVanAsch. Thanks for reaching out! I've escalated this to one of the Cocoa engineers who will be able to review your code sample and follow-up with you.

**Comment by Alex293** [comment] 2017-03-20 17:11
I may have the answer as I'm running the same king of issues. I bet you order your collection by the property you modify ? If so realm change sees that modification in the ordered collection as a delete then insert. Try without ordering in ProducersRealm().getAllProducers()

**Comment by CedricVanAsch** [comment] 2017-03-21 08:43
@Alex293 I'm not ordering my collection by that property. Here is some info on how the `favoriseItemRealm(realmProducer, textAdded: "addedRetailer", textDeleted: "deletedRetailer", view: self, button: nil)` looks like (i think this is where my crash is caused, since this is where I edit the .favorite part of the Producer):

`
  // if object is a Producer
    if (object as? Producer) != nil {
        if let downcastObject = object as? Producer {
            let open = realm.objects(Producer.self).filter("id == %@", downcastObject.id).first
            try! realm.write {
                // user is offline
                if hasInternet() == false {
                    if open!.favorite != true {
                        open?.favorite = true
                        if userLoggedIn() {
                            // write to dabatase if user is logged in, but offline
                            SyncFavoriteItemRealm.shared.saveOrUpdate((open?.id)!,favorite: true, type: ContentType.PRODUCER.rawValue)
                        }
                    } else {
                        open?.favorite = false
                        if userLoggedIn() {
                            // write to dabatase if user is logged in, but offline
                            SyncFavoriteItemRealm.shared.saveOrUpdate((open?.id)!,favorite: false, type: ContentType.PRODUCER.rawValue)
                        }
                    }
                    // user is online
                } else {
                    if open!.favorite != true {
                        open?.favorite = true
                        if userLoggedIn() {
                            //sync to backend
                        }
                        //GoogleAnalyticsHelper.shared.trackFavoriteItem(downcastObject)
                    } else {
                        open?.favorite = false
                        if userLoggedIn() {
                            // sync to backend
                        }
                    }
                }
            }
        }
        
    }
`

**Comment by stel** [comment] 2017-03-21 09:25
Before moving forward with further investigation I suggest you to remove `collectionView.reloadData()` from `collectionView:didSlectCell` because collection view will be updated properly in notification handler.

Also try to minimize the amount of actions you perform inside a write transaction, try to use it only for updating realm objects, like:

```Swift
if open!.favorite != true {
    try! realm.write {
        open!.favorite = true
    }
}
```

**Comment by CedricVanAsch** [comment] 2017-03-21 11:08
@stel Hi,
I implemented both your changes as requested, but with the exact same result.
Assertion failure in -[UICollectionView _endItemAnimationsWithInvalidationContext:tentativelyForReordering:], /SourceCache/UIKit/UIKit-3347.44.2/UICollectionView.m:3870
2017-03-21 12:07:50.029 promobutler-ios[1433:244897] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'attempt to delete item 49 from section 0 which only contains 4 items before the update'
*** First throw call stack:
(0x2708a137 0x35514c77 0x2708a00d 0x27d89bc9 0x2aceade3 0x2acee8ab 0x2acee70f 0x2a8ab05b 0x20298c 0x276d670 0x276d7a8 0x27339a4 0x1fedb71 0x1fed735 0x1f68bc9 0x1f68b33 0x1f5f765 0x1f5f66d 0x1fa4873 0x20f92c7 0x215b8b9 0x215c115 0x215c101 0x2705022f 0x2704f643 0x2704dcc1 0x26f999a1 0x26f997b3 0x2e95b1a9 0x2a74a635 0x1a85c0 0x35ae2aaf)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by stel** [comment] 2017-03-21 11:40
Alright, according to the error message you get you try to delete non-existing row from the collection view. Please check the number of rows in your collection view (`producers.count` actually) before you performing the update and check the indexes in notification handler.

Also please check if you modify your collection view from other places in your code. Unfortunately it's very hard to suggest anything without being able to reproduce this issue, so please make a simplified Xcode project that reproduces that issue and share it with us.

**Comment by CedricVanAsch** [comment] 2017-03-21 13:19
@stel what exactly do you mean with check the indexes in the notification handler? 
So this is what I got for the numbers

```
case .update(_, let deletions, let insertions, let modifications):
                self?.collectionView.performBatchUpdates({
                    self?.collectionView.insertItems(at: insertions.map({ IndexPath(row: $0, section: 0)}))
                    self?.collectionView.deleteItems(at: deletions.map({ IndexPath(row: $0, section: 0)}))
                    self?.collectionView.reloadItems(at: modifications.map({ IndexPath(row: $0, section: 0)}))
                    
                    for item in modifications {
                        print("modifying: \(item)")
                    }
                    for item in insertions {
                        print("inserting: \(item)")
                    }
                    for item in deletions {
                        print("deleting: \(item)")
                    }
```


> Get numberOfItemsInSection 0 153
data from didSelectItem -> Producer {
	id = 1234;
	name = ALDI;
	nameNL = ALDI;
	nameFR = ;
	logoUrl = mockupurl.com;
	siteUrl = mockupurl.com;
	favorite = 1;
}
modifying: 3
Get numberOfItemsInSection 0 153
2017-03-21 14:16:07.631 promobutler-ios[1602:265648] *** Assertion failure in -[UICollectionView _endItemAnimationsWithInvalidationContext:tentativelyForReordering:], /SourceCache/UIKit/UIKit-3347.44.2/UICollectionView.m:3870
2017-03-21 14:16:07.940 promobutler-ios[1602:265648] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'attempt to delete item 49 from section 0 which only contains 4 items before the update'
*** First throw call stack:
(0x2708a137 0x35514c77 0x2708a00d 0x27d89bc9 0x2aceade3 0x2acee8ab 0x2acee70f 0x2a8ab05b 0x1ed6bc 0x2758670 0x27587a8 0x271e9a4 0x1fd8b71 0x1fd8735 0x1f53bc9 0x1f53b33 0x1f4a765 0x1f4a66d 0x1f8f873 0x20e42c7 0x21468b9 0x2147115 0x2147101 0x2705022f 0x2704f643 0x2704dcc1 0x26f999a1 0x26f997b3 0x2e95b1a9 0x2a74a635 0x1932f0 0x35ae2aaf)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by stel** [comment] 2017-03-21 13:47
Well, according to that log messages you have 153 rows in collection view and reload the 3rd row while error message says that collection view has only 4 items. Most likely you're getting this error from another collection view. Please try to set [Exception Breakpoint](http://stackoverflow.com/questions/17802662/exception-breakpoint-in-xcode) to find the exact place of that issue in your app. Unfortunately without having the example Xcode project I'm not able to investigate it.

**Comment by CedricVanAsch** [comment] 2017-03-21 15:39
I'm beginning to see the issue. In my next step I have a 'Folders' collectionview, containing all the folders. The model is the following:
```
class Folder: Object, Mappable {
    dynamic open var id:Int = 0
    dynamic open var url:String?
    dynamic open var coverUrl: String?
    open var categories = List<RealmCategory>()
    open var types  = List<Types>()
    dynamic open var producer:Producer?
}
```

What I think is happening: with updating the Producer his favorite, it also triggers my Folders (which can contain this Producer model - see screenshot of the Folders model). For some reason in the Folders it deleted the Producer instead of modifying it.
Is there any way I can make sure the notifications only start when the selected collectionview is visible, and not before? (Because now it tries to update the Folders Realm while it's not visible, but the notification is triggered)
<img width="596" alt="screen shot 2017-03-21 at 16 33 43" src="https://cloud.githubusercontent.com/assets/14325937/24155587/8d6fb476-0e54-11e7-96f0-291d50eb98db.png">

**Comment by CedricVanAsch** [comment] 2017-03-21 15:59
Small update: I got it to stop crashing by placing the notification token from my next step (which wasn't visible yet, but the notification was called) in my `viewWillAppear` instead of the `viewDidLoad` (causing it not to receive a notification to update when the collectionview isn't visible). Is this a problem? If it isn't, my issue is solved.
Many thanks!

**Comment by stel** [comment] 2017-03-22 11:56
From what I've seen in the log and error messages you provided, I can tell that most likely the issue happened because the collection view was not in sync with your data. That could happen if you call  `reloadData()` (from the notification handler) too late or too early.

Happy to hear that you've resolved your problem. I'm closing this issue for, feel free to create a new one if you need any further help.

**Closed by stel** 2017-03-22 11:56 UTC
Labels: T:Help
