### ISSUE TITLE
Class conforming to Codable with @Persisted properties, cannot decode null values

### ISSUE THREAD

**Issue by miklselsoe** [realm/realm-cocoa#7332] opened 2021-07-08 10:59 UTC
Trying to migrate to the new `@Persisted` property wrapper, introduced in Realm 10.10, I get an error when trying to decode an optional value with nil.

Class definition:
```swift
class Notification: Object, Codable {
	@Persisted(primaryKey: true) var _id: ObjectId
	// ...
	@Persisted var technicalInspectionDate: Date?
	// ...
}
```

When using a JSONDecoder, trying to decode to a Notification class, I get this error:

```
Swift.DecodingError.valueNotFound(Swift.Optional<Foundation.Date>, Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "technicalInspectionDate", intValue: nil)], debugDescription: "Expected Optional<Date> but found null value instead.", underlyingError: nil))
```

For reference, this is how the property is defined in JSON:

```javascript
{
	"technicalInspectionDate": null
}
```

This used to work with the property being defined as an `RealmOptional`, like this:

```swift
dynamic var technicalInspectionDate = RealmOptional<Date>()
```

## Version of Realm and Tooling
Realm framework version: 10.10.0

Xcode version: 12.5.1

iOS/OSX version: 14.6

Dependency manager + version: Carthage 0.38

**Comment by pavel-ship-it** [comment] 2021-07-08 13:52
Hi @miklselsoe 
Thank you for reporting the issue. I can reproduce it.

**Comment by tgoyne** [comment] 2021-07-08 19:28
Unsurprisingly this is the exact same but as #7323 in a different spot.

**Comment by tgoyne** [comment] 2021-07-09 15:49
This is not a duplicate of #7323.

**Closed** 2021-07-09 17:37 UTC
Labels: O-Community
