### ISSUE TITLE
Queue-confined Realm instance still crashes due to incorrect thread after 5.0.0

### ISSUE THREAD

**Issue by homathko** [realm/realm-cocoa#6583] opened 2020-06-17 18:17 UTC
After RealmSwift 5.0.0 I have been attempting to isolate the threading issues in my data layer, but still can't avoid "incorrect thread" errors even though the realm instance is being used on the correct serial dispatch queue.

## Goals
Create predictable, long-term access to one of many realm instances bound to its own dispatch queue. It isn't possible to know what thread a Realm is created on when using the asyncOpen API, so queue-confined realms have benefits.

## Expected Results
On a dedicated `DispatchQueue` and on any thread, the realm instance should be accessible without 'incorrect thread' related exceptions as specified in 5.0.0 release notes referencing [PR #6427](https://github.com/realm/realm-cocoa/pull/6427)

## Actual Results
`*** Terminating app due to uncaught exception 'RLMException', reason: 'Realm accessed from 
incorrect thread.'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23e39f0e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff50ad79b2 objc_exception_throw + 48
	2   Realm                               0x000000010259786d -[RLMRealm verifyThread] + 70
	3   Realm                               0x0000000102534699 RLMGetObjects + 80
	4   RealmSwift                          0x0000000102dbb930 $s10RealmSwift0A0V7objectsyAA7ResultsVyxGxmAA6ObjectCRbzlF + 112
	5   dal-2Tests                          0x00000001032488c0 $s10dal_2Tests15RealmThreadTestC04testC35InSameQueueButDifferentThreadsFailsyyKFyycfU0_ + 384
	6   dal-2Tests                          0x0000000103248b50 $sIeg_IeyB_TR + 48
	7   libdispatch.dylib                   0x00007fff51911951 _dispatch_call_block_and_release + 12
	8   libdispatch.dylib                   0x00007fff519128cb _dispatch_client_callout + 8
	9   libdispatch.dylib                   0x00007fff5191860c _dispatch_lane_serial_drain + 707
	10  libdispatch.dylib                   0x00007fff51919044 _dispatch_lane_invoke + 388
	11  libdispatch.dylib                   0x00007fff519230c4 _dispatch_workloop_worker_thread + 626
	12  libsystem_pthread.dylib             0x00007fff51b386fc _pthread_wqthread + 290
	13  libsystem_pthread.dylib             0x00007fff51b37827 start_wqthread + 15
)
libc++abi.dylib: terminating with uncaught exception of type NSException`

## Steps to Reproduce
Unit test code

## Code Sample
    func testRealmInSameQueueButDifferentThreadsFails () throws {
        // Thread 1 <com.apple.main-thread>
        var realm: Realm? = nil
        var semaphore = DispatchSemaphore(value: 0)

        let queue = DispatchQueue(label: "com.test.realm")

        /// Making this block synchronous is to help the test by
        /// making it highly likely that the instance will be created on Thread 1
        queue.sync {
            // Confirm: Thread 1 <com.test.realm>
            realm = try! Realm()
        }

        // Back to Thread 1 <com.apple.main-thread>

        /// Next, dispatch on the dedicated queue asynchronously to 
        /// make it likely the block will be executed on a thread 
        /// other than Thread 1
        queue.async {
            /// Thread 4 <com.test.realm>
            if let thing = realm!.objects(Thing.self).first { // <-- throws
                print("success")
            }

            semaphore.signal()
        }

        semaphore.wait()
    }

## Version of Realm and Tooling
Realm framework version: RealmSwift 5.0.3

Realm Object Server version: ?

Xcode version: 11.4.1

iOS/OSX version: 13.4

Dependency manager + version: Carthage 0.34.0

**Comment by leemaguire** [comment] 2020-06-22 13:40
Hi @homathko 

Even though you have a custom queue, you can't share the Realm between threads.

```
// Query and update from any thread
DispatchQueue(label: "background").async {
    autoreleasepool {
        let realm = try! Realm()
        let theDog = realm.objects(Dog.self).filter("age == 1").first
        try! realm.write {
            theDog!.age = 3
        }
    }
}
```

In this example the `Realm` object is created in the async block, this ensures you are always accessing a Realm bound to that thread.

I would go with this approach as you are guaranteed the Realm will be created on that thread.

**Comment by homathko** [comment] 2020-06-23 21:29
Hey there @leemaguire,

Thanks for having a look. So, does that mean that I misunderstood the release notes?

> Add support for queue-confined Realms. Rather than being bound to a specific thread, queue-confined Realms are bound to a serial dispatch queue and can be used within blocks dispatched to that queue regardless of what thread they happen to run on. In addition, change notifications will be delivered to that queue rather than the thread's run loop.

**Comment by tgoyne** [comment] 2020-06-23 21:58
You have to explicitly pass in the queue to the Realm initializer to create a Realm instance which is confined to the queue. `try! Realm()` will give you a Realm which is confined to the current thread.

**Comment by homathko** [comment] 2020-06-24 22:19
@tgoyne Okay, so I can see then how this new enhancement might only apply to the `asyncOpen` api. I had made an assumption that the only reason `queue` was required to be passed in `asyncOpen` was so that it new which queue to dispatch to on its end. 

Based on that assumption, I could create a queue-confined Realm using the "synchronous" api `try! Realm(config:)` to open a full-sync realm by simply dispatching that api command within the queue that I wanted and would keep track of (as in the code sample I provided).

Can you only get a queue-confined realm by using the `asyncOpen` api? Or am I missing something else? I would very much like to have the option of using the offline-capable `try! Realm(config:)` to create a queue-confined realm.

**Comment by tgoyne** [comment] 2020-06-24 22:22
Realm's initializer has a queue parameter in addition to the configuration parameter.

**Comment by homathko** [comment] 2020-06-25 19:56
😑😑😑😑

I was unable to locate that fact in the [Realm Class Reference](https://realm.io/docs/swift/latest/api/Classes/Realm.html#/s:10RealmSwift0A0C7fileURLAC10Foundation0D0V_tKcfc)

I was also unable to find any evidence that this form of the api is available by looking through `RealmSwift.swift`

Thanks for clearing it up, I wish that hadn't taken me so long as well as used up other's time.

**Comment by tgoyne** [comment] 2020-06-25 20:00
Oh, it looks like there's something wrong with the docs deploy to the website. It also says Realm 3.21.0 there...

**Comment by tgoyne** [comment] 2020-06-25 20:03
Oh, I see what the problem is there. Realm is now a struct, which changed the URL but the old file wasn't deleted. The [correct URL](https://realm.io/docs/swift/latest/api/Structs/Realm.html#/s:10RealmSwift0A0V13configuration5queueA2C13ConfigurationV_So012OS_dispatch_D0CSgtKcfc) shows it.

**Comment by ericjordanmossman** [comment] 2020-09-15 19:21
Closing this thread because of the solutions [here](https://github.com/realm/realm-cocoa/issues/6583#issuecomment-648449601) and [here](https://github.com/realm/realm-cocoa/issues/6583#issuecomment-649104248).
@homathko If I missed something else, feel free to comment and we can re-open.

**Closed by ericjordanmossman** 2020-09-15 19:21 UTC
Labels: O-Community
