### ISSUE TITLE
Deleting models but still seeing them in Realm database

### ISSUE THREAD

**Issue by fenroar** [realm/realm-cocoa#5561] opened 2018-01-10 14:35 UTC
## Goals
Deleting models that are no longer in use. As Realm does not delete the tables defined in the database when the models are deleted, migration is performed to delete data.

## Expected Results
Realm database should not show these models and realm should open as normal.

## Actual Results
Realm fails to open and models are deleted. Receive the following error: `Fails to open realm: Table is target of cross-table link columns`

## Steps to Reproduce
1. Defined model User which contains child models Account and Card. Defined Address model that does not contain relation with other models defined.

2. Run on simulator.

3. Delete these models and perform migration to delete data.

4. Run on simulator. Expecting database to have no tables but get a error message: `Failed to open realm: Table is target of cross-table link columns`

## Code Sample
https://github.com/fenroar/RealmMigrationExample

`master` branch contains models defined
`migration` branch deletes models defined and performs migration

## Version of Realm and Tooling

Realm framework version: 3.0.0

Xcode version: 9.0

iOS/OSX version: 11.0

Dependency manager + version: Carthage 0.23.0

**Comment by ruipfcosta** [comment] 2018-01-10 17:29
+1

**Comment by bdash** [comment] 2018-01-17 05:06
This is a duplicate of https://github.com/realm/realm-cocoa/issues/3686.

**Closed by bdash** 2018-01-17 05:06 UTC
