### ISSUE TITLE
Realm Cocoa receives access denied when using async methods with another framework

### ISSUE THREAD

**Issue by nsnick** [realm/realm-cocoa#5563] opened 2018-01-11 17:14 UTC
## Goals
I am trying to use Realm-Cocoa inside another framework.

## Expected Results
Realm-Cocoa should execute code the same way regardless of whether it is used inside another framework or directly in an app.

## Actual Results
Calling asyncOpenWithConfiguration: in a project that defines the RLMObjects in another framework causes the server to return permission denied and close the connection.  Calling asyncOpenWithConfiguration: in a project that defines the RLMObjects outside of another framework finds the objects as expected.

The error on the iOS side is as follows:

```
2018-01-11 11:28:24.992639-0500 RealmBugObjc[5560:3092816] web server url: https://realm.yodellabs.com
2018-01-11 11:28:25.879787-0500 RealmBugObjc[5560:3092816] logged in user: <RLMSyncUser: 0x1c4029c00>
2018-01-11 11:28:25.879871-0500 RealmBugObjc[5560:3092816] remoteRealmURL: realms://realm.yodellabs.com/e556ef2b8765f15529ad4ffe15a04a73/facebook
2018-01-11 11:28:26.114080-0500 RealmBugObjc[5560:3092999] Sync: Connection[1]: Connected to endpoint '2607:7700:0:22::3457:5:443' (from '2607:fb90:58b6:2817:1821:830c:faae:be28:53829')
2018-01-11 11:28:26.808248-0500 RealmBugObjc[5560:3092999] Sync: Connection[1]: Received: ERROR(error_code=206, message_size=33, try_again=0, session_ident=1)
2018-01-11 11:28:26.809621-0500 RealmBugObjc[5560:3092999] Sync: Connection[1]: Connection closed due to error reported by server: Permission denied (BIND, REFRESH) (206)
2018-01-11 11:28:26.819028-0500 RealmBugObjc[5560:3092999] Sync: Closing Realm file: /var/mobile/Containers/Data/Application/4B39BE5A-AFBD-40B3-B697-628BD2D35B5C/Documents/realm-object-server/82bcbc60-fe7b-456a-963a-d0255b54391c/realms%3A%2F%2Frealm.yodellabs.com%2Fe556ef2b8765f15529ad4ffe15a04a73%2Ffacebook
2018-01-11 11:28:26.819333-0500 RealmBugObjc[5560:3092816] returned realm: (null)
2018-01-11 11:28:26.819409-0500 RealmBugObjc[5560:3092816] Error connecting to remote realm identified by /e556ef2b8765f15529ad4ffe15a04a73/facebook: Operation canceled
```

The error on the server side appears as follows:
```
[sync] Sync Connection[7668]: Session[1]: Permission denied (message_type='upload', path='/e556ef2b8765f15529ad4ffe15a04a73/Facebook').
```

The realm should be readable by every user.  The permissions show "Public R" on the realm being tested.  The problem shows up on other synced realms as well.

## Steps to Reproduce
Run the three XCode projects below.  The first one runs as expected.  The following two get access denied errors from the realm object server despite executing the same code.  The only difference being that the second two projects define the RLMObjects in a framework.

## Code Sample
This project does not use a framework for defining RLMObjects and executes as expected.  It can be used as a reference for what should happen in the other two projects.
https://github.com/yodellabs/RealmBug-noframework

These two projects use a framework to define RLMObjects and get access denied errors when attempting to connect to the realm object server using async methods.  They should behave exactly the same as the project above but they do not.
https://github.com/yodellabs/RealmBug-objc
https://github.com/yodellabs/RealmBug-swift

This is the framework that the two projects with the bug use.  It only defines the RLMObjects.
https://github.com/yodellabs/RealmBug-ALPS-framework

## Version of Realm and Tooling
Realm framework version:  3.0.2

Realm Object Server version:  2.2.0 && 2.4.2

Xcode version: 9.2

iOS/OSX version:  iOS 11.2.1

Dependency manager + version: cocoa pods 1.2.1

**Comment by tgoyne** [comment] 2018-01-11 21:34
The linked repositories appear not to have any code other than the Xcode-generated skeleton and Podfile.

One reason you may see an access denied error when opening a Realm you have read permissions for is if your local configuration includes object types which do not exist in the Realm on the server, as it would then try to create the tables for those object types and fail when it uploads that change.

**Comment by nsnick** [comment] 2018-01-11 22:53
I am very sorry about the git repos.  They are all there now.  

The versions with the framework have exactly the same models as the one without.  Wouldn't I see the same error if both projects had the same object types?

I am seeing a new error on the swift version only:
```
2018-01-11 17:49:27.365444-0500 ALPSRealmDemo[5670:3202187] logged in user: <RLMSyncUser: 0x1c002c9c0>
2018-01-11 17:49:27.365535-0500 ALPSRealmDemo[5670:3202187] remoteRealmURL: realms://realm.yodellabs.com/e556ef2b8765f15529ad4ffe15a04a73/facebook
2018-01-11 17:49:27.583671-0500 ALPSRealmDemo[5670:3202258] Sync: Connection[1]: Connected to endpoint '2607:7700:0:22::3457:5:443' (from '2607:fb90:58b6:2817:1821:830c:faae:be28:54841')
2018-01-11 17:49:28.304865-0500 ALPSRealmDemo[5670:3202187] returned realm: <RLMRealm: 0x1c00a40e0>
2018-01-11 17:49:28.304949-0500 ALPSRealmDemo[5670:3202187] connected remote realm: <RLMRealm: 0x1c00a40e0>
2018-01-11 17:49:28.307435-0500 ALPSRealmDemo[5670:3202187] *** Terminating app due to uncaught exception 'RLMException', reason: 'Object type 'ALPSStoredBeacon' is not managed by the Realm. If using a custom `objectClasses` / `objectTypes` array in your configuration, add `ALPSStoredBeacon` to the list of `objectClasses` / `objectTypes`.'
```
That object definitely is being managed by the realm.

**Comment by tgoyne** [comment] 2018-01-12 00:23
When using Realm in both a framework and the main application, you'll need to uncomment `use_frameworks!` in all of your Podfiles. Currently you're statically linking Realm into ALPS.framework, which results in two copies of the library in your final app, and the framework uses a different one from the app itself.

After making this change and rebuilding the framework, both the objc and swift versions appear to work correctly:

2018-01-11 16:13:34.652662-0800 ALPSRealmDemo[14064:27020376] web server url: https://realm.yodellabs.com
2018-01-11 16:13:35.426568-0800 ALPSRealmDemo[14064:27020376] logged in user: <RLMSyncUser: 0x600000233de0>
2018-01-11 16:13:35.426769-0800 ALPSRealmDemo[14064:27020376] remoteRealmURL: realms://realm.yodellabs.com/e556ef2b8765f15529ad4ffe15a04a73/facebook
2018-01-11 16:13:35.695321-0800 ALPSRealmDemo[14064:27020661] Sync: Connection[1]: Connected to endpoint '52.87.0.5:443' (from '172.20.20.118:60123')
2018-01-11 16:13:37.195222-0800 ALPSRealmDemo[14064:27020376] returned realm: <RLMRealm: 0x6000000a8160>
2018-01-11 16:13:37.195389-0800 ALPSRealmDemo[14064:27020376] connected remote realm: <RLMRealm: 0x6000000a8160>
2018-01-11 16:13:37.196764-0800 ALPSRealmDemo[14064:27020376] number of beacons: 1
2018-01-11 16:13:37.197357-0800 ALPSRealmDemo[14064:27020661] Sync: Closing Realm file: /Users/tgoyne/Library/Developer/CoreSimulator/Devices/C6D5458A-95E7-4462-94E6-5CB7D8B47893/data/Containers/Data/Application/94BCD3D1-DDAF-4C53-82C8-C62906477398/Documents/realm-object-server/11f965c1-2df3-4890-8abd-e88ec4408db1/realms%3A%2F%2Frealm.yodellabs.com%2Fe556ef2b8765f15529ad4ffe15a04a73%2Ffacebook

**Comment by nsnick** [comment] 2018-01-12 18:54
I uncommented use_frameworks again and I removed a file for an object that was in the realm before and is not currently being used in the realm by the framework or the client apps and it seems to be working.  I think the models may not have been compatible.

If you want to change the object models is there a way to do it without breaking the sync?

Also, "permission denied" did not lead me to think there was an incompatibility between the local models and the realm object server.  Is there any way to get more descriptive logging on either the client device or the server that would indicate a mismatch between the models instead of a general permission denied error?

**Comment by tgoyne** [comment] 2018-01-12 19:13
That does definitely need a better error message, but it's currently not totally trivial to do. The problem is that the client currently doesn't actually know that it doesn't have write permissions until it tries to upload the changeset and gets an error, while the server logic that does permission checking doesn't look at what the changes actually are, so neither layer is able to do something sensible. Thankfully I think this problem will be solved soon as we're switching over to a permissions model that actually does inspect the changes made.

With read-write synchronized Realms you can freely add new properties and Object classes, but cannot change any existing properties. For a read-only Realm, this is still mostly true, but has the caveat that you must ensure that the new properties or types are added to the server Realm before you connect with any of the read-only clients, as otherwise the read-only clients will try and fail to do the schema initialization for those types.

**Comment by stennie** [comment] 2019-09-18 20:26
@tgoyne Can this issue be closed or are there still changes to message handling needed?

**Comment by leemaguire** [comment] 2020-06-29 13:21
Closing issue due to age. If there are any more questions please open a new issue.

Thanks,
Lee

**Closed** 2020-06-29 13:26 UTC
Labels: O-Community, Pipeline-Discussion, T-Help
