### ISSUE TITLE
Documentation should be clearer about setting logLevel prior to opening any synced Realms

### ISSUE THREAD

**Issue by einsteinx2** [realm/realm-cocoa#4734] opened 2017-03-14 21:01 UTC
## Goals

What do you want to achieve?

I want to see why my connection is not working.

## Expected Results

I expect to see detailed connection information

## Actual Results

I see the same information in the lldb console whether I set SyncManger logLevel to all or leave it as default

## Steps to Reproduce

Set the log level

## Code Sample

```
RealmSwift.SyncManager.shared.logLevel = SyncLogLevel.all
RealmSwift.SyncManager.shared.errorHandler = { error, _ in
     print("Realm error: \(error)")
}
```

Neither of the above are having any effect, and the errorHandler block is never called. I confirmed that logLevel and errorHandler are being set.

## Version of Realm and Tooling

- Realm version: v2.4.3
- Xcode version: Xcode 8.2.1 (Build version 8C1002)
- iOS/OSX version:  10.12.3
- Dependency manager + version: `/usr/local/bin/carthage`, 0.18.1

**Comment by einsteinx2** [comment] 2017-03-14 21:13
I was able to successfully set the logLevel in the OS X Realm Browser app, so it looks like this may be specific to the RealmSwift framework.

**Comment by istx25** [comment] 2017-03-14 22:48
Hi @einsteinx2. Thanks for filing this issue. I've marked this issue with `T:Help` for now but I'm going to assign this issue to one of our Cocoa engineers to evaluate what you're experiencing further and determine if a fix on our side is necessary. Cheers.

**Comment by einsteinx2** [comment] 2017-03-15 22:01
For more information, I also just tried creating an Obj-C class with a single class method to set the parameters, and calling that from my Swift AppDelegate code. It also is having no effect. I tried setting logging to off as well to be sure.

    + (void)setupRealm {
        [[RLMSyncManager sharedManager] setLogLevel:RLMSyncLogLevelAll];
        [[RLMSyncManager sharedManager] setErrorHandler:^(NSError *error, RLMSyncSession * _Nullable session) {
            NSLog(@"Realm error: %@", error);
        }];
    }

**Comment by einsteinx2** [comment] 2017-03-15 22:01
In both cases, I'm calling them in the applicationDidFinishLaunching function of my AppDelegate class.

**Comment by bdash** [comment] 2017-03-15 22:04
The most likely reason that the log level wouldn't be respected is if you're setting it after you've already opened a synced Realm. Can you check the relative order of these to operations in your app?

**Comment by einsteinx2** [comment] 2017-03-15 22:12
@bdash Yep, that was it! Looks to be working now.

In any case, that seems like a bug, no? I would expect to be able to change log levels at any time, or at the very least have the new log level take effect the next time a Realm is created. Same with the error handler.

At the very least, it's a documentation bug. There's no mention of this requirement in either the Swift logging section (which just says: "The synchronization subsystem supports a number of logging levels, useful while developing an app. These can be selected by setting the logLevel property on the SyncManager singleton to the desired verbosity") or the Realm Object Server documentation Logging section which is linked to from the Swift docs for more information (btw that link takes you to the top of the documentation rather than directly to the Logging section which made me assume at first it was a broken link until I found the section myself).

**Comment by bdash** [comment] 2017-03-15 22:21
From [the documentation for `-[RLMSyncManager logLevel]`](https://realm.io/docs/objc/latest/api/Classes/RLMSyncManager.html#/c:objc(cs)RLMSyncManager(py)logLevel) (emphasis mine):

> The logging threshold which newly opened synced Realms will use. Defaults to RLMSyncLogLevelInfo. *Set this before any synced Realms are opened*. Logging strings are output to ASL.

**Comment by einsteinx2** [comment] 2017-03-15 22:30
That's nice and all, but that's the Objective-C class reference not the Swift documentation. The likelihood of someone new to the platform, reading through the documentation at https://realm.io/docs/swift/latest/ ever finding that is slim to none.

It would be nice to add it to this section, which makes no mention of it whatsoever:

<img width="907" alt="screen shot 2017-03-15 at 5 28 20 pm" src="https://cloud.githubusercontent.com/assets/350423/23973612/de83f99e-09a4-11e7-8bb4-5367f9cab0fe.png">

**Comment by bdash** [comment] 2017-03-15 22:33
I'm mainly pointing out that:
1. It is intentional behavior, not a bug.
2. It is documented.

Your point about also mentioning it when describing how to change the logging settings is a good one.

**Comment by einsteinx2** [comment] 2017-03-15 22:36
No problem, sometimes it's hard to tell tone and intent with text :)

I do appreciate the very quick responses. So far it's turned out every issue I've had has been some misunderstanding on my end of how something works, and overall the docs are great.

**Comment by bdash** [comment] 2017-03-15 23:01
@austinzheng has submitted a PR that addresses the documentation issues you mentioned. They'll be reflected on the website when we next cut a release of Realm Cocoa.

**Closed by bdash** 2017-03-15 23:01 UTC
Labels: S:P2 Backlog, T:Doc
