### ISSUE TITLE
Richer search

### ISSUE THREAD

**Issue by kjoelbro** [realm/realm-cocoa#2261] opened 2015-07-21 12:07 UTC
When searching a string field in Realm e.g. "name CONTAINS[c] 'fæ' " I want to find all strings that contain "fæ", "fa", "fä" etc. So basically I want mapping from some special letters to basic latin letters.

**Comment by yoshyosh** [comment] 2015-07-21 16:43
Thanks for the request! We are currently tracking diacritic insensitive predicates here https://github.com/realm/realm-cocoa/issues/1490 for now can you try checking out http://nshipster.com/cfstringtransform/ to do the mapping? Hope this helps

**Comment by jpsim** [comment] 2015-07-21 16:51
@kjoelbro thanks for the feature request, we'll take this into consideration. I'm closing this issue as a duplicate of #1490, feel free to resume the conversation there.

**Closed by jpsim** 2015-07-21 16:51 UTC
