### ISSUE TITLE
Potential performance issue on Realm v5.x.x

### ISSUE THREAD

**Issue by bguidolim** [realm/realm-cocoa#6867] opened 2020-10-15 15:29 UTC
## Goals
Identify the reason for poor performance when importing a huge amount of data.

## Expected Results
Have an acceptable processing time when importing a huge amount of data.

## Actual Results
Realm has a poor performance when importing a huge amount of data.

## Steps for others to Reproduce

Inside the zip file provided below, you can find two projects, one with Realm v4 and another one with Realm v5.
Run the projects (you can use the simulator) and tap "Import data".
An anonymized data sample is attached to the projects.

## Code Sample
https://www.icloud.com/iclouddrive/0dH27gR53QZXl-5CoDn1iVi6w#Realm-Performance-Test

The difference between both projects is the v5 project is queue-confined.

## Version of Realm and Tooling

Realm framework version: 5.5.0 and 4.4.1

Realm Object Server version: N/A

Xcode version: Xcode 11.7 - 12.1

iOS/OSX version: iPhone 8 Plus - iOS 13.6.1 (reproducible using simulator too)

Dependency manager + version: SPM (code sample) - Carthage (original project)

**Comment by bguidolim** [comment] 2020-10-15 15:51
Just out of curiosity, I did run both projects using the simulator, I got the following results:

**v4.4.1:**
 - Completed in 69 seconds
 - Realm file size: 184,5 MB

**v5.5.0:**
 - Completed in 8 minutes and 39 seconds
 - Realm file size: 310,6 MB

**Comment by tgoyne** [comment] 2020-10-15 16:09
Unsurprisingly this is completely i/o bound, so the problem is that it's having to write a lot more data. That's pretty surprising, as the changes in how data is stored were supposed to *reduce* writes. Will have to look into this more...

**Comment by tgoyne** [comment] 2020-10-15 19:18
I think I see why this is so different: one of the changes in 5.x is that we now use the primary key as the clustered index key, which means that the primary key value determines the order which the objects are stored in the Realm. This means that while with 4.x the bulk insertion was only appending objects on at the end, with 5.x it's doing mid insertions that result in a lot more data having to be written for each write transaction.

Using larger batch sizes significantly mitigates this. If I skip the batches entirely then both versions take roughly the same amount of time, and v4 produces a 416 MB file while v5 produces a 213 MB file (as we mostly fixed the problems with very large transactions in v5). Note that this requires pushing the autoreleasepool in addUsers() into the loop or memory usage gets unreasonably high.

**Comment by bguidolim** [comment] 2020-10-15 19:29
@tgoyne Thanks for taking a look at it.

I've got your point.

The idea behind of creating chunks of 1000 is to let the user start working with some data already, without making them waiting for too long.

Do you see any room for improvements here or are you considering this issue as closed?

**Comment by tgoyne** [comment] 2020-10-15 19:30
I think that this big of a regression is definitely something we need to find a way improve.

**Comment by tgoyne** [comment] 2020-10-16 02:32
It appears that the first 32k rows insert at roughly the same speed as v4 and it only slows down after that, so you could perhaps do 1k batches for the first 32 and then switch to a larger batch size after that.

**Comment by bguidolim** [comment] 2020-10-16 08:00
Fortunately, we don't have too many customers with this size of data to import. As a palliative solution, I'll increase the batch size to 10k, it has acceptable performance, should be enough for now. Looking forward to a real solution provided by Realm.

Please let me know if I can help with something else.

**Comment by bguidolim** [comment] 2021-02-09 16:30
@tgoyne is there any news about this?

I started to detect this issue on our analytics, I think it could be a problem in the future.

**Comment by DaDz-eiSos** [comment] 2021-03-16 11:59
Hello everyone,

We are also having a similar problem with realm in our application cause we recently switched from v4.4.1 to the newest version v10.7.2. 

In our app we have a synchronization process in the background that imports data to realm. While with v4.x.x we chunked the import. With v5.x.x and above the process is too slow to be chunked. 

A larger problem occurs when we want to modify a realm object that is in the synchronization write transaction process. The modification of this object will be applied after the synchronization write transaction has finished. Until then the modification will not be visible for the user which leads to bad UX. 

Are there any news to this topic? Or are there any possibilities to prioritize a transaction?

Thanks and Best regards

**Comment by bguidolim** [comment] 2021-03-16 12:09
In order to work around this issue, I've removed the primary key of the object and added the identifier field as index, then instead of using `realm.object(ofType:forPrimaryKey:)`, I am now using `realm.objects(type.self).filter("id == %@", id).first`.

Now I have almost the same performance as v4. To be honest, I don't really get why the table is being sorted by primary key, it might be useful only if you use a sequential number as a key, for every other case it will only make the process slow.

**Comment by DaDz-eiSos** [comment] 2021-03-16 14:53
@bguidolim thanks for your suggestion. With this workaround it is really a lot faster with chunked write transactions.

Here are my results with about 300K of objects:
- With 1000 chunks and v4.4 -> 31 seconds
- With 1000 chunks and v10.7.2 -> 3 minutes 8 seconds
- Without chunks and v10.7.2 -> 34 seconds
- With workaround and v10.7.2 -> 90 seconds

Unfortunately we depend on the primary key and can not apply this workaround. We hope there will be a fix by Realm for this issue.

**Comment by finnschiermer** [comment] 2021-03-16 16:36
Please see https://github.com/realm/realm-core/issues/4522

**Comment by tgoyne** [comment] 2021-06-10 15:38
We've ended up reverting the change which caused this: https://github.com/realm/realm-core/pull/4708. This'll be released in Cocoa 10.8.0.

**Closed** 2021-06-21 11:04 UTC
Labels: O-Community
