### ISSUE TITLE
Compile error when using new Cocoapods flag

### ISSUE THREAD

**Issue by Heckscheibe** [realm/realm-cocoa#5718] opened 2018-04-06 11:15 UTC
## Goals

Integrate RealmSwift via Cocoapods

## Expected Results

Build runs as expected without any errors

## Actual Results

When using the new `use_modular_header!` option in the `podfile` 24 Build Errors occur, all related to castings of `Int` to `UInt` or vice versa.
http://blog.cocoapods.org/CocoaPods-1.5.0/
## Steps to Reproduce

- Remove RealmSwift and Realm from Podfile
- perform `pod install`
- add RealmSwift to Podfile
- perform `pod install`
- run a build of your project

## Version of Realm and Tooling

Realm framework version: 3.3.2

Xcode version: 9.3

iOS/OSX version: 11.3

Dependency manager + version: Cocoapods 1.5

**Comment by tgoyne** [comment] 2018-04-06 14:57
Duplicate of https://github.com/realm/realm-cocoa/issues/5663.

**Closed by tgoyne** 2018-04-06 14:57 UTC
