### ISSUE TITLE
not setting (when update) nil value for to-one relationships

### ISSUE THREAD

**Issue by sroik** [realm/realm-cocoa#5063] opened 2017-06-23 12:57 UTC
Realm version 2.8.3

Guys you have to fix `create( type:* value:* update: true)` for nil RealmOptional properties too
or for 'optional to-one relationships'

Here it is 
<img width="701" alt="screen shot 2017-06-23 at 3 51 01 pm" src="https://user-images.githubusercontent.com/7701363/27482870-cb9f9542-582b-11e7-99e9-d5120b4ab3ff.png">

Handle this pls :)

**Comment by austinzheng** [comment] 2017-06-28 16:47
Duplicate of #4926

**Closed by austinzheng** 2017-06-28 16:47 UTC
