### ISSUE TITLE
RealmSwift crash when using NSOutlineView and deleting items

### ISSUE THREAD

**Issue by duncangroenewald** [realm/realm-cocoa#6169] opened 2019-06-07 09:56 UTC
## Goals
I am trying to use a NSOutlineView with Realm objects but can't seem to find a workaround for deleting objects.  It seems no matter what I try the OutlineView seems to try and access the realm object when removing it which causes a realm exception to be thrown.

## Expected Results
I would expect to be able to delete the realm object and then trigger an update to NSOutlineView by calling reloadData() without an exception being thrown

## Actual Results
See stack trace below - it's not really clear to me why the reloadData() would crash give the object has been removed from the data source but it looks like outlineView is trying to access the object in some fashion

2019-06-07 19:46:40.548426+1000 MM[8485:1624551] [General] Object has been deleted or invalidated.
2019-06-07 19:46:40.554541+1000 MM[8485:1624551] [General] (
	0   CoreFoundation                      0x00007fff52c21cfd __exceptionPreprocess + 256
	1   libobjc.A.dylib                     0x00007fff7d2c8a17 objc_exception_throw + 48
	2   Realm                               0x00000001012d499c ___ZN12_GLOBAL__N_115makeBoxedGetterIN5realm10StringDataEEEP11objc_objectm_block_invoke + 285
	3   Foundation                          0x00007fff54dd98c5 -[NSObject(NSKeyValueCoding) valueForKey:] + 281
	4   Realm                               0x00000001012ef898 -[RLMObjectBase valueForKey:] + 85
	5   Realm                               0x00000001012f0b44 -[RLMObjectBase hash] + 145
	6   Foundation                          0x00007fff54dc2176 probeGC + 79
	7   Foundation                          0x00007fff54e0d829 -[NSConcreteMapTable removeObjectForKey:] + 53
	8   AppKit                              0x00007fff504486e9 _NSOVFreeRowEntry + 59
	9   AppKit                              0x00007fff5044864f _NSOVRecursiveFreeChildrenAndItem + 121
	10  AppKit                              0x00007fff5043c9a6 _NSOVFastRemoveChildRowEntries + 216
	11  AppKit                              0x00007fff5043c882 -[NSOutlineView reloadData] + 564

## Steps to Reproduce
I can't seem to reproduce this in a test app.

## Code Sample
```
 realm.beginWrite()
            realm.delete(item)
            
            do {
                try realm.commitWrite()
                
                self.outlineView?.reloadData()
                
            } catch {
               
            }
```

## Version of Realm and Tooling
Realm framework version: latest version 

Realm Object Server version: Na

Xcode version: 10.21

iOS/OSX version: macOS 10.14.5

Dependency manager + version: Na

**Comment by cliftonlabrum** [comment] 2019-06-28 14:53
I remember running into issues like this. The timing of `NSOutlineView` datasource events and Realm writes are fraught with peril.

Perhaps as a workaround you could perform the UI updates first, and then execute the actual Realm object deletion a short time later.

For example:
- User deletes item
- Remove the item from the `NSOutlineView`
- Dispatch the Realm object deletion 2 seconds later

Similarly, you could do a soft delete where you mark a Realm object for deletion and your Realm datasource updates because it filters out items marked as `deleted`. At some regular interval, your app deletes all Realm objects marked for deletion.

Just a thought. Good luck!

**Comment by duncangroenewald** [comment] 2019-06-29 03:48
Thats what I ended up doing - remove from the UI and then delete and in other cases a soft delete.

**Comment by stennie** [comment] 2019-09-30 04:20
Closing this issue due to no recent activity. Please comment if you have additional information that may help reproduce this issue.

**Closed by stennie** 2019-09-30 04:20 UTC
Labels: O-Community, T-Help
