### ISSUE TITLE
A first Duplicated Primary Keys Are Allowed.

### ISSUE THREAD

**Issue by owenzhao** [realm/realm-cocoa#6662] opened 2020-07-21 01:52 UTC
!!! MANDATORY TO FILL OUT !!!

## Goals

I have a Weibo Project, when adding accounts of Weibo, I noticed that the account with the same primary key was inserted instead of replaced. The realm was upgraded from Realm Cocoa 4.x to 5.x.

I had also tested with a Twitter account, the result was the same.

There was one more thing need to be concerned that only the first duplicated account was inserted. When I added the same account again, the account would be added as replaced again. There won't be a third account with the same primary key.

## Expected Results

The account with the same primary key should replace the old one instead of added as a new one.

## Actual Results

The account was not replaced but inserted.

## Version of Realm and Tooling

Realm framework version: ?
5.3.1

Realm Object Server version: ?

Xcode version: ?
11.6 (11E708)

iOS/OSX version: ?
10.15.6 (19G73)

Dependency manager + version: ?
CocoaPods 1.9.3

<img width="2738" alt="issue_screenshot" src="https://user-images.githubusercontent.com/2182896/88003009-703deb00-cb36-11ea-8c36-0c23be5cb679.png">

**Comment by owenzhao** [comment] 2020-07-21 11:49
In my own test, if I installed the app in a new device, the issue wouldn't happen. So there must be something wrong within the progress of upgrading Realm 4.x to 5.x.

**Comment by tgoyne** [comment] 2020-07-21 16:44
Can you share the Realm file which ran into problems?

**Comment by owenzhao** [comment] 2020-07-21 18:00
I have removed some sensitive data. I hope the rest is good enough for debugging.
[default.realm.zip](https://github.com/realm/realm-cocoa/files/4955329/default.realm.zip)

**Comment by tgoyne** [comment] 2020-07-21 22:56
Any chance you have a pre-upgrade copy as well? The migration code appears to have generated object ids for the objects as if the type didn't have a string primary key; the first three objects have object ids appropriate for a type with no pk, while the two newly created objects which duplicate the primary key values have the correct object ids derived from the pk. It's not obvious from the end result why this would have happened though.

It should be possible to repair a Realm which was not automatically upgraded correctly in this way by assigning each object's primary key property to itself (i.e. something like `newObj["pKey"] = oldOld["pKey"]`) inside a migration as that'll regenerate the object id.

**Comment by owenzhao** [comment] 2020-07-22 00:45
This is another Realm database. The generated Realm was 4.4.1. This was not from the same macOS of the previous database. This was from a macOS client in Parallels Desktop, which was used for app testing by myself. It only contained one account. The account was also in the previous database, the duplicated Weibo account.

[default_4.4.1.realm.zip](https://github.com/realm/realm-cocoa/files/4957174/default_4.4.1.realm.zip)

**Comment by owenzhao** [comment] 2020-07-22 00:53
I have already done a workaround for the Account saving issue. However, I have other projects with Realms too. So the best way is to fix this by Realm. My workaround code.

    // FIXME: -
    private func workAroundForRealm(account:Account) {
        let realm = try! Realm(configuration: Realm.sharedConfiguration)
        if let oldAccount = realm.object(ofType: Account.self, forPrimaryKey: account.pKey) {
            try! realm.write {
                oldAccount.name = account.name
                oldAccount.profileImageURLString = account.profileImageURLString
                oldAccount.oauthKeyAndValues.removeAll()
                oldAccount.oauthKeyAndValues.append(objectsIn: account.oauthKeyAndValues)
                oldAccount.isDefault = account.isDefault
                if account.willExpireAt != nil {
                    oldAccount.willExpireAt = account.willExpireAt
                }
            }
        } else {
            try! realm.write {
                realm.add(account)
            }
        }
    }

The previous code was very simple.

    try! realm.write {
        realm.add(account, update: .all)
    }

**Comment by tgoyne** [comment] 2020-07-22 03:52
It looks like the upgrade should have been fixed in 5.2.0. I can reproduce the incorrect result by opening the unupgraded realm with 5.1.0, but 5.2.0 gives the correct result and that version pulled in a directly relevant PR (https://github.com/realm/realm-core/pull/3786) that for some reason did not get a changelog entry mentioning the most important thing it did.

**Comment by owenzhao** [comment] 2020-07-22 09:03
According to my Podfile.lock files, my Realm upgrading history was like this (Month.Day -> Realm Version)

    7.18    ->  5.3.1
    7.15    ->  5.3
    7.1     ->  5.2
    6.27    ->  5.1
    6.11    ->  5.0.3
    6.4     ->  5.02
    5.11    ->  4.4.1

If this issue was fixed in 5.2, why I still had this issue in 5.3.1?

**Comment by DominicFrei** [comment] 2021-01-13 10:39
According to the comment in the linked issue this seems to be fine now.

Feel free to re-open and provide information if problems arise again. @owenzhao

**Closed by DominicFrei** 2021-01-13 10:39 UTC
Labels: O-Community
