### ISSUE TITLE
Module file was created by an older version of the compiler; rebuild 'RealmSwift' and try again

### ISSUE THREAD

**Issue by jgonfer** [realm/realm-cocoa#2761] opened 2015-10-29 00:22 UTC
When I build the project, I'm getting this error:

```swift
Module file was created by an older version of the compiler; rebuild 'RealmSwift' and try again
```

I've installed 'RealmSwift' 0.96.2 via CocoaPods, and I'm using Xcode 7.1 (7B91b). I've deleted all content in DerivedData, and cleaned up the project, but I'm still getting this error when I build the project.

**Comment by mrackwitz** [comment] 2015-10-29 10:52
Which version of CocoaPods do you use?
Can you make sure to use the same Xcode application path as the one which is selected for command line tools? (`sudo xcode-select --reset`)

**Comment by jgonfer** [comment] 2015-10-29 11:55
I'm using CocoaPods v0.39.0. 

I'll run your command (```swift sudo xcode-select --reset```) when I get home. I'll let you know when I have more information. Thanks Marius!

**Comment by jgonfer** [comment] 2015-10-29 14:16
I've run the command (```sudo xcode-select --reset```) but I'm still getting the same error:

![captura de pantalla 2015-10-29 a las 15 16 07](https://cloud.githubusercontent.com/assets/5473123/10820939/0ce00c2e-7e50-11e5-8266-d912f8981a8b.png)

**Comment by mrackwitz** [comment] 2015-10-30 13:44
Did you tried to clean DerivedData after that change once again?
If not, could you try to reproduce the issue in an example project you could share?

**Comment by jgonfer** [comment] 2015-11-02 07:38
I've made some changes in the project. RealmSwift for watchOS was imported manually, and for others targets it was imported by Cocoapods. Now RealmSwift is imported by Cocoapods for all the targets.

After doing this, I'm getting a different error for Realm framework when I'm archiving (but not when building):

```swift
LLVM ERROR: Symbol name entry points before beginning or past end of file.
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/dsymutil failed with exit code 1
```

![captura de pantalla 2015-11-02 a las 8 28 44](https://cloud.githubusercontent.com/assets/5473123/10876305/cb421dc2-813b-11e5-95c6-9e6092ee101e.png)

**Comment by mrackwitz** [comment] 2015-11-02 11:36
That's a new one. Never saw that before. Could you try resetting the CocoaPods cache by `rm -rf "~/Library/Caches/CocoaPods"` and run `pod install` again? Perhaps you have to run it twice then, due to #2701.
If that shouldn't help, can you try to reproduce the issue in a sample project you could share with us? (help@realm.io)

**Comment by jgonfer** [comment] 2015-11-02 21:55
I reseted the CocoaPods cache and now I'm getting this error messages:

```swift
CreateUniversalBinary /Users/jgonfer/Library/Developer/Xcode/DerivedData/B2B-dknnmkplfuhntmbjfxavlmufuiif/Build/Intermediates/ArchiveIntermediates/B2B/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/Realm.framework/Realm normal armv7\ arm64
    cd "/Users/jgonfer/Documents/iOS Projects/B2B/Pods"
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo -create /Users/jgonfer/Library/Developer/Xcode/DerivedData/B2B-dknnmkplfuhntmbjfxavlmufuiif/Build/Intermediates/ArchiveIntermediates/B2B/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/Pods-B2B\ Free-Realm.build/Objects-normal/armv7/Realm /Users/jgonfer/Library/Developer/Xcode/DerivedData/B2B-dknnmkplfuhntmbjfxavlmufuiif/Build/Intermediates/ArchiveIntermediates/B2B/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/Pods-B2B\ Free-Realm.build/Objects-normal/arm64/Realm -output /Users/jgonfer/Library/Developer/Xcode/DerivedData/B2B-dknnmkplfuhntmbjfxavlmufuiif/Build/Intermediates/ArchiveIntermediates/B2B/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/Realm.framework/Realm

error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't move temporary file: /Users/jgonfer/Library/Developer/Xcode/DerivedData/B2B-dknnmkplfuhntmbjfxavlmufuiif/Build/Intermediates/ArchiveIntermediates/B2B/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/Realm.framework/Realm to file: /Users/jgonfer/Library/Developer/Xcode/DerivedData/B2B-dknnmkplfuhntmbjfxavlmufuiif/Build/Intermediates/ArchiveIntermediates/B2B/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/Realm.framework/Realm.lipo (No such file or directory)
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo emitted errors but did not return a nonzero exit code to indicate failure
```

![captura de pantalla 2015-11-02 a las 22 51 06](https://cloud.githubusercontent.com/assets/5473123/10895397/42d669d8-81b4-11e5-8e69-96d534fadb54.png)

Could be this issue related to #3493 of CocoaPods?

I'm not sure if I'll able to reproduce the project's issue because it's a "complex" project. I'll try it.

**Comment by mrackwitz** [comment] 2015-11-02 22:04
Well, the root cause of the CocoaPods issue, you link to, should be solved through the target de-duplication. But in some scenarios, it isn't applicable, so it might still help to turn off Parallelized Builds.

**Comment by jgonfer** [comment] 2015-11-02 23:18
Parallelized Builds turned off, but now I'm getting this:

```swift
PhaseScriptExecution Embed\ Pods\ Frameworks /Users/jgonfer/Library/Developer/Xcode/DerivedData/B2B-dknnmkplfuhntmbjfxavlmufuiif/Build/Intermediates/B2B.build/Debug-iphoneos/B2B.build/Script-66BE071508E4BCA949337419.sh
    cd "/Users/jgonfer/Documents/iOS Projects/B2B"
    /bin/sh -c /Users/jgonfer/Library/Developer/Xcode/DerivedData/B2B-dknnmkplfuhntmbjfxavlmufuiif/Build/Intermediates/B2B.build/Debug-iphoneos/B2B.build/Script-66BE071508E4BCA949337419.sh

/Users/jgonfer/Library/Developer/Xcode/DerivedData/B2B-dknnmkplfuhntmbjfxavlmufuiif/Build/Intermediates/B2B.build/Debug-iphoneos/B2B.build/Script-66BE071508E4BCA949337419.sh: line 2: /Users/jgonfer/Documents/iOS Projects/B2B/Pods/Target Support Files/Pods/Pods-frameworks.sh: No such file or directory
```

![captura de pantalla 2015-11-03 a las 0 17 18](https://cloud.githubusercontent.com/assets/5473123/10897313/47899354-81c0-11e5-9b23-e4f2358a5a27.png)

I understand that this is more an issue related to CocoaPods than to Realm , isn't it?

**Comment by jpsim** [comment] 2015-11-06 00:08
@mrackwitz could this be due to the CocoaPods script bug you mentioned in another issue about not supporting paths with spaces? This project is in a path containing `iOS Projects`.

**Comment by mrackwitz** [comment] 2015-11-06 06:30
@jpsim: This could be indeed the case. Thanks for taking a second look, I was a bit stumped here. But took a second look now and tried to reproduce it, but no look with that.

@jgonfer: Did you checked manually whether the referenced file exists? If not, something must be really went wrong with your CocoaPods integration. Could you in that case report the output of `tree Pods/Target Support Files` in your project directory? Additionally you could try to use [`cocoapods-deintegrate`](https://github.com/kylef/cocoapods-deintegrate) to reset your integration to a clean state and then run `pod install` again.

**Comment by mrackwitz** [comment] 2015-12-10 16:49
As we didn't got any further info on that, I'll assume that it is resolved and close this issue. If that wasn't the case, please feel free to re-open it. Otherwise it'd be also helpful for us to get to know how you could resolve the issue.

**Closed by mrackwitz** 2015-12-10 16:49 UTC
Labels: Help

**Comment by thegreatmichael** [comment] 2016-07-09 15:53
This problem is tripping me up still. 

```
/Users/tgm/dev/project-name/ProjectName/RedactedViewController.swift:14:8: Module file was created by an older version of the compiler; rebuild 'RealmSwift' and try again: /Users/tgm/dev/project-name/RealmSwift.framework/Modules/RealmSwift.swiftmodule/arm64.swiftmodule
```

There are no spaces in my path, here's the output of `ls` (is that similar enough to `tree`?): 

```
~/dev/project-name [feature/realm-db|✚ 35⚑ 3] 
11:41 $ ls Pods/Target\ Support\ Files/
BrightFutures      Pods-ProjectName      SIOSocket          ionicons
MMDrawerController Result             Sheriff
```

**Comment by elvinaze** [comment] 2016-11-20 07:41
You probably need to delete ~/Library/Developer/Xcode/DerivedData to clear out your old build products.
