### ISSUE TITLE
Exception thrown sporadically while safely accessing a Date

### ISSUE THREAD

**Issue by bptstmlgt** [realm/realm-cocoa#6310] opened 2019-10-18 11:12 UTC
## Goals

I'm recording the time spent on a certain recipe to determine if it's been cooked. A user may come back several times on said recipe in a day (e.g. phone locks/user opens another app, and then comes back to finish cooking the recipe). Therefore, I store on the recipe the last time it was opened, to determine if I should increment the timeSpentOnRecipe counter or start from 0 (e.g. if recipe was last opened yesterday, start from scratch. If opened today, increment counter).

I determine what to do with a function, `shouldContinueMeasuringFromPastSession`, that's called on `appEnteredBackground` and `appWillEnterForeground` of the RecipeDetails VC (for the reasons said above).
This function accesses `recipe.lastOpened` (of type Date?) in a what I believe is a safe way:
`guard let lastOpened = recipe.lastOpened else { return false }`
Note that `recipe` has already been safely unwrapped at this point, and has _not_ been deleted from the realm, since the viewcontroller from which this is being called is using that recipe object since the start. If recipe was deleted, it would have crashed way earlier, and wouldn't have gone past the preceding safe unwraps. 

## Expected Results
Get the Date.

## Actual Results
Crashed once at `guard let lastOpened = recipe.**lastOpened** else { return false }`
With trace:
`#1	(null) in objc_exception_throw ()`
`#2	0x104d6d4fc in invocation function for block in objc_object* (anonymous namespace)::makeBoxedGetter<realm::Times... ()`
`#3	0x104a9f96c in specialized RecipeDetailsStore.shouldContinueMeasuringFromPastSession(_:) at /*****/RecipeDetailsStore.swift:208`

## Steps to Reproduce
Hard to reproduce. It's only happened once, even though we've been trying to reproduce it by entering foreground/background while on this specific VC.

## Version of Realm and Tooling
Realm framework version: 3.17.3

Xcode version: 11.1

iOS/OSX version: 13.1.2

Dependency manager + version: ?

Any hints?

Apologies if I didn't provide enough details, this is my first issue report. Let me know how I can improve. Thanks.

**Comment by ericjordanmossman** [comment] 2020-04-07 18:04
> Apologies if I didn't provide enough details, this is my first issue report. Let me know how I can improve. Thanks.

Thanks for a detailed report! Some things to clear up:

- If `lastOpened` is of type `Date?`, do you also give a default value when the Recipe is initialized?

- Since you reported this, has it reoccurred?

> It's only happened once

- If so, we're you able to reproduce then?

**Comment by bptstmlgt** [comment] 2020-04-07 18:12
Hey 👋

- `lastOpened` is of type `Date`, and is `nil` by default.

- it hasn't reoccurred since then 🤷‍♂️and we were not able to reproduce. I'll update if it does.

Thanks

**Comment by ericjordanmossman** [comment] 2020-04-13 16:21
@bptstmlgt Thanks for the info.

The reason I asked about default values was to just sanity check there is a value. But I see that you mentioned it's already unwrapped:

> Note that recipe has already been safely unwrapped at this point, and has not been deleted from the realm, since the viewcontroller from which this is being called is using that recipe object since the start.

If it hasn't reoccurred and this will likely need a reproduction, I'm going to close this ticket. BUT if you do catch this or the frequency increases, please feel free to re-open. :)

**Closed by ericjordanmossman** 2020-04-13 16:21 UTC
Labels: O-Community, Pipeline-Triage, Pipeline-Waiting-for-User
