### ISSUE TITLE
Indexing is broken

### ISSUE THREAD

**Issue by anlaital** [realm/realm-cocoa#1735] opened 2015-04-07 05:11 UTC
If you define an indexed property on an RLMObject other than its primary key by overriding ```+ [RLMObject indexedProperties]``` this will break indexing at some point in the future when objects are added, updated and deleted. 

The actual result of this is that RLMResults do not contain objects whose indices are broken if they are used in filtering clauses, such as [SomeRLMObject objectsWhere:@"someIndexedProperty = 'foo'"].

This is an extremely serious issue and you should probably communicate it with your users and tell them not to define indexed properties until this is fixed. We have now had several high-priority issues in production because of this failure.

I am also in possession of an encrypted database where indices are broken that can easily be used to reproduce this error. However, it will need some serious sanitation before I can send it to you guys. What is the best approach to clean up some highly sensitive data from the database before sending it to you?

**Comment by rrrlasse** [comment] 2015-04-07 12:56
Does any string contain 0-bytes in the indexed column?

**Comment by tgoyne** [comment] 2015-04-07 16:43
There shouldn't be any difference querying-wise between a primary key and a regular indexed column. The only differences are that PK columns are checked for uniqueness on insert and `objectForPrimaryKey:` hits a different codepath from other queries.

**Comment by tgoyne** [comment] 2015-04-07 16:51
The key part for sanitizing a Realm file is to use `writeCopyToPath:` at the end to get a new file with only the live data, as a Realm file will normally contain some old data that hasn't been overwritten yet. If the sensitive data isn't needed to reproduce the issue, one option would be to create a small program with your object schema but with all of the sensitive properties removed, open the Realm (with a no-op migration), and write a new copy.

**Comment by anlaital** [comment] 2015-04-07 17:55
@rrrlasse There are no 0-bytes in the strings, as they are IBANs.

@tgoyne I'll try to asterisk out the sensitive parts of the data and send you the database file along with the encryption key.

I should also note that the results are returned correctly when indexes are not hit, i.e. performing CONTAINS or BEGINSWITH on the indexed string column.

**Comment by timanglade** [comment] 2015-04-08 02:05
P.S. you can send us files to help@realm.io

**Comment by anlaital** [comment] 2015-04-08 07:04
I've sent you the minimal test project along with the encrypted database that's had its indices corrupted.

**Comment by tgoyne** [comment] 2015-04-08 20:34
The problem is that the matching row indexes for each value in the index are not kept in sorted order in `move_last_over` (i.e. when a row is deleted), and the querying code relies on them being sorted. Primary Keys of course only have one row for each value, so the row indexes can't be out of order.

Fixing the string index updating code shouldn't be difficult, but fixing any existing databases will require regenerating the index.

**Comment by anlaital** [comment] 2015-04-09 02:54
Is there support for regenerating and deleting/adding indexed properties in migrations? If your model defines multiple indexed properties by overriding ```indexedProperties``` and in a later version you remove a property returned from that method, it doesn't look like the indices are actually removed from that property even after the migration is done.

I think it would be worth clarifying in the docs how indexing is handled in these cases during migrations.

**Comment by tgoyne** [comment] 2015-04-09 14:15
I implementing removing existing indexes in the core recently, but it hasn't made it into the binding yet.

**Comment by anlaital** [comment] 2015-04-13 04:42
I performed a migration in production for users that deleted the index (i.e. not returning the property from indexedProperties anymore) and deleted all indexed objects from the Realm. This did not, however, fully remedy the issue, as queries still fail to return all objects, so I'm assuming that the property is still being indexed even though ```po```ing the object's schema says otherwise.

When will the bindings support deleting indexes and when will you fix this on the core side? You said that ```writeCopyToPath:encryptionKey``` fixes the issue, so I suppose that is the only way for me to get this fixed in production. Is ```writeCopyToPath:encryptionKey``` still broken, or can it actually be used now?

**Comment by tgoyne** [comment] 2015-04-13 18:35
All reported issues with writeCopyToPath: were fixed by 0.90.6, but it doesn't do anything relevant to this.

**Comment by timanglade** [comment] 2015-04-13 19:38
To be clear, currently there is no way in Realm to re-generate the index (or remove them). @tgoyne is adding that feature right now.
(@anlaital: I think both you & I read Thomas saying “sanitizing the Realm file” as “sanitizing the indices” when in fact he was talking about removing sensitive info :D)

**Comment by tgoyne** [comment] 2015-04-13 19:45
https://github.com/realm/realm-cocoa/pull/1755 makes it so that search indexes are actually removed from existing database files.

**Comment by anlaital** [comment] 2015-04-14 03:09
Will this work retroactively as I have already shipped a version of the app to production where the indexed property is no longer returned from ```indexedProperties``` and have also bumped the schema version up already?

**Comment by tgoyne** [comment] 2015-04-14 03:51
Realm doesn't have any "memory" of schemas; it just compares the schema of the file being opened to the schema defined by your current RLMObject subclasses, with no regard to how the file came to have the schema it does. With the current implementation in #1755, this means that it'll demand a schema version bump since the schemas don't match, and once that's done will remove the indexes from existing files even if they were last touched by a version where they shouldn't have been indexed at all.

Requiring the schema version bump isn't acceptable though (changing the notion of schema equality between versions of Realm means that someone could update their version of Realm, fail to test with any existing databases, then ship an update to their app and break all existing installs), so I need to change that.

**Comment by anlaital** [comment] 2015-04-16 05:58
When will you be doing a new release with this fix included? I'm sorry to bother you like this, but we're getting a lot of complaints from production about problems that are directly caused by this bug about our core functionality, so you can imagine that we're in a bit of a bind here...

**Comment by jpsim** [comment] 2015-04-17 01:17
A fix was just pushed to master (#1755). Thanks for your patience, @anlaital!

**Closed by jpsim** 2015-04-17 01:17 UTC
Labels: bug, P1
