### ISSUE TITLE
EXC_BAD_ACCESS RLMClassInfo::propertyForTableColumn

### ISSUE THREAD

**Issue by kharmabum** [realm/realm-cocoa#5288] opened 2017-09-07 19:29 UTC
## Goals
Avoid crash.

## Expected Results
No crash.

## Actual Results
```

Download
OS Version: iOS 10.2 (14C92)
Report Version: 104

Exception Type: EXC_BAD_ACCESS (SIGBUS)
Exception Codes: BUS_NOOP at 0x0000000000000010
Crashed Thread: 0

Application Specific Information:
Attempted to dereference garbage pointer 0x10.

Thread 0 name: 
Thread 0 Crashed:
0   Realm                           0x10097575c         RLMClassInfo::propertyForTableColumn(unsigned long) const (RLMClassInfo.mm:49)
1   Realm                           0x100986694         [inlined] RLMObservationInfo::columnName(unsigned long) const (RLMObservation.mm:104)
2   Realm                           0x100986694         RLMObservationInfo::columnName(unsigned long) const (RLMObservation.mm:104)
3   Realm                           0x100987e20         [inlined] operator()<realm::BindingContext::ColumnInfo> (RLMObservation.mm:493)
4   Realm                           0x100987e20         [inlined] forEach<(lambda at /Users/realm/workspace/create_github_release_cocoa/realm-cocoa/Realm/RLMObservation.mm:492:24)> (RLMObservation.mm:418)
5   Realm                           0x100987e20         RLMDidChange(std::__1::vector<realm::BindingContext::ObserverState, std::__1::allocator<realm::BindingContext::ObserverState> > const&, std::__1::vector<void*, std::__1::allocator<void*> > const&) (RLMObservation.mm:492)
6   Realm                           0x1009ee274         (anonymous namespace)::RLMNotificationHelper::did_change(std::__1::vector<realm::BindingContext::ObserverState, std::__1::allocator<realm::BindingContext::ObserverState> > const&, std::__1::vector<void*, std::__1::allocator<void*> > const&, bool) (RLMRealmUtil.mm:116)
7   Realm                           0x100a1c8a8         [inlined] after (transact_log_handler.cpp:193)
8   Realm                           0x100a1c8a8         [inlined] ~KVOTransactLogObserver (transact_log_handler.cpp:635)
9   Realm                           0x100a1c8a8         (anonymous namespace)::KVOTransactLogObserver::~KVOTransactLogObserver() (transact_log_handler.cpp:634)
10  Realm                           0x100a1b4a8         [inlined] advance_with_notifications<(lambda at /Users/realm/workspace/create_github_release_cocoa/realm-cocoa/Realm/ObjectStore/src/impl/transact_log_handler.cpp:698:45)> (transact_log_handler.cpp:679)
11  Realm                           0x100a1b4a8         realm::_impl::transaction::advance(std::__1::unique_ptr<realm::SharedGroup, std::__1::default_delete<realm::SharedGroup> > const&, realm::BindingContext*, realm::_impl::NotifierPackage&) (transact_log_handler.cpp:698)
12  Realm                           0x10095ab20         realm::_impl::RealmCoordinator::advance_to_ready(realm::Realm&) (realm_coordinator.cpp:781)
13  Realm                           0x100a07908         realm::Realm::notify() (shared_realm.cpp:680)
14  Realm                           0x100a28728         realm::_impl::WeakRealmNotifier::Callback::operator()() const (weak_realm_notifier.cpp:42)
15  CoreFoundation                  0x30b557b5c         __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
16  CoreFoundation                  0x30b5574a4         __CFRunLoopDoSources0
17  CoreFoundation                  0x30b5550a4         __CFRunLoopRun
18  CoreFoundation                  0x30b4832b8         CFRunLoopRunSpecific
19  GraphicsServices                0x30e9e8198         GSEventRunModal
20  UIKit                           0x3174a07fc         -[UIApplication _run]
21  UIKit                           0x31749b534         UIApplicationMain
22  orca                            0x20011010c         <redacted>
23  libdyld.dylib                   0x30944e5b8         start

Thread 1 name: com.apple.uikit.eventfetch-thread
0   libsystem_kernel.dylib          0x309639188         mach_msg_trap
1   libsystem_kernel.dylib          0x309638ff8         mach_msg
2   CoreFoundation                  0x30b5575d0         __CFRunLoopServiceMachPort
3   CoreFoundation                  0x30b5551ec         __CFRunLoopRun
4   CoreFoundation                  0x30b4832b8         CFRunLoopRunSpecific
5   Foundation                      0x30cafa26c         -[NSRunLoop(NSRunLoop) runMode:beforeDate:]
6   Foundation                      0x30cb1add0         -[NSRunLoop(NSRunLoop) runUntilDate:]
7   UIKit                           0x317e14c38         -[UIEventFetcher threadMain]
8   Foundation                      0x30cbf7e68         __NSThread__start__
9   libsystem_pthread.dylib         0x3097ff850         _pthread_body
10  libsystem_pthread.dylib         0x3097ff760         _pthread_start

Thread 2 name: 
0   libsystem_kernel.dylib          0x309657314         __semwait_signal
1   libsystem_c.dylib               0x3094a525c         nanosleep
2   libsystem_c.dylib               0x30950f288         sleep
3   Sentry                          0x1008c2554         monitorCachedData (KSCrashCachedData.c:148)
4   libsystem_pthread.dylib         0x3097ff850         _pthread_body
5   libsystem_pthread.dylib         0x3097ff760         _pthread_start

Thread 3 name: KSCrash Exception Handler (Secondary)
0   libsystem_kernel.dylib          0x309639188         mach_msg_trap
1   libsystem_kernel.dylib          0x309638ff8         mach_msg
2   Sentry                          0x1008cfa74         handleExceptions (KSCrashMonitor_MachException.c:281)
3   libsystem_pthread.dylib         0x3097ff850         _pthread_body
4   libsystem_pthread.dylib         0x3097ff760         _pthread_start

Thread 5 name: AVAudioSession Notify Thread
0   libsystem_kernel.dylib          0x309639188         mach_msg_trap
1   libsystem_kernel.dylib          0x309638ff8         mach_msg
2   CoreFoundation                  0x30b5575d0         __CFRunLoopServiceMachPort
3   CoreFoundation                  0x30b5551ec         __CFRunLoopRun
4   CoreFoundation                  0x30b4832b8         CFRunLoopRunSpecific
5   AVFAudio                        0x33ebe5d24         GenericRunLoopThread::Entry(void*)
6   AVFAudio                        0x33ec0bd9c         CAPThread::Entry(CAPThread*)
7   libsystem_pthread.dylib         0x3097ff850         _pthread_body
8   libsystem_pthread.dylib         0x3097ff760         _pthread_start

Thread 6 name: com.apple.NSURLConnectionLoader
0   libsystem_kernel.dylib          0x3096578e8         __ulock_wait
1   libdispatch.dylib               0x3093fe0c4         _dispatch_ulock_wait
2   libdispatch.dylib               0x3093fe1ec         _dispatch_thread_event_wait_slow
3   libdispatch.dylib               0x3093fbdb8         _dispatch_barrier_sync_f_slow
4   CFNetwork                       0x30c481e14         TCPIOConnection::setConnectionEstablishmentDelegate_offqueue(std::__1::shared_ptr<TCPIOConnection::ConnectionEstablishmentDelegate>&)
5   CFNetwork                       0x30c415230         HTTPProtocol::useNetStreamInfoForRequest(MetaNetStreamInfo*, HTTPRequestMessage const*, unsigned char)
6   CFNetwork                       0x30c3ff3e0         HTTP2ConnectionCacheEntry::enqueueRequestForProtocol(MetaConnectionCacheClient*, HTTPRequestMessage const*, MetaConnectionOptions)
7   CFNetwork                       0x30c50cd08         HTTP2ConnectionCache::enqueueRequestForProtocol(MetaConnectionCacheClient*, HTTPRequestMessage const*, MetaConnectionOptions)
8   CFNetwork                       0x30c3db12c         TubeManager::_onqueue_enqueueRequestForProtocol(MetaConnectionCacheClient*, HTTPRequestMessage const*, MetaConnectionOptions, BaseAwaitingTube*)
9   CFNetwork                       0x30c3dafa0         ___ZN11TubeManager25enqueueRequestForProtocolEP25MetaConnectionCacheClientPK18HTTPRequestMessage21MetaConnectionOptions_block_invoke
10  CFNetwork                       0x30c3daf38         TubeManager::enqueueRequestForProtocol(MetaConnectionCacheClient*, HTTPRequestMessage const*, MetaConnectionOptions)
11  CFNetwork                       0x30c34cec0         GlueTubeManager::enqueueRequestForProtocol(MetaConnectionCacheClient*, HTTPRequestMessage const*, MetaConnectionOptions)
12  CFNetwork                       0x30c2df110         ___ZN12XTubeManager25enqueueRequestForProtocolEP25MetaConnectionCacheClientPK18HTTPRequestMessage21MetaConnectionOptionsPK17CoreSchedulingSet_block_invoke
13  CFNetwork                       0x30c2df044         XTubeManager::withTubeManager(CoreSchedulingSet const*, void ( block_pointer)(GlueTubeManager*))
14  CFNetwork                       0x30c2dd3d0         -[__NSURLSessionLocal _withConnectionCache_enqueueRequest:forProtocol:scheduling:options:]
15  CFNetwork                       0x30c4148fc         HTTPProtocol::asynchronouslyCreateAndOpenStream_WithMessage_AfterCookiesAndAuthenticatorHeaders(__CFHTTPMessage*)
16  CFNetwork                       0x30c4140bc         HTTPProtocol::asynchronouslyAddAuthenticatorHeadersAndContinue(__CFHTTPMessage*)
17  CFNetwork                       0x30c41600c         ___ZN12HTTPProtocol35asynchronouslyAddCookiesAndContinueEP15__CFHTTPMessage_block_invoke_3
18  libdispatch.dylib               0x3093eb1bc         _dispatch_client_callout
19  libdispatch.dylib               0x3093f6ab0         _dispatch_block_invoke_direct
20  CFNetwork                       0x30c5122a8         RunloopBlockContext::_invoke_block(void const*, void*)
21  CoreFoundation                  0x30b482c18         CFArrayApplyFunction
22  CFNetwork                       0x30c51218c         RunloopBlockContext::perform()
23  CFNetwork                       0x30c5134b4         MultiplexerSource::perform()
24  CFNetwork                       0x30c513220         MultiplexerSource::_perform(void*)
25  CoreFoundation                  0x30b557b5c         __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
26  CoreFoundation                  0x30b5574a4         __CFRunLoopDoSources0
27  CoreFoundation                  0x30b5550a4         __CFRunLoopRun
28  CoreFoundation                  0x30b4832b8         CFRunLoopRunSpecific
29  CFNetwork                       0x30c3b78f0         +[NSURLConnection(Loader) _resourceLoadLoop:]
30  Foundation                      0x30cbf7e68         __NSThread__start__
31  libsystem_pthread.dylib         0x3097ff850         _pthread_body
32  libsystem_pthread.dylib         0x3097ff760         _pthread_start

Thread 7 name: RLMRealm notification listener
0   Realm                           0x100b2c56c         realm::LinkView::~LinkView()
1   libc++.1.dylib                  0x308a7eb5c         std::__1::__shared_weak_count::__release_shared()
2   Realm                           0x10093db64         [inlined] ~shared_ptr (memory:4605)
3   Realm                           0x10093db64         [inlined] ~shared_ptr (memory:4603)
4   Realm                           0x10093db64         [inlined] operator() (collection_notifier.cpp:119)
5   Realm                           0x10093db64         [inlined] any_of<std::__1::__wrap_iter<const realm::_impl::DeepChangeChecker::OutgoingLink *>, (lambda at /Users/realm/workspace/create_github_release_cocoa/realm-cocoa/Realm/ObjectStore/src/impl/collection_notifier.cpp:101:34)> (algorithm:827)
6   Realm                           0x10093db64         realm::_impl::DeepChangeChecker::check_outgoing_links(unsigned long, realm::Table const&, unsigned long, unsigned long) (collection_notifier.cpp:121)
7   Realm                           0x10093dca8         realm::_impl::DeepChangeChecker::check_row(realm::Table const&, unsigned long, unsigned long) (collection_notifier.cpp:144)
8   Realm                           0x10093dac8         [inlined] operator() (collection_notifier.cpp:115)
9   Realm                           0x10093dac8         [inlined] any_of<std::__1::__wrap_iter<const realm::_impl::DeepChangeChecker::OutgoingLink *>, (lambda at /Users/realm/workspace/create_github_release_cocoa/realm-cocoa/Realm/ObjectStore/src/impl/collection_notifier.cpp:101:34)> (algorithm:827)
10  Realm                           0x10093dac8         realm::_impl::DeepChangeChecker::check_outgoing_links(unsigned long, realm::Table const&, unsigned long, unsigned long) (collection_notifier.cpp:121)
11  Realm                           0x10093dca8         realm::_impl::DeepChangeChecker::check_row(realm::Table const&, unsigned long, unsigned long) (collection_notifier.cpp:144)
12  Realm                           0x10093dd54         realm::_impl::DeepChangeChecker::operator()(unsigned long) (collection_notifier.cpp:154)
13  Realm                           0x100937184         std::__1::function<bool (unsigned long)>::operator()(unsigned long) const (functional:1817)
14  Realm                           0x100936824         realm::_impl::CollectionChangeBuilder::calculate(std::__1::vector<unsigned long, std::__1::allocator<unsigned long> > const&, std::__1::vector<unsigned long, std::__1::allocator<unsigned long> > const&, std::__1::function<bool (unsigned long)>, realm::u... (collection_change_builder.cpp:831)
15  Realm                           0x100966084         realm::_impl::ResultsNotifier::calculate_changes() (results_notifier.cpp:132)
16  Realm                           0x1009665ec         realm::_impl::ResultsNotifier::run() (results_notifier.cpp:160)
17  Realm                           0x100959f24         realm::_impl::RealmCoordinator::run_async_notifiers() (realm_coordinator.cpp:730)
18  Realm                           0x1009598d0         realm::_impl::RealmCoordinator::on_change() (realm_coordinator.cpp:512)
19  Realm                           0x1009421f4         realm::_impl::ExternalCommitHelper::listen() (external_commit_helper.cpp:217)
20  Realm                           0x100942e20         [inlined] operator() (external_commit_helper.cpp:159)
21  Realm                           0x100942e20         [inlined] __invoke<(lambda at /Users/realm/workspace/create_github_release_cocoa/realm-cocoa/Realm/ObjectStore/src/impl/apple/external_commit_helper.cpp:157:47)> (__functional_base:416)
22  Realm                           0x100942e20         [inlined] __execute<> (future:2348)
23  Realm                           0x100942e20         std::__1::__async_func<realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0>::operator()() (future:2341)
24  Realm                           0x100942da8         std::__1::__async_assoc_state<void, std::__1::__async_func<realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0> >::__execute() (future:1031)
25  Realm                           0x100942f6c         [inlined] __invoke<void (std::__1::__async_assoc_state<void, std::__1::__async_func<(lambda at /Users/realm/workspace/create_github_release_cocoa/realm-cocoa/Realm/ObjectStore/src/impl/apple/external_commit_helper.cpp:157:47)> >::*)(), std::__1::__async_assoc_sta... (__functional_base:383)
26  Realm                           0x100942f6c         [inlined] __thread_execute<void (std::__1::__async_assoc_state<void, std::__1::__async_func<(lambda at /Users/realm/workspace/create_github_release_cocoa/realm-cocoa/Realm/ObjectStore/src/impl/apple/external_commit_helper.cpp:157:47)> >::*)(), std::__1::__async_a... (thread:347)
27  Realm                           0x100942f6c         void* std::__1::__thread_proxy<std::__1::tuple<void (std::__1::__async_assoc_state<void, std::__1::__async_func<realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0> >::*)(), std::__1::__async_assoc_state<void, ... (thread:357)
28  libsystem_pthread.dylib         0x3097ff850         _pthread_body
29  libsystem_pthread.dylib         0x3097ff760         _pthread_start

Thread 8 name: com.apple.CFStream.LegacyThread
0   libsystem_kernel.dylib          0x309639188         mach_msg_trap
1   libsystem_kernel.dylib          0x309638ff8         mach_msg
2   CoreFoundation                  0x30b5575d0         __CFRunLoopServiceMachPort
3   CoreFoundation                  0x30b5551ec         __CFRunLoopRun
4   CoreFoundation                  0x30b4832b8         CFRunLoopRunSpecific
5   CoreFoundation                  0x30b5650ec         _legacyStreamRunLoop_workThread
6   libsystem_pthread.dylib         0x3097ff850         _pthread_body
7   libsystem_pthread.dylib         0x3097ff760         _pthread_start

Thread 9 name: com.apple.CFSocket.private
0   libsystem_kernel.dylib          0x30965723c         select$DARWIN_EXTSN
1   CoreFoundation                  0x30b55e468         __CFSocketManager
2   libsystem_pthread.dylib         0x3097ff850         _pthread_body
3   libsystem_pthread.dylib         0x3097ff760         _pthread_start

Thread 10 name: com.apple.CoreMotion.MotionThread
0   libsystem_kernel.dylib          0x309639188         mach_msg_trap
1   libsystem_kernel.dylib          0x309638ff8         mach_msg
2   CoreFoundation                  0x30b5575d0         __CFRunLoopServiceMachPort
3   CoreFoundation                  0x30b5551ec         __CFRunLoopRun
4   CoreFoundation                  0x30b4832b8         CFRunLoopRunSpecific
5   CoreFoundation                  0x30b4d0b44         CFRunLoopRun
6   CoreMotion                      0x3191a4120         CLStartStopAdvertisingBeacon
7   libsystem_pthread.dylib         0x3097ff850         _pthread_body
8   libsystem_pthread.dylib         0x3097ff760         _pthread_start

Thread 11 name: 
0   libsystem_kernel.dylib          0x3096569fc         msync
1   Realm                           0x100a942d4         realm::util::msync(void*, unsigned long)
2   Realm                           0x100b4f6c4         realm::GroupWriter::commit(unsigned long)
3   Realm                           0x100b4bde8         realm::SharedGroup::low_level_commit(unsigned long long)
4   Realm                           0x100b4b948         realm::SharedGroup::do_commit()
5   Realm                           0x100b4c0ec         realm::SharedGroup::commit_and_continue_as_read()
6   Realm                           0x1009592b4         realm::_impl::RealmCoordinator::commit_write(realm::Realm&) (realm_coordinator.cpp:397)
7   Realm                           0x100a071a0         realm::Realm::commit_transaction() (shared_realm.cpp:563)
8   Realm                           0x1009e97e8         -[RLMRealm commitWriteTransactionWithoutNotifying:error:] (RLMRealm.mm:564)
9   RealmSwift                      0x1011355b4         specialized Realm.commitWrite(withoutNotifying : [RLMNotificationToken]) throws -> () (Realm.swift:214)
10  RealmSwift                      0x101133658         [inlined] commitWrite
11  RealmSwift                      0x101133658         Realm.write(() throws -> ()) throws -> () (Realm.swift:160)
12  orca                            0x200495b64         <redacted>
13  orca                            0x200492654         <redacted>
14  libswiftObjectiveC.dylib        0x10197d6b4         autoreleasepool<A> (invoking : () throws -> A) throws -> A (__hidden#70_:188)
15  orca                            0x200152aa0         <redacted>
16  orca                            0x20014f20c         <redacted>
17  orca                            0x200445304         <redacted>
18  libdispatch.dylib               0x3093eb1fc         _dispatch_call_block_and_release
19  libdispatch.dylib               0x3093eb1bc         _dispatch_client_callout
20  libdispatch.dylib               0x3093f93dc         _dispatch_queue_serial_drain
21  libdispatch.dylib               0x3093ee9a4         _dispatch_queue_invoke
22  libdispatch.dylib               0x3093fb34c         _dispatch_root_queue_drain
23  libdispatch.dylib               0x3093fb0ac         _dispatch_worker_thread3
24  libsystem_pthread.dylib         0x3097fd2a0         _pthread_wqthread

Thread 12 name: 
0   libsystem_pthread.dylib         0x3097fcd88         start_wqthread

Thread 13 name: 
0   libsystem_kernel.dylib          0x3096391dc         semaphore_timedwait_trap
1   libdispatch.dylib               0x3093fd770         _dispatch_semaphore_wait_slow
2   libdispatch.dylib               0x3093fc808         _dispatch_worker_thread
3   libsystem_pthread.dylib         0x3097ff850         _pthread_body
4   libsystem_pthread.dylib         0x3097ff760         _pthread_start

Thread 14 name: 
0   Foundation                      0x30cb08de8         NSKeyValuePopPendingNotificationLocal
1   Foundation                      0x30cb08c14         [inlined] NSKeyValueDidChange
2   Foundation                      0x30cb08c14         NSKeyValueDidChange
3   Foundation                      0x30cbc0224         -[NSObject(NSKeyValueObservingPrivate) _changeValueForKeys:count:maybeOldValuesDict:usingBlock:]
4   Foundation                      0x30cb08220         -[NSObject(NSKeyValueObservingPrivate) _changeValueForKey:key:key:usingBlock:]
5   Foundation                      0x30cb08170         -[__NSOperationInternal _start:]
6   Foundation                      0x30cbd535c         __NSOQSchedule_f
7   libdispatch.dylib               0x3093eb1bc         _dispatch_client_callout
8   libdispatch.dylib               0x3093f93dc         _dispatch_queue_serial_drain
9   libdispatch.dylib               0x3093ee9a4         _dispatch_queue_invoke
10  libdispatch.dylib               0x3093fb34c         _dispatch_root_queue_drain
11  libdispatch.dylib               0x3093fb0ac         _dispatch_worker_thread3
12  libsystem_pthread.dylib         0x3097fd2a0         _pthread_wqthread

Thread 15 name: 
0   libsystem_pthread.dylib         0x3097fcd88         start_wqthread

Thread 16 name: 
0   libsystem_pthread.dylib         0x3097fcd88         start_wqthread

Thread 17 name: 
0   libsystem_kernel.dylib          0x3096391dc         semaphore_timedwait_trap
1   libdispatch.dylib               0x3093fd770         _dispatch_semaphore_wait_slow
2   CoreLocation                    0x31b6c3358         CLClientInvalidate
3   CoreLocation                    0x31b6c8474         CLClientGetCapabilities
4   CoreLocation                    0x31b6c8274         CLClientGetCapabilities
5   CoreLocation                    0x31b713fc0         CLClientCreateIso6709Notation
6   CoreLocation                    0x31b710608         CLClientCreateIso6709Notation
7   CoreLocation                    0x31b710528         CLClientCreateIso6709Notation
8   CoreLocation                    0x31b711be0         CLClientCreateIso6709Notation
9   libxpc.dylib                    0x3098798f4         _xpc_connection_call_event_handler
10  libxpc.dylib                    0x3098773e8         _xpc_connection_mach_event
11  libdispatch.dylib               0x3093eb28c         _dispatch_client_callout4
12  libdispatch.dylib               0x3093eed80         _dispatch_mach_msg_invoke
13  libdispatch.dylib               0x3093f9210         _dispatch_queue_serial_drain
14  libdispatch.dylib               0x3093ee1e0         _dispatch_mach_invoke
15  libdispatch.dylib               0x3093f9210         _dispatch_queue_serial_drain
16  libdispatch.dylib               0x3093ee9a4         _dispatch_queue_invoke
17  libdispatch.dylib               0x3093f9210         _dispatch_queue_serial_drain
18  libdispatch.dylib               0x3093ee9a4         _dispatch_queue_invoke
19  libdispatch.dylib               0x3093fa26c         _dispatch_root_queue_drain_deferred_item
20  libdispatch.dylib               0x309400af8         _dispatch_kevent_worker_thread
21  libsystem_pthread.dylib         0x3097fd14c         _pthread_wqthread

Thread 18 name: 
0   libsystem_pthread.dylib         0x3097fcd88         start_wqthread

Thread 19 name: 
0   libsystem_kernel.dylib          0x309639560         posix_madvise
1   libsystem_malloc.dylib          0x3096ea904         free_small
2   libswiftFoundation.dylib        0x1017ecd2c         _DataStorage.__deallocating_deinit
3   orca                            0x200498f88         <redacted>
4   orca                            0x200110e10         <redacted>
5   Starscream                      0x10101b950         specialized WebSocket.((processResponse in _E91840E7069A0D2D302D042308E9D928)(WebSocket.WSResponse) -> Bool).(closure #1) (WebSocket.swift:819)
6   Starscream                      0x10101d264         partial apply for WebSocket.((processResponse in _E91840E7069A0D2D302D042308E9D928)(WebSocket.WSResponse) -> Bool).(closure #1)
7   libdispatch.dylib               0x3093eb1fc         _dispatch_call_block_and_release
8   libdispatch.dylib               0x3093eb1bc         _dispatch_client_callout
9   libdispatch.dylib               0x3093f93dc         _dispatch_queue_serial_drain
10  libdispatch.dylib               0x3093ee9a4         _dispatch_queue_invoke
11  libdispatch.dylib               0x3093fb34c         _dispatch_root_queue_drain
12  libdispatch.dylib               0x3093fb0ac         _dispatch_worker_thread3
13  libsystem_pthread.dylib         0x3097fd2a0         _pthread_wqthread

Thread 20 name: 
0   libsystem_pthread.dylib         0x3097fcd88         start_wqthread

Thread 21 name: 
0   libsystem_kernel.dylib          0x309657a88         __workq_kernreturn
1   libsystem_pthread.dylib         0x3097fd344         _pthread_wqthread

Thread 22 name: 
0   libsystem_kernel.dylib          0x309657a88         __workq_kernreturn
1   libsystem_pthread.dylib         0x3097fd344         _pthread_wqthread

Thread 23 name: 
0   libsystem_kernel.dylib          0x309657a88         __workq_kernreturn
1   libsystem_pthread.dylib         0x3097fd344         _pthread_wqthread

Thread 24 name: 
0   libsystem_kernel.dylib          0x309657a88         __workq_kernreturn
1   libsystem_pthread.dylib         0x3097fd344         _pthread_wqthread

Thread 25 name: 
0   libsystem_kernel.dylib          0x309657a88         __workq_kernreturn
1   libsystem_pthread.dylib         0x3097fd344         _pthread_wqthread

Thread 26 name: 
0   libsystem_kernel.dylib          0x309657a88         __workq_kernreturn
1   libsystem_pthread.dylib         0x3097fd344         _pthread_wqthread

Thread 27 name: 
0   libsystem_kernel.dylib          0x309657a88         __workq_kernreturn
1   libsystem_pthread.dylib         0x3097fd344         _pthread_wqthread

Thread 28 name: 
0   libsystem_kernel.dylib          0x309657a88         __workq_kernreturn
1   libsystem_pthread.dylib         0x3097fd344         _pthread_wqthread

Thread 29 name: 
0   libsystem_kernel.dylib          0x309657a88         __workq_kernreturn
1   libsystem_pthread.dylib         0x3097fd344         _pthread_wqthread

Thread 30 name: 
0   libsystem_pthread.dylib         0x3097fcd88         start_wqthread

Thread 31 name: 
0   libsystem_kernel.dylib          0x309657a88         __workq_kernreturn
1   libsystem_pthread.dylib         0x3097fd344         _pthread_wqthread

Thread 32 name: 
0   libsystem_kernel.dylib          0x309657a88         __workq_kernreturn
1   libsystem_pthread.dylib         0x3097fd344         _pthread_wqthread

Thread 33 name: 
0   libsystem_kernel.dylib          0x309657a88         __workq_kernreturn
1   libsystem_pthread.dylib         0x3097fd344         _pthread_wqthread

Thread 34 name: 
0   libsystem_kernel.dylib          0x309657a88         __workq_kernreturn
1   libsystem_pthread.dylib         0x3097fd344         _pthread_wqthread

Thread 35 name: 
0   libsystem_kernel.dylib          0x309657a88         __workq_kernreturn
1   libsystem_pthread.dylib         0x3097fd344         _pthread_wqthread

Thread 36 name: 
0   libsystem_kernel.dylib          0x309657a88         __workq_kernreturn
1   libsystem_pthread.dylib         0x3097fd344         _pthread_wqthread



EOF
```

## Steps to Reproduce
Not available.

## Code Sample
Not available.

## Version of Realm and Tooling

Realm framework version: v2.10.0
Xcode version: 8.3.3
iOS/OSX version: 10.2
Dependency manager + version: Carthage 0.24.0

**Comment by austinzheng** [comment] 2017-09-15 19:26
Thanks for reporting this. Can you send us a reproduction case so we can investigate further?

**Comment by kharmabum** [comment] 2017-09-16 21:31
Not able to reliably reproduce unfortunately.

**Comment by austinzheng** [comment] 2017-11-08 19:37
Since this is a 2.10.* issue and there's no repro case, I'm closing this ticket. If you run into this issue with Realm 3.*, please feel free to open a new ticket.

**Closed by austinzheng** 2017-11-08 19:37 UTC
Labels: T:Bug-Crash
