### ISSUE TITLE
Describe inheritance support and its limitations

### ISSUE THREAD

**Issue by mrackwitz** [realm/realm-cocoa#3040] opened 2015-12-25 16:12 UTC
As long as #1109 is still outstanding, we should describe the limitations in our documentation and also have the proposed workarounds in our documentation as well. It would likely also very helpful if we would describe how class inheritances are mapped to tables in the model.

**Comment by jpsim** [comment] 2016-01-07 01:39
Closing as duplicate of #1722.

**Closed by jpsim** 2016-01-07 01:39 UTC
Labels: docs
