### ISSUE TITLE
Assertion failed: backlink_ndx != not_found

### ISSUE THREAD

**Issue by tspecht** [realm/realm-cocoa#1553] opened 2015-02-26 15:14 UTC
Hey, while calling removeAllObjects I'm facing the following error leaving the app being unable to start anymore.

```
column_backlink.cpp:120: Assertion failed: backlink_ndx != not_found
0   MyApplication                            0x005dca1b _ZN7tightdb4util9terminateEPKcS2_l + 394
1   MyApplication                            0x00646573 _ZN7tightdb14ColumnBackLink19remove_one_backlinkEmm + 654
2   MyApplication                            0x00666925 _ZN7tightdb8LinkView8do_clearEb + 256
3   MyApplication                            0x006665ad _ZN7tightdb8LinkView5clearEv + 172
4   MyApplication                            0x0054cc01 -[RLMArrayLinkView removeAllObjects] + 40
5   MyApplication                            0x000be147 +[MyObject myMethod:inRealm:] + 4534
6   MyApplication                            0x00168e33 __64-[MyOtherObject myOtherMethod:]_block_invoke_2 + 758
7   MyApplication                            0x0059671b -[RLMRealm transactionWithBlock:] + 146
8   MyApplication                            0x00168a9b __64-[MyOtherObject myOtherMethod:]_block_invoke + 518
9   MyApplication                            0x00169979 __64-[MyOtherObject myOtherMethod:]_block_invoke_2690 + 116
10  MyApplication                            0x003da33b __48-[BFTask continueWithExecutor:withSuccessBlock:]_block_invoke + 294
11  MyApplication                            0x003d9a5d __41-[BFTask continueWithExecutor:withBlock:]_block_invoke_2 + 128
12  libdispatch.dylib                   0x013fa9db _dispatch_call_block_and_release + 10
13  libdispatch.dylib                   0x014047c5 _dispatch_root_queue_drain + 976
14  libdispatch.dylib                   0x01405891 _dispatch_worker_thread3 + 100
15  libsystem_pthread.dylib             0x36718e31 _pthread_wqthread + 668
16  libsystem_pthread.dylib             0x36718b84 start_wqthread + 8
IMPORTANT: if you see this error, please send this log to help@realm.io.
```

**Comment by segiddins** [comment] 2015-02-26 18:27
@tspecht, thanks so much for sharing the stack trace with us. Any reproducible projects will help us a lot. to track down why this is happening. Feel free to send to help@realm.io to keep things private.

**Comment by segiddins** [comment] 2015-03-24 22:45
@tspecht, just following up on my earlier request for a reproducible Xcode project? If the issue is fixed in the most recent release of Realm, feel free to close the issue.

**Comment by segiddins** [comment] 2015-03-31 23:05
Feel free to reopen the issue if you manage to come up with a reproduction case.

**Closed** 2015-03-31 23:05 UTC
