### ISSUE TITLE
Realm lost observe notification when cascade deleting is made it on entity

### ISSUE THREAD

**Issue by karlesct** [realm/realm-cocoa#6940] opened 2020-11-16 07:35 UTC
## Goals

My issue happens when I try to replace whole sequence of objects with new sequence. What I do is get all objects from DB and deleteing them from DB and then I add new array of the same type of objects. The issue is if I delete the whole sequence and add new transaction the notification seems to break, it doesn't trigger for the operation. 

I separate the delete and add it into different write transaction then everyting seams to work but y get two notifications. Am I mission something?

I test the same implementation with realm 3.20 and it works as expected, and 5.1 seams that doesn't work.

Thanks for the help you can give me.

## Expected Results

The expected result is the possibility of deleting the items from the database in cascade without losing notifications. 

## Actual Results

The notifications that the item has changed are lost

## Steps for others to Reproduce

The current result is that the items are deleted from the database, when you fill it again the notifications are lost, but the new items are in the database.

## Code Sample

Implementation of save

```swift 
public func save<S: Sequence>(collection: S, update: Bool, clear: Bool) -> Observable<Void> where S.Iterator.Element == E {
    do {
        let store: Realm = try Realm(with: this.configuration)
        try store.write {
            if clear {
                    store.delete(objects, cascading: true)
                }
                store.add(objects, update: update ? .all : .error)
        }
    }
}

```

This implmentation seams don't lose notifications but we lose the new order of the items. And I get two notifications

```swift 
public func save<S: Sequence>(collection: S, update: Bool, clear: Bool) -> Observable<Void> where S.Iterator.Element == E {
        return self.operation { (store: Realm, observer: AnyObserver<Void>) -> Disposable in
            let objects: Results<E> = store.objects(E.self)

            if clear {
                _ = self.write(in: store, observer: observer, completion: {
                    store.delete(objects, cascading: true)
                })
            }
            
            return self.write(in: store, observer: observer, completion: {
                store.add(collection, update: update)
                print("Collection: ")
                print(collection)
                print("---------------")
            })
        }
    }

```

Notification changes

```swift
...
let token: NotificationToken = objects.observe { (changes: RealmCollectionChange<Results>) -> Void in
            switch changes {
            case let .initial(elements):
                observer.onNext((elements.get(offset, limit: limit), nil))
            case let .update(elements, deletions, insertions, modifications):
                observer.onNext((elements.get(offset, limit: limit), Changeset(deleted: deletions, inserted: insertions, updated: modifications, offset: offset, limit: limit)))
            case let .error(error):
                observer.onError(RepositoryError.storeFailed(reason: .collectionObserverFailed(error: error)))
            }
        }
...
```

Implementation of cascade deleting

```Swift
internal protocol CascadingDeletable: RealmSwift.Object {
    static var propertiesToCascadeDelete: [String] { get }
}

private extension Realm {
    private func cascadeDelete(_ entity: RLMObjectBase) {
        guard let entity = entity as? Object else { return }
        var toBeDeleted = Set<RLMObjectBase>()
        toBeDeleted.insert(entity)
        while !toBeDeleted.isEmpty {
            guard let element = toBeDeleted.removeFirst() as? Object, !element.isInvalidated else { continue }
            self.resolve(element: element, toBeDeleted: &toBeDeleted)
        }
    }
    private func resolve(element: Object, toBeDeleted: inout Set<RLMObjectBase>) {
        element.objectSchema.properties.forEach {
            guard let value = element.value(forKey: $0.name) else { return }
            if let entity = value as? RLMObjectBase {
                toBeDeleted.insert(entity)
            } else if let list = value as? RealmSwift.ListBase {
                for index in 0 ..< list._rlmArray.count {
                    // swiftlint:disable:next force_cast
                    toBeDeleted.insert(list._rlmArray.object(at: index) as! RLMObjectBase)
                }
            }
        }
        self.delete(element)
    }
}
```

## Version of Realm and Tooling

Realm framework version: 10.1.2

Realm Object Server version: N/A

Xcode version: 12.1

iOS/OSX version: 14.1

Dependency manager + version: CocoaPods 1.10.0

**Comment by jsflax** [comment] 2020-11-19 14:40
Could you try upgrading to 10.1.4 and seeing if the issue still occurs? Let us know if that works otherwise we can work to reproduce on our end.

**Comment by karlesct** [comment] 2020-11-23 11:30
Yes, even updating to version 10.1.4 I still experience the same behavior.

Sorry for the delay in answering, it was impossible for me to test this version until today.

**Comment by pavel-ship-it** [comment] 2021-01-22 13:18
Hi @karlesct,
That's not very clear to me how what you doing with the collection here. But there is a little trick with how to handle deletion notification. 
Could you please refer this thread on our forum [RealmSwift.changesetPublisher(object)](https://developer.mongodb.com/community/forums/t/realmswift-changesetpublisher-object/12393) maybe it will give you some ideas on how to organise deletion observation.

**Comment by pavel-ship-it** [comment] 2021-05-21 16:27
Hi @karlesct,
I cannot reproduce the issue with the available information. Can you share anything else regarding this issue? Can you try to reproduce it on Realm 10.7.6?

**Comment by tgoyne** [comment] 2021-11-08 18:13
In the bit of observation code you gave it looks like you're storing the token returned from `observe()` in a local variable. If that's the case, the token will go out of scope before any notifications are ever sent, which removes the observation.

**Closed** 2021-12-09 22:07 UTC
Labels: Reproduction-Required, O-Community
