### ISSUE TITLE
Any way to get old object data on modification notification?

### ISSUE THREAD

**Issue by asjesset** [realm/realm-cocoa#3893] opened 2016-07-19 21:05 UTC
Is there any way to get the old object data on a modification notification? I am really not wanting to cache all the old data so I can tell how it changed.

My specific use-case is determining if a modification notification makes a element move from one uitableview section to another.

**Comment by jpsim** [comment] 2016-07-20 21:17
Hi @asjesset, we're tracking adding this functionality as #3520. We're also tracking exposing moves more explicitly in #3571.

Alternatively, you could use KVO if the collection you're observing is an RLMArray or a List, which would provide the old/new objects. See our [docs on KVO](https://realm.io/docs/objc/latest/#key-value-observation) for more information.

I'm closing this as a duplicate of #3520 & #3571. Please subscribe to those issues for any updates in this area.

**Closed by jpsim** 2016-07-20 21:17 UTC
Labels: T:Duplicate
