### ISSUE TITLE
carthage --use-xcframework doesn't work for arm64 simulator

### ISSUE THREAD

**Issue by kodok1988** [realm/realm-cocoa#7386] opened 2021-08-10 08:04 UTC
**Bugs**

1) Prebuild frameworks files doesn't contain dSYM folder
2) Carthage support xcframework and arm64-simulator. but excluded architecture still remain. 
I think the commit https://github.com/realm/realm-cocoa/commit/7a812029d05890f35501dcbcb00f346ac196a7d9 was missed in merge process.

## Goals
Support Carthage with xcframework 

## Expected Results
Carthage/Build/RealmSwift.xcframework contains:
- ios-arm64_armv7
- ios-arm64_x86_64-maccatalyst
- **ios-arm64_i386_x86_64-simulator**

## Actual Results
- ios-arm64_armv7
- ios-arm64_x86_64-maccatalyst
- **ios-i386_x86_64-simulator**

## Steps for others to Reproduce
just add realm-cocoa to Cartfile and run Carthage update

## Code Sample
no code

## Version of Realm and Tooling
Realm framework version: ?
v10.12.0

Xcode version: ?
12.5.1

iOS/OSX version: ?
14.5

Dependency manager + version: ?
Carthage 0.38.0

**Comment by pavel-ship-it** [comment] 2021-08-11 10:07
@kodok1988 , thank you for submitting the issue. This is a duplicate of #7151

**Closed by pavel-ship-it** 2021-08-11 10:07 UTC
Labels: O-Community
