### ISSUE TITLE
Request for Apple Silicon Binaries (v5.5.0 and V4.4.1)

### ISSUE THREAD

**Issue by duncangroenewald** [realm/realm-cocoa#6932] opened 2020-11-13 05:50 UTC
## Goals
Run native on Apple Silicon

## Expected Results
We are still experiencing random crashes with v5.5.0 but v4.4.1 has proven to be extremely stable.

Testing on Apple Silicon DTK shows a significant performance increase and we would like to release a production version of the application using Realm Cloud on Apple Silicon to showcase the performance improvements of the new hardware. 

In order to do this we would need binary builds for Xcode 12 that support Arm64 and x86.  In the longer term we aim to migrate to Mongo Realm and RealmSwift v10.

**Comment by pavel-ship-it** [comment] 2020-11-13 14:13
@duncangroenewald ,
This is basically a duplicate of your previous question. I'll close it.
You can find more information in the Ian's answer here #6929

**Closed by pavel-ship-it** 2020-11-13 14:13 UTC
Labels: O-Community

**Comment by duncangroenewald** [comment] 2020-11-14 05:08
@pavel-ship-it - and now both issues are closed without any satisfactory answer!  

As far as I am aware it is not possible to download and build the Realm Cloud sync versions from the repo.  Yes we can already build RealmSwift standalone version from the repo but we are running with Realm Cloud sync.

Is the client sync component source code available somewhere  or did I miss something ?

**Comment by ianpward** [comment] 2020-11-14 16:07
@duncangroenewald Please open a ticket via the support portal and we can route you appropriately there. The github is generally for open source users of Realm, ie. without Realm Sync.
