### ISSUE TITLE
Reversed LinkingObjects cannot get realm update notification

### ISSUE THREAD

**Issue by liuxuan30** [realm/realm-cocoa#7185] opened 2021-03-22 02:50 UTC
I had another question not sure if it's bug or by design (get another question about realm update in https://github.com/realm/realm-cocoa/issues/7184)

So the schema is same as #7184: I have a Shelf Object type and Item Object:
```swift
    fileprivate let ShelfPrimaryKey = "shelfName"
    class Shelf: Object {
        @objc dynamic private var shelfName: String!
        private let rlmItems = List<Item>()
    
        private override init() {
            super.init()
        }
    
        private init(name: String) {
            super.init()
            shelfName = name
        }
    
        override static func primaryKey() -> String? {
            return ShelfPrimaryKey
        }
    }

    fileprivate let ItemPrimaryKey = "itemName"
    fileprivate let LinkingObjectsReverseKey = "rlmItems"
    class RealmItem: Object {
        @objc dynamic private var itemName: String!
        private let reversedShelves = LinkingObjects(fromType: RealmShelf.self, property: LinkingObjectsReverseKey)
    
        @objc dynamic internal var itemIdealShelf: RealmShelf?
        @objc dynamic internal var itemShelf: RealmShelf? { return reversedShelves.first }
        override static func primaryKey() -> String? {
            return ItemPrimaryKey
        }
    }
```
This is how I add them into Realm:
```swift
    func writeItem(itemName: String, shelfName: String) {
        writeQueue.async {
            autoreleasepool {
                do {
                    let realm = try Realm()
                    let item = RealmItem.getRealmItem(itemName, in: realm)
                    let targetShelf = RealmShelf.getRealmShelf(shelfName, in: realm)
                    try realm.write {
                        if let currentShelf = item.itemShelf {
                            if currentShelf != targetShelf {
                                currentShelf.removeItem(item)
                                targetShelf.add(item)
                            }
                        } else {
                            targetShelf.add(item)
                        }
                        // realm.add(item, update: .modified)  <-- not work still
                        realm.add(targetShelf, update: .modified)
                    }
                }
                catch {
                    logger.error("Failed to write Realm")
                }
            }
        }
    }
```
**Both shelf and item use its name as primary key**

I notice that during test, if the item's shelf is changed, 
e.g. `writeItem(itemName: "pizza", shelfName: "hot")` -> `writeItem(itemName: "pizza", shelfName: "cold")`

I have a item list:
>private var rlmItems: Results<RealmItem>?
and obverser:
```swift
        token = rlmItems?.observe { [weak self] changes in
            if let tableView = self?.itemTableView {
                switch changes {
                case .initial(_):
                    logger.debug("realm get initial notifications, reloading table view...")
                    tableView.reloadData()
                case .update(_, let deletions, let insertions, let modifications):
                    logger.debug("realm get updates, updating tablew view...")
                    logger.debug("insertions \(insertions)")
                    logger.debug("modifications \(modifications)")
                    // Query results have changed, so apply them to the UITableView
                    // TODO: update is not getting  called 
                    tableView.reloadData()

                case .error(let error):
                    logger.error("realm receives \(error)")
                }
            }
        }
```
it seems that, when the shelf is updated, and the item name is not changed, I cannot get a `.update` notify on the item list, even I manually add `realm.add(item, update: .modified)`. So I want to ask is this expected behavior?

because for
>`private let reversedShelves = LinkingObjects(fromType: RealmShelf.self, property: LinkingObjectsReverseKey)`

I assume this LinkingObjects will be updated as well, so I should get a update notify on item, even I don't call `realm.add(item, update: .modified)`

Thanks advance.

**Comment by liuxuan30** [comment] 2021-03-22 03:38
also got a UT:
```swift
    func testItemNotify() {
        var e1 = XCTestExpectation(description: "should be called on .update")

        let items = realm.objects(RealmItem.self)

        RealmOrderManager.sharedManager.writeItem(itemName: "Pizza", shelfName: "HOT")

        // writeItem() is in another serial queue
        // make sure write finished, or we will get the object in current thread too quick
        var barrier = XCTestExpectation()
        testQueue.asyncAfter(deadline: .now() + 1) {
            barrier.fulfill()
        }
        wait(for: [barrier], timeout: UTTimeout)
        XCTAssertEqual(items.first?.shelf.name, .hot)
        
        let token = items.observe { changes in
            switch changes {
            case .initial(_):
                logger.debug("realm initial \(String(describing: items.first))")
            case .update(_, let deletions, let insertions, let modifications):
                logger.debug("realm update delete: \(deletions), insert: \(insertions), modify: \(modifications)")
                e1.fulfill()
            default:
                break
            }
        }

        RealmOrderManager.sharedManager.writeItem(itemName: "Pizza", shelfName: "COLD")

        // writeItem() is in another serial queue
        // make sure write finished, or we will get the object in current thread too quick
        barrier = XCTestExpectation()
        testQueue.asyncAfter(deadline: .now() + 1) {
            barrier.fulfill()
        }
        wait(for: [e1, barrier], timeout: UTTimeout)

        XCTAssertEqual(items.first?.shelf.name, .cold)
        token.invalidate()
    }
```
currently the UT will fail at `wait(for: [e1, barrier], timeout: UTTimeout)` because cannot get an update call on item

**Comment by dianaafanador3** [comment] 2021-03-23 10:33
Duplicate of #7184

**Closed** 2021-03-23 10:36 UTC
Labels: O-Community
