### ISSUE TITLE
Cant filter list of primitives

### ISSUE THREAD

**Issue by RikvanderLinde** [realm/realm-cocoa#5575] opened 2018-01-16 14:37 UTC
## Goals

Filter a list of strings stored in realm.

## Expected Results

To get a result where the filter is applied

## Actual Results

uncaught exception 'Invalid value', reason: 'Expected object of type (null) for property 'dossierTypes' on object of type 'Activity', but received: general'
## Steps to Reproduce

Declare a List<String>(), and try applying a filter.

## Code Sample

```
class Activity: Object
{
	var dossierTypes = List<String>()
}
```

```
let rlm = RealmHandler.openRealm()
let results = rlm.objects(--------.self).filter("ID = '\(-----)'").first!.activityList
if filterBy == "general"
{
	filtered = results.filter("%@ IN dossierTypes", filterBy)
}
```

## Version of Realm and Tooling

Realm framework version: 3.0.1

Realm Object Server version: ?

Xcode version: 9C40b

iOS/OSX version: iOS 11.2.2

Dependency manager + version: ?

**Comment by bdash** [comment] 2018-01-16 17:16
Duplicate of https://github.com/realm/realm-cocoa/issues/5334.

**Closed by bdash** 2018-01-16 17:16 UTC
