### ISSUE TITLE
Missing limit and offset feature

### ISSUE THREAD

**Issue by kwojtaszek** [realm/realm-cocoa#947] opened 2014-09-30 22:16 UTC
Really great work so for on realm database for iOS, I was looking through documentation and it's really cool.

What I miss is limit/offset functionality for querying to make paging easy. I don't see it anywhere in documentation and think that it would be useful for big datasets.

**Comment by timanglade** [comment] 2015-04-28 20:33
Closing as a duplicate of #1580

**Closed by timanglade** 2015-04-28 20:33 UTC
Labels: blocked, enhancement, P2
