### ISSUE TITLE
try Realm(configuration:) causes non-systematic crashes

### ISSUE THREAD

**Issue by mauro-crr** [realm/realm-cocoa#7285] opened 2021-06-14 11:05 UTC
Hi, with RealmSwift '5.4.4' we're facing a random **crash** due to Realm init method.

## Goals
A solution for this crash

[report this crash to realm.zip](https://github.com/realm/realm-cocoa/files/6647814/report.this.crash.to.realm.zip)

## Expected Results
When instantiated, after app is launched, Realm init method should not cause the termination of the app 

## Actual Results
stack trace of a crash attached

## Steps for others to Reproduce
This crash seems to be random, or at least non systematic, so it's hard to reproduce

## Code Sample
Stacktrace & img attached

## Version of Realm and Tooling

Realm framework version: RealmSwift '5.4.4'
Xcode version: 12.x
iOS/OSX version: > 11.0
Dependency manager + version: CocoaPods 1.9.3

**Comment by dianaafanador3** [comment] 2021-06-14 11:27
Hi @mauro-crr, thanks for reporting this. We'll check the stack trace and let you if we can reproduce this issue. 
One question though, Can you upgrade to latest version of RealmSwift https://github.com/realm/realm-cocoa/releases/tag/v10.7.7?

**Comment by mauro-crr** [comment] 2021-06-14 13:02
Hi @dianaafanador3 thanks for your reply. Unfortunately, at the moment, I can't upgrade to the latest version (as the project is not personal).

**Comment by dianaafanador3** [comment] 2021-06-14 13:32
@mauro-crr Can you provide any code on how you are initialising the Realm?

**Comment by mauro-crr** [comment] 2021-06-14 15:00
Sure, here you are the code.

```swift
        let configuration = Realm.Configuration(
            fileURL: documentsDir.appendingPathComponent("\(self.realmFileName).realm"),
            encryptionKey: realmKey,
            schemaVersion: 1,
            migrationBlock: { _, _ in },
            shouldCompactOnLaunch: { _, _ in
                let shouldFileBeCompacted: Bool = self.compactRealmNextTime
                self.compactRealmNextTime = false
                return shouldFileBeCompacted
            }
        )
       
        do {
            return try Realm(configuration: configuration)
        } catch {
            throw CustomError.realmCreationError(error)
        }
```

**Comment by dianaafanador3** [comment] 2021-06-14 17:24
@mauro-crr Are you getting the same crash if you force `shouldCompactOnLaunch` to return false?

**Comment by dianaafanador3** [comment] 2021-06-18 11:50
Hi @mauro-crr I would recommend to update to the latest SDK release, some of this crashes has already been fixed on new version of the SDK. 
There are several things that can be the cause of this issue, if you can provide a sample code reproducing it, or maybe more info of the user actions before the crash, that will be great and will help us to fix it.

**Comment by mauro-crr** [comment] 2021-06-22 08:29
Thanks @dianaafanador3. We will update to the latest SDK release as soon as possible. If we recognize some pattern or some specific action causing the crash, I'll keep you informed.

**Comment by dianaafanador3** [comment] 2021-08-16 14:40
Hi @mauro-crr, I'm gonna close this issue if you are still getting this error after the update we can open it back.

**Closed by dianaafanador3** 2021-08-16 14:40 UTC
Labels: O-Community
