### ISSUE TITLE
Realm 10.0 breaks the debugger in the host app

### ISSUE THREAD

**Issue by miklselsoe** [realm/realm-cocoa#6837] opened 2020-10-06 11:11 UTC
## Goals
Debug my app while using Realm 10.0 RC 1

## Expected Results
Being able to print out object descriptions in the debugger

## Actual Results
When printing description of any object in the console, this error (and nothing else) is printed:

```
(lldb) po view
error: virtual filesystem overlay file '/Users/realm/workspace/cocoa-pipeline/DerivedData/Build/Intermediates.noindex/Realm.build/Release-iphonesimulator/RealmSwift.build/all-product-headers.yaml' not found

error: couldn't IRGen expression. Please check the above error messages for possible root causes.
```

This happens even in files that have nothing to do with Realm and that doesn't reference Realm. I have tried clean build, deleting derived data and rebooting my Mac. Other debugger commands works.

Peter Steinberger has a blog post about this error message that might be helpful:
https://steipete.com/posts/couldnt-irgen-expression/

## Steps for others to Reproduce
Not entirely sure, but I updated from Realm 10.0 Beta 5 to Realm 10 RC1 through Carthage and after that the problem occured. A colleague pulled the changes after I updated Realm does not experience the issue though.

## Version of Realm and Tooling
```
ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H2

/Applications/Xcode.app/Contents/Developer
Xcode 12.0.1
Build version 12A7300

/usr/local/bin/pod
1.9.3
(not in use here)

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin19)

/usr/local/bin/carthage
0.36.0
github "realm/realm-cocoa" "v10.0.0-rc.1"

/usr/bin/git
git version 2.24.3 (Apple Git-128)
```

**Comment by pavel-ship-it** [comment] 2020-10-08 09:38
Hi @miklselsoe ,
Unfortunately I cannot reproduce this issue too.
Did you try the workaround from the post you've mentioned here? Does it work for you?

**Comment by miklselsoe** [comment] 2020-10-08 13:52
Yes. Adding an empty Objective-C file to the project fixes the issue for me.

**Comment by leemaguire** [comment] 2020-11-02 11:46
Closing as this doesn't appear to be a Realm specific issue.

**Closed by leemaguire** 2020-11-02 11:46 UTC
Labels: O-Community
