### ISSUE TITLE
Realm issue: Use of unimplemented initialiser 'init(realm:schema:)' for class Storyboard

### ISSUE THREAD

**Issue by rameez-leftshift** [realm/realm-cocoa#3185] opened 2016-02-08 13:26 UTC
Following is the code snippet of my class:

```swift
public class StoryBoard: Object, Deserializable {
    public dynamic var status: Status?

    required public init() {
        status = Status()
        super.init()
    }

    required public init(data: [String: AnyObject]) {
        let new_id: Int = data["id"]! as! Int
        id =  "\(new_id)"
        super.init()
    }

    public class func fromJSON(data: [String : AnyObject]) -> StoryBoard? {
        return StoryBoard(data: data)
    }
}
```

I'm using swift version 2.1.1 and realm version 0.97.1. I have tried using the convenience initilaizer but couldn't resolve the issue. Thank you in advance. Also updated to 0.98.0, but the app still crashes.

**Comment by kishikawakatsumi** [comment] 2016-02-09 13:42
@rameez-leftshift Can you try to define convenience initializer instead overriding initializer? Like the following.

```swift
public class StoryBoard: Object {
    public dynamic var status: Status? = Status()

    convenience public init(data: [String: AnyObject]) { // Define convenience initializer
        let new_id: Int = data["id"]! as! Int
        id =  "\(new_id)"
        self.init() // Call self.init(), not super.init()
    }

    public class func fromJSON(data: [String : AnyObject]) -> StoryBoard? {
        return StoryBoard(data: data)
    }
}
```

Overriding initializer can work if you also implement `init(realm:schema:)`. But we don't recommend override `required init()` due to Swift's limitation.

See more details: https://github.com/realm/realm-cocoa/issues/1849#issuecomment-99547742

**Comment by rameez-leftshift** [comment] 2016-02-10 11:05
He i was able to get it work by removing the required public init and making the one with data params a convenience initialiser. Sorry forgot to update here have been busy off late.

**Comment by mrackwitz** [comment] 2016-03-03 16:46
Nice, thanks for taking the time to update us here. So I guess, we can close this now. :)

**Comment by rameez-leftshift** [comment] 2016-03-04 06:11
Yup sure. Thanks for the help appreciate it :)

**Comment by adamstener** [comment] 2016-03-09 15:14
I'm not able to get this working using just a convenience initializer.  If I only have a conv init, when I call self.init(), it expects the parameters to be filled in for the convenience init.

`//MARK: - Initialization
    convenience public init(myString: String) {
        let components: NSDateComponents = NSDateComponents()
        components.setValue(-UserConstants.Values.DefaultAge, forComponent: NSCalendarUnit.Year);
        let date: NSDate = NSDate()
        birthDate = NSCalendar.currentCalendar().dateByAddingComponents(components, toDate: date, options: NSCalendarOptions(rawValue: 0))!
        self.init()
    }
`

Error: Missing argument for parameter 'myString' in call

**Comment by mrackwitz** [comment] 2016-03-09 15:23
@adamstener: That's odd. That's not how they are supposed to work. Which Swift version are you using? Did you made a fresh clean build after changing your model to just one convenience initializer?

**Comment by adamstener** [comment] 2016-03-09 15:25
I'm not on any betas, using the most current 'stable' version of Xcode and Swift, yes a clean does nothing.

**Comment by adamstener** [comment] 2016-03-09 15:29
I see, so the issue is that I have to define some other type of initializer if I want my property to be non optional, and defined in an init.  If I define a default value that means I no longer require the value to filled in an init, then it works fine.  But if the var declaration just has a type, meaning it needs to be initialized in an init method, then just having a convenience method doesn't work.

**Comment by adamstener** [comment] 2016-03-09 15:32
That being said, I still don't have resolution on the end issue.  The OP had an error thrown that I am also seeing, because I would like to not have a default value for my property.  I would like to initialize the property in an init method, but that init method does not require any parameters.

**Comment by adamstener** [comment] 2016-03-09 15:33
If I do this

>     required public init() {
>         let components: NSDateComponents = NSDateComponents()
>         components.setValue(-UserConstants.Values.DefaultAge, forComponent: NSCalendarUnit.Year);
>         let date: NSDate = NSDate()
>         birthDate = NSCalendar.currentCalendar().dateByAddingComponents(components, toDate: date, options: NSCalendarOptions(rawValue: 0))!
>         super.init()
>     }

Then I get the OP original error at times.

**Comment by mrackwitz** [comment] 2016-03-09 15:46
When you don't set default values for a property in class, you must make sure that all required (/ necessary) initializers are re-defined in that class, because otherwise these inherited initializes wouldn't initialize this new property correctly, because they have no knowledge of it. So you would need to implement the initializer as seen in the error in your class as well. But that is using private types, which are not available in `RealmSwift.framework` and only available in `Realm.framework`. #2514 gives some further pointers why we try to avoid declaring that initializer as well as `required` and so letting the compiler enforce what is failing for you here.

**Closed by mrackwitz** 2016-03-09 15:46 UTC
Labels: T:Help

**Comment by adamstener** [comment] 2016-03-09 15:50
So this is closed as impossible for now?  All values in objects must have default values?

**Comment by mrackwitz** [comment] 2016-03-09 15:53
Yes, I closed this as we keep recommending using convenience initializers and default values. Sorry for these limitations, but I don't see how we could make this scenario more convenient without putting up burden in the more common cases.
