### ISSUE TITLE
java.lang.IllegalStateException  Cannot create asynchronous query while in a write transaction in /home/cc/repo/realm/release/realm/realm-library/src/main/cpp/io_realm_internal_Collection.cpp line 310

### ISSUE THREAD

**Issue by youlongsam** [realm/realm-cocoa#6023] opened 2018-11-27 06:34 UTC
mMusicRealmModuleRealmResults = mRealm.where(MusicRealmModule.class).equalTo(TYPENAME, mExtraTypeName).findAllAsync();
        mMusicRealmModuleRealmResults.addChangeListener((results) -> {
            // do something
        });

**Comment by stennie** [comment] 2019-09-29 22:16
This is a duplicate of https://github.com/realm/realm-java/issues/5771.

**Closed by stennie** 2019-09-29 22:16 UTC
Labels: O-Community, T-Duplicate
