### ISSUE TITLE
Realm lexical or preprocessor 'RLMAccessor.h' file not found  Objective C

### ISSUE THREAD

**Issue by manzoorShaikh** [realm/realm-cocoa#1940] opened 2015-05-14 15:56 UTC
Here is my `Podfile` content

```ruby
pod 'Realm', '~> 0.92.3'
pod 'AFNetworking', '~> 2.5'
pod 'ComponentKit', '~> 0.11'

target 'Plugd' do

end

target 'PlugdTests' do
   pod 'Realm/Headers'
end
```

**Comment by segiddins** [comment] 2015-05-15 18:29
@manzoorShaikh, can you try running the following commands to force CocoaPods to re-download Realm?

```
rm -r Pods/Realm*
rm -r ~/Library/Caches/CocoaPods/Pods/Release/Realm*
pod install
```

**Comment by XBeg9** [comment] 2015-05-19 14:51
+1 same for me @segiddins

**Comment by orschaef** [comment] 2015-05-20 14:50
Same here with a Swift project. Having this "file not found" issue for every Realm file.

**Comment by segiddins** [comment] 2015-05-22 16:31
Can either of you please share a project with us that reproduces the issue, as we've been unable to reproduce it ourselves? Thanks!

**Comment by michaelloistl** [comment] 2015-05-27 06:32
That happens for me only when I update the pod to 0.92.4. Going back to 0.92.3 fixes the issue for me.
````pod 'Realm', '0.92.3'```` ````pod install````

**Comment by jpsim** [comment] 2015-05-27 16:12
@michaelloistl that's surprising, since no changes were made to the podspec between `0.92.3` and `0.92.4`. Could you try running `COCOAPODS_SKIP_CACHE=1 pod install`?

**Comment by michaelloistl** [comment] 2015-05-30 09:17
@jpsim same issue when running ````COCOAPODS_SKIP_CACHE=1 pod install````.
Have also installed CocoaPods 0.37.2 which doesn't make any difference.
Going back to 0.92.3 still fixes the issue for me. ````pod 'Realm', '0.92.3'```` ````pod install````

**Comment by jpsim** [comment] 2015-05-31 03:25
Then I suggest you file an issue with CocoaPods because there were no changes in our podspec between those versions.

**Comment by michaelloistl** [comment] 2015-05-31 06:47
Don't understand how that would be related to Cocoapods. If you haven't made any changes to the pod file, why does it work when going back to 0.92.3 but doesn't work when going to 0.92.4. It can switch back and forth and it's consistent.

**Comment by michaelloistl** [comment] 2015-05-31 07:19
Updated to ````0.93.1````. So whatever you did, it fixed that issue for me :)

**Comment by jpsim** [comment] 2015-05-31 10:19
Again, no changes to the podspec in any of those versions you're mentioning.

**Comment by michaelloistl** [comment] 2015-05-31 10:20
Interesting...

**Comment by segiddins** [comment] 2015-06-01 05:02
This is almost certainly a CocoaPods issue, but unfortunately, without reliable reproduction steps, the CocoaPods team won't really be able to track this down either.
I'm going to close this issue for now, but feel free to keep us posted.

**Closed by segiddins** 2015-06-01 05:02 UTC

**Comment by carlos90g** [comment] 2018-02-23 19:33
pod cache clean Realm
pod cache clean RealmSwift
pod deintegrate || rm -rf Pods
pod install --verbose
