### ISSUE TITLE
Encrypting realm db is causing the app to crash

### ISSUE THREAD

**Issue by raulzito234** [realm/realm-cocoa#2812] opened 2015-11-06 16:46 UTC
Whenever I try to encrypt the realm db I'm getting a crash on iOs. I'm getting the following error:

```
Fatal Exception: RLMException
Realm at path `` already opened with different encryption key
```

I've already had a realm db on the same phone before trying to encrypt the db. I have also tried to run a migration with new schema but nothing worked.

**Comment by jpsim** [comment] 2015-11-06 18:15
This is actually the intended behavior. You can't convert an unencrypted Realm to use encryption while you're still accessing it, because encrypting a Realm has to rewrite every single block of the file on disk to be encrypted (which is kind of the point).

Since Realm memory maps the database file, allowing to change the encryption key on a file while accessing it would cause some bad accesses.

So you're best off either encrypting the file at the very start of your application life cycle, or copying the Realm file to a new location with a new encryption key and using that new file if you must encrypt a file late in your app's life cycle.

**Comment by TimOliver** [comment] 2015-11-12 04:32
Hi @raulzito234! I hope that answered your question!

Since this looks resolved, I'm closing the issue now. If you have additional questions, please feel free to re-open it! :)

**Closed by TimOliver** 2015-11-12 04:32 UTC
Labels: Help, pending
