### ISSUE TITLE
'impl/async_query.hpp' file not found

### ISSUE THREAD

**Issue by VVJason** [realm/realm-cocoa#3246] opened 2016-02-22 02:33 UTC
CocoaPod  0.39.0,  "'impl/async_query.hpp' file not found"???

**Comment by bawn** [comment] 2016-02-22 06:35
+1

**Comment by mrackwitz** [comment] 2016-02-22 12:22
I guess, that's happening since our latest release? Can you show the contents of your Podfile(.lock) regarding Realm?

**Comment by vahotm** [comment] 2016-02-22 14:38
@mrackwitz, right you are. I can show my Podfile.lock.

```
PODS:
  - Realm (0.98.2):
    - Realm/Headers (= 0.98.2)
  - Realm+JSON (0.2.14):
    - Realm (~> 0.95)
  - Realm/Headers (0.98.2)

DEPENDENCIES:
  - Realm
  - Realm+JSON (~> 0.2)

SPEC CHECKSUMS:
  Realm: 88a147fe04b8f07191a676b15c779b2b448991de
  Realm+JSON: 39bef066156e589b209a14e5f2d68754793f8843

COCOAPODS: 0.39.0
```

**Comment by bawn** [comment] 2016-02-22 14:40
@mrackwitz I solved the problem, I found to be due to network problems

**Comment by vahotm** [comment] 2016-02-22 14:44
@bawn well, how can your answer help other people to solve this problem?

**Comment by mrackwitz** [comment] 2016-02-22 14:45
@bawn: Thanks for reporting back.
From this answer, it seems like this is a duplicate of #2713. Please see the workarounds proposed there.
@vahotm: May network restrictions apply to you as well?

**Comment by bawn** [comment] 2016-02-22 14:49
@mrackwitz @vahotm 

I think the reason is because I am in China, when I updated reaml waited a long time, and then I found I force close problems caused by the update, I think you can try to clear the cache.

```
rm -rf "${HOME}/Library/Caches/CocoaPods"
rm -rf "`pwd`/Pods/"
pod update
```

**Comment by vahotm** [comment] 2016-02-22 15:32
@mrackwitz, I think no, because I'm in Belarus.
@bawn, thanks, that helped)

**Comment by mrackwitz** [comment] 2016-02-22 20:40
@bawn @vahotm: Great, thanks for leaving that here.
But pay attention `pod update` doesn't take the `Podfile.lock` into account and can integrate different versions than `pod install`. I'd recommend to run `pod install --verbose`, when there was a network issue on a previous run. This will make sure that you see at least some hint what's gone wrong, which would give us some first hints what went wrong. I updated the linked issue as well with said instructions.
I'm going to close this issue now, but feel free to comment on it again, whenever it appears again and you're unable to resolve it with given instructions.

**Closed by mrackwitz** 2016-02-22 20:40 UTC
Labels: T:Help
