### ISSUE TITLE
Filter numeric properties by prefix

### ISSUE THREAD

**Issue by peterpaulis** [realm/realm-cocoa#2980] opened 2015-12-10 15:49 UTC
in CD you can use .stringValue to treat a NSNumber like a NSString... that is quite handy, if you want to search for the BEGINSWITH which corresponds to a user search

<pre>
RLMResults * filteredCompounds = [allCompounds objectsWithPredicate:[NSPredicate predicateWithFormat:@"referenceNumber.stringValue BEGINSWITH[c] %@", text]];
</pre>

unfortunately i didn't found a way how to predicate objects, which number values start with a given number

In realm when using referenceNumber.stringValue i get

<pre>
*** Terminating app due to uncaught exception 'Invalid value', reason: 'Property 'referenceNumber' is not a link in object of type 'Compound''
</pre>

**Comment by peterpaulis** [comment] 2015-12-10 16:34
I came up with the following fix, which is quite retarded and works only if you know you wont have larger numbers than n

<pre>
    NSMutableString * predicateString = [NSMutableString new];
    [predicateString appendFormat:@"(referenceNumber = %ld)", referenceNumber];
    for (NSInteger i = 1; i < 5; ++i) {
        
        NSInteger order = pow(10, i);
        [predicateString appendFormat:@" OR (referenceNumber BETWEEN {%ld, %ld})", referenceNumber*order, (referenceNumber+1)*order-1];
        
    }
    
    RLMResults * filteredCompounds = [allCompounds objectsWithPredicate:[NSPredicate predicateWithFormat:predicateString]];
</pre>

for 15 it produces

(referenceNumber = 15) OR (referenceNumber BETWEEN {150, 159}) OR (referenceNumber BETWEEN {1500, 1599}) OR (referenceNumber BETWEEN {15000, 15999}) OR (referenceNumber BETWEEN {150000, 159999})

**Comment by mrackwitz** [comment] 2015-12-10 16:38
That's not supported yet and would require support in the underlying storage engine.

If your number has a fixed length, you can workaround with ranges as `referenceNumber BETWEEN {1300, 1399}` for all numbers prefixed with `13` for a length of 4 digits. This approach can be also extended for further lengths up to a given limit as you found yourself.

**Comment by jpsim** [comment] 2016-03-29 00:30
Closing as a duplicate of #2799.

**Closed by jpsim** 2016-03-29 00:30 UTC
Labels: Blocked On Core, S:Idea Backlog, T:Enhancement
