### ISSUE TITLE
Could not build by Pod install and Xcode 10.2b1 ~ b4.

### ISSUE THREAD

**Issue by 15620946376** [realm/realm-cocoa#6113] opened 2019-03-26 04:56 UTC
Module compiled with Swift 4.2 cannot be imported by the Swift 5.0 , use RealmSwift 3.13.1.
Can I build success in Xcode12

**Comment by samueleperricone** [comment] 2019-03-26 13:58
Duplicate of #6115

**Closed** 2019-03-28 16:25 UTC
Labels: O:User
