### ISSUE TITLE
RealmSwift: Crash when calling className()

### ISSUE THREAD

**Issue by Mazyod** [realm/realm-cocoa#2792] opened 2015-11-04 01:43 UTC
Hello,

I am finally pushing my realm-power app to the AppStore. My only complaint is slow open speed, it's  already documented in another issue, but the rest of the features rock. #2510 

So, about the issue. I've pushed the app to testers, and noticed a really weird crash when trying to call `className()`. It only happens in some cases, but not all cases .. ~~I haven't thoroughly debugged it, because I've noticed that `RealmSwift` now uses `className` as a property. Switching to a property fixed the issue.~~

~~The only issue now is, why am I even able to perform `realmObject.className()`? Do you provide the function call for backward compatibility? Do you have insights about this issue, or if I can provide more info about it?~~

Finally, the backtrace is suggesting that I am trying to perform a call on a `String`?:

```
* thread #1: tid = 0x4a653, 0x00000001007eaea0 MyFramework`static ext.MyFramework.MyFramework.SettingsTable<A where A: RealmSwift.Object, A: MyFramework.SettingsTable>.NotificationKey.getter : Swift.String(self=0x000025a144e7fda5) + 124 at SettingsTable.swift:23, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x25a144e7fda5)
  * frame #0: 0x00000001007eaea0 MyFramework`static ext.MyFramework.MyFramework.SettingsTable<A where A: RealmSwift.Object, A: MyFramework.SettingsTable>.NotificationKey.getter : Swift.String(self=0x000025a144e7fda5) + 124 at SettingsTable.swift:23
```

Relevant code:

```swift
public extension SettingsTable where Self: Object {
    
    static var NotificationKey: String {
        return "\(className()).On.Update"
    }

    ...
}
```

Thanks,

**Comment by Mazyod** [comment] 2015-11-04 01:48
:flushed: can't believe I fell into this .. it's just printing the selector... Let me dig deeper.

**Comment by Mazyod** [comment] 2015-11-04 02:14
Sorry about the previous confusion. Static `className()` function and `className` member  variable. Got it. So, that means the issue is still unresolved. `className()` call crashes in some cases, and I've narrowed it down.

1. Doesn't crash on simulator and iPhone 5.
2. Crashes on two iPhone 6s devices I've tried.
3. Everyone loves a sample project. [Here you go](https://www.dropbox.com/s/z5e9vanm6g5ah0q/RealmClassNameCrash.zip?dl=0).

Help? 

_(Couldn't understand the performance magic that was happening in the `+[RLMObjectBase className]` method :grin: )_

**Comment by jpsim** [comment] 2015-11-04 18:06
Hey, sorry about the troubles on this one. I'm not immediately sure why this is happening, we do run device tests on a 64bit iOS 8 device on a continuous basis and it's never caught this. I'll dig into it.

**Comment by Mazyod** [comment] 2015-11-04 18:20
Thanks @jpsim! Honestly, I am more concerned about other Realm users running into this than my specific use case. I've already worked around it.

**Comment by mrackwitz** [comment] 2015-11-05 18:06
I was testing that out and investigating to see what is happening here.

The problem seemed to became finally more obvious when I was reverse-engineering the generated framework binary with Hopper. It turns out that the `static var` defined in a protocol extension is implemented statically and isn't made available to the Objective-C runtime. This can confirmed by trying to execute `Subclass.performSelector("NotificationKey")`, which also fails on the simulator. But this doesn't seem to stop Swift from making it possible to use it even with `NSObject` descendants. This was for me surprising because I found out as well that static computed properties are available to the Objective-C runtime as well (by an alias calling the static variant) when they are directly defined in the class.

At least for me, it isn't crashing exactly on calling `className()`, but rather on trying to access `self` in the computed property `NotificationKey`. Same happens when trying to access the `dynamicType` in `proxy` in any other way. From my understanding, this seems to be rather a problem with the Swift compiler or runtime.

So what you definitively could do for now is to change your implementation to something like seen below:
```swift
public extension SettingsTable where Self: Object {
    …
    public var proxy: String {
        return "\(self.objectSchema.className).On.Update"
    }
}
```

Thanks for bringing this to our attention.
This definitively needs further investigation / follow-up.

**Comment by jpsim** [comment] 2016-01-13 20:04
I've looked further into this and determined that it's actually a Swift bug, so I filed a radar ([rdar://24173309](http://www.openradar.me/24173309)) as well as a ticket on Swift's bug tracker ([SR-537](https://bugs.swift.org/browse/SR-537)).

Here's a minimal repro case without referencing Realm at all:

```swift
import Foundation
// doesn't crash when subclassing a non-Objective-C class, or not subclassing
class Class1: NSObject, Protocol1 {}

protocol Protocol1 {}
// doesn't crash without the type constraint, or with a different constraint ('Self: Hashable')
extension Protocol1 where Self: Class1 {
    func printType() {
        print(self.dynamicType)
        // also crashes:
        // _ = String(self.dynamicType)
        // self.dynamicType.description()
    }
}

Class1().printType() // EXC_BAD_ACCESS
```

So I'm closing this ticket because the issue is unrelated to Realm.

**Closed by jpsim** 2016-01-13 20:04 UTC
Labels: bug, P1, swift
