### ISSUE TITLE
Support `NSDecimalNumber` directly

### ISSUE THREAD

**Issue by beloso** [realm/realm-cocoa#4613] opened 2017-01-31 12:16 UTC
## Goals

What do you want to achieve?
I have given a property the value of MAX_LONG
That property is the primary key

## Expected Results

What did you expected to happen?
No crashes

## Actual Results
I've received a crash:

What did happened instead?  

```
2017-01-31 11:53:19.844 BB App [11187:107495] *** Terminating app due to uncaught exception 'RLMException', reason: 'Invalid value '9223372036854775807' for property 'userId'
```

`userId` is defined as follows:

`@property (nonatomic, copy, nonnull) NSNumber<RLMInt>* userId;`

## Steps to Reproduce

We've simply sent MAX_LONG on a user ID via the remote server

## Version of Realm and Tooling

Realm version: 2.4.1

Xcode version: 8.2

iOS/OSX version: 10.2

Dependency manager + version: CocoaPods + 1.2.0

More info:

After some research we've found out that:

`2**59 == 576460752303423488` still works.
`2**60 == 1152921504606846976` doesn't work.

**Comment by istx25** [comment] 2017-01-31 16:26
Hi @beloso! Thanks for reaching out. I'll have someone look into this and respond with a solution or follow-up questions as soon as we can. 😸

**Comment by austinzheng** [comment] 2017-01-31 19:20
Thanks for reaching out to us, and sorry you're experiencing this problem.

I tried replicating this locally (creating a model as you described, and setting the `MAX_LONG` value on it). I wasn't able to reproduce this bug.

I don't quite understand your reproduction steps. When you say `We've simply sent MAX_LONG on a user ID via the remote server`, do you mean the remote server sent down the `MAX_LONG` value to your application, and the application then tried setting it on an object for a local Realm? Or are you using the Realm Object Server?

If you can provide a demo project or code listing that shows the crash, that would be extremely helpful. Thanks.

**Comment by beloso** [comment] 2017-02-02 11:22
The value was being provided by our server via a JSON endpoint, no it's not Realm Object Server. 

We are further investigating what the issue is. We saw an RLMException and assumed it was related to realm.

**Comment by CristianoCastro** [comment] 2017-02-02 12:12
I have been able to reproduce it via a test case, it seems its due to our serializer parsing it as a decimal number instead of integer, then we get the exception in RLMUtil.mm when validating the type.

```
#import "Realm.h"

@interface TestRMLInt : RLMObject

@property (nonatomic, copy) NSNumber<RLMInt> *userId;

@end

@implementation TestRMLInt

+ (NSString *)primaryKey {

    return NSStringFromSelector(@selector(userId));
}

@end

@implementation ViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    // Do any additional setup after loading the view, typically from a nib.
    
    // this one works
    NSNumber *n = @(NSIntegerMax);
    // this one doesn't work
    NSDecimalNumber *dn = [[NSDecimalNumber alloc] initWithString:[n stringValue]];
    
    // switch the attribution between n and dn to test
    NSNumber<RLMInt> *key = (NSNumber<RLMInt> *)dn;
    
    NSLog(@"n is '%@' (objc type %c) and dn is '%@' (objc type %c)",n, [n objCType][0],dn, [dn objCType][0]);
    
    RLMRealm *realm = [RLMRealm defaultRealm];
    [realm beginWriteTransaction];
    
    TestRMLInt *del = [TestRMLInt objectForPrimaryKey:key];
    if(del){
    
        [realm deleteObject:del];
        [realm commitWriteTransaction];
        [realm beginWriteTransaction];
    }
    
    TestRMLInt *testObject = [[TestRMLInt alloc] init];
    testObject.userId = key;
    [realm addOrUpdateObject:testObject];
    
    [realm commitWriteTransaction];
}

@end
```

Maybe we could validate a decimal as integer if it has no decimal value and fits within an integer, somewhat like you are doing with float validation.

**Comment by austinzheng** [comment] 2017-02-03 19:04
It turns out we don't support `NSDecimalNumber` right now unless you get the primitive value and then rewrap it in a regular `NSNumber`. You can use that as a workaround for now; I'm going to repurpose this ticket for tracking adding in that functionality. Thanks for reporting this, and best of luck with your future endeavors.

**Comment by austinzheng** [comment] 2017-02-09 23:27
I've updated our documentation. We support assigning `NSDecimalNumber` values to properties marked as `RLMDouble`. If you need to assign to a `RLMInt`, the best thing to do is to unwrap and rewrap manually.

**Closed by austinzheng** 2017-02-09 23:27 UTC
Labels: S:P2 Backlog, T:Enhancement
