### ISSUE TITLE
Crashed, bad access

### ISSUE THREAD

**Issue by zj159963** [realm/realm-cocoa#3130] opened 2016-01-25 03:21 UTC
m_observers = context->get_observed_rows();
        if (m_observers.empty()) {
            auto old_version = sg.get_version_of_current_transaction();
            if (validate_schema_changes) {
                func(static_cast<TransactLogValidator&>(*this));
            }
            else {
                func();
            }
            if (old_version != sg.get_version_of_current_transaction()) {
                context->did_change({}, {});
            }
            return;
        }

Crashed at context->did_change({},{});
Bad access

**Comment by kishikawakatsumi** [comment] 2016-01-25 08:13
@zj159963 I believe this issue is duplicate of #3013 and #3035. This was probably fixed by #3078, so try pointing CocoaPods at master rather than 0.97.0.
I'm going to close this issue. If you encounter the further problem, please feel free to reopen this issue or create a new one.

**Closed by kishikawakatsumi** 2016-01-25 08:13 UTC
