### ISSUE TITLE
umbrella header 'Realm.h' not found

### ISSUE THREAD

**Issue by fiancrs** [realm/realm-cocoa#2558] opened 2015-09-23 08:55 UTC
RS,this problem happened when i used cocoapods  integrate Realm to my iOS project(Using Xcode 7)
![136 pic_hd](https://cloud.githubusercontent.com/assets/14039062/10041038/c0e521f4-6213-11e5-9d8d-2621ef605ed3.jpg)
here's my screenshot, thanks!

**Comment by mrackwitz** [comment] 2015-09-23 16:14
Which version of CocoaPods do you use? I guess, you declare the directive `use_frameworks!` in your Podfile?

**Comment by fiancrs** [comment] 2015-09-23 16:36
The version is 0.38.2. I had found the problem finally, i had set &(PODS_ROOT) in Build Setting  in my Project(not the Pods’s).But in the other side ,it make some clashes with other thirty-party library. Absolutely , i had declared ‘use_frameworks’ in Podfile

**Comment by mrackwitz** [comment] 2015-09-23 16:43
So is it now working for you? Which third-party libraries are does, where you noticed clashes with? Would you mind sharing your Podfile? Is this perhaps more sort of a general problem with CocoaPods?

**Comment by fiancrs** [comment] 2015-09-23 16:59
here is my Podfile .  Actually I don't know if this is not a conflict。why i set $(PODS_ROOT),the Realm had warming me "umbrella header 'Realm.h' not found".without that ,the QBImagePickerController warming warming ''unfound QBImagePickerController"  about this
<img width="570" alt="77a7b431-dff3-4697-b196-d44fc65e68d9" src="https://cloud.githubusercontent.com/assets/14039062/10052055/60089f34-6257-11e5-8ffa-849b3261c60c.png">

**Comment by mrackwitz** [comment] 2015-09-24 18:46
With CocoaPods it should be never necessary to overwrite `PODS_ROOT` in your project or in any other target. If QBImagePickerController doesn't work without that, then it seems like something is wrong with this pod. Can you copy the exact error message you get?

**Comment by jpsim** [comment] 2015-09-29 22:45
@fiancrs have you had the chance to undo overwriting `PODS_ROOT` and then sharing the complete CocoaPods error message here so we can help you fix your project?

**Comment by jpsim** [comment] 2015-10-01 18:26
Closing assuming @fiancrs resolved their issue.

**Closed by jpsim** 2015-10-01 18:26 UTC
Labels: Help

**Comment by Leshich** [comment] 2015-10-15 06:44
I also have a problem exactly like this after I just added realm pods, and installed them through `pod update`

**Comment by fiancrs** [comment] 2015-10-15 14:08
Check whether u had set $(PODS-ROOT) in your main target's setting ,if had ,try to delete it

**Comment by Leshich** [comment] 2015-10-15 19:47
Still have problems, but now with cocoapods itself without PODS_ROOT in User Defined inside Build Settings for my app.

I have these warnings: 
```
[!] The `IntellectualCallerID [Debug]` target overrides the `PODS_ROOT` build setting defined in `Pods/Target Support Files/Pods-IntellectualCallerID/Pods-IntellectualCallerID.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `IntellectualCallerID [Release]` target overrides the `PODS_ROOT` build setting defined in `Pods/Target Support Files/Pods-IntellectualCallerID/Pods-IntellectualCallerID.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
```

**Comment by fiancrs** [comment] 2015-10-15 20:02
I don't know what's your mean exactly 。The pods root setting should not be happened in your main project target but not the pods project target . This warning is dued to the Xcode had searched the head files  straightly needn't framework's name while you had setting pods root in your main project target 。

**Comment by mrackwitz** [comment] 2015-10-15 20:18
@Leshich: Did you really removed the build setting or overwrote it with an empty value?

**Comment by Leshich** [comment] 2015-10-16 17:15
I did remove a value, so now it's empty. Xcode is not allowing me to fully remove this 'User-defined' build setting.

I have another project with realm installed. But I also have a pods_root setting in there. That project works fine. But I do have some problems with active project where I had a lot of pods for three months working correctly, and now I can't add only Realm. I don't really know what's the problem here.
![screen shot 2015-10-16 at 22 13 51](https://cloud.githubusercontent.com/assets/4246455/10548327/47286b76-7453-11e5-8fb2-2250b7a811dd.png)
Is this the setting you want me to remove?

**Comment by mrackwitz** [comment] 2015-10-21 13:25
Can you enable showing different levels to check where this build setting originates from? It doesn't seem to be overwritten anymore as it was when you ran `pod install`. Does the warning still appear if you run it again?

**Comment by mrackwitz** [comment] 2015-10-23 11:26
@Leshich: FYI - You can select the levels perspective here. The other red box marks where the setting is expected to come from, all other columns should be empty in that row, beside the column which shows the resolved value.
<img width="1205" alt="pods_root_levels" src="https://cloud.githubusercontent.com/assets/1389011/10691448/12b53648-7981-11e5-9d20-a8a7481f9330.png">

**Comment by Leshich** [comment] 2015-10-23 18:02
https://github.com/CocoaPods/CocoaPods/issues/4420

After updating to Xcode 7.1 I have this problem running with facebook/pop library. So now I have already two problems with connecting framework through cocoapods. I want to wait a bit for a fixes in cocoapods/xcode for now. 
![screen shot 2015-10-23 at 23 02 19](https://cloud.githubusercontent.com/assets/4246455/10700879/27a6b55a-79da-11e5-9504-890f598ac172.png)

**Comment by Leshich** [comment] 2015-10-30 08:23
Still have this problem installing Realm through Cocoapods.

Installed using Dynamic frameworks. It worked, but i really want to use cocoapods here)

Don't really know what's my problem, because I have a second app using realm through cocoapods, and it works:)

**Comment by krimpedance** [comment] 2016-01-09 14:44
I held the same problem, too.

I was adding Bridging Header to use SVProgressHUD in Swift.
But then a message as "error: 'SVProgressHUD.h' file not found" had, so I was settled by setting "User Header Search Paths = Pods/**".

When making Realm coexist, this setting seems to have been a problem.
So I was changed "Pods/**" to "Pods/SVProgressHUD/**".
Compilation passed by this.

By now, I guess you get used to my funny English writing.

**Comment by romanvolkov2** [comment] 2016-02-15 15:23
I had the same problem. Manually moving some header files (specifically, those declared in Realm.h) from “Project Headers” to “Public Headers” solved the issue. Latest Xcode, cocoa pods 1.0.0.beta.3.

![screen shot 2016-02-15 at 4 11 14 pm](https://cloud.githubusercontent.com/assets/13730111/13052665/6b51675c-d400-11e5-9de6-0d99a5ee3af3.png)
![screen shot 2016-02-15 at 4 13 48 pm](https://cloud.githubusercontent.com/assets/13730111/13052666/6b73ef7a-d400-11e5-9ca7-4a490d72ad40.png)

**Comment by jpsim** [comment] 2016-02-15 17:26
We don't support any of the CocoaPods 1.0 release candidates at the moment. Please use the latest stable version of CocoaPods to install Realm.

**Comment by bimusiek** [comment] 2016-02-22 09:21
@jpsim Any plans on supporting it? I am forced to do so, as other things are not working properly with stable cocoapods version. With beta I don't have any problems except for RealmSwift import. :(

**Comment by jpsim** [comment] 2016-02-22 17:15
*Of course* we plan on supporting CocoaPods 1.0! Unfortunately, the release candidates have introduced a regression, which is being tracked in CocoaPods/CocoaPods#4848 on their side, and realm/realm-cocoa#3052 on our side.

Contributors to both CocoaPods and Realm are looking into the best way to fix this.

**Comment by returnight** [comment] 2016-02-24 05:28
![image](https://cloud.githubusercontent.com/assets/5301947/13276443/65771d44-dafa-11e5-8a39-780c4b1517bd.png)

I also have this problem, too.  
CocoaPods 0.39.0 
swift

**Comment by returnight** [comment] 2016-02-24 06:43
![image](https://cloud.githubusercontent.com/assets/5301947/13277476/17b5d6ae-db04-11e5-8ff7-83a1bd286934.png)

**Comment by velthune** [comment] 2016-04-07 10:29
I find THE solution:

pod _0.39.0_ install --verbose

I was installing with cocoapod 1.0.* that Realm does not support yet!

**Comment by mrackwitz** [comment] 2016-04-07 10:33
>I was installing with cocoapod 1.0.* that Realm does not support yet!

That's not true anymore. We support the prereleases of CocoaPods 1.0 from `1.0.0.beta.4`.

**Comment by velthune** [comment] 2016-04-07 10:40
Oh.. are you sure? I'm using 1.0.0.beta.3 and Xcode 7.3.
I read "N.B.: The CocoaPods 1.0.0 Release Candidate versions are not supported at this time. Please use the latest stable version." from [doc](https://realm.io/docs/swift/latest/).

**Comment by velthune** [comment] 2016-04-07 12:53
@mrackwitz you're right, I updated cococapods

     sudo gem install cocoapods --pre

Then I run:

    pod clean
    pod install --verbose

And all works fine, thanks!
