### ISSUE TITLE
Assertion failed: row_ndx < size()

### ISSUE THREAD

**Issue by tspecht** [realm/realm-cocoa#1315] opened 2015-01-09 14:35 UTC
The error said to send it to you so here you go :) I'm using 0.89.2

/Users/myUser/Documents/Code/myApp/Pods/Headers/Build/Realm/tightdb/table.hpp:1621: Assertion failed: row_ndx < size()
0   MyApp                            0x000000010033ed24 _ZN7tightdb4util9terminateEPKcS2_l + 360
1   MyApp                            0x00000001002cfc74 _ZN7tightdb5Table3getEm + 72
2   MyApp                            0x00000001002ccab0 _ZN7tightdb5TableixEm + 24
3   MyApp                            0x0000000100324544 -[RLMResults countByEnumeratingWithState:objects:count:] + 556
4   MyApp                            0x00000001000c0e6c __25-[MyClass aMethod]_block_invoke397 + 1488
5   MyApp                            0x000000010031eae4 -[RLMRealm transactionWithBlock:] + 76
6   MyApp                            0x00000001000c0434 __25-[MyClass aMethod]_block_invoke + 456
7   MyApp                            0x00000001001e1274 __48-[BFTask continueWithExecutor:withSuccessBlock:]_block_invoke + 328
8   MyApp                            0x00000001001e088c __41-[BFTask continueWithExecutor:withBlock:]_block_invoke_2 + 56
9   libdispatch.dylib                   0x0000000100cd8e30 _dispatch_call_block_and_release + 24
10  libdispatch.dylib                   0x0000000100cd8df0 _dispatch_client_callout + 16
11  libdispatch.dylib                   0x0000000100ce59a0 _dispatch_root_queue_drain + 1280
12  libdispatch.dylib                   0x0000000100ce6f18 _dispatch_worker_thread3 + 132
13  libsystem_pthread.dylib             0x0000000198dd92e4 _pthread_wqthread + 816
14  libsystem_pthread.dylib             0x0000000198dd8fa8 start_wqthread + 4
IMPORTANT: if you see this error, please send this log to help@realm.io.

**Comment by alazier** [comment] 2015-01-09 19:22
Thanks for the report. This should have been resolved with this commit: #1296 - this will make it into the next release.

The problem is that your RLMResults is changing during enumeration. You need to make any changes which will change your set of RLMResults outside of the enumeration block.

**Closed by alazier** 2015-01-09 19:22 UTC
