### ISSUE TITLE
Realm crashes at init_from_ref with please_report_this message

### ISSUE THREAD

**Issue by cmittendorf** [realm/realm-cocoa#2311] opened 2015-07-29 06:27 UTC
Hi!

We've got a Mac application written using Swift and SwiftRealm/Realm version 0.9.32. It's a Finder extension and it crashes when accessing the Realm database in it's group container folder.

    Crashed Thread:        0  Dispatch queue: com.apple.main-thread

    Exception Type:        EXC_CRASH (SIGABRT)
    Exception Codes:       0x0000000000000000, 0x0000000000000000

    Application Specific Information:
    abort() called

    Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
    0   libsystem_kernel.dylib        	0x00007fff80f0a286 __pthread_kill + 10
    1   libsystem_c.dylib             	0x00007fff83dfeb53 abort + 129
    2   io.Realm.Realm                	0x0000000105ddfcb9 please_report_this_error_to_help_at_realm_dot_io + 9
    3   io.Realm.Realm                	0x0000000105ddfe78 realm::util::terminate_internal(std::__1::basic_stringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) + 328
    4   io.Realm.Realm                	0x0000000105dee456 void realm::util::terminate<unsigned long, int>(char const*, char const*, long, unsigned long, int) + 518
    5   io.Realm.Realm                	0x0000000105e8dafd realm::Group::init_from_ref(unsigned long) + 749
    6   io.Realm.Realm                	0x0000000105e9b326 realm::SharedGroup::begin_read(realm::SharedGroup::VersionID) + 182
    7   io.Realm.Realm                	0x0000000105dcb8d1 -[RLMRealm getOrCreateGroup] + 65
    8   io.Realm.Realm                	0x0000000105da511e RLMTableForObjectClass(RLMRealm*, NSString*) + 106
    9   io.Realm.Realm                	0x0000000105da5af6 -[RLMObjectSchema table] + 61
    10  io.Realm.Realm                	0x0000000105daae21 RLMGetObjects + 182
    11  io.Realm.RealmSwift           	0x00000001057ebf2b _TFC10RealmSwift5Realm7objectsfS0_U__FMQ_GCS_7ResultsQ__ + 139
    12  de.freenet.Sync               	0x000000010531c10a _TFFFC4Sync24RealmFileSyncStatusStoreg14statusProducerGV13ReactiveCocoa14SignalProducerGVSs10DictionaryCSo5NSURLOS_14FileSyncStatus_OS1_7NoError_U_FTGVSs6SinkOfGOS1_5EventGS3_S4_S5__S6___CS1_19CompositeDisposable_T_U_FTO10RealmSwift12NotificationCS10_5Realm_T_ + 842 (FileSyncStatusStore.swift:100)
    13  io.Realm.RealmSwift           	0x00000001057f6402 _TFF10RealmSwift41rlmNotificationBlockFromNotificationBlockFFT12notificationOS_12Notification5realmCS_5Realm_T_bTGSQSS_GSQCSo8RLMRealm__T_U_FTGSQSS_GSQS2___T_ + 530
    14  io.Realm.RealmSwift           	0x00000001057f3f6d _TPA__TFF10RealmSwift41rlmNotificationBlockFromNotificationBlockFFT12notificationOS_12Notification5realmCS_5Realm_T_bTGSQSS_GSQCSo8RLMRealm__T_U_FTGSQSS_GSQS2___T_ + 93
    15  io.Realm.Realm                	0x0000000105dcd679 -[RLMRealm sendNotifications:] + 317
    16  io.Realm.Realm                	0x0000000105dce08f -[RLMRealm handleExternalCommit] + 150
    17  io.Realm.Realm                	0x0000000105d933a6 -[RLMNotifier listen]::$_0::__invoke(void*) + 38
    18  com.apple.CoreFoundation      	0x00007fff84864a01 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
    19  com.apple.CoreFoundation      	0x00007fff84856b8d __CFRunLoopDoSources0 + 269
    20  com.apple.CoreFoundation      	0x00007fff848561bf __CFRunLoopRun + 927
    21  com.apple.CoreFoundation      	0x00007fff84855bd8 CFRunLoopRunSpecific + 296
    22  com.apple.HIToolbox           	0x00007fff8aa7c56f RunCurrentEventLoopInMode + 235
    23  com.apple.HIToolbox           	0x00007fff8aa7c2ea ReceiveNextEventCommon + 431
    24  com.apple.HIToolbox           	0x00007fff8aa7c12b _BlockUntilNextEventMatchingListInModeWithFilter + 71
    25  com.apple.AppKit              	0x00007fff885308ab _DPSNextEvent + 978
    26  com.apple.AppKit              	0x00007fff8852fe58 -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 346
    27  com.apple.AppKit              	0x00007fff88525af3 -[NSApplication run] + 594
    28  com.apple.AppKit              	0x00007fff884a2244 NSApplicationMain + 1832
    29  libxpc.dylib                  	0x00007fff8d7f5958 _xpc_objc_main + 793
    30  libxpc.dylib                  	0x00007fff8d7f7060 xpc_main + 490
    31  com.apple.Foundation          	0x00007fff8e07af0a -[NSXPCListener resume] + 163
    32  com.apple.pluginkit.framework 	0x00007fff84c89476 -[PKService run] + 493
    33  com.apple.pluginkit.framework 	0x00007fff84c89157 +[PKService main] + 55
    34  com.apple.pluginkit.framework 	0x00007fff84c894b8 +[PKService _defaultRun:arguments:] + 17
    35  libextension.dylib            	0x00007fff8febf3f3 NSExtensionMain + 51
    36  libdyld.dylib                 	0x00007fff8dace5c9 start + 1

The code in line 100 of FileSyncStatusStore.swift is:

    let statusObjects = realm.objects(FileStatus).filter("filePath in %@", paths)

What could we do wrong here?

**Comment by jpsim** [comment] 2015-07-29 06:50
> What could we do wrong here?

You're likely doing nothing wrong in this case. Hitting this assertion is likely indicative of a bug in Realm. There should be a message being logged to the console when triggering this assertion, could you please share that with us? If you're able to share steps for us to reproduce the issue, that would be instrumental in helping us resolve it.

Thanks!

**Comment by cmittendorf** [comment] 2015-07-29 08:42
There are only two entries in system.log with the crashed process id:

    Jul 29 08:03:31 hh-50036738-d com.apple.xpc.launchd[1] (de.….SyncExtension[33369]): Service exited due to signal: Abort trap: 6

and

    Jul 29 08:03:31 hh-50036738-d... ReportCrash[34050]: Saved crash report for SyncExtension[33369] version 1.0.0 (1) to /Users/...

Which is probably not the information that you were looking for … and reproducing the error seems to be difficult. When I start the app a second time this crash did not happen again.

**Comment by segiddins** [comment] 2015-07-29 17:17
Could you share the saved crashed report mentioned in that second log entry, perchance? Thanks!

**Comment by cmittendorf** [comment] 2015-07-31 08:08
@segiddins  I've sent the two similar crash reports to you for further investigation.

**Comment by segiddins** [comment] 2015-07-31 16:35
Unfortunately, those crash reports don't contain the assertion log, so I'm still at a loss as to what could be causing this.

**Comment by cmittendorf** [comment] 2015-08-03 11:55
Hi! Today I managed to see a crash where the assertion message was shown:

    group.cpp:133: [realm-core-0.89.6] Assertion failed: top_size >= 3 [0, 3]
    0   Realm                               0x000000010104ed58 _ZN5realm4util18terminate_internalERNSt3__118basic_stringstreamIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE + 40
    1   Realm                               0x000000010105d456 _ZN5realm4util9terminateImiEEvPKcS3_lT_T0_ + 518
    2   Realm                               0x00000001010fcafd _ZN5realm5Group13init_from_refEm + 749
    3   Realm                               0x000000010110a326 _ZN5realm11SharedGroup10begin_readENS0_9VersionIDE + 182
    4   Realm                               0x000000010103a8d1 -[RLMRealm getOrCreateGroup] + 65
    5   Realm                               0x00000001010457c2 RLMRealmSchemaVersion + 38
    6   Realm                               0x0000000101016543 RLMUpdateRealmToSchemaVersion + 91
    7   Realm                               0x000000010103b483 +[RLMRealm realmWithPath:key:readOnly:inMemory:dynamic:schema:error:] + 1421
    8   Realm                               0x000000010103ad51 +[RLMRealm realmWithPath:readOnly:error:] + 52
    9   RealmSwift                          0x000000010036b1bf _TFC10RealmSwift5RealmCfMS0_FT4pathSS_S0_ + 111
    10  XXXXX                            0x000000010008b7eb _TFC8CloudMac8Injector21realmForCurrentThreadfS0_FT_C10RealmSwift5Realm + 875
    11  Sync                                0x0000000100acad43 _TFC4Sync24RealmFileSyncStatusStore19removeAllWithStatusfS0_FOS_14FileSyncStatusT_ + 67
    12  Sync                                0x0000000100acc32f _TTWC4Sync24RealmFileSyncStatusStoreS_19FileSyncStatusStoreS_FS1_19removeAllWithStatusUS1___fQPS1_FOS_14FileSyncStatusT_ + 15
    13  Sync                                0x0000000100a8cd14 _TFFC4Sync11SyncManager17syncFilesFromDiskFS0_FTGV13ReactiveCocoa14SignalProducerGSaV9FileModel4File_OS1_7NoError_17lastFilesFromDiskGS2_GSaS4__S5__15filesFromServerGS2_GSaS4__S5___GS2_TOS_9SyncEventOS3_6Change_S5__U_FT_T_ + 84
    14  Sync                                0x0000000100a8cd41 _TTRXFo__dT__XFo_iT__iT__ + 17
    15  Sync                                0x0000000100a07c31 _TPA__TTRXFo__dT__XFo_iT__iT__ + 81
    16  ReactiveCocoa                       0x00000001005bede2 _TFFF13ReactiveCocoa2onU_S_9ErrorType__FT7startedGSqFT_T__5eventGSqFGOS_5EventQ_Q0__T__5errorGSqFQ0_T__9completedGSqFT_T__11interruptedGSqFT_T__10terminatedGSqFT_T__8disposedGSqFT_T__4nextGSqFQ_T___FGVS_14SignalProducerQ_Q0__GS2_Q_Q0__U_FGS2_Q_Q0__GS2_Q_Q0__U_FTGVSs6SinkOfGS1_Q_Q0___CS_19CompositeDisposable_T_ + 146
    17  ReactiveCocoa                       0x000000010058a1c5 _TPA__TFFF13ReactiveCocoa2onU_S_9ErrorType__FT7startedGSqFT_T__5eventGSqFGOS_5EventQ_Q0__T__5errorGSqFQ0_T__9completedGSqFT_T__11interruptedGSqFT_T__10terminatedGSqFT_T__8disposedGSqFT_T__4nextGSqFQ_T___FGVS_14SignalProducerQ_Q0__GS2_Q_Q0__U_FGS2_Q_Q0__GS2_Q_Q0__U_FTGVSs6SinkOfGS1_Q_Q0___CS_19CompositeDisposable_T_ + 565
    18  ReactiveCocoa                       0x0000000100564a0e _TFV13ReactiveCocoa14SignalProducer15startWithSignalU_S_9ErrorType__fGS0_Q_Q0__FFTGCS_6SignalQ_Q0__PS_10Disposable__T_T_ + 1086
    19  ReactiveCocoa                       0x00000001005befc7 _TFFF13ReactiveCocoa2onU_S_9ErrorType__FT7startedGSqFT_T__5eventGSqFGOS_5EventQ_Q0__T__5errorGSqFQ0_T__9completedGSqFT_T__11interruptedGSqFT_T__10terminatedGSqFT_T__8disposedGSqFT_T__4nextGSqFQ_T___FGVS_14SignalProducerQ_Q0__GS2_Q_Q0__U_FGS2_Q_Q0__GS2_Q_Q0__U_FTGVSs6SinkOfGS1_Q_Q0___CS_19CompositeDisposable_T_ + 631
    20  ReactiveCocoa                       0x000000010058a1c5 _TPA__TFFF13ReactiveCocoa2onU_S_9ErrorType__FT7startedGSqFT_T__5eventGSqFGOS_5EventQ_Q0__T__5errorGSqFQ0_T__9completedGSqFT_T__11interruptedGSqFT_T__10terminatedGSqFT_T__8disposedGSqFT_T__4nextGSqFQ_T___FGVS_14SignalProducerQ_Q0__GS2_Q_Q0__U_FGS2_Q_Q0__GS2_Q_Q0__U_FTGVSs6SinkOfGS1_Q_Q0___CS_19CompositeDisposable_T_ + 565
    21  ReactiveCocoa                       0x0000000100564a0e _TFV13ReactiveCocoa14SignalProducer15startWithSignalU_S_9ErrorType__fGS0_Q_Q0__FFTGCS_6SignalQ_Q0__PS_10Disposable__T_T_ + 1086
    22  ReactiveCocoa                       0x000000010058730e _TPA__TFFFF13ReactiveCocoaP33_BB0E5F533EEE68215FAAD3E87E37BD995mergeU_S_9ErrorType__FGVS_14SignalProducerGS1_Q_Q0__Q0__GS1_Q_Q0__U_FTGVSs6SinkOfGOS_5EventQ_Q0___CS_19CompositeDisposable_T_U0_FTGCS_6SignalGS1_Q_Q0__Q0__PS_10Disposable__T_U_FGS1_Q_Q0__T_ + 238
    23  ReactiveCocoa                       0x000000010058738c _TPA__TTRG1_RPq0_P13ReactiveCocoa9ErrorType__XFo_oGVS_14SignalProducerq_q0___dT__XFo_iGS1_q_q0___iT__ + 60
    24  ReactiveCocoa                       0x000000010059a0dd _TFZFO13ReactiveCocoa5Event4sinkU_S_9ErrorType__FMGS0_Q_Q0__FT5errorGSqFQ0_T__9completedGSqFT_T__11interruptedGSqFT_T__4nextGSqFQ_T___GVSs6SinkOfGS0_Q_Q0___U_FGS0_Q_Q0__T_ + 637
    25  ReactiveCocoa                       0x00000001005715e1 _TPA__TFZFO13ReactiveCocoa5Event4sinkU_S_9ErrorType__FMGS0_Q_Q0__FT5errorGSqFQ0_T__9completedGSqFT_T__11interruptedGSqFT_T__4nextGSqFQ_T___GVSs6SinkOfGS0_Q_Q0___U_FGS0_Q_Q0__T_ + 225
    26  ReactiveCocoa                       0x00000001005997d8 _TPA__TFFVSs6SinkOfcU__FMGS_Q__USs8SinkType__FQ_GS_Qd___U_FQd__T_2219 + 72
    27  ReactiveCocoa                       0x00000001005a1d45 _TFFC13ReactiveCocoa6SignalcU_S_9ErrorType__FMGS0_Q_Q0__FFGVSs6SinkOfGOS_5EventQ_Q0___GSqPS_10Disposable__GS0_Q_Q0__U_FGS3_Q_Q0__T_ + 1365
    28  ReactiveCocoa                       0x00000001005bbacb _TFFV13ReactiveCocoa14SignalProducer15startWithSignalU_S_9ErrorType__FGS0_Q_Q0__FFTGCS_6SignalQ_Q0__PS_10Disposable__T_T_U0_FGOS_5EventQ_Q0__T_ + 155
    29  ReactiveCocoa                       0x000000010057d301 _TPA__TFFV13ReactiveCocoa14SignalProducer15startWithSignalU_S_9ErrorType__FGS0_Q_Q0__FFTGCS_6SignalQ_Q0__PS_10Disposable__T_T_U0_FGOS_5EventQ_Q0__T_586 + 113
    30  ReactiveCocoa                       0x00000001005997d8 _TPA__TFFVSs6SinkOfcU__FMGS_Q__USs8SinkType__FQ_GS_Qd___U_FQd__T_2219 + 72
    31  ReactiveCocoa                       0x00000001005a1d45 _TFFC13ReactiveCocoa6SignalcU_S_9ErrorType__FMGS0_Q_Q0__FFGVSs6SinkOfGOS_5EventQ_Q0___GSqPS_10Disposable__GS0_Q_Q0__U_FGS3_Q_Q0__T_ + 1365
    32  ReactiveCocoa                       0x00000001005a31d4 _TFFFF13ReactiveCocoa3mapU__S_9ErrorType__FFQ_Q0_FGCS_6SignalQ_Q1__GS1_Q0_Q1__U_FGS1_Q_Q1__GS1_Q0_Q1__U_FGVSs6SinkOfGOS_5EventQ0_Q1___GSqPS_10Disposable__U_FGS3_Q_Q1__T_ + 196
    33  ReactiveCocoa                       0x0000000100590990 _TPA__TFFFF13ReactiveCocoa3mapU__S_9ErrorType__FFQ_Q0_FGCS_6SignalQ_Q1__GS1_Q0_Q1__U_FGS1_Q_Q1__GS1_Q0_Q1__U_FGVSs6SinkOfGOS_5EventQ0_Q1___GSqPS_10Disposable__U_FGS3_Q_Q1__T_ + 144
    34  ReactiveCocoa                       0x00000001005997d8 _TPA__TFFVSs6SinkOfcU__FMGS_Q__USs8SinkType__FQ_GS_Qd___U_FQd__T_2219 + 72
    35  ReactiveCocoa                       0x00000001005a1d45 _TFFC13ReactiveCocoa6SignalcU_S_9ErrorType__FMGS0_Q_Q0__FFGVSs6SinkOfGOS_5EventQ_Q0___GSqPS_10Disposable__GS0_Q_Q0__U_FGS3_Q_Q0__T_ + 1365
    36  ReactiveCocoa                       0x00000001005bbacb _TFFV13ReactiveCocoa14SignalProducer15startWithSignalU_S_9ErrorType__FGS0_Q_Q0__FFTGCS_6SignalQ_Q0__PS_10Disposable__T_T_U0_FGOS_5EventQ_Q0__T_ + 155
    37  ReactiveCocoa                       0x000000010057d301 _TPA__TFFV13ReactiveCocoa14SignalProducer15startWithSignalU_S_9ErrorType__FGS0_Q_Q0__FFTGCS_6SignalQ_Q0__PS_10Disposable__T_T_U0_FGOS_5EventQ_Q0__T_586 + 113
    38  ReactiveCocoa                       0x00000001005997d8 _TPA__TFFVSs6SinkOfcU__FMGS_Q__USs8SinkType__FQ_GS_Qd___U_FQd__T_2219 + 72
    39  ReactiveCocoa                       0x00000001005a1d45 _TFFC13ReactiveCocoa6SignalcU_S_9ErrorType__FMGS0_Q_Q0__FFGVSs6SinkOfGOS_5EventQ_Q0___GSqPS_10Disposable__GS0_Q_Q0__U_FGS3_Q_Q0__T_ + 1365
    40  ReactiveCocoa                       0x0000000100598ff3 _TPA__TFFFFF13ReactiveCocoa9observeOnU_S_9ErrorType__FPS_13SchedulerType_FGCS_6SignalQ_Q0__GS2_Q_Q0__U_FGS2_Q_Q0__GS2_Q_Q0__U_FGVSs6SinkOfGOS_5EventQ_Q0___GSqPS_10Disposable__U_FGS4_Q_Q0__T_U_FT_T_ + 99
    41  ReactiveCocoa                       0x00000001005b6c1f _TFFC13ReactiveCocoa14QueueScheduler8scheduleFS0_FFT_T_GSqPS_10Disposable__U_FT_T_ + 95
    42  libdispatch.dylib                   0x0000000100faf2bb _dispatch_call_block_and_release + 12
    43  libdispatch.dylib                   0x0000000100fa9d43 _dispatch_client_callout + 8
    44  libdispatch.dylib                   0x0000000100fadfb3 _dispatch_queue_drain + 1804
    45  libdispatch.dylib                   0x0000000100faffc0 _dispatch_queue_invoke + 223
    46  libdispatch.dylib                   0x0000000100facf5e _dispatch_root_queue_drain + 666
    47  libdispatch.dylib                   0x0000000100fbecd0 _dispatch_worker_thread3 + 106
    48  libsystem_pthread.dylib             0x00007fff8199a637 _pthread_wqthread + 729
    49  libsystem_pthread.dylib             0x00007fff8199840d start_wqthread + 13
    IMPORTANT: if you see this error, please send this log to help@realm.io.
    (lldb)


I hope this information can help you track down this crash.

**Comment by segiddins** [comment] 2015-08-03 18:06
@cmittendorf so I've spoken to our core team about this one before, and they say they'll need a project they can run in order to debug further. Could you share a project, either here or privately at help@realm.io? Thanks!

**Comment by cmittendorf** [comment] 2015-08-05 08:48
We are currently investigating sharing the project with you and I'm waiting for a final feedback. Until then I'd like to explain what we are actually doing. We're using a single Realm database from two applications, a main application (not sandboxed) and a finder extension (sandboxed), where only the main application is writing to the database, which is located in the apps group container. From my understanding, using Realm like this is a new feature, as it is [described on your site](https://realm.io/news/thomas-goyne-fast-inter-process-communication/). May that be a hint on what is going wrong?

**Comment by segiddins** [comment] 2015-08-05 17:25
@cmittendorf we've supported multi-process sharing of realm files for several months now, so that alone shouldn't be causing an issue. Is it possible that this might be fixed in Realm 0.94.0? If you haven't yet, could you give that update a try? Thanks!

**Comment by cmittendorf** [comment] 2015-08-06 08:41
@segiddins I will try out updating our version of Realm to 0.94.0. Besides, we are using [Carthage](http://github.com/Carthage/Carthage) for dependency management and selecting a specific version seems to be a bit of a problem. Using a simple entry like ```github "realm/realm-cocoa"``` in our Cartfile will checkout ```*** Checking out realm-cocoa at "null-string-beta-2"```.

**Comment by segiddins** [comment] 2015-08-06 16:14
@cmittendorf I believe my patch to fix that in Carthage is in the latest version. Are you using 0.7.5?

**Comment by cmittendorf** [comment] 2015-08-07 07:56
@segiddins Thanks, yes, upgrading Carthage to 0.7.5 did solve the error building the frameworks.

**Comment by segiddins** [comment] 2015-08-10 17:47
I'm going to close this issue out for now, since we were unable to reproduce the issue with the project you sent us. If there are any other tips you might have for reproducing it, we'll reopen. Thanks so much for bearing with us!

**Closed by segiddins** 2015-08-10 17:47 UTC
