### ISSUE TITLE
RLMSyncUser:configurationWithPartitionValue not available in Swift

### ISSUE THREAD

**Issue by levelchanger** [realm/realm-cocoa#6615] opened 2020-06-30 17:15 UTC
!!! MANDATORY TO FILL OUT !!!

## Goals
Call RLMSyncUser:configurationWithPartitionValue from Swift. The method is marked as NS_REFINED_FOR_SWIFT but there is no equivalent Swift func to call

## Expected Results
Be able to call the method or a redefined function in Swift.

## Actual Results
Compiler error

## Steps to Reproduce
Just use the Objective C SDK and try calling the function from Swift.

## Version of Realm and Tooling
Realm framework version: ?
Realm (10.0.0-beta.2)

Realm Object Server version: ?
NA

Xcode version: ?
Xcode 11.5

iOS/OSX version: ?
ProductName:	Mac OS X
ProductVersion:	10.15.5
BuildVersion:	19F101

Dependency manager + version: ?
pod 1.9.3

**Comment by jsflax** [comment] 2020-06-30 17:16
Try `myUser.configuration(partitionValue: "my partition value")`.

**Comment by levelchanger** [comment] 2020-06-30 17:23
Doesn't work.

<img width="1220" alt="compilerError" src="https://user-images.githubusercontent.com/43216100/86157031-a6e68f80-babb-11ea-99f8-1cf2f7a26f01.png">

**Comment by jsflax** [comment] 2020-06-30 17:31
Can I see a larger code snippet?

**Comment by jsflax** [comment] 2020-06-30 17:36
Assuming you are calling the objc API from Swift, this is an issue. We will fix this in the next release.

**Comment by levelchanger** [comment] 2020-06-30 17:40
Yes, I am. There are many items in the SDK that are marked as NS_REFINED_FOR_SWIFT. I don't know if those are problems as well. Also, the RLMSupport.swift file is missing the helpful extensions that were in the 5.0 version of the SDK.

**Comment by andreasley** [comment] 2020-11-06 16:56
Any ETA on his?

Is there a workaround (for Realm v10.1.1 in Swift) to be able to use Realm Sync Beta?

**Comment by ericjordanmossman** [comment] 2020-11-06 16:59
@andreasley 
I'm working on this today. No exact ETA yet. I'll post updates in this thread.

**Comment by andreasley** [comment] 2020-11-06 23:19
@ericjordanmossman Actually, my problem seems to be a completely different one, despite resulting in the same symptoms.

I'm using the Swift Package Manager, which works fine for "regular" Realm. However, all symbols for Realm Sync seem to be missing (e.g. `App`). Some important Swift files are excluded from the target `SwiftRealm` in [Package.swift](https://github.com/realm/realm-cocoa/blob/master/Package.swift) and I suppose all the C++ sources for sync aren't referenced either. There's probably a reason for that which I have yet to find. :)

**Comment by tgoyne** [comment] 2020-11-07 00:26
Yes, needing the binary library is why we can't support sync with swift package manager. We actually have now [open sourced the sync client](https://github.com/realm/realm-core/tree/monorepo/src/realm/sync), but there's some work left to be done to build against that instead of the prebuilt library.

**Comment by DominicFrei** [comment] 2021-01-21 16:16
@levelchanger 

The usage of `NS_REFINED_FOR_SWIFT` is [defined in Apple's documentation](https://developer.apple.com/documentation/swift/objective-c_and_c_code_customization/improving_objective-c_api_declarations_for_swift) as follows:

```
If you want to expose an Objective-C API to Swift with a different declaration,
but a similar underlying implementation, use the NS_REFINED_FOR_SWIFT macro.
When you import an Objective-C API into Swift, you can adopt Swift-only types
such as tuples. You can also reorder, combine, and rename parameters so the API
matches other Swift APIs.
```

This function has been [re-written in the `RealmSwift` SDK](https://github.com/realm/realm-cocoa/blob/master/RealmSwift/Sync.swift#L338) and is available there:
```
func configuration<T: BSON>(partitionValue: T) -> Realm.Configuration {
    let config = self.__configuration(withPartitionValue: ObjectiveCSupport.convert(object: AnyBSON(partitionValue))!)
    return ObjectiveCSupport.convert(object: config)
}
```

However, if you use the Objective-C framework `Realm` instead of `RealmSwift` [the function call changes slightly](https://developer.apple.com/documentation/swift/objective-c_and_c_code_customization/improving_objective-c_api_declarations_for_swift):
```
Applying the NS_REFINED_FOR_SWIFT macro exposes the existing Objective-C API
for reuse in your refined API. The existing API is renamed with double underscores (__)
when it's imported, to help prevent you from accidentally using the existing API elsewhere.
```

I have prepared [an example repository](https://github.com/DominicFrei/Playground/tree/realm/realm-cocoa/issues/6615) that shows your reproduction steps and the resolution.

Your call from above
```
let configuration = user.configuration(partitionValue: user?.identity)
```
(see https://github.com/DominicFrei/Playground/commit/1f01f373604166f6060a45b1940ac5748c6b1ff9#diff-61a64f31044fbfd03856ead0b699077b15bc799953059f5dd6711e4c3d362ca3R22)

would look like this:
```
let configuration = user?.__configuration(withPartitionValue: "" as RLMBSON)
```
(see https://github.com/DominicFrei/Playground/commit/4d82ea953ac4139e8f61f2fc8d38548fc9595465#diff-61a64f31044fbfd03856ead0b699077b15bc799953059f5dd6711e4c3d362ca3R22)

**Comment by ericjordanmossman** [comment] 2021-01-21 16:20
Sorry @DominicFrei, I forgot to mention. @levelchanger also had [this](https://github.com/realm/realm-cocoa/issues/6857) related issue. Where [this](https://github.com/realm/realm-cocoa/pull/6886) is also available.

**Comment by DominicFrei** [comment] 2021-01-21 17:00
I've just spoken to @ericjordanmossman about this as a general solution:
- The above mentioned way of using `__` is a viable way to go.
- However, [our recommended solution for mixed projects](https://realm.io/docs/objc/latest/#realmswift-and-realm-objective-c) is to use both `Realm` and `RealmSwift`.

@andreasley The solution shown in [my example repository](https://github.com/DominicFrei/Playground/tree/realm/realm-cocoa/issues/6615) is probably also valid for you from what I can see. Using `RLMApp` instead of `App` since you are accessing the Objective-C layer.

@levelchanger @andreasley I will close this issue for now. Feel free to re-open it and provide further information if the above solutions don't fix your problems.

**Closed by DominicFrei** 2021-01-21 17:00 UTC
Labels: O-Community
