### ISSUE TITLE
std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0> >(void*, void*) 

### ISSUE THREAD

**Issue by ganesh-ananthan** [realm/realm-cocoa#6853] opened 2020-10-13 13:48 UTC
Application got crashed while accessing realm, we do access only desired known tables. But in the exception it's pointing no such table found. 

`Incident Identifier: 0af7d1fd-9805-4b24-841a-1b0079d068ec
CrashReporter Key:   8CA543BC-C77B-4085-940F-7DCC8AFB243A
Hardware Model:      iPad6,12
Process:         appName [437]
Path:            /private/var/containers/Bundle/Application/50510610-5101-4F92-BE7F-D647A59171AA/appName.app/appName
Identifier:      com.domain.phone2
Version:         4.0.970 (4.0.970)
Code Type:       arm64
Parent Process:  ??? [1]

Date/Time:       2020-10-12T17:14:40.999Z
Launch Time:     2020-10-12T17:05:26Z
OS Version:      iPhone OS 14.0.1 (18A393)
Report Version:  104

Exception Type:  SIGABRT
Exception Codes: #0 at 0x1b604195c
Crashed Thread:  28

Application Specific Information:
*** Terminating app due to uncaught exception 'realm::NoSuchTable', reason: 'No such table exists
Exception backtrace:
0   Realm                               0x000000010696c3f0 _ZN5realm11NoSuchTableC1Ev + 60
1   Realm                               0x0000000106a2913c _ZNK5realm13ConstTableRef5checkEv + 120
2   Realm                               0x0000000106a291a8 _ZNK5realm13ConstTableRefptEv + 20
3   Realm                               0x0000000106978384 _ZN5realm11Transaction14import_copy_ofENS_13ConstTableRefE + 32
4   Realm                               0x000000010684e4a8 _ZN5realm5QueryC2EPKS0_PNS_11TransactionENS_13PayloadPolicyE + 312
5   Realm                               0x000000010697871c _ZN5realm11Transaction14import_copy_ofERNS_5QueryENS_13PayloadPolicyE + 64
6   Realm                               0x0000000106767e44 _ZN5realm5_impl15ResultsNotifier12do_attach_toERNS_11TransactionE + 64
7   Realm                               0x0000000106723efc _ZN5realm5_impl18CollectionNotifier9attach_toENSt3__110shared_ptrINS_11TransactionEEE + 36
8   Realm                               0x0000000106753a70 _ZN5realm5_impl16RealmCoordinator19run_async_notifiersEv + 856
9   Realm                               0x00000001067536bc _ZN5realm5_impl16RealmCoordinator9on_changeEv + 24
10  Realm                               0x0000000106727c68 _ZN5realm5_impl20ExternalCommitHelper6listenEv + 204
11  Realm                               0x0000000106728740 _ZNSt3__114__thread_proxyINS_5tupleIJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS3_EEEEZN5realm5_impl20ExternalCommitHelperC1ERNS8_16RealmCoordinatorEE3$_0EEEEEPvSE_ + 52
12  libsystem_pthread.dylib             0x00000001d0a9eb70 _pthread_start + 288
13  libsystem_pthread.dylib             0x00000001d0aa3880 thread_start + 8'

Last Exception Backtrace:
0   libc++abi.dylib                      0x000000019f780154 std::__terminate(void (*)()) + 16
1   libc++abi.dylib                      0x000000019f782e68 __cxa_rethrow + 140
2   Realm                                0x00000001067287ec std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0> >(void*, void*) (external_commit_helper.cpp:180)
3   libsystem_pthread.dylib              0x00000001d0a9eb70 _pthread_start + 284
4   libsystem_pthread.dylib              0x00000001d0aa3880 thread_start + 4

Thread 28 Crashed:
0   libsystem_kernel.dylib               0x00000001b604195c __pthread_kill + 8
1   libsystem_c.dylib                    0x0000000194aa8934 abort + 96
2   appName                        	 0x00000001054a5618 uncaught_exception_handler + 68
3   appName                         	 0x000000010554b6ec uncaught_cxx_exception_handler(MSCrashesUncaughtCXXExceptionInfo const*) (MSCrashes.mm:135)
4   appName                        	 0x0000000105556cb0 MSCrashesUncaughtCXXTerminateHandler() (MSCrashesCXXExceptionHandler.mm:95)
5   libc++abi.dylib                      0x000000019f780154 std::__terminate(void (*)()) + 12
6   libc++abi.dylib                      0x000000019f782e68 __cxa_rethrow + 140
7   Realm                                0x00000001067287ec std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0> >(void*, void*) (external_commit_helper.cpp:180)
8   libsystem_pthread.dylib              0x00000001d0a9eb70 _pthread_start + 284
9   libsystem_pthread.dylib              0x00000001d0aa3880 thread_start + 4

Thread 0:
0   libsystem_kernel.dylib               0x00000001b60423a0 __ulock_wait + 8
1   libc++.1.dylib                       0x000000019f75a490 std::__1::thread::join() + 28
2   Realm                                0x0000000106727a70 realm::_impl::ExternalCommitHelper::~ExternalCommitHelper() (external_commit_helper.cpp:194)
3   Realm                                0x0000000106758998 std::__1::unique_ptr<realm::_impl::ExternalCommitHelper, std::__1::default_delete<realm::_impl::ExternalCommitHelper> >::reset(realm::_impl::ExternalCommitHelper*) (memory:2339)
4   Realm                                0x0000000106752584 realm::_impl::RealmCoordinator::~RealmCoordinator() (memory:2610)
5   Realm                                0x0000000106719910 std::__1::shared_ptr<realm::_impl::CollectionNotifier>::~shared_ptr() (memory:3544)
6   Realm                                0x0000000106825518 realm::Realm::~Realm() (memory:4520)
7   Realm                                0x0000000106719910 std::__1::shared_ptr<realm::_impl::CollectionNotifier>::~shared_ptr() (memory:3544)
8   libobjc.A.dylib                      0x000000019f683c40 object_cxxDestructFromClass(objc_object*, objc_class*) + 108
9   libobjc.A.dylib                      0x000000019f699a04 objc_destructInstance + 84
10  libobjc.A.dylib                      0x000000019f6a06f8 _objc_rootDealloc + 48
11  Realm                                0x00000001067f6580 -[RLMRealm dealloc] (RLMRealm.mm:814)
12  libobjc.A.dylib                      0x000000019f6a3584 AutoreleasePoolPage::releaseUntil(objc_object**) + 196
13  libobjc.A.dylib                      0x000000019f6a3460 objc_autoreleasePoolPop + 204
14  CoreFoundation                       0x000000018be69a1c _CFAutoreleasePoolPop + 24
15  CoreFoundation                       0x000000018bddcf00 __CFRunLoopPerCalloutARPEnd + 40
16  CoreFoundation                       0x000000018bdd812c __CFRunLoopRun + 2544
17  CoreFoundation                       0x000000018bdd7200 CFRunLoopRunSpecific + 568
18  GraphicsServices                     0x00000001a1ed2598 GSEventRunModal + 156
19  UIKitCore                            0x000000018e69d004 -[UIApplication _run] + 1048
20  UIKitCore                            0x000000018e6a25d8 UIApplicationMain + 160
21  appName                        	 0x00000001047153c4 main (AppDelegate.swift:39)
22  libdyld.dylib                        0x000000018bab6598 start + 0`

Realm Version : 5.4.7
CocoaPod Version: 1.9.3

**Comment by ericjordanmossman** [comment] 2020-10-13 13:52
@ganesh-ananthan 
Closing as duplicate of #6767. If you have any more information on the crash please update in that thread.

**Closed by ericjordanmossman** 2020-10-13 13:52 UTC
Labels: O-Community

**Comment by ganesh-ananthan** [comment] 2020-10-14 02:37
the mentioned ticket #6767 used realm version 5.3.2, we are using latest realm version 5.4.7. As per finnschiermer's comment on that ticket, they must have enough logs in current stack trace. Consider this as fresh issue and analyse.

**Comment by ericjordanmossman** [comment] 2020-10-15 19:42
I understand, thank you. We prefer to have a single issue for crashes that are present in multiple versions. Otherwise we'd have 10 different issues for the same crash on different versions.
Feel free to comment in 6767 with updated info for the latest version.
