### ISSUE TITLE
Use a designated initializer for RLMObject

### ISSUE THREAD

**Issue by jeremiegirault** [realm/realm-cocoa#738] opened 2014-08-05 13:19 UTC
With the following class custom class
```
@interface MyClass : RLMObject
@end

@implementation MyClass
- (instancetype)init {
    self = [super init];
    if (self) {
        [self doSomethingImportant];
    }
}
@end
```
When I create the object with [[MyClass alloc] init] doSomethingImportant is called 
But when an object is pulled out of the realm, the following initializer is called
```
- (instancetype)initWithRealm:(RLMRealm *)realm
                       schema:(RLMObjectSchema *)schema
                defaultValues:(BOOL)useDefaults {
    self = [super init];
    ...
```
Due to the self = [super init]; code, I have different behavior between objects I create and objects I pull out of the Realm.

Maybe an overridable -(void)RLMObject::RLMWakeUp method would be useful to execute initialization code in both cases.

Thanks

**Comment by jpsim** [comment] 2016-03-29 00:06
We believe that this issue is a duplicate of #1994. Closing.

**Closed by jpsim** 2016-03-29 00:06 UTC
Labels: S:Idea Backlog, T:Enhancement
