### ISSUE TITLE
wierd problem with realm and object mapper at the same time

### ISSUE THREAD

**Issue by M0TRIX** [realm/realm-cocoa#6912] opened 2020-11-04 15:11 UTC
var myCourses :[Course]?

` ServiceAPI.getAllCourse(executeMessage: executeMessage, onResponse: { (response) in
            
            self.myCourses?.removeAll()
            self.myCourses = response.result.data
            self.tableView.reloadData()
            
            self.setCourseEntities(courseEntities: response.result.data)
            if (self.myCourses != nil) {
               // ShopDataSource.instance.save(shopEntity: self.myCourses ?? []) // problem happens here
            }
            
        }) { (error:Error) in
            print("hg",error)
        }`

` func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "shopCell", for: indexPath) as! ShopTableViewCell
        cell.indexpath = indexPath
        cell.bind(object: myCourses?[indexPath.row])
        cell.effect(cell: cell, row: indexPath.row)
        return cell
    }`

my " myCourse" object contains 4 objects and working correctly. but when I save it with realm tableView shows just one object

**Comment by leemaguire** [comment] 2020-11-04 15:53
duplicate of https://github.com/realm/realm-cocoa/issues/6913

**Closed by leemaguire** 2020-11-04 15:53 UTC
Labels: O-Community
