### ISSUE TITLE
Migration of corrupted objects

### ISSUE THREAD

**Issue by mladjan** [realm/realm-cocoa#3087] opened 2016-01-10 15:04 UTC
With have STLUser model and STLGeneral model (all models subclass this STLGeneral model).
STLGeneral model has id as primary key and indexed property. Somehow I have two user objects in DB which has id 0 and all fields empty: http://cloud.blgrd.co/3j0w1c0J2f3M
Not sure how this happened at all!

And we changed some things (added some new field in user model), so we needed to migrate our db, and we are getting into problem with some users with these corrupted objects in db "Primary key property 'id' has duplicate values after migration"
http://cloud.blgrd.co/2P2K0L142U45

We are facing this problem with some users in production, and I'm not sure how to fix this properly.

**Comment by mrackwitz** [comment] 2016-01-11 12:09
Are you able to delete the faulty objects with empty fields in the migration?

**Comment by mladjan** [comment] 2016-01-11 12:44
I can try, but not sure is this the best option? I was thinking to add some checks before adding object to db to fix this in the future also.

**Comment by mladjan** [comment] 2016-01-11 13:39
Hmm, when I try to delete "oldObject" with deleteObject on migration instance, I'm getting: "Can only delete an object from the Realm it belongs to." 
I don't know the better way to delete it :|

**Comment by mrackwitz** [comment] 2016-01-11 17:34
The objects provided to `-[RLMMigration deleteObject:]` have to be the new objects (via the second argument of the block) received while enumerating via `-[RLMMigration enumerateObjects:block:]`.

**Comment by mrackwitz** [comment] 2016-01-11 17:36
I have another question, based on what you wrote here:

>I was thinking to add some checks before adding object to db to fix this in the future also.

Those objects, you want to get rid of now while migrating, do they have been valid with the previous schema?

**Comment by mladjan** [comment] 2016-01-11 18:59
That's the problem, they was valid, and I just added one array (to many relation) in user model.

**Comment by mrackwitz** [comment] 2016-01-11 19:33
Can you trace that back to a specific operation in a write transaction? If so, could you please share the related code with us?

**Comment by jpsim** [comment] 2016-01-11 19:48
@mrackwitz I think what @mladjan is saying is that the object is "corrupt" at the business logic level of his app rather than being an invalid Realm object.

**Comment by mladjan** [comment] 2016-01-11 19:55
By "corrupt" I think about being able to add two objects with the same id (which is defined as primary key).

**Comment by mladjan** [comment] 2016-01-12 09:43
Deleting "newObject" solves migration issue. I added business logic to prevent getting objects in realm without id, but I still think that Realm should not allow me to add a object in realm with the same ID twice.

**Comment by jpsim** [comment] 2016-01-12 19:09
If your ID property wasn't a primary key when you created these objects, how was Realm supposed to know you wanted it to be unique? Until a uniqueness constraint is added in Realm (see [Primary Keys](https://realm.io/docs/objc/latest/#primary-keys)), you'll need to manage that uniqueness yourself.

**Comment by mladjan** [comment] 2016-01-12 21:47
ID property IS primary key from day one :)

**Comment by jpsim** [comment] 2016-01-12 22:05
Ah, then this is certainly a bug. Can you share some code that successfully creates multiple objects with the same primary key value? We have measures in place to prevent this from happening.

**Comment by mladjan** [comment] 2016-01-12 22:39
Nobody knows how this happened, so I just figured out when I wanted to do a
migration. The only difference then "usual" is:
I have STLGeneral, which have id, createdAt and updatedAt, and all other
models are subclases of STLGeneral.

**Comment by jpsim** [comment] 2016-01-12 22:43
> Nobody knows how this happened

Indeed. What would you like us to do about this then, since we don't have any actionable information to go on?

**Comment by jpsim** [comment] 2016-01-16 00:50
I'm closing this as we don't have any actionable information to go on. @mladjan if you manage to find out more information about this issue, or ideally steps to reproduce, please file a new issue and we'll be happy to take a closer look.

**Closed by jpsim** 2016-01-16 00:50 UTC
Labels: Help, pending
