### ISSUE TITLE
When object is updated, all its collections are destroyed

### ISSUE THREAD

**Issue by superandrew** [realm/realm-cocoa#4228] opened 2016-10-17 12:00 UTC
## Goals

Update realm object without destroying its data

## Expected Results

When I update a realm object, I would expect all of its collections to remain intact

## Actual Results

I update the object, and the object which has been updated, has all of its collection emptied.

## Code Sample

```swift
if let n = Mapper<Node>().map(JSONObject: jsonResponse.result.value)
{
    let realm = try! Realm()
    try! realm.write {
        realm.create(Node.self, value: n, update: true)
    }
}
```

## Version of Realm and Tooling

Realm version: 2.0.2

Xcode version: 8

iOS/OSX version: 10.12

Dependency manager + version: CocoaPods

**Comment by jpsim** [comment] 2016-10-17 23:11
It would help if you shared much more relevant information in your report.

For example, what's the value of `n`? What's the value of the `Node` object with the primary key being updated before and after the code sample you posted? What do you mean the collection is emptied? What does your `Node` model class look like? How about other relevant model definitions? The section entitled "Steps to Reproduce" doesn't actually include steps to reproduce...

For example, if your schema looks like this:

```swift
class IntValue: Object {
  dynamic var value = 0
}
class Node: Object {
  dynamic var pk = 0
  let list = List<IntValue>()
  override static func primaryKey() -> String? {
    return "pk"
  }
}
```

and if the value of the `Node` object is this before:

```swift
Node(pk: 0, list: [IntValue(value: 0), IntValue(value: 1)])
```

and then you update it with an empty list:

```swift
let n = ["pk": 0, "list": []]
realm.create(Node.self, value: n, update: true)
```

Then it's expected that `list` will be empty because you're setting it to an empty array.

If you don't wish to set a property on an object during `Realm.create(_:value:update: true)`, you'll need to omit the property from the value. For example:

```swift
let n = ["pk": 0]
realm.create(Node.self, value: n, update: true)
```

Which wouldn't affect the `Node` object's `list` property.

**Comment by superandrew** [comment] 2016-10-18 08:03
@jpsim you're absolutely right. Unfortunately in my case I have some difficulties creating a xcode demo project because the data is retrieved via VPN.

I filed this issue because I thought it was a design choice to reset the lists connected to an object when you update it. 

I must say that I update the object after mapping it with ObjectMapper, and in fact now that I had the time to check, it is probably the latter that empties the collections.

**Comment by jpsim** [comment] 2016-10-18 23:29
> I filed this issue because I thought it was a design choice to reset the lists connected to an object when you update it.

Just when you specify that the object should be updated with an empty list, which appears to be the case here.

I hope you consider this matter resolved, so I'll be closing this issue. Feel free to reopen if you have any further questions or if you think we should do anything differently here.

**Closed by jpsim** 2016-10-18 23:29 UTC
Labels: T:Help
