### ISSUE TITLE
Swift: Nested JSON Objects

### ISSUE THREAD

**Issue by lewo** [realm/realm-cocoa#1386] opened 2015-01-22 01:08 UTC
Hi, just playing around with the new Swift syntax (al-swift branch) and having the following issue trying to write the following JSON data to the default Realm:

```
2015-01-22 10:56:18.298 N2[11853:729175] +[RLMStandalone_Ward createOrUpdateInRealm:withObject:]: unrecognized selector sent to class 0x7fcf5c8d9800
2015-01-22 10:56:18.312 N2[11853:729175] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[RLMStandalone_Ward createOrUpdateInRealm:withObject:]: unrecognized selector sent to class 0x7fcf5c8d9800'`
```

```json
{"hospitals":[{"id":1,"name":"PPH","wards":[{"id":1,"name":"Jacaranda Surgical"},{"id":2,"name":"Acacia Cancer and Haematology"},{"id":3,"name":"Magnoli "},{"id":4,"name":"Obstetric "},{"id":5,"name":"Intensive Care Unit"},{"id":6,"name":"Day Surgery Unit"},{"id":7,"name":"High Dependency Unit"},{"id":8,"name":"Coronary Care Unit"},{"id":9,"name":"Day Infusion Service"}]}]}
```

My Objects look like:

```swift
import RealmSwift

class Hospital: Object {    
    dynamic var id: Int = 1
    dynamic var name : String = ""
    
    override class func primaryKey() -> String {
        return "id"
    }
    let wards = List<Ward>()
}

class Ward: Object {
    
    dynamic var id: Int = 1
    dynamic var name : String = ""

    var hospitals: [Hospital] {
        return linkingObjectsOfClass("Hospital", forProperty: "wards") as [Hospital]
    }
    override class func primaryKey() -> String {
        return "id"
    }
}
```
and I call:

```swift
Hospital.createInRealm(realm, withObject: result)
```
where result = the JSON data above.

Works all ok with the old RLMObject syntax and using: 
```swift
Patient.createOrUpdateInDefaultRealmWithObject(result)
```
Thanks

**Comment by alazier** [comment] 2015-01-23 21:42
We don't yet have tests for the new apis to validate creating/updating nested objects. Sounds like this is probably a bug. Thanks for reporting.

**Comment by jpsim** [comment] 2015-01-24 00:02
Looks like this is a duplicate of #1322.

**Comment by jpsim** [comment] 2015-01-24 01:17
After further investigation, #1322 is a different issue altogether, so I'm reopening this.

**Comment by lewo** [comment] 2015-01-26 23:44
Thanks, will jump back to this branch once it's fixed :+1:

**Comment by segiddins** [comment] 2015-01-29 23:22
@lewo I just copy-pasted your code into an example app and was unable to reproduce the issue you reported. Could you either try again with the latest bits from the al-swift branch, or share an example project that reproduces the issue? Thanks!

**Comment by lewo** [comment] 2015-01-30 00:38
Still happening on the latest al-swift branch, I'll see if I can create an example. Not sure if this helps but this is how I'm calling createInRealm and println(result) output below.:

```swift
 dispatch_async(queue)  {
       let realm = defaultRealm()
                    realm.write() {
                           Hospital.createInRealm(realm, withObject: result)
                     }
}
```

```json
{
    id = 1;
    name = PPH;
    wards =     (
                {
            id = 1;
            name = "Jacaranda Surgical";
        },
                {
            id = 2;
            name = "Acacia Cancer and Haematology";
        },
                {
            id = 3;
            name = "Magnoli ";
        },
                {
            id = 4;
            name = "Obstetric ";
        },
                {
            id = 5;
            name = "Intensive Care Unit";
        },
                {
            id = 6;
            name = "Day Surgery Unit";
        },
                {
            id = 7;
            name = "High Dependency Unit";
        },
                {
            id = 8;
            name = "Coronary Care Unit";
        },
                {
            id = 9;
            name = "Day Infusion Service";
        }
    );
}
```

**Comment by lewo** [comment] 2015-01-30 03:40
And if I remove the primary key on the Ward object it works all ok.

**Comment by segiddins** [comment] 2015-01-30 20:56
Hm, I still can't reproduce the issue. Is there any way you could share an example project that demonstrates it? Thanks!

**Comment by segiddins** [comment] 2015-01-30 22:35
@lewo I just managed to reproduce the issue and am digging into it. Thanks so much for reporting it!

**Comment by segiddins** [comment] 2015-01-31 00:20
@lewo I think we've fixed the issue in https://github.com/realm/realm-cocoa/commit/f27ab75270bf5105285aa8fed53e8907914415b1, which should make it onto `al-swift` soon

**Comment by lewo** [comment] 2015-01-31 01:17
Great thanks, I'll give it a try.

**Comment by lewo** [comment] 2015-01-31 02:20
Works the first time on loading the JSON data:-) but fails on the second reload due to the primary key: 

RLMAccessor.mm

```Swift
static inline void RLMSetValueUnique(__unsafe_unretained RLMObjectBase *obj, NSUInteger colIndex, NSString *propName, long long val) {
    RLMVerifyInWriteTransaction(obj);
    size_t row = obj->_row.get_table()->find_first_int(colIndex, val);
    if (row == obj->_row.get_index()) {
        return;
    }
    if (row != tightdb::not_found) {
        NSString *reason = [NSString stringWithFormat:@"Can't set primary key property '%@' to existing value '%lld'.", propName, val];
        @throw [NSException exceptionWithName:@"RLMException" reason:reason userInfo:nil];
    }
    obj->_row.set_int(colIndex, val);
}
```
2015-01-31 12:15:14.194 N2[20598:929736] *** Terminating app due to uncaught exception 'RLMException', reason: 'Can't set primary key property 'id' to existing value '1'.'

**Comment by foffer** [comment] 2015-02-11 13:04
>Works the first time on loading the JSON data:-) but fails on the second reload due to the primary key:
>RLMAccessor.mm
I too get the above error upon re-fetching the JSON. Let me know if I can provide any info to help the debugging.

**Comment by jpsim** [comment] 2015-03-25 21:06
@foffer could you try the latest version of `RealmSwift`, currently available from the `master` branch? We'll be officially releasing it shortly and would love to make sure this is fixed.

**Comment by lewo** [comment] 2015-03-26 06:50
I'm using realmswift now from the master branch. Works perfectly :-)

**Comment by jpsim** [comment] 2015-03-26 06:57
Great to hear! Please share your thoughts & issues you may run into.

**Closed by jpsim** 2015-03-26 06:57 UTC
Labels: bug, pending
