### ISSUE TITLE
Assertion failed: _impl::TableFriend::is_link_type(ColumnType(type))

### ISSUE THREAD

**Issue by tspecht** [realm/realm-cocoa#1662] opened 2015-03-18 16:25 UTC
```
../tightdb/impl/transact_log.hpp:741: [realm-core-0.88.5] Assertion failed: _impl::TableFriend::is_link_type(ColumnType(type))
0   MyApp                            0x006d72ad _ZN7tightdb4util9terminateEPKcS2_lbxx + 580
1   MyApp                            0x0075702f _ZN7tightdb5_impl17TransactLogParser8do_parseINS_5Group16TransactReverserEEEvRT_ + 4982
2   MyApp                            0x007557b7 _ZN7tightdb5Group16reverse_transactEmRKNS_10BinaryDataE + 182
3   MyApp                            0x0075da0f _ZN7tightdb11SharedGroup32do_rollback_and_continue_as_readEPKcS2_ + 22
4   MyApp                            0x0075286d _ZN7tightdb5_impl17WriteLogCollector26do_rollback_write_transactERNS_11SharedGroupE + 92
5   MyApp                            0x0075d987 _ZN7tightdb11SharedGroup29rollback_and_continue_as_readEv + 98
6   MyApp                            0x0065abe7 _ZN7tightdb14LangBindHelper29rollback_and_continue_as_readERNS_11SharedGroupE + 14
7   MyApp                            0x00656c3f -[RLMRealm cancelWriteTransaction] + 206
8   MyApp                            0x00618695 RLMUpdateRealmToSchemaVersion + 624
9   MyApp                            0x006546c9 +[RLMRealm realmWithPath:key:readOnly:inMemory:dynamic:schema:error:] + 2988
10  MyApp                            0x00653721 +[RLMRealm realmWithPath:readOnly:error:] + 192
11  MyApp                            0x006535c9 +[RLMRealm realmWithPath:] + 152
12  MyApp                            0x0016c65b -[DSAppDelegate application:didFinishLaunchingWithOptions:] + 8434
13  UIKit                               0x316095a7 <redacted> + 274
14  UIKit                               0x31608efb <redacted> + 1610
15  UIKit                               0x3160358b <redacted> + 714
16  UIKit                               0x3159f709 <redacted> + 3540
17  UIKit                               0x3159e871 <redacted> + 72
18  UIKit                               0x31602cc9 <redacted> + 616
19  GraphicsServices                    0x33bd4aed <redacted> + 608
20  GraphicsServices                    0x33bd46d7 <redacted> + 34
21  CoreFoundation                      0x2ed48ab7 <redacted> + 34
22  CoreFoundation                      0x2ed48a53 <redacted> + 346
23  CoreFoundation                      0x2ed47227 <redacted> + 1398
24  CoreFoundation                      0x2ecb1f0f CFRunLoopRunSpecific + 522
25  CoreFoundation                      0x2ecb1cf3 CFRunLoopRunInMode + 106
26  UIKit                               0x31601ef1 <redacted> + 760
27  UIKit                               0x315fd16d UIApplicationMain + 1136
28  MyApp                            0x0018de25 main + 116
29  libdyld.dylib                       0x399d5ab7 <redacted> + 2
IMPORTANT: if you see this error, please send this log to help@realm.io.
```
The error occured while executing a normal migration where a 1-m foreign key was removed.

**Comment by segiddins** [comment] 2015-03-23 18:15
@tspecht I just tried to reproduce this issue, and was unable to. If you could share an example project that demonstrates it, that would be immensely helpful. Thanks for sending this in!

**Comment by tspecht** [comment] 2015-03-23 18:16
@segiddins sorry but won't be able to, the issue just occurred once I'm afraid. Just posted it here because the error message said so ;)

**Comment by segiddins** [comment] 2015-03-23 18:17
In that case, thanks for sharing it! I'm going to close this issue, but I've opened a ticket with our Core team to investigate. Feel free to comment if you see this again.

**Closed by segiddins** 2015-03-23 18:17 UTC

**Comment by calmez** [comment] 2015-06-02 12:08
I just ran into this issue as well. It seems to be reproducible each time with the following scenario:
I had a RLMObject subclass removed and delete all objects of that class from the default realm. There is another RLMObject subclass that holds references to the deleted one in a RLMArray property. Of course this property is deleted during the migration (happens automatically).
From what I can see the migration seems to be aborted and then the crash happens.

**Comment by calmez** [comment] 2015-06-02 12:58
I found out that this only happens when deleting the objects either via the realm's or the migration's ```deleteObject:```. With ```deleteDataForClassName:``` on ```RLMMigration``` from version ```0.93.1``` though the migrations seem to run through.

**Comment by lbanders** [comment] 2015-07-12 07:00
I have also seen this error during migration 0.93.2.
Given I have migration for version 1, 2, 3 and introduce version 4.
I have a field, field1 in version 1 which I rename to field1mk1 in version 2. 
Now, in version 4, I rename this field again to field1mk2.
Then I will get the above error when migrating from a database version 1 as field1mk1 is not part of the new datamodel.
This was NOT my expected behaviour based on your documentation on the migration block.

**Comment by jpsim** [comment] 2015-09-07 18:18
Hi all, we just fixed a crash due to an assertion being triggered when rolling back a transaction in which an RLMObject or RLMArray property was removed.

We believe this addresses the problem discussed here. We're aiming to ship this fix in the next major release of Realm (should be 0.96).

Thanks for your patience!
