### ISSUE TITLE
ANY  (bb.id1 = '1' AND bb.id2 = '2')  error

### ISSUE THREAD

**Issue by github2016a** [realm/realm-cocoa#1889] opened 2015-05-09 14:22 UTC
hi guys, i'm using RealmsSwift.
i have two class:
```swift
class AA: Object {
    let bb = List<BB>()
}
class BB: Object {
    dynamic var id1 : String = ""
    dynamic var id2 : String = ""
}
```
```swift
var a = AA()
var b = BB()
b.id1 = "1"
b.id2 = "1"
a.bb.append(b)
            
var b2 = BB()
b2.id1 = "2"
b2.id2 = "2"
a.bb.append(b2)

public let realm = Realm()
realm.write{
    realm.add(a)
}
```
How should i use the **filter** to get AA whose bb has a row (id1 = '1' and id2 = '2')
if i write 
```swift
realm.objects(AA).filter("ANY  bb.id1 = '1' AND ANY bb.id2 = '2'").count  // get 1,not right
```
and 
```swift
realm.objects(AA).filter("ANY  (bb.id1 = '1' AND bb.id2 = '2')")  // error
```
so how should i use filter?

**Comment by bdash** [comment] 2015-05-11 20:05
The first predicate that you tried doesn't do what you expect. It's filtering for an `AA` object that has at least one `BB` with `id1 = '1'` and at least one `BB` with `id2 = '2'`. There's no requirement that the `BB` objects in each case be the same object.

I think the predicate you're looking for is `SUBQUERY(bb, $bb, $bb.id1 = '1' AND $bb.id2 = '2').@count > 0`. Unfortunately this uses `SUBQUERY` which we do not yet support (see issue #1490).

**Comment by bdash** [comment] 2015-05-11 20:18
Duplicate of #1490.

**Closed by bdash** 2015-05-11 20:18 UTC

**Comment by menhui222** [comment] 2016-01-07 09:16
class AA: Object {
    dynamic var id = ""
    dynamic var bb :BB!
}
class BB: Object {
    dynamic var id1 : String = ""
    dynamic var id2 : String = ""
}

realm.objects(AA).filter("id = "1" AND bb.id1 = "2"")

**Comment by menhui222** [comment] 2016-01-07 09:17
What do I do

**Comment by jpsim** [comment] 2016-01-07 16:40
`"id = "1" AND bb.id1 = "2""` isn't a valid Swift string so it won't compile. This should be `"id = '1' AND bb.id1 = '2'"`. See [Apple's Swift docs on strings](https://developer.apple.com/library/ios/documentation/Swift/Conceptual/Swift_Programming_Language/StringsAndCharacters.html) to learn more.

**Comment by menhui222** [comment] 2016-01-08 01:46
I mean can queries can be between two table
realm.objects(AA).filter("id = '1' AND bb.id1 = '2' ")

**Comment by jpsim** [comment] 2016-01-08 03:12
I believe so.
