### ISSUE TITLE
Realm notification enumname

### ISSUE THREAD

**Issue by FabianTerhorst** [realm/realm-cocoa#4086] opened 2016-09-14 07:18 UTC
**Feature Request**:

Notification enum from realm has the same name like Foundation.Notification. Its not possible anymore to use Notification without Foundation.Notification, because realm is using the same name.

Realm version: 1.0.2

Xcode version: 8

Dependency manager + version: cocoapods 1.1

**Comment by jpsim** [comment] 2016-09-14 16:49
Thanks for filing this @FabianTerhorst. I'm a bit torn on this, since this is Swift's name spacing working "as designed", but obviously to have your code stop compiling because you `import RealmSwift` is obviously not ideal. On the other hand, renaming to `RealmSwift.RealmNotification` isn't terribly elegant either.

I'll discuss this with the team and report back with what we decide.

As far as I can tell, this is only an issue with `Notification`. Are there other types that collide with Foundation, AppKit or UIKit?

**Comment by bdash** [comment] 2016-09-14 16:57
`RealmSwift.Error` conflicting with `Swift.Error` is something that has been mentioned as well.

**Comment by jpsim** [comment] 2016-09-14 18:10
We're likely to nest `Notification` in `Realm`, but keep `RealmSwift.Error` at the top level, since it applies to the whole framework and can't really be nested, and shouldn't be renamed.

@FabianTerhorst I'll be closing this ticket now, you can follow progress on our Swift 3 API changes in #4078.

**Closed by jpsim** 2016-09-14 18:10 UTC
Labels: T:Help
