### ISSUE TITLE
Unable to open a realm at path after set NSFileProtectionNone

### ISSUE THREAD

**Issue by yreaction** [realm/realm-cocoa#3785] opened 2016-06-21 16:00 UTC
Hi there, I've followed the documentation here for solve our current issue with [background refresh](https://realm.io/docs/swift/latest/#using-realm-with-background-app-refresh), exactly with the same default realm and after the migration block.

```swift
// Set up
let realm = try! Realm()
// Get our Realm file's parent directory
let folderPath = realm.configuration.fileURL!.URLByDeletingLastPathComponent!.path!
// Disable file protection for this directory
try! NSFileManager.defaultManager().setAttributes([NSFileProtectionKey: NSFileProtectionNone],
                                                  ofItemAtPath: folderPath)
```
But still, we different errors like if the file was not create yet:

> fatal error: 'try!' expression unexpectedly raised an error: Error Domain=io.realm Code=2 "Unable to open a realm at path '/var/mobile/Containers/Data/Application/E5A106ED-CCCC-47B5-B829-FC0F015D205B/Documents/default.realm.lock': open() failed: Operation not permitted." UserInfo={Error Code=2, NSFilePath=/var/mobile/Containers/Data/Application/E5A106ED-CCCC-47B5-B829-FC0F015D205B/Documents/default.realm.lock, Underlying=open("/var/mobile/Containers/Data/Application/E5A106ED-CCCC-47B5-B829-FC0F015D205B/Documents/default.realm.lock") failed: Operation not permitted, NSLocalizedDescription=Unable to open a realm at path '/var/mobile/Containers/Data/Application/E5A106ED-CCCC-47B5-B829-FC0F015D205B/Documents/default.realm.lock': open() failed: Operation not permitted.}: file /Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-703.0.18.8/src/swift/stdlib/public/core/ErrorType.swift, line 54

Can anyone help how to proper set up with the default realm for background fetching.

XCode 7.2
Realm 1.0.1

Thanks in advance

**Comment by jpsim** [comment] 2016-06-22 01:23
@yreaction could you please share a sample project that reproduces this behavior? The code you posted should work.

**Comment by jpsim** [comment] 2016-06-30 15:12
@yreaction just following up on my last request for a reproducible sample project. thanks.

**Comment by MikeKasperlik** [comment] 2016-07-06 07:51
We expiring the same issue. Unfortunately I can't reproduce this every time, but we get many of these crashes in Crashlytics. 

Setup is the same as above, setting the directory of realm to `NSFileProtectionNone` and when we do a background refresh the app crashes with the same error message.

**Comment by TimOliver** [comment] 2016-07-15 16:58
Following up this issue again. If you're having trouble with using Realm while the app is backgrounded, please make sure you've placed the Realm file in a directory and changed the `NSFileProtection` properties of the directory itself. 

Additionally, looking at that sample code, it may look like you're trying to change the protection rights of the `Documents` folder itself. It may be more appropriate to change the location of the default Realm to its own subfolder that can receive the permission rights.

It should just work. So without any sample code, we can't diagnose the problem.

Since @yreaction hasn't responded since the initial post, I'm going to close this issue. But please feel free to re-open it if more help is required.

**Closed by TimOliver** 2016-07-15 16:58 UTC
Labels: Reproduction Required, S:Waiting For User, T:Help
