### ISSUE TITLE
Building the 'master' branch from Carthage fails when cleaning/compiling 'PlaygroundFrameworkWrapper'

### ISSUE THREAD

**Issue by bensarz** [realm/realm-cocoa#4070] opened 2016-09-08 14:45 UTC
## Goals

I want to build the `master` branch using Carthage without errors.

## Expected Results

Successful build.

## Actual Results

```
*** xcodebuild output can be found in /var/folders/mt/xyqwwnr92dgbg8987kt45prr0000gn/T/carthage-xcodebuild.Wvz0yN.log
*** Building scheme "RealmSwift" in RealmExamples.xcworkspace
*** Building scheme "Realm" in RealmExamples.xcworkspace
*** Building scheme "PlaygroundFrameworkWrapper" in RealmExamples.xcworkspace
** CLEAN FAILED **


The following build commands failed:
       	Check dependencies
(1 failure)
** BUILD FAILED **


The following build commands failed:
       	Check dependencies
(1 failure)
warning: no umbrella header found for target 'PlaygroundFrameworkWrapper', module map will not be generated
warning: no umbrella header found for target 'PlaygroundFrameworkWrapper', module map will not be generated
A shell task (/usr/bin/xcrun xcodebuild -workspace /Users/[REDACTED]/Carthage/Checkouts/realm-cocoa/examples/ios/swift-2.2/RealmExamples.xcworkspace -scheme PlaygroundFrameworkWrapper -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** CLEAN FAILED **


The following build commands failed:
       	Check dependencies
(1 failure)
** BUILD FAILED **


The following build commands failed:
       	Check dependencies
(1 failure)
```

## Steps to Reproduce

Create a `Cartfile` containing:

```
github "realm/realm-cocoa" "master"
```

Run the following command:

```
$ carthage update --platform iOS
```

## Version of Realm and Tooling

Realm version: master branch

Xcode version: 8.0 GM

iOS/OSX version: 2.3 or 3.0

Dependency manager + version: Carthage

**Comment by jpsim** [comment] 2016-09-08 23:24
Duplicate of #4042, fix pending review in #4043.

**Closed by jpsim** 2016-09-08 23:24 UTC
