### ISSUE TITLE
RLMSetErrorOrThrow(NSError*, NSError* __autoreleasing*)

### ISSUE THREAD

**Issue by AyeChanPyaeSone** [realm/realm-cocoa#5447] opened 2017-11-02 07:07 UTC
I am using Realm (2.10.0) and I saw this on crash log. Please help me how to investigate further. 

> *** Terminating app due to uncaught exception 'RLMException', reason: 'mmap() failed: Cannot allocate memory size: 1048576 offset: 0'

<img width="1319" alt="screen shot 2017-11-02 at 3 04 59 pm" src="https://user-images.githubusercontent.com/8436265/32313801-8a4bb6b8-bfdf-11e7-9e61-1a7a460bcc2d.png">

**Comment by austinzheng** [comment] 2017-11-02 18:51
Thanks for getting in touch with us.

The error you're seeing is caused when the Realm file on disk grows too big. Realm uses [mmap](https://en.wikipedia.org/wiki/Mmap) to map the file into memory, but iOS has limitations on how big a file can be `mmap`ed.

More importantly, it's possible to use Realm incorrectly in such a way that the file grows far too big than it should. Please take a look at [this comment](https://github.com/realm/realm-cocoa/issues/5358#issuecomment-335583393) for more information on what causes this and what you can do to mitigate it. You will also want to read our [documentation on file sizes](https://realm.io/docs/objc/latest/#limitations-file-size).

**Comment by AyeChanPyaeSone** [comment] 2017-11-14 05:34
I am running realm transactions only on main thread. I will use compact method first. Thanks you so much.

**Comment by AyeChanPyaeSone** [comment] 2017-11-14 09:23
and Even though I compact it happens again. It happens again on 5s. Does it because of low ios phone?

**Comment by austinzheng** [comment] 2017-11-14 19:43
Once this error actually starts occurring it is too late for compaction. This means that you need both preventative measures: use compaction to keep the file itself from growing too big because of lots of free space inside the file; use best practices when running transactions on background queues (perhaps not applicable in your case).

Another possibility is that the database actually contains about that much data. Are you storing large amounts of binary data in your Realms, such as perhaps image files? We generally recommend that people don't store large binary data blobs directly within Realm for a variety of reasons, one of which is that it tends to increase database sizes to the point where the Realm file cannot be opened any longer.

**Comment by AyeChanPyaeSone** [comment] 2017-11-15 05:01
I don't store binary data in realm. for the images, I only saved URL. would that problem will solve if i store realm in server or somewhere not inside the app?

**Comment by kishikawakatsumi** [comment] 2017-11-15 05:57
@AyeChanPyaeSone Can you send us the file that causes the error for investigation?

**Comment by AyeChanPyaeSone** [comment] 2017-11-15 06:32
Yes. Can i send privately because my client data is inside the file?

**Comment by kishikawakatsumi** [comment] 2017-11-15 06:58
@AyeChanPyaeSone Please send it to `help@realm.io`. We treat your file privately.

**Comment by AyeChanPyaeSone** [comment] 2017-11-15 07:07
I sent the file. Please help check. Thanks you so much for your help.

**Comment by kishikawakatsumi** [comment] 2017-11-17 07:52
@AyeChanPyaeSone ​

Thank you for sending the file. But we cannot reproduce the issue. The file size is around 75MB, it is unlikely that a `mmap()` error will occur with this size. I also confirmed that the file can be opened correctly on my device. Can you make sure you are not sending another file? Can you check again whether the problem will be reproduced in your hand? If it reproduces please tell us more details of your environment, like device, OS etc.

**Comment by bdash** [comment] 2018-01-17 05:49
Closing due to the lack of further information. Feel free to reopen this if you're still in need of assistance and are able to provide the requested information.

**Closed by bdash** 2018-01-17 05:49 UTC
Labels: T:Help
