### ISSUE TITLE
Realm Combine Publisher Crash

### ISSUE THREAD

**Issue by willmorris44** [realm/realm-cocoa#7197] opened 2021-04-03 00:16 UTC
## Goals

Trying to sync my SwiftUI app using Realm Sync

/cc @simonask @tkaye407
## Expected Results

Changes on app to happen in cloud.
## Actual Results

App crashes when starting sync.
## Steps for others to Reproduce

Followed the steps here for using sync (copy pasted all code into project). My app looks exactly like the example.
https://docs.mongodb.com/realm/sdk/ios/integrations/swiftui/
- Copy code
- Create Cluster and database
- Put in development mode
- Turn on anon sign in
- Put app id into app
- Click run
- Should get below error in 'Combine.swift'
<img width="1271" alt="Screen Shot 2021-04-02 at 6 01 01 PM" src="https://user-images.githubusercontent.com/46915014/113462288-68c92400-93dd-11eb-8900-1eb713f96ed9.png">

## Code Sample

```
@main
struct SwiftUI_RealmApp: SwiftUI.App {
    let app: RealmSwift.App? = RealmSwift.App(id: "ID-GOES-HERE")

    var body: some Scene {
        WindowGroup {
            // Using Sync?
            if let app = app {
                SyncContentView(app: app)
            } else {
                LocalOnlyContentView()
            }
        }
    }
}
```
```
struct SyncContentView: View {
    @ObservedObject var app: RealmSwift.App

    @State var realm: Realm?

    var body: AnyView {
        guard let user = app.currentUser else {
            return AnyView(LoginView(app: app))
        }
        guard let realm = realm else {
            return AnyView(ProgressView() // Show the activity indicator while the realm loads
                .onReceive(Realm.asyncOpen(configuration: user.configuration(partitionValue: user.id)).assertNoFailure()) { realm in
                    if realm.objects(Group.self).count == 0 {
                        try! realm.write {
                            realm.add(Group())
                        }
                    }
                    self.realm = realm
                })
        }
        return AnyView(ItemsView(group: realm.objects(Group.self).first!,
                                 leadingBarButton: AnyView(LogoutButton(app: app))))
    }
}
```
## Version of Realm and Tooling

Realm framework version: 10.7.2

Realm Object Server version: ?

Xcode version: 10.4

iOS/OSX version: 14.4

Dependency manager + version: Swift Package Manager

**Comment by DominicFrei** [comment] 2021-04-06 10:48
Hey @willmorris44 !

Thanks for submitting this issue. I will have a look into it and check your findings against the documentation.

**Comment by DominicFrei** [comment] 2021-04-06 13:28
Also, cc @simonask and @tkaye407 here since Sync is involved.

**Comment by DominicFrei** [comment] 2021-04-09 12:07
@willmorris44 I've worked through the tutorial myself just to make sure it works and could not reproduce the problem.

Did you try the code in https://docs.mongodb.com/realm/sdk/ios/integrations/swiftui/#with-sync ?
I've added that to my project, edited the app ID and it works fine.

**Comment by willmorris44** [comment] 2021-04-12 20:29
So I copy pasted that code and I am still getting the crash. I found out why though. It appears my schema was wrong so for some reason when syncing, the error resulted in an app crash (is this intended?). To fix, I deleted my Realm schemas and put into Dev mode (for the auto schema). The app now works.

**Comment by DominicFrei** [comment] 2021-04-19 11:14
@willmorris44 Thanks for reporting the result back to us. The schemes actually have to match, yes. Otherwise you'd end up in a corrupt state if device and server are in a different state.

Dev Mode takes care of those changes by offering the auto schema to test while developing.

I'll go ahead and close this for now since the original problem has been solved. If you have any further questions about this feel free to ask.

**Closed by DominicFrei** 2021-04-19 11:14 UTC
Labels: O-Community, Reproduction-Required
