### ISSUE TITLE
XCode 7.3 / Swift 2.2 throws error: "Module file was created by and older version of the compiler; rebuild RealmSwift and try again"

### ISSUE THREAD

**Issue by SergioSCF** [realm/realm-cocoa#3358] opened 2016-03-22 20:23 UTC
## Goals

> Build my app with Realm 0.98.5 using XCode 7.3 + Swift 2.2

## Expected Results

> Build

## Actual Results

> The app throws the error: "Module file was created by and older version of the compiler; rebuild RealmSwift and try again"

## Steps to Reproduce

> Download XCode 7.3
> Build
> The error didn't exist before

## Code Sample

> import RealmSwift (the error is showed up here)

## Version of Realm and Tooling

> XCode 7.3
> Swift 2.2
> Deployment target: 8.0+
> Realm 0.98.5
<img width="1137" alt="captura de tela 2016-03-22 as 17 23 30" src="https://cloud.githubusercontent.com/assets/2027565/13966785/d64f6856-f052-11e5-92fc-946274a4105f.png">

**Comment by ericlewis** [comment] 2016-03-22 20:40
+1 same exact problem

**Comment by zinthemoney** [comment] 2016-03-22 20:45
:+1:

**Comment by bdash** [comment] 2016-03-22 20:48
This is a duplicate of #3355. Please take a look at @jpsim's comments in that issue for information about why this is happening, and what you can do to avoid it.

**Closed by bdash** 2016-03-22 20:48 UTC
Labels: T:Duplicate

**Comment by bdash** [comment] 2016-03-25 08:24
We have just released [Realm Swift v0.98.6](https://github.com/realm/realm-cocoa/releases/tag/v0.98.6), built with Xcode 7.3, to address this issue.
