### ISSUE TITLE
It should be possible to debug an application using encrypted realms

### ISSUE THREAD

**Issue by bdash** [realm/realm-cocoa#1885] opened 2015-05-08 18:12 UTC
We disabled debugging of applications using encrypted realms to address a frequent LLDB deadlock that would occur (issue #1625). We should address the underlying issue that causes the hang and reinstate the ability to debug applications that use encrypted realms. This will likely require changes in core.

**Comment by jondal** [comment] 2015-07-03 16:28
So how would one go about debugging an app using an encrypted Realm database?

**Comment by jpsim** [comment] 2015-07-03 16:55
You should disable encryption, without modifying any of your code, by setting the following environment variable: `REALM_DISABLE_ENCRYPTION=YES`. You can read more about this in our docs: https://realm.io/docs/objc/latest/#debugging-encrypted-realms

**Comment by marchyman** [comment] 2015-07-03 20:27
Which works, but... if the problem you are trying to debug has anything to do with the content of an encrypted database you are back to adding NSLog statements with the added hassle of not being able to run your program within Xcode.

**Comment by segiddins** [comment] 2015-07-03 20:33
@marchyman we understand that's far from ideal, hence why adding support for debugging encrypted realms is a P1 (priority one) for us at the moment.

**Comment by natanrolnik** [comment] 2015-07-26 00:51
+1 for this adding the support for debugging encrypted realms.
In my case, I have a pre-populated realm file, that is copied in the first launch... And as I'm using Swift 2, Realm 0.92 doesn't work due to some error in `RLMAccessor.mm`.
What's left for me is to run the app in the release mode, but this is far from ideal, as I can't debug it anymore.

**Comment by narup** [comment] 2015-09-30 06:20
Can I migrate from un-encrypted to encrypted version later? If I decide to use encryption once debugging support is enabled

**Comment by jpsim** [comment] 2015-09-30 06:48
Yes, you can specify a new encryption key as part of `-[RLMRealm writeCopyToPath:encryptionKey:error:]`.

**Comment by jondal** [comment] 2015-10-01 13:55
May I kindly suggest that this be upgraded to P1 again?

**Comment by jpsim** [comment] 2015-10-01 18:07
> May I kindly suggest that this be upgraded to P1 again?

This issue is essentially equivalent to "rewrite how encryption works", which is certainly not a top priority for us at the moment. To debug encrypted Realms during development, you can disable encryption without changing any of your code by setting the `REALM_DISABLE_ENCRYPTION` environment variable, as described in our [docs](https://realm.io/docs/objc/latest/#debugging-encrypted-realms):

> Attaching an LLDB session to a process using an encrypted Realm is not currently supported. In some cases, you may work around this by setting `REALM_DISABLE_ENCRYPTION=YES` in your environment; this variable forces all encrypted API methods to work without encryption, allowing you to debug without having to change which Realm APIs you call in your app code. For obvious security reasons, this workaround will not work if you try to access an existing `.realm` file that was previously encrypted (this will result in an exception: `File::AccessError`), but it might be useful in cases where your app creates & accesses new Realm files.

**Comment by zpapp** [comment] 2015-10-02 02:09
This is very disappointing. I think this is very close to saying that Realm on iOS doesn't support encryption. Even if I decide to put up with this major inconvenience and encrypt my database, I have to wonder what kind of ripple effect this will have on encryption as a feature. How many Realm users will decide that using encryption is not worth the trouble, how the decreased usage will lower the priority of any future bug related to encryption, while at the same time increasing the chance that I will be the first one to run into such bugs...

IMHO this should be the first thing you mention in the "Encryption" section of the documentation, not the WatchOS radar.

**Comment by jpsim** [comment] 2015-10-02 02:32
I'm sorry you're disappointed. We know this is important to many users of encryption, and maybe others can share their own tips when debugging encrypted Realms (/cc @anlaital).

The best way you can help us prioritize the issue is to help us grow our engineering team, so we can put more people on important tasks like these: https://realm.io/jobs.

**Comment by bmunkholm** [comment] 2015-10-02 07:41
@zpapp I can assure you that supporting encryption as a feature is a top priority for us. And we always prioritise bug fixing and support above anything else - so there is no need to worry about the encryption feature stability, although I do follow your line of thought. 
Having this as a P2 does not mean that it's low priority, just that the ones in P1 are higher priority to get fixed before we tackle the current P2's. One of the factors we use when prioritising is if there are workarounds. Another factor is if it affects current users, and yet another the effort it requires to fix. 
Some of the other features we have had even more requests for, and which we are working hard to complete, are null support, async queries and fine grained notifications. What's not visible from this priority list is also that fixing the debug support for encryption actually requires a lot of work in the core database team, so this reflects that teams priorities more than the Cocoa teams.
But we hear you, and will do our best to get it resolved as quickly as we can with due consideration to other requests as well.

**Comment by anlaital** [comment] 2015-10-02 08:11
As stated above, debugging encrypted Realms isn't something that's currently working. What we've done is that we simply don't use encryption in debug builds, so it's enabled only in Beta and App Store builds. It's definitely not optimal, but we haven't been able to find another solution to it so far. Encryption has been working solid for a long time now, so we don't find this approach too risky.

**Comment by zpapp** [comment] 2015-10-02 17:34
I appreciate the responses!

One of my concerns is how would I debug a problem (in my app, not with Realm) that can only be reproduced by an encrypted Realm file (which I would get from a user).

What's the easiest way to remove encryption from a previously encrypted database file?

My first thought was that the browser might do this, but it looks like the browser can't even open an encrypted realm. So I am guessing I'll have to write an app to do this...? Is there an inverse of the writeCopyToPath:encryptionKey: method that would allow me to wholesale remove encryption, instead of copying the objects one by one?

**Comment by tgoyne** [comment] 2015-10-02 17:37
The version of writeCopyToPath that doesn't take an encryption key writes an unencrypted copy.

**Comment by jpsim** [comment] 2015-10-02 17:38
> One of my concerns is how would I debug a problem (in my app, not with Realm) that can only be reproduced by an encrypted Realm file (which I would get from a user).

Using console logs, or a remote logging tool like [PonyDebugger](/square/PonyDebugger) or [Antenna](/mattt/Antenna).

> What's the easiest way to remove encryption from a previously encrypted database file?

Using writeCopyToPath: without an encryption key. Changing the encryption key for a file can be done in a similar way.

> My first thought was that the browser might do this, but it looks like the browser can't even open an encrypted realm.

The Realm Browser can open encrypted Realms as of realm/realm-browser-osx#74, a build of which is awaiting App Store approval.

**Comment by tgoyne** [comment] 2015-11-17 22:20
The required core changes have now landed in master, so now we just need a new core release to make this possible.

**Comment by zpapp** [comment] 2015-11-18 04:38
That's great news, thanks for letting us know!

**Closed** 2015-11-18 19:27 UTC
Labels: Enhancement, P2

**Comment by codywinton** [comment] 2015-12-17 22:55
Any update here?

**Comment by bdash** [comment] 2015-12-17 23:09
This is fixed in Realm Objective-C and Swift v0.97, [released earlier today](https://realm.io/news/realm-objc-swift-0.97.0/).
