### ISSUE TITLE
Use "LIKE" as "*a*b*" cause endless loop

### ISSUE THREAD

**Issue by boboboa32** [realm/realm-cocoa#4690] opened 2017-02-23 07:59 UTC
## Goals

use LIKE predicate

## Expected Results

use LIKE wildcard predicate 

## Actual Results

become endless loop, the result never fetch out

## Code Sample

```objc
    NSString *trimmedText = [text stringByTrimmingCharactersInSet:[NSCharacterSet whitespaceCharacterSet]];
    NSMutableString *string = [NSMutableString new];
    [string appendString:@"*"];
    for (int i = 0; i != trimmedText.length; i++) {
        NSString *c = [trimmedText substringWithRange:NSMakeRange(i, 1)];
        [string appendString:c];
        [string appendString:@"*"];
    }
    
    NSPredicate *predicate = [NSPredicate predicateWithFormat:@"phone LIKE[c] %@ || pinyin LIKE[c] %@ || realName LIKE[c] %@ || nickName LIKE[c] %@",
                              string, string, string, string];
    
    return predicate;
```

## Version of Realm and Tooling

- Realm version: 2.4.2
- Xcode version: 8.2.1
- iOS/OSX version: 8.4.1
- Dependency manager + version: cocoapods, 1.2.0

**Comment by istx25** [comment] 2017-02-24 21:25
Hi @boboboa32. Thanks for reaching out. We'll have someone review what you've shared and follow-up with a solution and/or additional follow-up questions. In the meantime, I recommend reading through our [NSPredicate Cheatsheet](https://realm.io/news/nspredicate-cheatsheet/) in case your solution lies in there. Cheers!

**Comment by austinzheng** [comment] 2017-02-24 23:19
Thanks for getting in touch. Can you provide us with a sample project that we can run to see this bug ourselves? Unfortunately there is not enough information in your code snippet to properly diagnose the cause. You can email a zip file to help@realm.io.

**Comment by austinzheng** [comment] 2017-02-28 22:03
Thank you for sending us a reproduction case. I've filed a bug against the underlying database engine: https://github.com/realm/realm-core/issues/2476.

**Comment by bdash** [comment] 2017-03-06 19:07
The bug has been fixed in core. We'll be able to pull this fix in once it makes its way into a release.

**Closed** 2017-03-08 23:16 UTC
Labels: Blocked, S:P1 Backlog, T:Bug
