### ISSUE TITLE
iOS 14 GM - Fatal error due to memory

### ISSUE THREAD

**Issue by qazwini** [realm/realm-cocoa#6773] opened 2020-09-17 05:38 UTC
## Goals

Write to Realm database in app group.

## Expected Results

Writes to database, like usual.

## Actual Results

Ever since iOS 14, every time I try to rewrite my objects (I rewrite them every on update and there are about 1400. i delete the old objects at the end), I get this error:
```
Fatal error: 'try!' expression unexpectedly raised an error: Error Domain=io.realm Code=9 "mmap() failed: Cannot allocate memory size: 63963136 offset: 469762048" UserInfo={NSLocalizedDescription=mmap() failed: Cannot allocate memory size: 63963136 offset: 469762048, Error Code=9}
```

I tried adding this:
```
config.maximumNumberOfActiveVersions = 5
```
but it only led to more errors. This is what I get now:
```
*** Terminating app due to uncaught exception 'RLMException', reason: 'Number of active versions (3752) in the Realm exceeded the limit of 5'
```
And if I set the max number of active versions to 4000, I get the first error (memory issue) again.

## Steps for others to Reproduce

- Build a database from JSON with 1400 objects
- Build it twice

## Code Sample

This is my Realm helper class:
```
class DB {
    static let version: UInt64 = 24 // set to 4 before releasing update
    
    static var realm: Realm {
        return try! Realm()
    }
    
    static func setup() {
        let migrationBlock: MigrationBlock = { migration, oldSchemaVersion in
            if oldSchemaVersion < 2 {
                migration.enumerateObjects(ofType: MyClass.className()) { oldObject, newObject in
                    let favorited = oldObject!["favorited"] as! Bool
                    newObject!["favorite"] = NafFav(favorited: favorited, dateFavorited: getNormalDate(withYear: true, numberFormat: true))
                }
            }
        }

        var config = Realm.Configuration(schemaVersion: version, migrationBlock: migrationBlock)
        config.fileURL = FileManager.default.containerURL(forSecurityApplicationGroupIdentifier: appGroupID)!.appendingPathComponent("db.realm", isDirectory: true)
        Realm.Configuration.defaultConfiguration = config
    }
}
```
This is how I serialize my data, and where I keep getting the memory error message:
```
let myClasses = try jsonDecoder.decode([MyClass].self, from: data)
let nafStrings = realm.objects(NafString.self)
var currentIndex = 0
try! realm.write {
    nafStrings.filter("name ENDSWITH '-1441' || name ENDSWITH '-1442'").setValue(true, forKey: "userDefined")
    nafStrings.filter("userDefined == false").setValue(false, forKey: "isLinked")
}
for myClass in myClasses {
    try! realm.write {
        let newMyClass = realm.create(MyClass.self, value: [
            "id": myClass.id,
            "entitle": myClass.entitle,
            "artitle": myClass.artitle,
            "searchen": myClass.searchen as Any,
            "searchar": myClass.searchar as Any,
            "type": myClass.type as Any,
            "submenus": myClass.submenus,
            "date": myClass.date,
            "location": myClass.location,
            "trans": myClass.trans
        ], update: .modified)
        serializeAudio(jsonNaf: myClass, userNaf: newMyClass)
    }
    currentIndex += 1
    percentCompleted?(Float(currentIndex) / Float(myClasses.count))
}
try! realm.write { realm.delete(nafStrings.filter("isLinked == false")) }
```

## Version of Realm and Tooling

Realm framework version: 5.3.5

Realm Object Server version: 6.0.19

Xcode version: 12 GM

iOS/OSX version: 14 GM

Dependency manager + version: SPM 5.2

**Comment by ericjordanmossman** [comment] 2020-09-17 17:08
@qazwini 
Closing as a duplicate of #6572 

- Please check out the posts on [pinning/releasing](https://github.com/realm/realm-cocoa/issues/6572#issuecomment-662770639) versions in this thread.  
- "I rewrite them every on update" - Try looking into using [update](https://realm.io/docs/swift/5.4.1/api/Structs/Realm.html#/s:10RealmSwift0A0V12UpdatePolicyO)
- Also note there was in fact a bug with [releasing versions](https://github.com/realm/realm-cocoa/issues/6572#issuecomment-666019805).

If you're still seeing this issue after using 5.4.x, have followed all the recommendations in #6572, and still believe this a bug, please comment in #6572.

**Closed by ericjordanmossman** 2020-09-17 17:08 UTC
Labels: O-Community
