### ISSUE TITLE
Writing in background thread and main thread freezes app

### ISSUE THREAD

**Issue by bb-git** [realm/realm-cocoa#5544] opened 2018-01-02 12:10 UTC
I have a huge Database (170k entries) being downloaded and written to realm on a serial background thread. All of this, also reading from realm works quite fine until I try to write to the realm on the main thread.
The app then freezes, until the background thread finishes.

I create a separate instance of realm on the background thread like suggested here
https://github.com/realm/realm-cocoa/issues/4944

So what is going wrong and is this a know issue?

**Comment by bb-git** [comment] 2018-01-02 16:47
Here is the code for the background thread:

```
Alamofire.request("https://www.example.com/", method: .post, parameters: parameters).responseJSON(queue: serialQueueDatabaseBackend) {response in
                switch response.result {
                case .success(let value):
                    let realm = try! Realm()
                    realm.beginWrite()
                    ....
                    try! realm.commitWrite()
                }
}
```

**Comment by Zhuinden** [comment] 2018-01-02 17:20
This is expected behavior, because transactions are blocking across threads.

If you don't want UI thread to block while background thread transaction is active, then don't start writing on UI thread

**Comment by Zhuinden** [comment] 2018-01-02 17:28
Okay so what Realm does is called "MVCC" and the way it works is that writing from one thread *does not invalidate what you already see on another thread*, until the Realm bumps the version which typically happens after all queries are asynchronously re-evaluated (or `refresh()` is called, in which case this happens synchronously).

This is all done so that **even during write transaction, you see consistent view of current version on other threads, until Realm can be updated to see latest version**. Without using locks on tables during reads and stuff.

----

To achieve this however, if a new version of Realm is in process of being created, then there can be only **one** new version in the process of being created at a given time. So Realm write transactions are actually blocking across *threads* and even *processes*.

Write transactions always block each other until previous transaction is committed or cancelled. So if you have long-running background thread write transactions, you shouldn't do write on UI thread until that is complete. Or just run it on bg thread and it'll be done at some point later.

**Comment by bb-git** [comment] 2018-01-02 17:41
That's more than a bit frustrating, as this will prevent users being able to use the app until all data is available.
So what is the best practise for this? I need the data, that I write on the main thread right now directly, as it needs to be displayed to the user. I do not care about when the data written on the background thread (or to be more clear the 170k entries) are available to the user.

**Comment by Zhuinden** [comment] 2018-01-02 18:24
Few options:

1.) ship Realm file with Realm app (or download it on the fly?) with 170k entries already in Realm file

2.) run the background writes in batches so that there is a chance it doesn't freeze UI thread

3.) track when UI thread wants to start a write transaction, force the background transaction to commit at that time, run UI thread transaction, then restart the remaining inserts in a new transaction on the background thread(?)

I mean, 170k entries can't just be appearing from nowhere

disclaimer: i'm not an official Realm member

**Comment by bb-git** [comment] 2018-01-02 23:42
I opted for solution 4, I created 2 realm files, one containging the huge dataset and the other for storing the users inputs, this way the UI stays responsive and the background thread can update as long as it needs after the first launch. Data changes too fast and is different for every country, so shipping the file does not work in this case.

**Comment by Zhuinden** [comment] 2018-01-02 23:49
@bb-git good approach, write transactions are specific to RealmConfiguration, so having two different RealmConfiguration enables having two Realms with two simultaneous write transactions.

I didn't think of that, that approach is much better! Thanks!

**Closed** 2018-01-03 18:29 UTC
