### ISSUE TITLE
Version 0.96 and createInRealm:withValue:

### ISSUE THREAD

**Issue by skrew** [realm/realm-cocoa#2697] opened 2015-10-16 18:06 UTC
Hi,

Since Realm 0.96, i got a strange bug.

```
[RProgram createInRealm: realm withValue:@[[RUserChannel objectForPrimaryKey:@(currentid)],
                                                             primary,
                                                             @([b[0] integerValue]), // startts
                                                             (...)
```
primary = NSString
startts = NSInteger

This code worked until 0.96, now i got this error:
`Invalid value '1584-1445009400' for property 'startts'`

Look like Realm put the value of `primary` in `startts`... If i uninstall / reinstall application all works fine, but i can't tell to users to uninstall / reinstall application ;)

Thanks

**Comment by mrackwitz** [comment] 2015-10-28 12:00
Could you show us the full `RProgram` class, where the properties are declared?
Are you sure you didn't changed the order of the properties accidentally?
You should be able to resolve that by passing a dictionary with named keys to `createInRealm:withValue:` instead of relying on the position. e.g.
```objective-c
NSDictionary *dict = @[
     @"userChannel": [RUserChannel objectForPrimaryKey:@(currentid)],
     @"primary": primary,
     @"startts": @([b[0] integerValue]),
];
[RProgram createInRealm:realm withValue:dict];
```

**Comment by jpsim** [comment] 2015-11-05 19:06
@skrew just following up on @mrackwitz's last comment. Do you have steps for us to try so we can reproduce the issue? Or maybe you can investigate this further on your end?

It's possible that something went wrong in the file format migration (0.96 introduced a new database file format).

**Comment by skrew** [comment] 2015-11-06 23:38
Hi @jpsim, just tested with 0.96.2 and same problem.

I don't want to make a dictionary before because, if you remember the sample i had send to you, time are critical in my application. Creating 30.000 - 90.000 dictionaries are not a (good) solution for me. 

I will make a sample to reproduce the bug and i will send it on your mail (or another mailbox if you want, just tell me.)

**Comment by jpsim** [comment] 2015-11-06 23:40
> Creating 30.000 - 90.000 dictionaries are not a (good) solution for me.

Yes, please don't do that.

> I will make a sample to reproduce the bug and i will send it on your mail (or another mailbox if you want, just tell me.)

Great! A way to reproduce this issue will be helpful in fixing it! Emailing help@realm.io is best.

**Comment by skrew** [comment] 2015-11-07 00:28
Mail send, hope it will help.

**Comment by bdash** [comment] 2015-12-02 01:11
@skrew, I apologize for the delay on getting back to you here. This issue appears to have slipped through the cracks. I don't see any email from you to help@realm.io on the date of your last comment. Would you be able to re-send the sample application so that we can investigate the problem you're seeing?

**Comment by skrew** [comment] 2015-12-02 01:20
@bdash Sended again, subject: "Sample project for reproducing issue #2697". I looked at my server log, mail have status=send, 250 ok. Should be ok.

**Comment by bdash** [comment] 2015-12-02 01:42
Thanks, I'm able to reproduce the issue by following the instructions you provided.

**Comment by bdash** [comment] 2015-12-02 02:18
I'm able to confirm that this issue exists in v0.96.2 and has since been fixed in master (cb608ae9fa63b4cb457ea55eb33e67658d4292c0).

The underlying issue is that the automatic migration of types such as `NSString *` from required to optional in v0.96.2 did not correctly preserve the order of the columns in the underlying table. The newly-optional columns were moved to the end of the table. In the provided example, the `primary` property is now treated as optional in v0.96.2 and its column ends up positioned after the `indexPathRow` column rather than being second as is expected. This results in the array form of `createInRealm:withValue:` attempting to match up values with unexpected properties.

**Comment by bdash** [comment] 2015-12-02 02:23
After speaking with @tgoyne, he clarified that our API contract is that the order of values in the array passed to `createInRealm:withValue:` only needs to match the declared order of properties, not the order of columns in the table on disk. That indicates there's more going on here than I expected: my debugging indicated we were depending on the order of the properties in the Realm on disk.

**Comment by bdash** [comment] 2015-12-03 01:34
From what I can see, after opening a Realm we update the order of the properties in `RLMObjectSchema` to match the order of the table columns. This is done by [`RLMCopyColumnMapping`](https://github.com/realm/realm-cocoa/blob/c5b7519953fd2c76c34f13740b15239d9092d2a4/Realm/RLMRealm.mm#L197). The order of the properties on the `RLMObjectSchema` determines the order we attempt to match the array entries with properties inside `RLMCreateObjectInRealmWithValue`.

**Closed** 2015-12-08 20:58 UTC
Labels: bug
