### ISSUE TITLE
Problems with iPhone 5S and iPad Mini 2 (Retina) running iOS 7

### ISSUE THREAD

**Issue by tspecht** [realm/realm-cocoa#2334] opened 2015-08-03 15:01 UTC
Hi guys,

I just updated the version of my realm installation from 0.93.2 to 0.94 on Friday and shipped it to my beta group. Unfortunately, I'm seeing an increasing amount of crashes just occuring on iPhone 5S and iPad Mini 2 (Retina) models running just iOS 7 which I can't really explain with my code (since I'm not doing  anything really fancy). All other device models and OS versions are working like expected. Unfortunately I won't be able to get a physical device until tomorrow but I just wanted to ask already, if this is a known issue?

```
Thread : Crashed: com.apple.main-thread
0  libsystem_kernel.dylib         0x000000018f4ea58c __pthread_kill + 8
1  libsystem_pthread.dylib        0x000000018f56d4a8 pthread_kill + 104
2  libsystem_c.dylib              0x000000018f47e84c abort + 112
3  MyApp                       0x0000000100721268 realm::util::terminate_internal(std::__1::basic_stringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) + 26072
4  MyApp                       0x00000001007213a4 realm::util::terminate_internal(std::__1::basic_stringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) + 26388
5  libsystem_pthread.dylib        0x000000018f56d4a8 pthread_kill + 104
6  MyApp                       0x000000010070b29c realm::util::terminate(char const*, char const*, long) (terminate.hpp:38)
7  MyApp                       0x00000001007fb070 std::__1::vector<realm::ColumnTemplateBase const*, std::__1::allocator<realm::ColumnTemplateBase const*> >::__append(unsigned long, realm::ColumnTemplateBase const* const&) + 518
8  MyApp                       0x00000001007640ec realm::RowIndexes::sort(realm::RowIndexes::Sorter&) + 300124
9  MyApp                       0x00000001007637b4 realm::TableViewBase::sort(std::__1::vector<unsigned long, std::__1::allocator<unsigned long> >, std::__1::vector<bool, std::__1::allocator<bool> >) + 297764
10 MyApp                       0x0000000100711ce0 RLMResultsValidate(RLMResults*) (vector:2733)
11 MyApp                       0x0000000100712468 -[RLMResults objectAtIndex:] (RLMResults.mm:216)
12 MyApp                       0x00000001002b64ac function signature specialization <Arg[0] = Owned To Guaranteed, Arg[1] = Owned To Guaranteed, Arg[2] = Owned To Guaranteed> of MyApp.AController.tableView (MyApp.AController)(ObjectiveC.UITableView, cellForRowAtIndexPath : ObjectiveC.NSIndexPath) -> ObjectiveC.UITableViewCell (AController.swift:228)
13 MyApp                       0x00000001002b4560 @objc MyApp.AController.tableView (MyApp.AController)(ObjectiveC.UITableView, cellForRowAtIndexPath : ObjectiveC.NSIndexPath) -> ObjectiveC.UITableViewCell (AController.swift)
14 UIKit                          0x0000000185ea395c -[UITableView _createPreparedCellForGlobalRow:withIndexPath:] + 408
15 UIKit                          0x0000000185e43390 -[UITableView _updateVisibleCellsNow:] + 1892
16 UIKit                          0x0000000185e42b28 -[UITableView layoutSubviews] + 168
17 UIKit                          0x0000000185d56d78 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 348
18 QuartzCore                     0x00000001859530cc -[CALayer layoutSublayers] + 184
19 QuartzCore                     0x000000018594dc94 CA::Layer::layout_if_needed(CA::Transaction*) + 300
20 UIKit                          0x0000000185d6e254 -[UIView(Hierarchy) layoutBelowIfNeeded] + 548
21 UIKit                          0x0000000185e2e20c -[UINavigationController navigationTransitionView:didEndTransition:fromView:toView:] + 456
22 UIKit                          0x0000000185d93c54 -[UIViewAnimationState sendDelegateAnimationDidStop:finished:] + 196
23 UIKit                          0x0000000185d91ee4 +[UIViewAnimationState popAnimationState] + 332
24 UIKit                          0x0000000185e1e584 -[UINavigationTransitionView transition:fromView:toView:] + 1788
25 UIKit                          0x0000000185e1de80 -[UINavigationTransitionView transition:toView:] + 36
26 UIKit                          0x0000000185e14840 -[UINavigationController _startDeferredTransitionIfNeeded:] + 636
27 UIKit                          0x0000000185e14564 -[UINavigationController __viewWillLayoutSubviews] + 56
28 UIKit                          0x0000000185e144e4 -[UILayoutContainerView layoutSubviews] + 200
29 UIKit                          0x0000000185d56d78 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 348
30 QuartzCore                     0x00000001859530cc -[CALayer layoutSublayers] + 184
31 QuartzCore                     0x000000018594dc94 CA::Layer::layout_if_needed(CA::Transaction*) + 300
32 QuartzCore                     0x0000000185980bc8 -[CALayer layoutIfNeeded] + 204
33 UIKit                          0x0000000185ddd5c4 -[UIWindow _setRotatableClient:toOrientation:updateStatusBar:duration:force:isRotating:] + 4128
34 UIKit                          0x0000000185ddc520 -[UIWindow _setRotatableViewOrientation:updateStatusBar:duration:force:] + 128
35 UIKit                          0x0000000185d5e078 -[UIWindow _updateToInterfaceOrientation:duration:force:] + 404
36 UIKit                          0x0000000185ddbb4c -[UIViewController _tryBecomeRootViewControllerInWindow:] + 192
37 UIKit                          0x0000000185d639a0 -[UIWindow addRootViewControllerViewIfPossible] + 524
38 UIKit                          0x0000000185dd33f0 -[UIWindow setRootViewController:] + 916
39 MyApp                       0x0000000100230200 function signature specialization <Arg[0] = Owned To Guaranteed> of static MyApp.BController.replaceWindowRootViewControllerWithMenu (MyApp.BController.Type)(completionClosure : Swift.Optional<() -> ()>) -> () (BController.swift:278)
40 MyApp                       0x00000001002331cc MyApp.BController.(viewDidAppear (MyApp.BController) -> (Swift.Bool) -> ()).(closure #1) (BController.swift:381)
41 MyApp                       0x000000010019f894 reabstraction thunk helper from @callee_owned (@owned Swift.ImplicitlyUnwrappedOptional<ObjectiveC.BFTask>) -> (@owned Swift.ImplicitlyUnwrappedOptional<Swift.AnyObject>) to @callee_unowned @convention(block) (@unowned Swift.ImplicitlyUnwrappedOptional<ObjectiveC.BFTask>) -> (@autoreleased Swift.ImplicitlyUnwrappedOptional<Swift.AnyObject>) (CController.swift)
42 MyApp                       0x00000001003b1714 __55-[BFTask continueWithExecutor:block:cancellationToken:]_block_invoke_2 (BFTask.m:334)
43 MyApp                       0x00000001003aefb4 __29+[BFExecutor defaultExecutor]_block_invoke_2 (BFExecutor.m:45)
44 MyApp                       0x00000001003af504 -[BFExecutor execute:] (BFExecutor.m:109)
45 MyApp                       0x00000001003b1684 __55-[BFTask continueWithExecutor:block:cancellationToken:]_block_invoke (BFTask.m:326)
46 MyApp                       0x00000001003b1268 -[BFTask runContinuations] (BFTask.m:306)
47 MyApp                       0x00000001003b1000 -[BFTask trySetCancelled] (BFTask.m:283)
48 MyApp                       0x00000001003b0f10 -[BFTask cancel] (BFTask.m:269)
49 MyApp                       0x00000001003b2700 -[BFTaskCompletionSource cancel] (BFTaskCompletionSource.m:64)
50 MyApp                       0x0000000100232604 MyApp.BController.(viewDidLoad (MyApp.BController) -> () -> ()).(closure #1) (BController.swift:91)
51 MyApp                       0x00000001002330c4 reabstraction thunk helper from @callee_owned (@owned Swift.ImplicitlyUnwrappedOptional<Swift.Dictionary<ObjectiveC.NSObject, Swift.AnyObject>>, @owned Swift.ImplicitlyUnwrappedOptional<ObjectiveC.NSError>) -> (@unowned ()) to @callee_unowned @convention(block) (@unowned Swift.ImplicitlyUnwrappedOptional<ObjectiveC.NSDictionary>, @unowned Swift.ImplicitlyUnwrappedOptional<ObjectiveC.NSError>) -> (@unowned ()) (BController.swift)
52 MyApp                       0x00000001003c7b18 -[Branch handleInitSuccess] (Branch.m:1143)
53 MyApp                       0x00000001003cf090 -[BranchOpenRequest processResponse:error:] (BranchOpenRequest.m:126)
54 MyApp                       0x00000001003c71e0 __30-[Branch processNextQueueItem]_block_invoke (Branch.m:1021)
55 MyApp                       0x00000001003bc508 __79-[BNCServerInterface genericHTTPRequest:retryNumber:log:callback:retryHandler:]_block_invoke (BNCServerInterface.m:113)
56 Foundation                     0x0000000183a34ad0 __67+[NSURLConnection sendAsynchronousRequest:queue:completionHandler:]_block_invoke_2 + 148
57 Foundation                     0x000000018393be04 -[NSBlockOperation main] + 76
58 Foundation                     0x0000000183928d38 -[__NSOperationInternal _start:] + 644
59 Foundation                     0x00000001839ead7c __NSOQSchedule_f + 76
60 libdispatch.dylib              0x000000018f3d43e0 _dispatch_client_callout + 16
61 libdispatch.dylib              0x000000018f3d756c _dispatch_main_queue_callback_4CF + 344
62 CoreFoundation                 0x0000000182e46d64 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
63 CoreFoundation                 0x0000000182e450a4 __CFRunLoopRun + 1452
64 CoreFoundation                 0x0000000182d85b38 CFRunLoopRunSpecific + 452
65 GraphicsServices               0x00000001887ab830 GSEventRunModal + 168
66 UIKit                          0x0000000185dc40e8 UIApplicationMain + 1156
67 MyApp                       0x0000000100153898 main (main.m:33)
68 libdyld.dylib                  0x000000018f3efaa0 start + 4
```

**Comment by kishikawakatsumi** [comment] 2015-08-03 15:12
@tspecht It seems the same as https://github.com/realm/realm-cocoa/issues/2332. To make sure, could you please check whether you sort by the properties of the int or long when you query the RLMResults object?

Thank you for your reporting!

**Comment by tspecht** [comment] 2015-08-03 15:13
Yes, I indeed am sorting by an NSInteger property. Is there an ETA for a fix?

**Comment by kishikawakatsumi** [comment] 2015-08-03 15:24
We can't give yet an exact ETA because the issue was discovered for the first time today.

**Comment by jpsim** [comment] 2015-08-03 15:29
Since this is almost definitely a duplicate of #2332, we'll be closing this ticket. Let's continue the conversation over at #2332, @tspecht. Thanks for reporting this, though! We're prioritizing investigating this issue and will share any updates to #2332.

**Closed by jpsim** 2015-08-03 15:29 UTC
Labels: bug, P1
