### ISSUE TITLE
RLMObject is empty in runtime

### ISSUE THREAD

**Issue by orkenstein** [realm/realm-cocoa#2777] opened 2015-11-02 10:15 UTC
I have a class, called `HCUser`:
```
class HCUser: HCRealmObject {
  dynamic var email = ""
  dynamic var name = ""
  dynamic var sex = ""
  dynamic var location = ""
  dynamic var sessionId = ""
  dynamic var phone: String? = ""
  dynamic var zipCode = ""
  dynamic var city = ""
  dynamic var state = ""
  dynamic var avatarUrl: String = ""
  dynamic var presetAvatar = false
}
```

And I have methods, to store current logged user:

```
  class func currentUser() -> HCUser? {
    //  Simple solution if we do not store other users
    return HCUser.allObjects().firstObject() as? HCUser
  }
  
  class private func setCurrentUser(user: HCUser?) {
    let realm = RLMRealm.defaultRealm()
    realm.beginWriteTransaction()
    realm.deleteObjects(HCUser.allObjects())
    if user != nil {
      realm.addObject(user!)
    }
    try! realm.commitWriteTransaction()
  }
```

In one particular point I do stuff like this:
```
let user = HCUser.currentUser()!
self.fillFormWithObject(user) // it takes user and fills VC with info

if user.presetAvatar == false {
  self.profileAddImageButton.iconImageView.setImageWithURL(NSURL(string: user.avatarUrl)!)
}
```

And at this point `user` is empty in debugger:
![2015-11-02 13-09-08 hcpersonalinfovc swift](https://cloud.githubusercontent.com/assets/1461936/10879087/fb819f36-8162-11e5-9234-724b3a2656e0.png)

But when I call `po user`, I get the following:
```
Printing description of user:
HCUser {
	id = 561f50e2f36d875f118c0a9e;
	key = 5402120353;
	email = good_email;
	name = good_name;
	sex = Male;
	location = Angola;
	sessionId = good_session_id ;
	phone = 11;
	zipCode = ;
	city = ;
	state = ;
	avatarUrl = http://good_url;
	presetAvatar = 0;
}
```

My setup:
```
ProductName:	Mac OS X
ProductVersion:	10.11.1
BuildVersion:	15B42

/Applications/Xcode.app/Contents/Developer
Xcode 7.1
Build version 7B91b

/usr/local/bin/pod
0.39.0
Realm (0.96.2)

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)

/usr/local/bin/carthage
0.8.0
(not in use here)

/usr/bin/git
git version 2.4.9 (Apple Git-60)
```

**Comment by kishikawakatsumi** [comment] 2015-11-02 10:40
@orkenstein It's intended behavior. Realm does not copy any data until actually access the properties. When access the properties, Realm fetch the data directly from its file. So Realm does not store any data to its ivar. Additionally, Realm object will change to another class at the moment it is persisted. That's why you cannot see any values via the debugger and nil out all value after committed.

In Objective-C, we provide LLDB script to fix this behavior, however doesn't  for Swift unfortunately.
See also https://realm.io/docs/objc/latest/#debugging

**Closed by kishikawakatsumi** 2015-11-02 10:40 UTC
