### ISSUE TITLE
@Persisted breaks EmbeddedObject lists

### ISSUE THREAD

**Issue by michaelpeternell** [realm/realm-cocoa#7531] opened 2021-11-15 17:55 UTC
### How frequently does the bug occur?

All the time

### Description

The following program (called by `Program.main()`):

```swift
import Foundation
import RealmSwift

class Parent: Object {
    @objc dynamic var id: String = ""
    let children = List<Child>()
    
    override class func primaryKey() -> String? {
        "id"
    }
}

class Child: EmbeddedObject {
    @Persisted var name: String = "child"
}

class Program {
    static func main() {
        _ = Program()
    }
    
    private let realm: Realm = {
        let config = Realm.Configuration(fileURL: nil, inMemoryIdentifier: "mem", syncConfiguration: nil, encryptionKey: nil, readOnly: false, schemaVersion: 1, migrationBlock: nil, deleteRealmIfMigrationNeeded: true, shouldCompactOnLaunch: nil, objectTypes: nil)
        let realm = try! Realm(configuration: config, queue: nil)
        return realm
    }()
    
    private init() {
        step1()
        step2()
    }
    
    private func step1() {
        let parent = Parent()
        parent.id = "13"
        let child = Child()
        parent.children.append(child)
        try! realm.write {
            realm.add(parent)
        }
        print("step1: parent has \(parent.children.count) children.")
    }
    
    private func step2() {
        let parent = realm.object(ofType: Parent.self, forPrimaryKey: "13")!
        print("step2: parent has \(parent.children.count) children.")
    }
}
```

prints correctly

```
step1: parent has 1 children.
step2: parent has 1 children.
```

However, if I change the line

```swift
@objc dynamic var id: String = ""
```

to

```swift
@Persisted var id: String = ""
```

it prints

```
step1: parent has 1 children.
step2: parent has 0 children.
```

This means that **a list of EmbeddedObjects is unusable if the containing object uses `@Persisted` properties instead of `@objc dynamic` properties**. Note that the `List` itself is defined in the same way in both programs.

I could reproduce it in v10.15.1 as well as in v10.19.0.
I used an iPhone with iOS 14.8 and an iPhone with iOS 15.0.2.
(in total 4 combinations of realm-version and iOS-version)

### Can you reproduce the bug?

Yes, always

### Version

10.19.0

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

iOS 14.8 and iOS 15.0.2

### Build environment

Xcode version: 13.0 (13A233)
Dependency manager and version: carthage 0.38.0
iOS deployment target: 14.0
called from a SwiftUI "Hello world" app.

**Comment by tgoyne** [comment] 2021-11-15 18:10
You need to mark both `id` and `children` with `@Persisted`.

**Comment by michaelpeternell** [comment] 2021-11-16 09:38
So, what is the purpose of `@Persisted`? For me it acted as a trap to fall into. Other than that, what is the advantage of using it?

**Comment by dianaafanador3** [comment] 2021-11-16 10:50
@michaelpeternell @Persisted is another way to model your data, is cleaner and easier to implement. 
All properties are declared the same way, no longer having to remember that some types required `@objc dynamic var` and easier for declaring Optionals, and primary key (no longer overriding `primaryKey()` and returning a string with the name of the property which is not type safe).
We are supporting both types of data modeling for the foreseeable future, but we don't support mixing both old style and new style within the same class, so if you are migrating your `Child` embedded Object to the new syntax you should migrate your parent object as well.

```
class Parent: Object {
    @Persisted(primaryKey: true) var id: String = ""
    @Persisted var children = List<Child>()
}

class Child: EmbeddedObject {
    @Persisted var name: String = "child"
}
```

**Comment by pavel-ship-it** [comment] 2021-11-17 09:39
I close the issue as the problem is solved. If you have any further questions please open another issue here or on [community forum](https://www.mongodb.com/community/forums/)

**Closed by pavel-ship-it** 2021-11-17 09:39 UTC
Labels: T-Help, O-Community
