### ISSUE TITLE
Memory leak when trying to save realm value to global variable

### ISSUE THREAD

**Issue by AlekseiR** [realm/realm-cocoa#6147] opened 2019-05-14 19:41 UTC
## Goals
I have a global struct Config, which I am trying to update with an API_HOST String stored in Realm. It happens each time the application being opened, so that I won't need to find Host value in database for each API call.

## Expected Results
I expect the String value stored in database to be extracted and placed in Struct String property seamlessly.

## Actual Results
Despite the fact of successful assigning and storing the value, I also get a memory leak of CFString in CoreFoundation with a backtrace to Realm function RLMStringDataToNSString.

## Steps to Reproduce
- Get stored String value from Realm
- Assign it to global variable
- Inspect with Debug Memory Graph 

## Code Sample
Struct:

```
struct Config {
    static var apiUrl = ""
}
```

Model:
```
class Host: Object {
    @objc dynamic var id = 0
    @objc dynamic var apiUrl: String = ""
    override static func primaryKey() -> String? {
        return "id"
    }
}
```

Data described by this model is being extracted in viewDidLoad of the first screen loaded:
```
let hostData = database.objects(Host.self).max(by: { $0.id < $1.id })
let apiUrl = hostData.apiUrl
```

and then assigned like that:
```
Config.apiUrl = apiUrl
```

Changing thread, assigning inside/outside write transaction doesn't affect the issue.

## Version of Realm and Tooling
```
ProductName:	Mac OS X
ProductVersion:	10.14.4
BuildVersion:	18E226

/Applications/Xcode.app/Contents/Developer
Xcode 10.2.1
Build version 10E1001

/usr/local/bin/pod
1.6.1
Realm (3.15.0)
RealmSwift (3.15.0)
RealmSwift (~> 3.15)

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin18)


(not in use here)

/usr/local/bin/git
git version 2.12.2
```

**Comment by iDevid** [comment] 2020-01-20 13:06
Seems that the problem is due the RLMStringDataToNSString method
![Schermata 2020-01-20 alle 14 06 03](https://user-images.githubusercontent.com/1254022/72728593-0431f880-3b8e-11ea-9125-703b1a19bf02.png)

**Comment by quangtandat** [comment] 2020-05-06 04:17
I have the same leak in RLMStringDataToNSString. Any help to this???

**Comment by leemaguire** [comment] 2020-06-23 11:17
I cannot replicate this with the latest version of Realm. @quangtandat can you update to the latest version and let us know if this is still happening?

Thanks,
Lee

**Comment by ericjordanmossman** [comment] 2020-09-17 21:27
Closing because of thread age.
@quangtandat @AlekseiR If this is still occurring please see @leemaguire 's [question here](https://github.com/realm/realm-cocoa/issues/6147#issuecomment-648080414).

**Closed by ericjordanmossman** 2020-09-17 21:27 UTC
Labels: O-Community, T-Help

**Comment by HamstringAssassin** [comment] 2020-11-21 00:24
If it's any help, i'm also seeing the same memory leak. Im using version 10.1.3 and was previously seeing it in version 5.3.3. iOS 14 simulators.

![image](https://user-images.githubusercontent.com/6310250/99861669-b364a500-2b8e-11eb-80e3-9965018da919.png)

In the screenshot above, theres one leak for the one struct. Normally, there would be hundreds if not thousands of leaks. Ive tried recreating with a sample app and i am not having any luck though. The recreation steps sound really similar to @AlekseiR. I have a `RealmObject` with a string property. A ViewModel that is init-ed with either an ID (and subsequently fetches the RealmObject) or the RealmObject itself, and assigns the string property of the RealmObject to a viewModel property. The viewModel is a struct and will be consumed by a CollectionViewCell. The CollectionView and CollectionViewCells are the first screen in the app. 

I get RealmObjects through a Repository class...
```
class RealmRepository<T: RealmObject> {
    static var defaultRealm: Realm? {
        do {
            return try Realm()
        } catch {
            log("error: \(error.localizedDescription)")
        }
        return nil
    }

    init() { }

    static func objectById(_ id: String) -> T? {
        guard let realm = defaultRealm else { return nil }
        let object = realm.object(ofType: T.self, forPrimaryKey: id)
        return object
    }
...
```
Any help here would be really appreciated.

**Comment by HamstringAssassin** [comment] 2020-11-22 19:17
Just to follow up incase anyone comes across this with a similar issue - changing the assignment in the struct using string interpolation seems to have fixed it. 

``` swift
self.name = "\(realmObject.name.capitalized)"
```

Once i did this, all the memory leaks were resolved. Im still not able to reproduce the issue in a demo app. :(

**Comment by dbrunning-hs** [comment] 2021-04-30 16:15
We're also seeing this memory leak in our app when we're assigning a Swift struct's String property from a Realm object. Having RLMStringDataToNSString return a copy of the NSString created from the realm::StringData also seems to fix the leak for us.

**Comment by Kaushal0812** [comment] 2022-05-18 14:16
Its still persists in 10.8.1.  However [HamstringAssassin](https://github.com/HamstringAssassin) sol.(String interpolation) worked.
