### ISSUE TITLE
anyone can help me

### ISSUE THREAD

**Issue by codesourse** [realm/realm-cocoa#2183] opened 2015-07-09 10:54 UTC
java encrypt realm file,iOS decrypt realm file , throw following problem:
 Error Domain=io.realm Code=2 "Invalid database" UserInfo=0x1708701c0 {NSLocalizedDescription=Invalid database, Error Code=2}

**Comment by segiddins** [comment] 2015-07-09 16:33
This seems to be a duplicate of https://github.com/realm/realm-cocoa/issues/2185, @codesourse ?

**Closed by segiddins** 2015-07-09 16:33 UTC
