### ISSUE TITLE
Using RealmSwift in App Extension with option "Allow app extension API only"

### ISSUE THREAD

**Issue by jcjee** [realm/realm-cocoa#1962] opened 2015-05-20 02:08 UTC
Hi, I am having problems using RealmSwift inside an app extension named 'RMBrowser' for my project. In the app extension setting, if "Allow app extension API only" is checked, I would get the following errors:

1) .../Build/Products/Debug-iphonesimulator/RMBrowser.framework/Headers/RMBrowser-Swift.h:165:23: Declaration of 'RLMNotificationToken' must be imported from module 'Realm.RLMRealm' before it is required

The offending code in RMBrowser-Swift.h is "@property (nonatomic) RLMNotificationToken * __nullable notificationToken;"

2) .../Build/Products/Debug-iphonesimulator/RMBrowser.framework/Headers/RMBrowser-Swift.h:258:54: Type name requires a specifier or qualifier

The offending code in RMBrowser-Swift.h is "@property (nonatomic, readonly) /* List<RMRecord> */ records;"

3) Could not build Objective-C module 'RMBrowser'

If the "Allow app extension API only" isn't checked, the app builds without errors, but as per the Apple app store requirements, this app will not be allowed into the App Store.

Really appreciate your team's input on this, thanks!

**Comment by segiddins** [comment] 2015-05-20 03:11
I'm guessing the root cause of this is the same as https://github.com/realm/realm-cocoa/issues/1884, where the synthesized Objective-C header is malformed. Unfortunately, this is an apple bug, one that we can't really fix. I am curious as to why `Allow app extension API only` seems to trigger it, though.

**Comment by jcjee** [comment] 2015-05-20 05:51
Thanks for the input. I have resorted to using the Realm Objective-C Dynamic Framework (in Swift) and it seems to build without errors now. Hopefully Apple will fix this bug soon, RealmSwift is really much nicer to use :-)

**Comment by jpsim** [comment] 2015-05-22 19:48
Closing as this is a problem that should be fixed by Apple, and workarounds are provided both here and in #1884.

**Closed by jpsim** 2015-05-22 19:48 UTC
