### ISSUE TITLE
Support Xcode 8.3 beta 1

### ISSUE THREAD

**Issue by TimOliver** [realm/realm-cocoa#4586] opened 2017-01-25 14:26 UTC
iOS 10.3 beta 1 was released earlier today, along with the first beta of Xcode 8.3. This version of Xcode introduced Swift 3.1, for which Realm Swift will need to be updated.

## Goals

To be able to use Realm Swift in Xcode 8.3 without any issues.

## Expected Results

To be able to succesffuly build a project with Realm Swift.

## Actual Results

When building the Realm Swift build target itself in Xcode 8.3 beta 1:

<img width="958" alt="screen_shot_2017-01-25_at_8 23 20_pm" src="https://cloud.githubusercontent.com/assets/429119/22294044/c484d58c-e34c-11e6-909e-cb8c523b5740.png">
(Attempting to do the same in Xcode 8.2 builds successfully with no issues)

When bringing Realm Swift in as a CocoaPods dependency for an iOS app:

![screen shot 2017-01-25 at 10 19 00 pm](https://cloud.githubusercontent.com/assets/429119/22294087/f0fed202-e34c-11e6-8367-9d1b75b6672e.png)

(Again, opening the same project in Xcode 8.2 will build and deploy with no issues).

## Steps to Reproduce

1. [Download Xcode 8.3 beta 1](https://developer.apple.com/download/)
2. Open Realm.xcodeproj, select the Realm Swift build target, and hit 'Build'

## Version of Realm and Tooling

Realm version: 2.3.0

Xcode version: 8.3 beta 1

iOS/OSX version: 10.3

Dependency manager + version: CocoaPods 1.1.1

**Comment by jpsim** [comment] 2017-01-25 21:58
Note that it's not just Realm Swift that's affected, but also Realm Objective-C (the first error you report).

**Comment by jpsim** [comment] 2017-01-25 22:13
Filed a radar: http://www.openradar.me/30194818

But I'm continuing to investigate.

**Comment by jpsim** [comment] 2017-01-26 18:37
Swift 3.1 is supposed to be source-compatible with 3.0.x, so I'm:

1) finding workarounds so our users can build with 8.3 despite these compiler regressions
2) checking if apple/swift#7017 helps
3) filing radars/SRs if it doesn't

**Comment by jpsim** [comment] 2017-01-27 05:17
No luck. Filed [rdar://30228957](http://www.openradar.me/30228957).

**Comment by istx25** [comment] 2017-01-27 17:11
Would we consider this blocked?

**Comment by woodland021** [comment] 2017-01-29 01:28
same issue :(

**Comment by RustyKnight** [comment] 2017-01-29 23:29
Should be filing our radars (basically copying yours) to get this more notice from Apple?

**Comment by jpsim** [comment] 2017-01-30 00:18
@RustyKnight thanks for offering to help! The best way to do that is to help reduce the repro case. Duplicating the radar may or may not help draw attention to this.

**Comment by jpsim** [comment] 2017-01-30 00:38
Apparently a fix is pending in apple/swift#7136

**Comment by jckarter** [comment] 2017-01-30 17:15
The issue arose when making a type conform to more than one of `MutableCollection`, `RangeReplaceableCollection`, and `{Bidirectional,RandomAccess}Collection` simultaneous. If you need a workaround, you can specify the type's `SubSequence` and `subscript(Range<Index>)` explicitly, for example:

```swift
extension Foo: RangeReplaceableCollection, RandomAccessCollection {
  // These should not be necessary, but 8.3 beta 1's compiler fails to infer the `SubSequence`,
  // and the standard library neglects to provide the default implementation of `subscript`
  typealias SubSequence = RangeReplaceableRandomAccessSlice<Foo>

  subscript(slice: Range<MyIndex>) -> SubSequence {
    return SubSequence(base: self, bounds: slice)
  }
}
```

**Comment by jpsim** [comment] 2017-01-30 19:14
Thanks for the suggestion @jckarter! That does indeed fix compilation with Xcode 8.3 beta 1, but breaks previous versions of Xcode.

> RealmSwift/List.swift:483:22: Type alias 'SubSequence' circularly references itself

Unfortunately due to [rdar://30215450](http://www.openradar.me/30215450), we can't conditionally do this for the beta.

**Comment by slavapestov** [comment] 2017-01-31 05:48
@jpsim Can you try a developer snapshot once Joe's fix makes it in to one?

**Comment by slavapestov** [comment] 2017-01-31 05:49
@jpsim Also the version issue should be fixed in the snapshots too

**Comment by matthijsotterloo** [comment] 2017-02-05 10:24
Is there a fix for this yet? I want to run my app in Xcode beta but can't get it to run due to these errors.

**Comment by jpsim** [comment] 2017-02-05 22:54
A fix was merged in apple/swift#7136, so any Swift snapshot after Feb 1st should work.

**Comment by jpsim** [comment] 2017-02-07 06:08
`master` now compiles with Xcode 8.3 beta 2.

**Closed by jpsim** 2017-02-07 06:08 UTC
Labels: S:Review, T:Feature

**Comment by jckarter** [comment] 2017-02-07 16:40
Were there any other changes necessary from the 8.2-compatible version to compile with 8.3 beta 2?

**Comment by jpsim** [comment] 2017-02-07 17:00
Have you seen this comment? https://github.com/realm/realm-cocoa/pull/4640#issue-205720145

> Doesn't look like apple/swift#7136 made it into Xcode 8.3 beta 2, but at least [rdar://30215450](http://www.openradar.me/30215450) was resolved so we can conditionally fix Swift 3.1.

**Comment by jckarter** [comment] 2017-02-07 17:04
Ah, yeah, beta 2 was in the pipe before the fix landed in master. It should show up in the next seed. At that point, hopefully you can remove the conditional compilation.

**Comment by jpsim** [comment] 2017-02-07 17:47
We'll probably just keep the conditional compile. Thanks for the follow up!

**Comment by jckarter** [comment] 2017-02-07 17:58
That's your call, but I'd appreciate the verification that it's unnecessary by the time 3.1 final ships.

**Comment by jpsim** [comment] 2017-03-07 22:27
Xcode 8.3 beta 3 compiles Realm Swift just fine without the explicit type alias and subscript declarations. Thanks @jckarter!

**Comment by jckarter** [comment] 2017-03-08 00:08
Awesome, thanks for confirming!
