### ISSUE TITLE
Carthage v0.94.1 failing with due to bitcode on iTunes Connect

### ISSUE THREAD

**Issue by baek-jinoo** [realm/realm-cocoa#2399] opened 2015-08-14 06:50 UTC
#### Goals

- Push iOS build to iTunes Connect

#### Expected results

- Able to test app on TestFlight

#### Actual results

- Fails with an e-mail containing the following line: ```Invalid Executable - The executable 'xyz.app/Frameworks/Realm.framework/Realm' contains bitcode.```

#### Steps to reproduce

1. setup Cartfile with ```github "realm/realm-cocoa" "v0.94.1"``` on your app
2. execute ```carthage update```
3. archive your release build and push to iTunes Connect
4. Wait for the failure e-mail with the bitcode error message

#### Code sample that highlights the issue (full Xcode projects that we can compile ourselves are ideal)

Requires project that has App Store distribution capacity with all the Certificate and Provisioning Profile present in the environment. So, I won't be including an Xcode project or code sample. Please follow steps above for an existing app that is capable of uploading builds for TestFlight tests.

Versions:
Realm - v0.94.1
Xcode - 6.3.2
OSX - 10.10.4 (14E46)

**Comment by segiddins** [comment] 2015-08-14 06:54
I'm going to close this as a duplicate of https://github.com/realm/realm-cocoa/issues/2397, but thanks for the excellent bug report, @baek-jinoo !

**Closed by segiddins** 2015-08-14 06:54 UTC
