### ISSUE TITLE
ignoredProperties 

### ISSUE THREAD

**Issue by LoveElaine** [realm/realm-cocoa#2775] opened 2015-11-02 02:44 UTC
Hello,
I encountered a problem

@interface Dog : RLMObject
@property NSString *name;
@property NSInteger age;
@end

@implementation JKLock

+ (NSArray *)ignoredProperties {
    return @[@"age"];
}

@end

I want to modify the age value at run time,but do not store,just use in memory, what should i do!
Thanks!

**Comment by LoveElaine** [comment] 2015-11-02 02:46
sorry, should be this
@implementation Dog
+ (NSArray *)ignoredProperties { return @[@"age"]; }
@end

**Comment by kishikawakatsumi** [comment] 2015-11-02 07:55
@LoveElaine `+ ignoredProperties` method should be class method. Please change the minus sign of the method to a plus sign like following:

```
@implementation Dog
+ (nullable NSArray *)ignoredProperties {
    return @[@"age"];
}
@end
```

**Comment by LoveElaine** [comment] 2015-11-02 08:14
thanks, I know it should be  ‘+‘
```
@interface Test : RLMObject

@property NSString *name;
@property NSInteger age;
@end

@implementation Test
+ (NSArray *)ignoredProperties {
    return @[@"age"];
}
@end

RLMRealm *realm = [RLMRealm defaultRealm];
Test *test = [[Test alloc]init];
test.name = @"Test";
test.age = 100;
[realm beginWriteTransaction];
[realm addObject:test];
[realm commitWriteTransaction];
    
    
Test *test2 = [[Test allObjects] firstObject];
NSLog(@"%@-----%d",test2.name,test2.age);
```
**Output:      Test-----0**

**I want the age value to be 100**
**what should i do,  thank you for your reply.**

**Comment by LoveElaine** [comment] 2015-11-02 08:16
**I don't need to save age value,just in memory**

**Comment by kishikawakatsumi** [comment] 2015-11-02 08:30
Sorry, I misunderstood. It's an intended behavior. "ignored" means the properties marked ignored are not persisted. So you instantiate new `test2` object from Realm, the value of age is gone. 

It is not possible to achieve what you said by "Ignored properties". Why do you want in that way?

**Comment by LoveElaine** [comment] 2015-11-02 09:06
This scenario is not good description, I use a property record status(disconnected,connecting,connected...), i can modify the age value at run time. Other properties can be stored except the status property.

**Comment by jpsim** [comment] 2015-11-05 23:43
> This scenario is not good description, I use a property record status(disconnected,connecting,connected...), i can modify the status value at run time. Other properties can be stored except the status property.

Here's how you could model that:

```objc
@interface RecordObject : RLMObject
@property NSString *status;
@end

@implementation RecordObject
+ (nullable NSArray *)ignoredProperties {
  return @[@"status"];
}
@end
```

With this model, Realm won't persist `status` if you set it to `disconnected`, `connecting`, or any value really, that you set at run time, on a specific instance of your object.

**Comment by TimOliver** [comment] 2015-11-12 03:56
Hi @LoveElaine! Hopefully that answered your question. Don't forget that if you specify a property as ignored, it will only be available in the instance of the object in which you've set it.

I'm going to close this issue now. If you still have more questions, feel free to re-open it! :)

**Closed by TimOliver** 2015-11-12 03:56 UTC
Labels: Help, pending
