### ISSUE TITLE
Deadlock on realm.beginWriteTransaction()

### ISSUE THREAD

**Issue by lesyk-bilyk** [realm/realm-cocoa#4649] opened 2017-02-09 13:12 UTC
## Goals

Want to modify/update db object

## Expected Results

Expected db object modification/update

## Actual Results

Got deadlock on realm.beginWriteTransaction()

![screen shot 2017-02-08 at 3 49 02 pm](https://cloud.githubusercontent.com/assets/18705124/22784599/573f8ac4-eed9-11e6-902b-3eef436c4052.png)

## Steps to Reproduce

It’s not replicated very often. Mostly it happens when realm objects are modified in background. So, if I launch the app after that modifications it works ok during some time but in a few seconds I experience deadlock

## Version of Realm and Tooling

Realm version: 2.4.2

Xcode version: 8.2

iOS/OSX version: iOS 10.2.1 

Dependency manager + version: CocoaPods(1.2.0)

**Comment by tbaranes** [comment] 2017-02-09 13:24
Seems to be the same as #4428 🎉 (happy to see that I'm not alone to get that deadlock...)

**Comment by semireg** [comment] 2017-02-09 16:13
We are affected by this deadlock.

**Comment by austinzheng** [comment] 2017-02-09 22:48
Closing this issue as a duplicate of #4428. Please follow that ticket for updates.

**Closed by austinzheng** 2017-02-09 22:48 UTC
