### ISSUE TITLE
Updating realm causes Primary Key property class has duplicate values after migration

### ISSUE THREAD

**Issue by philippeauriach** [realm/realm-cocoa#6941] opened 2020-11-16 09:34 UTC
## Goals
Update Realm version without making my app crash on update. 

## Expected Results
No crash

## Actual Results
Realm cannot open (happened to 90% of users who made the update). The error is :
```Error Domain=io.realm Code=1 "Primary key property 'class_UserPushSettingsDAO.id' has duplicate values after migration." UserInfo={NSLocalizedDescription=Primary key property 'class_UserPushSettingsDAO.id' has duplicate values after migration., Error Code=1}```

I should mention that I am not touching those classes, the primary keys are here for a long time (a few years) and working as expected.

A workaround I made is to empty those two problematic tables during a new migration. This is fine in this case because those tables are synced with my server (manually, not with realm sync) at launch time, but could be problematic if other tables were affected.

By the way, it happens on Android too (see https://github.com/realm/realm-java/issues/7202), and is much more problematic (seems many more tables are concerned).

## Steps for others to Reproduce
I could not reproduce. Happened only in production, when updating my app from the previous version (with realm 5.3.3) to the latest version with realm 5.4.2.

## Code Sample
I have two affected classes (from the logs):
```swift
class UserPushSettingsDAO: Object {
    @objc dynamic var id = ""
    //some other props
    override class func primaryKey() -> String? {
        return "id"
    }
}
```

## Version of Realm and Tooling

Realm framework version: 5.3.3 -> 5.4.2

Realm Object Server version: not used

Xcode version: 11.7

iOS/OSX version: any

Dependency manager + version: Carthage

**Comment by jsflax** [comment] 2020-11-19 14:37
@finnschiermer this sounds like an issue we heard about early in the core 6 release– any thoughts?

**Comment by jsflax** [comment] 2020-12-10 13:10
@philippeauriach are you able to migrate to the latest realm 10.x version and see if the issue still occurs?

**Comment by kouki-dan** [comment] 2020-12-18 11:12
I have got the same issue.
It also happened only in production in my app.
It happened in the first migration in a year. The current Realm version is 5.4.4. About 40% of users affect them.

I have brought the Realm file from the production and experimented.
I tried to upgrade to v10.5 and it no longer causes this error.

I have not produced v10.x in production, but it may be fixed in Realm v10.x.


My workaround is here. I chose not to migrate.
```
// Create configuration
if let schemaVersion = try? schemaVersionAtURL(config.fileURL!) {
    config.schemaVersion = schemaVersion
}
return try Realm(configuration: config)
```
I can choose this because the migration does not affect data structure and I haven't migrated recently. This workaround is not for everyone.

**Comment by jsflax** [comment] 2020-12-18 11:18
That's good to hear at least.

@philippeauriach can you confirm this as well?

**Comment by philippeauriach** [comment] 2020-12-19 17:32
Hi, I can not test for now as a migration to realm 10 is not something I take lightly :) Also, I made my own workaround which seems to have fixed the problem in my case (while deleting the content of two tables...) 

I don't quite understand the workaround?

**Comment by smpanaro** [comment] 2021-01-04 14:48
I am also seeing this on Realm v5.0.0.

> `Fatal error: 'try!' expression unexpectedly raised an error: Error Domain=io.realm Code=1 "Primary key property 'class_Bean.id' has duplicate values after migration." UserInfo={NSLocalizedDescription=Primary key property 'class_Bean.id' has duplicate values after migration., Error Code=1}: file brewtimer/RealmHelpers.swift, line 17`

My migration does not touch that class at all. My workaround was to ship a change to the migration to regenerate unique keys for those duplicates. This allowed the migration to complete successfully, but now I have duplicate objects in Realm (somewhat obvious in hindsight).

I couldn't reproduce locally or outside of my production app, but I do now have a set of example Realm files from before the migration and after applying my workaround mentioned above. @jsflax is there somewhere I can email them privately?

**Comment by jsflax** [comment] 2021-01-21 17:12
We haven't had any non-sync regression reported in v10– @philippeauriach @smpanaro while it's reasonable to wait to upgrade, we highly recommend that you do, since the bug is fixed there.

I'm going to close this issue as there are no plans to backport this fix.

**Closed by jsflax** 2021-01-21 17:12 UTC
Labels: O-Community, Pipeline-Waiting-for-User
