### ISSUE TITLE
Issues with Realm 0.95.0

### ISSUE THREAD

**Issue by gagarwal** [realm/realm-cocoa#2482] opened 2015-09-03 21:38 UTC
I recently updated my project to use Realm 0.95.0 using Cocoapods. And I started getting following linker error, any idea why?

```
duplicate symbol _llvm.cmdline in:
    /Users/gaurava/MobileiOS/Pods/Realm/core/librealm-ios.a(encrypted_file_mapping-iPhoneOS.o)
    /Users/gaurava/MobileiOS/Pods/Realm/core/librealm-ios.a(misc_errors-iPhoneOS.o)
duplicate symbol _llvm.embedded.module in:
    /Users/gaurava/MobileiOS/Pods/Realm/core/librealm-ios.a(encrypted_file_mapping-iPhoneOS.o)
    /Users/gaurava/MobileiOS/Pods/Realm/core/librealm-ios.a(misc_errors-iPhoneOS.o)
duplicate symbol _llvm.cmdline in:
    /Users/gaurava/MobileiOS/Pods/Realm/core/librealm-ios.a(encrypted_file_mapping-iPhoneOS.o)
    /Users/gaurava/MobileiOS/Pods/Realm/core/librealm-ios.a(basic_system_errors-iPhoneOS.o)
duplicate symbol _llvm.embedded.module in:
    /Users/gaurava/MobileiOS/Pods/Realm/core/librealm-ios.a(encrypted_file_mapping-iPhoneOS.o)
    /Users/gaurava/MobileiOS/Pods/Realm/core/librealm-ios.a(basic_system_errors-iPhoneOS.o)
duplicate symbol _llvm.cmdline in:
    /Users/gaurava/MobileiOS/Pods/Realm/core/librealm-ios.a(encrypted_file_mapping-iPhoneOS.o)
    /Users/gaurava/MobileiOS/Pods/Realm/core/librealm-ios.a(file-iPhoneOS.o)
duplicate symbol _llvm.embedded.module in:
    /Users/gaurava/MobileiOS/Pods/Realm/core/librealm-ios.a(encrypted_file_mapping-iPhoneOS.o)
    /Users/gaurava/MobileiOS/Pods/Realm/core/librealm-ios.a(file-iPhoneOS.o)
duplicate symbol _llvm.cmdline in:
    /Users/gaurava/MobileiOS/Pods/Realm/core/librealm-ios.a(encrypted_file_mapping-iPhoneOS.o)
    /Users/gaurava/MobileiOS/Pods/Realm/core/librealm-ios.a(file_mapper-iPhoneOS.o)
duplicate symbol _llvm.embedded.module in:
    /Users/gaurava/MobileiOS/Pods/Realm/core/librealm-ios.a(encrypted_file_mapping-iPhoneOS.o)
    /Users/gaurava/MobileiOS/Pods/Realm/core/librealm-ios.a(file_mapper-iPhoneOS.o)
duplicate symbol _llvm.cmdline in:
    /Users/gaurava/MobileiOS/Pods/Realm/core/librealm-ios.a(encrypted_file_mapping-iPhoneOS.o)
    /Users/gaurava/MobileiOS/Pods/Realm/core/librealm-ios.a(memory_stream-iPhoneOS.o)
duplicate symbol _llvm.embedded.module in:
    /Users/gaurava/MobileiOS/Pods/Realm/core/librealm-ios.a(encrypted_file_mapping-iPhoneOS.o)
    /Users/gaurava/MobileiOS/Pods/Realm/core/librealm-ios.a(memory_stream-iPhoneOS.o)
duplicate symbol _llvm.cmdline in:
    /Users/gaurava/MobileiOS/Pods/Realm/core/librealm-ios.a(encrypted_file_mapping-iPhoneOS.o)
    /Users/gaurava/MobileiOS/Pods/Realm/core/librealm-ios.a(string_buffer-iPhoneOS.o)
duplicate symbol _llvm.embedded.module in:
    /Users/gaurava/MobileiOS/Pods/Realm/core/librealm-ios.a(encrypted_file_mapping-iPhoneOS.o)
    /Users/gaurava/MobileiOS/Pods/Realm/core/librealm-ios.a(string_buffer-iPhoneOS.o)
duplicate symbol _llvm.cmdline in:
    /Users/gaurava/MobileiOS/Pods/Realm/core/librealm-ios.a(encrypted_file_mapping-iPhoneOS.o)
    /Users/gaurava/MobileiOS/Pods/Realm/core/librealm-ios.a(terminate-iPhoneOS.o)
duplicate symbol _llvm.embedded.module in:
    /Users/gaurava/MobileiOS/Pods/Realm/core/librealm-ios.a(encrypted_file_mapping-iPhoneOS.o)
    /Users/gaurava/MobileiOS/Pods/Realm/core/librealm-ios.a(terminate-iPhoneOS.o)
duplicate symbol _llvm.cmdline in:
    /Users/gaurava/MobileiOS/Pods/Realm/core/librealm-ios.a(encrypted_file_mapping-iPhoneOS.o)
    /Users/gaurava/MobileiOS/Pods/Realm/core/librealm-ios.a(thread-iPhoneOS.o)
```

**Comment by jpsim** [comment] 2015-09-03 21:49
Have you tried cleaning your workspace, restarting Xcode and building again? Duplicate symbol issues are often caused by a bad Xcode cache.

**Comment by gagarwal** [comment] 2015-09-03 21:58
Yes, I cleaned the build folder. Even tried deleting the DerivedData folder. Same issue.

**Comment by jpsim** [comment] 2015-09-03 22:10
What version of CocoaPods are you using? Realm 0.95 requires CocoaPods 0.37.1 or later.

**Comment by gagarwal** [comment] 2015-09-03 22:11
I am using Cocoapods 0.38.2.

**Comment by jpsim** [comment] 2015-09-03 22:15
Perhaps there's a problem with your project's configuration.

We maintain (and continuously test) installation examples for all our supported installation mechanisms in this repo.

Could you try running `pod install` from this directory to see if that works for you? https://github.com/realm/realm-cocoa/tree/master/examples/installation/ios/objc/CocoaPodsExample

**Comment by gagarwal** [comment] 2015-09-03 22:37
Yup. It works for me. I will dig more into my project settings and see whats happening. It was working fine few hours ago and the change I made was only update to new Realm version.

**Comment by gagarwal** [comment] 2015-09-04 00:55
I am seeing this error with other libraries too on a little Google search. Can this be related?

https://github.com/bitstadium/HockeySDK-iOS/issues/190
https://github.com/tenonedesign/T1Autograph/issues/1

**Comment by segiddins** [comment] 2015-09-09 00:35
This is likely a duplicate of https://github.com/realm/realm-cocoa/issues/2462 ?

**Comment by JanC** [comment] 2015-09-13 07:23
Hi,
I had the same issue with my own library. It appears when I compile the simulator slice with the `-fembed-bitcode` flag. In other words, I use the bitcode flag only when compiling the library for the device.

Here is a part of my build script
```ruby
# simulator without bitcode
fail unless system "xcrun xcodebuild -workspace #{WORKSPACE} \
                                     -scheme #{SCHEME_SDK} \
                                     -configuration #{configuration} \
                                     -sdk iphonesimulator9.0 \
                                     -derivedDataPath #{derived_data_path} \
                                     clean build | xcpretty -c"

# device with bitcode
fail unless system "xcrun xcodebuild OTHER_CFLAGS='-fembed-bitcode' \
                                     -workspace #{WORKSPACE} \
                                     -scheme #{SCHEME_SDK} \
                                     -configuration #{configuration} \
                                     -sdk iphoneos9.0 \
                                     -derivedDataPath #{derived_data_path} \
                                     clean build | xcpretty -c"
# fat library 
arm_file = "#{derived_data_path}/Build/Products/#{configuration}-iphoneos/lib#{target}a"
x86_file = "#{derived_data_path}/Build/Products/#{configuration}-iphonesimulator/lib#{target}.a"
final_file = "#{BUILDS_SDK_LIB_DIR}/lib#{target}-#{sdk_version}.a"

fail unless system "lipo -create #{arm_file} #{x86_file} -output #{final_file}"
```

**Comment by TimOliver** [comment] 2015-09-24 04:36
Thanks a lot for providing a build solution for that @JanC! 
I actually had a similar situation in one of my own apps linking against some third-party libraries, and for time constraints, I ended up simply disabling bitcode for that particular release. I'm definitely going to try that one out myself!

@gagarwal Please let us know if that solution doesn't end up working for you!

**Closed by TimOliver** 2015-09-24 04:36 UTC
