### ISSUE TITLE
Not able to perform predicate query on inverse relationship

### ISSUE THREAD

**Issue by ProjectDent** [realm/realm-cocoa#2124] opened 2015-06-25 13:13 UTC
I have this inverse relationship:

    class Image: Media {
        var messageContainingImage: Message? {
            return linkingObjects(Message.self, forProperty: "images")[0]
        }
    }

But if I do a query on this, like so:

    let images = Realm().objects(Image).filter("messageContainingImage.sentTime < '\(message.sentTime)'")

It crashes with the error message:

> Terminating app due to uncaught exception 'Invalid property name', reason: 'Property 'messageContainingImage' not found in object of type 'Image''

**Comment by segiddins** [comment] 2015-06-25 14:46
@ProjectDent querying based upon ignored or computed properties isn't supported, since querying happens directly in the database engine, which only has persisted data available to it.
We're tracking adding support for querying based upon backlinks in https://github.com/realm/realm-cocoa/issues/1324, but the suggestion (storing an explicit backlink property) should still work!

**Comment by jpsim** [comment] 2015-06-25 15:33
Closing as a duplicate of #1324.

**Closed by jpsim** 2015-06-25 15:33 UTC
