### ISSUE TITLE
v5.4.2 cannot be carthage update

### ISSUE THREAD

**Issue by myammm** [realm/realm-cocoa#6784] opened 2020-09-18 09:03 UTC
## Goals
Successful carthage update.

## Actual Results
xcodebuild log ↓
/Carthage/Checkouts/realm-cocoa/Realm/ObjectStore/src/object_changeset.hpp:24:10: fatal error: 'realm/keys.hpp' file not found

## Steps for others to Reproduce
I tried to update by the following method.
$ ./carthage-build.sh update --no-use-binaries --platform iOS realm-cocoa
(https://github.com/Carthage/Carthage/issues/3019#issuecomment-664099506)

## Version of Realm and Tooling
Realm framework version: v5.4.2
Xcode version: Xcode 12 GM

**Comment by bguidolim** [comment] 2020-09-18 09:32
@myammm please try using this: https://gist.github.com/skymobilebuilds/61f4a95bd62a3db36b52719aeab7e0d5

It was mentioned some comments below: https://github.com/Carthage/Carthage/issues/3019#issuecomment-694329329

**Comment by bguidolim** [comment] 2020-09-18 09:55
Ah, it's not about the script, same error here.

**Comment by bguidolim** [comment] 2020-09-18 13:03
Could it be related to https://github.com/realm/realm-cocoa/issues/6774 ?

**Comment by tgoyne** [comment] 2020-09-18 15:14
Duplicate of https://github.com/realm/realm-cocoa/issues/6717.

If using the prebuilt library is acceptable and you don't specifically need to build from source, you can simply remove `--no-use-binaries`.

**Closed by tgoyne** 2020-09-18 15:14 UTC
Labels: O-Community

**Comment by myammm** [comment] 2020-09-24 03:39
@bguidolim @tgoyne 
I tried the script and it worked.
Thank you!
