### ISSUE TITLE
Realm error with cocoapods

### ISSUE THREAD

**Issue by marko1503** [realm/realm-cocoa#3356] opened 2016-03-22 17:38 UTC
## Goals

I want to integrate Realm in my project. I tried to integrate realm via cocoapods, insert as dynamic and static library. I always get errors. One of them **'Realm/Realm.h' file not found**.

## Expected Results

After integrate Realm and build a project I don't have any errors or warnings.

## Actual Results

Project builds with errors.
'Realm/Realm.h' file not found.
ld: file not found: /Users/marko1503/Library/Developer/Xcode/DerivedData/Test-ctnonttshetqagbeobrgiyokydhe/Build/Intermediates/Test.build/Debug-iphonesimulator/Test.build/Objects-normal/x86_64/AppDelegate.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)

## Steps to Reproduce

1). Create test project.
2). Add Realm dynamic framework from realm-objc-0.98.5/ios/dynamic/xcode-7/Realm.framework to the project (copy items flag enabled).
3). Open AppDelegate.m insert #import <Realm/Realm.h>  at Top of the file.
4). Build test project. Project builded with success.
5). Integrate cocoapods to the project. I try with cocoapods 0.39 and 1.0 beta 6.
Add podfile to you project folder, open terminal, navigate to the project folder, execute command pod install
Pod file:
```
platform :ios, '8.0'

use_frameworks!
# ignore all warnings from all pods
inhibit_all_warnings!

target "You_test_project_name" do
#    pod 'Realm'
end
```
6). Build you project. The project builded with error 'Realm/Realm.h' file not found.
7). Remove Realm static or dynamic framework. Add pod 'Realm' to pod file. Update you podfile with pod update.
8). Build you project. The project builded with error 'Realm/Realm.h' file not found and many more.

## Version of Realm and Tooling

I use Xcode 7.3, Realm for iOS, dependency manager involved CocoaPods.

**Comment by andrewloyola** [comment] 2016-03-22 19:12
i'm having the same issue, Xcode 7.3, cocoapods 1.0.0b5, with 'RealmSwift'

`<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "Headers/Realm.h"
        ^
/Users/... iphonesimulator/Realm/Realm.framework/Headers/Realm.h:21:9: error: 'Realm/RLMArray.h' file not found
#import <Realm/RLMArray.h>
        ^
<unknown>:0: error: could not build Objective-C module 'Realm'
<module-includes>:2:9: note: in file included from <module-includes>:2:
#import "Headers/RealmSwift-Swift.h"`

**Comment by jpsim** [comment] 2016-03-29 02:29
We can't reproduce this from the samples given. One thing that's reportedly helped in these cases is clearing the CocoaPods cache and Xcode's Derived Data and trying to compile again. Could you please try doing this and reporting back again?

```
pod cache clean Realm
pod cache clean RealmSwift
pod deintegrate || rm -rf Pods
pod install --verbose
```

**Comment by marko1503** [comment] 2016-04-02 11:57
Doesn't help.
My pod file:
platform :ios, '8.0'

# 
use_frameworks!
# ignore all warnings from all pods
inhibit_all_warnings!

target "MyProject" do
    pod 'libextobjc/EXTScope'
    pod 'SnapKit'
    pod 'PureLayout'
    pod 'Realm'

    target "MyProjectTests" do
        inherit! :search_paths
        pod 'OCMock'
    end
end

#import <Realm/Realm.h>
<img width="251" alt="screen shot 2016-04-02 at 14 56 58" src="https://cloud.githubusercontent.com/assets/351837/14226181/32a6d0f6-f8e3-11e5-918e-0c7ad7b757e9.png">

**Comment by jpsim** [comment] 2016-04-04 17:52
I'm sorry I can't reproduce the issues you've been having. Here are the steps I've taken to attempt to reproduce your project's state and the problems you've been seeing:

First, I made a new iOS app project:

![image](https://cloud.githubusercontent.com/assets/474794/14257437/a47f2d98-fa52-11e5-9a2c-39b5f9043839.png)

Here's my environment:

```
$ ruby --version
ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-darwin15]
$ pod --version
1.0.0.beta.6
$ xcodebuild -version
Xcode 7.3
Build version 7D175
```

And the steps I took to reproduce your issue:

```
$ cd GH3356
$ pod init
$ vim Podfile
$ cat Podfile
platform :ios, '8.0'

use_frameworks!
# ignore all warnings from all pods
inhibit_all_warnings!

target "GH3356" do
    pod 'libextobjc/EXTScope'
    pod 'SnapKit'
    pod 'PureLayout'
    pod 'Realm'

    target "GH3356Tests" do
        inherit! :search_paths
        pod 'OCMock'
    end
end
$ pod install
```

So that succeeded.

Then writing a bit of Realm code in the app and running it to confirm that works:

```objc
#import "AppDelegate.h"
#import <Realm/Realm.h>

@interface MyModel : RLMObject
@property NSString *stringProp;
@end
@implementation MyModel
@end

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    RLMRealm *realm = [RLMRealm defaultRealm];
    [realm transactionWithBlock:^{
        [MyModel createInRealm:realm withValue:@[@"a"]];
    }];
    NSLog(@"%@", [MyModel allObjectsInRealm:realm]);
    // Prints
    // RLMResults <0x7ff45a851020> (
    // 	[0] MyModel {
    // 		stringProp = a;
    // 	}
    // )
    return YES;
}

@end
```

Could you please try these steps too to see if there's something either configured differently on your system or in your app? Thanks!

**Comment by imrepapp** [comment] 2016-04-19 14:09
Hello, 
I did the steps you described above, build process was successful, but when i have tried archive, i got "linker error".

ruby 2.2
pod 1.0.0.beta.8
Xcode 7.2

**Comment by jpsim** [comment] 2016-04-19 14:11
what's the linker error? is there more to the error message than that? can you share the project?

**Comment by imrepapp** [comment] 2016-04-19 14:16
error was in this line: Ld .../.../.../Realm arm64 normal

**Comment by jpsim** [comment] 2016-04-19 14:21
What was the error? This could happen if the `pod install` step failed, not downloading Realm's core binaries. What's the console output of `pod install`?

**Comment by imrepapp** [comment] 2016-04-19 15:53
** ARCHIVE FAILED **


The following build commands failed:
	Ld /Users/pappi/Library/Developer/Xcode/DerivedData/GH3356-fralsoihoawkqbgsgcuvmtfcehvy/Build/Intermediates/ArchiveIntermediates/GH3356/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/Realm.build/Objects-normal/arm64/Realm normal arm64
(1 failure)

**Comment by imrepapp** [comment] 2016-04-19 15:56
-> Installing Realm (0.98.8)
 > Git download
 > Git download
     $ /usr/bin/git clone https://github.com/realm/realm-cocoa.git /var/folders/xt/bbxb_ys163x2qgj_59rx3lc80000gn/T/d20160419-630-xhuphn --template= --single-branch --depth 1 --branch v0.98.8
     Cloning into '/var/folders/xt/bbxb_ys163x2qgj_59rx3lc80000gn/T/d20160419-630-xhuphn'...
     Note: checking out '65cbc1512975bb42f47bb933a30dbb59e3858d85'.
     
     You are in 'detached HEAD' state. You can look around, make experimental
     changes and commit them, and you can discard any commits you make in this
     state without impacting any branches by performing another checkout.
     
     If you want to create a new branch to retain commits you create, you may
     do so (now or later) by using -b with the checkout command again. Example:
     
       git checkout -b <new-branch-name>
     
 > Running prepare command
   $ /bin/bash -c  set -e sh build.sh cocoapods-setup
   core is not a symlink. Deleting...
   Downloading dependency: core 0.97.4
   Installing for Xcode 7+.
  > Copying Realm from `/Users/pappi/Library/Caches/CocoaPods/Pods/Release/Realm/0.98.8-0e293` to `Pods/Realm`

**Comment by imrepapp** [comment] 2016-04-19 16:19
Here is the project: https://github.com/imrepapp/GH3356

**Comment by imrepapp** [comment] 2016-04-19 19:12
I think the problem maybe the version (7.2) of Xcode, my friend downloaded the project from github, and he could build archive successfully. He has 7.3.

**Comment by jpsim** [comment] 2016-04-28 10:33
Closing this since @imrepapp can no longer reproduce, the sample project is gone, and other information shared here is attributable to CocoaPods & Xcode configuration issues or solved by clearing relevant caches.

**Closed by jpsim** 2016-04-28 10:33 UTC
Labels: T:Help

**Comment by lexuanquynh** [comment] 2016-09-26 03:42
I can' t using pod to install Realm on xcode 8.
I using command on this:
https://realm.io/docs/swift/latest/
But I get bugs:
![image](https://cloud.githubusercontent.com/assets/17588791/18822030/bd53f9b8-83d5-11e6-9b11-2e97ade7f98e.png)

**Comment by jpsim** [comment] 2016-09-26 03:45
@lexuanquynh did you set the appropriate Swift version in your Podfile as described in our [installation instructions](https://realm.io/docs/swift/latest/#installation)?

for example:

```ruby
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '2.3' # or '3.0'
    end
  end
end
```
