### ISSUE TITLE
CocoaPods error on OS X: umbrella header 'Realm.h' not found

### ISSUE THREAD

**Issue by rcharlton** [realm/realm-cocoa#3570] opened 2016-05-12 16:30 UTC
When building target RealmSwift the error _umbrella header 'Realm.h' not found_ occurs with a new (minimal template) Mac Cocoa Application with project set up using Cocoapods.

pod --version = 1.0.0
Realm (0.100.0):
Xcode 7.3.1 (7D1014)

Podfile:
```
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'MyRealmApp' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyRealmApp
  pod 'RealmSwift'
end
```
Robin

**Comment by tgoyne** [comment] 2016-05-12 23:05
Please try the steps given in https://github.com/realm/realm-cocoa/issues/3556#issuecomment-218752216, as that's worked for a few users.

**Comment by rcharlton** [comment] 2016-05-13 16:30
The rm Cocoapods and Clean Build Folder suggestions do not work for either of my projects.

Making the Realm.h header public allows the build to proceed until it fails with: 
_Header 'RLMAccessor.h' not found_

**Comment by tgoyne** [comment] 2016-05-13 16:41
We've now filed a Cocoapods bug for this: https://github.com/CocoaPods/CocoaPods/issues/5313. You can probably temporarily work around this by manually creating a symlink from `Versions/A/PrivateHeaders` to `PrivateHeaders` within the built `Realm.framework`.

**Comment by mrackwitz** [comment] 2016-05-14 10:29
As we could confirm this issue, I promoted this issue to `T:Bug`, even though it doesn't necessarily need to be fixed within this repo. Beside what @tgoyne proposed above, there is a possible workaround by PR #3582, but further validation is still outstanding.

**Comment by mrackwitz** [comment] 2016-05-18 13:33
It turned out that the possible workaround would break 0.39 inevitable. Meanwhile I've a filed a PR https://github.com/CocoaPods/CocoaPods/pull/5352, which is going to fix the root cause of that issue.

**Comment by jpsim** [comment] 2016-05-26 15:42
Keeping this open until CocoaPods 1.0.1 is released.

**Comment by jpsim** [comment] 2016-06-02 16:26
CocoaPods 1.0.1 is out: https://github.com/CocoaPods/CocoaPods/releases/1.0.1

thanks @mrackwitz.

**Closed by jpsim** 2016-06-02 16:26 UTC
Labels: S:On Hold, T:Bug

**Comment by amleszk** [comment] 2021-07-11 19:50
After much investigation into cocoapods I discovered this issue was caused by a git configuration issue where symbolic links were not being created in the git repository. The fix was:

`git config --global core.symlinks true`

and `git reset --hard HEAD`

and then do a clean build.
