### ISSUE TITLE
RealmSwift failed while Building Scheme Carthage

### ISSUE THREAD

**Issue by MohanabalanD** [realm/realm-cocoa#6788] opened 2020-09-19 12:11 UTC
**Questions**: RealmSwift failed while Building Scheme Carthage

**Feature Request**: Able to build RealmSwift in Carthage (XCode 12)

**Bugs**:  Building scheme "RealmSwift" in Realm.xcworkspace
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/mohanabalan/Documents/Repo/ios-MobileFirstION/Carthage/Checkouts/realm-cocoa/Carthage/Realm.xcworkspace -scheme RealmSwift -configuration Release -derivedDataPath /Users/mohanabalan/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A7209/realm-cocoa/v5.4.2 -sdk iphonesimulator -destination platform=iOS\ Simulator,id=EEA86542-ECCB-4D26-B6CC-83363EB5BEBD -destination-timeout 3 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES build (launched in /Users/mohanabalan/Documents/Repo/ios-MobileFirstION/Carthage/Checkouts/realm-cocoa)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/yw/4_r4ppsn43v5443gs3hy35r80000gp/T/carthage-xcodebuild.Nj911E.log

**Comment by twalshcbs** [comment] 2020-09-21 10:35
I get the same on all v5.4.x versions

**Comment by jsflax** [comment] 2020-09-21 11:05
This is a duplicate of #6717.

**Closed by jsflax** 2020-09-21 11:05 UTC
Labels: O-Community
