### ISSUE TITLE
Impossible to pass a RLMObject without a primary key between threads.

### ISSUE THREAD

**Issue by rogernolan** [realm/realm-cocoa#1512] opened 2015-02-17 14:16 UTC
I have a realm without a primary key - how do I pass objects to other threads?

**Comment by alazier** [comment] 2015-02-17 17:46
At the moment the best option is to add a primary key to your object. You an easily generate a random primary key using `NSUUID`.

We have been discussing ways of making this easier but haven't yet settled on a solution. One option would be to autogenerate primary keys for objects without them. The main issue with this approach is the performance cost. Another option would be a handoff mechanism that requires locking the Realms objects are being passed between. I feel that the complexity of this approach is too high. In any case this is something we are thinking about and we are working towards a better solution.

**Comment by rogernolan** [comment] 2015-02-17 17:51
That's what I did thanks.
FWIW, I like the performance of a class without a primary key but it would be nice to be able to turn on a auto generated primary key when I do need it to prevent having to use boilerplate UUID code and write (even a simple) a migration. I'm guessing you could implement something much faster than UUID generation too.

**Comment by jpsim** [comment] 2015-03-03 02:14
I'm closing this as a duplicate of #1097. Please continue the conversation there.

**Closed by jpsim** 2015-03-03 02:14 UTC
Labels: pending
