### ISSUE TITLE
"Unsupported Realm file format version" crash using Realm 1.0.2

### ISSUE THREAD

**Issue by Goner** [realm/realm-cocoa#4256] opened 2016-10-25 10:22 UTC
using XCode 8 and Realm 1.0.2   simulator ios10

**Comment by TimOliver** [comment] 2016-10-25 21:30
Thanks for your issue. I'm assuming this is a duplicate of https://github.com/realm/realm-cocoa/issues/4257, so I'll close this one down. If I'm mistaken, please re-open.

**Closed by TimOliver** 2016-10-25 21:30 UTC
Labels: T:Duplicate
