### ISSUE TITLE
Many crashes in random places on Realm (ObjC) after update to higher version

### ISSUE THREAD

**Issue by EugenKuzn** [realm/realm-cocoa#6911] opened 2020-11-04 13:38 UTC
After update to higher version app starts crashing for some devices in random places (mostly on methods addObjects, removeObjects). App crashes always on the same place after started crashing on that place (I see 20-30 crashes for one user with interval in 20-30 secs). Nothing can help, only one solution worked for me: re-install app and re-create realm database.

Mostly app crashes when you update from 5.a.b to 5.x.y
Noticed crashes after update from 3.a.b to 5.x.y

## Goals

Store simple objects with properties of type String, Bool, Int, Float, Double and etc.

## Expected Results

App should not crash after pod Realm updated to higher version.

## Actual Results

![Screenshot 2020-12-14 at 13 30 39](https://user-images.githubusercontent.com/33037693/102076590-9713fb00-3e10-11eb-893b-c7a37830172e.png)

## Steps for others to Reproduce

Create a few simple objects on old realm version, then update realm to some higher version.
App can start crashing on random places every time you launch/use app.

## Code Sample

App crashes on [RLMRealm addObjects:], [RLMRealm removeObjects:]
.
.
.
![98221536-6c549e00-1f58-11eb-9022-7457ae3a30e2](https://user-images.githubusercontent.com/33037693/98222004-fa308900-1f58-11eb-93a3-fea285e81158.png)

## Version of Realm and Tooling

Realm framework version: 5.5.0

Realm Object Server version: don't use server

Xcode version: 12.1

iOS/OSX version: iOS 12.3.1 (iPad Air 2)

Dependency manager + version: ?

**Comment by leemaguire** [comment] 2020-11-05 09:10
It's not clear where the issue is, and there is nothing Realm related in that crash screenshot. Could you please show us the method body of `[RFReferral write:]`

Thanks

**Comment by EugenKuzn** [comment] 2020-11-05 09:16
@leemaguire 

Pls take a look at the screenshot below, where I provided method `[RFReferral write:]` 👍 
No exceptions from Realm. It seems like it crashes somewhere inside lib.

App crashes on the line 117, which you can find on the screenshot below.
Thanks!

**Comment by EugenKuzn** [comment] 2020-11-05 09:17
@leemaguire 

Here is method:
.
.
![Screenshot 2020-11-05 at 11 16 56](https://user-images.githubusercontent.com/33037693/98221536-6c549e00-1f58-11eb-9022-7457ae3a30e2.png)

**Comment by leemaguire** [comment] 2020-11-05 09:19
There isn't much to go off here without a backtrace. Is your logger capturing anything? One thing I would say is, ensure you are not adding an object with a duplicate primary key.

**Comment by EugenKuzn** [comment] 2020-11-05 09:25
@leemaguire 

yes, that's true. I haven't had a chance to catch this crash on Simulator, backtrace on Firebase is too pure.
I don't use primary_key, because I don't care about uniqueness of entries in DB. And if I remember correct, there was a crash on some version 4.x.y related to primary_key usage

**Comment by EugenKuzn** [comment] 2020-11-05 09:27
@leemaguire 

The problem is that crash happens for small number of users. It seems like realm DB is damaged or something like that. 
If the crash happens, I see 50-70 crashes for user in a few hours (looks like app crashes on startup). After re-install app doesn't crash and work normally.

**Comment by leemaguire** [comment] 2020-11-05 09:31
Did you set any custom configuration for your Realm? Compaction, Schema changes etc?

**Comment by EugenKuzn** [comment] 2020-11-05 09:37
@leemaguire 

Configuration - NO: always use default realm (I mean `RLMRealm.defaultRealm`)
Compaction - NO: no need, because normally app uses around 200 simple entries like RFReferral
Schema - YES: I have a few simple migration, where I only add fields. Looks pls at the example of migration below:
.
.
![Screenshot 2020-11-05 at 11 37 03](https://user-images.githubusercontent.com/33037693/98223783-454b9b80-1f5b-11eb-99f0-30926ddf59b3.png)

**Comment by leemaguire** [comment] 2020-11-05 09:43
We need the error message thrown in the exception on [RLMRealm addObjects:] to dig further. I'd also recommend upgrading to the latest version of Realm v10.1.1

**Comment by EugenKuzn** [comment] 2020-11-05 09:51
@leemaguire 

Already updated to v10.1.1 and will keep tracking crashes. 
Thanks!

About exception thrown: not sure, how I can get error message thrown, because app crashes on the method [RLMRealm addObjects:], which crashes somewhere inside and doesn't throw any exceptions, which I can catch inside my catch-block.

**Comment by leemaguire** [comment] 2020-11-05 09:55
It's strange that you're not getting any exception info in your catch block, if you remove the try catch the error should bubble up in to the crash report.

**Comment by EugenKuzn** [comment] 2020-11-05 10:01
@leemaguire 

I agree, but it's possible. Plus I'm logging exceptions to file. It's empty, no crashes from Realm.
To be clear: app crashes on line 117 and app doesn't proceed to line 120 at all, which means that method doesn't throw any exceptions. Otherwise app doesn't crash, if it can proceed to line 120.

P.S. Thanks for help in advance 👍

**Comment by EugenKuzn** [comment] 2020-11-06 00:12
@leemaguire 

Today I got a perfect example.
Some user got 33 crashes in one hour. After re-install app works fine.
As you can see, app crashed every time on the same place.
.
.
.
![Screenshot 2020-11-06 at 02 08 02](https://user-images.githubusercontent.com/33037693/98310372-66e96900-1fd5-11eb-9f34-65b21d4c593e.png)

**Comment by leemaguire** [comment] 2020-11-06 09:10
@EugenKuzn Do you know if that user required to upgrade their Realm file version on launch? If so could you give the exact version of what they were on vs what version they upgraded to?  Thanks.

**Comment by EugenKuzn** [comment] 2020-11-06 09:40
@leemaguire 

The user updated from version 5.3.1 or 5.3.3 or 5.3.6 to version 5.5.0 (app crashed on 5.5.0, last version before 10)
I'm sure, that version was 5.3.x, where x can be 1, 3 or 6. 
Hope this helpful
Thanks!

**Comment by EugenKuzn** [comment] 2020-11-11 08:00
@leemaguire 

One more crash on simple Realm operation. 11 times per 1 user
Stack trace in Firebase console
![Screenshot 2020-11-11 at 09 59 08](https://user-images.githubusercontent.com/33037693/98785045-add7c400-2404-11eb-897c-e8226850ca0f.png)

Object interface
![Screenshot 2020-11-11 at 09 57 43](https://user-images.githubusercontent.com/33037693/98785053-b0d2b480-2404-11eb-8b12-41976d6e2c4e.png)

Method
![Screenshot 2020-11-11 at 09 57 02](https://user-images.githubusercontent.com/33037693/98785055-b0d2b480-2404-11eb-828c-ae99e02fcd15.png)

**Comment by EugenKuzn** [comment] 2020-11-13 17:00
@leemaguire 

One more user with crash on [RFReferral addObjects:] (19 crashes on each launch, happened yesterday)
![Screenshot 2020-11-13 at 18 58 12](https://user-images.githubusercontent.com/33037693/99098907-5b53fe80-25e2-11eb-91be-9ed82e7b3321.png)

**Comment by EugenKuzn** [comment] 2020-11-24 08:31
A few more users with the same crash on [RFReferral write:]
.
.
.
![Screenshot 2020-11-24 at 10 30 46](https://user-images.githubusercontent.com/33037693/100068447-39f3dd80-2e40-11eb-8d73-a4450eb944c2.png)

**Comment by EugenKuzn** [comment] 2020-12-01 15:04
One more client with the same problem
.
.
.
![Screenshot 2020-12-01 at 17 04 14](https://user-images.githubusercontent.com/33037693/100757676-54592880-33f7-11eb-9dca-8b65d15eabd7.png)

**Comment by EugenKuzn** [comment] 2020-12-11 22:30
Updated Realm to v.10.2.0 using Cocoapods v.2.6.0
Waiting for crash reports

**Comment by leemaguire** [comment] 2021-01-11 12:23
Closing this issue as it has been inactive for some time. If you have any other questions please open a new issue.

**Comment by EugenKuzn** [comment] 2021-01-12 10:46
@leemaguire 

Still no solution. Not sure, that closing issue = solving problem :)

**Comment by jsflax** [comment] 2021-01-12 11:45
@EugenKuzn without more info (a sandbox app reproducing the crash, a stacktrace with an error message), this is a fairly difficult error for us to debug.

Can you give us a larger code sample?

Are you doing any work across threads?

Can we see a bit more context around your call sites to `write`?

**Comment by EugenKuzn** [comment] 2021-01-12 12:10
@jsflax 

1. Nothing doing across threads, always main thread to avoid any crashes (I know, that Realm crashes, when you access to the same object from different threads)
2. Here is the stack trace:

![Screenshot 2021-01-12 at 14 08 31](https://user-images.githubusercontent.com/33037693/104312749-b5d4e280-54df-11eb-9b38-ff260bcfb70c.png)
.
.
3. Here is code around write (it's pretty simple):
![Screenshot 2021-01-12 at 14 07 36](https://user-images.githubusercontent.com/33037693/104312810-cc7b3980-54df-11eb-9ab2-4e7d9e4c59d7.png)
![Screenshot 2021-01-12 at 14 10 19](https://user-images.githubusercontent.com/33037693/104312903-eddc2580-54df-11eb-956d-ef33585da9c3.png)
![Screenshot 2021-01-12 at 14 10 06](https://user-images.githubusercontent.com/33037693/104312906-ee74bc00-54df-11eb-8203-c4350dd50a12.png)

**Comment by bmunkholm** [comment] 2021-11-08 18:09
@EugenKuzn Is this still a problem for you? Can you help us with a reproduction project?

**Comment by EugenKuzn** [comment] 2021-11-09 09:28
@bmunkholm no, this problem was resolved after Mongo DB took over and released version 10.x.y
I saw these crashes only on Realm version 5.x.y

Do you have the same issue?

**Comment by bmunkholm** [comment] 2021-11-09 10:40
Lovely thanks @EugenKuzn I'll close the issue then!

**Closed by bmunkholm** 2021-11-09 10:40 UTC
Labels: Reproduction-Required, O-Community
