### ISSUE TITLE
Index 1000 is out of bounds (must be less than 1000)

### ISSUE THREAD

**Issue by Vactorwang** [realm/realm-cocoa#7321] opened 2021-07-03 10:15 UTC
!!! MANDATORY TO FILL OUT !!!

## Goals
fix bounds out
## Expected Results
Terminating app due to uncaught exception 'RLMException', reason: 'Index 1000 is out of bounds (must be less than 1000).
## Actual Results
delete result prefix count
## Steps for others to Reproduce
only add most datas, and delete large amounts of data 

## Code Sample

class ViewController: UIViewController {

    override func viewDidLoad() {
        super.viewDidLoad()
        add()
    }

    override func touchesBegan(_ touches: Set<UITouch>, with event: UIEvent?) {
        del()
    }
    
    func add(){
        do {
            let r = try Realm()
            r.beginWrite()
            var obs = [TestObj]()
            for index in 0..<2000{
                obs.append(TestObj(index: "\(index)"))
            }
            r.add(obs, update:.all)
            try r.commitWrite()
        } catch {}
    }
    
    func del(){
        do {
            let r = try Realm()
            let obs = r.objects(TestObj.self)
            let result = obs[0...1000]
            r.beginWrite()
            r.delete(result)
            try r.commitWrite()
        } catch {}
    }
}

class TestObj:Object{
    @objc dynamic var index = ""
    override static func primaryKey() -> String? {
        return "index"
    }
    
    convenience init(index:String) {
        self.init()
        self.index = index
    }
}

## Version of Realm and Tooling

Realm framework version: ?
10.9.0
Xcode version: ?
12.5.1
iOS/OSX version: ?
macos 11.4  ios 14.6
Dependency manager + version: ?

**Comment by jsflax** [comment] 2021-07-03 14:49
Your view controller only adds items on load. Touching the screen more than twice will naturally result in a crash. If there is something you'd like to better understand about building a view with Realm, we're happy to help, otherwise please close this ticket when you get a chance.

**Comment by Vactorwang** [comment] 2021-07-05 01:09
> Your view controller only adds items on load. Touching the screen more than twice will naturally result in a crash. If there is something you'd like to better understand about building a view with Realm, we're happy to help, otherwise please close this ticket when you get a chance.

I only touch the screen once.There is a similar scenario in my business. I have stored more than 2000 pieces of data. After a period of time, I deleted 1000 pieces and then it crashed

**Comment by jsflax** [comment] 2021-07-05 08:08
I'm unable to reproduce this with the code you provided. If you have a reproducible example, that would be helpful.

**Comment by pavel-ship-it** [comment] 2021-07-05 13:20
Hi @Vactorwang 
as said in the documentation

> Do not pass in a slice to a `Results` or any other auto-updating Realm collection 
 type (for example, the type returned by the Swift `suffix(_:)` standard library
 method). Instead, make a copy of the objects to delete using `Array()`, and pass
 that instead. Directly passing in a view into an auto-updating collection may
 result in 'index out of bounds' exceptions being thrown.

What you can do is - in`del()` to replace `let result = obs[0...1000]` with `let result: [TestObj] = obs[0..<1000].map {$0}`

**Closed by pavel-ship-it** 2021-07-05 13:20 UTC
Labels: O-Community
