### ISSUE TITLE
isEqualToObject: between RLMObject that has persisted and non-RLMObject object causes a crash

### ISSUE THREAD

**Issue by kishikawakatsumi** [realm/realm-cocoa#1605] opened 2015-03-11 21:30 UTC
### Related:
https://github.com/realm/realm-cocoa/pull/1548
https://github.com/realm/realm-cocoa/issues/1547

### Problem
`isEqualToObject:` between RLMObject that has persisted and non-RLMObject object causes a crash.
Since the RLMObject that has persisted try to compare each `realm` property, the non-RLMObject do not have `realm` property, that causes `unrecognized selector` exception.

### Reproduce

```
Dog *mydog = [[Dog alloc] init];
mydog.name = @"Rex";
mydog.age = 9;

RLMRealm *realm = [RLMRealm defaultRealm];
[realm transactionWithBlock:^{
    [realm addObject:mydog];
}];

[mydog isEqualToObject:[NSObject new]]; // Crash
```

### Stack trace

```
2015-03-12 06:23:36.999 Simple[4486:597542] -[NSObject realm]: unrecognized selector sent to instance 0x7f9b5844d500
2015-03-12 06:23:37.011 Simple[4486:597542] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSObject realm]: unrecognized selector sent to instance 0x7f9b5844d500'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000104b83f35 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x000000010481cbb7 objc_exception_throw + 45
	2   CoreFoundation                      0x0000000104b8b04d -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
	3   CoreFoundation                      0x0000000104ae327c ___forwarding___ + 988
	4   CoreFoundation                      0x0000000104ae2e18 _CF_forwarding_prep_0 + 120
	5   Simple                              0x0000000102aa6ec5 -[RLMObjectBase isEqualToObject:] + 65
	6   Simple                              0x0000000102aa5734 -[RLMObject isEqualToObject:] + 39
	7   Simple                              0x0000000102a97af4 -[AppDelegate application:didFinishLaunchingWithOptions:] + 1108
	8   UIKit                               0x000000010355f475 -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:] + 234
	9   UIKit                               0x000000010355ffbc -[UIApplication _callInitializationDelegatesForMainScene:transitionContext:] + 2463
	10  UIKit                               0x0000000103562d2c -[UIApplication _runWithMainScene:transitionContext:completion:] + 1350
	11  UIKit                               0x0000000103561bf2 -[UIApplication workspaceDidEndTransaction:] + 179
	12  FrontBoardServices                  0x00000001070912a3 __31-[FBSSerialQueue performAsync:]_block_invoke + 16
	13  CoreFoundation                      0x0000000104ab953c __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12
	14  CoreFoundation                      0x0000000104aaf285 __CFRunLoopDoBlocks + 341
	15  CoreFoundation                      0x0000000104aaea43 __CFRunLoopRun + 851
	16  CoreFoundation                      0x0000000104aae486 CFRunLoopRunSpecific + 470
	17  UIKit                               0x0000000103561669 -[UIApplication _run] + 413
	18  UIKit                               0x0000000103564420 UIApplicationMain + 1282
	19  Simple                              0x0000000102a97de3 main + 115
	20  libdyld.dylib                       0x0000000105108145 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

**Comment by segiddins** [comment] 2015-03-11 22:02
@kishikawakatsumi what version of Realm is this with?

**Comment by alazier** [comment] 2015-03-11 23:37
In all versions. Need to add:
```   
 if (![otherObject isKindOfClass:RLMObjectBase.class])) {
    return NO;
}
```
and a test.

**Comment by alazier** [comment] 2015-03-11 23:38
Feel free to make a pr with a fix

**Comment by segiddins** [comment] 2015-03-11 23:40
Actually, I'm not sure we should. `isEqualToObject` should only take an `RLMObject`, whereas `isEqual` should take `id`.

**Comment by alazier** [comment] 2015-03-11 23:42
The problem is we assume that an RLMObject actually is an RLMObject. In the case it isn't (which can easily happen in objc) we crash. I assume that is the issue here.

**Comment by segiddins** [comment] 2015-03-11 23:48
Right, but isn't that just user error?

**Comment by alazier** [comment] 2015-03-12 00:10
You are right it is a user error and it should throw an exception. On al-swift though we will crash instead as we access the ivar directly.  So on al-swift we should have this check and throw rather than crashing.

**Comment by segiddins** [comment] 2015-03-24 21:48
This has been fixed on `master`.

**Closed by segiddins** 2015-03-24 21:48 UTC
Labels: bug, P2

**Comment by Sebacho-Barajas** [comment] 2016-10-07 03:16
so do you have a sample of how to campare realm objects with non-realm objects?
