### ISSUE TITLE
Crash for exception that isn't thrown "Fatal Exception: RLMException The Realm is already in a write transaction"

### ISSUE THREAD

**Issue by cpinski** [realm/realm-cocoa#3814] opened 2016-06-30 22:35 UTC
## Goals

What do you want to achieve?

A great user experience.

## Expected Results

What did you expected to happen?

To not crash when writing.

## Actual Results

The app crashed even though my write transaction is in a do catch block.

## Steps to Reproduce

Its hard to tell what exactly went wrong but it happened during a write transaction. The exact error received was "Fatal Exception: RLMException The Realm is already in a write transaction."

## Code Sample

```
func updateUnitOfWork(realm: Realm, specificSessionIndexes: Results<SpecificSessionIndex>, newSessionIndex: SessionIndex, newSpecificSessionIndex: SpecificSessionIndex) {
    newSessionIndex.unitOfWork = specificSessionIndexes.first!.sessionIndex?.unitOfWork
    
    do {
        try realm.write {
            realm.add(newSessionIndex)
            realm.add(newSpecificSessionIndex)
        }
    } catch let error as NSError {
        print("Error: \(error.localizedDescription)")
    }
}
```

## Version of Realm and Tooling

Realm version:

Realm ( 1.0.1 )

Xcode version:

7.3.1

iOS/OSX version:

9.3.2

Dependency manager + version:

Cocoa pods 0.39.0

**Comment by bdash** [comment] 2016-06-30 22:43
The exception you're seeing is telling you that you're attempting to begin a write transaction while already inside a write transaction. Nesting write transactions in this manner is not supported. Realm raises exceptions in case of programmer error, and these exceptions are not intended to be caught at runtime. Rather, they indicate to a developer that they've misused the API in some manner.

**Comment by cpinski** [comment] 2016-07-01 00:03
What exactly is meant by nesting write transactions? I know we don't have anything such as: 
```
try realm.write {
    realm.add(newSessionIndex)
    realm.add(newSpecificSessionIndex)
    
    try realm.write {
        realm.add(newSessionIndex)
        realm.add(newSpecificSessionIndex)
    }
}
```
in our code base. Is something such as 
```
try realm.write {
    realm.add(newSessionIndex)
    realm.add(newSpecificSessionIndex)
}

try realm.write {
    realm.add(newSessionIndex)
    realm.add(newSpecificSessionIndex)
}
```
permitted?

**Comment by bdash** [comment] 2016-07-01 00:06
The former is not permitted as it begins a write transaction while an existing write transaction is open. The latter is permitted because it doesn't attempt to open more than one write transaction at a time.

**Comment by cpinski** [comment] 2016-07-01 00:12
Ok, thank you! We will investigate the issue on our end and see if anything turns up.

**Comment by cpinski** [comment] 2016-07-01 21:34
After some more investigation today I can see two different threads seemingly getting into the write block. Attached below is the stack trace. I was under the assumption that Realm would only allow one write per thread but this is indicating that two threads are writing at the same time. Any ideas what the issue could be or do we need to create a locking mechanism at our app level?

<img width="1927" alt="screen shot 2016-07-01 at 4 19 11 pm" src="https://cloud.githubusercontent.com/assets/4740365/16535011/a9826b60-3fa9-11e6-8679-bb40dca4beb5.png">
<img width="1927" alt="screen shot 2016-07-01 at 4 19 20 pm" src="https://cloud.githubusercontent.com/assets/4740365/16535012/ac65e4f6-3fa9-11e6-91c1-e5581edbe899.png">
<img width="1927" alt="screen shot 2016-07-01 at 4 19 27 pm" src="https://cloud.githubusercontent.com/assets/4740365/16535013/aedbe258-3fa9-11e6-9914-3fd3eb5dba83.png">
<img width="1927" alt="screen shot 2016-07-01 at 4 19 35 pm" src="https://cloud.githubusercontent.com/assets/4740365/16535015/b21686b2-3fa9-11e6-846e-2d062f0b29fc.png">

**Comment by tgoyne** [comment] 2016-07-01 21:42
Those screenshots show only a single thread in a write transaction. Thread 88 is waiting on the write lock so that it can begin a write transaction, and Thread 96 is currently in the process of committing a write transaction.

**Comment by tgoyne** [comment] 2016-07-01 21:44
They do however show what your actual problem probably is: an exception is being thrown from `mmap()` while committing the write transaction, which will result in the commit failing and the Realm being left in the write transaction. You're probably swallowing this error (presumably unintentionally), and then later trying to start another write transaction with the same instance.

**Comment by cpinski** [comment] 2016-07-01 21:48
Between `mmap()` and the apps code we don't have anything other than Realm. Our realm.write transactions are within do catch blocks but we aren't catching an exception here. Could Realm possibly be swallowing this error and leaving us in a bad state? Would there be any way to test this to verify?

**Comment by cpinski** [comment] 2016-07-01 21:53
Another thing to note is that we open a new Realm instance each time before we do ```try realm.write {
    realm.add(newSessionIndex)
    realm.add(newSpecificSessionIndex)
}```

**Comment by JadenGeller** [comment] 2016-07-01 21:57
@cpinski When you say "Our realm.write transactions are within do catch blocks but we aren't catching an exception here," do you mean something like this?
```swift
do {
    try realm.write {
        // perform writes
    }
} catch {
    // don't crash
}
```
If so, the exception is just being delayed making it more difficult to understand what went wrong. It's probably best to use `try!` unless you have a good reason to handle the exception.

**Comment by cpinski** [comment] 2016-07-01 22:02
@JadenGeller Our code does look as you described above. Currently we would like to catch the exception so that we can fix what we are doing incorrectly. As of now we are seeing rather consistent crashes with the error "RLMException The Realm is already in a write transaction" and would like to clean up our code and follow the proper guidelines as well as possible.

**Comment by bdash** [comment] 2016-07-01 22:09
An exception being thrown as part of committing a write transaction can leave the Realm in a write transaction. This likely explains why you're seeing "The Realm is already in a write transaction" when you attempt to start a write transaction in the future.

Understanding why an exception is being thrown when committing your write transaction seems like the key to addressing the problem you're seeing. We need to see information about the exception that's thrown to help with that though.

**Comment by JadenGeller** [comment] 2016-07-01 22:10
@cpinski Most use cases don't require dynamically recovering from errors at runtime. If you really do want to catch errors, make sure you rethrow any errors that you don't have a specific recovery plan for. If you catch and error but do nothing about it, that's considered "swallowing" the error, and will likely cause some mysterious failure later. It's easiest to debug a problem if you crash for errors that you don't have a recovery plan in place for.

**Comment by cpinski** [comment] 2016-07-01 22:15
That all makes sense. Im pretty sure we are currently doing something wrong when it comes to spinning up Realms and executing write transactions. How would you suggest I go about debugging this? Is there anything in the above statements that worry you about our setup or how we are executing writes?

**Comment by JadenGeller** [comment] 2016-07-01 22:18
Well, I suggest you first change your `try write`s to `try! write`s and see if you get more informative exceptions. If so, definitely share them with us, that'll definitely help us diagnose the issue! 🙂

**Comment by cpinski** [comment] 2016-07-05 19:03
I got the error to happen again and this is what the console spit out. 

```
fatal` error: 'try!' expression unexpectedly raised an error: Error Domain=io.realm Code=9 "mmap() failed: Cannot allocate memory size: 671088640 offset: 0" UserInfo={NSLocalizedDescription=mmap() failed: Cannot allocate memory size: 671088640 offset: 0, Error Code=9}: file /Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-703.0.18.8/src/swift/stdlib/public/core/ErrorType.swift, line 54
```

**Comment by cpinski** [comment] 2016-07-06 14:06
@jpsim @JadenGeller @bdash @tgoyne Was realm/realm-core#838 ever completed? I saw that it was referenced in issue [#3083](https://github.com/realm/realm-cocoa/issues/3083) but the page can no longer be found.

**Comment by bdash** [comment] 2016-07-06 14:19
The exception indicates that Realm is trying to map ~670MB of data as part of committing the write transaction. Is that figure in the right ballpark for the amount of data in your Realm file plus the new data being written?

**Comment by cpinski** [comment] 2016-07-06 14:21
Yes that is. We have a fairly data intensive app.

**Comment by bdash** [comment] 2016-07-06 14:45
Ok. I suspect that a fix that #3809 pulls in, described in the changelog as "Reduce address space used when committing write transactions", will address this.

**Comment by cpinski** [comment] 2016-07-06 14:57
Thanks you for the info. Is there any timeline for releasing that?

**Comment by bdash** [comment] 2016-07-06 16:26
Hopefully within the next week.

**Comment by cpinski** [comment] 2016-07-06 17:16
We just pulled in the change locally and it seems as though the crash is resolved using version 1.2.0 of core. It seems that the performance is a bit slow though. Is this an expected consequence or something that has yet to be optimized?

**Comment by bdash** [comment] 2016-07-06 17:25
It's great to hear that it addresses your crash. What do you mean when you say the performance is "a bit slow"? Can you provide some detail about what scenario you're measuring, how you're measuring it, and how it compares to the current Realm version?

**Comment by cpinski** [comment] 2016-07-06 18:53
Well it seems as though we have pushed the crash from a Realm file size of 671.1MB to 805.3MB. We are testing on a device which is an iPad Air 2 and using iExplorer to monitor the size of the realm on disk. As we were testing I was saying that the performance is slow because once it reached 671.1MB is seemed to be getting caught on a line indicating that it was searching for more memory to use. Thus it would take a while to actually write and update the size of the Realm on disk.

**Comment by bdash** [comment] 2016-07-06 19:30
Would you be able to collect and share a time profile using Instruments while your app is performing the writes? That would help us understand where time is being spent. You can email the Instruments trace to help@realm.io if you'd like to keep the information private.

**Comment by mrackwitz** [comment] 2016-07-25 09:01
@cpinski: If you would be willing to share a built version of your app as IPA privately with us together with some instructions how to reproduce this scenario, I think we could also collect the data we need ourselves, if that's easier for you.

**Comment by stel** [comment] 2016-08-15 12:21
What is the status for this issue? Can we close it?

**Comment by cpinski** [comment] 2016-08-15 13:44
We have unfortunately moved on from Realm for this use case. I am also not privileged enough to share a build at this moment.

**Comment by jpsim** [comment] 2016-08-15 16:21
I'm sorry to hear that @cpinski. We'll be closing this issue now.

**Closed by jpsim** 2016-08-15 16:21 UTC
Labels: T:Help
