### ISSUE TITLE
Encrypted Realm crashes on 64bit iOS devices when dealing with Shared Group stuff

### ISSUE THREAD

**Issue by dismory** [realm/realm-cocoa#1432] opened 2015-01-29 10:42 UTC
Realm 0.90.3 by CocoaPods

```
group.cpp:132: [realm-core-0.88.0] Assertion failed: top_size >= 3
0   RealmCrash                          0x0000000100171f3c _ZN7tightdb4util9terminateEPKcS2_l + 360
1   RealmCrash                          0x00000001001e5924 _ZN7tightdb5Group25reset_free_space_versionsEv + 0
2   RealmCrash                          0x00000001001ef544 _ZN7tightdb11SharedGroup10begin_readENS0_9VersionIDE + 188
3   RealmCrash                          0x0000000100155640 -[RLMRealm getOrCreateGroup] + 152
4   RealmCrash                          0x0000000100158e08 -[RLMRealm beginWriteTransaction] + 152
5   RealmCrash                          0x0000000100113d88 RLMUpdateRealmToSchemaVersion + 140
6   RealmCrash                          0x0000000100156d4c +[RLMRealm realmWithPath:key:readOnly:inMemory:dynamic:schema:error:] + 3828
7   RealmCrash                          0x0000000100155b28 +[RLMRealm realmWithPath:readOnly:error:] + 136
8   RealmCrash                          0x0000000100155a38 +[RLMRealm realmWithPath:] + 76
9   RealmCrash                          0x00000001000ec8b4 -[AppDelegate application:didFinishLaunchingWithOptions:] + 420
...
20  UIKit                               0x00000001876a63c0 UIApplicationMain + 1488
21  RealmCrash                          0x00000001000ecef0 main + 116
IMPORTANT: if you see this error, please send this log to help@realm.io.
```

There is no crash when encrypted on 32bit iOS devices.  If not encrypted, it works well on 32bit and 64bit.

Also, there are some interesting facts that the crash will suddenly be fixed if I do the following things:
- remove just one of my naive RLMObject subclasses(i.e. just has some primary value property but has no relationship property) from the build target
- make names(no longer than 63 bytes since it works well on 32bit devices) of RLMObject subclasses or their property names even shorter

Since the tightdb part of Realm is not open source, my guess is that there may be some calculation mistakes when dealing with Shared Group stuff on 64bit devices.

I made a simplified version of the crashed project by removing sensitive info, but I can not rename/remove all sensitive stuff due to the issue may have something to do with **the naming**, so I hope to send the project directly to the Realm team for debugging purpose.

**Comment by anlaital** [comment] 2015-02-02 17:13
:+1:

I'm getting this as well and had to disable encryption with Realm (0.90.4). Encryption does work correctly with the simulators. Hopefully you guys can get this fixed since this will block our release. If you need crash logs from Crashlytics, let me know and I'll sanitize them.

**Comment by yoshyosh** [comment] 2015-02-02 17:16
Any reproducible projects will help us a lot. Feel free to send to help@realm.io to keep things private.

**Comment by anlaital** [comment] 2015-02-02 17:36
Looks like I managed to isolate how to reproduce the crash. You just need a class with a name longer than 57 characters, so "@class apokerkopaerpokapeorkapeokrpaoekrapoerkapoerkapeorkapeeok : RLMObject" would not crash whilst "@class apokerkopaerpokapeorkapeokrpaoekrapoerkapoerkapeorkapeeoka : RLMObject" would. I have also e-mailed you a test project illustrating the crash on an iPhone 6 running in release mode.

**Comment by tgoyne** [comment] 2015-02-03 21:42
I've made a PR on core that fixes this. I'll try to get a build with the fixes for you as soon as it's been reviewed.

**Comment by tgoyne** [comment] 2015-02-04 18:26
0.90.5 has now been released with a fix for this (and no other changes).

**Closed by tgoyne** 2015-02-04 18:26 UTC
Labels: P1
