### ISSUE TITLE
Allow commitWriteTransactionWithoutNotifying:error: to work with any token/realm that is pointing to the same database file as the realm being written to, in the transaction.

### ISSUE THREAD

**Issue by kunalsood** [realm/realm-cocoa#4753] opened 2017-03-21 03:29 UTC
## Goals

My database tends to get large enough that committing write transactions on main thread does cause momentary UI freezes/hangs, so all my write transactions are committed on a background queue. Thread Safe References have only made this easier for me, which is great. I was very happy to see the introduction of `commitWriteTransactionWithoutNotifying:error:` method, now I can implement re-ordering of my table views which was messy (at best) to implement previously. But, wait, there is a caveat: `The tokens passed to this method must be for notifications for this specific RLMRealm instance. Notifications for different threads cannot be skipped using this method.`. Which means I must commit my write transaction which modifies the order of the items in the tableView on the main thread? because: if I pass the tableView's backing `RLMResults` to a background queue using a Thread Safe Reference, the  `RLMRealm` instance on the background queue is different from the one on the main/UI thread, so I can not really use this method with my token from the main thread.

## Expected Results

I would like to be able to commit write transaction on a background queue, and skip notification on the main thread.

## Actual Results

`@throw RLMException(@"Incorrect Realm: only notifications for the Realm being modified can be skipped.");`

**Comment by istx25** [comment] 2017-03-21 19:23
Hi @kunalsood. Thanks for reaching out about this. I'll get some eyes on this and see what we can do to work around this problem.

**Comment by istx25** [comment] 2017-03-21 19:23
Whoops, didn't mean to add the `Blocked` tag.

**Comment by TimOliver** [comment] 2017-03-24 20:20
Hi @kunalsood! Thanks for your issue. I just had a little look into it, and it looks like you may have highlighted a weakness in our API. Realm notification tokens are paired with a specific Realm instance, so they can't be used with different instances pointing to the same Realm backing on background threads. Unfortunately there doesn't seem to be a way to create a thread reference for tokens.

@tgoyne or @austinzheng might be able to shed some additional light on this. It might be worth adding this to our feature list.

**Comment by jpsim** [comment] 2017-03-24 23:42
This limitation of writes skipping notifications is there by design. Lifting it would make usage prone to race conditions, leading to `NSInternalInconsistencyException`s in your connected UITableView/UICollectionView integrations.

In your specific example, you have two incompatible goals: to make modifications synchronously (reordering your tableview cells) but commit these modifications asynchronously (writes on background thread). This approach is inherently "racey", since the Realm on your UI thread is no longer synchronized to your UITableView/UICollectionView.

**Comment by austinzheng** [comment] 2017-04-10 18:38
I'm going to close this because JP's comment above addresses the issue. Please file more issues if anything else comes up, and thanks for using Realm!

**Closed by austinzheng** 2017-04-10 18:38 UTC
Labels: S:Waiting For User, T:Help
