### ISSUE TITLE
Make List and Results Sliceable

### ISSUE THREAD

**Issue by segiddins** [realm/realm-cocoa#1448] opened 2015-02-03 18:10 UTC

**Comment by alazier** [comment] 2015-02-03 20:11
This requires core support for querying on results/listViews with offset/limit

**Comment by bmunkholm** [comment] 2015-02-03 22:31
That was supported years ago :-) Check query.hpp find_all() and aggregates support it already.

**Comment by tgoyne** [comment] 2015-02-03 23:40
The problem is further querying the sliced results. Filtering a Query on a TableView doesn't retain the TableView, so we can't use anything that requires that.

**Comment by bmunkholm** [comment] 2015-02-04 07:04
So we need a ticket in core that describes the needed updates.

**Comment by timanglade** [comment] 2015-04-28 20:40
Closing as a duplicate of #1580

**Closed by timanglade** 2015-04-28 20:40 UTC
Labels: blocked, P3, swift
