### ISSUE TITLE
Realm ___pthread_kill what 's the matter?

### ISSUE THREAD

**Issue by blackteachinese** [realm/realm-cocoa#3918] opened 2016-07-27 16:35 UTC
```
OS Version:          iPhone OS 9.3.2 (13F69)
Report Version:      104
Exception Type:  SIGABRT
Exception Codes: #0 at 0x183ba411c
Triggered by Thread:  36
Thread 36 Crashed:
0   libsystem_kernel.dylib          0x0000000183ba411c ___pthread_kill :8 (in libsystem_kernel.dylib)
1   libsystem_c.dylib               0x0000000183b15dac _abort :140 (in libsystem_c.dylib)
2   Project              0x0000000100b81204 _please_report_this_error_to_help_at_realm_dot_io :12 (in Project)
3   Project              0x0000000100b812ec __ZN5realm4util18terminate_internalERNSt3__118basic_stringstreamIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE :232 (in Project)
4   Project              0x0000000100b8145c __ZN5realm4util9terminateEPKcS2_l :340 (in Project)
5   Project              0x0000000100b7db78 __ZN5realm4util4File5closeEv :80 (in Project)
6   Project              0x0000000100ca77ec __ZN5realm5_impl17WriteLogCollectorD2Ev :72 (in Project)
7   Project              0x0000000100ca75b0 __ZN5realm5_impl17WriteLogCollectorD0Ev :12 (in Project)
8   Project              0x0000000100b6edac __ZN5realm5RealmD2Ev memory:2516 (in Project)
9   libc++.1.dylib                  0x000000018362e6a8 __ZNSt3__119__shared_weak_count16__release_sharedEv :60 (in libc++.1.dylib)
10  libobjc.A.dylib                 0x000000018366eb54 __ZL27object_cxxDestructFromClassP11objc_objectP10objc_class :148 (in libobjc.A.dylib)
11  libobjc.A.dylib                 0x000000018367a040 _objc_destructInstance :92 (in libobjc.A.dylib)
12  libobjc.A.dylib                 0x000000018367a0a0 _object_dispose :28 (in libobjc.A.dylib)
13  Project              0x0000000100b5afd8 -[RLMRealm dealloc] RLMRealm.mm:592 (in Project)
14  libobjc.A.dylib                 0x0000000183689ae8 __ZN12_GLOBAL__N_119AutoreleasePoolPage3popEPv :508 (in libobjc.A.dylib)
15  libdispatch.dylib               0x0000000183a63a58 __dispatch_root_queue_drain :2464 (in libdispatch.dylib)
16  libdispatch.dylib               0x0000000183a630b0 __dispatch_worker_thread3 :112 (in libdispatch.dylib)
17  libsystem_pthread.dylib         0x0000000183c6d470 __pthread_wqthread :1092 (in libsystem_pthread.dylib)
18  libsystem_pthread.dylib         0x0000000183c6d020 _start_wqthread :4 (in libsystem_pthread.dylib)
```

**Comment by mrackwitz** [comment] 2016-07-27 16:55
I saw that you created directly two related issue reports #3918 & #3919. I wonder whether these two crashes happened for the same installation?
How did you got access to these: Did they happen on one of your devices while debugging or are these reports from the appstore?
If the former should be the case, are you able to reproduce these crashes or in which situation they occurred?

**Comment by blackteachinese** [comment] 2016-07-27 17:02
these reports from the App Store and i can't reproduce these crash.

**Comment by blackteachinese** [comment] 2016-07-27 17:17
these crashes has happened on different device and almost one device at a time

**Comment by jpsim** [comment] 2016-07-27 19:20
@blackteachinese have you seen the comment over at https://github.com/realm/realm-cocoa/issues/3919#issuecomment-235649578? Is it possible you're deleting files while Realm is still accessing them?

**Comment by stel** [comment] 2016-08-15 12:41
@blackteachinese did you solve this problem or did you find a way to reproduce it? Should we close this issue?

**Comment by stel** [comment] 2016-08-17 08:31
Closing this issue for now because of inactivity and duplication of https://github.com/realm/realm-cocoa/issues/3919. @blackteachinese feel free to open a new issue if you need any further help.

**Closed by stel** 2016-08-17 08:31 UTC
Labels: S:Waiting For User, T:Bug-Crash
