### ISSUE TITLE
Linker Warning After Updating to 0.98.7

### ISSUE THREAD

**Issue by promisenxu** [realm/realm-cocoa#3434] opened 2016-04-14 07:35 UTC
After installing 0.98.7 and build my app via Xcode version 7.2 (7C68), it gives the following warning messages:

```
ld: warning: ignoring linker optimzation hint at __ZNK5realm5Table18get_backlink_countEmRKS0_m+0x80 because ldrInfoC.offset == 0
ld: warning: ignoring linker optimzation hint at __ZNK5realm5Table12get_backlinkEmRKS0_mm+0x88 because ldrInfoC.offset == 0
ld: warning: ignoring linker optimzation hint at __ZN5realm5Table29connect_opposite_link_columnsEmRS0_m+0x4C because ldrInfoC.offset == 0
ld: warning: ignoring linker optimzation hint at __ZN5realm5Table16update_subtablesEPKmS2_PNS0_15SubtableUpdaterE+0x94 because ldrInfoC.offset == 0
ld: warning: ignoring linker optimzation hint at __ZN5realm5Table19upgrade_file_formatEv+0x12C because ldrInfoC.offset == 0
ld: warning: ignoring linker optimzation hint at __ZNK5realm5Table15get_column_linkEm+0x1C because ldrInfoC.offset == 0
ld: warning: ignoring linker optimzation hint at __ZNK5realm5Table20get_column_link_listEm+0x1C because ldrInfoC.offset == 0
ld: warning: ignoring linker optimzation hint at __ZN5realm5Table11do_set_linkEmmm+0x54 because ldrInfoC.offset == 0
ld: warning: ignoring linker optimzation hint at __ZN5realm5Table12get_linklistEmm+0x4C because ldrInfoC.offset == 0
ld: warning: ignoring linker optimzation hint at __ZNK5realm5Table3getINS_10StringDataEEET_mm+0xE0 because ldrInfoC.offset == 0
ld: warning: ignoring linker optimzation hint at __ZNK5realm5Table3getINS_10StringDataEEET_mm+0x138 because ldrInfoC.offset == 0
ld: warning: ignoring linker optimzation hint at __ZNK5realm5Table3getINS_10BinaryDataEEET_mm+0x78 because ldrInfoC.offset == 0
ld: warning: ignoring linker optimzation hint at __ZN5realm5Table10set_binaryEmmNS_10BinaryDataE+0xAC because ldrInfoC.offset == 0
ld: warning: ignoring linker optimzation hint at __ZNK5realm5Table9get_mixedEmm+0x44 because ldrInfoC.offset == 0
ld: warning: ignoring linker optimzation hint at __ZN5realm5Table9set_mixedEmmNS_5MixedE+0x78 because ldrInfoC.offset == 0
ld: warning: ignoring linker optimzation hint at __ZNK5realm5Table8get_linkEmm+0x30 because ldrInfoC.offset == 0
ld: warning: ignoring linker optimzation hint at __ZN5realm5Table8set_linkEmmm+0x7C because ldrInfoC.offset == 0
ld: warning: ignoring linker optimzation hint at __ZNK5realm5Table12get_linklistEmm+0x34 because ldrInfoC.offset == 0
ld: warning: ignoring linker optimzation hint at __ZNK5realm5Table17find_first_stringEmNS_10StringDataE+0x84 because ldrInfoC.offset == 0
ld: warning: ignoring linker optimzation hint at __ZNK5realm5Table17find_first_stringEmNS_10StringDataE+0xFC because ldrInfoC.offset == 0
```

**Comment by jpsim** [comment] 2016-04-14 07:39
It would be very useful if you could fill out our issue template: https://github.com/realm/realm-cocoa/blob/master/.github/ISSUE_TEMPLATE.md

Especially relevant is the installation method, and whether or not the issue goes away if you clear Xcode's cache (deleting derived data), or reset your CocoaPods (if relevant):

```
pod cache clean Realm
pod cache clean RealmSwift
pod deintegrate || rm -rf Pods
pod install --verbose
```

**Comment by promisenxu** [comment] 2016-04-14 07:57
Wow! This was a very fast response! Really appreciate it! I tried all of the above commands and cleaned the project cache, however the problem persists. I updated Realm from 0.98.6 to 0.98.7, and experienced these warnings. Furthermore, by changing the Pod file I am not able to go back to 0.98.6.

Realm version: 0.98.7
Xcode version: 7.2 (7C68)
iOS/OSX version: iOS 8.4 (might not be applicable here, the app does build successfully, just have lots of warnings)
Dependency manager + version: Cocoapods 0.39.0

**Comment by promisenxu** [comment] 2016-04-14 08:01
I tried pod 'Realm', '~> 0.98.6' to re-run pod install, but 0.98.7 still gets installed. Even if I remove Realm and reinstall it, still couldn't go back to the earlier version...Unless I go back to a previous commit and avoid running pod install/pod update.

**Comment by jpsim** [comment] 2016-04-14 08:40
Hi @promisenxu, I could reproduce the same linker warnings using the same configuration as you (though Xcode 7.2.1 7C1002). I suspect that this is happening because Realm's core binary was built using clang from Xcode 7.3, as this linker warning isn't present on that version of Xcode.

Generally, we try to support Xcode versions going back to 6.4 for Realm Objective-C, so this is something we'll look into further to see if we can avoid the linker warning. Thanks for reporting this.

**Comment by promisenxu** [comment] 2016-04-14 09:09
Thank you so much @jpsim ! Does it mean if Xcode is upgraded, the warnings should go away?

**Comment by jpsim** [comment] 2016-04-14 09:21
Yes

**Comment by austinzheng** [comment] 2016-05-18 19:57
If we're still interested in looking into this minor issue http://stackoverflow.com/questions/34820679/how-do-i-resolve-linker-warning-ignoring-linker-optimzation-hint-at-in-xcode might be useful.

**Comment by jpsim** [comment] 2016-05-18 22:18
As of #3575, Xcode 7.3 is required to build Realm, so we'll be closing this issue.

**Closed by jpsim** 2016-05-18 22:18 UTC
Labels: S:P2 Backlog, T:Bug
