### ISSUE TITLE
FR: BOOL property on RLMRealm for inWriteTransaction

### ISSUE THREAD

**Issue by webstersx** [realm/realm-cocoa#1817] opened 2015-05-02 16:13 UTC
I often write methods like below so that I can easily create one or many of my model objects on demand:

```objective-c
- (NSArray*) addModels:(NSArray*)modelsJson {
  NSMutableArray *models = [NSMutableArray array];

  [_realm beginWriteTransaction];
  for (NSDictionary *json in modelsJson) {
    [objects addObject:[self addModel:json]];
  }
  [_realm commitWriteTransaction];

  return models.copy;
}

- (Model*) addModel:(NSDictionary*)modelJson {
  /* I want to test where I'm currently in a write transaction so I know whether I need to begin one or not */
  Model *model = [Model createOrUpdateInRealm:_ream withObject:modelJson];
  /* I want to test where I'm currently in a write transaction so I know whether I need to commit or not */

  return model;
}
```

I currently have to add another signature for addModel:commit: to test

It would be great if you could extend RLMRealm so I can just query the realm instead

Thanks!

**Comment by segiddins** [comment] 2015-05-02 18:15
Thanks for the request @webstersx, but I'm going to go ahead and close this as a duplicate of https://github.com/realm/realm-cocoa/issues/1541, which already has making `inWriteTransaction` public as a part of our immediate roadmap.

**Closed by segiddins** 2015-05-02 18:15 UTC
