### ISSUE TITLE
Cannot iterate unmanaged LinkingObjects property

### ISSUE THREAD

**Issue by kishikawakatsumi** [realm/realm-cocoa#4259] opened 2016-10-25 17:48 UTC
## Goals

Iterate unmanaged LinkingObjects property

```swift
class Article: Object {
    dynamic var text = ""
    dynamic var writer: User?
}

class User: Object {
    dynamic var name = ""
    let articles = LinkingObjects(fromType: Article.self, property: "writer")
}
```

```swift
let article = Article()
let user = User()
article.writer = user

let articles = user.articles
for article in articles { // EXC_BAD_ACCESS
    print(article)
}
```

## Expected Results

Should not crash.

## Actual Results

Crash occurred at L95 in RLMCollection.mm `Class accessorClass = _info->rlmObjectSchema.accessorClass;`. Because `_info` is `NULL`

```objc
- (NSUInteger)countByEnumeratingWithState:(NSFastEnumerationState *)state
                                    count:(NSUInteger)len {
    [_realm verifyThread];
    if (!_tableView.is_attached() && !_collection) {
        @throw RLMException(@"Collection is no longer valid");
    }
    // The fast enumeration buffer size is currently a hardcoded number in the
    // compiler so this can't actually happen, but just in case it changes in
    // the future...
    if (len > RLMEnumerationBufferSize) {
        len = RLMEnumerationBufferSize;
    }

    NSUInteger batchCount = 0, count = state->extra[1];

    Class accessorClass = _info->rlmObjectSchema.accessorClass;
```

## Steps to Reproduce

Execute above code after `v1.1.0`.
To be strict, this crash occurs from 5ae668399f1f83b55917456c21c898f318de9137.

## Code Sample

```swift
class Article: Object {
    dynamic var text = ""
    dynamic var writer: User?
}

class User: Object {
    dynamic var name = ""
    let articles = LinkingObjects(fromType: Article.self, property: "writer")
}
```

```swift
let article = Article()
let user = User()
article.writer = user

let articles = user.articles
for article in articles { // EXC_BAD_ACCESS
    print(article)
}
```

## Version of Realm and Tooling

Realm version: v1.1.0 or after
Xcode version: 8.0

CC @tgoyne @jpsim

**Comment by bdash** [comment] 2016-10-25 18:16
Looks to be a duplicate of #4195. My PR in #4196 should address this.

**Closed** 2016-10-25 23:23 UTC
Labels: S:Review, T:Bug-Crash
