### ISSUE TITLE
RLMGenerator.next() could not cast value of type 'XYZ'

### ISSUE THREAD

**Issue by Entalpi** [realm/realm-cocoa#2384] opened 2015-08-11 20:27 UTC
I am receiving some weird casting errors from the RLMGenerator.next method. I can request three of the objects from the generator before it tires to cast everything into my model class type [H_News.NewsClass].

Here is a sample of the errors I am getting.

``` bash
(lldb) po readingPile?.nextNews()
Could not cast value of type 'OS_xpc_data' (0x1a0e9e540) to 'H_News.NewsClass' (0x1001c85a0).
error: Execution was interrupted, reason: signal SIGABRT.
The process has been returned to the state before expression evaluation.
(lldb) po readingPile?.nextNews()
2015-08-11 22:20:44.904 H-News[3877:1047565] -[NSISRestrictedToNonNegativeMarkerVariableToBeMinimized resize:]: unrecognized selector sent to instance 0x12791f6c0
error: Execution was interrupted, reason: internal ObjC exception breakpoint(-3)..
The process has been returned to the state before expression evaluation.
(lldb) po readingPile?.nextNews()
Could not cast value of type 'NSContentSizeLayoutConstraint' (0x1a0eba108) to 'H_News.NewsClass' (0x1001c85a0).
error: Execution was interrupted, reason: signal SIGABRT.
The process has been returned to the state before expression evaluation.
(lldb) po readingPile?.nextNews()
Could not cast value of type 'NSISLinearExpression' (0x1a0eb9988) to 'H_News.NewsClass' (0x1001c85a0).
error: Execution was interrupted, reason: signal SIGABRT.
The process has been returned to the state before expression evaluation.
```

I am using Xcode beta 4, running on Yosemite 10.10.4 together with Swift 2.0 on iOS 9.

**Comment by segiddins** [comment] 2015-08-11 20:30
@Entalpi this is quite strange, and I'm unsure how things are getting to this point. Could you please share the code that led to this happening? Thanks!

**Comment by Entalpi** [comment] 2015-08-11 20:38
Sure thing.

From the table view
```swift
    override func tableView(tableView: UITableView, cellForRowAtIndexPath indexPath: NSIndexPath) -> UITableViewCell {
        if let cell = tableView.dequeueReusableCellWithIdentifier("Cell", forIndexPath: indexPath) as? HNewsTableViewCell,
            let news = readingPile?.nextNews() {
            cell.news = news
            return cell
        }
        return UITableViewCell()
    }
```

Calls into 
```swift
    private var newsGenerator: RLMGenerator<NewsClass>?
    
    func nextNews() -> News? {
        if newsGenerator == nil {
            newsGenerator = realm?.objects(NewsClass).generate()
        }
        if let newsClass = newsGenerator?.next() {
            return newsClass.convertToNews()
        }
        
        return nil
    }
```

**Comment by segiddins** [comment] 2015-08-11 20:48
That's really strange, I can't tell that anything's obviously wrong just form that code snippet. Would you mind sharing your project with us, either here or privately at help@realm.io, so I can have a look at debugging? Thanks!

**Comment by Entalpi** [comment] 2015-08-11 20:56
Absolutely! I sent the project to the address. :)

**Comment by segiddins** [comment] 2015-08-11 21:21
I couldn't reproduce the issue in either a 32 or 64 bit simulator running Xcode 7 beta 5. Are there any specific circumstances needed to reproduce?

**Comment by Entalpi** [comment] 2015-08-11 21:24
Hmm, thats strange. I will try with the latest beta of Xcode. I might be that..

**Comment by Entalpi** [comment] 2015-08-11 21:29
For some reason I could not reproduce it either on the simulator ...

**Comment by segiddins** [comment] 2015-08-11 21:45
I also just tried on my iPhone 6, and couldn't reproduce it there either...

**Comment by Entalpi** [comment] 2015-08-11 21:46
Really strange, I will get back in a day or so when I have tested this through and through. :)

**Comment by segiddins** [comment] 2015-08-11 21:48
Thanks!

**Comment by Entalpi** [comment] 2015-08-12 08:50
Steps to reproduce
1. Open the App on simulator or device (clean install).
2. Wait for Hacker News top stories to load, then swipe (from left to right) on 8 (or more for other errors) stories.
3. Press the top right icon.
4. Try to scroll down the table view. --> CRASH

I tried this with Xcode beta 5, iOS 9. Both on simulator and device. I get a EXEC_BAD_ACCESS exception on the line 'let accessor = generatorBase.next() as! Element?'. Sometimes other errors occur but it is always something with Realm in the call stack.

![screen shot 2015-08-12 at 10 49 38](https://cloud.githubusercontent.com/assets/1652130/9220048/e3e2f0d2-40df-11e5-80be-356c2c9a6f97.jpg)

**Comment by segiddins** [comment] 2015-08-12 15:31
Awesome, thanks! I'll investigate shortly!

**Comment by segiddins** [comment] 2015-08-12 17:03
OK, so I've managed to reproduce this, and the issue seems to come down to us using our `NSFastEnumeration` implementation to back `RLMGenerator`. `RLMResults` and `RLMArray` both rely on an autoreleased buffer staying alive during fast enumeration, which doesn't happen when the fast enumeration state is held onto longer than a single enumeration.

**Comment by segiddins** [comment] 2015-08-12 17:23
For the time being, it's unsafe to hold onto an `RLMGenerator` across different autoreleasepools, and we need to decide if that limitation is worth the performance tradeoff of not being able to batch generate accessor objects in RealmSwift.

**Comment by Entalpi** [comment] 2015-08-12 17:27
The use cases are pretty divergent, the pros with being able to batch generate those objects enables things like dynamic paging and other fun stuff. I don't know how large of an tradeoff it is though.

**Comment by segiddins** [comment] 2015-08-12 17:40
Yeah,  I'll have to measure how big the loss is. This is one of those cases where the lack of an explicit enumeration protocol in swift is a hinderance, as there are optimizations we can apply to enumeration that flat out don't work for the general case of generation.

**Comment by tgoyne** [comment] 2015-08-12 18:11
The refactoring done in #2170 will make it fairly easy for RLMGenerator to strongly retain the enumeration helper rather than autoreleasing it (which is a hack around an obj-c problem that doesn't exist in Swift).

**Comment by austinzheng** [comment] 2017-06-27 17:54
The built-in iterator has been significantly changed since the last time this ticket was updated. Closing.

**Closed by austinzheng** 2017-06-27 17:54 UTC
Labels: S:Idea Backlog, T:Bug
