### ISSUE TITLE
Cannot set nil to a property in Realm

### ISSUE THREAD

**Issue by peihsendoyle** [realm/realm-cocoa#5032] opened 2017-06-13 08:23 UTC
Hi all, I'm here again after a long-time research on stackoverflow and issues. 

My case is:
1. Calling API return a list with nextPage and previousPage (this 2 properties allow nil) and add them to Realm.
2. Calling to the lastPage, of course nextPage is nil --> add to Realm, and bump...it's not nil. Is that Realm cannot write nil to a property?

Here is the code:
```
class ZStoreModel: Object {
    dynamic var identifier = ""
    dynamic var infors: String? = nil
    dynamic var errors: String? = nil
    dynamic var validationErrors: String? = nil
    dynamic var warnings: String? = nil
    dynamic var currentPage: Int = 0
    dynamic var totalPage: Int = 0
    dynamic var previousURL: String? = nil
    dynamic var nextURL: String? = nil
    var types: [String: ZModel.Type] = [:]
    dynamic var auto_create_node = true
    var _currentDataSource: ZServiceDataSource? = nil
    
    override static func primaryKey() -> String? {
        return "identifier"
    }
    
    override static func ignoredProperties() -> [String] {
        return ["types", "_currentDataSource"]
    }
    
    required init(dataSource: ZServiceDataSource, data: ZServiceResponseData? = nil) {
        super.init()
        
        self._currentDataSource = dataSource
        self.identifier = dataSource.md5Identifier
        self.auto_create_node = dataSource.auto_create_node
        self.types = dataSource.types
        
        guard let data = data else { return }
        
        self.infors = data.navigation?.infors?.description
        self.errors = data.navigation?.errors?.description
        self.validationErrors = data.navigation?.validationErrors?.description
        self.warnings = data.navigation?.warnings?.description
        self.currentPage = data.currentPage
        self.totalPage = data.totalPage
        
        if let previous_url = data.previousURL {
            self.previousURL = ZStoremanagerConfiguration.API + previous_url
        } else {
            self.previousURL = nil
        }
        
        if let next_url = data.nextURL {
            self.nextURL = ZStoremanagerConfiguration.API + next_url
        } else {
            self.nextURL = nil
        }
        
        Log.debug(self) <---- next URL is nil ---> OK, good from server API.
        ZRealmStore.add(self)
        Log.debug(self) <----next URL is not nil ---> they return old value.
    }
}
```
<img width="970" alt="screen shot 2017-06-13 at 2 50 56 pm" src="https://user-images.githubusercontent.com/7514128/27072917-2b8cf586-504c-11e7-9939-a55773b5f35d.png">

**Comment by Zhuinden** [comment] 2017-06-13 13:02
What is `ZRealmStore`?

**Comment by kishikawakatsumi** [comment] 2017-06-13 20:12
@peihsendoyle It seems duplicate of https://github.com/realm/realm-cocoa/issues/5000. Could we close this issue because the issue is tracked by #5000 and #4926 ?

**Comment by peihsendoyle** [comment] 2017-06-14 04:51
@kishikawakatsumi yes, it's really a duplicate of #5000. Thanks, I've just downgraded the Realm version to 2.7.0 and everything works. It seems a bug of Realm 2.8.0 and above.

**Comment by peihsendoyle** [comment] 2017-06-14 04:52
@Zhuinden it's just a wrapper for Realm operations like add, delete, retrieve objects...

**Closed** 2017-06-14 04:52 UTC
Labels: T:Help
