### ISSUE TITLE
Realm causes Leaks instrument to crash

### ISSUE THREAD

**Issue by joamaki** [realm/realm-cocoa#2738] opened 2015-10-23 13:47 UTC
While this is unlikely to be Realm's fault I'm reporting it here just in case as
it seems to be the only thing triggering this.

With Xcode 7.0 and 7.1 Realm causes the injected liboainject library to crash
when collecting memory leaks:

```swift
    func applicationDidFinishLaunching(aNotification: NSNotification) {
        // Insert code here to initialize your application
        Realm.Configuration.defaultConfiguration = Realm.Configuration(
            schemaVersion: 0,
            migrationBlock: { m, old in () }
        )
        let _ = try! Realm()
    }
```

Causes the following crash when ran through Instruments:
https://gist.github.com/joamaki/132dd96729284f951cd5

Leaving out the default configuration does not seem to trigger it.

Any ideas?

**Comment by bdash** [comment] 2015-10-27 01:54
I'm not able to reproduce this by dropping the code you pasted into a blank OS X Swift application and running under the Leaks instrument. Can you share a complete application that reproduces the problem?

**Comment by bdash** [comment] 2015-10-27 01:55
Can you also please share which version of Realm you're using?

**Comment by joamaki** [comment] 2015-10-28 09:40
Realm versions I tested with were 0.96.1 and 0.95.2. I observed this behaviour with 
Xcode 7.0.2 and 7.1. Also just tested on another machine and saw the same behaviour.

Complete app here: https://github.com/joamaki/leakcrash
Run "pod install", open leak crash.xcworkspace, Product -> Profile and select Leaks & record.

**Comment by bdash** [comment] 2015-10-28 16:02
Thanks, I can reproduce using your project. The crash log I get is a little different:

```
Thread 7 Crashed:
0   liboainject.dylib             	0x000000010d1c102a _OARecordFinalEvent + 20
1   liboainject.dylib             	0x000000010d1c1276 _OARecordFinalEvent + 608
2   liboainject.dylib             	0x000000010d1c2aa3 _objectalloc_logger + 313
3   libsystem_malloc.dylib        	0x00007fff85d3d9de malloc_zone_calloc + 118
4   libsystem_malloc.dylib        	0x00007fff85d3e472 calloc + 49
5   libobjc.A.dylib               	0x00007fff90f63bcd class_createInstance + 88
6   libdispatch.dylib             	0x00007fff967f910e _os_object_alloc_realized + 38
7   libdispatch.dylib             	0x00007fff967fb832 dispatch_source_create + 156
```

**Comment by angerman** [comment] 2015-11-11 06:37
I'm running into the same crash. Any news on this?

**Comment by jpsim** [comment] 2015-11-20 23:06
Unfortunately no progress to report on this yet. It's not quite obvious how to fix this.

**Comment by ReganBell** [comment] 2015-12-02 03:32
Bump, I've been having the same issue. Crash is identical to the log @joamaki posted.

**Comment by jamesk-au** [comment] 2015-12-17 08:38
I'm also having this issue with Xcode 7.2 and RealmSwift 0.96.3.

I can't see any material difference between the crash log posted by @bdash and the original log posted by @joamaki (focusing just on the crashed threads).

The crash log I get is slightly different—in particular, the crashed thread is always designated as "RLMRealm notification listener", even when there is no code for Realm notification blocks.  Lines 0 to 4 are otherwise identical to the logs posted above.

```
Thread 8 Crashed:: RLMRealm notification listener
0   liboainject.dylib             	0x000000010a0d21bc _OARecordFinalEvent + 418
1   liboainject.dylib             	0x000000010a0d227a _OARecordFinalEvent + 608
2   liboainject.dylib             	0x000000010a0d3aa7 _objectalloc_logger + 313
3   libsystem_malloc.dylib        	0x000000010e6a568e malloc_zone_calloc + 118
4   libsystem_malloc.dylib        	0x000000010e6a5dcf calloc + 49
5   libobjc.A.dylib               	0x000000010aaf5916 allocateBuckets(unsigned int) + 30
6   libobjc.A.dylib               	0x000000010aaf5ab7 cache_t::reallocate(unsigned int, unsigned int) + 43
7   libobjc.A.dylib               	0x000000010aaf5f3f cache_fill + 174
8   libobjc.A.dylib               	0x000000010aafee17 lookUpImpOrForward + 420
9   libobjc.A.dylib               	0x000000010ab0d8bb objc_msgSend + 187
10  com.apple.Foundation          	0x000000010a685f21 +[NSNotificationCenter defaultCenter] + 248
11  com.apple.Foundation          	0x000000010a781db2 __NSThread__start__ + 1125
12  libsystem_pthread.dylib       	0x000000010e7e5c13 _pthread_body + 131
13  libsystem_pthread.dylib       	0x000000010e7e5b90 _pthread_start + 168
14  libsystem_pthread.dylib       	0x000000010e7e3375 thread_start + 13
```

**Comment by jpsim** [comment] 2015-12-17 23:27
The logic around notification listeners has changed in 0.97, which was just released today. It's possible that this was resolved in the process. Could one of you please verify this? /cc @joamaki @angerman @ReganBell @jamesk-au 

Thanks!

**Comment by jamesk-au** [comment] 2015-12-19 05:20
Working for me now with RealmSwift 0.97.  Thanks very much!

**Comment by tbaranes** [comment] 2015-12-24 10:15
We are getting the same error as @bdash on our mac app. When running on the iOS version, instruments and Realm are working well together. Is the fix should run well on mac too?

**Comment by jpsim** [comment] 2015-12-30 20:30
Yes, I'd expect this to work on OS X too. Which version of Realm are you using?

**Comment by tbaranes** [comment] 2015-12-30 23:26
Never mind, just try again today and it's working well. Sorry to bother you!

**Comment by jpsim** [comment] 2015-12-30 23:30
No problem, happy to see this has been resolved.

**Closed by jpsim** 2015-12-30 23:30 UTC
Labels: bug, P2
