### ISSUE TITLE
SIGABRT in RLMAddObjectToRealm (RLMObjectStore.mm line 146)

### ISSUE THREAD

**Issue by wasi002** [realm/realm-cocoa#6365] opened 2019-11-27 05:19 UTC
App is crashing on iOS 13 only on the line number 146 of RLMObjectStore.mm

**Crash log**

Incident Identifier: 9D3AD555-0A8B-40AD-ABBF-F5F2ED510A2D
Beta Identifier:     DFC15202-16BE-4D6B-97D4-3AD7546B2479
Hardware Model:      iPhone9,2
Process:             WaveMoney [1471]
Path:                /private/var/containers/Bundle/Application/CBA02E2A-9F29-4DD5-A2A0-58AA80F7B9BD/WaveMoney.app/WaveMoney
Identifier:          mm.com.wavemoney.wavepay
Version:             21 (1.1.1)
AppStoreTools:       11B48b
AppVariant:          1:iPhone9,2:13
Beta:                YES
Code Type:           ARM-64 (Native)
Role:                Foreground
Parent Process:      launchd [1]
Coalition:           mm.com.wavemoney.wavepay [986]

Date/Time:           2019-11-24 10:29:36.5869 +0630
Launch Time:         2019-11-24 10:29:29.5675 +0630
OS Version:          iPhone OS 13.2.2 (17B102)
Release Type:        User
Baseband Version:    7.11.01
Report Version:      104

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Triggered by Thread:  0

Last Exception Backtrace:
0   CoreFoundation                	0x1a105d80c __exceptionPreprocess + 220 (NSException.m:199)
1   libobjc.A.dylib               	0x1a0d85fa4 objc_exception_throw + 56 (objc-exception.mm:565)
2   Realm                         	0x1063f9bd0 RLMAddObjectToRealm + 608 (RLMObjectStore.mm:146)
3   RealmSwift                    	0x106adc7e4 Realm.add<A>(_:update:) + 868 (Realm.swift:287)
4   WaveMoney                     	0x104784cec closure #2 in static WMContactHelper.syncContacts(_:) + 892 (WMContactHelper.swift:186)
5   RealmSwift                    	0x106adbfa0 Realm.write(_:) + 60 (Realm.swift:155)
6   WaveMoney                     	0x104785d60 specialized static WMContactHelper.syncContacts(_:) + 1616 (WMContactHelper.swift:178)
7   WaveMoney                     	0x1046be9f0 closure #1 in AppDelegate.application(_:didFinishLaunchingWithOptions:) + 112 (<compiler-generated>:0)
8   WaveMoney                     	0x1047847bc closure #1 in static WMContactHelper.fetchUserContact(_:) + 1052 (WMContactHelper.swift:59)
9   WaveMoney                     	0x1046c29f0 thunk for @escaping @callee_guaranteed (@guaranteed [APContact]?, @guaranteed Error?) -> () + 116 (<compiler-generated>:0)
10  libdispatch.dylib             	0x1a0d2a610 _dispatch_call_block_and_release + 24 (init.c:1408)
11  libdispatch.dylib             	0x1a0d2b184 _dispatch_client_callout + 16 (object.m:495)
12  libdispatch.dylib             	0x1a0cdd190 _dispatch_main_queue_callback_4CF$VARIANT$mp + 1044 (inline_internal.h:2484)
13  CoreFoundation                	0x1a0fdb3a8 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12 (CFRunLoop.c:1749)
14  CoreFoundation                	0x1a0fd639c __CFRunLoopRun + 2004 (CFRunLoop.c:3069)
15  CoreFoundation                	0x1a0fd58a0 CFRunLoopRunSpecific + 464 (CFRunLoop.c:3192)
16  GraphicsServices              	0x1aaf2d328 GSEventRunModal + 104 (GSEvent.c:2246)
17  UIKitCore                     	0x1a50c6740 UIApplicationMain + 1936 (UIApplication.m:4758)
18  WaveMoney                     	0x1045c8164 main + 68 (AppDelegate.swift:23)
19  libdyld.dylib                 	0x1a0e60360 start + 4

Thread 0 name:
Thread 0 Crashed:
0   libsystem_kernel.dylib        	0x00000001a0e55ec4 __pthread_kill + 8
1   libsystem_pthread.dylib       	0x00000001a0d71774 pthread_kill$VARIANT$mp + 112 (pthread.c:1456)
2   libsystem_c.dylib             	0x00000001a0cc58c0 __abort + 112 (abort.c:147)
3   libsystem_c.dylib             	0x00000001a0cc5850 abort + 112 (abort.c:118)
4   libc++abi.dylib               	0x00000001a0e1e7d4 abort_message + 128 (abort_message.cpp:76)
5   libc++abi.dylib               	0x00000001a0e1e9c4 demangling_terminate_handler() + 296 (cxa_default_handlers.cpp:66)
6   libobjc.A.dylib               	0x00000001a0d86258 _objc_terminate() + 124 (objc-exception.mm:701)
7   WaveMoney                     	0x0000000104896e20 CLSTerminateHandler() + 348
8   libc++abi.dylib               	0x00000001a0e2b304 std::__terminate(void (*)()) + 16 (cxa_handlers.cpp:59)
9   libc++abi.dylib               	0x00000001a0e2b29c std::terminate() + 44 (cxa_handlers.cpp:87)
10  libdispatch.dylib             	0x00000001a0d2b198 _dispatch_client_callout + 36 (object.m:498)
11  libdispatch.dylib             	0x00000001a0cdd190 _dispatch_main_queue_callback_4CF$VARIANT$mp + 1044 (inline_internal.h:2484)
12  CoreFoundation                	0x00000001a0fdb3a8 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12 (CFRunLoop.c:1749)
13  CoreFoundation                	0x00000001a0fd639c __CFRunLoopRun + 2004 (CFRunLoop.c:3069)
14  CoreFoundation                	0x00000001a0fd58a0 CFRunLoopRunSpecific + 464 (CFRunLoop.c:3192)
15  GraphicsServices              	0x00000001aaf2d328 GSEventRunModal + 104 (GSEvent.c:2246)
16  UIKitCore                     	0x00000001a50c6740 UIApplicationMain + 1936 (UIApplication.m:4758)
17  WaveMoney                     	0x00000001045c8164 main + 68 (AppDelegate.swift:23)
18  libdyld.dylib                 	0x00000001a0e60360 start + 4

Thread 1 name:
Thread 1:
0   libsystem_kernel.dylib        	0x00000001a0e5742c fsync + 8
1   libsqlite3.dylib              	0x00000001a2cd6de0 unixSync + 208 (sqlite3.c:38708)
2   libsqlite3.dylib              	0x00000001a2cd68c8 sqlite3PagerCommitPhaseOne + 1608 (sqlite3.c:22822)
3   libsqlite3.dylib              	0x00000001a2cc1d0c sqlite3BtreeCommitPhaseOne + 160 (sqlite3.c:73522)
4   libsqlite3.dylib              	0x00000001a2c8df44 sqlite3VdbeHalt + 2788 (sqlite3.c:85242)
5   libsqlite3.dylib              	0x00000001a2cba774 sqlite3VdbeExec + 54880 (sqlite3.c:93621)
6   libsqlite3.dylib              	0x00000001a2cabb5c sqlite3_step + 388 (sqlite3.c:88583)
7   libsqlite3.dylib              	0x00000001a2c731cc sqlite3_exec + 300 (sqlite3.c:125846)
8   WaveMoney                     	0x00000001049dec34 -[APMSqliteStore endTransaction] + 72
9   WaveMoney                     	0x00000001049de8ec -[APMSqliteStore performTransaction:] + 116
10  WaveMoney                     	0x00000001049a1b30 -[APMDatabase initializeAppMetadata] + 76
11  WaveMoney                     	0x00000001049ac0ec -[APMDatabase initializeDatabaseResourcesWithContext:databasePath:] + 168
12  WaveMoney                     	0x00000001049a1954 -[APMDatabase initWithDatabaseName:persistedConfig:] + 160
13  WaveMoney                     	0x00000001049b2998 __47-[APMMeasurement startMeasurementOnWorkerQueue]_block_invoke + 1012
14  libdispatch.dylib             	0x00000001a0d2b184 _dispatch_client_callout + 16 (object.m:495)
15  libdispatch.dylib             	0x00000001a0cd29a4 _dispatch_once_callout + 28 (once.c:52)
16  WaveMoney                     	0x00000001049b2584 -[APMMeasurement startMeasurementOnWorkerQueue] + 308
17  WaveMoney                     	0x00000001049b20f4 -[APMMeasurement setEnabledOnWorkerQueue:] + 228
18  WaveMoney                     	0x00000001049cadec __51-[APMScheduler scheduleOnWorkerQueueBlockID:block:]_block_invoke + 44
19  libdispatch.dylib             	0x00000001a0d2a610 _dispatch_call_block_and_release + 24 (init.c:1408)
20  libdispatch.dylib             	0x00000001a0d2b184 _dispatch_client_callout + 16 (object.m:495)
21  libdispatch.dylib             	0x00000001a0cd7404 _dispatch_lane_serial_drain$VARIANT$mp + 608 (inline_internal.h:2484)
22  libdispatch.dylib             	0x00000001a0cd7df8 _dispatch_lane_invoke$VARIANT$mp + 420 (queue.c:3863)
23  libdispatch.dylib             	0x00000001a0ce1314 _dispatch_workloop_worker_thread + 588 (queue.c:6445)
24  libsystem_pthread.dylib       	0x00000001a0d7af88 _pthread_wqthread + 276 (pthread.c:2323)
25  libsystem_pthread.dylib       	0x00000001a0d7dad4 start_wqthread + 8

Realm framework version: 3.2.0

Xcode version: 10.2.3

iOS/OSX version: 13.0.0 + 

Dependency manager + version: ?

**Comment by bmunkholm** [comment] 2019-11-27 06:46
@wasi002 Could you please fill out the issue template? We would like to know if this is reproducible, has occurred more than once etc.

**Comment by leemaguire** [comment] 2020-07-01 14:15
Closing due to age and lack of information. If you have any more questions please open a new issue.

Thanks.

**Closed** 2020-07-01 14:16 UTC
Labels: O-Community
