### ISSUE TITLE
Question about createOrUpdate

### ISSUE THREAD

**Issue by jault3** [realm/realm-cocoa#1322] opened 2015-01-12 07:35 UTC
No matter what I seem to do, RLMArray.firstObject() always returns nil. Same with objectAtIndex() or indexing into it like an array, say with [0]. Im using swift.

It would be really helpful to have support for Arrays of basic types in subclasses of RLMObject. But that aside, here is my class.

```
class RTruck: RLMObject {
    dynamic var id = ""
    dynamic var name = ""
    dynamic var imageUrl = ""
    dynamic var keywords = RLMArray(objectClassName: RString.className())
    dynamic var latitude = 0.0
    dynamic var longitude = 0.0
    dynamic var isNew = false
    dynamic var isInServingMode = false
    
    override init() {
        super.init()
    }
    
    override class func primaryKey() -> String! {
        return "id"
    }
}
```

and the basic class holding a simple string

```
class RString: RLMObject {
    dynamic var value = ""
    
    class func initFromString(string: String) -> RString {
        let rstring = RString()
        rstring.value = string
        return rstring
    }
}
```

The problem will lie in that array of RString objects, keywords. Im using Alamofire to get back some data from the network. The data is perfect, I've checked it. In fact, the data is perfect halfway through realm. Here is where it goes wrong

```
var truckResponse = ActiveTrucksResponse.parseFromNSData(data!)
            
let realm = RLMRealm.defaultRealm()
realm.beginWriteTransaction()
            
for truck in truckResponse.trucks {
    let activeTrucksResponseTruck = truck as ActiveTrucksResponse.Truck
    let rresponse = RTruck.objectsWhere("id = %@", activeTrucksResponseTruck.id)
    // I have to check if there are results because its possible there aren't any at this point
    var rtruck: RTruck? = nil
    if rresponse.count == 0 {
        // if no results, setup a truck to store
        rtruck = RTruck()
        rtruck!.id = activeTrucksResponseTruck.id
    } else {
        rtruck = rresponse.firstObject() as? RTruck
    }
    println("at - keys \(rtruck!.keywords) and count \(rtruck!.keywords.count) and first \(rtruck!.keywords.firstObject()) using index \(rtruck!.keywords.objectAtIndex(0))")
    rtruck!.latitude = activeTrucksResponseTruck.latitude
    rtruck!.longitude = activeTrucksResponseTruck.longitude
    RTruck.createOrUpdateInRealm(realm, withObject: rtruck!)
}
realm.commitWriteTransaction()
```

Here is what I get in the console

```
at - keys RLMArray <0x7f8357887610> (
	[0] RString {
		value = Awesome;
	},
	[1] RString {
		value = Truck;
	}
) and count 2 and first  using index 
at - keys RLMArray <0x7f83578a32e0> (
	[0] RString {
		value = Wicked;
	},
	[1] RString {
		value = Awesome;
	},
	[2] RString {
		value = Grill;
	}
) and count 3 and first  using index 
```

As you can see, I get the full RLMArray object printed out just fine. The data shown is the exact data I need. It even shows the count correctly. But when I try to get a single object, its empty, nil, not there, etc. Ive tried the methods shown and indexing using [0]. Not really sure what's going on here. Any ideas?

Also, running this on a iPhone 6 Simulator running iOS 8. Although that doesn't __seem__ to matter as it also happens on my real device. Really enjoying Realm so far by the way!

**Comment by jpsim** [comment] 2015-01-12 19:53
I think this might be related to Swift's picky dynamic casting behavior. Can you try `rtruck = rresponse.firstObject() as RTruck` instead of `rtruck = rresponse.firstObject() as? RTruck`?

**Comment by jault3** [comment] 2015-01-12 20:33
Thanks for the quick response @jpsim ! But unfortunately that ended up with the same output. Heres what I changed

```
if rresponse.count == 0 {
    rtruck = RTruck()
    rtruck!.id = activeTrucksResponseTruck.id
} else {
    rtruck = rresponse.firstObject() as RTruck
}
```

and the output

```
at - keys RLMArray <0x7fcd86683dd0> (
	[0] RString {
		value = Awesome;
	},
	[1] RString {
		value = Truck;
	}
) and count 2 and first  using index 
at - keys RLMArray <0x7fcd84f04dc0> (
	[0] RString {
		value = Wicked;
	},
	[1] RString {
		value = Awesome;
	},
	[2] RString {
		value = Grill;
	}
) and count 3 and first  using index 
```

I also tried casting it to an implicitly unwrapped optional with the same result (`rtruck = rresponse.firstObject() as RTruck!`).

And just for kicks I tried messing around with making it a constant and skipping the whole optionals concept all together. 

```
let rtruck = rresponse.firstObject() as RTruck
println("at - keys \(rtruck.keywords) and count \(rtruck.keywords.count) and first \(rtruck.keywords.firstObject()) using index \(rtruck.keywords.objectAtIndex(0))")
rtruck.latitude = activeTrucksResponseTruck.latitude
rtruck.longitude = activeTrucksResponseTruck.longitude
RTruck.createOrUpdateInRealm(realm, withObject: rtruck)
```

But again I got the same output. Let me know if I should try something else.

**Comment by jpsim** [comment] 2015-01-12 20:57
Ok, so the issue is actually that there is a bug in making Objective-C classes conform to `Printable` (see #840), which means that `"\(rlmObject)"` prints nothing, but `"\(rlmObject.description)"` prints the description as expected. This is fixed in our upcoming new Swift API, but can't be fixed in our existing Swift API.

Here's the complete code to an AppDelegate that should be able to help you:

```swift
import UIKit
import Realm

class RString: RLMObject {
    dynamic var value = ""
}

class RTruck: RLMObject {
    dynamic var id = ""
    dynamic var name = ""
    dynamic var imageUrl = ""
    dynamic var keywords = RLMArray(objectClassName: RString.className())
    dynamic var latitude = 0.0
    dynamic var longitude = 0.0
    dynamic var isNew = false
    dynamic var isInServingMode = false

    override class func primaryKey() -> String! {
        return "id"
    }
}

struct Truck {
    let id: String
    let latitude: Double
    let longitude: Double
}

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {

    var window: UIWindow?

    func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: NSDictionary?) -> Bool {

        self.window = UIWindow(frame: UIScreen.mainScreen().bounds)
        self.window!.rootViewController = UIViewController()
        self.window!.makeKeyAndVisible()

        NSFileManager.defaultManager().removeItemAtPath(RLMRealm.defaultRealmPath(), error: nil)

        let trucks = [
            Truck(id: "1", latitude: 0.0, longitude: 0.0),
            Truck(id: "2", latitude: 0.0, longitude: 0.0)
        ]

        let realm = RLMRealm.defaultRealm()
        realm.beginWriteTransaction()

        for activeTrucksResponseTruck in trucks {
            let rresponse = RTruck.objectsWhere("id = %@", activeTrucksResponseTruck.id)
            // I have to check if there are results because its possible there aren't any at this point
            let rtruck: RTruck = {
                if let responseTruck = rresponse.firstObject() as RTruck? {
                    return responseTruck
                }
                // if no results, setup a truck to store
                let newTruck = RTruck()
                newTruck.id = activeTrucksResponseTruck.id
                return newTruck
            }()
            println(rtruck.description)
            rtruck.latitude = activeTrucksResponseTruck.latitude
            rtruck.longitude = activeTrucksResponseTruck.longitude
            RTruck.createOrUpdateInRealm(realm, withObject: rtruck)
        }
        realm.commitWriteTransaction()

        return true
    }
}
```

**Comment by jault3** [comment] 2015-01-14 05:54
Thanks @jpsim that seems to have worked. Here's what I get as my println for the description

```
RTruck {
	id = 5da1bcd7-8e41-47d2-8792-5da60c6efd85;
	name = Wicked Awesome Grill;
	imageUrl = https://google.com;
	keywords = RLMArray <0x7fcc7e313f80> (
	[0] RString {
		value = Wicked;
	},
	[1] RString {
		value = Awesome;
	},
	[2] RString {
		value = Grill;
	}
);
	latitude = 0;
	longitude = 0;
	isNew = 0;
	isInServingMode = 0;
}
```

It's very strange why such an odd approach has to be taken to get it to work. But anyways, I got to another part in the code where that list of trucks is passed around. And now I want to actually use the keywords on one of those RTruck objects and display each of them on screen. So, there are two strange things that happen here. The first being the following line of code,

```
join(", ", myRLMArrayInstance)
```

If you give the join method an instance of myRLMArrayInstance it says it does not conform to the SequenceProtocol. Which is not correct because I know it does conform to that protocol in the RLMSupport.swift file. So to get around that, I figured I would loop through the items in my RLMArray instance and add them to my own array and do the join that way. Probably not the best approach but I just wanted to get it working first.

```
func updateViewWithTruck(truck:RTruck) {
    println(truck.description)
    var keywords = [String]()
    println("tdo - keywords \(truck.keywords.description) and \(truck.keywords.count) and first \(truck.keywords.firstObject() as RString)")
    for keyword in truck.keywords {
        let v = (keyword as RString).value
        keywords.append((keyword as RString).value)
    }
    truckTagsLabel.text = join(", ", keywords)
}
```

So I printed out the truck that came from the method we worked on in my previous comments. It prints out great! except for the keywords part. Here is an example of this println `println(truck.description)`

```
RTruck {
	id = 5da1bcd7-8e41-47d2-8792-5da60c6efd85;
	name = Wicked Awesome Grill;
	imageUrl = https://google.com;
	keywords = RLMArray <0x7fcc7e11f250> (

);
	latitude = 43.0418863;
	longitude = -87.9050517;
	isNew = 0;
	isInServingMode = 0;
}
```

As you can see, the keywords RLMArray is empty. I'm not sure where these 3 RStrings went. If they just aren't printing out thats fine. However, sometimes the following println, (the one starting with `tdo - `) crashes the app because `truck.keywords` is nil. In the debugger it says the backing array for the RLMArray is nil. Very strange behavior. So if I take out that println that sometimes crashes, it `never` enters the for loop. Perhaps I need to do some more casting here? Either way, I can't really figure it out. I've tried a lot so far. Any pointers?

**Comment by jault3** [comment] 2015-01-14 07:42
Using the realm browser I can see that the keywords `are` in the RString table, but looking in the RTruck table, they `are not` linked to the trucks at all. Hope that helps us figure out what I'm doing wrong

**Comment by jault3** [comment] 2015-01-14 08:29
@jpsim Alright, after further inspection it seems something goes wrong when I call the `createOrUpdateInRealm` method. So in  my very first comment on this issue, I had a line of code like this 

```
RTruck.createOrUpdateInRealm(realm, withObject: rtruck!)
```

After all the updates and whatever else I've done so far that line is the same. But directly before that line I am printing out the truck description and again directly after. Here is what it looks like

```
println("saving ->> \(rtruck!.description)")
RTruck.createOrUpdateInRealm(realm, withObject: rtruck!)
println("just saved ->> \(rtruck!.description)")
```

And here is the output

```
saving ->> RTruck {
	id = 5da1bcd7-8e41-47d2-8792-5da60c6efd85;
	name = Wicked Awesome Grill;
	imageUrl = https://google.com;
	keywords = RLMArray <0x7f9e101c8aa0> (
	[0] RKeyword {
		value = Wicked;
	},
	[1] RKeyword {
		value = Awesome;
	},
	[2] RKeyword {
		value = Grill;
	}
);
	latitude = 43.0418863;
	longitude = -87.9050517;
	isNew = 0;
	isInServingMode = 0;
}
just saved ->> RTruck {
	id = 5da1bcd7-8e41-47d2-8792-5da60c6efd85;
	name = Wicked Awesome Grill;
	imageUrl = https://google.com;
	keywords = RLMArray <0x7f9e101b8530> (

);
	latitude = 43.0418863;
	longitude = -87.9050517;
	isNew = 0;
	isInServingMode = 0;
}
```

Not sure what happens to the keywords in that method but they do have different memory addresses before and after. I figured I would do a lot of debugging and give you everything I know! :)

**Comment by jpsim** [comment] 2015-01-14 19:00
Ok, let's see if I can catch up.

> `join(", ", myRLMArrayInstance)`

This doesn't work, not because `RLMArray` doesn't conform to SequenceType, but rather because `RLMObject`s can't be joined by a string.

> So to get around that, I figured I would loop through the items in my RLMArray instance and add them to my own array and do the join that way.

There's no other way, really. Even `RLMArray` supported `map`, it would still just loop and append in there.

Finally, we get to your last comment. `rtruck`'s description should be identical before and after a `createOrUpdate` since it has a primary key, and therefore should never create a duplicate object.

I'll look into creating a reproducible case on my side so I can identify what's happening here. I'll keep you posted.

**Comment by jpsim** [comment] 2015-01-15 03:26
I haven't been able to reproduce your issue, @jault3. If you change the `RTruck.createOrUpdateInRealm(realm, withObject: rtruck)` line from [my last code sample](https://github.com/realm/realm-cocoa/issues/1322#issuecomment-69644446) to this:

```swift
rtruck.keywords.addObject(RString(object: ["\(rtruck.id)"]))
println("will save \(rtruck.description)")
RTruck.createOrUpdateInRealm(realm, withObject: rtruck)
println("did save \(rtruck.description)")
```

this is printed out:

```
will save RTruck {
	id = 1;
	name = ;
	imageUrl = ;
	keywords = RLMArray <0x7f8733c87c90> (
	[0] RString {
		value = 1;
	}
);
	latitude = 0;
	longitude = 0;
	isNew = 0;
	isInServingMode = 0;
}
did save RTruck {
	id = 1;
	name = ;
	imageUrl = ;
	keywords = RLMArray <0x7f8733c87c90> (
	[0] RString {
		value = 1;
	}
);
	latitude = 0;
	longitude = 0;
	isNew = 0;
	isInServingMode = 0;
}
will save RTruck {
	id = 2;
	name = ;
	imageUrl = ;
	keywords = RLMArray <0x7f8733de6840> (
	[0] RString {
		value = 2;
	}
);
	latitude = 0;
	longitude = 0;
	isNew = 0;
	isInServingMode = 0;
}
did save RTruck {
	id = 2;
	name = ;
	imageUrl = ;
	keywords = RLMArray <0x7f8733de6840> (
	[0] RString {
		value = 2;
	}
);
	latitude = 0;
	longitude = 0;
	isNew = 0;
	isInServingMode = 0;
}
```

Could you provide me with a code sample that I can run to reproduce the issue?

**Comment by jpsim** [comment] 2015-01-19 18:21
Hi @jault3, we haven't heard back from you in a few days. Are you still having issues with this?

**Comment by jault3** [comment] 2015-01-19 23:32
Sorry about this @jpsim. Had a few crazy busy days. But in terms of what you can use to reproduce it, our application is open sourced. Here is the repo with a direct link to the branch you can use https://github.com/TruckMuncher/TruckMuncher-iOS/tree/realm. It is on the `realm` branch. You should be able to clone the repo, run the app, and read the logs and see the issue I'm having. The file where the print lines are coming from is TruckMuncher/api/TrucksManager.swift https://github.com/TruckMuncher/TruckMuncher-iOS/blob/realm/TruckMuncher/api/TrucksManager.swift. Let me know if you need anything else from me! Again, sorry for the delay.

**Comment by jault3** [comment] 2015-01-19 23:33
Oops, forgot to say where exactly in that file you should pay attention to. That would be lines 46 - 48. In the `getActiveTrucks` method. You should see the print lines.

**Comment by jpsim** [comment] 2015-01-20 00:08
@jault3 ok, so I've built the project and ran it. These are the logs:

```
2015-01-19 16:03:44.012 TruckMuncher[28711:291227]  INFO: Reveal server started.
found token nil
Error Domain=kCLErrorDomain Code=0 "The operation couldn’t be completed. (kCLErrorDomain error 0.)"2015-01-19 16:03:49.053 TruckMuncher[28711:291227]  INFO: Reveal server started.
request <NSMutableURLRequest: 0x7fdfebb7d460> { URL: https://api.truckmuncher.com:8443/com.truckmuncher.api.menu.MenuService/getFullMenus }
response Optional(<NSHTTPURLResponse: 0x7fdfeba6efa0> { URL: https://api.truckmuncher.com:8443/com.truckmuncher.api.menu.MenuService/getFullMenus } { status code: 200, headers {
    "Cache-Control" = "no-cache, no-store, no-transform";
    "Content-Length" = 4980;
    "Content-Type" = "application/x-protobuf";
    Date = "Tue, 20 Jan 2015 00:03:54 GMT";
} })
successful request
found token nil
request <NSMutableURLRequest: 0x7fdfecec8ad0> { URL: https://api.truckmuncher.com:8443/com.truckmuncher.api.trucks.TruckService/getTruckProfiles }
response Optional(<NSHTTPURLResponse: 0x7fdfe8f224d0> { URL: https://api.truckmuncher.com:8443/com.truckmuncher.api.trucks.TruckService/getTruckProfiles } { status code: 200, headers {
    "Cache-Control" = "no-cache, no-store, no-transform";
    "Content-Length" = 663;
    "Content-Type" = "application/x-protobuf";
    Date = "Tue, 20 Jan 2015 00:03:56 GMT";
} })
successful request
```

What can I do to trigger the issue you're seeing?

**Comment by jault3** [comment] 2015-01-20 00:12
@jpsim did you check out the `realm` branch or are you on master? I'm not seeing the print lines I put in and those should be printed out without any user interaction in the application. All you should have to do is run the app.

**Comment by jpsim** [comment] 2015-01-20 00:16
Using the `realm` branch

**Comment by jpsim** [comment] 2015-01-20 00:23
Keep in mind that your `Properties.plist` file isn't checked in to git so I may not have correct API credentials.

**Comment by jault3** [comment] 2015-01-20 00:37
Ah, I forgot you cant check in default locations for simulators into VC. This might be because the simulator hasnt chosen a location or clicked allow when prompted to access the simulators location. Im investigating this now. Sorry, its hard to foresee these issues when you work on it everyday and have the environment setup :) and the plist file should be ok without having it

**Comment by jault3** [comment] 2015-01-20 01:44
@jpsim Here are the steps I took to reproduce the issue.

```
git clone https://github.com/TruckMuncher/TruckMuncher-iOS.git
cd TruckMuncher-iOS
git checkout realm
pod install
git submodule update --init
```

I then opened up `TruckMuncher.xcworkspace` and deleted the reference to Properties.plist to get it to compile for now. Then I clicked the Run button to launch the app. When the app opens in the simulator it asks for permission to access your location. I clicked `Allow`. Then while the simulator is running, in the menu/status bar I clicked `Debug`->`Location`->`Apple`. Then the important step, `I had to run the application again in Xcode`. Then my logs start by showing what you saw, and then multiple iterations of this:

```
SAVING TRUCK RTruck {
	id = 2d1dada3-80f1-4c0e-b878-a02626aafea7;
	name = Awesome Blossom;
	imageUrl = https://truck-images.s3.amazonaws.com/2d1dada3-80f1-4c0e-b878-a02626aafea7;
	keywords = RLMArray <0x7ff440821d00> (
	[0] RString {
		value = Awesome;
	},
	[1] RString {
		value = Blossom;
	}
);
	latitude = 43.05;
	longitude = -87.95;
	isNew = 0;
	isInServingMode = 0;
}
the truck we just saved was->> RTruck {
	id = 2d1dada3-80f1-4c0e-b878-a02626aafea7;
	name = Awesome Blossom;
	imageUrl = https://truck-images.s3.amazonaws.com/2d1dada3-80f1-4c0e-b878-a02626aafea7;
	keywords = RLMArray <0x7ff440887950> (

);
	latitude = 43.05;
	longitude = -87.95;
	isNew = 0;
	isInServingMode = 0;
}
```

I was able to reproduce what you were seeing (the absence of the logs that showed the issue) when the simulator did not have a location set) and I did not run the app for the second time after setting a location.

**Comment by jault3** [comment] 2015-01-22 23:28
hey @jpsim was just wondering if you had a chance to look at this yet?

**Comment by jpsim** [comment] 2015-01-22 23:28
Not yet, thanks for your patience. I'll let you know as soon as I do!

**Comment by jpsim** [comment] 2015-01-24 00:04
I got the app to run as expected in the `realm` branch (by running on device) and determined that this is the same issue as #1386, which is that createOrUpdate unlinks relationships in Swift. So I marked this as a bug and we'll get started on a fix soon.

**Comment by jpsim** [comment] 2015-01-24 01:24
Ah, so @jault3 turns out that your usage of Realm is actually incorrect (although we should share the blame since the `createOrUpdate` methods can be a bit misleading).

So in your code, when you update an `RLMObject` property value, you're done! You don't have to pass that modified object back into `createOrUpdate`. That method is more for passing in an `NSDictionary` or `NSArray` of updated values.

I really should have caught this as soon as you shared your code, but that shows that this method might benefit from a different name, though nothing comes to mind.

See #1409 for more details.

**Closed by jpsim** 2015-01-24 01:24 UTC
Labels: question

**Comment by jault3** [comment] 2015-01-26 16:17
So @jpsim is this still a bug and I am also using it incorrectly? Or is this just me incorrectly using realm and it is not a bug? I took a look at #1409 and that would be a great idea. An exception would be a nice reminder! 

I do have one question though. Let's take the situation where you make a network request, construct one of my RTruck objects, use the `createOrUpdate` method and it stores it perfect. Now that truck is stored and has a primary key with the `id`. What if the app is closed and later its opened again and data used to construct a brand new RTruck in memory was taken from the network and then passed to `createOrUpdate`? Even if its a brand new truck in memory, I can't use `createOrUpdate`?

**Comment by jpsim** [comment] 2015-01-26 21:55
@jault3 no this is not a bug. Yes you are using Realm incorrectly, though I understand the method name is misleading. Could you clarify your follow up question? I don't quite understand what you're asking. Maybe a code snippet would help.

**Comment by jault3** [comment] 2015-01-26 22:06
Ok, thanks for the clarifications, that does help a lot. And regarding my question, let's say I make a network request, and I get this JSON back from my server

```
{"id":"1234", "name":"Awesome Blossom","imageUrl":null, "keywords": ["Awesome", "Blossom"], "latitude": 0, "longitude": 0, "isNew": true, "isInServingMode":false}
```

I construct an RTruck object (my Realm backed class) from this JSON and use the `createOrUpdate` method to persist this to realm and everything works great. 

Now maybe the user closes the application. Some time passes and they open the application again. The same request is made to the server but this time I get back slightly different JSON.

```
{"id":"1234", "name":"Awesome Blossom","imageUrl":null, "keywords": ["Awesome", "Blossom"], "latitude": 43.05, "longitude": -87.95, "isNew": false, "isInServingMode":true}
```

Note that latitude, longitude, isNew, and isInServingMode have changed values. But the `id` is the same value. The `id` is the primary key for my RTruck class. I again construct an RTruck object from this JSON. How do I save this realm backed object? It has already been saved if you look at the database just by finding the `id` primary key. But this is a brand new object in memory. Do I use the `createOrUpdate` method? Or is realm smart enough to first look for an object with the primary key, and if it finds one, then it performs an update of the values within a write transaction?

**Comment by jault3** [comment] 2015-01-26 22:10
That may still be confusing, so here is a standalone coding example. It just seems kind of strange to me that with new objects you wouldn't have to call createOrUpdate.

```
import UIKit
import Realm

class RTruck: RLMObject {
    dynamic var id = ""
    dynamic var name = ""
    dynamic var imageUrl = ""

    override class func primaryKey() -> String! {
        return "id"
    }
}

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {

    var window: UIWindow?

    func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: NSDictionary?) -> Bool {

        self.window = UIWindow(frame: UIScreen.mainScreen().bounds)
        self.window!.rootViewController = UIViewController()
        self.window!.makeKeyAndVisible()

        NSFileManager.defaultManager().removeItemAtPath(RLMRealm.defaultRealmPath(), error: nil)

        let realm = RLMRealm.defaultRealm()
        realm.beginWriteTransaction()
        
        let rtruck = RTruck()
        rtruck.id = "1234"
        rtruck.name = "Awesome"
        rtruck.imageUrl = "http://google.com"
        RTruck.createOrUpdateInRealm(realm, withObject: rtruck)
        realm.commitWriteTransaction()


        // let's do it again, but construct a brand new object
        let realm2 = RLMRealm.defaultRealm()
        realm2.beginWriteTransaction()
        
        let rtruck2 = RTruck()
        rtruck2.id = "1234"
        rtruck2.name = "Awesome Blossom" // this has changed value from rtruck
        rtruck2.imageUrl = "http://github.com" // this has also changed value from rtruck
        RTruck.createOrUpdateInRealm(realm, withObject: rtruck) // is this correct? or is it not necessary?
        realm2.commitWriteTransaction()

        return true
    }
}
```

**Comment by jault3** [comment] 2015-01-26 23:19
You can ignore the example above. There is an `addOrUpdateObject` method on realm objects that I should have been using this whole time.

**Comment by jpsim** [comment] 2015-01-26 23:19
Ok, so are we good? Is there anything else lingering that we can help with?

**Comment by jault3** [comment] 2015-01-26 23:20
Nope, everything is solved. Thanks for all your help
