### ISSUE TITLE
 Weird version number 4539323416

### ISSUE THREAD

**Issue by csauvage** [realm/realm-cocoa#2015] opened 2015-05-27 16:15 UTC
I started a new project and, update 2 times my DB Scheme, since then I encountered this quite strange issue : 

`*** Terminating app due to uncaught exception 'RLMException', reason: 'Realm at path 'myPath.realm' has version number 4539323416 which is greater than the current schema version 0. You must call setSchemaVersion: or setDefaultRealmSchemaVersion: before accessing an upgraded Realm.'`

Any options to downgrade the version or solve this issue ? Thx

OS X 10.8, Lastest Realm, XCode v6.2 (6C131E)

**Comment by jpsim** [comment] 2015-05-27 16:26
The latest stable version of Realm (0.92.4) uses `NSUInteger` to represent schema versions (the next release will use `uint64_t`/`UInt64`). Is it possible that you, at some point, called `setSchemaVersion:` with a signed integer, which would have caused it to be interpreted as `4539323416`?

Downgrading your version of Realm would likely have no effect.

**Comment by csauvage** [comment] 2015-05-27 16:34
I meant is there a way to downgrade Realm Scheme Number ? To be honest I've called 
`[RLMRealm setSchemaVersion:2 forRealmAtPath:@"myPathToRealm.realm" withMigrationBlock:^(RLMMigration *migration, NSUInteger oldSchemaVersion){...}];`

Quite

**Comment by jpsim** [comment] 2015-05-27 16:37
No, schema versions have to be continuously increasing, so there's no way to set the schema version back to a lower value.

If that's in fact the code you used to set the version number, it would indicate a bug in Realm and we'd love to look further into it. Is there any chance you could share a sample project that reproduces this issue? e.g. the schema version being set to a different number than what you pass in?

**Comment by jpsim** [comment] 2015-06-24 18:19
Hi @csauvage, I'm just following up on my request for a repro case... it's really the best way to continue investigating what happened here.

**Comment by csauvage** [comment] 2015-06-24 18:21
Hi JP, 

I’m at ObjCGN for the moment, will send you that on monday (holy sh** I forget that when was on your offices...)

Best Regards,
-- 
Clément Sauvage
 iOS | OS X Developer

Lille Area, France

+33 6 78 77 13 12

Le 24 juin 2015 à 20:19:29, JP Simard (notifications@github.com) a écrit:

Hi @csauvage, I'm just following up on my request for a repro case... it's really the best way to continue investigating what happened here.

**Comment by jpsim** [comment] 2015-07-08 23:00
@csauvage could you send us a repro case, please?

**Comment by jpsim** [comment] 2015-07-21 17:08
Closing since we never heard back, but @csauvage please send us a repro case if you can ever create one. Thanks!

**Closed by jpsim** 2015-07-21 17:08 UTC
Labels: bug, pending
