### ISSUE TITLE
ld: symbol(s) not found for architecture x86_64

### ISSUE THREAD

**Issue by badeleux** [realm/realm-cocoa#3788] opened 2016-06-22 08:42 UTC
## Goals

I want to build a project

## Expected Results

I expect succesfull build.

## Actual Results

``` 
"realm::LinkListColumn::unregister_linkview(realm::LinkView const&)", referenced from:


      realm::LinkView::~LinkView() in libRealm.a(RLMArray.o)


      realm::LinkView::~LinkView() in libRealm.a(RLMArrayLinkView.o)


      realm::LinkView::~LinkView() in libRealm.a(RLMObjectBase.o)


      realm::LinkView::~LinkView() in libRealm.a(RLMMigration.o)


      realm::LinkView::~LinkView() in libRealm.a(RLMListBase.o)


      realm::LinkView::~LinkView() in libRealm.a(RLMObject.o)


      realm::LinkView::~LinkView() in libRealm.a(RLMResults.o)


      ...


  "realm::util::PlatformSpecificCondVar::PlatformSpecificCondVar()", referenced from:


      realm::SharedGroup::SharedGroup(realm::Replication&, realm::SharedGroup::DurabilityLevel, char const*, bool) in libRealm.a(shared_realm.o)


  "realm::util::PlatformSpecificCondVar::~PlatformSpecificCondVar()", referenced from:


      realm::SharedGroup::SharedGroup(realm::Replication&, realm::SharedGroup::DurabilityLevel, char const*, bool) in libRealm.a(shared_realm.o)


  "realm::Query::Query(realm::Table const&, realm::util::bind_ptr<realm::LinkView> const&)", referenced from:


      realm::Table::where(realm::util::bind_ptr<realm::LinkView> const&) in libRealm.a(RLMArrayLinkView.o)


  "realm::Table::set_datetime(unsigned long, unsigned long, realm::DateTime)", referenced from:


      realm::RowFuncs<realm::Table, realm::BasicRow<realm::Table> >::set_datetime(unsigned long, realm::DateTime) in libRealm.a(RLMAccessor.o)


      copy_property_values(realm::Property const&, realm::Property const&, realm::Table&) in libRealm.a(object_store.o)


  "realm::StringIndex::get(unsigned long, std::__1::array<char, 8ul>&) const", referenced from:


      void realm::StringIndex::set<realm::null>(unsigned long, realm::null) in libRealm.a(RLMArray.o)


      void realm::StringIndex::erase<realm::null>(unsigned long, bool) in libRealm.a(RLMArray.o)


      void realm::StringIndex::erase<realm::StringData>(unsigned long, bool) in libRealm.a(RLMArray.o)


      void realm::StringIndex::erase<long long>(unsigned long, bool) in libRealm.a(RLMArray.o)


      void realm::StringIndex::set<realm::null>(unsigned long, realm::null) in libRealm.a(RLMArrayLinkView.o)


      void realm::StringIndex::erase<realm::null>(unsigned long, bool) in libRealm.a(RLMArrayLinkView.o)


      void realm::StringIndex::erase<realm::StringData>(unsigned long, bool) in libRealm.a(RLMArrayLinkView.o)


      ...


  "realm::TableViewBase::maximum_datetime(unsigned long, unsigned long*) const", referenced from:


      auto realm::Results::max(unsigned long)::$_3::operator()<realm::TableView>(realm::TableView const&) const in libRealm.a(results.o)


  "realm::TableViewBase::minimum_datetime(unsigned long, unsigned long*) const", referenced from:


      auto realm::Results::min(unsigned long)::$_7::operator()<realm::TableView>(realm::TableView const&) const in libRealm.a(results.o)


  "realm::Table::get_datetime(unsigned long, unsigned long) const", referenced from:


      realm::RowFuncs<realm::Table, realm::BasicRow<realm::Table> >::get_datetime(unsigned long) const in libRealm.a(RLMAccessor.o)


      copy_property_values(realm::Property const&, realm::Property const&, realm::Table&) in libRealm.a(object_store.o)


  "realm::Table::maximum_datetime(unsigned long, unsigned long*) const", referenced from:


      auto realm::Results::max(unsigned long)::$_3::operator()<realm::Table>(realm::Table const&) const in libRealm.a(results.o)


  "realm::Table::minimum_datetime(unsigned long, unsigned long*) const", referenced from:


      auto realm::Results::min(unsigned long)::$_7::operator()<realm::Table>(realm::Table const&) const in libRealm.a(results.o)


ld: symbol(s) not found for architecture x86_64


clang: error: linker command failed with exit code 1 (use -v to see invocation) 
```

## Steps to Reproduce

I think the issue is related with [new cocoapods](http://stackoverflow.com/questions/37852822/realm-1-0-1-ios-obj-c-compilation-error)

## Version of Realm and Tooling

[In the CONTRIBUTING guidelines](https://git.io/vgxJO), you will find a script,
which will help determining these versions.

Realm version: 1.0.1

Xcode version: 7.3.1 (7D1014)

iOS/OSX version: 9.3

Dependency manager + version: cocoapods 1.0.1

**Comment by mrackwitz** [comment] 2016-06-28 13:18
Have you tried to clean the build folder and build again from scratch?

**Comment by mrackwitz** [comment] 2016-06-28 14:00
Okay, sorry for bothering with this question. After investigating #3763, this seems to be a duplicate of that specific to CocoaPods 1.0.1 when integrating with static libraries. As a workaround you could either use an older version of CocoaPods or declare `use_frameworks!` in your Podfile.

**Closed** 2016-06-28 14:00 UTC
Labels: T:Bug, T:Duplicate
