### ISSUE TITLE
RLMObject category init method not seen from Swift view controller

### ISSUE THREAD

**Issue by viktorasl** [realm/realm-cocoa#2416] opened 2015-08-19 07:52 UTC
Hello, I have a problem using category declared init method of RLMObject from Swift view controller. I have created a demo project (https://github.com/viktorasl/ObjcSwiftRealmModel) to demonstrate that. Mainly the steps are these:

* Swift: Model `SwiftModel: RLMObject`
* ObjC: Category `RLMObject+JSON` with `initWithJSONDictionary:` method
* Swift: `SwiftVC: UIViewController`
* `ObjcSwiftRealmModel-Bridging-Header` includes all required ObjC files

The problem: I cannot use `SwiftModel(JSONDictionary: [NSObject:AnyObject]())`

**Comment by kishikawakatsumi** [comment] 2015-08-20 07:54
I think it may be Swift compiler's bug because it reproduces without Realm like below:

```objc
@interface TestObj : NSObject
@end

@interface TestObj (test)
- (instancetype)initWithSomething:(NSObject *)obj;
- (void)test;
@end
```

```swift
class SwiftObj: TestObj {

}
```

```swift
let obj1 = TestObj() // OK
obj1.test() // OK

let obj2 = TestObj(something: nil) // OK
obj2.test() // OK

let sobj1 = SwiftObj() // OK
sobj1.test() // OK

let sobj2 = SwiftObj(something: nil) // NG
```

Further investigation with `type lookup`, it does not seem anything wrong.

```
(lldb) type lookup TestObj
@objc class TestObj : ObjectiveC.NSObject {
  @objc deinit  {
  }
  @objc init()
}
extension TestObj {
  @objc init!(something obj: ObjectiveC.NSObject!)
  @objc func test()
}
(lldb) type lookup SwiftObj
@objc class SwiftObj : __ObjC.TestObj {
  @objc deinit 
  @objc @objc init()
}
```

**Comment by kishikawakatsumi** [comment] 2015-08-20 10:09
By Further investigation, it might not be the compiler bug. It is fixed by adding `NS_DESIGNATED_INITIALIZER` to `init`, like below: 

```
@interface TestObj : NSObject
- (instancetype)init NS_DESIGNATED_INITIALIZER;
@end
```

It makes results of `type lookup` to:

```
(lldb) type lookup TestObj
@objc class TestObj : ObjectiveC.NSObject {
  @objc deinit  {
  }
  @objc init!()
}
extension TestObj {
  @objc convenience init!(something obj: ObjectiveC.NSObject!)
  @objc func test()
}
(lldb) type lookup SwiftObj
@objc class SwiftObj : __ObjC.TestObj {
  @objc deinit 
  @objc @objc init!()
}
(lldb) 
```

**Closed** 2015-08-20 20:46 UTC
