### ISSUE TITLE
Realm for Swift 3.1 - Command failed due to signal: Illegal instruction: 4

### ISSUE THREAD

**Issue by linhcn** [realm/realm-cocoa#4841] opened 2017-04-09 04:47 UTC
## Goals
Running Realm on Swift 3.1

## Expected Results
No error related to Realm

## Actual Results

`Module compiled with Swift 3.0.2 cannot be imported in Swift 3.1: RealmSwift.framework`

After I updated the project with Realm for Swift 3.1 downloaded from [here](https://realm.io/docs/swift/latest/), got this issue `Command failed due to signal: Illegal instruction: 4` in all model files using Realm

Tried removing the frameworks and using CocoaPods instead, but the issues persist.

## Error Description
`CompileSwift normal x86_64 /Users/linhcn/Documents/XcodeProjects/HerdManager/HerdManager/Models/ActionCategory.swift -target x86_64-apple-ios9.3 -enable-objc-interop -sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.3.sdk -I /Users/linhcn/Library/Developer/Xcode/DerivedData/HerdManager-exytfaymknfhzqabpximiccdzmaa/Build/Products/Debug-iphonesimulator -F /Users/linhcn/Library/Developer/Xcode/DerivedData/HerdManager-exytfaymknfhzqabpximiccdzmaa/Build/Products/Debug-iphonesimulator -F /Users/linhcn/Library/Developer/Xcode/DerivedData/HerdManager-exytfaymknfhzqabpximiccdzmaa/Build/Products/Debug-iphonesimulator/FileBrowser -F /Users/linhcn/Library/Developer/Xcode/DerivedData/HerdManager-exytfaymknfhzqabpximiccdzmaa/Build/Products/Debug-iphonesimulator/Realm -F /Users/linhcn/Library/Developer/Xcode/DerivedData/HerdManager-exytfaymknfhzqabpximiccdzmaa/Build/Products/Debug-iphonesimulator/RealmSwift -F /Users/linhcn/Library/Developer/Xcode/DerivedData/HerdManager-exytfaymknfhzqabpximiccdzmaa/Build/Products/Debug-iphonesimulator/Toast-Swift -F /Users/linhcn/Documents/XcodeProjects/HerdManager/HerdManager/Frameworks -enable-testing -g -module-cache-path /Users/linhcn/Library/Developer/Xcode/DerivedData/ModuleCache -D DEBUG -D COCOAPODS -serialize-debugging-options -Xcc -I/Users/linhcn/Library/Developer/Xcode/DerivedData/HerdManager-exytfaymknfhzqabpximiccdzmaa/Build/Intermediates/HerdManager.build/Debug-iphonesimulator/HerdManager.build/swift-overrides.hmap -Xcc -iquote -Xcc /Users/linhcn/Library/Developer/Xcode/DerivedData/HerdManager-exytfaymknfhzqabpximiccdzmaa/Build/Intermediates/HerdManager.build/Debug-iphonesimulator/HerdManager.build/HerdManager-generated-files.hmap -Xcc -I/Users/linhcn/Library/Developer/Xcode/DerivedData/HerdManager-exytfaymknfhzqabpximiccdzmaa/Build/Intermediates/HerdManager.build/Debug-iphonesimulator/HerdManager.build/HerdManager-own-target-headers.hmap -Xcc -I/Users/linhcn/Library/Developer/Xcode/DerivedData/HerdManager-exytfaymknfhzqabpximiccdzmaa/Build/Intermediates/HerdManager.build/Debug-iphonesimulator/HerdManager.build/HerdManager-all-non-framework-target-headers.hmap -Xcc -ivfsoverlay -Xcc /Users/linhcn/Library/Developer/Xcode/DerivedData/HerdManager-exytfaymknfhzqabpximiccdzmaa/Build/Intermediates/HerdManager.build/all-product-headers.yaml -Xcc -iquote -Xcc /Users/linhcn/Library/Developer/Xcode/DerivedData/HerdManager-exytfaymknfhzqabpximiccdzmaa/Build/Intermediates/HerdManager.build/Debug-iphonesimulator/HerdManager.build/HerdManager-project-headers.hmap -Xcc -I/Users/linhcn/Library/Developer/Xcode/DerivedData/HerdManager-exytfaymknfhzqabpximiccdzmaa/Build/Products/Debug-iphonesimulator/include -Xcc -I/Users/linhcn/Library/Developer/Xcode/DerivedData/HerdManager-exytfaymknfhzqabpximiccdzmaa/Build/Intermediates/HerdManager.build/Debug-iphonesimulator/HerdManager.build/DerivedSources/x86_64 -Xcc -I/Users/linhcn/Library/Developer/Xcode/DerivedData/HerdManager-exytfaymknfhzqabpximiccdzmaa/Build/Intermediates/HerdManager.build/Debug-iphonesimulator/HerdManager.build/DerivedSources -Xcc -DDEBUG=1 -Xcc -DCOCOAPODS=1 -Xcc -working-directory/Users/linhcn/Documents/XcodeProjects/HerdManager -emit-module-doc-path /Users/linhcn/Library/Developer/Xcode/DerivedData/HerdManager-exytfaymknfhzqabpximiccdzmaa/Build/Intermediates/HerdManager.build/Debug-iphonesimulator/HerdManager.build/Objects-normal/x86_64/Invoice~partial.swiftdoc -serialize-diagnostics-path /Users/linhcn/Library/Developer/Xcode/DerivedData/HerdManager-exytfaymknfhzqabpximiccdzmaa/Build/Intermediates/HerdManager.build/Debug-iphonesimulator/HerdManager.build/Objects-normal/x86_64/Invoice.dia -Onone -module-name HerdManager -emit-module-path /Users/linhcn/Library/Developer/Xcode/DerivedData/HerdManager-exytfaymknfhzqabpximiccdzmaa/Build/Intermediates/HerdManager.build/Debug-iphonesimulator/HerdManager.build/Objects-normal/x86_64/Invoice~partial.swiftmodule -emit-dependencies-path /Users/linhcn/Library/Developer/Xcode/DerivedData/HerdManager-exytfaymknfhzqabpximiccdzmaa/Build/Intermediates/HerdManager.build/Debug-iphonesimulator/HerdManager.build/Objects-normal/x86_64/Invoice.d -emit-reference-dependencies-path /Users/linhcn/Library/Developer/Xcode/DerivedData/HerdManager-exytfaymknfhzqabpximiccdzmaa/Build/Intermediates/HerdManager.build/Debug-iphonesimulator/HerdManager.build/Objects-normal/x86_64/Invoice.swiftdeps -o /Users/linhcn/Library/Developer/Xcode/DerivedData/HerdManager-exytfaymknfhzqabpximiccdzmaa/Build/Intermediates/HerdManager.build/Debug-iphonesimulator/HerdManager.build/Objects-normal/x86_64/Invoice.o`

Realm framework version: 2.5.1

Realm Object Server version: ?

Xcode version: 8.1

iOS/OSX version: 9.3

**Comment by istx25** [comment] 2017-04-12 18:00
Hi @linhcn. Thanks for reporting this issue. I would recommend [deleting your derived data](http://stackoverflow.com/questions/38016143/how-to-delete-derived-data-in-xcode-8) as well as [clearing the CocoaPods cache](https://gist.github.com/mbinna/4202236). Please let us know if the issue persists and I'll escalate to one of the engineers.

**Comment by linhcn** [comment] 2017-04-12 23:53
Thanks. I did those two before raising the issue. None of them works.

**Comment by istx25** [comment] 2017-04-13 00:54
Can you share the contents of your `Podfile` and `Podfile.lock` with us?

**Comment by linhcn** [comment] 2017-04-13 01:03
I don't use `cocoaPod` for integrating Realm. I manually added the frameworks in by following the steps in this [article](https://realm.io/docs/swift/latest/). 

Having this issue after updating Xcode to 8.3.1. I did tried using cocoaPod to see if it works, but the it didn't.

**Comment by TimOliver** [comment] 2017-04-14 00:55
Hi @linhcn! Just to remove all doubt that it's not a build cache issue, can you please try creating a separate app project from scratch and try importing Realm into that one? If the problem still persists in that one, could you please send it to us? :)

**Comment by din** [comment] 2017-04-18 01:50
We've had the similar issue with my project for quite a while so we decided to stay on Xcode 8.2.1 instead. Xcode 8.3.1 plus realm makes it impossible to compile with the aforementioned error. 

As far as I can tell from the manual debugging, it's something related to the enumeration of collections provided by RealmSwift, but cannot tell for sure. 

I also cannot send my project because it's too big, but on a smaller project this couldn't be replicated.

**Comment by TimOliver** [comment] 2017-04-19 23:20
Sorry to hear you've been encountering the same issue @din!

I did a little more research into `Command failed due to signal: illegal instruction: 4` to see what I could find. 

It turns out it's a Swift compile error, and according to the Apple Developer Forums, it seems to be quite prevalent when migrating Swift code to new versions.

There are two issues on the forums in which users were able to solve the problem. 

https://forums.developer.apple.com/message/20702
https://forums.developer.apple.com/message/40254

Apparently there should be enough debug information along the message to work out the portion of Swift code causing the illegal instruction, and you should be able to fix it there.

Staying on Xcode 8.2 might mitigate the problem for now, but since Apple may choose to stop allowing app submissions from specific older versions of Xcode in the future, I'd recommend you continue exploring the cause of the problem.

In any case, the `illegal instruction` error doesn't seem to be an issue with Realm Swift on its own; so there's nothing we can do on our end to fix this.

I'm going to close this issue. I recommend reviewing those Apple Forum threads and trying to refactor your code. If you can replicate the issue in a project small enough to share here, please feel free to reopen the issue. :)

**Closed by TimOliver** 2017-04-19 23:20 UTC
Labels: T:Help
