### ISSUE TITLE
Realm cannot recognize/include classes in Test target when initialized too soon

### ISSUE THREAD

**Issue by tom-sparo** [realm/realm-cocoa#3165] opened 2016-02-01 23:28 UTC
I'm tracking down a weird bug... it seems to me that when a Realm gets initialized too early, it doesn't reupdate with new schemas that are included later.

So here's an example setup:

### In TestBug folder
`AppDelegate.swift`
```swift
import UIKit
import RealmSwift

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {

    var window: UIWindow?

    func application(application: UIApplication, willFinishLaunchingWithOptions launchOptions: [NSObject : AnyObject]?) -> Bool {
        // Offending line of code
        _ = try! Realm()
        return true
    }

}
```

`BaseModel.swift`
```swift
import RealmSwift

class BaseModel: Object {
}
```

### In TestBugUnitTest folder

`TestModel.swift`
```swift
import UIKit
import RealmSwift
@testable import TestBug

class TestModel: BaseModel {
    dynamic var someProperty: String = ""
}
```

`TestBugTests.swift`
```swift
import XCTest
import RealmSwift

class TestRealmSyncTests: XCTestCase {
    override func setUp() {
        super.setUp()
        Realm.Configuration.defaultConfiguration.inMemoryIdentifier = self.name
    }
    
    func testExample() {
        let realm = try! Realm()
        let testObject = TestModel()
        testObject.someProperty = "test" // Throws error: failed: caught "NSInvalidArgumentException", "-[RLMStandalone_BaseModel setSomeProperty:]: unrecognized selector sent to instance 0x7ff2d84dce50"
    }
}
```

And it looks to me that what's causing this is something to do with the way object schemas are created.  When a Realm is first created too early, even if later we change the default configuration, those schemas are not reloaded.  So here when the realm is first created in the AppDelegate, none of the test files are included in the objc calls.  That's bad because then when we go to create a new Realm object with a class that has its declaration in the test target, Realm has no idea what we're talking about and just resorts to using the base class.  And we get a different error if we try something simila rwithout the base class: `-[TestRealmSyncTests.TestRealmSyncTests testExample] : failed: caught "RLMException", "Object type 'TestModel' not persisted in Realm"`.  So it's definitely a schema issue.

As to workarounds, I really do need to instantiate Realm that early because I would like to have that persisted information around for restoration (happens between willLaunch and didLaunch).  So I suppose the best workaround is to just declare any and all Realm objects in the main target?

Bug fixes on your end are to reload in schemas after realm changes?  I expected changing the inMemoryIdentifier would reload the schemas, but apparently it doesn't.  I'm not sure exactly the timing on when and how schemas get read in from files.

What do you all think?

**Comment by jpsim** [comment] 2016-02-02 00:10
At first glance, this seems like it may be a legitimate issue, but this will need further investigation to confirm that it's a bug and to identify why this is happening.

In any case, thanks for reporting this!

**Comment by tgoyne** [comment] 2016-02-02 00:11
The problem is that Realm only scans the list of obj-c classes once (since it's a fairly expensive operation), so any classes defined in bundles loaded after that are never registered with Realm. `application:willFinishLaunchingWithOptions:` is called before your test bundle is injected into the process, so any classes defined in the test target haven't been loaded yet.

You probably don't actually want to be doing your normal willLaunch/didLaunch things when running tests, so one simple solution would be to [set and environment variable for you test target, and skip doing anything if it's set](http://stackoverflow.com/questions/29464833/how-can-i-set-flags-that-my-app-will-see-when-its-running-under-xctest#answers).

**Comment by tom-sparo** [comment] 2016-02-02 00:18
That works for me @tgoyne, although I wish there was a way to directly add Realm classes to the Schema at runtime because while I agree that scan operation is way too costly to run each time a new file could appear in the bundles, the user should be able to override this behavior and add files they know  are Realm files.

And the env var is a good option if there's no way to add schema files manually, but I try to keep as much testing code checks out of the main code as possible.

**Comment by bigfish24** [comment] 2016-02-15 22:22
@tom-sparo (cc @jpsim, @tgoyne) can we close this issue?

**Closed** 2016-02-15 22:23 UTC
Labels: T:Help

**Comment by jpsim** [comment] 2016-02-15 22:29
Yeah, it's ok to close this one. Although we'll probably end up improving this situation when building #938 or #2459.
