### ISSUE TITLE
Support Swift 2

### ISSUE THREAD

**Issue by grimabe** [realm/realm-cocoa#2062] opened 2015-06-09 08:36 UTC
I know that Swift 2 has just been published but for future compatibility it will be great to fix it.

I'm using cocoa pod with Realm (0.93.1) RealmSwift (0.93.1)

![screen shot 2015-06-09 at 10 30 38](https://cloud.githubusercontent.com/assets/1334148/8053693/5b5c0060-0e93-11e5-9294-bcc54e358760.png)

**Comment by voidref** [comment] 2015-06-09 17:57
If anyone else is trying a recompile under Xcode 7, I suggest not going with the automatic syntax update, it appears to cause a number of problems that are likely easier to sort out when you know the design intent of the code flow. This seems especially prevalent around the new exception handling.

**Comment by jpsim** [comment] 2015-06-09 18:50
Thanks for filing this, we're of course working on it and will attempt to have a branch and PR up as soon as possible so you can at least continue testing your apps with Swift 2.

**Comment by grimabe** [comment] 2015-06-09 20:05
@voidref even if your are not using automatic syntax conversion compilation will still failed. But doesn't matter I'll be waiting for fixed.
@jpsim thanks for that

**Comment by neonichu** [comment] 2015-06-10 04:58
👍

**Comment by tgoyne** [comment] 2015-06-11 00:45
Preliminary support for Swift 2.0 can be found at https://github.com/realm/realm-cocoa/pull/2069. This compiles and passes all tests, but has not been tested extensively.

**Comment by voidref** [comment] 2015-06-11 06:10
This is great! You guys are awesome!

 ... but, umm, is there a script somewhere to build the swift-for-ios package correctly?

I tried `./build.sh ios-swift` to no avail, and the `github_release.rb` isn't doing the trick either. The RealmSwift.framework isn't getting it's Realm.framework embedded in any of these builds.

Ok, putting it in there manually seems to work out, but am getting a compiler crash.

Of course, the compiler *shouldn't* be crashing, but I am unsure if this is perhaps being caused by a misconfiguration with the embedded realm framework.

So ... shouldn't there be a script that bundles the RealmSwift.framework somewhere in here?

Thanks!

**Comment by voidref** [comment] 2015-06-11 06:13
Also, it's asking me to do a try ... catch for ANY realm accesses now. I don't think exceptions were supposed to be used quite so extensively. Optionals are still a thing. =)

**Comment by voidref** [comment] 2015-06-11 06:28
Ok, I see why you might want to catch those init exceptions in some cases, but using the default Realm() init shouldn't have any recoverable runtime errors.

Perhaps instead of a default value for the path, consider splitting out the path taking init and the no-args taking one?

The current solution results in `try! Realm().thing` being a ubiquitous sight.

**Comment by voidref** [comment] 2015-06-11 06:35
I do want to say, thank you, again for being so responsive on this update. 

I hope I do not sound unappreciative and demanding in my comments.

**Comment by bdash** [comment] 2015-06-11 06:48
Since [Realm Swift 0.9.3](https://realm.io/news/realm-objc-swift-0.93/) we're no longer packaging Realm.framework inside RealmSwift.framework. It should now be installed alongside RealmSwift.framework.

**Comment by voidref** [comment] 2015-06-11 07:43
Ah, thanks!

**Comment by MarcoSero** [comment] 2015-06-11 08:23
Thank you Realm team to start working on this immediately.

Just a heads up: as @voidref said, installing the swift-2.0 branch (with Carthage in my case) does not create the RealmSwift.framework in the build folders.
I had to manually run `./build.sh ios-swift`.

**Comment by MarcoSero** [comment] 2015-06-11 13:43
Unfortunately though, the framework generated by running `./build.sh ios-swift` doesn't have a correct bundle identifier and running the app results in a Xcode error:
```
The operation couldn’t be completed. (LaunchServicesError error 0.)
```
with the simulator logging:

```
RealmSwift.framework did not have a CFBundleIdentifier in its Info.plist
```

**Comment by tgoyne** [comment] 2015-06-11 14:50
I'm really not a fan of having to do `try! Realm()` everywhere. It's ugly, and most of the calls to `Realm()` legitimately cannot fail for any reason (if there's already a cached realm for the current thread, there simply aren't any error paths), but that's not something that can be expressed in the type system, and you can't overload functions on `throws`.

There's a few options that have come to mind so far:
 
1. Add overloads which return `Realm?` and just return `nil` on error, making the "shut up I know this can't fail" code `Realm()!.write { ... }`.
2. Ask for overloading on `throws` and have it actually be added. I doubt this will happen.
3. Tell everyone to always just use `let realm = try! Realm()`, and discover that in most cases that's totally fine.
4. Tell people to use a trivial wrapper function around `try! Realm()` (but if we're telling people to copy and paste a function, shouldn't that function just be included?).
5. Make `Realm()` abort on error, and only the overloads with arguments `throws` (including just `Realm(path: myPath)`.

**Comment by marchyman** [comment] 2015-06-11 16:04
Opinion...

> 
> 	• Add overloads which return Realm? and just return nil on error, making the "shut up I know this can't fail" code Realm()!.write { ... }.

As ugly as try! Realm()

> 	• Ask for overloading on throws and have it actually be added. I doubt this will happen.

Heh.

> 	• Tell everyone to always just use let realm = try! Realm(), and discover that in most cases that's totally fine.

Telling people to ignore error handling because in most cases that's totally
fine does not seem like a good idea.

> 	• Tell people to use a trivial wrapper function around try! Realm() (but if we're telling people to copy and paste a function, shouldn't that function just be included?).

Realm() should be that function

> 	• Make Realm() abort on error, and only the overloads with arguments throws (including just Realm(path: myPath).


Yup.  If I can’t live with an abort I can pass in the default path.

**Comment by tgoyne** [comment] 2015-06-11 18:24
@MarcoSero That's now fixed, and the samples work in the simulator and on device.

**Comment by voidref** [comment] 2015-06-11 19:01
As a consumer of the API, I would prefer the latter solution. The implementation seems like it would be trivial as well:

    public convenience init() {
        try! return self.init(path: Realm.defaultPath)
    }

**Comment by jpsim** [comment] 2015-06-11 19:17
Oh, the implementation isn't the difficult part... it's figuring out what we want to encourage & enable users to do that's hard :smile: 

I have to think about this some more, but my current preference is to go from these initializers:

```swift
public convenience init(path: String = Realm.defaultPath) throws
public convenience init(path: String, readOnly: Bool, encryptionKey: NSData? = nil) throws
public convenience init(inMemoryIdentifier: String)
```

to these:

```swift
public convenience init(path: String = Realm.defaultPath, readOnly: Bool = false, encryptionKey: NSData? = nil) throws
public convenience init(inMemoryIdentifier: String)
```

Which would always require the user to think about whether or not the Realm initialization *can* fail, and they'd have to explicitly `try!` to ignore errors. This means there will be times when it's appropriate to use `try!` and there may be an educational challenge here for users, but I'd argue it's important for Realm users to know this.

As for being ugly, it'd be nice if Swift had a bit of semantic sugar for force trying functions and initializers (`try! Realm()` -> `Realm!()`) which would cut down on the verbosity a bit. I'd also encourage the use of local variables when accessing the same Realm many times in a given scope.

**Comment by voidref** [comment] 2015-06-11 19:56
What is the scenario you see for being able to recover from failing to initialize the default realm?

I fear we may end up with 'exception fatigue' for the API, where anytime someone sees a `throws` they will just reflexively prepend a `try!` without thinking about it.

**Comment by jpsim** [comment] 2015-06-11 19:59
There are a number of recoverable errors that can occur when constructing a Realm: https://github.com/realm/realm-cocoa/blob/v0.93.1/Realm/RLMRealm.mm#L210-L242

I definitely agree that there will be some exception fatigue, but at least users will be aware of it, rather than doing `try!` implicitly for them.

**Comment by voidref** [comment] 2015-06-11 20:27
I'm not sure I understand, how would one recover at runtime from any of those when creating the *default* Realm? There should definitely be examples of this in the documentation!

**Comment by jpsim** [comment] 2015-06-29 19:18
Hi everyone, we'll be maintaining a `swift-2.0` branch for a bit, which you can also see as a PR here: #2069.

We may decide at some point to merge that branch into `master` in a separate folder next to `RealmSwift` to maintain support for both Swift 1.2 and 2.0beta simultaneously, at which point we'd update #2069 with that information.

So I'm closing this issue since this work is complete. Installation instructions to use that branch are detailed in the aforementioned PR.

**Closed by jpsim** 2015-06-29 19:18 UTC
Labels: enhancement
