### ISSUE TITLE
Notification Block Not Called On Large RLMResults

### ISSUE THREAD

**Issue by LeffelMania** [realm/realm-cocoa#4292] opened 2016-11-03 19:08 UTC
## Goals

Implement infinite scrolling in a table to progressively load more objects from our server into our Realm database to populate the table.

## Expected Results

We reach the end of the table, fire an API request, new Realm objects are created, and we receive a notification that our observed RLMResults object has changed so we can update the table. This happens continuously, fetching more and more results that populate the table.

## Actual Results

Our first request brings in 10 objects that are displayed in the table. Each subsequent request brings in 20 more to display. 

As we scroll, we successfully bring in up to 130 objects into our table. On the next scroll, 20 more objects are returned from our API, 20 more objects are present in our RLMResults object, but we receive no notification that those insertions took place, and our table doesn't update.

If we scroll again, 20 more objects are created and we _do_ get a change notification with those 20 insertions, but now the size of our RLMResults has grown by 40 objects since our last update. This isn't reflected in the change set, and so we hit an internal inconsistency exception trying to update our table.

We've worked around this by detecting that inconsistency and fully reloading our table view when it happens, but once the results grow to ~150 objects, we start getting notified only every other time the insertions take place.

## Steps to Reproduce

[Hypothetical] Set up some kind of infinitely scrolling table view that triggers an asynchronous load of new objects that your table is displaying. Set a breakpoint in the results change notification callback. Continue scrolling until there are more than 150 objects. Notice breakpoint isn't hit every time new objects are loaded.

## Code Sample

This is what we're using to load our tables with Realm objects, and where I've put a print statement to show how many objects are in our results as our API requests come back. `handleChange` does the normal insert/update/delete of rows based on the change set. As described above, that block isn't called in response to new objects being created when we get to 150 objects.

```
func startLoading(tableView: UITableView) {
    
    if let token = self.token {
        token.stop()
        self.token = nil
    }
    
    self.tableView = tableView
    
    self.token = self.results.addNotificationBlock({ [weak self] (results, change, error) in
        let count = results?.count ?? 0
        print("*** Loader \(self?.label) has \(count) objects")
        self?.handleChange(change)
    })
}
```

## Version of Realm and Tooling

```
ProductName:	Mac OS X
ProductVersion:	10.12.1
BuildVersion:	16B2555

/Applications/Xcode.app/Contents/Developer
Xcode 8.1
Build version 8B62

/Users/alexleffelman/.rbenv/shims/pod
1.0.1
Realm (2.0.3)

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)

/usr/local/bin/carthage
0.15.2
(not in use here)

/usr/bin/git
git version 2.9.3 (Apple Git-75)
```

**Comment by jpsim** [comment] 2016-11-08 19:26
Have you tried this with the `tg/changeset-skip` branch? We've fixed some issues regarding changeset notifications in there that may resolve this issue.

**Comment by jpsim** [comment] 2016-11-08 19:27
This could be a duplicate of #4186.

**Comment by LeffelMania** [comment] 2016-11-08 19:40
I have not; I'll try that today or tomorrow and report back. That ticket does look like pretty much our exact scenario, so I can monitor that one if you want to close this one.

**Comment by jpsim** [comment] 2016-11-08 20:05
Although I can't say for sure that this issue is _identical_ to #4186, it seems likely, so let's close this as a duplicate unless we can confirm that they're separate issues.

**Closed by jpsim** 2016-11-08 20:05 UTC
Labels: T:Help
