### ISSUE TITLE
Realm crash: terminating with uncaught exception of type realm::KeyNotFound: No such object

### ISSUE THREAD

**Issue by anton-plebanovich** [realm/realm-cocoa#7198] opened 2021-04-03 02:24 UTC
## Goals
I want my app to work without crashes

## Expected Results
I expected my app to not crash

## Actual Results

```
Thread 10#0	0x00007fff6112f766 in kevent ()
#1	0x000000010423bcb9 in realm::util::network::Service::IoReactor::wait_and_activate(std::__1::chrono::time_point<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >, std::__1::chrono::time_point<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >) ()
#2	0x000000010423c342 in realm::util::network::Service::IoReactor::wait_and_advance(std::__1::chrono::time_point<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >, std::__1::chrono::time_point<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >, bool&, realm::util::network::Service::OperQueue<realm::util::network::Service::AsyncOper>&) ()
#3	0x000000010423cc95 in realm::util::network::Service::Impl::run() ()
#4	0x00000001041b331d in realm::sync::Client::run() ()
#5	0x000000010434ba4d in void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, realm::_impl::SyncClient::SyncClient(std::__1::unique_ptr<realm::util::Logger, std::__1::default_delete<realm::util::Logger> >, realm::SyncClientConfig const&, std::__1::shared_ptr<realm::SyncManager const>)::'lambda0'()> >(void*) ()
#6	0x00007fff61167109 in _pthread_start ()
#7	0x00007fff61162b8b in thread_start ()

Thread 11#0	0x00007fff6112d882 in __psynch_cvwait ()
#1	0x00007fff61167425 in _pthread_cond_wait ()
#2	0x000000010423fc52 in realm::util::network::Service::Impl::resolver_thread() ()
#3	0x000000010423fb2d in void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, realm::util::network::Service::Impl::add_resolve_oper(std::__1::unique_ptr<realm::util::network::Service::ResolveOperBase, realm::util::network::Service::LendersOperDeleter>)::'lambda'()> >(void*) ()
#4	0x00007fff61167109 in _pthread_start ()
#5	0x00007fff61162b8b in thread_start ()

Realm notification listener (12)#0	0x00007fff6112f766 in kevent ()
#1	0x0000000104246908 in realm::_impl::ExternalCommitHelper::listen() ()
#2	0x0000000104246a8e in void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0> >(void*) ()
#3	0x00007fff61167109 in _pthread_start ()
#4	0x00007fff61162b8b in thread_start ()

CRASH HERE ===> Realm notification listener (13)#0	0x00007fff6113133a in __pthread_kill ()
#1	0x00007fff61166e60 in pthread_kill ()
#2	0x00007fff200fab94 in abort ()
#3	0x00007fff20253818 in abort_message ()
#4	0x00007fff20244e65 in demangling_terminate_handler() ()
#5	0x00007fff201780d9 in _objc_terminate() ()
#6	0x00007fff20252c47 in std::__terminate(void (*)()) ()
#7	0x00007fff202555b6 in __cxa_rethrow ()
#8	0x0000000104246b38 in void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0> >(void*) ()
#9	0x00007fff61167109 in _pthread_start ()
#10	0x00007fff61162b8b in thread_start ()
```

Console:
```
uncaught exception in notifier thread: N5realm11KeyNotFoundE: No such object
libc++abi.dylib: terminating with uncaught exception of type realm::KeyNotFound: No such object
terminating with uncaught exception of type realm::KeyNotFound: No such object
```

## Steps for others to Reproduce
I have a pretty complex setup but I can provide all details if needed. The crash reproduces with 100% frequency. A brief explanation below.

I have 2 Mongo Atlas databases. The first for public data to which all users have access. The second for user data. Public data is lazily loaded from the network using an insert trigger for one of the user collections. The app listens for a user object in the user database and for a container object in the public database using separate Realms. 

The container object is always present and has relationships to all other public data and just aggregates this data. The app observes that object. Realm function adds leaf objects and so the container data became available when relationships are resolved. 

So what I got from logs is that when I add an object to the user database I receive an update about that, then Realm trigger calls function to update 3 different tables with data when it received from the network and app crashes after that, probably on trying to fetch an update. ~~It might be a race condition of some sort because the Realm function updates those objects concurrently.~~

The app works fine after restart. I tried to terminate and start sync again without success. I tried to erase and fetch all data without success. I tried to deleted and install the app without success.

**Update 1:** I tried to put 5 seconds delay between fetches but it didn't help so it looks like the problem is more general.

**Update 2:** When I removed container object observation the app stopped to crash and works fine even after the restart when new data is populated. So the root cause seems to be the observation during relationship resolve from `nil` to some new object.

App logs:
```
04.03 05:03:34.282 | R | Performing write
04.03 05:03:34.286 | R | User Realm update
04.03 05:03:34.287 | R | Deletions: [] | Insertions: [] | Modifications: [0]
04.03 05:03:34.287 | R | User objects count: 1
uncaught exception in notifier thread: N5realm11KeyNotFoundE: No such object
2021-04-03 05:03:35.514950+0300 Divtracker[74750:22811057] uncaught exception in notifier thread: N5realm11KeyNotFoundE: No such object
libc++abi.dylib: terminating with uncaught exception of type realm::KeyNotFound: No such object
terminating with uncaught exception of type realm::KeyNotFound: No such object
```

Trigger logs:
```
Logs:
[
  "04.03 02:03:34.626 | Symbol: EVV",
  "04.03 02:03:34.645 | Company for symbol 'EVV' not found. Fetching and fixing data...",
  "04.03 02:03:34.646 | Previous day price for symbol 'EVV' not found. Fetching and fixing data...",
  "04.03 02:03:34.731 | Previous day price for symbol 'EVV' not found. Fetching and fixing data...",
  "04.03 02:03:34.791 | Inserting company for symbol 'EVV'...",
  "04.03 02:03:34.791 | Company for symbol 'EVV' successfully inserted",
  "04.03 02:03:34.850 | Inserting previous day price for symbol 'EVV'...",
  "04.03 02:03:34.850 | Previous day price for symbol 'EVV' successfully inserted",
  "04.03 02:03:34.946 | Inserting dividends container for symbol 'EVV'...",
  "04.03 02:03:34.947 | Dividends for symbol 'EVV' successfully inserted"
]
```

Sync logs:
```
OK - Apr 03 5:03:35+03:00 - 61ms - SyncWrite

Source:

Write originated from MongoDB
Logs:
[
  "Upload message contained 1 changeset(s)",
  "Integrating upload required conflict resolution to be performed on 0 of the changesets",
  "Latest server version is now 6"
]
Partition:

P
Write Summary:
{
  "CompanyRealmModel": {
    "inserted": [
      "EVV"
    ]
  },
  "DividendsContainerRealmModel": {
    "inserted": [
      "EVV"
    ]
  },
  "PreviousDayPriceRealmModel": {
    "inserted": [
      "EVV"
    ]
  }
}
```

## Code Sample
I can provide Realm functions, schemes, objects, and code I use for objects observing later if needed.

## Version of Realm and Tooling
```
ProductName:	Mac OS X
ProductVersion:	10.15.6
BuildVersion:	19G2021

/Applications/Xcode.app/Contents/Developer
Xcode 12.4
Build version 12D4e

/usr/local/bin/pod
1.10.1
Realm (10.7.2)
RealmSwift (10.7.2)

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin19)

/usr/local/bin/carthage
0.37.0
(not in use here)

/usr/bin/git
git version 2.24.3 (Apple Git-128)
```

**Comment by anton-plebanovich** [comment] 2021-04-03 08:11
The other thing I noted is that when I delete leaf objects they are no longer available when I use `realm.objects(Leaf.self)` but they still exist in the container object. Do I need to delete them manually? It doesn't look right though 😕

**Comment by anton-plebanovich** [comment] 2021-04-04 01:23
I reworked db not use any relationships and collecting everything manually as a workaround

**Comment by DominicFrei** [comment] 2021-04-06 11:20
Hey @anton-plebanovich !

Thanks for providing all the information. Since you already noted you can reproduce this issue 100% I think it would be a good idea to just use that as a starting point.

In case this information (code, repo, etc.) is not supposed to be posted publicly, can you send it to realm-help@mongodb.com so we can have a look at it?

Thank you!

**Comment by anton-plebanovich** [comment] 2021-04-06 11:44
Hey @DominicFrei , thanks for the response. I already reworked the database and the source code for the app but I'll try to set up a demo project you can use tomorrow.

**Comment by DominicFrei** [comment] 2021-04-06 12:29
@anton-plebanovich  Alright. :) 
Glad to hear your rework works for you. No rush with the repo then. Whenever you'll be able to put something together we'll sure appreciate it! 👍

**Comment by anton-plebanovich** [comment] 2021-04-07 06:42
@DominicFrei sadly, I can't reproduce it anymore I tried to recreate the same setup but everything just works right now. I think we can close it as not reproducible or I can try it during the week since it might be some weird race conditions related to the network or server load I can't capture right now.

**Comment by DominicFrei** [comment] 2021-04-07 10:23
@anton-plebanovich Thank you for the feedback. I'll close it then and in case you stumble upon it again I'm happy to re-open as soon as we got more information. 👍

**Closed by DominicFrei** 2021-04-07 10:23 UTC
Labels: O-Community, Reproduction-Required

**Comment by bdkjones** [comment] 2021-07-19 06:31
I'm hitting this same crash now, after moving my previously-fine app to the new `@Persisted` property wrapper. I don't have anything more to report currently, but just adding a data point.

**Comment by leemaguire** [comment] 2021-07-19 11:19
@bdkjones I have seen a similar issue where this exception occurs when a primary key value is `nil` but the property is declared as non nil. I had solved it by declaring my property as optional.

e.g.

```
@Persisted(primaryKey: true) var _id: ObjectId
// becomes
@Persisted(primaryKey: true) var _id: ObjectId?
```

Maybe you are hitting something similar?
