### ISSUE TITLE
realm object reference become nil

### ISSUE THREAD

**Issue by Nikolus005** [realm/realm-cocoa#5382] opened 2017-10-09 10:00 UTC
## Goals
there are following models I am using:
```
class CurrentUser : Object, Mappable {
    
    dynamic var user : User? = nil
    dynamic var session : Session? = nil
    
    required convenience init?(map: Map) {
        self.init()
    }

    func mapping(map: Map) {
        user <- map["user"]
        session <- map["session"]
    }
    
    override func isEqual(_ object: Any?) -> Bool {
        let user = object as! User
        return user.id.value == self.user!.id.value
    }
}
```

```
class Session : Object, Mappable {
    
    dynamic var access_token : String? = nil
    
    required convenience init?(map: Map) {
        self.init()
    }
}
```

```

class User: Object, Mappable {
    enum Gender : String {
        case
        male = "Male",
        female = "Female",
        none = ""
    }

    let id = RealmOptional<Int>()
    dynamic var username: String? = nil
    dynamic var profile_picture: Images?
    dynamic var full_name: String? = nil
    private dynamic var genderRaw : String? = nil
    var gender: Gender? {
        get {
            
            return Gender(rawValue: genderRaw ?? "")
        }
        set{
            genderRaw = newValue?.rawValue
        }
    }
    let verified = RealmOptional<Bool>()
    dynamic private var workVisible : String? = nil
    dynamic private var locationVisible : String? = nil
    dynamic var work : String? = nil
    dynamic var education : String? = nil
    dynamic var bio : String? = nil
    dynamic var address : Location?
    let age = RealmOptional<Int>()
    dynamic var dobString : String? = nil
    override class func primaryKey() -> String? {
        return "id"
    }
}
```
I am calling API which returns JSON response for CurrentUser, here is code snippet:
```
static func signInUsing(fbProfile: DOPOFacebookProfile, success: ((CurrentUser) -> ())?, failure: ((Int, ApiError?)-> ())?){
        var params = Parameters()
        params["uid"] = fbProfile.uid
        params["fb_token"] = fbProfile.fbToken
        
        self.CallApiWithoutHeaders(url: SIGN_IN, method: .get, parameters: params, success: { (data) in
            let parsedResponse = CurrentUser(JSONString: data!.stringValue)
            success!(parsedResponse!)
        }, failure: failure)
    }
```
```
DogetherApi.signin(with: userProfile, success: { (currentUser) in
        let realm = try! Realm()
            try! realm.write {
                realm.add(currentUser)  //>>>>>HERE IS THE PROBLEM<<<<<<<
            }
        }, failure: { (errorCode, apiError) in
           ....
        })
```
currentUser's members becomes nil once `realm.add(currentUser)` is executed.
## Expected Results
valid object of User and Session class after execution of `realm.add(currentUser)`

## Actual Results
nil value for members of CurrentUser's object

## Version of Realm and Tooling

Realm framework version: 2.8.1
Xcode version: 8.3
iOS/OSX version: iOS 10.3.2

**Comment by kishikawakatsumi** [comment] 2017-10-09 11:09
If you are talking about Xcode's debug area, it's intended behavior. Realm does not copy any data until actually access the properties. When access the properties, Realm fetch the data directly from its file. So Realm does not store any data to its ivar. Additionally, Realm object will change to another class at the moment it is persisted. That's why you cannot see any values via the debugger and nil out all value after committed.

So if you'd like to debug objects value, you can use `po` command in debug console, or just use `print()` method.

See also: https://github.com/realm/realm-cocoa/issues/2777

**Comment by Nikolus005** [comment] 2017-10-09 11:29
yes. thanks for a quick reply.

**Closed** 2017-10-09 11:30 UTC
