### ISSUE TITLE
Make realm.resolve() work on frozen objects

### ISSUE THREAD

**Issue by astigsen** [realm/realm-cocoa#6950] opened 2020-11-19 14:56 UTC
When working with frozen objects, it often happens that you need to convert them back into live objects (this comes up every time you need to modify them, or just make sure that you have the latest version).

Today you can do that by first creating a `ThreadSafeReference` and then using `realm.resolve()` to get the live object:

```swift
realm.resolve(ThreadSafeReference(to: frozenItem))
```

This works, but it is not documented anywhere, and not very intuitive to a casual developer. It would be nice if we could have an overload of the `resolve` method that worked on a frozen objects directly, so it would instead just be:

```swift
realm.resolve(frozenItem)
```

**Comment by jsflax** [comment] 2020-11-19 15:02
@ericjordanmossman  is working on a `thaw` function that does exactly this: https://github.com/realm/realm-cocoa/tree/em/thaw. This is similar to the boilerplate that I have on my SwiftUI PR. This is the JIRA ticket: https://jira.mongodb.org/browse/RCOCOA-960 (not sure why it's private, I'll look into that).

`thaw`ing feels intuitive after `freez`ing, and accomplishes the above. Does this seem sufficient for your issue?

**Comment by astigsen** [comment] 2020-11-19 15:04
Yes, I would be happy with that. `thaw` definitely seems more discoverable.

**Comment by ericjordanmossman** [comment] 2020-12-01 15:49
Closing as duplicate of #6951

**Closed** 2020-12-01 15:50 UTC
Labels: T-Duplicate, T-Feature
