### ISSUE TITLE
Crash in Realm.object(ofType:forPrimaryKey:)

### ISSUE THREAD

**Issue by gshahbazian** [realm/realm-cocoa#7033] opened 2021-01-07 18:09 UTC
We're seeing crash reports with this trace:

```
Crashed: realmRead
0  Superhuman                     0x101ad11d8 realm::ClusterNodeInner::try_get(realm::ObjKey, realm::ClusterNode::State&) const + 94472
1  Superhuman                     0x101ad481c realm::ClusterTree::is_valid(realm::ObjKey) const + 108364
2  Superhuman                     0x101bfaf00 realm::Table::find_primary_key(realm::Mixed) const + 655632
3  Superhuman                     0x101859b9c realm::Object realm::Object::get_for_primary_key<objc_object* __strong, RLMAccessorContext>(RLMAccessorContext&, std::__1::shared_ptr<realm::Realm> const&, realm::ObjectSchema const&, objc_object* __strong) + 381 (object_accessor.hpp:381)
4  Superhuman                     0x1018594cc RLMGetObject + 220 (RLMObjectStore.mm:220)
5  Superhuman                     0x101911de8 Realm.object<A, B>(ofType:forPrimaryKey:) + 673 (Realm.swift:673)
```

## Version of Realm and Tooling
Realm framework version: 10.5.0
Xcode version: 12.3
iOS version: 14.2

**Comment by DominicFrei** [comment] 2021-01-07 18:56
Hi @gshahbazian,

Thank you for your report.

Can you provide some sample code? Maybe even an example repo so that we can reproduce your issue?

**Comment by gshahbazian** [comment] 2021-01-07 19:00
Hey @DominicFrei, I do not have a sample reproducing project at the moment. This began showing up in our crash reporter after testing an upgrade to 10.5.0.

I can try reproducing and following up here.

**Comment by DominicFrei** [comment] 2021-01-07 20:01
@gshahbazian Great, thank you!

**Comment by DominicFrei** [comment] 2021-02-22 13:46
I am going to close this for now since it seems it did not occur again and cannot be reproduced.

If anyone has further information on this issue please re-open the ticket at any time.

**Closed by DominicFrei** 2021-02-22 13:46 UTC
Labels: O-Community
