### ISSUE TITLE
Lag and slow performance when retrieve and write, delete objects on the main thread at the same time

### ISSUE THREAD

**Issue by peihsendoyle** [realm/realm-cocoa#4939] opened 2017-05-09 12:43 UTC
Hi, I'm back after a long journey to Japan last month.

Sorry for the late reply, I cannot keep up with this issue. Really sorry about that.

I'm really in stuck with my logic in Realm. I'm going to describe it for you @austinzheng @kishikawakatsumi, it would be pleased if you could help me guys.

My case is something like this:
1. I pull my data from my server API --> new objects
2. I retrieve old objects from Realm.
3. I compare the new objects and old objects. After that, I delete mismatched objects from Realm, update matched objects with new states from the server and add new objects (if they are not in Realm before).
4. I show them (new objects from Realm) on the table view.

--> I'm doing all of these steps on main thread. And it's really bad UI (lag and low performance). Any suggestion for me on this cases?

Thanks and hope that someone could help me.

Here is my class:

```swift
class ZStoreManager { }

// MARK: Load child object

extension ZStoreManager {
    
    class func nodes(_ store: ZStoreModel) -> Results<ZNodeModel> {
        return ZRealmStore.models(ZNodeModel.self).filter("storeIndentifier == '\(store.identifier)'")
    }
    
    class func object<T: Object>(_ type: T.Type, id: String) -> T? {
        return ZRealmStore.object(type, id: id)
    }
    
    class func objects<T: Object>(_ type: T.Type) -> Results<T> {
        return  ZRealmStore.objects(type)
    }
}

// MARK: Load local

extension ZStoreManager {
    
    class func local(dataSource: ZServiceDataSource, complete: @escaping ((_ store: ZStoreModel?) -> Void)) {
        DispatchQueue.main.async {
            Log.debug("------------ LOCAL START: ", dataSource.url)
            
            ZStoreManager.clean(dataSource: dataSource)
            
            let store = ZStoreModel()
            store.identifier = dataSource.md5Identifier
            
            Log.debug("------------ LOCAL DONE: ", dataSource.url)
            
            if dataSource.current_page == 0 {
                DispatchQueue.main.async {
                    complete(store)
                }
            }
        }
    }
}

// MARK:  Load server

extension ZStoreManager {
    
    class func clean(dataSource: ZServiceDataSource) {
        Log.debug("------------ CLEAN START : ", dataSource.url)
        
        let store = ZStoreModel()
        store.identifier = dataSource.md5Identifier
        
        if let _nodes = store.nodes() {
            for node in _nodes {
                if dataSource.current_page == 0 && node.page != 0 { ZRealmStore.delete(node) }
            }
        }
        
        Log.debug("------------CLEAN DONE: ", dataSource.url)
    }
    
    class func server(dataSource: ZServiceDataSource, complete: @escaping ((_ store: ZStoreModel?) -> Void)) {
        DispatchQueue.main.async {
            Log.debug("----------- SERVER START: ", dataSource.url)
            
            ZStoreManager.clean(dataSource: dataSource)
            
            ZServiceManager.request(dataSource) { (data) in
                Log.debug("----------- SERVER REPONSE: ", dataSource.url)
                
                if let error: ZServiceResponseError = data.error {
                    if error == ZServiceResponseError.unauthorized {
                        // FIXME: FIX IT
                        Log.error("Authenticate needed...")
                        Service.authenticate({ (_) in })
                    } else {
                        Log.error("ERROR:", error)
                        complete(nil)
                    }
                    return
                }
                
                // new store
                let store = ZStoreModel(dataSource: dataSource, data: data)
                
                if store.isInvalidated == false {
                    
                    // Map server data with specific types
                    var all_nodes = List<ZNodeModel>()
                    
                    Log.debug("----------- SERVER START MAP: ", dataSource.url)
                    if let _data = data.data as? [String: Any] {
                        for (key, type) in dataSource.types {
                            let nodes = self.mapperObject(type, data: _data, key: key, store_identifier: store.identifier, store_current_page: store.currentPage, store_auto_create_node: store.auto_create_node)
                            all_nodes += nodes.nodes
                        }
                    }
                    
                    Log.debug("----------- SERVER DONE MAP: ", dataSource.url)
                    
                    let temp_nodes = List<ZNodeModel>()
                    
                    // Parse nodes (must be add data before add node)
                    if dataSource.auto_create_node == false {
                        if let json_nodes = data.nodes as? [Any] {
                            for item in json_nodes {
                                if let node = Mapper<ZNodeModel>().map(JSONObject: item) {
                                    temp_nodes.append(node)
                                }
                            }
                        }
                    }
                    
                    for node in temp_nodes {
                        node.storeIndentifier = store.identifier
                        dataSource.types.forEach({ (element:(key: String, value: AnyClass)) in
                            if element.key == node.type {
                                node.object_type = NSStringFromClass(element.value.self).components(separatedBy: ".").last!
                            }
                        })
                        node.page = store.currentPage
                        if node.object_type != nil {
                            all_nodes.append(node)
                        } else {
                            assertionFailure("Please add types to dataSource")
                        }
                    }
                    
                    Log.debug("----------- SERVER START CLEAN NODES: ", dataSource.url)
                    
                    // Delete old node
                    if dataSource.current_page == 0 {
                        if let old_nodes = store.nodes() {
                            let mis_match = old_nodes.filter{ !all_nodes.contains($0) }
                            for missing in mis_match {
                                ZRealmStore.delete(missing)
                            }
                        }
                    }
                    
                    Log.debug("----------- SERVER DONE CLEAN NODES: ", dataSource.url)
                    
                    // update node
                    for node in all_nodes {
                        ZRealmStore.add(node)
                    }
                    
                    Log.debug("----------- SERVER DONE: ", dataSource.url)
                    DispatchQueue.main.async {
                        complete(store)
                    }
                }
            }
        }
    }
}

extension Mapper {
    
    /// Maps a JSON dictionary to an object that conforms to Mappable
    public func map<T: Mappable>(type: T.Type, JSON: Any?) -> T? {
        if let JSON = JSON as? [String: Any] {
            let map = Map(mappingType: .fromJSON, JSON: JSON, context: context, shouldIncludeNilValues: shouldIncludeNilValues)
            if var object = type.init(map: map) as T! {
                object.mapping(map: map)
                return object
            }
        }
        return nil
    }
    
}

extension ZStoreManager {
    
    static func mapperObject<T: ZModel>(_ type: T.Type, data: [String: Any], key: String, store_identifier: String, store_current_page: Int, store_auto_create_node: Bool) -> (nodes:[ZNodeModel], objects: [T]) {
        
        var _nodes: [ZNodeModel] = []
        var _objects:[T] = []
        var _objects_delete_nedded:[T] = []
        
        if let object = data[key] as? [Any]  {
            for (index, item ) in object.enumerated() {
                if let gennericObject = Mapper<ZModel>().map(type: type, JSON: item) {
                    if gennericObject.is_deleted == true {
                        if let objectDeleteNeed = ZRealmStore.object(type, id: String(gennericObject.id)) {
                            _objects_delete_nedded.append(objectDeleteNeed)
                        }
                    } else {
                        if store_auto_create_node == true {
                            let node = ZNodeModel(store_identifier, type: key, objectType: type, sortIndex: index, page: store_current_page, objectId: gennericObject.id)
                            _nodes.append(node)
                        }
                        ZRealmStore.add(gennericObject)
                        _objects.append(gennericObject)
                    }
                } else {
                    Log.debug("MAP \(key) : faild -> ", data.count)
                }
            }
        }
        _objects_delete_nedded.forEach { (object) in
            NotificationCenter.default.post(name: Notification.Name(rawValue: "kNotificationDidDeleteObject"), object: object)
        }
        return (_nodes, _objects)
    }
}
```

**Comment by austinzheng** [comment] 2017-05-09 18:32
Don't worry about the late reply! Thanks for using Realm!

The solution to your problem is almost certainly moving the bulk of your work (everything that happens in the callback to `ZServiceManager.request(dataSource)`) to a background thread so the main thread isn't tied up by work, causing choppy UI performance.

It looks like you are using class methods on a singleton object `ZRealmStore` to perform operations on your Realm instance (I am guessing, since you didn't include the definition :). If you use a side thread you will need to refactor `ZRealmStore` to open a new Realm instance when performing its operations. My recommendation is that you should store the Realm configuration instead of the Realm instance, and open up a new Realm every time you perform an operation. Because we cache the expensive parts of Realms internally, opening the same Realm multiple times should not incur any sort of noticeable performance penalty.

Also, this isn't really a performance issue but you shouldn't create a `List<T>` variable and manipulate it outside the context of a Realm. For what you are doing a standard Swift `Array<T>` should be used.

I hope these suggestions help! If you have additional questions or require clarification, please let us know.

**Comment by peihsendoyle** [comment] 2017-05-11 13:37
Hi @austinzheng, I'm here after some days working with Realm background thread.

Everything seems to be good now. I do all the `ZServiceManager.request(dataSource)` work on the background thread and call a completion on main thread after that. But in the completion, I have to pass the `store` object that I created and saved to realm on the background thread before in the `ZServiceManager.request(dataSource)`. I followed the docs and created a ThreadSafeReference to `store` and resolved it on the main thread. However, the `store` after resolved is not exactly the `store` on the background thread.

Here is the code: 
```
class func server(dataSource: ZServiceDataSource, complete: @escaping ((_ store: ZStoreModel?) -> Void)) {
        
        ZStoreManager.clean(dataSource: dataSource)
        
        ZServiceManager.request(dataSource) { (data) in
            DispatchQueue.global().async {

                // new store
                
-------create thread safe reference on background--------
                let store = ZStoreModel(dataSource: dataSource, data: data)
                let objectRef = ThreadSafeReference(to: store)
                
                if store.isInvalidated == false {
                    
                    // Parse data
                    var all_nodes:[ZNodeModel] = []
                    
                    if let _data = data.data as? [String: Any] {
                        for (key, type) in dataSource.types {
                            let nodes = self.mapperObject(type, data: _data, key: key, store: store)
                            all_nodes += nodes.nodes
                        }
                    }
                   
                    var temp_nodes: [ZNodeModel] = []
                    
                    if dataSource.auto_create_node == false {
                        if let json_nodes = data.nodes as? [Any] {
                            for item in json_nodes {
                                if let node = Mapper<ZNodeModel>().map(JSONObject: item) {
                                    temp_nodes.append(node)
                                }
                            }
                        }
                    }
                    
                    for node in temp_nodes {
                        node.storeIndentifier = store.identifier
                        dataSource.types.forEach({ (element:(key: String, value: AnyClass)) in
                            if element.key == node.type {
                                node.object_type = NSStringFromClass(element.value.self).components(separatedBy: ".").last!
                            }
                        })
                        node.page = store.currentPage
                        if node.object_type != nil {
                            all_nodes.append(node)
                        } else {
                            assertionFailure("Please add types to dataSource")
                        }
                    }
                    
                    var not_containt_match_nodes: [ZNodeModel] = []
                    if dataSource.current_page == 0 {
                        if let old_nodes = store.nodes() {
                            for node in old_nodes {
                                var ismatch: Bool = false
                                for _node in all_nodes {
                                    if let id0 = node.id, let id1 = _node.id {
                                        if id0 == id1 {
                                            ismatch = true
                                            break
                                        }
                                    }
                                }
                                if ismatch == false {
                                    not_containt_match_nodes.append(node)
                                }
                            }
                        }
                        ZRealmStore.deletes(not_containt_match_nodes)
                    }
                                        
                    // update node
                    ZRealmStore.adds(all_nodes)

-------resolve on the main thread----------
                     DispatchQueue.main.async {
                        autoreleasepool {
                            let realm = ZRealmStore.configAutomaticallyUpdateSchema(isMemoryIdentifier: true)
                            guard let object = realm.resolve(objectRef) else { return }
                            complete(object) ---> the object I get doesn't have attributes I added on the background, it's default attributes of initialization.
                        }
                    }
                }
            }
        }
    }
```

ZStoreModel class:

```
class ZStoreModel: Object {
    
    dynamic var identifier: String!
    dynamic var infors: String?
    dynamic var errors: String?
    dynamic var validationErrors: String?
    dynamic var warnings: String?
    dynamic var currentPage: Int = 0
    dynamic var totalPage: Int = 0
    dynamic var previousURL: String?
    dynamic var nextURL: String?
    dynamic var status: Bool = true
    dynamic var createdAt: Date?
    dynamic var updatedAt: Date?
    dynamic var types: [String: ZModel.Type] = [:]
    dynamic var auto_create_node: Bool = true
    dynamic var is_public: Bool = true
    
    dynamic var modified_at = Date()
    
    var _currentDataSource: ZServiceDataSource? = nil
    
    override static func primaryKey() -> String? {
        return "identifier"
    }
    
    override static func ignoredProperties() -> [String] {
        return ["types", "_currentDataSource"]
    }
    
    required init() { super.init() }
    required init(realm: RLMRealm, schema: RLMObjectSchema) { super.init(realm: realm, schema: schema) }
    
    required init(value: Any, schema: RLMSchema) {
        super.init(value: value, schema: schema)
    }
    
    required init(dataSource: ZServiceDataSource, data: ZServiceResponseData? = nil) {
        super.init()
        
        self._currentDataSource = dataSource
        
        self.identifier = dataSource.md5Identifier
        self.auto_create_node = dataSource.auto_create_node
        self.types = dataSource.types
        
        if let data = data {
            self.infors = data.navigation?.infors?.description
            self.errors = data.navigation?.errors?.description
            self.validationErrors = data.navigation?.validationErrors?.description
            self.warnings = data.navigation?.warnings?.description
            self.currentPage = data.currentPage
            self.totalPage = data.totalPage
            
            if self.currentPage == 0 {
                self.currentPage = dataSource.current_page
            }
            
            if let url = data.previousURL {
                self.previousURL = ZStoremanagerConfiguration.API + url
            } else {
                self.previousURL = nil
            }
            if let url = data.nextURL {
                self.nextURL = ZStoremanagerConfiguration.API + url
            } else {
                self.nextURL = nil
            }
            
            self.add()
        }
    }

static func add() {
        let realm = ZRealmStore.configAutomaticallyUpdateSchema(isMemoryIdentifier: true)
        
        try! realm.write({
            realm.add(self, update: true)
        })
    }
}
```

Did I miss something, @austinzheng .
Thanks very much if you could help this case.

**Comment by austinzheng** [comment] 2017-05-11 20:27
Can you try calling `refresh` on the `realm` in your block dispatched to main (right before the call to `complete(object)`)? Alternately, you can create the thread-safe reference right before you dispatch to main, since it looks like you make changes to the object or Realm at that point?

Also, if you're ignoring the property `types` in your model, why is it still declared as `dynamic`? I don't see a setter or getter.

**Comment by peihsendoyle** [comment] 2017-05-12 00:35
I've tried your solution but it doesn't work. Here is the code:
```
// update node
                    ZRealmStore.adds(all_nodes)
                    
                    print(store.nextDataSource()?.types as Any) //----- right
                    
                    let objectRef = ThreadSafeReference(to: store)
                    
                    print(store.nextDataSource()?.types as Any) //------ right
                    
                    DispatchQueue.main.async {
                        autoreleasepool {
                            let realm = ZRealmStore.configAutomaticallyUpdateSchema(isMemoryIdentifier: true)
                            guard let object = realm.resolve(objectRef) else { return }
                            realm.refresh()
                            print(object.nextDataSource()?.types as Any) //----- nothing
                            complete(object)
                        }
                    }
```

Here is what I get from the log of 3 print lines:
```
Optional(["comments": Yosing_Development.CommentModel])
Optional(["comments": Yosing_Development.CommentModel])
Optional([:])

**Comment by austinzheng** [comment] 2017-05-12 21:14
There might or might not be a bug in thread-safe references; it is a little hard to tell without the context of the project. Is there a chance you could build a simple reproduction project and send it over, so that we can look at the problem in more detail?

For now, can you try getting rid of thread safe references and, instead, re-fetch the object using its primary key with the `object(ofType:forPrimaryKey:)` API? You can change the line that resolves the thread safe reference to fetch the item using the primary key instead. If that doesn't fix the problem, we can continue investigating.

**Comment by austinzheng** [comment] 2017-06-01 18:31
I'm going to close this ticket since it hasn't been touched for a while. If you have further questions please feel free to file new tickets against us.

**Closed by austinzheng** 2017-06-01 18:31 UTC
Labels: S:Waiting For User, T:Help
