### ISSUE TITLE
Realm Browser hangs on startup

### ISSUE THREAD

**Issue by mkoppanen** [realm/realm-cocoa#1320] opened 2015-01-10 12:49 UTC
Version: 0.89.2

Opening by running "open <path>" from Terminal. Seems to happen consistently and renders the Browser unusable.

```
Date/Time:       2015-01-10 12:45:27 +0000
OS Version:      10.10.1 (Build 14B25)
Architecture:    x86_64
Report Version:  21

Command:         Realm Browser
Path:            /Applications/Realm Browser.app/Contents/MacOS/Realm Browser
Version:         0.89.2 (0.89.2)
Parent:          launchd [1]
PID:             16189

Event:           hang
Duration:        1.00s (process was unresponsive for 129 seconds before sampling)
Steps:           11 (100ms sampling interval)

Hardware model:  MacBookPro10,1
Active cpus:     8

Fan speed:       2168 rpm

--------------------------------------------------
Timeline format: stacks are sorted chronologically
Use -i and -heavy to re-report with count sorting
--------------------------------------------------

Heaviest stack for the main thread of the target process:
  11  start + 1 (libdyld.dylib + 13769) [0x7fff9336e5c9]
  11  NSApplicationMain + 1832 (AppKit + 13012) [0x7fff980192d4]
  11  -[NSApplication run] + 594 (AppKit + 97827) [0x7fff9802de23]
  11  -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 194 (AppKit + 147072) [0x7fff98039e80]
  11  _DPSNextEvent + 964 (AppKit + 149201) [0x7fff9803a6d1]
  11  _BlockUntilNextEventMatchingListInModeWithFilter + 71 (HIToolbox + 188411) [0x7fff89e1affb]
  11  ReceiveNextEventCommon + 179 (HIToolbox + 188606) [0x7fff89e1b0be]
  11  RunCurrentEventLoopInMode + 235 (HIToolbox + 189503) [0x7fff89e1b43f]
  11  CFRunLoopRunSpecific + 296 (CoreFoundation + 464952) [0x7fff8c59e838]
  11  __CFRunLoopRun + 2159 (CoreFoundation + 467695) [0x7fff8c59f2ef]
  11  __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9 (CoreFoundation + 744537) [0x7fff8c5e2c59]
  11  _dispatch_main_queue_callback_4CF + 861 (libdispatch.dylib + 56511) [0x7fff8d0d0cbf]
  11  _dispatch_client_callout + 8 (libdispatch.dylib + 7187) [0x7fff8d0c4c13]
  11  _dispatch_barrier_sync_f_slow_invoke + 412 (libdispatch.dylib + 61518) [0x7fff8d0d204e]
  11  _dispatch_client_callout + 8 (libdispatch.dylib + 7187) [0x7fff8d0c4c13]
  11  __50-[RLMDocument initWithContentsOfURL:ofType:error:]_block_invoke + 72 (Realm Browser + 7496) [0x1058dad48]
  11  -[RLMRealmNode connect:] + 77 (Realm Browser + 96857) [0x1058f0a59]
  11  ??? (<E53C4B7B-E233-3DBE-979E-A1CE4A201E01> + 222775) [0x10595e637]
  11  ??? (<E53C4B7B-E233-3DBE-979E-A1CE4A201E01> + 224930) [0x10595eea2]
  11  ??? (<E53C4B7B-E233-3DBE-979E-A1CE4A201E01> + 227756) [0x10595f9ac]
  11  ??? (<E53C4B7B-E233-3DBE-979E-A1CE4A201E01> + 1072520) [0x105a2dd88]
  11  ??? (<E53C4B7B-E233-3DBE-979E-A1CE4A201E01> + 1072669) [0x105a2de1d]
  11  ??? (<E53C4B7B-E233-3DBE-979E-A1CE4A201E01> + 293833) [0x10596fbc9]
  11  __psynch_mutexwait + 10 (libsystem_kernel.dylib + 90466) [0x7fff9962d162]
 *11  psynch_mtxcontinue + 0 (pthread + 22095) [0xffffff7f80f5764f]


Process:         Realm Browser [16189]
Path:            /Applications/Realm Browser.app/Contents/MacOS/Realm Browser
Architecture:    x86_64
Parent:          launchd [1]
UID:             501
Task size:       5126 pages
Note:            Unresponsive for 129 seconds before sampling

  Thread 0x8e4707     DispatchQueue 1     11 samples (1-11)   priority 46
  <thread QoS user interactive, boosted, received importance donation from WindowServer [122], IO policy important>
  11  start + 1 (libdyld.dylib + 13769) [0x7fff9336e5c9] 1-11
    11  NSApplicationMain + 1832 (AppKit + 13012) [0x7fff980192d4] 1-11
      11  -[NSApplication run] + 594 (AppKit + 97827) [0x7fff9802de23] 1-11
        11  -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 194 (AppKit + 147072) [0x7fff98039e80] 1-11
          11  _DPSNextEvent + 964 (AppKit + 149201) [0x7fff9803a6d1] 1-11
            11  _BlockUntilNextEventMatchingListInModeWithFilter + 71 (HIToolbox + 188411) [0x7fff89e1affb] 1-11
              11  ReceiveNextEventCommon + 179 (HIToolbox + 188606) [0x7fff89e1b0be] 1-11
                11  RunCurrentEventLoopInMode + 235 (HIToolbox + 189503) [0x7fff89e1b43f] 1-11
                  11  CFRunLoopRunSpecific + 296 (CoreFoundation + 464952) [0x7fff8c59e838] 1-11
                    11  __CFRunLoopRun + 2159 (CoreFoundation + 467695) [0x7fff8c59f2ef] 1-11
                      11  __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9 (CoreFoundation + 744537) [0x7fff8c5e2c59] 1-11
                        11  _dispatch_main_queue_callback_4CF + 861 (libdispatch.dylib + 56511) [0x7fff8d0d0cbf] 1-11
                          11  _dispatch_client_callout + 8 (libdispatch.dylib + 7187) [0x7fff8d0c4c13] 1-11
                            11  _dispatch_barrier_sync_f_slow_invoke + 412 (libdispatch.dylib + 61518) [0x7fff8d0d204e] 1-11
                              11  _dispatch_client_callout + 8 (libdispatch.dylib + 7187) [0x7fff8d0c4c13] 1-11
                                11  __50-[RLMDocument initWithContentsOfURL:ofType:error:]_block_invoke + 72 (Realm Browser + 7496) [0x1058dad48] 1-11
                                  11  -[RLMRealmNode connect:] + 77 (Realm Browser + 96857) [0x1058f0a59] 1-11
                                    11  ??? (<E53C4B7B-E233-3DBE-979E-A1CE4A201E01> + 222775) [0x10595e637] 1-11
                                      11  ??? (<E53C4B7B-E233-3DBE-979E-A1CE4A201E01> + 224930) [0x10595eea2] 1-11
                                        11  ??? (<E53C4B7B-E233-3DBE-979E-A1CE4A201E01> + 227756) [0x10595f9ac] 1-11
                                          11  ??? (<E53C4B7B-E233-3DBE-979E-A1CE4A201E01> + 1072520) [0x105a2dd88] 1-11
                                            11  ??? (<E53C4B7B-E233-3DBE-979E-A1CE4A201E01> + 1072669) [0x105a2de1d] 1-11
                                              11  ??? (<E53C4B7B-E233-3DBE-979E-A1CE4A201E01> + 293833) [0x10596fbc9] 1-11
                                                11  __psynch_mutexwait + 10 (libsystem_kernel.dylib + 90466) [0x7fff9962d162] 1-11
                                                 *11  psynch_mtxcontinue + 0 (pthread + 22095) [0xffffff7f80f5764f] 1-11

  Thread 0x8e4713     DispatchQueue 2     11 samples (1-11)   priority 46
  <thread QoS user interactive, boosted, received importance donation from WindowServer [122], IO policy important>
  11  _dispatch_mgr_thread + 52 (libdispatch.dylib + 19050) [0x7fff8d0c7a6a] 1-11
    11  kevent64 + 10 (libsystem_kernel.dylib + 94766) [0x7fff9962e22e] 1-11
     *11  ??? (kernel + 6000416) [0xffffff80007b8f20] 1-11

  Thread 0x8e4730     DispatchQueue 187   11 samples (1-11)   priority 37
  <thread QoS user initiated, boosted, received importance donation from WindowServer [122], IO policy important>
  11  start_wqthread + 13 (libsystem_pthread.dylib + 5281) [0x7fff996364a1] 1-11
    11  _pthread_wqthread + 729 (libsystem_pthread.dylib + 14027) [0x7fff996386cb] 1-11
      11  _dispatch_worker_thread3 + 91 (libdispatch.dylib + 77796) [0x7fff8d0d5fe4] 1-11
        11  _dispatch_root_queue_drain + 463 (libdispatch.dylib + 18103) [0x7fff8d0c76b7] 1-11
          11  _dispatch_queue_invoke + 202 (libdispatch.dylib + 28364) [0x7fff8d0c9ecc] 1-11
            11  _dispatch_queue_drain + 1100 (libdispatch.dylib + 21349) [0x7fff8d0c8365] 1-11
              11  _dispatch_client_callout + 8 (libdispatch.dylib + 7187) [0x7fff8d0c4c13] 1-11
                11  __NSOQSchedule_f + 184 (Foundation + 33187) [0x7fff93a6f1a3] 1-11
                  11  -[__NSOperationInternal _start:] + 653 (Foundation + 34204) [0x7fff93a6f59c] 1-11
                    11  -[NSBlockOperation main] + 97 (Foundation + 170245) [0x7fff93a90905] 1-11
                      11  __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 7 (Foundation + 1299176) [0x7fff93ba42e8] 1-11
                        11  __80-[NSDocumentController openDocumentWithContentsOfURL:display:completionHandler:]_block_invoke_2879 + 59 (AppKit + 4715971) [0x7fff984955c3] 1-11
                          11  -[NSDocumentController makeDocumentWithContentsOfURL:ofType:error:] + 627 (AppKit + 4719081) [0x7fff984961e9] 1-11
                            11  -[RLMDocument initWithContentsOfURL:ofType:error:] + 679 (Realm Browser + 7175) [0x1058dac07] 1-11
                              11  _dispatch_barrier_sync_f_slow + 597 (libdispatch.dylib + 46423) [0x7fff8d0ce557] 1-11
                                11  semaphore_wait_trap + 10 (libsystem_kernel.dylib + 71018) [0x7fff9962856a] 1-11
                                 *11  semaphore_wait_continue + 0 (kernel + 1415472) [0xffffff8000359930] 1-11

  Thread 0x8e4738     11 samples (1-11)   priority 46
  <thread QoS user interactive, boosted, received importance donation from WindowServer [122], IO policy important>
  11  thread_start + 13 (libsystem_pthread.dylib + 5297) [0x7fff996364b1] 1-11
    11  _pthread_start + 176 (libsystem_pthread.dylib + 12921) [0x7fff99638279] 1-11
      11  _pthread_body + 131 (libsystem_pthread.dylib + 13052) [0x7fff996382fc] 1-11
        11  _NSEventThread + 137 (AppKit + 1603495) [0x7fff9819d7a7] 1-11
          11  CFRunLoopRunSpecific + 296 (CoreFoundation + 464952) [0x7fff8c59e838] 1-11
            11  __CFRunLoopRun + 1371 (CoreFoundation + 466907) [0x7fff8c59efdb] 1-11
              11  __CFRunLoopServiceMachPort + 212 (CoreFoundation + 469780) [0x7fff8c59fb14] 1-11
                11  mach_msg_trap + 10 (libsystem_kernel.dylib + 70958) [0x7fff9962852e] 1-11
                 *11  ipc_mqueue_receive_continue + 0 (kernel + 1209328) [0xffffff80003273f0] 1-11

  Binary Images:
         0x1058d9000 -        0x1058f9fff  io.realm.Realm-Browser 0.89.2 (0.89.2) <D6576816-5E3E-3309-B7D8-DD2FE86B9D36>  /Applications/Realm Browser.app/Contents/MacOS/Realm Browser
         0x105928000 -                ???  ???                                    <E53C4B7B-E233-3DBE-979E-A1CE4A201E01>
      0x7fff89ded000 -     0x7fff8a0effff  com.apple.HIToolbox 2.1.1 (756)        <9DD121B5-B7EB-3C43-8155-61A4417F8E9A>  /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/HIToolbox
      0x7fff8c52d000 -     0x7fff8c8c3fff  com.apple.CoreFoundation 6.9 (1151.16) <F2B088AF-A5C6-3FAE-9EB4-7931AF6359E4>  /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
      0x7fff8d0c3000 -     0x7fff8d0edfff  libdispatch.dylib (442.1.4)            <502CF32B-669B-3709-8862-08188225E4F0>  /usr/lib/system/libdispatch.dylib
      0x7fff9336b000 -     0x7fff9336efff  libdyld.dylib (353.2.1)                <19FAF435-C165-3374-9DEF-D7BBA7D61DB6>  /usr/lib/system/libdyld.dylib
      0x7fff93a67000 -     0x7fff93d95fff  com.apple.Foundation 6.9 (1151.16)     <18EDD673-A010-3E99-956E-DA594CE1FA80>  /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
      0x7fff98016000 -     0x7fff98b57fff  com.apple.AppKit 6.9 (1343.16)         <C98DB43F-4245-3E6E-A4EE-37DAEE33E174>  /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
      0x7fff99617000 -     0x7fff99634fff  libsystem_kernel.dylib (2782.1.97)     <93E0E0A9-75B6-3904-BB4E-4BC7C05F4B6B>  /usr/lib/system/libsystem_kernel.dylib
      0x7fff99635000 -     0x7fff9963efff  libsystem_pthread.dylib (105.1.4)      <26B1897F-0CD3-30F3-B55A-37CB45062D73>  /usr/lib/system/libsystem_pthread.dylib
 *0xffffff7f80f52000 - 0xffffff7f80f5afff  com.apple.kec.pthread 1.0 (1)          <DB4D4632-FD2B-3FAE-86D3-3432DCDB7FA9>  /System/Library/Extensions/pthread.kext/Contents/MacOS/pthread
 *0xffffff8000200000 - 0xffffff80009fffff  kernel (2782.1.97)                     <89E10306-BC78-3A3B-955C-7C4922577E61>  /System/Library/Kernels/kernel
```

**Comment by alazier** [comment] 2015-01-12 19:17
There is currently an issue when accessing realm files simultaneously from the browser and simulator. If this is the issue you are hitting, then killing your app in the simulator may allow you to work around this for the time being. Choosing a 64bit simulator device can also in some cases work around this issue.

**Comment by alazier** [comment] 2015-01-16 18:23
Closing this as a duplicate of #1270

**Closed by alazier** 2015-01-16 18:23 UTC
