### ISSUE TITLE
report an error that lead to crash

### ISSUE THREAD

**Issue by piaotairen** [realm/realm-cocoa#4936] opened 2017-05-09 02:36 UTC
# Crashlytics - plaintext stacktrace downloaded by Cobb at Tue, 09 May 2017 02:26:51 GMT
# Organization: Livestar
# Platform: pos
# Application: LiveStar
# Version: N/A
# Issue #: 1245
# Issue ID: 58f5e1080aeb16625bd3752b
# Session ID: 7893a2369bd04c828397c843e20e6c4c_f0cf40e37a9646ca9f59a4cc5c99c5a9_0_v1
# Date: 2017-05-03T00:03:14Z
# OS Version: 10.3.1 (14E304)
# Device: iPhone 7 Plus
# RAM Free: 41.8%
# Disk Free: 80.4%

#0. Crashed: com.apple.main-thread
0  libsystem_info.dylib                0x18b539014 (Missing)
1  libsystem_networkextension.dylib    0x18b603334 (Missing)
2  libcopyfile.dylib                   0x18b4ad9c4 (Missing)
3  Realm                               0x102f2cee0 please_report_this_error_to_help_at_realm_dot_io + 10
4  Realm                               0x102f2d358 realm::util::terminate_internal(std::__1::basic_stringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) + 232
5  libsystem_networkextension.dylib    0x18b603334 (Missing)
6  Realm                               0x102f2d4ec realm::util::terminate(char const*, char const*, long, std::initializer_list<realm::util::Printable>&&) + 388
7  libsystem_networkextension.dylib    0x18b603334 (Missing)
8  Realm                               0x102fdac58 void realm::util::terminate<unsigned long, int, unsigned long, int, unsigned long, int>(char const*, char const*, long, unsigned long, int, unsigned long, int, unsigned long, int) + 98
9  Realm                               0x102fda114 realm::Group::attach(unsigned long, bool) + 188
10 Realm                               0x102fe570c realm::SharedGroup::do_begin_read(realm::VersionID, bool) + 76
11 Realm                               0x102fe4bd4 realm::SharedGroup::begin_read(realm::VersionID) + 36
12 Realm                               0x102ea3d84 realm::Realm::read_group() + 44
13 Realm                               0x102ea35d0 realm::Realm::Realm(realm::Realm::Config, std::__1::shared_ptr<realm::_impl::RealmCoordinator>) + 256
14 Realm                               0x102df82d4 realm::Realm::make_shared_realm(realm::Realm::Config, std::__1::shared_ptr<realm::_impl::RealmCoordinator>)::make_shared_enabler::make_shared_enabler(realm::Realm::Config, std::__1::shared_ptr<realm::_impl::RealmCoordinator>) + 88
15 Realm                               0x102df8084 std::__1::shared_ptr<realm::Realm::make_shared_realm(realm::Realm::Config, std::__1::shared_ptr<realm::_impl::RealmCoordinator>)::make_shared_enabler> std::__1::shared_ptr<realm::Realm::make_shared_realm(realm::Realm::Config, std::__1::shared_ptr<realm::_impl::RealmCoordinator>)::make_shared_enabler>::make_shared<realm::Realm::Config, std::__1::shared_ptr<realm::_impl::RealmCoordinator> >(realm::Realm::Config&&, std::__1::shared_ptr<realm::_impl::RealmCoordinator>&&) + 136
16 Realm                               0x102df477c realm::_impl::RealmCoordinator::get_realm(realm::Realm::Config) + 400
17 Realm                               0x102ea4c50 realm::Realm::get_shared_realm(realm::Realm::Config) + 112
18 Realm                               0x102e883b4 +[RLMRealm realmWithConfiguration:error:] + 584
19 Livestar                            0x100103630 -[LSRealmDataManager setDefaultRealm] (LSRealmDataManager.m:196)
20 Livestar                            0x100102f80 +[LSRealmDataManager manager] (LSRealmDataManager.m:105)
21 Livestar                            0x10040549c -[LSFlowMessageCenter checkIfHasNewFlowMessage] (LSFlowMessageCenter.m:146)
22 Livestar                            0x10040539c -[LSFlowMessageCenter timerBegin] (LSFlowMessageCenter.m:134)
23 Livestar                            0x100305ca0 -[LSMyFlowViewController init] (LSMyFlowViewController.m:66)
24 Livestar                            0x10036fac8 -[LSTabBarController addAllChildVcs] (LSTabBarController.m:88)
25 Livestar                            0x10036f78c -[LSTabBarController viewDidLoad] (LSTabBarController.m:59)
26 UIKit                               0x19279f6c8 -[UITabBarController initWithNibName:bundle:] + 256
27 Livestar                            0x1003353b4 -[AppDelegate setupMainViewController] (AppDelegate.m:225)
28 Livestar                            0x100335294 -[AppDelegate advertisementFinishLaunching] (AppDelegate.m:217)
29 Livestar                            0x1003351c4 __32-[AppDelegate loadAdvertisement]_block_invoke (AppDelegate.m:205)
30 Livestar                            0x1004342b8 -[LSAdvertisementManager shouldLoadAdvertisementWithCompletion:] (LSAdvertisementManager.m:286)
31 Livestar                            0x1003350c8 -[AppDelegate loadAdvertisement] (AppDelegate.m:196)
32 Livestar                            0x100334670 -[AppDelegate application:didFinishLaunchingWithOptions:] (AppDelegate.m:75)
33 UIKit                               0x1926df2dc -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:] + 380
34 UIKit                               0x1928eb800 -[UIApplication _callInitializationDelegatesForMainScene:transitionContext:] + 3452
35 UIKit                               0x1928f12a8 -[UIApplication _runWithMainScene:transitionContext:completion:] + 1684
36 UIKit                               0x192905de0 __84-[UIApplication _handleApplicationActivationWithScene:transitionContext:completion:]_block_invoke.3151 + 48
37 UIKit                               0x1928ee53c -[UIApplication workspaceDidEndTransaction:] + 168
38 FrontBoardServices                  0x18e0e7884 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 36
39 FrontBoardServices                  0x18e0e76f0 -[FBSSerialQueue _performNext] + 176
40 FrontBoardServices                  0x18e0e7aa0 -[FBSSerialQueue _performNextFromRunLoopSource] + 56
41 CoreFoundation                      0x18c4ed424 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24
42 CoreFoundation                      0x18c4ecd94 __CFRunLoopDoSources0 + 540
43 CoreFoundation                      0x18c4ea9a0 __CFRunLoopRun + 744
44 CoreFoundation                      0x18c41ad94 CFRunLoopRunSpecific + 424
45 UIKit                               0x1926d845c -[UIApplication _run] + 652
46 UIKit                               0x1926d3130 UIApplicationMain + 208
47 Livestar                            0x10022d8e8 main (main.m:6)
48 libcopyfile.dylib                   0x18b42959c (Missing)

--

#0. Crashed: com.apple.main-thread
0  libsystem_info.dylib                0x18b539014 (Missing)
1  libsystem_networkextension.dylib    0x18b603334 (Missing)
2  libcopyfile.dylib                   0x18b4ad9c4 (Missing)
3  Realm                               0x102f2cee0 please_report_this_error_to_help_at_realm_dot_io + 10
4  Realm                               0x102f2d358 realm::util::terminate_internal(std::__1::basic_stringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) + 232
5  libsystem_networkextension.dylib    0x18b603334 (Missing)
6  Realm                               0x102f2d4ec realm::util::terminate(char const*, char const*, long, std::initializer_list<realm::util::Printable>&&) + 388
7  libsystem_networkextension.dylib    0x18b603334 (Missing)
8  Realm                               0x102fdac58 void realm::util::terminate<unsigned long, int, unsigned long, int, unsigned long, int>(char const*, char const*, long, unsigned long, int, unsigned long, int, unsigned long, int) + 98
9  Realm                               0x102fda114 realm::Group::attach(unsigned long, bool) + 188
10 Realm                               0x102fe570c realm::SharedGroup::do_begin_read(realm::VersionID, bool) + 76
11 Realm                               0x102fe4bd4 realm::SharedGroup::begin_read(realm::VersionID) + 36
12 Realm                               0x102ea3d84 realm::Realm::read_group() + 44
13 Realm                               0x102ea35d0 realm::Realm::Realm(realm::Realm::Config, std::__1::shared_ptr<realm::_impl::RealmCoordinator>) + 256
14 Realm                               0x102df82d4 realm::Realm::make_shared_realm(realm::Realm::Config, std::__1::shared_ptr<realm::_impl::RealmCoordinator>)::make_shared_enabler::make_shared_enabler(realm::Realm::Config, std::__1::shared_ptr<realm::_impl::RealmCoordinator>) + 88
15 Realm                               0x102df8084 std::__1::shared_ptr<realm::Realm::make_shared_realm(realm::Realm::Config, std::__1::shared_ptr<realm::_impl::RealmCoordinator>)::make_shared_enabler> std::__1::shared_ptr<realm::Realm::make_shared_realm(realm::Realm::Config, std::__1::shared_ptr<realm::_impl::RealmCoordinator>)::make_shared_enabler>::make_shared<realm::Realm::Config, std::__1::shared_ptr<realm::_impl::RealmCoordinator> >(realm::Realm::Config&&, std::__1::shared_ptr<realm::_impl::RealmCoordinator>&&) + 136
16 Realm                               0x102df477c realm::_impl::RealmCoordinator::get_realm(realm::Realm::Config) + 400
17 Realm                               0x102ea4c50 realm::Realm::get_shared_realm(realm::Realm::Config) + 112
18 Realm                               0x102e883b4 +[RLMRealm realmWithConfiguration:error:] + 584
19 Livestar                            0x100103630 -[LSRealmDataManager setDefaultRealm] (LSRealmDataManager.m:196)
20 Livestar                            0x100102f80 +[LSRealmDataManager manager] (LSRealmDataManager.m:105)
21 Livestar                            0x10040549c -[LSFlowMessageCenter checkIfHasNewFlowMessage] (LSFlowMessageCenter.m:146)
22 Livestar                            0x10040539c -[LSFlowMessageCenter timerBegin] (LSFlowMessageCenter.m:134)
23 Livestar                            0x100305ca0 -[LSMyFlowViewController init] (LSMyFlowViewController.m:66)
24 Livestar                            0x10036fac8 -[LSTabBarController addAllChildVcs] (LSTabBarController.m:88)
25 Livestar                            0x10036f78c -[LSTabBarController viewDidLoad] (LSTabBarController.m:59)
26 UIKit                               0x19279f6c8 -[UITabBarController initWithNibName:bundle:] + 256
27 Livestar                            0x1003353b4 -[AppDelegate setupMainViewController] (AppDelegate.m:225)
28 Livestar                            0x100335294 -[AppDelegate advertisementFinishLaunching] (AppDelegate.m:217)
29 Livestar                            0x1003351c4 __32-[AppDelegate loadAdvertisement]_block_invoke (AppDelegate.m:205)
30 Livestar                            0x1004342b8 -[LSAdvertisementManager shouldLoadAdvertisementWithCompletion:] (LSAdvertisementManager.m:286)
31 Livestar                            0x1003350c8 -[AppDelegate loadAdvertisement] (AppDelegate.m:196)
32 Livestar                            0x100334670 -[AppDelegate application:didFinishLaunchingWithOptions:] (AppDelegate.m:75)
33 UIKit                               0x1926df2dc -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:] + 380
34 UIKit                               0x1928eb800 -[UIApplication _callInitializationDelegatesForMainScene:transitionContext:] + 3452
35 UIKit                               0x1928f12a8 -[UIApplication _runWithMainScene:transitionContext:completion:] + 1684
36 UIKit                               0x192905de0 __84-[UIApplication _handleApplicationActivationWithScene:transitionContext:completion:]_block_invoke.3151 + 48
37 UIKit                               0x1928ee53c -[UIApplication workspaceDidEndTransaction:] + 168
38 FrontBoardServices                  0x18e0e7884 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 36
39 FrontBoardServices                  0x18e0e76f0 -[FBSSerialQueue _performNext] + 176
40 FrontBoardServices                  0x18e0e7aa0 -[FBSSerialQueue _performNextFromRunLoopSource] + 56
41 CoreFoundation                      0x18c4ed424 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24
42 CoreFoundation                      0x18c4ecd94 __CFRunLoopDoSources0 + 540
43 CoreFoundation                      0x18c4ea9a0 __CFRunLoopRun + 744
44 CoreFoundation                      0x18c41ad94 CFRunLoopRunSpecific + 424
45 UIKit                               0x1926d845c -[UIApplication _run] + 652
46 UIKit                               0x1926d3130 UIApplicationMain + 208
47 Livestar                            0x10022d8e8 main (main.m:6)
48 libcopyfile.dylib                   0x18b42959c (Missing)

#1. Thread
0  libsystem_networkextension.dylib    0x18b5fed78 (Missing)

#2. Thread
0  libsystem_info.dylib                0x18b539a88 (Missing)
1  libsystem_networkextension.dylib    0x18b5ff274 (Missing)
2  libsystem_networkextension.dylib    0x18b5fed7c (Missing)

#3. Thread
0  libsystem_info.dylib                0x18b539a88 (Missing)
1  libsystem_networkextension.dylib    0x18b5ff274 (Missing)
2  libsystem_networkextension.dylib    0x18b5fed7c (Missing)

#4. com.apple.uikit.eventfetch-thread
0  libsystem_info.dylib                0x18b51b224 (Missing)
1  libsystem_info.dylib                0x18b51b09c (Missing)
2  CoreFoundation                      0x18c4ece88 __CFRunLoopServiceMachPort + 192
3  CoreFoundation                      0x18c4eaadc __CFRunLoopRun + 1060
4  CoreFoundation                      0x18c41ad94 CFRunLoopRunSpecific + 424
5  Foundation                          0x18cf34d64 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 304
6  Foundation                          0x18cf55b34 -[NSRunLoop(NSRunLoop) runUntilDate:] + 96
7  UIKit                               0x19305d5f8 -[UIEventFetcher threadMain] + 136
8  Foundation                          0x18d0322c8 __NSThread__start__ + 996
9  libsystem_networkextension.dylib    0x18b60175c (Missing)
10 libsystem_networkextension.dylib    0x18b60166c (Missing)
11 libsystem_networkextension.dylib    0x18b5fed84 (Missing)

#5. Thread
0  libsystem_info.dylib                0x18b539a88 (Missing)
1  libsystem_networkextension.dylib    0x18b5ff274 (Missing)
2  libsystem_networkextension.dylib    0x18b5fed7c (Missing)

#6. com.twitter.crashlytics.ios.binary-images
0  libsystem_info.dylib                0x18b51cca4 (Missing)
1  Livestar                            0x100816254 __CLSFileWriteWithRetries_block_invoke + 844256
2  Livestar                            0x100816194 CLSFileLoopWithWriteBlock + 844064
3  Livestar                            0x100816444 CLSFileWriteToFileDescriptorOrBuffer + 844752
4  Livestar                            0x100816718 CLSFileWriteCollectionStart + 845476
5  Livestar                            0x10081661c CLSFileWriteSectionStart + 845224
6  Livestar                            0x1007fec10 __CLSBinaryImageChanged_block_invoke + 748444
7  libcopyfile.dylib                   0x18b3f69e0 (Missing)
8  libcopyfile.dylib                   0x18b3f69a0 (Missing)
9  libcopyfile.dylib                   0x18b404ad4 (Missing)
10 libcopyfile.dylib                   0x18b3fa2cc (Missing)
11 libcopyfile.dylib                   0x18b404fa8 (Missing)
12 libcopyfile.dylib                   0x18b406a50 (Missing)
13 libcopyfile.dylib                   0x18b4067d0 (Missing)
14 libsystem_networkextension.dylib    0x18b5ff1d0 (Missing)
15 libsystem_networkextension.dylib    0x18b5fed7c (Missing)

#7. Thread
0  libsystem_info.dylib                0x18b539a88 (Missing)
1  libsystem_networkextension.dylib    0x18b5ff274 (Missing)
2  libsystem_networkextension.dylib    0x18b5fed7c (Missing)

#8. com.twitter.crashlytics.ios.MachExceptionServer
0  libsystem_info.dylib                0x18b51b224 (Missing)
1  libsystem_info.dylib                0x18b51b09c (Missing)
2  Livestar                            0x100802700 CLSMachExceptionServer + 763532
3  libsystem_networkextension.dylib    0x18b60175c (Missing)
4  libsystem_networkextension.dylib    0x18b60166c (Missing)
5  libsystem_networkextension.dylib    0x18b5fed84 (Missing)

#9. com.apple.NSURLConnectionLoader
0  libsystem_info.dylib                0x18b51b224 (Missing)
1  libsystem_info.dylib                0x18b51b09c (Missing)
2  CoreFoundation                      0x18c4ece88 __CFRunLoopServiceMachPort + 192
3  CoreFoundation                      0x18c4eaadc __CFRunLoopRun + 1060
4  CoreFoundation                      0x18c41ad94 CFRunLoopRunSpecific + 424
5  CFNetwork                           0x18cc26ca4 +[NSURLConnection(Loader) _resourceLoadLoop:] + 404
6  Foundation                          0x18d0322c8 __NSThread__start__ + 996
7  libsystem_networkextension.dylib    0x18b60175c (Missing)
8  libsystem_networkextension.dylib    0x18b60166c (Missing)
9  libsystem_networkextension.dylib    0x18b5fed84 (Missing)

#10. Thread
0  libsystem_info.dylib                0x18b539a88 (Missing)
1  libsystem_networkextension.dylib    0x18b5ff274 (Missing)
2  libsystem_networkextension.dylib    0x18b5fed7c (Missing)

#11. Thread
0  libsystem_info.dylib                0x18b539a88 (Missing)
1  libsystem_networkextension.dylib    0x18b5ff274 (Missing)
2  libsystem_networkextension.dylib    0x18b5fed7c (Missing)

#12. Thread
0  libsystem_info.dylib                0x18b539a88 (Missing)
1  libsystem_networkextension.dylib    0x18b5ff274 (Missing)
2  libsystem_networkextension.dylib    0x18b5fed7c (Missing)

#13. Thread
0  libsystem_networkextension.dylib    0x18b5fed78 (Missing)

#14. Thread
0  libsystem_info.dylib                0x18b539a88 (Missing)
1  libsystem_networkextension.dylib    0x18b5ff274 (Missing)
2  libsystem_networkextension.dylib    0x18b5fed7c (Missing)

**Comment by austinzheng** [comment] 2017-05-09 18:13
Thanks for reporting your stack trace. What version of Realm are you using, what was the app doing when it crashed, and is there any possibility of providing us with a reproduction case? We'll need more information to investigate the issue.

**Comment by stel** [comment] 2017-05-15 13:10
@piaotairen could you please provide the request info or let us know if we can close this issue, thanks!

**Comment by austinzheng** [comment] 2017-06-01 18:32
I'm going to close this ticket since it hasn't been touched for a while. If you have further questions please feel free to file new tickets against us.

**Closed by austinzheng** 2017-06-01 18:32 UTC
Labels: S:Waiting For User, T:Help
