### ISSUE TITLE
-Wdocumentation flag is producing hundreds of warnings

### ISSUE THREAD

**Issue by generalpf** [realm/realm-cocoa#4995] opened 2017-06-02 13:39 UTC
## Goals
Realm compiles with the `-Wdocumentation` flag (corresponding to Xcode's "Documentation Comments" option), which is good, and it _has_ clang documentation, but it's very frequently wrong. This results in hundreds of warnings like this:

```
    ⚠ Pods/Realm/include/core/realm/array.hpp:[539,16] did you mean 'end'?
    »     /// \param indirection an \c Array containing valid indices of values in
    »                ^~~~~~~~~~~
    ⚠ Pods/Realm/include/core/realm/util/buffer.hpp:[86,16] parameter 'copy_begin,' not found in the function declaration [-Wdocumentation]
    »     /// \param copy_begin, copy_end Specifies a range of element
    »                ^~~~~~~~~~~
    ⚠ Pods/Realm/include/core/realm/util/buffer.hpp:[86,16] did you mean 'copy_begin'?
    »     /// \param copy_begin, copy_end Specifies a range of element
    »                ^~~~~~~~~~~
```

## Expected Results
I expect that either Realm would compile cleanly, without these warnings.

## Actual Results
Realm compiles with hundreds of warnings.

## Steps to Reproduce
Compile the CocoaPod.

## Version of Realm and Tooling
Realm framework version: 2.7.0
Xcode version: 8.3.2
Dependency manager + version: CocoaPods 1.2.1

**Comment by generalpf** [comment] 2017-06-02 13:50
By the way, if this is bothering anyone else, add this to the end of `Podfile`:

```
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['CLANG_WARN_DOCUMENTATION_COMMENTS'] = 'NO'
        end
    end

    installer.pods_project.build_configurations.each do |config|
        config.build_settings['CLANG_WARN_DOCUMENTATION_COMMENTS'] = 'NO'
    end
end
```

**Comment by jpsim** [comment] 2017-06-02 15:55
Duplicate of #4853, we'll release a version with a fix shortly.

**Closed by jpsim** 2017-06-02 15:55 UTC
