### ISSUE TITLE
Exception handling broken after adding Realm to project

### ISSUE THREAD

**Issue by ndonald2** [realm/realm-cocoa#2012] opened 2015-05-27 02:23 UTC
### Goals

To add Realm to a project (using CocoaPods) without breaking unit tests.

### Expected Results

Adding Realm to the project (and doing nothing more) should not change the application or unit tests.

### Actual Results

After adding Realm, the following warning shows up when compiling:

`ld: warning: too many personality routines for compact unwind to encode`

The app behaves normally, but there is an issue with some of our unit tests, specifically the ones that assert that exceptions are thrown. They all work on 64-bit simulators, but on 32-bit simulators (iPhone 4S, iPhone 5) exception handling is broken so *any* exception thrown during unit testing will cause a crash.

This [Apple Developer Forums](https://devforums.apple.com/message/1132535#1132535) thread suggests that it may be a bug in the developer tools and that rebuilding any pre-built binaries with the latest tools may resolve the issue.

### Steps to Reproduce

I attempted to reproduce the issue in isolation but was unable to do so. [This answer](http://stackoverflow.com/a/29653008/1128820) suggests that the personality routine problem occurs when the binary has too many forms of exception handling, possibly having been linked from several other pre-built binaries. See the list of other installed CocoaPods in the project below to get an idea of what else is in our app.

### Code Sample

I haven't yet been able to reproduce this in isolation and I can't expose my company's proprietary codebase where it is reproducible. If I am able to reproduce it I will upload the example.

### Environment

Realm 0.92.4
Xcode 6.3.1
OSX 10.10.3
Built against iOS 8.3, targeting iOS 8.1 or later

Other installed pods: 
- Google Analytics ~> 3.0
- Mixpanel ~> 2.6
- HockeyApp ~> 3.0
- Masonry ~> 0.6
- ReactiveCocoa ~> 2.0
- CocoaLumberjack ~> 1.0
- Kiwi ~> 2.0 (for unit test target)

**Comment by ndonald2** [comment] 2015-05-27 13:31
I should also mention that we have a rather large internal c++ library linked into the app, which is likely contributing to the variety of types of exception handling. That said, prior to adding Realm, we were not getting this warning.

**Comment by segiddins** [comment] 2015-05-27 16:06
@ndonald2 unfortunately, this is a limitation of the way C++ exception handling is done on Itanium-like CPUs. It uses something called a compact unwind table, which has an upper bound on the number of different exception paths it can handle in a single binary. [This StackOverflow question](http://stackoverflow.com/questions/21150223/ld-warning-too-many-personality-routines-for-compact-unwind-to-encode) has some good answers on _why_ this is happening, but the long story short is that, on 32-bit iOS, there's a limitation on the amount of different exception code paths the linker can handle. Your hunch is likely correct, in that it's the combination of Realm and your internal C++ library that's putting things over the limit. Unfortunately, there's not really anything we can do about this -- its an underlying platform limitation.

**Comment by ndonald2** [comment] 2015-05-27 16:58
Thanks for the info. It's worth noting that when I build in Xcode 6.2, this issue does not manifest at all, so it seems to be related to the current dev tools release, not some intrinsic limitation.

Is the static library distributed with the Realm Cocoapods release built in 6.3 or 6.2? The internal C++ library we are using is built with 6.3, but I could also try building it with 6.2 before linking in 6.3.

The dev forum post by the Apple dev support agent suggests that this will go away in the next Xcode 6.4 beta, so I may try that as well.

**Comment by segiddins** [comment] 2015-05-27 17:01
@tgoyne do you know with which version of Xcode CI is building the Core releases with?

**Comment by tgoyne** [comment] 2015-05-27 17:06
The core OS X slave is running 10.9, so it's built with some pre-6.3 version. Compiler versions being tied to OS releases is wonderful.

**Comment by ndonald2** [comment] 2015-05-27 17:09
I just verified that building our own c++ libs with Xcode 6.2 and then building the app and linking the lib with 6.3 does resolve the issue. Hopefully Xcode 6.4 will resolve the issue so that it no longer matters, but this solves my problem in the short term.

Thanks for you help!

**Comment by ndonald2** [comment] 2015-05-27 17:11
Scratch that. Still broken for 32-bit.

**Comment by ndonald2** [comment] 2015-05-27 17:27
There are no issues in Xcode 6.4 beta 4. So for now I guess it's a matter of patience - chances are we won't ship the app before 6.4 is released.

**Comment by jpsim** [comment] 2015-05-27 18:03
I'm closing this issue as the issue isn't specific to Realm and a fix is coming in a future version of Xcode.

**Closed by jpsim** 2015-05-27 18:03 UTC

**Comment by tgoyne** [comment] 2015-05-27 18:26
Could you try building with 6.3 and https://static.realm.io/downloads/temp/core-xcode-6.3-0.89.4.zip in place of the automatically downloaded copy of the core library? It should be identical other than being built with Xcode 6.3, and if that does solve the problem it's worth spending the time upgrading the CI slave.

**Comment by ndonald2** [comment] 2015-05-28 20:18
@tgoyne Nope, same issue with that library file. It's all Xcode's fault I'm afraid.
