### ISSUE TITLE
Add subclassed object to RLMArray property

### ISSUE THREAD

**Issue by depl0y** [realm/realm-cocoa#1718] opened 2015-04-01 17:28 UTC
I have a question, which I can't seem to figure out at the moment, while I can think of work-arounds for this problem, there might be a more official solution to this.

For example, I have a class called `Base`, which is subclassing `RLMObject`. I then create a subclass of this `Base` class called `SubclassedBase`. So I should have something like this:

```
class Base: RLMObject {
}

class SubclassedBase: Base {
}
```

Now I create another class, which will contain a one-to-many relation to the `Base` class:

```
class Parent: RLMObject {
  dynamic var bases = RLMArray(objectClassName: Base.className());
}
```

Now when I try to add a `SubclassedBase` object to this array it crashes with an exception that I am trying to store the wrong kind of object in the `RLMArray`, which, of course, is kind of obvious. 

Is there a simple solution for this that I am completely missing? In my real project there are more than one subclasses of `Base`, otherwise I could have just changed the definition of the `bases` property to accept `SubclassedBase`.

In my datamodel I use primary keys, so maybe I should store primary keys and fetch the object by it's key, but I don't think there is a way to query ALL tables for a record with this primary key.

**Comment by segiddins** [comment] 2015-04-01 17:58
@depl0y at the moment, Realm does not support that kind of polymorphism, since each entity type is stored in its own table.

**Comment by tgoyne** [comment] 2015-04-01 18:29
We're planning to add support for link and array properties which can link to more than one table along with support for querying multiple tables at once so that inheritance can be fully functional, but it'll probably be a while off.

The workaround we usually recommend for now is something like the following:

```swift
class Base: RLMObject {
}

class SubclassOne: Base {
}

class SubclassTwo: Base {
}

class Union: RLMObject {
  dynamic var base: Base? = nil
  dynamic var one: Base? = nil
  dynamic var two: Base? = nil
}

class Parent: RLMObject {
  dynamic var bases = RLMArray(objectClassName: Union.className());
}

let obj = SubclassOne(...)
let wrapper = Union()
wrapper.one = obj
parentObj.bases.addObject(wrapper)
```

**Comment by jpsim** [comment] 2015-04-01 19:40
Closing as a duplicate of #1109.

**Closed by jpsim** 2015-04-01 19:40 UTC

**Comment by depl0y** [comment] 2015-04-02 05:00
@segiddins thanks, that was I was encountering. It's good to have this confirmed.

@tgoyne Your solution actually doesn't work, with the same error. Once you assign a `SubclassOne` to `wrapper.one`, the same error occurs. But I think you didn't mean to make the types of `one` and `two` `Base`, but probably `SubclassOne` and SubclassTwo`. After that is changed this should work.
