### ISSUE TITLE
Find memory leak.

### ISSUE THREAD

**Issue by TheHmmka** [realm/realm-cocoa#3343] opened 2016-03-18 07:16 UTC
## Code Sample

RLMResults<Item*>* items = [Item objectsWhere: queryString];

## Version of Realm and Tooling

Objective-C
Realm: 0.98.5
XCode: 7.2.1 (7C1002)
MacOS: 10.10.5 (14F1605)

<img width="1280" alt="screenshot 2016-03-18 10 11 18" src="https://cloud.githubusercontent.com/assets/468660/13871027/388511ec-ecf2-11e5-8ed8-e18d483d0dfe.png">

<img width="1280" alt="screenshot 2016-03-18 10 13 03" src="https://cloud.githubusercontent.com/assets/468660/13871039/4f63453c-ecf2-11e5-9889-c30432407236.png">

<img width="1280" alt="screenshot 2016-03-18 10 13 33" src="https://cloud.githubusercontent.com/assets/468660/13871045/58bf1cd2-ecf2-11e5-864b-16f3dfb315ad.png">

<img width="1280" alt="screenshot 2016-03-18 10 13 43" src="https://cloud.githubusercontent.com/assets/468660/13871050/62540cf8-ecf2-11e5-8bc1-6387fac57843.png">

**Comment by jpsim** [comment] 2016-03-29 01:54
@TheHmmka sorry for the late reply, could you please share a more complete code sample and reproduction steps that highlights this memory leak? The `RLMResults* items = [Item objectsWhere: queryString];` you've shared is insufficient. For example, what's the `queryString`? Also, what's the model definition for your `Item` model? Without these, it's impossible for us to tell what's causing this memory leak.

**Comment by k-o-d-e-n** [comment] 2016-04-14 20:01
I have this problem.
![screen shot 2016-04-14 at 15 51 34](https://cloud.githubusercontent.com/assets/18463658/14541636/94497b74-0293-11e6-9420-38c970d3daac.png)
![screen shot 2016-04-14 at 15 55 43](https://cloud.githubusercontent.com/assets/18463658/14541656/a477a796-0293-11e6-8172-1615cf2fc795.png)

**Comment by jpsim** [comment] 2016-04-14 21:01
Going to mark this one as a duplicate of #3270. Please help us find reproduction steps for the leak there. Thanks!

**Closed by jpsim** 2016-04-14 21:01 UTC
Labels: T:Help
