### ISSUE TITLE
A Results made from link query has wrong results after deleting the right-hand side object of the condition.

### ISSUE THREAD

**Issue by kishikawakatsumi** [realm/realm-cocoa#2782] opened 2015-11-02 23:12 UTC
A Results made from link query has wrong results after deleting the right-hand side object of the condition. It occurs because the row index is changed unintentionally.

Steps to reproduce.

- Define following two models, `Dog` and `Person`. `Dog` has `Person` as `owner` property:

```swift
class Person: Object {
    dynamic var name = ""
}

class Dog: Object {
    dynamic var name = ""
    dynamic var owner: Person?
}
```
- Save two `Dog` objects, each objects has `person` objects as `owner` like following:

```swift
let person1 = Person()
person1.name = "person1"
let person2 = Person()
person2.name = "person2"

let dog1 = Dog()
dog1.owner = person1
let dog2 = Dog()
dog2.owner = person2

try! realm.write { () -> Void in
    realm.add(dog1)
    realm.add(dog2)
}
```

- Query for the `Dog` that has `person1` as `owner`.

```swift
let results = realm.objects(Dog).filter("owner = %@", person1)
print(results) // Returns `dog1`
```

The query returns `dog1`, then delete `person`.

```swift
try! realm.write { () -> Void in
    realm.delete(person1)
}
print(results) // Returns `dog2`
```

Now the `results` has `dog2`. An expected result is to return empty.

cc/ @jpsim @bdash

**Comment by tgoyne** [comment] 2015-11-02 23:18
Same as https://github.com/realm/realm-core/issues/811?

**Comment by kishikawakatsumi** [comment] 2015-11-02 23:35
Yes, I forgot to mention it.

If this problem is not fixed for a while, I think it should be documented not to hold Results object made by link query beyond method scope. And recommend workaround, for example, use primary key on the right-hand side instead an object. Will you let me know what you think about it?

**Comment by astigsen** [comment] 2015-11-03 00:11
The object gets deleted, so the query is not really valid anymore (what does it mean to search for a non-exiting object?). We should have some way to detect that is happening and invalidating the query.

**Comment by tgoyne** [comment] 2015-11-03 00:13
> what does it mean to search for a non-exiting object?

It seems perfectly sensible to me for that to just return zero results. Why does that not make sense?

**Comment by kishikawakatsumi** [comment] 2015-11-03 00:27
@astigsen 

> The object gets deleted, so the query is not really valid anymore

If there are three or more objects, even if you delete the objects without any relation to the query, the result will be wrong.

For example, add `person3` to above code:

```
let person1 = Person()
person1.name = "person1"
let person2 = Person()
person2.name = "person2"
let person3 = Person()
person3.name = "person3"

let dog1 = Dog()
dog1.owner = person1
let dog2 = Dog()
dog2.owner = person2
let dog3 = Dog()
dog3.owner = person3

try! realm.write { () -> Void in
    realm.add(dog1)
    realm.add(dog2)
    realm.add(dog3)
}
```

Query for `person3` object,

```
let results = realm.objects(Dog).filter("owner = %@", person3)
print(results) // Returns `dog3`
```

Then delete `person1` object, the results will be empty unexpectedly. Because the row index has shifted.

```
try! realm.write { () -> Void in
    realm.delete(person1)
}
print(results) // Returns empty!!
```

**Comment by astigsen** [comment] 2015-11-03 01:21
> It seems perfectly sensible to me for that to just return zero results. Why does that not make sense?

That would make sense for me as well. I guess it should just be treated as if the value was nil.

> If there are three or more objects, even if you delete the objects without any relation to the query, the result will be wrong. ... Because the row index has shifted.

We probably have to treat queries involving object ids as accessors, so that they get updated when objects move.

**Comment by vigonius** [comment] 2015-12-02 22:55
2782, 811, and 1847 all point to the same issue. I'm working on it and should have resolution be EOB Friday.

**Comment by vigonius** [comment] 2015-12-02 23:05
#2782 and #1847 all point to the same issue. I'm working on it and should have resolution be EOB Friday.

**Comment by jpsim** [comment] 2015-12-15 23:58
I'm closing this issue as a duplicate of #1803.

**Closed by jpsim** 2015-12-15 23:58 UTC
Labels: backlog, bug
