### ISSUE TITLE
"UITableView: The number of rows contained in an existing section..."

### ISSUE THREAD

**Issue by crrobinson14** [realm/realm-cocoa#4244] opened 2016-10-20 23:31 UTC
I'm trying to track down a very frustrating crash using the latest Realm as of a few weeks ago (not up to the minute, but the CHANGELOG doesn't mention any changes here).

Here's the error - we've all see this one and we know its causes:

`Invalid update: invalid number of rows in section 0.  The number of rows contained in an existing section after the update (195) must be equal to the number of rows contained in that section before the update (194), plus or minus the number of rows inserted or deleted from that section (48 inserted, 48 deleted) and plus or minus the number of rows moved into or out of that section (0 moved in, 0 moved out).`

Here's a summary of what I have set up. It's super vanilla:
1. `RLMResults *myResults = [MyClass allObjects]`;
2. UITableViewDataSource returning `myResults.count` for `numberOfRowsInSection`.
3. UITableViewDataSource returning `configureACell(myResults[indexPath.row])` for `cellForRowAtIndexPath`.
4. Strong reference taken to `RLMNotificationToken *myToken = ...` with the `begin/delete/insert/update/commit` code sequence precisely as outlined in https://realm.io/docs/objc/latest/#collection-notifications, even the same order.

Now, I have a WebSocket connection to a server with new data to draw arriving on that connection. That connection writes a new row to the table in a background thread managed by SRWebSocket.

99% of the time this works. The trouble is SOMETIMES when an update comes in I get the error above and the app crashes. It SEEMS to happen more when the updates are coming quickly, but that's just a suspicion. I have so far been unable to reproduce it on-demand to test fixes/workarounds, but it definitely happens enough to be driving our users nuts.

I caught the one above in the debugger and managed to check the original `myResults.count` (194) against the notification block's `results.count` (also 194). So the two base data sets look to be in sync. The most likely explanation is a race condition somewhere, but I'm at a loss on next steps. Any ideas where to even begin looking?

**Comment by tgoyne** [comment] 2016-10-26 17:41
The `tg/changeset-skip` branch may fix this. There's some race conditions on `master` that have been resolved there, so if you're mostly seeing issues when there's a lot of updates then it seems likely that those are the cause.

**Comment by jpsim** [comment] 2016-11-09 23:49
@crrobinson14 have you had the chance to see if the `tg/changeset-skip` branch resolved your issue?

**Comment by crrobinson14** [comment] 2016-11-10 00:06
Sorry, I missed this update while posting #4260. I'll try this tomorrow and get back to you.

**Comment by crrobinson14** [comment] 2016-11-10 04:56
@jpsim this branch doesn't actually build for me. I get an error in RLMCollection.mm `"No member named 'suppress_next' in realm::NotificationToken"`. I'm installing this via CocoaPods via:

`  pod 'Realm', :git => 'https://github.com/realm/realm-cocoa.git', :branch => 'tg/changeset-skip', :submodules => true`

Should I be using a different option?

**Comment by jpsim** [comment] 2016-11-10 18:35
That branch is under active development, so it's possible it may not compile at times.

**Comment by jpsim** [comment] 2016-11-18 22:01
@crrobinson14 were you ever able to build with that branch? Note that the `tg/changeset-skip` branch has now been deleted and merged to `master` in #4253, as of a few minutes ago.

We'll be cutting a release including those fixes and features shortly. I'd love to hear if that addresses the issues you've been seeing.

**Comment by crrobinson14** [comment] 2016-11-18 22:21
I was never able to build the side branch but I'll definitely try master over the weekend.

**Comment by jpsim** [comment] 2016-11-18 22:22
👌

**Comment by jpsim** [comment] 2016-12-07 02:03
Closing since I suspect 2.1.0 or 2.1.1 fixed this as the situation seems similar to other cases confirmed fixed, and we haven't heard back from @crrobinson14 in a few weeks.

**Closed by jpsim** 2016-12-07 02:03 UTC
Labels: S:Waiting For User, T:Help
