### ISSUE TITLE
Support in RLMArray for basic types (int, strings, etc)

### ISSUE THREAD

**Issue by maxgoedjen** [realm/realm-cocoa#1312] opened 2015-01-09 07:51 UTC
It'd be awesome if `RLMArray` supported the types `RLMObject` does (or just plain `NSArray`/Swift `Array` types for basic types), for use cases like this:

```
{
"id": "1234",
"name": "test",
"tags": ["one", "two", "three"]
}
```

**Comment by segiddins** [comment] 2015-04-01 19:49
Closing as a duplicate of https://github.com/realm/realm-cocoa/issues/1120.

**Closed by segiddins** 2015-04-01 19:49 UTC
Labels: backlog
