### ISSUE TITLE
Unexpected migration results after changing property's optionality

### ISSUE THREAD

**Issue by njuri** [realm/realm-cocoa#6008] opened 2018-11-19 12:27 UTC
## Goals
I noticed that sometimes my app loses data after updating to the new version. I was able to narrow down the problem - the data gets lost only on updates when I change the structure of the data - I change the schema version and the migration is performed. But the issue turned out to be that automatic migration doesn't behave the way I would expect.

Let's say we have a following class:

```
class User : Object {
  @objc dynamic var id : Int = -1
  @objc dynamic var name : String?
  
  override public static func primaryKey() -> String? {
    return "id"
  }
}
```

More specifically we've got a property `name` which is optional String (`String?`). And let's say we have two users: first with name "John" and the other being without a name (`nil`).

We decided to change it to just `String` with provided default value, in this case an empty string. So the updated class would look like this:

```
class User : Object {
  @objc dynamic var id : Int = -1
  @objc dynamic var name : String = ""
  
  override public static func primaryKey() -> String? {
    return "id"
  }
}
```

We increase the schema version and rerun the app to perform a migration.

## Expected Results

First user's name hasn't changed, the second user's name was replaced by an empty string.

## Actual Results

Both users' names are replaced by empty strings.

## Code Sample

I have created a [sample project](https://github.com/njuri/realm-migration-test) with described class.

### Steps to Reproduce

Change `User` object's `name` property from being optional `String?` to `String` with default value.

**From:**

    @objc dynamic var name : String?

**To:**

    @objc dynamic var name : String = ""

And rerun the app, you'll see that both object's names were replaced by the default value (in this case an empty string).

## Version of Realm and Tooling

Realm framework version: 3.11.2

Xcode version: 10.1 (10B61)

macOS version: 10.14.1

Dependency manager + version: Carthage 0.31.2

## Thoughts

It might be asking too much for automatic migration to perform such "migration" I would expect, but I think it could be much better if Realm would've shown at least some kind of warning that you are changing types of _existing_ properties which will cause data loss, so manual migration is required to prevent it.

**Comment by MattCarr147** [comment] 2018-11-20 09:14
Hi @njuri - I've recently questioned this behaviour on an older, related, case. You may find the comments in #4370 useful whilst waiting for a response to this one.

**Comment by stennie** [comment] 2019-09-29 22:31
This appears to be a duplicate of the behaviour discussed in #4370.

**Closed by stennie** 2019-09-29 22:31 UTC
Labels: O-Community, T-Duplicate
