### ISSUE TITLE
LLDB hangs when debugging an application that is using an encrypted Realm.

### ISSUE THREAD

**Issue by anlaital** [realm/realm-cocoa#1625] opened 2015-03-13 04:42 UTC
LLDB hangs in Xcode 6.2 when stepping (or continuing) through code in a project that has accessed an encrypted Realm in any way. The hang occurs even when you are not stepping over Realm statements. This is very easy to reproduce and happens every time, thus making debugging applications using encrypted Realms impossible.

I have also sent you a project to reproduce this issue with.

**Comment by tgoyne** [comment] 2015-03-19 16:34
The issue appears to be the debug view causing reads that need the exception handler thread to be running. I think it might be possible to fix this with some python scripting.

**Comment by alazier** [comment] 2015-03-27 20:34
Is this still the case with the latest encryption fixes?

**Comment by tgoyne** [comment] 2015-03-27 20:34
Yes.

**Comment by anlaital** [comment] 2015-04-06 08:25
Is there any eta on fixing this as it's making development using encrypted Realms entirely impossible?

**Comment by puttin** [comment] 2015-04-16 02:46
Realm 0.91.1 with LLDB in Xcode 6.3 still

**Comment by jpsim** [comment] 2015-04-17 01:11
@anlaital sorry for the late reply, no ETA on this just yet.

You're welcome to take a look at the current implementation of the LLDB script (https://github.com/realm/realm-cocoa/blob/master/plugin/rlm_lldb.py) to see if there's anything that could be changed to work around this issue in there. I believe it's possible to do so in there.

However, it's likely that a proper fix would involve making some changes to our signal handler, which is in our closed source core, so someone from our team will have to look into that.

**Comment by tgoyne** [comment] 2015-04-17 02:03
There's nothing that can be done to fix this in the core for ios. The problem is that local variables show up in the debug view before they're actually in scope and generally contain garbage. When they're pointer variables, this results in lldb trying to read an invalid address, and generating a mach exception... which gets delivered to an exception handler running on a paused thread, and lldb deadlocks. On OS X we could theoretically use an out-of-process exception handler to avoid having it get paused, but that's not possible on non-jailbroken ios.

My idea for getting it to work via python scripting is to just have the script automatically resume the exception handler thread every time the debugger breaks. I'm not sure if this is actually possible.

**Comment by bdash** [comment] 2015-05-06 16:41
I don't believe it's possible to script around this issue. LLDB does provide for stop hooks that are triggered every time the debugger breaks, however it doesn't appear to be possible to resume a single thread within this context from a script without resuming the entire process. The deadlock happens when LLDB attempts to compute the description of a local Objective-C object that isn't a pointer to valid memory. During this evaluation LLDB resumes only a single thread at a time to attempt to compute the result. You can see where this happens in the LLDB source in [AppleObjCRuntime.cpp](https://github.com/llvm-mirror/lldb/blob/master/source/Plugins/LanguageRuntime/ObjC/AppleObjCRuntime/AppleObjCRuntime.cpp#L149-L154). Having only a single thread running guarantees that this will deadlock in cases where the exception handler thread needs to execute in order for the evaluation to proceed.

**Comment by bdash** [comment] 2015-05-06 19:11
The long-term fix for this requires core to move away from using a mach exception handler. The only reliable short-term workaround I've found for the hang is to disable debugging of applications using encrypted realms.

**Closed** 2015-05-07 03:49 UTC
Labels: bug, P1

**Comment by timanglade** [comment] 2015-05-08 04:23
@bdash We need to update [the relevant docs section](http://realm.io/docs/swift/latest/#debugging-encrypted-realms) in light of your findings. Can you submit a PR to the docs?
