### ISSUE TITLE
error Error itms-90035

### ISSUE THREAD

**Issue by shmidt** [realm/realm-cocoa#1887] opened 2015-05-08 20:54 UTC
After uploading build to iTC I get an error:

![screen shot 2015-05-08 at 23 38 34](https://cloud.githubusercontent.com/assets/1472370/7545283/20eb202e-f5dd-11e4-9cfe-0bda500840da.png)

I installed RealmSwift with Carthage.

That's how runscript looks:
![screen shot 2015-05-08 at 23 52 51](https://cloud.githubusercontent.com/assets/1472370/7545310/69b78bee-f5dd-11e4-8eee-a30e2cd975ee.png)

How can I fix it?

**Comment by segiddins** [comment] 2015-05-08 21:07
This issue is a duplicate of https://github.com/realm/realm-cocoa/issues/1865. @shmidt, could you check if https://github.com/realm/realm-cocoa/pull/1866 fixes things for you?

**Closed** 2015-05-08 21:07 UTC

**Comment by jpsim** [comment] 2015-05-08 21:13
Also, you shouldn't need to run `strip-frameworks.sh` in your run script, as that's already covered by `carthage copy-frameworks`.

**Comment by shmidt** [comment] 2015-05-09 18:20
@segiddins No, unfortunately v0.92.2 doesn't fix it. I installed it with Carthage and later manually, but result is till the same.
