### ISSUE TITLE
I found a crash when I use realm in my app

### ISSUE THREAD

**Issue by Mingmingmew** [realm/realm-cocoa#5441] opened 2017-10-31 05:17 UTC
## Goals

Resolve the craash
## Expected Results

Resolve the craash
## Actual Results

0 libobjc.A.dylib | objc_retain + 16
-- | --
**The first type of crash**
```
1 XChat | RLMObservationInfo::didChange(NSString*, NSKeyValueChange, NSIndexSet*) const (RLMObservation.hpp:121)
2 XChat | RLMDidChange(std::__1::vector<realm::BindingContext::ObserverState, std::__1::allocator<realm::BindingContext::ObserverState> > const&, std::__1::vector<void*, std::__1::allocator<void*> > const&) (RLMObservation.mm:493)
3 XChat | (anonymous namespace)::RLMNotificationHelper::did_change(std::__1::vector<realm::BindingContext::ObserverState, std::__1::allocator<realm::BindingContext::ObserverState> > const&, std::__1::vector<void*, std::__1::allocator<void*> > const&, bool) (RLMRealmUtil.mm:117)
4 XChat | (anonymous namespace)::KVOTransactLogObserver::~KVOTransactLogObserver() (transact_log_handler.cpp:230)
5 XChat | realm::_impl::transaction::advance(std::__1::unique_ptr<realm::SharedGroup, std::__1::default_delete<realm::SharedGroup> > const&, realm::BindingContext*, realm::_impl::NotifierPackage&) (memory:2581)
6 XChat | realm::_impl::RealmCoordinator::advance_to_ready(realm::Realm&) (realm_coordinator.cpp:0)
7 XChat | realm::Realm::notify() (shared_realm.cpp:755)
8 XChat | realm::_impl::WeakRealmNotifier::Callback::operator()() const (memory:4626)
9 CoreFoundation | ___CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24
10 CoreFoundation | ___CFRunLoopDoSources0 + 524
11 CoreFoundation | ___CFRunLoopRun + 804
12 CoreFoundation | CFRunLoopRunSpecific + 444
13 GraphicsServices | GSEventRunModal + 180
14 UIKit | -[UIApplication _run] + 684
15 UIKit | UIApplicationMain + 208
16 XChat | main (main.m:14)
17 libdyld.dylib | _start + 4
```
**The second type of crash**
```
0 XChat | RLMClassInfo::propertyForTableColumn(unsigned long) const (RLMClassInfo.mm:49)
-- | --
1 XChat | RLMObservationInfo::columnName(unsigned long) const (RLMObservation.mm:0)
2 XChat | RLMObservationInfo::columnName(unsigned long) const (RLMObservation.mm:0)
3 XChat | RLMDidChange(std::__1::vector<realm::BindingContext::ObserverState, std::__1::allocator<realm::BindingContext::ObserverState> > const&, std::__1::vector<void*, std::__1::allocator<void*> > const&) (RLMObservation.mm:493)
4 XChat | (anonymous namespace)::RLMNotificationHelper::did_change(std::__1::vector<realm::BindingContext::ObserverState, std::__1::allocator<realm::BindingContext::ObserverState> > const&, std::__1::vector<void*, std::__1::allocator<void*> > const&, bool) (RLMRealmUtil.mm:117)
5 XChat | (anonymous namespace)::KVOTransactLogObserver::~KVOTransactLogObserver() (transact_log_handler.cpp:230)
6 XChat | realm::_impl::transaction::advance(std::__1::unique_ptr<realm::SharedGroup, std::__1::default_delete<realm::SharedGroup> > const&, realm::BindingContext*, realm::_impl::NotifierPackage&) (memory:2581)
7 XChat | realm::_impl::RealmCoordinator::advance_to_latest(realm::Realm&) (memory:2589)
8 XChat | realm::Realm::refresh() (shared_realm.cpp:794)
9 XChat | ___39-[UserDb addOrUpdateUserInfo:complete:]_block_invoke.212 + 60
10 libdispatch.dylib | __dispatch_call_block_and_release + 24
11 libdispatch.dylib | __dispatch_client_callout + 16
12 libdispatch.dylib | _dispatch_main_queue_callback_4CF + 1000
13 CoreFoundation | ___CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
14 CoreFoundation | ___CFRunLoopRun + 1660
15 CoreFoundation | CFRunLoopRunSpecific + 444
16 GraphicsServices | GSEventRunModal + 180
17 UIKit | -[UIApplication _run] + 684
18 UIKit | UIApplicationMain + 208
19 XChat | main (main.m:14)
20 libdyld.dylib | _start + 4
```

## Steps to Reproduce

This is not a collapse that is bound to happen
## Code Sample

```
- (void)addOrUpdateUserInfo:(UserInfo *)userInfo
                   complete:(void (^)(void))complete
{
    dispatch_async(writeQueue, ^{
        RLMRealm *realm = [RLMRealm defaultRealm];
        [realm beginWriteTransaction];
        [UserInfo createOrUpdateInDefaultRealmWithValue:userInfo];
        [realm commitWriteTransaction];
        
        callback_and_refresh_realm(complete);

    });
}

#define callback_and_refresh_realm(block)\
dispatch_async_safe_main(^(void)\
{\
[[RLMRealm defaultRealm] refresh];\
if(block)\
{\
    block();\
}\
});\
```
## Version of Realm and Tooling

Realm framework version: ?3.0.1

Realm Object Server version: ?

Xcode version: ?xcode9

iOS/OSX version: ?Above iOS9

Dependency manager + version: ?Cocoapods 1.3.1

**Comment by james-rantmedia** [comment] 2017-11-01 10:33
Doesn't look like Realm's fault to me. It appears that you are passing the `userInfo` object across threads and trying to write to a Realm that is instantiated on a different thread.
Without seeing the implmentation of `[UserInfo createOrUpdateInDefaultRealmWithValue:userInfo];`, it's impossible to know exactly what is being done with that `userInfo` object.

**Comment by austinzheng** [comment] 2017-11-01 21:12
James is right. The fact that `userInfo` is being passed across queues is almost certainly a bug.

As for the first issue (the one involving `RLMObservationInfo`), that looks like the bug in #5287. Unfortunately, without a reproduction case we can't really investigate it further.

**Comment by Mingmingmew** [comment] 2017-11-03 07:30
@interface UserInfo : RLMObject
@property(nonatomic, assign) UserID uid;
@property(nonatomic, strong) NSString *erbanNo;
@property(nonatomic, strong) NSString *nick;
@property(nonatomic, assign) long birth;
@property(nonatomic, strong) NSString *star;
@property(nonatomic, strong) NSString *signture;
@property(nonatomic, strong) NSString *userVoice;
@property(nonatomic, assign) NSInteger voiceDura;
@property(nonatomic, assign) UserGender gender;
@property(nonatomic, strong) NSString *avatar;
@property(nonatomic, strong) NSString *region;
@property(nonatomic, strong) NSString *userDesc;
@property(nonatomic, assign) long followNum;
@property(nonatomic, assign) long fansNum;
@property(nonatomic, assign) long fortune;
@property(nonatomic, assign) AccountType defUser;
@property(nonatomic, strong) RLMArray<UserPhoto *><UserPhoto> *privatePhoto;

@end

RLM_ARRAY_TYPE(UserInfo)


#import "UserInfo.h"
#import "NSObject+YYModel.h"
@implementation UserInfo
+ (NSString *)primaryKey
{
    return @"uid";
}

+ (nullable NSDictionary<NSString *, id> *)modelContainerPropertyGenericClass {
    return @{
                @"privatePhoto":UserPhoto.class
             };
}

**Comment by Mingmingmew** [comment] 2017-11-03 07:31
This is the header and implmentation about the userInfo.

**Comment by austinzheng** [comment] 2017-11-03 18:46
Thanks. Since `UserInfo` is a Realm object subclass, you _cannot_ pass it between queues. Either open a Realm on the destination queue and re-fetch there, or use [thread-safe references](https://realm.io/docs/objc/3.0.1/api/Classes/RLMThreadSafeReference.html) to safely move the object to the destination queue.

**Comment by Mingmingmew** [comment] 2017-11-07 09:05
I just refresh the realm in main queue after I finish write operation. And I use RAC to observe the UserInfo's change in main queue.Am I pass the UserInfo between queues?

**Comment by Mingmingmew** [comment] 2017-11-07 09:20
Because If I pass the UserInfo between queues,the app would be crash.But my crash didn't appear each time I run my app.

**Comment by Mingmingmew** [comment] 2017-11-07 09:31
[UserCore.h.txt](https://github.com/realm/realm-cocoa/files/1449370/UserCore.h.txt)
[UserCore.m.txt](https://github.com/realm/realm-cocoa/files/1449371/UserCore.m.txt)
[UserDb.h.txt](https://github.com/realm/realm-cocoa/files/1449372/UserDb.h.txt)
[UserDb.m.txt](https://github.com/realm/realm-cocoa/files/1449373/UserDb.m.txt)
[UserInfo.m.txt](https://github.com/realm/realm-cocoa/files/1449375/UserInfo.m.txt)
[UserInfo.h.txt](https://github.com/realm/realm-cocoa/files/1449376/UserInfo.h.txt)

**Comment by austinzheng** [comment] 2017-11-07 21:35
Yes, you are passing objects between queues in `addOrUpdateUserInfo:complete:`, which you showed us in your original comment. `userInfo` is a Realm object of type `userInfo`. You are passing it into that method from whatever queue the code calling that method is. Then you dispatch onto `writeQueue` and use the `userInfo` variable again. Therefore, you have passed an object between a queue, which is not allowed.

Also, in your attached code files, I see you wrote some code to use thread safe references. A thread safe reference is _not_ an object. You need to [create a thread safe reference from an object](https://realm.io/docs/objc/3.0.1/api/Classes/RLMThreadSafeReference.html#/c:objc(cs)RLMThreadSafeReference(cm)referenceWithThreadConfined:), pass the thread safe reference to the destination queue, open the same Realm on the destination queue, and then [resolve the thread safe reference using that `RLMRealm`](https://realm.io/docs/objc/3.0.1/api/Classes/RLMRealm.html#/c:objc(cs)RLMRealm(im)resolveThreadSafeReference:). Please review our documentation if you have any more questions.

**Comment by Mingmingmew** [comment] 2017-11-08 03:48
But the Realm object of type userInfo in  addOrUpdateUserInfo:complete: is a unmanaged object.The documentation said the unmanaged object can pass between queue safety.

**Comment by austinzheng** [comment] 2017-11-08 05:20
Well, telling us that does change things.

If you have a reproduction case we'd be happy to look at it further. Otherwise it's not clear from your code samples why things would be failing.

**Comment by bdash** [comment] 2018-01-17 05:47
Closing due to the lack of further information. Feel free to reopen this if you're still in need of assistance and are able to provide the requested information.

**Closed by bdash** 2018-01-17 05:47 UTC
