### ISSUE TITLE
Creating Encryption Key - Swift 3.0

### ISSUE THREAD

**Issue by cmyers78** [realm/realm-cocoa#4276] opened 2016-10-28 14:25 UTC
I am working on encrypting an object, but my app crashes when I try to generate a new key.  The error is:

"Assertion failed: failed to insert the new key into the keychain"
## Goals

My goal is to create an encryption key in Swift 3.  I'm using the sample project that is Swift 2 and trying to update it.
## Expected Results

I expected to be able to generate a key
## Actual Results

"Assertion failed: failed to insert the new key into the keychain"
## Steps to Reproduce

I will say that I have the keychain button turned on in Capabilities which generated the necessary Dictionary and String in the Entitlements file.  (I know that many suggested that would work, but we already had done that before we every ran the program)
## Code Sample

`func generateKey() -> Data {

```
    let keychainIdentifier = "RealmEncryption"
    let keychainIdentifierData = keychainIdentifier.data(using: String.Encoding.utf8, allowLossyConversion: false)!

    var query: [String: AnyObject] = [
        kSecClass as String: kSecClassKey,
        kSecAttrApplicationTag as String: keychainIdentifierData as AnyObject,
        kSecAttrKeySizeInBits as String: 512 as AnyObject,
        kSecReturnData as String: true as AnyObject
    ]

    var dataTypeRef: AnyObject?
    var status = withUnsafeMutablePointer(to: &dataTypeRef) { SecItemCopyMatching(query as [String : AnyObject] as CFDictionary, UnsafeMutablePointer($0)) }
    if status == errSecSuccess {
        if let data = dataTypeRef as! Data? {
            return data
          }
        }

    var keyData = Data(count: 64)
    let result = keyData.withUnsafeMutableBytes { mutableBytes in SecRandomCopyBytes(kSecRandomDefault, keyData.count, mutableBytes)}

        query = [   kSecClass as String: kSecClassKey,
                kSecAttrApplicationTag as String: keychainIdentifierData as AnyObject,
                kSecAttrKeySizeInBits as String: 512 as AnyObject,
                kSecReturnData as String: true as AnyObject]

    status = SecItemAdd(query as [String : AnyObject] as CFDictionary, nil)
        assert(status == errSecSuccess, "Failed to insert the new key in the keychain")

   return keyData
}
```

`
## Version of Realm and Tooling

[In the CONTRIBUTING guidelines](https://git.io/vgxJO), you will find a script,
which will help determining these versions.

Realm version: 2.0.3

Xcode version: 8.0

iOS/OSX version: 10.12.1

Dependency manager + version: Cocoapods1.1.0

**Comment by kishikawakatsumi** [comment] 2016-11-01 15:49
@cmyers78 It seems you attempt to add a keychain item in spite of the item has already existed. You should use `SecItemUpdate()` function instead `SecItemAdd()` if you already added an item.

If you are not familiar with Keychain API, I recommend you to use wrapper library like https://github.com/kishikawakatsumi/KeychainAccess.

**Comment by kishikawakatsumi** [comment] 2016-11-01 15:51
I'll close this issue because it's not related Realm. If you have further questions, feel free to ask us.

**Closed by kishikawakatsumi** 2016-11-01 15:51 UTC

**Comment by cmyers78** [comment] 2016-11-01 16:25
The function above was one provided by Realm.  I shouldn't already have a keychain, though my new error says I'm using an existing keychain....not sure where that is coming from though.   I'm just using the encryption example provided by Realm.

**Comment by aman836** [comment] 2020-10-06 07:55
@cmyers78 I am facing the same issue, The issue is happening only for a few handful of users on my app, were you able to find a solution?
