### ISSUE TITLE
Support fast retrieval of all distinct values for a RLMObject key path. 

### ISSUE THREAD

**Issue by bigfish24** [realm/realm-cocoa#1297] opened 2015-01-05 22:09 UTC
Explored building a replacement for NSFetchedResultsController that is backed by Realm:

https://github.com/Roobiq/RBQFetchedResultsController

My current version works but has a few limitations. Specifically, creating the section and row index information to identify changes, requires iterating over the entire RLMResults whenever a change is notified (note: the controller works in conjunction with a notification manager that broadcasts object-level notifications).

The main reason for this iteration is to identify all of the values for the key path used to create the sections. If there was a faster way to retrieve all the distinct values for the key path given an RLMResult, this would prevent the performance degradation seen in the current implementation.

**Comment by alazier** [comment] 2015-01-06 19:00
There is currently not a way to get a list of all values for a property through the objc apis. It would be possible to make such an api using core apis for properties which have indexes but this is pretty low on the priority list at the moment and might be more trouble than it's worth if it doesn't work for any property.

One thing that might work instead is to store sections as RLMObjects with a single string property designated as the primary key. This could allow you to reuse section objects across multiple object, and getting the list of sections would be as easy and efficient as calling ```[Sections allObjects]``` as section names will be guaranteed to be unique.

Haven't had a chance to try out your project but it looks interesting. We have been holding off on adding support for change notifications until we have proper core support and it is obviously one of Realm's biggest pain points at the moment. I'm interested in hearing in now this performs and perhaps considering adding such functionality in the objc code until we have proper core support (which should be a lot faster once we get it).

**Comment by bigfish24** [comment] 2015-01-06 19:41
Thanks for the feedback. That is an interesting idea on how to handle sections and overlaps with an improvement I was thinking about. Given that NSFetchedResultsController utilizes a disk-based cache:

>
Pre-computed section info is cached to a private directory under this name. If Core Data finds a cache stored with this name, it is checked to see if it matches the fetchRequest. If it does, the cache is loaded directly—this avoids the overhead of computing the section and index information. If the cached information doesn’t match the request, the cache is deleted and recomputed when the fetch happens.
>

RBQFetchedResultsController could do something similar by only doing the full iteration initially to identify the unique section and index information. This information could then be persisted into a separate Realm that is identified by a hash generated from the original RBQFetchRequest. Then subsequent loads and any changes would only need to work off of this information.

**Comment by bigfish24** [comment] 2015-01-09 19:07
Wanted to update that the RBQFetchedResultsController now uses an internal cache backed by a separate Realm file, which prevents the need to iterate over the results to identify changes.

https://github.com/Roobiq/RBQFetchedResultsController

**Comment by astigsen** [comment] 2015-01-16 21:49
Is this a duplicate of #1103?

**Comment by alazier** [comment] 2015-01-16 22:00
Looks like it. Closing as duplicate of #1103

**Closed by alazier** 2015-01-16 22:00 UTC
Labels: backlog
