### ISSUE TITLE
Realm should not use excessive space when writing data

### ISSUE THREAD

**Issue by Codeido** [realm/realm-cocoa#1034] opened 2014-10-16 21:24 UTC
Hello. I think I've found a serious bug in Realm.

This is my code to generate some records:

<blink>
RLMRealm *realm = [RLMRealm defaultRealm];
for (int i = 0; i < 1000; i++) {
        [realm beginWriteTransaction];
       for (int j = 0; j < 1000; j++) {
            USFacebookUser *facebookUser = [[USFacebookUser alloc]init];
            facebookUser.username=@"some text";
            facebookUser.link=@"some text";
            facebookUser.birthday=@"some text";
            facebookUser.firstName=@"some text";
            ....
            [realm addObject:facebookUser];
       }
       [realm commitWriteTransaction];
}
</blink>

This code create a DB of 100000 records (and the size of dafult.realm is 604MB).

But, when i launch this to clear all the records:
[realm beginWriteTransaction];
[realm deleteObjects:[USFacebookUser allObjects]];
[realm commitWriteTransaction];

the records of the DB is equal to zero (i opened the db with the Realm browser), but the size of the file default.realm remains the same!
It is a bug?

**Comment by timanglade** [comment] 2015-04-28 20:15
Closing this in favor of realm/realm-core#738 & realm/realm-core#739 as this is really a core issue, that shouldn’t require any cocoa-level work.

**Closed by timanglade** 2015-04-28 20:15 UTC
Labels: blocked, bug, P1

**Comment by bryan1anderson** [comment] 2016-01-08 20:20
what there ever an answer to this? I'm experiencing this issue

**Comment by jpsim** [comment] 2016-01-08 21:07
Are the solutions listed in this thread not sufficient for your use case? What exactly is your issue? You may be better off filing a new issue with more details so we can better address your needs.

**Comment by JosephZZ** [comment] 2016-03-19 02:44
after making a compact copy we can still write to db right? 
In my case I have a huuuuuuge chunk of data entries to write at the beginning and later on it'll be more of updating the existing value. So all I need to do is making a compact copy  after finishing the initial writing and overwrite it as the default path right?

**Comment by jpsim** [comment] 2016-03-19 02:47
Yes

**Comment by JosephZZ** [comment] 2016-03-19 02:49
for future new data entries, will they be automatically in the compacted format or not?

**Comment by jpsim** [comment] 2016-03-19 03:27
Compaction is an action, not a format. To compact again, you'll need to compact again.

**Comment by JosephZZ** [comment] 2016-03-19 06:07
So how is it compacted? Just taking the space away like minified js? And if I update the current data entry value, will it make it bigger again?

**Comment by jleach** [comment] 2016-04-27 04:09
I've used `writeCopyToPath` to create a new compact database, but how do you go about telling `Realm()` to use it? What I do is copy it it, then replace the old one with the new copy. The problem is, `Realm()` acts a bit like a singleton in that it recycled objects / connections so they need to know to close and re-open the db. Thx.

**Comment by jpsim** [comment] 2016-04-27 17:18
> how do you go about telling Realm() to use it

You can create Realms backed by files at any location by using the `Realm(fileURL:)` initializer or setting the `Realm.Configuration.fileURL` property for the configuration passed to the `Realm(configuration:)` initializer.

If you have further questions, please open a new issue, which will make it easier to keep track of this separate conversation.
