### ISSUE TITLE
Encrypted Realm crashes when opening

### ISSUE THREAD

**Issue by anlaital** [realm/realm-cocoa#1746] opened 2015-04-09 11:51 UTC
We are getting some crashes from production when using an encrypted Realm (0.91.1). Sadly I have no further information on this issue as of yet.

```
SIGABRT ABORT at 0x0000000193e07270
Thread : Crashed: com.apple.main-thread
0  libsystem_kernel.dylib         0x0000000193e07270 __pthread_kill + 8
1  libsystem_pthread.dylib        0x0000000193ea5170 pthread_kill + 112
2  libsystem_c.dylib              0x0000000193d7eb18 abort + 112
3  *                              0x00000001003f26e0 tightdb::util::terminate(char const*, char const*, long, bool, long long, long long) + 656
4  *                               0x00000001003f29d4 tightdb::util::terminate(char const*, char const*, long, bool, long long, long long) + 1412
5  *                               0x0000000100468128 tightdb::Group::init_from_ref(unsigned long) + 2004
6  *                               0x0000000100471c64 tightdb::SharedGroup::begin_read(tightdb::SharedGroup::VersionID) + 7208
7  *                               0x0000000100324464 -[RLMRealm getOrCreateGroup] (RLMRealm.mm:226)
8  *                               0x000000010032f094 RLMRealmSchemaVersion (group.hpp:596)
9  *                               0x00000001003040b4 RLMMigrationRequired(RLMRealm*, unsigned long) (RLMObjectStore.mm:253)
10 *                               0x0000000100302f34 RLMUpdateRealmToSchemaVersion (RLMObjectStore.mm:269)
11 *                               0x0000000100324d6c +[RLMRealm realmWithPath:key:readOnly:inMemory:dynamic:schema:error:] (RLMRealm.mm:381)
12 *                               0x0000000100324850 +[RLMRealm realmWithPath:encryptionKey:readOnly:error:] (RLMRealm.mm:304)
```

**Comment by jpsim** [comment] 2015-05-01 18:19
This is caused by a corrupted file, likely due to having null bytes in strings, which are unsupported but has only been enforced in recent versions of realm.

We're closing this issue as this should no longer happen in new files.

**Closed by jpsim** 2015-05-01 18:19 UTC
