### ISSUE TITLE
Copying an object with nested list relations randomly loses the relationships

### ISSUE THREAD

**Issue by vittoriom** [realm/realm-cocoa#3077] opened 2016-01-07 15:53 UTC
I'm not sure how to best name this issue, but this is what I get:

I have the following object hierarchy:

An entity A has 0 or more references to an entity B, that in turn has 0 or more references to an entity C
`A -*> B -*> C`

With the Cocoa Realm (version 0.97.0) copying a given object A to another Realm correctly works and copies all the nested relationships. By using the Swift version (same 0.97.0) I lose some relationships. Of course the original object is the same and all the relationships are correctly set.

The major difference in copying the object to the other realm is:

```diff
-   let newArticleModel = ArticleModel.createInRealm(realm, withValue: articleModel)
+   let newArticleModel = realm.create(ArticleModel.self, value: articleModel, update: false)
```

All the properties of the Realm Objects are the same `dynamic var` except for `RLMArray`s that now became `let ... = List<xxx>()`

I would like to privately send you the same realms (they're very small, just one entity with the nested objects) created by the Objc and the Swift versions so you can see the difference and the issue I found. Please provide an email for this.

I'll try next week to reproduce the issue with a standalone project even though I realize this will take some time, maybe just by looking at the Realms and the line of code I changed you can already get to some conclusions...

**Comment by mrackwitz** [comment] 2016-01-08 11:54
You can share files privately with us via help@realm.io. It would be helpful, if you could include your model class definitions.

**Comment by vittoriom** [comment] 2016-01-11 07:48
I just sent you an email with the realms and the relevant model class definitions with both the ObjC and Swift versions of Realm.

Thanks!

**Comment by vittoriom** [comment] 2016-01-11 08:21
One more thing, I sent you the zip of a small project that reproduces the issue, hopefully this is of more help!

**Comment by mrackwitz** [comment] 2016-01-11 19:35
Thanks for the excellent reproduction case. Turns out that this is a duplicate of https://github.com/realm/realm-cocoa/issues/2905. There is ongoing work in PR https://github.com/realm/realm-cocoa/pull/2901 to fix this issue. I'll close this issue for now.

**Closed by mrackwitz** 2016-01-11 19:35 UTC
Labels: Help

**Comment by vittoriom** [comment] 2016-01-12 07:37
Cool, I had a look at both the issue and the PR you mentioned but wasn't sure that was going to exactly fix my issue, good to know that! Even though the PR looks a bit abandoned, I'll subscribe to stay updated. Thanks!
