### ISSUE TITLE
createOrUpdate on partial objects causes nested objects to reset

### ISSUE THREAD

**Issue by webstersx** [realm/realm-cocoa#1806] opened 2015-04-28 13:47 UTC
Sample project
https://github.com/webstersx/realm-createOrUpdate-example/

For some endpoints, the API I'm working with returns partial objects to reduce DB workload. Trying to put the response through [ModelClass createOrUpdateInDefaultRealm:responseObject] causes the missing values in the nested objects to be replaced with defaults instead of performing a lookup and doing a partial update on that object instead.

**Comment by webstersx** [comment] 2015-04-28 14:31
An edits which worked for me but fails the unit tests are:

Before setting the value, recurse in and get the actual object based on the values -- this should find the existing object
0.91.4 ~> RLMObjectStore.mm:516
```objective-c
            id propValue = dict[prop.name];

/* from here */            
            if (prop.type == RLMPropertyTypeObject) {
                propValue = RLMCreateObjectInRealmWithValue(realm, prop.objectClassName, value[prop.name], options);
            }
/* to here */
            
            if (propValue && (created || !prop.isPrimary)) {
```

I have another snippet that works for me but I'm it's late and I'm pretty sure I didn't think it through so I'll save myself the embarassment ;)

**Comment by segiddins** [comment] 2015-04-28 15:38
@webstersx this is a code path that we know has issues -- we'd love to see a pull request with some of the changes you've been playing around with!

**Comment by segiddins** [comment] 2015-04-28 17:26
This is likely a duplicate of https://github.com/realm/realm-cocoa/issues/1362

**Closed** 2015-04-28 17:50 UTC
