### ISSUE TITLE
RLMResults returns deleted objects

### ISSUE THREAD

**Issue by bigfish24** [realm/realm-cocoa#1317] opened 2015-01-09 19:28 UTC
In my test project for: https://github.com/Roobiq/RBQFetchedResultsController

I found that RLMResults will return deleted objects. Is this an expected result in certain situations? In the test project, the delete bar button will grab the RLMResults for the first section and then iterate over the results to delete each object. The crash occurred because one of the objects returned was invalidated.

**Comment by alazier** [comment] 2015-01-13 22:10
You should not be deleting items during enumeration. We recently pushed a fix that should throw an exception when this occurs. Instead of deleting objects individually, it's recommended that you delete a whole set of objects at once using the ```deleteObjects:``` method.

**Comment by bigfish24** [comment] 2015-01-13 23:37
Got it. I switched the code to use ```deleteObjects:```. I forgot to do this because I was iterating to make sure to post a notification so that the FRC would update.

To adapt, I created a RLMRealm category in my test project ```deleteObjectsWithNotification:``` to perform the necessary notifications while also the deletes.

**Comment by bigfish24** [comment] 2015-01-15 01:03
I saw the update that throws the exception. Does this also apply to editing an object so that its new property value makes it fall outside of the RLMResults query during the enumeration?

**Comment by tgoyne** [comment] 2015-01-15 01:10
Yes. Unfortunately, that's something that we don't have a good solution for yet. Bad solutions are to call `firstObject` in a loop until the RLMResults is empty or to convert it to an NSArray first, both of which are ugly and have performance implications.

**Comment by bigfish24** [comment] 2015-01-15 01:15
Hmm I guess you could also call allObjects and loop through all of them, checking if the property meets the one you are looking to adjust, then adjust it?

**Comment by tgoyne** [comment] 2015-01-15 01:21
Yes, that'd work. Also probably wouldn't perform very well at the moment due to `allObjects` doing a lot more work than it needs to, but that should change very soon (just waiting for a new version of the core library to be released).

**Comment by bigfish24** [comment] 2015-01-15 01:34
Ok, well I have some other ideas on how to work around it. Thanks for quick follow up.

**Comment by alazier** [comment] 2015-01-16 22:19
Closing as a duplicate of  #1179. Once we freeze RLMResults during fast enumeration this will no longer be an issue.

**Closed by alazier** 2015-01-16 22:19 UTC
Labels: pending
