### ISSUE TITLE
addOrUpdateObject leaves orphan child objects

### ISSUE THREAD

**Issue by rciobanu-omnifone** [realm/realm-cocoa#1370] opened 2015-01-21 12:29 UTC
Hello,

I realize cascading deletions are in the works at present time. This is probably somewhat related.
Here's what I have.
- `class A`, that has a property `propertyB` of `class B`;
- `class A` has a primary key defined;
- doesn't matter if `class B` has a PK or not;
- both classes A and B are descendants of `RLMObject`;
- `objectA` of `class A` has its `propertyB = objectB1` of `class B`.

**1. Goals:** I am now trying to `addOrUpdateObject` the `objectA` with an instance whose `propertyB = objectB2`
**2. Expected results:** The existing object of `class A` that has the same PK will be updated, so no new entry in table A will be created. `objectB1`, being unreferenced, is deleted from the table B.
**3. Actual results:** Everything fine with objectA, but both `objectB1` and `objectB2` are now present in the DB.
**4. Version of Realm/Xcode/OSX:** Realm - 0.89.1, Xcode - 6.1.1, OSX - 10.10.1

I know about the `[linkingObjectsOfClass:forProperty:]` and am able to use it successfully to avoid creating orphans when deleting an object. My problem is with `[addOrUpdateObject:]` because this method hides the complexity of having to search for an existing copy of the object and deciding whether to update it or create a new one. The orphaning happens even if `class B` has no PK defined, meaning this is purely a 1-to-1 relationship.

My current workaround would be to treat `[addOrUpdateObject:]` in a very special and careful way, just as I do with `[deleteObject:]`: first check all child objects if there's no one else pointing to them with `[linkingObjectsOfClass:forProperty:]` and delete the children that would become orphaned.
Is there any better way of handling this?

**Comment by alazier** [comment] 2015-01-21 19:02
It sounds like your workaround is the correct approach until we support cascading deletes (#1186). Will close this as a duplicate of that issue.

If there is a 1-1 relationship between A and B, adding a primary key to the B object (and using the same primary key for both objects) would essentially reuse the B object updating is properties when updating A. This would obviate the need to manually delete orphaned objects.

**Closed by alazier** 2015-01-21 19:02 UTC

**Comment by rciobanu-omnifone** [comment] 2015-01-22 10:04
@alazier Thank you for the quick reply.
Adding a PK to class B doesn't work if there are objects of other classes who need to reference it.
In my scenario I would be using an OptionalString class (as described here https://github.com/realm/realm-cocoa/issues/628#issuecomment-56765986) and could be referenced from, say, Book and Author classes. Using a Book's PK as an OptionalString's PK at the same time as using the Author's PK as an OptionalString's PK will work only while there are no duplicate PKs in the Author and Book tables (which can't be guaranteed).
Also, if the Author has multiple properties that are OptionalStrings there's a PK clash again (that's not a 1-to-1 relationship, strictly speaking).

Probably to do this right each OptionalString property should be of some different class, like AuthorName or BookName, which both descend from OptionalString. But that means creating new classes not because they're logically needed, but because of implementation intricacies. Kind of violates the Occam's Razor principle, if you see what I mean.
