### ISSUE TITLE
Change how Realm().add(_:update: false) works

### ISSUE THREAD

**Issue by natemann** [realm/realm-cocoa#2140] opened 2015-06-30 12:29 UTC
Currently, if you call` Realm().add(_:update:false)` on an object that already exists in the realm, the application crashes.  This makes the `( update: false)` parameter useless.  How about simply not adding/ updating the object if `update: false` and the object already exist in the realm.

**Comment by bigfish24** [comment] 2015-06-30 21:24
Thanks for the feedback, however, I am not sure I agree this is a good solution. If the object already exists, silently ignoring to the add doesn't make it clear to the dev what is going on. If this is an issue, I think it is helpful to see this error and then re-architect the code to prevent this situation or decide to use a primary key on the model so that you can ensure uniqueness/update.

**Comment by natemann** [comment] 2015-07-08 00:07
Then at least have it throw an error.  I am using this with a primary key.  Sometimes, when I am downloading objects, I might download existing objects, but do not want to update them, thus the desire to mark update: false.  This however, crashes my app

**Comment by bigfish24** [comment] 2015-07-08 01:01
I believe it is throwing an exception but since Swift doesn't have the ability to catch exceptions (Swift 2.0 fixes this), this is just causing the crash.

The short term fix is to check for the item manually and ignore the call to add if it exists. 

I will bring this up with the team to figure out if they want to adjust API to include passing an error or if it should be updated for Swift 2.0 to support the exception handling.

**Comment by jpsim** [comment] 2015-07-21 17:11
I'm closing this ticket as this is the expected behavior. Feel free to ping us if you have any further questions.

**Closed by jpsim** 2015-07-21 17:11 UTC
Labels: enhancement, pending
