### ISSUE TITLE
Xcode 12 Carthage Support

### ISSUE THREAD

**Issue by Senocico** [realm/realm-cocoa#6780] opened 2020-09-17 15:52 UTC
It does not compile with Carthage.

Run 

`carthage update --platform iOS realm-cocoa`

You will receive the following error 🛑  :

```
Please update to the latest Carthage version: 0.35.1. You currently are on 0.35.0
*** Checking out realm-cocoa at "v5.4.1"
*** xcodebuild output can be found in /var/folders/70/r33z6h3x10n3bqxr45td4j080000gn/T/carthage-xcodebuild.B8ehkB.log
*** Downloading realm-cocoa.framework binary at "v5.4.1"
***  Skipped installing realm-cocoa.framework binary due to the error:
	"Incompatible Swift version - framework was built with 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53) and the local version is 5.3 (swiftlang-1200.0.29.2 clang-1200.0.30.1)."

    Falling back to building from the source
*** Building scheme "Realm" in Realm.xcworkspace
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace .../Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A7209/realm-cocoa/v5.4.1 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/70/r33z6h3x10n3bqxr45td4j080000gn/T/realm-cocoa SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in .../Carthage/Checkouts/realm-cocoa)
```

Any solutions?

**Comment by tgoyne** [comment] 2020-09-17 16:14
Duplicate of #6717.

**Closed by tgoyne** 2020-09-17 16:14 UTC
Labels: O-Community
