### ISSUE TITLE
Frozen object usage leading to drastic memory and disk usage growth?

### ISSUE THREAD

**Issue by winstondu** [realm/realm-cocoa#6980] opened 2020-12-08 01:55 UTC
We have been using frozen objects in conjunction with RxRealm as a way to add a filter to our realm object change listeners. Frozen objects alleviate our need for writing custom snapshot methods.

Unfortunately, despite the fact that our usage of frozen objects are called on a RunLoop-Thread (main), our refactor led to our app persistently using more and more memory as changes accumulated. Strangely, even the size of the realm db on disk (which should be agnostic to whether we have frozen objects or not), expanded drastically. Digging through the Realm internals, we noticed freezing realm persists a realm version in the lock file. We also found the following comment in the library:

```
     - warning: Holding onto a frozen Realm for an extended period while performing write
     transaction on the Realm may result in the Realm file growing to large sizes. See
     `Realm.Configuration.maximumNumberOfActiveVersions` for more information.
```

This comment clearly portrays the behavior in memory/disk usage in what we are seeing. Yet, that behavior makes no sense. After all, a frozen realm's size should be fixed (it is at worst just a duplicate of the realm file at a certain time). Future writes don't affect that frozen realm (only the live realm). Yet, somehow just having a frozen object can cause Realm's usage to vastly increase beyond the sum of the sizes of the frozen realm + the active realm?

## Goals
Having an easy way to snapshot a realm object (make it no longer live) for change comparison purposes. Not use too much memory or disk space.

## Expected Results
- Realm should be consuming memory in proportion to the number of frozen realm objects I have. So if I am holding at most 5 frozen realm objects, I should expect a memory usage of at most 5x my realm db's size + the size of all active realms in my app.
- Once the app is shutdown (e.g. force-killed), usage of frozen objects in my app should have little/no effect on the realm db file's disk size.

## Actual Results
- drastic and unending increase in memory and disk usage as I hold on to a few frozen objects 
- Large realm file disk usage persists in between app sessions (even if the other issue was due to my code, this issue is something I am convinced is a problem with realm)

## Steps for others to Reproduce
Use RxRealm change listeners as Observables, with the filter comparison code (see below)

## Code Sample
```
extension ObservableType where Element: Object /* i.e. Realm object */ {
    public func withFrozenShadow() -> Observable<(Self.Element, Self.Element)> {
        return self.map { object -> (Self.Element?, Self.Element?) in
            return (object, object?.freeze())
        }
    }

    // MARK: - Custom distinctUntilChanged operators
    public func distinctUntilFrozenChanged(comparer: @escaping (Self.Element, Self.Element) -> Bool) -> Observable<Self.Element> {
        return self
            .withFrozenShadow()
            .distinctUntilChanged({ (/*live*/_, frozen) -> Self.Element? in
                return frozen
            }, comparer: { (prev, next) -> Bool in
                return comparer(prev, next)
        }).map { $0.0 } // map back to live
    }
}
```
## Version of Realm and Tooling
Realm framework version: 10.1.4

Xcode version: 12.1

iOS/OSX version: 14

Dependency manager + version: Cocoapods, 1.9.3

**Comment by winstondu** [comment] 2020-12-08 01:57
@tgoyne ?

**Comment by tgoyne** [comment] 2020-12-08 19:09
Freezing objects does not create a new file which contains the data for those objects. It continues to use the same file, and writes to the file simply do not overwrite any of the data needed for the frozen references. On a newly compacted Realm where the live data size is equal to the file size this means that any writes will have to grow the file to store the new data, but in most cases we'll start with overwriting data from versions before the frozen one.

What can lead to problems with frozen objects is that they currently also pin the versions after them in addition to the frozen version. Normally, if you make four write transactions to a Realm file, the third write transaction is allowed to overwrite data written by the first transaction, and the fourth write transaction can overwrite data written by the second transaction. If before performing any of the writes you freeze an object (and continue to hold onto that frozen object), none of those write transactions will be able to overwrite any data written by the previous writes. If, on the other hand, after each of the writes you re-obtained a new version of the frozen object, and discarded the old one, we'd be able to overwrite older data as usual.

Looking at the source of [DistinctUnionUntilChangedSink](https://github.com/ReactiveX/RxSwift/blob/main/RxSwift/Observables/DistinctUntilChanged.swift#L78) I can see that it stores the initial key and then continues to store that same object until the comparer returns false. This means that it's continuing to pin the original version until the value changes. If `self.currentKey = key` were moved above `if areEqual { return }`, then it'd instead always be holding onto the most recent frozen object rather than the oldest one, and not cause any problems.



The only time we shrink an existing file is when compacting it (via shouldCompactOnLaunch in the Realm configuration).

**Comment by astigsen** [comment] 2020-12-08 19:16
Is there any chance that you could use realms own distinct operator instead?

https://docs.mongodb.com/realm-sdks/swift/10.2.0/Structs/Results.html#/s:10RealmSwift7ResultsV8distinct2byACyxGqd___tSTRd__SS7ElementRtd__lF

**Comment by winstondu** [comment] 2020-12-08 21:22
> What can lead to problems with frozen objects is that they currently also pin the versions after them in addition to the frozen version.

Yes, but that clearly is not desirable behavior no? And in any case, why would frozen objects necessitate version pinning in between app sessions?

My goal is to snapshot an object (and any of its relations) at a particular time for change comparison in an inexpensive manner. Are you saying this is not the use case for frozen objects? 

> Looking at the source of [DistinctUnionUntilChangedSink](https://github.com/ReactiveX/RxSwift/blob/main/RxSwift/Observables/DistinctUntilChanged.swift#L78) I can see that it stores the initial key and then continues to store that same object until the comparer returns false. This means that it's continuing to pin the original version until the value changes. If `self.currentKey = key` were moved above `if areEqual { return }`, then it'd instead always be holding onto the most recent frozen object rather than the oldest one, and not cause any problems.

Why would that eliminate all issues? It is possible that as I hold onto a particular frozen object, there could be writes in the db unrelated to that particular object. Yet those unrelated writes (as you indicate) mean more realm db versions are pinned even though the underlying changeObserver for the object I care about is not even invoked.

> Is there any chance that you could use realms own distinct operator instead?

@astigsen , I'm not sure how this is relevant at all to my goal. This operator is used for querying realm to get distinct results from a particular version of the db file, not for checking whether an object changed between versions of the db file.

For example, take the following schema:
```
class Person: Object {
    @objc dynamic var name: String?
    @objc dynamic var phoneNumber: String?
    @objc dynamic var bestFriend: Person?
    let pets = List<Pet>()
}
class Pet: Object {
    @objc dynamic var name: String?
    @objc dynamic var breed: String?
}
```

If I needed to know if a particular `Person` object changed, HOW it changed (so I can determine whether the change matters), how would I do that effectively?
The possible use cases are very straightforward:
    - Send text notification that a person has a new best Friend (gasp), but not when any other fields/relations change.
    - Send a notification that a person has a new Pet

Currently, I effectively need to write custom snapshot code for the `Person` and the fields/relations I care about.

**Comment by tgoyne** [comment] 2020-12-08 21:55
> In any case, why would frozen objects necessitate version pinning in between app sessions? I mean, you can either store a copy of the db at the frozen version, or store a compacted changelog of writes since the frozen version to the most recent version. Neither of these approaches should require version pinning all the realm data in between.

Writing just the diffs from the oldest version is conceptually similar to what we do, although it's in a format optimized for read performance and not always particularly compact. The problem is that with how our allocator works we can't actually free any of the data used by those diffs until they're older than the oldest live version. If you modify a property on an object three times (in different write transactions), each of those intermediate values are considered live and reachable as long as there's an older pinned version even though two of them aren't very interesting any more.

> I can see how that mitigates the problem, but why would that eliminate all issues? It is possible that as I hold onto a particular frozen object, there could be writes in the db unrelated to that particular object. Yet those unrelated writes (as you indicate) mean more realm db versions are pinned even though the underlying changeObserver for the object I care about is not even invoked.

Ah yes, that's true. Frozen objects in their current form probably can't work well for what you're doing, unfortunately. We're currently looking into ways that we can make them work better so I guess this is a good example of something we need to make work.

**Comment by astigsen** [comment] 2020-12-09 07:20
> If I needed to know if a particular Person object changed, HOW it changed (so I can determine whether the change matters), how would I do that effectively?

[Object Notifications](https://docs.mongodb.com/realm/ios/notifications#object-notifications) should tell you exactly that (and without the overhead of you having to manually compare and diff on every single update).

**Comment by winstondu** [comment] 2021-01-21 22:54
| Object Notifications should tell you exactly that (and save you the overhead of having to manually compare and diff on every single update).

> [Object Notifications](https://docs.mongodb.com/realm/ios/notifications#object-notifications) should tell you exactly that (and save you the overhead of having to manually compare and diff on every single update).

Not very helpful, because sometimes I want to diff only on particular values of the object, rather than if any property changed.

**Comment by nirinchev** [comment] 2021-01-22 02:13
Object notifications tell you which property changed - you can early return from your handler in case you don't care about that particular property.

**Comment by winstondu** [comment] 2021-01-22 18:54
@tgoyne , is there a way to just remove all pinned versions besides the most recent on db startup?

**Comment by tgoyne** [comment] 2021-01-22 19:00
Versions are only pinned while the file is actually open, so on startup only the latest version is live. You can set `shouldCompactOnLaunch` in the Realm configuration if you would like to automatically compact the file and actually reduce the disk space used.

**Comment by winstondu** [comment] 2021-01-22 19:05
> Versions are only pinned while the file is actually open, so on startup only the latest version is live.

So in other words, if I had 100 pinned versions, and then I restarted the app (or closed the realm then reopened), I won't have all those versions pinned anymore?


> You can set `shouldCompactOnLaunch` in the Realm configuration if you would like to automatically compact the file and actually reduce the disk space used.

So even though the versions are no longer pinned, they still occupy disk space?

**Comment by tgoyne** [comment] 2021-01-22 19:13
Yes, the active version count is always 1 when the file is first opened.

The space previously used for older versions is overwritten by subsequent writes to the file. Reducing the size of the file on disk requires that all of the live data be at the start of the file, which typically won't be the case.

**Comment by winstondu** [comment] 2021-01-22 19:56
> The space previously used for older versions is overwritten by subsequent writes to the file. Reducing the size of the file on disk requires that all of the live data be at the start of the file, which typically won't be the case.

So in other words, once the db uses a certain capacity, that capacity won't decrease unless the realm is compacted. But if a lot of that capacity is "unused" (aka overwritable), the capacity won't increase either?

**Comment by tgoyne** [comment] 2021-01-22 19:59
Correct.

**Comment by leemaguire** [comment] 2021-02-08 10:57
Closing as explanation for Frozen objects has been provided.

**Closed** 2021-02-08 10:58 UTC
Labels: O-Community
