### ISSUE TITLE
No Such Module 'RealmSwift' ; Xcode 9 Beta Swift 4

### ISSUE THREAD

**Issue by michaelcordero** [realm/realm-cocoa#5196] opened 2017-08-01 16:17 UTC
## Goals

After installation of Realm with Cocoa Pods;
I want to import RealmSwift without Xcode's
compiler complaining. 

## Expected Results

Realm installed. Import RealmSwift with no errors

## Actual Results

Error Message: No Such Module Realm Swift

## Steps to Reproduce

1. Create new Xcode Project. 
2. Name it RealmTasksTutorial
3. Close Xcode
4. Open Terminal
5. Navigate to project's directory i.e. cd ../RealmTasksTutorial
6. run this command: pod init
7. run this command: nano Podfile
8. uncomment platform: iOS 9 and add 'pod RealmSwift'
9. pod install
10. open RealmTasksTutorial.xcworkspace

## Code Sample

import UIKit
import RealmSwift

//MARK: Model
class ViewController: UITableViewController {
}

## Version of Realm and Tooling

Realm framework version: 2.9

Realm Object Server version:  n/a

Xcode version:  Xcode 9 beta

iOS/OSX version: 11

Dependency manager + version: Ruby Gems 2.0 / cocoa-pods 1.2.1

Swift version: 4

**Comment by austinzheng** [comment] 2017-08-01 22:02
Please try the CocoaPods instructions [here](https://realm.io/docs/objc/latest/#cocoapods), and get back to us if it still doesn't work.

**Comment by michaelcordero** [comment] 2017-08-02 02:53
@austinzheng 
After running the deintegrate cocoa pods commands:

pod cache clean Realm
pod cache clean RealmSwift
pod deintegrate || rm -rf Pods
pod install --verbose
rm -rf ~/Library/Developer/Xcode/DerivedData

and reopening the project RealmTasksTutorial.xcworkspace with 'open' command. 
I am getting the same error.

**Comment by bdash** [comment] 2017-08-03 18:09
@michaelcordero, I followed the steps you shared and was unable to reproduce the problem. CocoaPods pulled down v2.9.1 of both Realm and Realm Swift, which is newer than the version you mentioned using, but there were no relevant changes between v2.9.0 to v2.9.1.

The fact that Xcode is unable to find the RealmSwift module suggests that it, or the Realm framework it depends on, is missing or has failed to build.

Just to confirm: are you seeing this error when building the RealmTasksTutorial project, or are you simply seeing it after opening the Xcode workspace? I do know that Xcode will complain about failing to find modules simply because you've not got around to building them yet. In that case hitting Cmd-B or Product -> Build will build your project and its dependencies, and will likely clear up the issue.

If you are seeing the error as a result of building your project, this presumably indicates that Realm or RealmSwift failed to build. In that case you'll want to share the build log that Xcode created while building your project as it will contain relevant information, such as the error messages, that will help us understand the failure. You can find the build logs under the Report navigator in Xcode (View -> Navigators -> Show Report Navigator, or Cmd-9).

**Comment by bdash** [comment] 2017-08-08 19:32
@michaelcordero, have you had a chance to try this again (either with Xcode 9 beta 4, or the recently-released beta 5)?

**Comment by michaelcordero** [comment] 2017-08-08 19:38
Not yet. But I will because I had some version issues with FBSDKCoreKit, so
hopefully if I tweak the versions it will work.

**Comment by kishikawakatsumi** [comment] 2017-08-21 11:55
It looks to me as if we've answered your question. I'm going to close this issue. Please feel absolutely free to open a new one if you have more questions.

**Closed by kishikawakatsumi** 2017-08-21 11:55 UTC
Labels: build, S:Waiting For User, T:Help

**Comment by hastlerr** [comment] 2017-10-20 14:53
you need to delete the pods folder in the project, and make pod install

**Comment by jonathanbronson** [comment] 2017-10-21 19:54
Hi I' having a similar issue. I have a project written in Swift 3. I'm using Realm 3.0.0 and it compiles and runs just fine. When I try clicking "Conversion to Swift 4" I get a "No such module as 'RealmSwift' Swift Compiler Error. I tried the cleaning suggested by Austin Zheng above. I also tried deleting and reinstalling cocoapods. I'm using Xcode version 9.0 (9A235). 

I installed Realm via a Podfile shown below. Any thoughts would be appreciated.

Thanks!

# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'My App' do

  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods
  pod 'Charts', '~> 3.0.4'
  pod 'RealmSwift', '~>3.0.0'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '4.0'
      end
    end
  end

end

**Comment by austinzheng** [comment] 2017-10-23 18:10
Please create a new ticket and fill out the Issue Template. Thanks.
