### ISSUE TITLE
Use of camelCased properties importing from JSON

### ISSUE THREAD

**Issue by michalkos** [realm/realm-cocoa#1063] opened 2014-10-22 13:38 UTC
My model in Swift has property named `isPromo`.
In JSON, this property is named `is_promo` and this throws an exception when importing with `createInDefaultRealmWithObject`

Is there some way how to import this without changing the JSON dictionary?
It would be nice to have some function in model where we could define this transforms. Also if we have different property names in models.

For example something like this:

    class MyModel: RLMObject {
        dynamic var isPromo = false
        dynamic var productDescription = ""

        override class func importPropertyNames() -> [String : String] {
            return [ "is_promo" : "isPromo", "description" : "productDescription" ]
        }

**Comment by yoshyosh** [comment] 2015-04-08 17:37
Incase someone comes across this, another person had issues using ObjectMapper https://github.com/realm/realm-cocoa/issues/1726

**Comment by timanglade** [comment] 2015-04-28 20:53
Closing as duplicate of #694

**Closed by timanglade** 2015-04-28 20:53 UTC
Labels: backlog
