### ISSUE TITLE
Query with 'OR' condition doesn't always work in relationship

### ISSUE THREAD

**Issue by jeremygrenier** [realm/realm-cocoa#1863] opened 2015-05-07 14:10 UTC
Hey Realm team,

Below, a small example to reproduce the problem.

```
#import "AppDelegate.h"
#import <Realm/Realm.h>

@protocol Person;

@interface Person : RLMObject
@property NSString *login;
@property NSString *display_name;

@end

RLM_ARRAY_TYPE(Person)

@implementation Person

+ (NSString*)primaryKey
{
    return @"login";
}

@end

@interface User : RLMObject

@property NSString *login;
@property RLMArray<Person> *friends;

@end

@implementation User
@end

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
    self.window = [[UIWindow alloc] initWithFrame:[[UIScreen mainScreen] bounds]];
    self.window.rootViewController = [[UIViewController alloc] init];
    [self.window makeKeyAndVisible];
    
    void (^log)() = ^() {
        User *me = User.allObjects.firstObject;
        NSLog(@"Friends: %@", me.friends);
        
        NSString *filter = @"fab";
        RLMResults *newResults = [me.friends objectsWhere:@"login CONTAINS[c] %@ OR display_name CONTAINS[c] %@", filter, filter];
        NSLog(@"Number of friends with filter '%@': %li", filter, (unsigned long)newResults.count);
    };
    
    [[NSFileManager defaultManager] removeItemAtPath:[RLMRealm defaultRealmPath] error:nil];
    
    RLMRealm *realm = [RLMRealm defaultRealm];
    User *me = User.allObjects.firstObject;

    me = User.new;
    me.login = @"me";
    
    [realm transactionWithBlock:^{ [realm addObject:me]; }];
    
    Person *person = Person.new;
    person.login = @"azazaz";
    person.display_name = @"Fabrice B.";
    
    [realm transactionWithBlock:^{ [realm addOrUpdateObject:person]; }];
    
    Person *friend1 = Person.new;
    friend1.login = @"john42";
    friend1.display_name = @"John H.";
    
    Person *friend2 = Person.new;
    friend2.login = @"jeremy";
    friend2.display_name = @"Jeremy G.";
    
    [realm transactionWithBlock:^{
        [realm addOrUpdateObject:friend1];
        [realm addOrUpdateObject:friend2];
        
        [me.friends addObject:friend1];
        [me.friends addObject:friend2];
    }];

    log();
    
    Person *friend = Person.new;
    friend.login = @"azazaz";
    friend.display_name = @"Fabrice B.";
    
    [realm transactionWithBlock:^{
        [realm addOrUpdateObject:friend];
        [me.friends addObject:friend];
    }];
    
    log();
    
    return YES;
}

@end
```

**Comment by tgoyne** [comment] 2015-05-07 19:42
Will be fixed by https://github.com/realm/realm-core/pull/812. The problem is that the OR query node is expecting the row indices to be in ascending order, which is not always the case for an RLMArray.

**Closed** 2015-05-13 17:56 UTC
Labels: bug
