### ISSUE TITLE
Query on RLMArray containing NSString crashes.

### ISSUE THREAD

**Issue by Gawetaner** [realm/realm-cocoa#5785] opened 2018-05-29 08:26 UTC
## Goals
Query all objects that contain a specific string in a RLMArray property.

## Expected Results
The result contains all objects which contain the specific string in their RLMArray property.

## Actual Results
The query throws an exception:
> Expected object of type (null) for property 'strings' on object of type 'RealmObject', but received: 1

## Steps to Reproduce
1. Create a new ObjC iOS Project
2. Add Realm as dependency
3. Paste the sample code into `AppDelegate.m`
4. Start the App

## Code Sample
```objc
#import "AppDelegate.h"

// Frameworks
#import <Realm/Realm.h>

@interface RealmObject : RLMObject

@property (nonatomic) RLMArray <NSString *> <RLMString> *strings;

@end

@implementation RealmObject

+ (NSArray<NSString *> *)requiredProperties
{
    return @[NSStringFromSelector(@selector(strings))];
}

@end

@interface AppDelegate ()

@end

@implementation AppDelegate


- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
    RealmObject *object1 = [RealmObject new];
    [object1.strings addObjects:@[@"1"]];

    RealmObject *object2 = [RealmObject new];
    [object2.strings addObjects:@[@"2"]];

    RealmObject *object3 = [RealmObject new];
    [object3.strings addObjects:@[@"3"]];

    RLMRealm *realm = [RLMRealm defaultRealm];
    [realm transactionWithBlock:^{
        [realm deleteAllObjects];
        [realm addObjects:@[object1, object2, object3]];
    }];
    
    RLMResults *results = [RealmObject objectsWhere:@"%@ IN SELF.strings", @"1"];
    NSLog(@"%@", results);
    
    return YES;
}
@end
```

## Version of Realm and Tooling
```
ProductName:	Mac OS X
ProductVersion:	10.13.4
BuildVersion:	17E202

/Applications/Xcode_9.3.0.app/Contents/Developer
Xcode 9.3
Build version 9E145

/Users/gawetaner/.rbenv/shims/pod
1.5.3
Realm (3.5.0)
Realm (~> 3.5)

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin17)

carthage not found
(not in use here)

/usr/local/bin/git
git version 2.17.0
```

**Comment by zntfdr** [comment] 2018-09-07 05:02
Any update in this? @jpsim

**Comment by jsflax** [comment] 2019-11-02 19:57
Duplicate of #5334.

**Closed by jsflax** 2019-11-02 19:57 UTC
Labels: O-Community, T-Bug-Crash
