### ISSUE TITLE
Crash when terminating an application: "realm::util::Mutex::destroy_failed"

### ISSUE THREAD

**Issue by gonzaloperretti** [realm/realm-cocoa#6148] opened 2019-05-20 15:48 UTC
!!! MANDATORY TO FILL OUT !!!

## Goals

I´m having a crash using realm-cocoa

## Expected Results

Realm should not crash

## Actual Results

Realm is crashing, report using firebase is:

> Crashed: com.apple.main-thread
0  libsystem_kernel.dylib         0x1997cb104 __pthread_kill + 8
1  libsystem_pthread.dylib        0x19984a998 pthread_kill$VARIANT$armv81 + 296
2  libsystem_c.dylib              0x199722d78 abort + 140
3  Realm                          0x108fc2db8 please_report_this_error_to_help_at_realm_dot_io + 10
4  Realm                          0x108fc3098 realm::util::terminate_internal(std::__1::basic_stringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) + 256
5  libsystem_pthread.dylib        0x19984a998 pthread_kill$VARIANT$armv81 + 296
6  Realm                          0x108fc3244 realm::util::terminate(char const*, char const*, long, std::initializer_list<realm::util::Printable>&&) + 392
7  libsystem_pthread.dylib        0x19984a998 pthread_kill$VARIANT$armv81 + 296
8  Realm                          0x108fc3a34 realm::util::Mutex::destroy_failed(int) + 52
9  Realm                          0x108fc4b5c realm::util::Mutex::~Mutex() + 44
10 libsystem_pthread.dylib        0x19984a998 pthread_kill$VARIANT$armv81 + 296
11 libsystem_c.dylib              0x199723ab4 __cxa_finalize_ranges + 384
12 libsystem_c.dylib              0x199723dd8 exit + 24
13 UIKitCore                      0x1c6e3c670 -[UIApplication terminateWithSuccess] + 462

## Version of Realm and Tooling

Realm framework version: realm-cocoa "v3.14.1"

Realm Object Server version: ?

Xcode version: 10.1

iOS/OSX version: 10.14.3

Dependency manager + version: Carthage 0.33.0

**Comment by jedelbo** [comment] 2019-05-22 08:52
Probably a duplicate of https://github.com/realm/realm-core-private/issues/112

**Closed by jedelbo** 2019-05-22 08:52 UTC
Labels: O:User, T:Bug-Crash, T:Duplicate
