### ISSUE TITLE
Updating with nested dictionary breaks RLMArray and RLMObject connections

### ISSUE THREAD

**Issue by Just-** [realm/realm-cocoa#1401] opened 2015-01-23 08:07 UTC
I have such model classes `Room, Channel, User, OptionalBool`. Before updating `User` have an array of followed `Channels` and `OptionalBool` with true value.

```
po [BGUser allObjects]
RLMResults <0x7ffb3065a600> (
	[0] BGUser {
		...
		isMine = OptionalBool {
		value = 1;
	};
		followed = RLMArray <0x7ffb30523480> (
		[0] BGChannel {
			identifier = 53685;
			name = Design;
			isDefault = 1;
		}
	);
```

Then I update `Room` with calling `createOrUpdateInRealm:(RLMRealm *)realm withObject:(id)value`  with a dictionary below

```
{
    channel = "BGChannel {\n\tidentifier = 53685;\n\tname = Design;\n\tisDefault = 1;\n}";
    code = 2;
    createdAt = "2015-01-18 12:43:45 +0000";
    identifier = 5033;
    likes = 1;
    messagesCount = 3;
    ...
    user =     {
        avaUrl = "";
        displayName = "Tom Occhinosen";
        identifier = 2606;
    };
    views = 14;
}
```

And after such update all followed `Channels` and `OptionalBool` connection are cleared.

```
BGUser {
		identifier = 2501;
		displayName = Incognito 1834;
		avaUrl = ;
		isMine = (null);
		followed = RLMArray <0x7ffb32a6c2b0> (
	);
```

That seems like a bug to me because updating `User` directly keeps all connections. What do I do wrong?

**Comment by Just-** [comment] 2015-01-25 13:09
Got this on 0.88.2 and 0.90.0

**Comment by segiddins** [comment] 2015-01-29 23:39
@Just- would it be possible to provide a sample project that demonstrates this issue? It would make it much easier to track down the root cause. If that isn't possible, at least seeing your model definitions would be a great help. thanks!

**Comment by Just-** [comment] 2015-02-02 08:02
See test project with simplified model https://dl.dropbox.com/s/tzsnt79ceso5wa7/RealmNestedUpdates.zip  
Just run `pod install` to install Realm before using. It gives me the next output

```
2015-02-02 10:54:57.092 RealmNestedUpdates[27030:33972436] User: BGUser {
	identifier = 1;
	displayName = SomeUserName;
	isMine = OptionalBool {
	value = 1;
};
	followed = RLMArray <0x7ff8bbc5f2b0> (
	[0] BGChannel {
		identifier = 1;
		name = SomeChannel;
		isDefault = 0;


	}
);
}
2015-02-02 10:54:57.094 RealmNestedUpdates[27030:33972436] User: BGUser {
	identifier = 1;
	displayName = ChangedUserName;
	isMine = OptionalBool {
	value = 1;
};
	followed = RLMArray <0x7ff8be046a30> (

);
}
```
In my project such update also clears `isMine` connection and here it doesn't. But it breaks followed connection as well.

**Comment by segiddins** [comment] 2015-02-02 23:30
@Just- thanks for the example project! I've reproduced the issue.

**Comment by segiddins** [comment] 2015-02-03 00:12
It turns out that the root cause of this bug is https://github.com/realm/realm-cocoa/issues/1362.

**Comment by Just-** [comment] 2015-02-06 09:59
@segiddins glad to help :)

**Comment by jpsim** [comment] 2015-03-25 20:49
This really is a duplicate of #1362, so please continue the conversation in there.

**Closed by jpsim** 2015-03-25 20:49 UTC
Labels: P1
