### ISSUE TITLE
Crash during a write, left us with a database file that was corrupted

### ISSUE THREAD

**Issue by marcvanolmen** [realm/realm-cocoa#2089] opened 2015-06-16 14:09 UTC
First of all sorry for not having more details, but this happened now 2x. 

1. Yesterday I was debugging our app and during write block the app crashed and restarted the phone.
After that I tried to run the app and I notice that the realm database crashed during opening of the file. I was in a hurry and didn't make a copy of the database file, which I now regret but was late...

2. Other case was user that was doing heavy changes with the app, and the app crashed and restarted the phone.  After that Realm couldn't open the project file anymore and he needed to delete app.

Questions: 

a) Is there anything special we should take into account when writing, our write blocks are small updates and only do writes. 
b) Any options we can turn on to make sure that writes are maybe slower but can't cause files to be corrupted?
c) Is there a backup workflow we could do, like store copy in the app, etc.. but not sure how I can recover in that case, because in example 1, it was hard crash from Realm during opening of the file. I was running in debug mode.

marc

**Comment by jpsim** [comment] 2015-06-16 17:19
Hi Marc, it looks like you've hit an issue that we recently fixed in [v0.93.2](https://github.com/realm/realm-cocoa/blob/master/CHANGELOG.md#0932-release-notes-2015-06-12):

> Fix a case where data loss would occur if a device was hard-powered-off shortly after a write transaction was committed which had to expand the Realm file.

If you experience this issue with 0.93.2 or later, then it means there are cases that we were unable to fix and having steps to reproduce would be key to fixing further scenarios.

To answer your questions specifically:

> a) Is there anything special we should take into account when writing, our write blocks are small updates and only do writes.

No, we generally designed Realm to handle any write/read patterns. If you find yourself doing otherwise, please let us know so we can be aware.

> b) Any options we can turn on to make sure that writes are maybe slower but can't cause files to be corrupted?

We may offer an option to have extreme durability guarantees in the future, but that would incur a very significant performance hit, but our team is under the impression that our fix in 0.93.2 will be sufficient to cover all realistic data loss situations.

> c) Is there a backup workflow we could do, like store copy in the app, etc.. but not sure how I can recover in that case, because in example 1, it was hard crash from Realm during opening of the file. I was running in debug mode.

Realm asserts if it finds any corruption in the file, preventing you from handling that scenario. We expect the 0.93.2 to eliminate these situations so that these assertions are never hit.

**Comment by marcvanolmen** [comment] 2015-06-17 02:56
Thanks for the quick feedback! Much appreciated, will be upgrading to this new version in our next update will keep you informed of our testing.

**Comment by jpsim** [comment] 2015-06-17 05:15
Great! Please reopen this issue if you're still experiencing difficulties with the new version.

**Closed by jpsim** 2015-06-17 05:15 UTC
