### ISSUE TITLE
Missing mandatory realm fields in atlas when set to "base" value.

### ISSUE THREAD

**Issue by nobur** [realm/realm-cocoa#7192] opened 2021-03-29 16:13 UTC
## Goals
we don't try to achieve any thing special. we just ace a sync issue.
In Realm Schema, if some fields are tagged "Mandatory" but value entered are an empty string, a 0 value for an int or a false value for a bool, those filed are not passed to Atlas document.

This behavior breaks the sync!

## Expected Results
having all mandatory fields synchronised to Atlas documents.

## Actual Results
a string property set to an empty string is not synced in atlas. Other values work correctly.
a int property set to 0 is not synced in atlas. Other values work correctly.
a boolean property set to false is not synced in atlas. Other values work correctly.

In C# string seems not to be problematic but int and boolean behave identically.

I didn't notice such behavior in node.js

Due to this the sync beween Atlas and Realm is broken (document are missing if modified in atlas). Worse, sync can't be turn  back on ain case of maintenance/schema changes.

only possible solution : correct manually all faulty document by adding all missing document fields.

## Steps for others to Reproduce
Create a simple collection.
Create an Realm App and define a schema for this collection have an int, a string and a boolean property.
Turn on Realm Sync.
Create a simple client App that connect to Sync Realm and create 2  object : 
- 1 initialized with 32 for the int property, "string" for the string property and true for the boolean property
- 1 initialized with 0 for the int property, "" for the string property and false for the boolean property

Compare resultant documents in atlas.

## Code Sample
```
public class License: EmbeddedObject {

    @objc public dynamic var _id:ObjectId = ObjectId.generate()
    @objc public dynamic var __partition:String?
    @objc public dynamic var isEnabled:Bool = false
    @objc public dynamic var comment:String = ""
    @objc public dynamic var extensions:Int = 524287
    @objc public dynamic var maxRegistrationDisplay:Int = 0
    @objc public dynamic var maxDisplayController:Int = 0
    @objc public dynamic var maxCamera:Int = 0
    @objc public dynamic var validUntil:Date?

    public convenience required init(partition:String) {
        self.init()
        self.__partition = partition
    }
}

License(partition: partition)
````

result in atlas : 
```
_id: 6051cc7091942e269dc03b47
__partition: "603a72fd6afac24e45e2be84"
extensions: 524287
```

## Version of Realm and Tooling
Realm framework version: ?
IOS/SwiftUI
CocoaPod SDK version : 10.7.2

Quite the same behavior in C# SDK 10.1.2.0

Realm Object Server version:  no clue.

Xcode version: 12.4

iOS/OSX version: 14.2

Dependency manager + version: ?

for C# VS version 16.8.3

**Comment by nirinchev** [comment] 2021-03-30 00:03
This is a duplicate of https://github.com/realm/realm-dotnet/issues/2165. We'll leave the Cocoa issue open so that people using the Swift SDK can discover it easier, but linking just for the record.

**Comment by nobur** [comment] 2021-04-01 20:00
Hi,

there is something that is mention in the forum that I think it is important to note here as well for those who find this issue: 
The problem occurs when objects are added to realm with the parameter `.modified`.

the source => https://developer.mongodb.com/community/forums/t/i-cannot-synchronize-data-between-mongodb-atlas-cluster-and-client-application/10075/9

regards.

**Comment by jsflax** [comment] 2021-09-07 16:22
This has since been fixed cloud side.

**Closed by jsflax** 2021-09-07 16:22 UTC
Labels: O-Community
