### ISSUE TITLE
Idea: makeObjectsPerformSelector:

### ISSUE THREAD

**Issue by OlegAnghelov** [realm/realm-cocoa#1760] opened 2015-04-15 15:41 UTC
Hi all!

First of all: could you please clarify what are the cases when we should post to google groups and when on github?

And back to the topic:
Are you planning on implementing `makeObjectsPerformSelector:` on your `RLMArray`?

**Comment by segiddins** [comment] 2015-04-15 18:27
I don't think we had any plans to add `makeObjectsPerformSelector:` to `RLMCollection`, because fast enumeration is almost as concise, and doesn't require adding new APIs:

```objc
RLMArray *array = ...;
for (RLMObject *object in array) {
   [object doFoo];
}
```

As for the mailing list vs. GitHub: issues should generally be used to file bugs with Realm and request new features, whereas the mailing list is a better place for discussion and debugging your own code to take place. Hope that helps!

**Comment by OlegAnghelov** [comment] 2015-04-16 08:10
There is an issue that appears... 

My goal: 
drop from database "all dogs that belong to a particular owner".

I might be doing something wrong, but here is the code:
```objective-c
RLMRealm *realm = [RLMRealm defaultRealm];
    [realm transactionWithBlock:^{
        for (id model in typedArray) {
            [realm deleteObject:model];
        }
    }];
```
Where `array ` is an `RLMArray` of a one-to-many relationship. 
I get the `Terminating app due to uncaught exception 'RLMException', reason: 'Collection was mutated while being enumerated.'`.
What is wrong in my approach?

**Comment by kishikawakatsumi** [comment] 2015-04-16 16:28
The issue is due to the feature of Realm that RLMArray (and RLMResults) are always up to date.
If you will delete all objects in `typedArray`, use `RLMRealm#deleteObjects:` (deleteObject**"s"** method).

Like below:

```objc
RLMRealm *realm = [RLMRealm defaultRealm];
[realm transactionWithBlock:^{
    [realm deleteObjects:typedArray];
}];
```

See also:
https://github.com/realm/realm-cocoa/issues/1643
https://github.com/realm/realm-cocoa/issues/1561

**Comment by jpsim** [comment] 2015-04-17 00:44
@kishikawakatsumi is correct. I'm closing this issue because I agree with @segiddins that adding this functionality wouldn't add much value over performing operations during fast enumeration.

@OlegAnghelov please let us know if there are cases where `makeObjectsPerformSelector:` allows doing things that are not currently possible.

**Closed by jpsim** 2015-04-17 00:44 UTC
