### ISSUE TITLE
Make compact() method publicly available

### ISSUE THREAD

**Issue by kevincador** [realm/realm-cocoa#4137] opened 2016-09-26 11:43 UTC
Would it be possible to publicly expose compact()? We are currently using it because or synchronisation process is done in a way that a lot of objects are deleted and created again. This inflates the database file to things like 3.5 gigabytes if we don't compact.

We are compacting the database at launch before anything else is done. We know it is not safe but we prefer to have the app crash once and reboot with a compacted file than having lots of crashes without a way to recover.

Thanks.

**Comment by jpsim** [comment] 2016-09-26 17:47
I'd say this is a duplicate of #1243 and #3289. Closing.

**Closed by jpsim** 2016-09-26 17:47 UTC
Labels: T:Enhancement
