### ISSUE TITLE
Open encrypted Realm DB with Realm studio get error "Opening Realm files of format version 0 is not supported by this version of Realm"

### ISSUE THREAD

**Issue by itenyh** [realm/realm-cocoa#6751] opened 2020-09-10 13:23 UTC
!!! MANDATORY TO FILL OUT !!!

## Goals

1.  open the encrypted Realm DB with realm studio
2. perform CRUD without error in my program

## Expected Results
1.  open the DB file with realm studio I should get one of the following results:
     (1)  it is opened correctly without any info
     (2) asking me to upgrade the DB file before opened
     (3) show me "Opening Realm files of format version x is not supported by this version of Realm" x is bigger than 0.

2. when running my program: if one of the first two options of 1 is met, the program will not crash; if it is the third condition, I could upgrade the realm to solve the problem. 

## Actual Results
1.  open the DB file with realm studio, and it show me "Opening Realm files of format version 0 is not supported by this version of Realm"
2. perform CRUD in my program and it crashes with info "The Realm file format must be allowed to be upgraded in order to proceed."

Upgrade the realm studio or the realm version of my program will not help.

## More Info
1. if do not encrypt,  everything works fine !
2. if encrypt, when I wrote all the datas which make the file size bigger than 100MB,  error happen. But If I wrote part of the datas which make the file size around 40MB, no error happen.

## Code Sample

- (RLMRealm *)_defaultRealm {
    RLMRealmConfiguration *config = [RLMRealmConfiguration defaultConfiguration];
    config.fileURL = [[config.fileURL URLByDeletingLastPathComponent]
                      URLByAppendingPathComponent:REALM_NAME];
    [RLMRealmConfiguration setDefaultConfiguration:config];
    NSError *error;
    RLMRealm *realm = [RLMRealm realmWithConfiguration:config error:&error];
    if (error) {
        NSLog(@"Error opening realm: %@", error);
        return nil;
    }
    
    return realm;
}

[realm transactionWithBlock:^{
        [realm addObjects:objs];
        NSLog(@"realm create finish!");
    }];

[realm writeCopyToURL:[NSURL URLWithString:documentPath] encryptionKey:key error:&error];

## Version of Realm and Tooling

Realm framework version:  tried all main version

Xcode version: XCode 11

iOS/OSX version: 13.3

**Comment by pavel-ship-it** [comment] 2020-09-10 15:10
Hi @itenyh 
it could be a migration problem. Could you please refer the documentation on [local migrations](https://realm.io/docs/objc/latest/#migrations)?
Try to promote the `schemaVersion` and provide a `migrationBlock` if required.
_Don't forget to make a backup of a target Realm file!_

**Comment by itenyh** [comment] 2020-09-11 01:13
@pavel-ship-it    I am sure its no a problem about migration, because I create a new realm DB with datas from other source. But it could not open with realm studio.

**Comment by xiejunyuan** [comment] 2020-09-11 01:40
@itenyh I encountered the same situation as you

**Comment by owenzhao** [comment] 2020-09-11 06:05
Did you upgrade to Realm Cocoa 5.4.0? It requires Realm Studio 3.12, which is not released. You probably are using 3.11.

**Comment by itenyh** [comment] 2020-09-11 14:18
@owenzhao  I tried several version of Realm Cocoa combine with different version of Realm Studio and I draw the conclusion as described above.

**Comment by pavel-ship-it** [comment] 2020-09-11 17:08
@itenyh The next week we're expecting the release of the Realm Studio 3.12. Could you please try your database against this version?

**Comment by owenzhao** [comment] 2020-09-12 02:38
> @owenzhao I tried several version of Realm Cocoa combine with different version of Realm Studio and I draw the conclusion as described above.

You should aware that Realm Cocoa 5.4.0 is format breaking. Once you installed 5.4.0, all other version realms prior to 5.4.0 cannot deal with the database 5.4.0 created. So you may just doing extra work for nothing.

**Comment by itenyh** [comment] 2020-09-12 08:49
@owenzhao  To better express my idea, I create three sample realm DB:

1 - encrypt can not open :  this one is encrypted and has a comparatively larger size. When open with Realm studio I get "Opening Realm files of format version 0 is not supported by this version of Realm".

2 - not encrypt can open: this one is not encrypted and has exactly the same data as 1.  It can be opened by Realm studio correctly.

3 - encrypt can open:   this one is encrypted and has a comparatively smaller size.  It can be opened by Realm studio with 
 encryption key correctly.

Datas Created with Realm Version: 5.3.6
Realm Studio Version: 3.11.0
key: 30633537303236663361323264383565313834353465306465666537363265636239333761616566323832303331363034616538363161613933626139373735
Datas:  [https://drive.google.com/file/d/1i3JyMAu181FLTX1wE8kZK_HmiwYAFYOO/view?usp=sharing](url)

**Comment by owenzhao** [comment] 2020-09-12 10:10
After a little search I found this issue was widely happened across all Realm implementations with js, java and cocoa, on encrypted big realm databases.

js https://github.com/realm/realm-js/issues/3002
java https://github.com/realm/realm-java/issues/6889
cocoa https://github.com/realm/realm-cocoa/issues/6638
cocoa https://github.com/realm/realm-cocoa/issues/6692

@iteyh Are you sure that the "2 - not encrypt can open.realm" file will get this issue right after it is encrypted? If that is true. I believe it will be very useful when the developer of realm could use this file.

**Comment by itenyh** [comment] 2020-09-12 22:03
@owenzhao   Yes, quite sure and you can use these samples as you want.  I find that I set the schemaVersion to be 5 when I create these samples, but I think it does not matter. 

One more point is that, before upgrading to 5.3.6 I used 3.11.2 which can encrypt and decrypt the big realm DB correctly.

Hope this issue could be fixed as soon as possible, otherwise I can not publish my application safely, thanks!

**Comment by owenzhao** [comment] 2020-09-13 04:54
@tgoyne

I have just done a research of mine. I created a very simple model.

```swift
class Model:Object {
    @objc dynamic var id = 0
    @objc dynamic var value = 1
    
    override class func primaryKey() -> String? {
        return "id"
    }
}
```

And then write as many items of the model as possible to the disk. Each time, I will remove the realm file manually in Finder.

```swift
private func run() {
    let keyString = "30633537303236663361323264383565313834353465306465666537363265636239333761616566323832303331363034616538363161613933626139373735"
    let key = keyString.hexDecodedData()
    
    let config = Realm.Configuration(encryptionKey: key)
    let realm = try! Realm(configuration: config)
    
    let max = 187_0908
    var index = 0
    var array = [Model]()
    
    while index < max {
        let m = Model()
        m.id = index
        array.append(m)
        index += 1
    }
    
    try! realm.write {
        realm.add(array, update: .all)
    }
}
```

I found something that seemed not right.

1. When max was 187_0908, the size of encrypted database was 79 MB. The file couldn't be opened again.
2. When max was 187_0907, just one minus, the size would be 67.7 MB. The file could be opened again.

So it seems that the only issue is the encryption part. When a database is bigger to some point, the encryption will make the database unusable. The encryption also makes the file get even bigger than it should.

RealmSwift 5.3.6
Xcode 11.7
macOS 10.15.6
Realm Studio 3.11

For RealmSwift 5.4.0, the result will be the same. But there is no suitable Realm Studio availalbe.

**Comment by jedelbo** [comment] 2020-09-14 14:04
@leemaguire was able to reproduce this and created a file that fails to open. I will create a Core test case.

**Comment by jedelbo** [comment] 2020-09-14 16:27
Root cause of this problem has been found.

**Comment by jedelbo** [comment] 2020-09-14 18:27
Duplicate of https://github.com/realm/realm-java/issues/6889

**Closed** 2020-09-14 18:27 UTC
Labels: O-Community, T-Duplicate
