### ISSUE TITLE
Can't merge user_target_xcconfig 

### ISSUE THREAD

**Issue by keyclipse** [realm/realm-cocoa#2365] opened 2015-08-10 02:42 UTC
Hi, 

I have this issue with cocoapod 0.38.2 installation...

[!] Can't merge user_target_xcconfig for pod targets: ["Realm", "Headers", "pop"]. Singular build setting CLANG_CXX_LANGUAGE_STANDARD has different values.

[!] Can't merge user_target_xcconfig for pod targets: ["Realm", "Headers", "pop"]. Singular build setting CLANG_CXX_LANGUAGE_STANDARD has different values.

Is there any easy way to fix this?

**Comment by segiddins** [comment] 2015-08-10 02:43
There's no real way around this at the moment, at least until https://github.com/CocoaPods/CocoaPods/pull/3916 and https://github.com/realm/realm-cocoa/pull/2262 are merged.

**Comment by keyclipse** [comment] 2015-08-10 02:47
Maybe can merge it to a branch like "0.38 cocoapod" branch?

**Comment by segiddins** [comment] 2015-08-10 02:51
Well, it relies on that CocoaPods PR also being finished, so it wouldn't be of much use now.

**Comment by segiddins** [comment] 2015-08-10 17:44
Since the CocoaPods PR was merged, if you're using CocoaPods master, you can point your Podfile to the `mr-podspec-config` branch in the meantime.

**Comment by segiddins** [comment] 2015-08-21 01:51
I'm going to close this as a duplicate of https://github.com/realm/realm-cocoa/issues/2053,  but you can definitely use the `mr-podspec-config` branch until it's merged!

**Closed by segiddins** 2015-08-21 01:51 UTC
