### ISSUE TITLE
Cannot open Realm at default path from Safari App Extension

### ISSUE THREAD

**Issue by jpsim** [realm/realm-cocoa#4502] opened 2017-01-03 19:25 UTC
See this twitter thread: https://twitter.com/andreipetre/status/812379854012293120

and this GitHub repo demonstrating a repro case: https://github.com/andreipetre/sample-mac-app-extension

I haven't validated this yet.

/cc @andreipetre

**Comment by bdash** [comment] 2017-01-03 19:53
The error messages in andreipetre/sample-mac-app-extension#1 look like they're networking related (perhaps a failure to submit analytics?). @andreipetre, are you seeing any problems besides the error messages in the output?

**Comment by andreipetre** [comment] 2017-01-06 15:36
@bdash No, that's the entire output. Nothing else appears in the Xcode console output.

**Comment by bdash** [comment] 2017-01-06 17:40
Thanks. To be clear, the error message itself is the only problem, and everything else behaves correctly?

**Comment by andreipetre** [comment] 2017-01-06 19:48
The issue is that I couldn't use Realm in a Safari App Extension, not event to initialise it. The crash happens at the initialisation phase, i.e. `let realm = try! Realm()`, so it never gets to the other steps like querying or adding objets. For example, this code

```swift
let realm = try! Realm()
try! realm.write {
    realm.add(someObj)
}
```

would crash at the first line. `realm.write` would never be executed.

However, I have now moved to using app groups as a shared location for the Realm database, for both the parent mac app and the safari app extension. With this setup I can successfully initialise Realm and add objects to the database. I will keep you posted if I run into any Realm operations that don't work from the Safari App Extension.

_Side note_
I may be completely wrong about this, but considering that it works when using an app group directory as the Realm database location and it doesn't work when using the default Realm settings, might indicate that Realm is not able to use the default settings (like database location) when used from within a Safari App Extension. Just a thought.

**Comment by bdash** [comment] 2017-01-06 20:04
Ah, thanks for clarifying! I'd completely misunderstood the problem.

**Comment by cliftonlabrum** [comment] 2017-07-11 17:07
In case it's helpful, I was getting this same error on a Mac app. It started happening after I enabled the **App Sandbox** entitlement. But once I checked the two boxes in the entitlement that allow for networking, I was good to go. 
<img width="499" alt="appsandbox" src="https://user-images.githubusercontent.com/2513753/28080409-c3c4ee46-6620-11e7-87d7-06118455161d.png">

**Comment by andreipetre** [comment] 2017-07-12 12:32
Thanks @cliftonlabrum What you're saying sounds familiar and I might have done the same while fiddling around to try and solve the issue.

**Comment by kishikawakatsumi** [comment] 2017-09-01 17:00
@andreipetre @cliftonlabrum I cannot reproduce the crash. I confirmed that I can instantiate/write/read Realm correctly in your project  https://github.com/andreipetre/sample-mac-app-extension. The only change is upgrading Realm to the latest version (`v2.10.0`) because it cannot be built with Xcode 8.3.

Could you try again with the latest version of Realm?
Also, can we close this issue?

**Comment by andreipetre** [comment] 2017-09-01 18:46
Sure, feel free to close the issue. Thanks!

**Closed** 2017-09-05 07:44 UTC
Labels: P:2 Expected, T:Bug
