### ISSUE TITLE
sumOfProperty wrong

### ISSUE THREAD

**Issue by shaozi** [realm/realm-cocoa#2984] opened 2015-12-11 05:31 UTC
Hi, Please see the question on SO: http://stackoverflow.com/q/34216584/528629
I did a deleteAllObjects and then add them back quickly. But the sumOfProperty gives me 0 instead of the correct sum. Meanwhile, a for loop that add each works.

**Comment by mrackwitz** [comment] 2015-12-11 17:54
Hey, I saw your question and gave some first general hints in the comments, but I couldn't yet figure out where this difference is originating from just from the snippets you posted there. Could you share a simple sample project with us, which reproduces this behavior? You can also send us code privately to help@realm.io.

**Comment by shaozi** [comment] 2015-12-12 14:19
I created a repository: https://github.com/shaozi/RealmSumReproduce.git

**Comment by bdash** [comment] 2015-12-12 18:11
Thanks for the excellent test case, @shaozi! I was able to reproduce the problem by following your instructions, and could easily see where the bug is.

The underlying issue is that `TableView` appears to fail to update `m_num_detached_refs` in some cases. This can result in `TableViewBase::aggregate` thinking that all refs in the table view are detached, causing it to early-exit with a result of 0. It can also result in an incorrect result when the table view is empty, since the assumption is that for an empty table view `m_num_detached_refs` will be zero. This will need to be fixed in core. I'll file a core issue once I have a chance to boil the test case down to something that uses core directly.

**Comment by shaozi** [comment] 2015-12-12 18:30
Great! Once it is fixed, will this method be faster than loop and sum?

**Comment by mrackwitz** [comment] 2015-12-14 19:35
@shaozi: Yes, once this is fixed, it should be vastly faster than looping manually over the objects. Internally we're able to iterate over all relevant values of the column and to add up those without having to instantiate full accessor objects in the Objective-C runtime for every object in the array.

**Comment by shaozi** [comment] 2016-01-21 23:19
When will the fix be merged?

**Comment by jpsim** [comment] 2016-01-21 23:30
> When will the fix be merged?

It's fixed in core, but we need a new release of our core binaries, which should happen soon.

**Comment by jpsim** [comment] 2016-01-26 19:07
A fix for this was merged in #3015. Thanks all for reporting this and helping us identify what was wrong!

**Closed by jpsim** 2016-01-26 19:07 UTC
Labels: bug, P1
