### ISSUE TITLE
header_mappings_dir probably points to wrong directory

### ISSUE THREAD

**Issue by TadeasKriz** [realm/realm-cocoa#3085] opened 2016-01-10 00:59 UTC
With Cocoapods 1.0.0.beta2, Realm cannot be compiled because it cannot find headers under `realm/` etc. For example line `#include <realm/util/features.h>` fails because the header directories are flattened. The `pod lib lint` should throw errors in the new Cocoapods 1.0.0.beta2 version.

**Comment by jpsim** [comment] 2016-01-12 17:39
Closing as a duplicate of #3052.

**Closed by jpsim** 2016-01-12 17:39 UTC
Labels: bug, P1
