### ISSUE TITLE
Calling resolve on a ThreadSafeReference does not give an updated version of the object.

### ISSUE THREAD

**Issue by HHK1** [realm/realm-cocoa#5420] opened 2017-10-23 21:45 UTC
## Goals
I want to get an updated version of an object that was created on a different thread. Because that object can be deleted at that point, I check if the object has been invalidated before updating it, and I make changes to it.

## Expected Results
I get the object on the new background thread I'm working on with a ThreadSafeRerence that I resolve. I check if the object has been invalidated, and it's not.
I make my changes in a write transaction on the realm for that thread. I expect the write transaction to work, as the object should be up to date.

## Actual Results

I get an exception inside the write transaction even though I checked the invalidated:
RLMException(@"Object has been deleted or invalidated.");

If I check the isInvalidated property of my object **inside** the write block, I don't have this exception.
However the documentation of `resolve` states the following:
>  Returns `nil` if this object was deleted after the reference was created.

This leads me to think that it is not the correct behaviour for the function.

## Steps to Reproduce

Create a ThreadSafeReference to an object that has been saved into the Realm.
Delete it
On another thread, resolve the reference, and check if the object has been invalidated. It should say it's not.
Modify the object in a write transaction. Object is now invalidated, as the realms have now been resolved. 

## Code Sample

````
let threadReference = ThreadSafeReference(to: object)
        
 backgroundTask().onSuccess(context) { (infoForObject) in
    guard let realm = try? Realm(), let object = realm.resolve(threadReference), !object.isInvalidated else {
        promise.failure(Error.unexpected(reason: "Object was deleted or invalidated)"))
            return
        }
        do {
            try realm.write {
               object.info = infoForObject
            }
            promise.success(object)
        } catch let error {     
            print(error)       
        }
    }.onFailure { (error) in
            promise.failure(error)
    }
    return promise.future
}
````

## Version of Realm and Tooling
framework version: 3.0.0

Realm Object Server version: N/A

Xcode version: 9.0.1 (9A1004)

iOS/OSX version: 11.0.3

Dependency manager + version: Cocoapods 1.3.1

**Comment by tgoyne** [comment] 2017-10-23 22:07
This is the intended behavior. Resolving a thread-safe reference is not guaranteed to refresh the Realm it is imported in to, so if that Realm has not been refreshed since the write transaction deleting the object was made then the object will still exist in the version that the Realm is looking at.

**Closed** 2017-10-27 23:04 UTC
