### ISSUE TITLE
[RealmSwift] CocoaPods cannot find Realm.h when resolving RealmSwift's private modulemap

### ISSUE THREAD

**Issue by e7hz3r0** [realm/realm-cocoa#1918] opened 2015-05-12 12:36 UTC
Firstly, awesome product, guys, it's really a joy to use!

Context:
Using Cocoapods 0.37.1
Targeting iOS 8.0
Language: Swift

I was using Realm cocoa until I upgraded to 0.92.2 two days ago. Everything was working great until the upgrade. Now I get the above error when building. 

I read the new, updated instructions for RealmSwift, altered my Podfile to use that instead of Realm, and changed my imports from Realm to RealmSwift (and RLMRealm to Realm, etc).

**Comment by alexdd55** [comment] 2015-05-12 14:18
same here. needed to downgrade back again.

**Comment by jpsim** [comment] 2015-05-12 20:52
Have you tried forcing the reinstallation of Realm & Realm Swift?

```
rm -r Pods/Realm*
rm -r ~/Library/Caches/CocoaPods/Pods/Released/Realm*
pod install
```

**Comment by e7hz3r0** [comment] 2015-05-13 00:13
I did try that, yes. No joy.

**Comment by jpsim** [comment] 2015-05-13 00:31
Perhaps your Xcode project is set up differently than what we're using to test this on our end?

We verify our that our installation methods (including CocoaPods) work every time we push code to the `master` branch and those tests continue to pass.

Can you try running `pod install` with the following project and let us know if it works for you? https://github.com/realm/realm-cocoa-installation-samples/tree/master/ios/swift/CocoaPodsExample

If it does, I suspect your Xcode project's configuration is preventing Realm Swift from being installed properly. If it doesn't, I suspect there's something wrong with your local version of CocoaPods.

**Comment by e7hz3r0** [comment] 2015-05-15 19:07
That example project worked fine for me.

I'll take another look at my project to see if I can spot anything suspicious.

**Comment by kapoorsahil** [comment] 2015-05-19 15:32
Same issue with me.

**Comment by kapoorsahil** [comment] 2015-05-20 07:45
I am having same issue. Downgrading to 0.92.2 also didn't work for me. Hey, have you find any solution? Why has this issue been removed from pending?

**Comment by e7hz3r0** [comment] 2015-05-20 09:24
So far, the only solution I found is to downgrade to 0.91. Still trying to find another one though.

**Comment by kapoorsahil** [comment] 2015-05-20 10:03
Cloning my project afresh and installing 0.92.3 worked for me. (Pods directory was in .gitignore, so wasn't synced)

**Comment by e7hz3r0** [comment] 2015-05-20 13:21
That didn't work for me, unfortunately.

**Comment by segiddins** [comment] 2015-05-22 16:31
@e7hz3r0 can you please share a project with us that reproduces the issue you were seeing?

**Comment by staticdreams** [comment] 2015-05-22 19:28
I'm now also getting this problem with the newest version.
Made me start new project from scratch.. but as soon as I included ``import RealmSwift`` and hit build got this error. 
``[...]/Pods/Realm/Realm/module.modulemap:2:21: Umbrella header 'Realm.h' not found``
Cleaning / purging / rebuilding wouldn't help.
I also tried including a bridging file (something I don't have to do since RealmSwift came out), but to no avail. I'm using cocoapods installation as usual

**Comment by jpsim** [comment] 2015-05-22 19:50
I recommend that everyone who is having trouble installing Realm Swift via CocoaPods try our installation example as noted in my previous comment (https://github.com/realm/realm-cocoa/issues/1918#issuecomment-101467542). This should help you (and us) narrow down why it's not working on your machine or in your project.

**Comment by staticdreams** [comment] 2015-05-23 07:19
I did some digging and here's what I have found.
I had two new projects which were identical (both using cocoapods), but with the difference that one (project 1) contained a bunch of cocoa pods and the other (project 2) just RealmSwift (and Realm as dependency).

Project 2 would build right away. Project 1 wouldn't. Long story short:
I managed to build Project 1 AFTER I stopped using obj-c header file  and removed these two options from target Build Settings:
![screen_shot_2015-05-23_at_08_59_57](https://cloud.githubusercontent.com/assets/988705/7782854/ed95be64-012b-11e5-93f6-6f2e18d91d5b.jpg)

The main pain being User Header Search Paths (which is installed when adding obj-c header file and looks something line this ``$(SRCROOT)``) but I guess I still need this for non swift pods to play along?

Hope that helps fixing this.

**Comment by jpsim** [comment] 2015-05-26 20:44
Thanks for posting those steps, @staticdreams. I can't necessarily confirm that they're appropriate, but then again I haven't been able to reproduce this issue myself, so it's worth a shot.

I'll be closing this issue for the time being, but will reopen if we see more reports of `Umbrella header Realm.h not found from module.modulemap`.

**Comment by e7hz3r0** [comment] 2015-05-27 00:45
I've recreated the issue in a new project (sorry, I would have done this sooner except is was a long weekend in the US): https://github.com/e7hz3r0/RealmSwift-Test-App

**Comment by jpsim** [comment] 2015-05-27 00:47
Ok, we'll take a look, thanks!

**Comment by jpsim** [comment] 2015-05-28 01:16
I believe I've identified the problem and have filed a PR against your sample project here: https://github.com/e7hz3r0/RealmSwift-Test-App/pull/1. Let's continue the conversation there, as I don't believe this is an issue with Realm, but rather a CoocaPods limitation.

**Closed by jpsim** 2015-05-28 01:16 UTC
Labels: bug, P1

**Comment by e7hz3r0** [comment] 2015-05-29 14:07
Okay, interesting. After merging that PR, I played around a little and found that I could only use RealmSwift and Evernote (necessary for the project that I originally found the problem in) if I:
 1. Didn't use CocoaPods at all and included both frameworks manually
 2. Used CocoaPods for Evernote, but included RealmSwift manually

So using CocoaPods for RealmSwift and *not* for Evernote, resulted in the same issue as above. This is unfortunate because Realm updates more frequently than Evernote.

**Comment by jpsim** [comment] 2015-05-29 17:24
You could also update Evernote's podspec to support building with `use_frameworks!`.

**Comment by i-schuetz** [comment] 2015-07-13 19:58
I algo got this error, installed realm the first time, v.0.93.2

I have a multitarget project (OSX/iOS) and I'm using a bridging header for both.

User Header Search Paths is set to Pods/**, I need this to get my pods working.

This is my podfile:

```ruby
def shared
    use_frameworks!
    pod 'Alamofire', '~> 1.2'
    pod 'Valet', '~> 1.3'
    pod 'RealmSwift'
end

target ‘myproj_osx' do
    platform :osx, '10.10'
    shared
end

target 'myproj_ios’ do
    platform :ios, '8.0'
    pod 'WYPopoverController', '~> 0.2.2'
    shared
end

target 'myproj_tests' do
    platform :osx, '10.10'
    shared
    pod 'Quick', '~> 0.3.0'
    pod 'Nimble', '~> 0.4.0'

end
```

Before adding realm everything was working...

**Comment by i-schuetz** [comment] 2015-07-13 22:19
I found the issue -  it was the Pods/** in the User Header Search Paths. I added this to fix an issue I had in the past with the multitarget setup, but it seems to be gone now. I removed it and everything works.

I also cleaned up the pods installation directories as @segiddins suggested in the [mailing list](https://groups.google.com/forum/#!topic/realm-cocoa/qgsQc7CpCMA), which probably is the reason that it works now without Pods/**.

**Comment by karzler** [comment] 2016-01-06 15:43
@i-schuetz I faced the same issue just now. Pods/** just worked for me like a charm! Thanks!

**Comment by jplazcano87** [comment] 2016-02-15 13:20
I have the same problem, i just swich between branches in my project, run pod install and this error appear  the ```Pods/**. ``` didn't work for me because i did't do anything with my project build config.
The error appeared just by creating another branch and run pod install.
I have reviewed other solutions like delete the pods cache and pod folder, and run ```pod install``` again but still no luck

**Comment by jpsim** [comment] 2016-02-15 17:25
CocoaPods doesn't support mixing frameworks with non-frameworks in your Podfile. Please use only frameworks or none at all.

**Comment by frgmt** [comment] 2016-03-15 11:44
I've got the same issue and can't fix it. Even with all hints and tips described here in the comments I still have this issue.

**Comment by mrackwitz** [comment] 2016-03-15 12:44
@frgmt: Which version of the toolchain and CocoaPods do you use?

**Comment by jplazcano87** [comment] 2016-03-15 12:49
I solved the problem by deleting the cocoapods gem 
```

# remove all old versions of the gem
gem cleanup cocoapods

# choose which ones you want to remove
gem uninstall cocoapods
```

and deleting all the pods folders, then i run 
```
sudo gem install cocoapods
```
and finally 

```
pod install
```

**Comment by mrackwitz** [comment] 2016-03-15 13:06
@jplazcano87: Thanks for reporting that here. Note that you can always use `pod --version` to validate which version of CocoaPods will be executed, if you have multiple versions installed at different paths, so it depends on your environment. You can select one specific by running e.g. `pod _0.39.0_ install`.

**Comment by frgmt** [comment] 2016-03-15 14:39
I got it work with updating to beta version 1.0.0.beta.6 of CocoaPods. 
Everything else wasn't working for me.

**Comment by wishsoul** [comment] 2016-03-18 09:48
It worked for me.
1.sudo gem uninstall cocoapods -v 0.39
2.sudo gem install cocoapods -v 0.38.2

**Comment by lakhman** [comment] 2016-04-13 20:50
maybe this will help someone else, but I had to use `Pods/**/**` (Notice the extra `/**`).

Spent a whole day debugging this! :@

**Comment by rdlopes** [comment] 2016-04-19 00:13
If that can help... contrary to other pods, Realm doesn't expose its public headers in the public section, but in the project one.
Putting them back in the correct section solves the issue.

**Comment by bdash** [comment] 2016-04-19 00:53
@rdlopes, if you're seeing problems integrating Realm using CocoaPods, please file a new issue with information about which version of Realm you're attempting to use and with which version of CocoaPods you're seeing the problem with. To the best of our knowledge both Realm and RealmSwift work correctly with CocoaPods v0.39 and the 1.0.0 betas (from beta 4 onwards). If there are problems we'd like to hear about them and address them.

**Comment by fpillet** [comment] 2016-05-26 16:01
FWIW I just had the same issue and after some head scratching, moved `Realm-iOS` and `Realm-OSX` headers from the `Project Headers` section to the `Public Headers` section and that did the trick.

**Comment by rdlopes** [comment] 2016-05-26 16:42
@bdash I don't have problems with Realm cause I stopped using it, felt too unstable.

But you do have a problem, and I was providing you with the solution.

Simple.

PS: first time I get a "file a bug" reply when I'm providing help.

**Comment by jpsim** [comment] 2016-05-26 18:30
@rdlopes we appreciate the time you've taken to share the issues you've faced and the workarounds that worked for you. The reality is that we get a large number of reports that omit crucial details like the versions of Realm and other relevant tools like CocoaPods and in these cases we encourage users to file more detailed bug reports so we can better help you.

@fpillet I think you may have been bit by CocoaPods/CocoaPods#5313 which, despite our best efforts to support CocoaPods 1.0 in its RC phase, snuck in before the official release 😬 . @mrackwitz has already submitted a fix to CocoaPods (CocoaPods/CocoaPods#5352) which should be included in CocoaPods 1.0.1. Until then, we recommend OS X builders to use CocoaPods 0.39.0. I apologize for the inconvenience.

**Comment by fpillet** [comment] 2016-05-26 19:20
@jpsim thanks for the additional info. Yes it looks like that's what happened! Not complaining though, I assumed that this was an issue with CP rather than with Realm itself.

**Comment by rdlopes** [comment] 2016-05-26 19:59
@jpsim sorry I'm stranger to bullshit especially when I get a "I don't know any problem with Realm" while we're discussing a problem with Realm...

Again, I'm not sharing my "problems", I'm providing the users with the workaround, while you're still figuring out why you don't have your headers in the public section.

The rest is white noise, cause that's not my problem if you're struggling with issues management.

So stop the "thanks for sharing but bla bla bla and eventually f*ck off" line and don't assert you don't have any problems at all when we're discussing a problem.

That would be a perfect start and would avoid flaming by posters when they get replied with handful of bullshit.

**Comment by jpsim** [comment] 2016-05-26 20:58
I'm sorry for not being more clear, we appreciate you sharing your workaround, which is likely necessary due to CocoaPods/CocoaPods#5313, which has since been fixed in CocoaPods.

I'm afraid this conversation is no longer civil and am forced to lock this conversation. We encourage any further problems with CocoaPods integration to be [filed as a new issue](https://github.com/realm/realm-cocoa/issues/new).
