### ISSUE TITLE
valueForKey: returns nil for primaryKey property when using dynamic API

### ISSUE THREAD

**Issue by stel** [realm/realm-cocoa#4185] opened 2016-10-05 13:12 UTC
Addressed to https://github.com/realm/realm-browser-osx/issues/181

Code to reproduce:

``` Swift
let configuration = RLMRealmConfiguration()

configuration.dynamic = true
configuration.fileURL = URL(fileURLWithPath: "saframaxPedidosMobile.realm") // see attached file in https://github.com/realm/realm-browser-osx/issues/181

let realm = try! RLMRealm(configuration: configuration)

let sequence = realm.allObjects("Sequence").firstObject()!

assert(sequence["entityName"] != nil)
assert(sequence.value(forKey: "entityName") != nil) // <-- false
```

**Comment by kishikawakatsumi** [comment] 2017-08-30 13:45
This is not a bug. Since `NSObject` has an `entityName` instance method on macOS, so `valueForKey: @"entityName"` calls the `NSObject`'s `entityName` method instead of Realm's accessor.

We can avoid this problem by using subscripting. Subscripting does not follow the KVC calling convention.

I think that it is better to leave the KVC behavior as it is. 

I think we can close this issue. What's your opinion on this? @stel @tgoyne @bdash

**Comment by kishikawakatsumi** [comment] 2017-09-19 14:34
Closing it works as expected.

**Closed by kishikawakatsumi** 2017-09-19 14:34 UTC
Labels: P:2 Expected, T:Bug
