### ISSUE TITLE
[Swift] Copying object to another realm doesn't copy nested relationships

### ISSUE THREAD

**Issue by allbto** [realm/realm-cocoa#2754] opened 2015-10-27 13:21 UTC
I'm trying to copy an Object from one Realm to another using the method `Realm.create(type:, value:, update:)`

My database schema looks like this:

```
Device {
    ...
    List<Mood>
    ...
}

Mood {
    ...
    List<Schedule>
    ...
}

Schedule {
    ...
}
```

So I have a Device contained in my default realm, and here is how I try to copy it to another realm:

```swift
// let device: Device = ...

let editRealm = try! Realm(configuration: Realm.Configuration(inMemoryIdentifier: "AnIdentifier"))

editRealm.beginWrite()
let editDevice = editRealm.create(Device.self, value: device, update: true)
editRealm.commitWrite()
```

What happens is that I get the list of `Mood` in my `editDevice` but the `Mood` have an empty list of `Schedule`. They contained a few `Schedule` each on the main Realm.

Am I doing something wrong ? Should I implement a custom copy method for my `Device` ?

XCode 7.0.1, Swift 2.0, Realm 0.95.1

**Comment by bigfish24** [comment] 2015-10-28 17:27
Are all of the nested objects persisted?

**Comment by allbto** [comment] 2015-11-02 13:03
@bigfish24 Yes, I just checked, they belong to a realm and an objectSchema, they even appear on Realm Browser.

**Comment by bigfish24** [comment] 2015-11-06 23:20
@allbto could you provide a sample project? The reason being is that internally we should be handling nested relationships. The process should be working like this:

1. Swift `create()`
2. ObjC++ `RLMCreateObjectInRealmWithValue`
3. ObjC++ `RLMDynamicSet` when setting the property values
4. ObjC++ `RLMGetLinkedObjectForValue` to retrieve/create the linked object(s) for the property
5. ObjC++ `RLMCreateObjectInRealmWithValue` to create the linked object(s) for the property

If you can't provide any code, you can verify this path is occurring from the `create()` call.

**Comment by TimOliver** [comment] 2015-11-12 04:09
Hi @allbto!

Just touching base on this issue; are you able to provide us with a sample project to test this functionality?

Thanks! :)

**Comment by smpanaro** [comment] 2015-11-12 05:17
Hi, I think I might be experiencing a similar problem.

```swift
class Task {
    dynamic var name: String? = nil
    let steps = List<Step>()
}

class Step {
    dynamic var name: String? = nil
    let duration = RealmOptional<NSTimeInterval>()
}
```

When I copy a `Task` from a read-only compressed realm into the default realm, everything is copied over except the `duration` property which shows up as 0 in the Realm browser. I verified using the Realm browser that the `duration` property is not 0 in the read-only Realm.

I'm happy to open another issue if that would be more appropriate, but I thought another example might be helpful. 

Let me see if I can reproduce in a separate project.

I'm on XCode 7.1 (7B91b) / OS X 10.11.1 / Realm 0.96.2 / Carthage 0.9.2

**Comment by smpanaro** [comment] 2015-11-12 07:09
Here's a test project (it's a .zip file, so you'll have to change the extension when you download it):
![test-proj](https://cloud.githubusercontent.com/assets/2950214/11112420/ed10d2de-88e0-11e5-80ed-0d3080d1d49d.png)

My built frameworks were too big to upload, but I can find a way to upload them if needed.

Here's the output I get in my console when running the project:
```
Objects in main realm before deletion: Results<Task> (

)
Deleting all objects from main Realm.
Creating read-only Realm.
Read-only Realm saved to /Users/......./readonly.realm
Objects in the read-only realm: Results<Task> (
	[0] Task {
		name = taskName;
		steps = RLMArray <0x7fcd3b585300> (
			[0] Step {
				name = stepName;
				duration = 3.5;
			}
		);
	}
)
Inserted read-only objects into main Realm.
Objects in main realm after: Results<Task> (
	[0] Task {
		name = taskName;
		steps = RLMArray <0x7fcd3b726d90> (
			[0] Step {
				name = stepName;
				duration = (null);          <<<<< I think this should be 3.5
			}
		);
	}
)
Objects in read-only realm after: Results<Task> (
	[0] Task {
		name = taskName;
		steps = RLMArray <0x7fcd3b738740> (
			[0] Step {
				name = stepName;
				duration = 3.5;
			}
		);
	}
)
```

This is an almost perfect replica of my issue in my other project. The only difference is that my other project persists the default Realm across launches but this one does not seem to do that. 

Let me know what I'm doing wrong or if there's anything else I can provide!

**Comment by jpsim** [comment] 2015-11-12 17:40
@smpanaro thanks for sending us a repro project, it really helps us understand!

I think your case is very different than @allbto's issue, since for you, it's writing a copy of the Realm file that causes a `RealmOptional` property to lose its value (the `steps` relationship of our `Task` objects are preserved in the copy). I'm investigating this further to see if there are situations in which `Realm.writeCopyToPath(...)` ignores data from optional properties.

**Comment by smpanaro** [comment] 2015-11-19 02:01
Hi @jpsim I was wondering if you had any update on my problem. Would it be useful to open a separate issue?

**Comment by smpanaro** [comment] 2015-11-24 01:35
@jpsim @bigfish24 - Have you had a chance to look at my example? Optional support is awesome, but this bug pretty much negates it. (Unless I'm doing something bad, which would be great to know.)

**Comment by allbto** [comment] 2015-11-24 16:26
@bigfish24 @TimOliver Here is a [test project](https://drive.google.com/file/d/0BxLVPjjzgHzUUmFXWGRaNUJrMWM/view?usp=sharing)

**Comment by bigfish24** [comment] 2015-11-25 00:15
@allbto thanks for the test project! I identified the issue. This PR has the fix: https://github.com/realm/realm-cocoa/pull/2901

**Comment by allbto** [comment] 2015-11-25 12:48
@bigfish24 Awesome, I'm looking forward it to be fixed :)

**Comment by bigfish24** [comment] 2015-11-25 21:08
@smpanaro can you create a new issue for your case? It is different than @allbto and I would like to close this thread and continue work on your issue elsewhere. Thanks!

**Comment by smpanaro** [comment] 2015-11-25 22:28
@bigfish24 I've opened #2905 for my case.

**Comment by bigfish24** [comment] 2015-11-25 22:53
@smpanaro thanks will move over to that and will close this now. cc @jpsim

**Closed by bigfish24** 2015-11-25 22:53 UTC
Labels: bug, Help
