### ISSUE TITLE
'Version of Realm file on disk is higher than current schema version'

### ISSUE THREAD

**Issue by webmagnets** [realm/realm-cocoa#1474] opened 2015-02-09 14:44 UTC
Would someone please have a look at this stackoverflow question?:

http://stackoverflow.com/questions/28382320/why-am-i-getting-this-error-after-upgrade-version-of-realm-file-on-disk-is-hi

**Comment by tspecht** [comment] 2015-02-09 15:23
I'm currently having the very same problem

**Comment by alazier** [comment] 2015-02-09 16:26
You need to be sure to call `setSchemaVersion` for all Realms paths used in your app. That change was made in 0.90.0. If that is no the issue then we may need some more help reproducing the issue.

**Comment by alazier** [comment] 2015-02-09 16:38
Would either of you be able to send a copy of a Realm file which produced this issue to help@realm.io? This could help us to diagnose and fix the issue.

**Comment by webmagnets** [comment] 2015-02-09 16:42
I just sent mine.

**Comment by alazier** [comment] 2015-02-10 01:07
So the problem here was that `allObjects` was being called during the initialization of an RLMResults member variable of a swift view controller - this is a problem because viewControllers are initialized from a nib before `applicationDidFinishLaunching` is called.

The fix for this is to initialize the swift RLMResults property in the viewController's `viewDidLoad` method rather than initializing it where it is declared. To do this it needs to be declared as optional or implicitly unwrapped optional

**Comment by tspecht** [comment] 2015-02-10 08:18
I'm not doing any of this nor having even touched Swift at all so how is this fixing the migration problem?

**Comment by alazier** [comment] 2015-02-10 15:56
@tspecht is it possible that you have a different issue from @webmagnets 

Is it possible that you may have other initialization code that could run before calling setSchemaVersion? We just pushed a change to master which gives more debug information when seeing this issue #1478 . Would you mind trying out master to see if this sheds any light on the issue?

**Comment by tspecht** [comment] 2015-02-10 21:08
I'll try with the changes tomorrows at some point and will get back to you, thanks for reopening it @alazier !

**Comment by alazier** [comment] 2015-02-17 17:51
Any word @tspecht ?

**Comment by tspecht** [comment] 2015-02-18 13:23
Sorry for getting back to you just now! I pulled the lastest master and from the error message I'm receiving with the exception it seems that the old schema version is not recognised correctly?

Realm at path '/var/mobile/Containers/Data/Application/A0580E8C-8DDE-4BDC-BB3B-89CBFE7FF958/Documents/search' has version number 19 which is greater than the current schema version 0. You must call setSchemaVersion: or setDefaultRealmSchemaVersion: before accessing an upgraded Realm.

**Comment by alazier** [comment] 2015-02-18 18:25
You need to be sure to call `setSchemaVersion:forRealmAtPath:withMigrationBlock` for this path with a version >= 19 before any Realms are accessed. If you are already making this call then it is likely a Realm instance is being accessed before the call to `setSchemaVersion:forRealmAtPath:withMigrationBlock` is made. If you add a breakpoint for all exceptions, then you can inspect the callstack to figure out what calls are triggering this error.

**Comment by jpsim** [comment] 2015-03-03 17:53
Have you looked further into this @tspecht? @alazier's diagnosis seems right to me.

**Closed** 2015-03-19 23:56 UTC
Labels: pending

**Comment by EvilGeniusTechnologies** [comment] 2015-03-31 17:16
Hi there alazier -- I'm sad to say I can't actually understand the steps to solve this problem from what is written above.  My project is entirely non-Swift and Realm is being added via CocoaPods.  Can you please re-explain the proper steps to solve this problem?  

I tried putting a setSchemaVersion:forRealmAtPath:withMigrationBlock call as the first line in my application:didFinishLaunchingWithOptions: and this still didn't solve the problem.  

Thanks for your help!

**Comment by jpsim** [comment] 2015-03-31 17:57
@EvilGeniusTechnologies what are the contents of your `setSchemaVersion:forRealmAtPath:withMigrationBlock:` call? What's the result of running [`+[RLMRealm schemaVersionAtPath:error:]`](https://realm.io/docs/cocoa/0.91.1/api/Classes/RLMRealm.html#//api/name/schemaVersionAtPath:error:)? Make sure to run that last call before opening your realm.

**Comment by yoshyosh** [comment] 2015-03-31 18:59
http://realm.io/docs/cocoa/0.91.1/#performing-a-migration has some samples on this as well. The main idea is that `setSchemaVersion:......` needs to have a number greater than the last schema version that was set

**Comment by EvilGeniusTechnologies** [comment] 2015-03-31 20:34
Happy to report that re-running "pod install" and cleaning everything apparently did the trick.  I realized I wasn't running the newest version of Realm (to my chagrin!) but all is well now.  Thanks to all.
