### ISSUE TITLE
ProgressNotification callback not triggered without receiving data from sync in Realm 10

### ISSUE THREAD

**Issue by erdem-inan** [realm/realm-cocoa#7006] opened 2020-12-17 12:13 UTC
## Goals 
Listening ProgressNotification to see if there is pending data to download.

## Expected Results
The ProgressNotification callback for download to be triggered without an initial download.

## Actual Results
The ProgressNotification callback for download is not triggered until new data are received. 
From this point, It will trigger every time we need it, even if no data are received

## Steps for others to Reproduce
We are using MongoDB Realm in our app.

The first time the user is connected to the app, the ProgressNotifcation callback is triggered correctly, and it will work and trigger whenever a new download is coming. 
Even if no download is pending, the ProgressNotification callback will be triggered (the Progress object pass in the callback will contain values from the last download) at least once(when creating it). I supposed this is due to the fact that we are downloading the first data set of the user.

But after killing the app and launching it again, the ProgressNotification callback is not triggered anymore until new data are received by the app. And from this point, the callback will be called every time we need it.
 
It seems that now, the framework needs a first download since the app is launch to make ProgressNotification callback to be triggered every time we need it.
 
This was working in the previous version of Realm (5.X.X). We just finished the migration to Realm 10 and discover this issue.
Is something has changed? Is this working as intended according to you? 

Note: this is no more working in both mode : .forCurrentlyOutstandingWork and .reportIndefinitely

## Code Sample
```
self.token = syncSession.addProgressNotification(for: .download, mode: .forCurrentlyOutstandingWork) { progress in
                           .......Some code........   <- this part of the code is not triggered anymore
}

```
## Version of Realm and Tooling
Realm framework version:  10.5.0

Realm Object Server version: MongoDB Realm

Xcode version: 12.3

iOS/OSX version: 14.3

Dependency manager + version: Cocoapods 1.10.0

**Comment by jsflax** [comment] 2020-12-17 14:23
@fealebenpae do you have any thoughts on this?

**Comment by erdem-inan** [comment] 2021-01-04 07:12
Hello ! I am still stuck on this issue. Is there any news from your side? 

Thanks

**Comment by DominicFrei** [comment] 2021-01-04 16:55
Hi @erdem-inan,

Sorry for the delay. I will check back with @fealebenpae.

Kind regards,
Dominic

**Comment by DominicFrei** [comment] 2021-01-07 11:38
@erdem-inan Trying to clarify this further for us so that we can reproduce it:
I suppose the problem is that progress notifications are delivered only if this is the first time the realm file is opened and synchronised from the server?

@simonask  Do you think we have enough information to reproduce this issue?

**Comment by erdem-inan** [comment] 2021-01-07 12:10
Hi @DominicFrei !

Yes, it is that.
So, at first lunch, it is working great and as expected (since we have data to download).
But after, let say that we kill the app and restart it. The progress notifications will no more deliver notifications until new data is pushed to the Realm (through MongoDB with the right Partition key).

**Comment by erdem-inan** [comment] 2021-01-25 07:32
Hello @DominicFrei ! Any news on this issue?

**Comment by DominicFrei** [comment] 2021-01-26 15:14
@erdem-inan The issue has been passed on to @leemaguire. He is looking into similar issues already.

**Comment by leemaguire** [comment] 2021-03-02 22:09
This is confirmed as fixed with the latest version of Cocoa.

**Closed** 2021-03-02 22:10 UTC
Labels: O-Community, Pipeline-Discussion
