### ISSUE TITLE
Sudden spike in crashes from Realm, v 0.91

### ISSUE THREAD

**Issue by mightyleader** [realm/realm-cocoa#1837] opened 2015-05-05 08:36 UTC
Hey,
We've experienced a sudden spike in crashes in our app over the past few days. The stack seems to indicate an issue internal to Realm during an object delete. 
The calling code in the app hasn't changed for about 2 months, the only change we can see that's relevant is the update to Realm from 0.9 to 0.91.

I've attached the log below:

    Thread 9 Crashed:
    0   libsystem_kernel.dylib               0x3862d1f0 __pthread_kill + 8
    1   libsystem_pthread.dylib              0x38697797 pthread_kill + 56
     2   libsystem_c.dylib                    0x385ddfdd abort + 74
     3   libc++abi.dylib                      0x3790ccd7 abort_message + 72
     4   libc++abi.dylib                      0x379256af default_terminate_handler() + 196
     5   libobjc.A.dylib                      0x3806af89 _objc_terminate() + 226
     6   libc++abi.dylib                      0x379231c7 std::__terminate(void (*)()) + 76
     7   libc++abi.dylib                      0x37922a1d __cxa_throw + 114
     8   libc++.1.dylib                       0x378fb313 operator new(unsigned long) + 76
     9   noths                                0x0020b36f tightdb::AdaptiveStringColumn::do_move_last_over(unsigned      long, unsigned long) + 204
     10  noths                                0x00256c7d tightdb::Table::do_move_last_over(unsigned long, bool) + 66
     11  noths                                0x00256c01 tightdb::Table::remove_backlink_broken_rows(std::__1::vector<tightdb::ColumnBase::CascadeState::row, std::__1::allocator<tightdb::ColumnBase::CascadeState::row> > const&) + 298
     12  noths                                0x0025abc7 tightdb::Table::move_last_over(unsigned long) + 352
     13  noths                                0x00225053 tightdb::LinkView::remove_all_target_rows() + 172
     14  noths                                0x00184e39 -[RLMRealm deleteObjects:] (RLMRealm.mm:693)
     15  noths                                0x000ff4d7 -[PersonalizableProductRO cascadeDeleteFromRealm:] (PersonalizableProductRO.m:33)
     16  noths                                0x000ec751 -[BasketProductRO cascadeDeleteFromRealm:] (BasketProductRO.m:50)
     17  noths                                0x00101bed +[NOTBasketPersistentStore removePersistedProduct:] (NOTBasketPersistentStore.m:329)
     18  libdispatch.dylib                    0x38552833 _dispatch_call_block_and_release + 8
     19  libdispatch.dylib                    0x38558f11 _dispatch_queue_drain$VARIANT$mp + 486
     20  libdispatch.dylib                    0x38558c97 _dispatch_queue_invoke$VARIANT$mp + 40
     21  libdispatch.dylib                    0x38559a45 _dispatch_root_queue_drain + 74
     22  libdispatch.dylib                    0x38559d29 _dispatch_worker_thread2 + 54
     23  libsystem_pthread.dylib              0x38694bd3 _pthread_wqthread + 296
     24  libsystem_pthread.dylib              0x38694a98 start_wqthread + 6```

**Comment by tgoyne** [comment] 2015-05-05 17:10
Are you using 0.91.2 or 0.91.3? There's an issue with the string index migration in those versions which could cause similar problems to that.

**Comment by mightyleader** [comment] 2015-05-05 17:32
Hey,
Neither it's just 0.91

Rob

**Comment by segiddins** [comment] 2015-05-05 21:32
@mightyleader is this a bug you can reliably reproduce? If so, a project that demonstrates it would be incredible helpful (you can send one privately to help@realm.io if it isn't something you can share publicly). Thanks!

**Comment by mightyleader** [comment] 2015-05-05 21:46
Hey Samuel,
I'd love to say we could. Our only visibility is the crash logs we are getting back from Hockey App.
What's strange is that we got 35 crashes with the same log output over the weekend, when the previous weekend we got zero. 
We *think* it's possibly when the data is migrated across a few versions of Realm in one pass, and an object is deleted then it occurs but we've no hard data for that.

Rob

**Comment by mightyleader** [comment] 2015-05-06 12:14
UPDATE - just seen that it happened after we upgraded the app from 0.90.4 to 0.91.0.

**Comment by jpsim** [comment] 2015-05-06 17:04
@mightyleader do you happen to use Crashlytics in this app? If so, we could send you a version of Realm which logs its exception and assertion messages to Crashlytics' logs, which would collect more information about how this is happening.

**Comment by mightyleader** [comment] 2015-05-07 08:14
Hi JP,
We use the crash reporting SDK in HockeyApp, but not crashlytics does that help?

**Comment by jpsim** [comment] 2015-05-13 04:13
Hi @mightyleader, HockeyApp should be logging the exception messages Realm throws without any special help. Have you made any headway in figuring out what's causing the increase in crashes in your app?

**Comment by mightyleader** [comment] 2015-05-13 08:30
Hi JP, 
It's definitely the move from 0.90.4 to 0.91.0.
We've been reluctant to upgrade further yet.
Would you recommend 0.91.5 as something that might fix these issues? I know there were some noted issues in 0.91.2 & 3.

**Comment by jpsim** [comment] 2015-05-13 17:32
I've opened an issue with our core team to look into this problem, but it will be difficult without a reproduction case. If you manage to craft a reproducible scenario demonstrating this issue, it will most definitely speed up a fix.

**Comment by segiddins** [comment] 2015-06-02 20:18
@mightyleader unfortunately, our core team won't be able to investigate this crash coming from such an old version -- could you try updating to 0.93.1 and seeing if that fixes things? Thanks!

**Comment by ivanandriolloNOTHS** [comment] 2015-06-19 14:26
@segiddins @jpsim we updated to v0.93.1 and are still getting the same crashes. 
It's the same line: realm::AdaptiveStringColumn::do_move_last_over(unsigned long, unsigned long) + 176

![screen shot 2015-06-19 at 15 19 10](https://cloud.githubusercontent.com/assets/7499580/8255353/52fd1362-1697-11e5-9d83-a466cd3a9377.png)

**Comment by mightyleader** [comment] 2015-06-23 10:02
@jpsim @segiddins @mrackwitz Hey, so we did the upgrade to 0.93.1 as Ivan mentioned and are still seeing a similar level of crashes. The last stable version for us is still 0.90.4. Is it not possible to know what changes happened in the core at this point that might have triggered this issue?

**Comment by jpsim** [comment] 2015-06-24 07:44
Sorry to hear you're both still having issues, even with 0.93.1. Are you using encrypted Realms? The only change in Realm's core between objc versions 0.90.4 and the subsequent release was a fix for encryption on 64-bit devices.

And have neither of you been able to trigger the issue reliably so we can replicate the behavior on our end to investigate further? A repro case would go a long way towards being able to identify what's happening.

As for access to the release notes for core, I'll look into posting those here, but scanning them doesn't reveal anything particularly relevant.

**Comment by jpsim** [comment] 2015-06-24 07:47
Actually, I just remembered that we *do* already make Realm Core's release notes available publicly, so here's the change log since Realm Objective-C v0.90.4 (core 0.88.0):

0.89.6 Release notes
====================

Bugfixes:

-   Fixed durability issue in case of power / system failures on Apple
    platforms. We now use a stronger synchronization
    (fcntl(fd, F_FULLFSYNC)) to stable storage when the file is
    extended.

* * * * *

0.89.5 Release notes
====================

Bugfixes:

-   Fixed errors when a changes to a table with an indexed int column
    are rolled back or advanced over.

* * * * *

0.89.4 Release notes
====================

Enhancements:

-   Detaching (and thus destroying) row acessors and TableViews can now
    be done safely from any thread.
-   Improved performance of Query::find_all() with assertions enabled.

* * * * *

0.89.3 Release notes
====================

Bugfixes:

-   Fixed incorrect results for Or() when querying via a LinkView with a
    different order than the target table.
-   Fixed incorrect results when getting the count for a query where the
    only condition is checking for non-equality to an int.

Enhancements:

-   Automatically log assertion messages to Crashlytics if it's loaded
    into the current process.

* * * * *

0.89.2 Release notes
====================

Bugfixes:

-   Fixed encryption on Android ARM64 devices.
-   Changes the mmap doubling treshold on mobile devices from 128MB to
    16MB.

* * * * *

0.89.1 Release notes
====================

Bugfixes:

-   Fixed bug in "index rebuilding" (would delete the wrong column,
    causing crash). See https://github.com/realm/realm-core/pull/798 ;
    "Remove the correct column when removing search indexes #798"

* * * * *

0.89.0 Release notes
====================

Bugfixes:

-   Added a check for NUL bytes in indexed strings to avoid corrupting
    data structures.
-   Fixed bug in SharedGroup::compact(). The bug left the freelist
    outdated in some situations, which could cause crash later, if work
    continued on the same shared group. The bug did not affect the data
    written to the compacted database, but later commits working on the
    outdated freelist might have. The fix forces proper
    (re)initialization of the free list.
-   Fixed incorrect results in querying on an indexed string column via
    a LinkView.
-   Fixed corruption of indexes when using move_last_over() on rows with
    duplicated values for indexed properties.

API breaking changes:

-   Changed the tightdb namespace to realm.
-   We switched to C++11, and removed functionality that was duplicated
    from the C++11 standard library, including null_ptr and
    util::UniquePtr.

Enhancements:

-   Improved performance of advance_read() over commits with string or
    binary data insertions.
-   Improved performance sorting TableView and LinkView.
-   Added Table::remove_search_index().

* * * * *

0.88.6 Release notes
====================

Bugfixes:

-   Fixed bug in Integer index that could make it crash or return bad
    results (String index not affected)

* * * * *

0.88.5 Release notes
====================

Bugfixes:

-   Fixed crash when std::exit() is called with active encrypted
    mappings.
-   Fixed writing over 4KB of data to an encrypted file with
    Group::write().
-   Fixed crash after making commits which produced over 4KB of writelog
    data with encryption enabled.

* * * * *

Internals:

-   Switched to using mach exceptions rather than signal() for encrypted
    mappings on Apple platforms.

* * * * *

0.88.4 Release notes
====================

Bugfixes:

-   Fixed out-of-bounds reads when using aggregate functions on sorted
    TableViews.
-   Fixed issues with ArrayString that could be the cause of all the
    asserts the past few days

* * * * *

Internals:

-   Many REALM_ASSERT invocations replaced by new REALM_ASSERT_3 macro
    that prints variable/argument contents on failure. It's not
    implemented optimally yet.

* * * * *

0.88.3 Release notes
====================

Enhancements:

-   Added emulation of inter-process condition variables for use on
    platforms which do not properly implement them.

* * * * *

0.88.2 Release notes
====================

Bugfixes:

-   Fixed duplicated results when querying on a link column with matches
    at row 1000+.

* * * * *

Internals:

-   Added support for Android ARM64

* * * * *

0.88.1 Release notes
====================

Bugfixes:

-   Fix encryption on platforms with non-4KB pages.

* * * * *

0.88.0 Release notes
====================

Enhancements:

-   SharedGroup::compact() now appends ".tmp_compaction_space" to the
    database name in order to get the name of its temporary workspace
    file instead of ".tmp". It also automatically removes the file in
    case it already exists before compaction.
-   Add support for comparing string columns to other string columns in
    queries.
-   WriteTransaction::has_table() and WriteTransaction::rollback() were
    added. Previously, only implicit rollback was possible with
    WriteTransaction.

* * * * *

Internals:

-   All assert failures now print the release version number.

* * * * *

**Comment by mightyleader** [comment] 2015-06-24 08:05
Morning JP,
Thanks for the info! We'll review and get back to you asap.

Rob

**Comment by ivanandriolloNOTHS** [comment] 2015-06-24 08:50
@jpsim we are not using encrypted Realms.

**Comment by jpsim** [comment] 2015-06-24 18:12
> we are not using encrypted Realms.

Ok. Please keep us posted if you're able to trigger this issue reliably, as it's something we'd really like to fix.

**Comment by mightyleader** [comment] 2015-06-25 10:33
Hey JP.
Having looked into it some more we have issued a potential fix at the app level and will monitor to see if it's effective.
Basically we take on the task of cascade deletion within our local Realm objects and once this is complete we delete the root Realm object. We do this in a single commit transaction. It looks like the process of deleting all the objects isn;t completing serially despite being on a serial queue so we've move the final deletion stage into it's own discrete commit transaction.
If it proves this is a good fix we can build an example app to demonstrate the issue and send it on to you.

**Comment by mightyleader** [comment] 2015-06-25 13:56
Hey JP, We have a possible repro case, at least the data concerned.
Can you send an email address we can send details to?

**Comment by segiddins** [comment] 2015-06-25 14:00
@mightyleader it would be great if you could send that to us at help@realm.io, thanks!

**Comment by segiddins** [comment] 2015-08-21 00:50
I believe we concluded that this only happened with databases created with v0.90.5 of the cocoa binding, and that core has since been fixed?

**Comment by jpsim** [comment] 2015-09-01 01:06
Closing since we believe this to be fixed in recent versions of Realm and we haven't heard back from @mightyleader in a while.

**Closed by jpsim** 2015-09-01 01:06 UTC
Labels: blocked, bug, P1, pending
