### ISSUE TITLE
Latest stable release of realm (0.90.5) crashes on release version of app

### ISSUE THREAD

**Issue by eni9889** [realm/realm-cocoa#1503] opened 2015-02-14 06:45 UTC
Our app was rejected twice by the app store because it was crashing on launch with the following log:

http://pastie.org/private/s1ftstnpy74mjvaowx9jtw

This crash only happens in the latest version  (0.90.5) and it goes away when we revert to  (0.90.0). Also it only happens on the release version of our app.

**Comment by segiddins** [comment] 2015-02-16 06:11
@eni9889, thanks for sharing the stack trace with us. We'd truly appreciate if you could share a reproducible case of this issue (if you manage to find one) so we have some sample code to debug with. It would help us a lot with regards to discovering this assertion failure. (You can send a project to us privately at help@realm.io if you'd prefer not to share it here on GitHub.)

Thanks for your help!

**Comment by segiddins** [comment] 2015-03-24 22:31
Just following up on this request for an Xcode project that could help use reproduce this issue, @eni9889.

**Comment by nolanamy** [comment] 2015-03-30 08:58
@segiddins We're also getting crashes in release builds as well; we've been able to reproduce it here: <https://github.com/nolanamy/realm-test>. It doesn't seem to have any issues in the simulator, but crashes every time on at least iPhone 6 Plus.

**Comment by jpsim** [comment] 2015-03-30 18:24
We've managed to reproduce @nolanamy's crash, which is caused by a bug in how the `CFString` was autoreleased. The solution there is to use `NSString` instead.

Note that @eni9889's issue is separate from @nolanamy's, which we haven't been able to reproduce yet.

@eni9889 an Xcode project that could help use reproduce this issue would be greatly appreciated.

**Comment by jpsim** [comment] 2015-04-29 20:22
@eni9889 we're closing this as we were never able to reproduce the issue. If you see this again, please let us know and be sure to include as much information as possible for us to reproduce it and investigate.

**Closed by jpsim** 2015-04-29 20:22 UTC
Labels: pending
