### ISSUE TITLE
 NSForwarding: warning: object 0x10868a2f0 of class 'RealmTest.Dog' does not implement methodSignatureForSelector: -- did you forget to declare the superclass of 'RealmTest.Dog'?

### ISSUE THREAD

**Issue by ConanMTHu** [realm/realm-cocoa#4152] opened 2016-09-28 04:41 UTC
class Dog:Object {
    dynamic var name = ""  
}

```
    let dog = Dog()

    print(dog.name)
```

i  run it error .........   "Object" is error??

**Comment by bdash** [comment] 2016-09-30 15:30
Please provide the crash log and/or backtrace. If possible, please also share a test project that demonstrates this crash so we can reproduce this problem. Please also let us know which versions of Realm, Xcode and Swift you're using.

**Comment by jpsim** [comment] 2016-10-17 23:56
@ConanMTHu just following up on @bdash's request for more information, such as a crash log and/or backtrace, along with a test project that reproduces the issue.

**Comment by deepumukundan** [comment] 2016-11-03 19:34
I got similar error on a project.
**Realm 2.0.3 installed via Carthage - Xcode 8.1 - Swift 3.0.1**
The missing piece for me was that I had forgot to add the Carthage copy frameworks build phase specified in https://realm.io/docs/swift/latest/#getting-started.

@ConanMTHu Did you by any chance make the same mistake?

**Comment by bdash** [comment] 2016-11-08 16:33
@deepumukundan, thanks for the input!

@ConanMTHu, did you make any progress on this?

**Comment by jpsim** [comment] 2016-12-07 01:59
Closing since we were never able to get sufficient information on this.

**Closed by jpsim** 2016-12-07 01:59 UTC
Labels: Reproduction Required, S:Waiting For User, T:Bug-Crash
