### ISSUE TITLE
Error installing RealmSwift

### ISSUE THREAD

**Issue by idevAgg** [realm/realm-cocoa#6806] opened 2020-09-25 07:45 UTC
Realm framework version: ???
Realm Object Server version: ???
Xcode version: 12.0
iOS/OSX version: OS X 11.0 Beta BigSur
Dependency manager + version: 1.9.3

When running `pod install` getting the issue:

[!] Error installing RealmSwift
[!] Failed to download 'RealmSwift': [!] /usr/bin/git -C /var/folders/12/gkl91qgs1wz7731nbbvf3f9w0000gn/T/d20200925-2721-mas67c submodule update --init --recursive

Submodule path 'Realm/ObjectStore': checked out 'e29b5515df8b8adfe2454424b78878bb63879307'
Submodule 'Realm/ObjectStore' (https://github.com/realm/realm-object-store.git) registered for path 'Realm/ObjectStore'
Cloning into '/private/var/folders/12/gkl91qgs1wz7731nbbvf3f9w0000gn/T/d20200925-2721-mas67c/Realm/ObjectStore'...
Submodule 'external/catch' (https://github.com/catchorg/Catch2) registered for path 'Realm/ObjectStore/external/catch'
Cloning into '/private/var/folders/12/gkl91qgs1wz7731nbbvf3f9w0000gn/T/d20200925-2721-mas67c/Realm/ObjectStore/external/catch'...
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: the remote end hung up unexpectedly
fatal: clone of 'https://github.com/catchorg/Catch2' into submodule path '/private/var/folders/12/gkl91qgs1wz7731nbbvf3f9w0000gn/T/d20200925-2721-mas67c/Realm/ObjectStore/external/catch' failed
Failed to clone 'external/catch'. Retry scheduled
Cloning into '/private/var/folders/12/gkl91qgs1wz7731nbbvf3f9w0000gn/T/d20200925-2721-mas67c/Realm/ObjectStore/external/catch'...
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: the remote end hung up unexpectedly
fatal: clone of 'https://github.com/catchorg/Catch2' into submodule path '/private/var/folders/12/gkl91qgs1wz7731nbbvf3f9w0000gn/T/d20200925-2721-mas67c/Realm/ObjectStore/external/catch' failed
Failed to clone 'external/catch' a second time, aborting
Failed to recurse into submodule path 'Realm/ObjectStore'

**Comment by eofs** [comment] 2020-09-25 07:54
Same error is raised when installing using Xcode 12 and SwiftPM

**Comment by aamarkov** [comment] 2020-09-25 08:17
Same error when installing using Xcode 11.7 and SwiftPM.

**Comment by iHesh** [comment] 2020-09-25 08:39
Facing the same issue with Xcode 12 GM and SwiftPM

**Comment by tamasdancsi** [comment] 2020-09-25 08:42
The catch folder is empty in Realm's resolved dependencies. If you download catch (https://github.com/catchorg/Catch2) and copy the contents of the single_include/catch2 folder it will work, but this is REALLY BAD

**Comment by JulianKahnert** [comment] 2020-09-25 09:02
Same error with Xcode 12.0.1 (12A7300). Deleting the derived data folder and changing the global git `http.postBuffer` size did **not** fixed the problem.

**Comment by mir-dawn** [comment] 2020-09-25 09:03
This is a strange one. We had the same issue, and could reproduce the error both in Carthage and SwiftPM! 

It looks to be an issue during the "git submodule update -v --init --recursive", were we get a "RPC failed; curl 18 transfer closed with outstanding read data remaining" error. This issue have been seen before with large repos. Not sure who to "blame" here but I do actually not think this is a bug in Realm!

The most common suggestion to solve this to do a shallow clone, which is not possible in these cases. 

But another suggestion is to use SSH instead of HTTPS! So what we did to solve it **(as a temporary fix)** was to change all git commands from HTTPS to SSH by adding the following to the global git config!

git config --global url."git@github.com:".insteadOf https://github.com/

This will force git to use SSH instead of HTTPS for GitHub, and that resolved the issue for us. 

Remember to remove this config again later, to avoid possible problems later. Do not see this as a permanent fix 😉

**Comment by MeGaPk** [comment] 2020-09-25 09:24
same error on pod 'Realm'

**Comment by eofs** [comment] 2020-09-25 09:35
> git config --global url."[git@github.com](mailto:git@github.com):".insteadOf https://github.com/

Thanks @mir-dawn! I was able to install Realm using SwiftPM althought I had to tweak the command a bit to avoid breaking installation of other dependencies:

`git config --global url."git@github.com:catchorg/Catch2".insteadOf https://github.com/catchorg/Catch2`

**Comment by MeGaPk** [comment] 2020-09-25 09:53
> > git config --global url."[git@github.com](mailto:git@github.com):".insteadOf https://github.com/
> 
> Thanks @mir-dawn! I was able to install Realm using SwiftPM althought I had to tweak the command a bit to avoid breaking installation of other dependencies:
> 
> `git config --global url."git@github.com:catchorg/Catch2".insteadOf https://github.com/catchorg/Catch2`

Hello! I tried this, but get errors:
```

[!] Error installing Realm
[!] /usr/bin/git -C /var/folders/6f/yw_vww5s7zl_s_kscnx25f6h0000gn/T/d20200925-55137-1pndacv submodule update --init --recursive

Submodule path 'Realm/ObjectStore': checked out '7ad03b857ddc0ef29779caeb93ad5a6d9cef44af'
Submodule 'Realm/ObjectStore' (https://github.com/realm/realm-object-store.git) registered for path 'Realm/ObjectStore'
Cloning into '/private/var/folders/6f/yw_vww5s7zl_s_kscnx25f6h0000gn/T/d20200925-55137-1pndacv/Realm/ObjectStore'...
Submodule 'external/catch' (https://github.com/catchorg/Catch2) registered for path 'Realm/ObjectStore/external/catch'
Cloning into '/private/var/folders/6f/yw_vww5s7zl_s_kscnx25f6h0000gn/T/d20200925-55137-1pndacv/Realm/ObjectStore/external/catch'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'https://github.com/catchorg/Catch2' into submodule path '/private/var/folders/6f/yw_vww5s7zl_s_kscnx25f6h0000gn/T/d20200925-55137-1pndacv/Realm/ObjectStore/external/catch' failed
Failed to clone 'external/catch'. Retry scheduled
Cloning into '/private/var/folders/6f/yw_vww5s7zl_s_kscnx25f6h0000gn/T/d20200925-55137-1pndacv/Realm/ObjectStore/external/catch'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'https://github.com/catchorg/Catch2' into submodule path '/private/var/folders/6f/yw_vww5s7zl_s_kscnx25f6h0000gn/T/d20200925-55137-1pndacv/Realm/ObjectStore/external/catch' failed
Failed to clone 'external/catch' a second time, aborting
Failed to recurse into submodule path 'Realm/ObjectStore'

```

**Comment by mir-dawn** [comment] 2020-09-25 09:54
@eofs Cool, this is maybe a better approach! I tested the other with Carthage and SwiftPM in the terminal, and there they worked. But I can see that they do not work in Xcode 12, But you approach do! :)

**Comment by mir-dawn** [comment] 2020-09-25 09:56
@MeGaPk looks like you are missing a SSH key.

https://docs.github.com/en/github/authenticating-to-github/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent

**Comment by eofs** [comment] 2020-09-25 09:56
> Hello! I tried this, but get errors:
>
> git@github.com: Permission denied (publickey).
> fatal: Could not read from remote repository.
> 

You need to generate necessary keys and setup your GitHub account for SSH access. See following documentation how to set it up: https://docs.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh

**Comment by MeGaPk** [comment] 2020-09-25 09:59
> @MeGaPk looks like you are missing a SSH key.
> 
> https://docs.github.com/en/github/authenticating-to-github/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent



> > Hello! I tried this, but get errors:
> > [git@github.com](mailto:git@github.com): Permission denied (publickey).
> > fatal: Could not read from remote repository.
> 
> You need to generate necessary keys and setup your GitHub account for SSH access. See following documentation how to set it up: https://docs.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh

thanks it works now

**Comment by Almaz5200** [comment] 2020-09-25 10:13
> Thanks @mir-dawn! I was able to install Realm using SwiftPM althought I had to tweak the command a bit to avoid breaking installation of other dependencies:
> git config --global url."git@github.com:catchorg/Catch2".insteadOf https://github.com/catchorg/Catch2

I'm getting this error now

`[!] /bin/bash -c 
set -e
sh build.sh cocoapods-setup

core is not a symlink. Deleting...
Downloading dependency: sync 4.9.0 from https://static.realm.io/downloads/sync/realm-sync-cocoa-4.9.0.tar.xz
mv: rename core to sync-4.9.0/core: Directory not empty`

**Comment by MeGaPk** [comment] 2020-09-25 10:14
> > Thanks @mir-dawn! I was able to install Realm using SwiftPM althought I had to tweak the command a bit to avoid breaking installation of other dependencies:
> > git config --global url."[git@github.com](mailto:git@github.com):catchorg/Catch2".insteadOf https://github.com/catchorg/Catch2
> 
> I'm getting this error now
> 
> ```
> set -e
> sh build.sh cocoapods-setup
> 
> core is not a symlink. Deleting...
> Downloading dependency: sync 4.9.0 from https://static.realm.io/downloads/sync/realm-sync-cocoa-4.9.0.tar.xz
> mv: rename core to sync-4.9.0/core: Directory not empty
> ```

try rm -fr ~/.cocoapods maybe will help

**Comment by idevAgg** [comment] 2020-09-25 10:19
After generating and adding ssh, works even without `git config --global url."git@github.com:catchorg/Catch2".insteadOf https://github.com/catchorg/Catch2`.

**Comment by Kalzem** [comment] 2020-09-25 10:34
Facing the same problem using xcode 12 + SPM with Realm v4.x.x (latest v4).

Not being able to use ssh (continuous integration over a server with not enough ssh rights), this still remains an issue.

I hope the Realm team can fix this quickly 🤞

**Comment by IhorChernysh** [comment] 2020-09-25 10:41
From the documentation:

If you’re using Xcode 12, add the following to your Podfile:
Copy to clipboardpost_install do |installer|
     installer.pods_project.targets.each do |target|
           target.build_configurations.each do |config|
                 config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
           end
     end
 end
This is a temporary workaround for until CocoaPods 1.10 is released.

**Comment by idevAgg** [comment] 2020-09-25 10:44
> From the documentation:
> 
> If you’re using Xcode 12, add the following to your Podfile:
> Copy to clipboardpost_install do |installer|
> installer.pods_project.targets.each do |target|
> target.build_configurations.each do |config|
> config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
> end
> end
> end
> This is a temporary workaround for until CocoaPods 1.10 is released.


It doesn't solve the problem

**Comment by Almaz5200** [comment] 2020-09-25 10:46
@MeGaPk 

Thanks for response, this helped me!
https://github.com/realm/realm-cocoa/issues/6285#issuecomment-538560001

**Comment by IhorChernysh** [comment] 2020-09-25 11:42
I installed the previous version:
pod 'RealmSwift', '~> 5.4.0'

**Comment by MeGaPk** [comment] 2020-09-25 11:43
> I installed the previous version:
> pod 'RealmSwift', '~> 5.4.0'

i tried to install 4.3.0 but have same error

**Comment by iHesh** [comment] 2020-09-25 12:44
> > git config --global url."[git@github.com](mailto:git@github.com):".insteadOf https://github.com/
> 
> Thanks @mir-dawn! I was able to install Realm using SwiftPM althought I had to tweak the command a bit to avoid breaking installation of other dependencies:
> 
> `git config --global url."git@github.com:catchorg/Catch2".insteadOf https://github.com/catchorg/Catch2`

I've tried replacing the url but I am getting this error 

`
Showing Recent Messages
terminated(1): HOME=/Users/heshamkalil TMPDIR=/var/folders/p6/2fh359351hxcd0xjlq7w9c5w0000gp/T/ GIT_SSH_COMMAND=ssh -oBatchMode=yes __CF_USER_TEXT_ENCODING=0x1F6:0x0:0x2 XPC_FLAGS=0x0 PATH=/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin XPC_SERVICE_NAME=com.apple.dt.Xcode.31968 GIT_TERMINAL_PROMPT=0 SHELL=/bin/zsh CA_DEBUG_TRANSACTIONS=1 USER=heshamkalil SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.sXI8yidakz/Listeners LOGNAME=heshamkalil MallocNanoZone=0 LD_LIBRARY_PATH=/Applications/Xcode.app/Contents/Developer/../SharedFrameworks/ CA_ASSERT_MAIN_THREAD_TRANSACTIONS=1 /Applications/Xcode.app/Contents/Developer/usr/bin/git -C /Users/heshamkalil/Library/Developer/Xcode/DerivedData/Selfapy-iOS-cqrotptjafzmhgbbxctbyabjesux/SourcePackages/checkouts/realm-cocoa submodule update --init --recursive output:
`

I've tried deleting the DerivedData, also deleting realm and downloading it again but nothing helped out.

I am on Xcode 12 and using SPM.

**Comment by iHesh** [comment] 2020-09-25 20:45
@MohammedBadr20s you can do it through this command 
`git config --global --unset url."git@github.com:".insteadOf https://github.com/`

or you can try `git config --global --edit` to edit your global git config and delete it manually.

**Comment by aczel** [comment] 2020-09-25 21:31
Does anyone care in this company, that we need to work with this crap???

**Comment by tgoyne** [comment] 2020-09-25 21:32
We do not have the power to fix github's server issues.

**Comment by jsflax** [comment] 2020-09-25 21:32
We are looking into this issue– it seems to have to do with Catch. One user as provided a workaround. Xcode 12 has come with a number of issues that we are working to solve.

**Comment by aczel** [comment] 2020-09-25 22:07
I am just wondering if this would be a GitHub server issue than why RealmSwift is the only library that I cannot install. Every other (around 20 different one) GitHub hosted/related libraries are loading without any problem. Please make some usable solution here, because the `git config --global url."git@github.com:catchorg/Catch2".insteadOf https://github.com/catchorg/Catch2` patch is not working. Thanks!

**Comment by enuance** [comment] 2020-09-25 23:10
Okay, so I was having the same issue with SPM. Adding an SSH key to my account for the computer I was working with ended up doing the trick. SPM is able to resolve Realm as a dependency now with the SSH key installed.

**Comment by Kalzem** [comment] 2020-09-26 08:30
It's back 🎉🎉🎉🎉🎉

**Comment by mir-dawn** [comment] 2020-09-28 08:30
I agree with @Kalzem. The issue looks to be resolved. I do not see any changes in the projects, so I still believe it was a GitHub issue. Anyone know if anything has changed?

**Comment by leemaguire** [comment] 2020-09-28 09:03
Closing as this is Github related & also looks to be resolved.

**Closed by leemaguire** 2020-09-28 09:03 UTC
Labels: O-Community

**Comment by jonmagic** [comment] 2020-10-01 23:26
I found another work around if you use the instructions at https://github.com/realm/realm-cocoa#building-realm. If you tell git to use protocol version 2 it doesn't fail when checking out the Catch2 submodule.

```bash
git -c protocol.version=2 submodule update --init --recursive
```

I'm not sure how to do the same thing with carthage (which had the same error according to https://github.com/realm/realm-cocoa/issues/6807) without updating that project so I opened https://github.com/Carthage/Carthage/pull/3062.

**Comment by jonmagic** [comment] 2020-10-02 17:09
## Next steps

After several days of trying I still haven't been able to replicate the problem we see in garage/prod in my development environment. The strongest lead we have is https://github.com/github/babeld/issues/962#issuecomment-701607648, that Apple compiles git with their own crypto library and we're not handling some edge case in how data gets chunked up.

Here's what we know right now:

* We can replicate the bug with this one liner: `rm -rf realm-cocoa && /usr/bin/git clone https://garage.github.com/jonmagic/realm-cocoa && cd realm-cocoa && /usr/bin/git -cprotocol.version=2 submodule update -f --init --recursive && cd ..` where `/usr/bin/git` is the version of git Apple ships with MacOS. In my case that would be `git version 2.24.3 (Apple Git-128)`
* This only occurs when the submodules are configured to use the http protocol
* The bug goes away if we specify protocol v2: `/usr/bin/git -c protocol.version=2`
* We haven't been able to replicate in development even when we put babeld behind an https reverse proxy
* Only one customer wrote in to complain about the issue (and I went ahead and commented on their repo with an alternate fix https://github.com/realm/realm-cocoa/issues/6806#issuecomment-702448003 in case we decide to push forward without fixing)

I'm at the point where I need help:

* Improving my debugging abilities, which likely means getting access to more parts of the stack, namely the git daemon that babeld talks to.
* More pairing time.

Alternatively, we could start ramping the feature back up as is and actively work with customers that experience this edge case to update their git commands to use protocol v2, or recommend they try the ssh protocol.

@iageoghe your thoughts?

**Comment by jonmagic** [comment] 2020-10-02 17:17
Apologies for the comment I left that was supposed to be on an internal debugging thread at github 🙏  I've deleted my comment here and I apologize for any confusion.
