### ISSUE TITLE
crash question

### ISSUE THREAD

**Issue by yixiaojichunqiu** [realm/realm-cocoa#6013] opened 2018-11-22 03:07 UTC
## Goals
solve question

## Expected Results
solve question

## Actual Results
crash

## Steps to Reproduce
when use kvo in swift4 arm64e   addobserve to a object which inherit from Object(inherit from RLMObjectBase)

## Code Sample
model.addObserver(self, forKeyPath: key as String, options:.new, context: nil)

## Version of Realm and Tooling
Realm framework version: ?
3.11.2
Realm Object Server version: ?

Xcode version: ?
10.1
iOS/OSX version: ?
12.1
Dependency manager + version: ?

**Comment by bmunkholm** [comment] 2018-11-22 09:49
@yixiaojichunqiu Please provide more information so we can help.
Which crash?
How do we reproduce the crash? Provide a project or test case.

**Comment by yixiaojichunqiu** [comment] 2018-11-22 10:35
@bmunkholm thank you

**Comment by bmunkholm** [comment] 2018-11-22 10:58
@yixiaojichunqiu We don't have that device. Could you please check if you get the error on other devices or in simulator?
Also please post all details about the crash. What information do you get?
How have you tried to debug this?
Can you reduce it further down to a minimal test case?

**Comment by yixiaojichunqiu** [comment] 2018-11-22 11:43
@bmunkholm 
I doubt it only happen on device which architecture is arm64e
other ipad and simulator do not happen it
download crash screenshot in https://github.com/yixiaojichunqiu/pic

**Comment by yixiaojichunqiu** [comment] 2018-11-22 11:54
import UIKit
import RealmSwift

class Model: Object {
    @objc dynamic var age:Double = 18
}


import UIKit
class ViewController: UIViewController {

    let model = Model.init()
    override func viewDidLoad() {
        super.viewDidLoad()
        model.addObserver(self, forKeyPath: "age", options: .new, context: nil)
    }
    
    deinit {
        model.removeObserver(self, forKeyPath: "age")
    }

    override func observeValue(forKeyPath keyPath: String?, of object: Any?, change: [NSKeyValueChangeKey : Any]?, context: UnsafeMutableRawPointer?) {
        print("touch")
    }
    
    override func touchesBegan(_ touches: Set<UITouch>, with event: UIEvent?) {
        model.age = 28
    }
    
}

only this, the project will crash in RLMObjectBase
this line

- (void)addObserver:(id)observer
         forKeyPath:(NSString *)keyPath
            options:(NSKeyValueObservingOptions)options
            context:(void *)context {
    if (!_observationInfo) {
        _observationInfo = new RLMObservationInfo(self);
    }
    _observationInfo->recordObserver(_row, _info, _objectSchema, keyPath);

    [super addObserver:observer forKeyPath:keyPath options:options context:context];
}

info 
Thread 1: EXC_BAD_ACCESS (code=1, address=0x0)

**Comment by yixiaojichunqiu** [comment] 2018-11-22 11:57
@bmunkholm thank you
the test is very simple in https://github.com/yixiaojichunqiu/testRealm
and the crash is happen in model.addObserver(self, forKeyPath: "age", options: .new, context: nil)
very direct

**Comment by bmunkholm** [comment] 2018-11-22 12:09
It doesn't happen in the simulator if you simulate that exact device?
From your screenshoot, could you should show the actual call where it crashes? It cashes due to so null reference. Please follow that one.

Just FYI, you can copy-paste screenshoots directly here in github - no need for special repos for that :-)

**Comment by bmunkholm** [comment] 2018-11-22 12:10
For reference - the pic from above: 
![image](https://user-images.githubusercontent.com/1215687/48902173-08626900-ee58-11e8-9db4-e20cca151fb8.png)

**Comment by yixiaojichunqiu** [comment] 2018-11-22 12:35
if model inherit NSObject，not happen in the new device ipad
@bmunkholm 
oh thank you tell me
<img width="77" alt="2018-11-22 8 34 41" src="https://user-images.githubusercontent.com/6872868/48903301-159e4880-ee96-11e8-85da-221f47015eaf.png">
so cool

**Comment by yixiaojichunqiu** [comment] 2018-11-22 12:51
<img width="1341" alt="1jndkjnsj" src="https://user-images.githubusercontent.com/6872868/48904067-39fb2480-ee98-11e8-8953-efd92eb8a6f1.png">
<img width="1373" alt="2sjksnjk" src="https://user-images.githubusercontent.com/6872868/48904093-4c755e00-ee98-11e8-9700-26bfb6bad64a.png">

**Comment by lzx2015** [comment] 2018-11-23 02:56
In my project, The same problem happened in the latest iPad

**Comment by yixiaojichunqiu** [comment] 2018-11-23 10:09
@bmunkholm  how should I solve the question
I find when I archive the project,export a ipa,then run the new ipad,it also not happen

**Comment by tgoyne** [comment] 2018-11-26 17:51
From the Xcode 10.1 release notes:

> Support for arm64e (Preview)
>
> To try the developer preview of arm64e, select your iOS app target in the Project Editor, find its Architectures build setting, select the Other… option, and add arm64e to the list of architectures.
>
> The App Store and TestFlight don't accept submissions containing arm64e. Xcode will remove arm64e content from your app when you distribute from the Organizer window. (42296212)

When you rxport an ipa and then install that on the ipad it doesn't use the arm64e version, so any arm64e-specific issues won't happen. This also means that this crash currently can't happen for any actual end users.

**Comment by tgoyne** [comment] 2018-11-26 17:57
The iPhone XS also supports arm64e, so I'll see if I can reproduce the crash on one of those.

**Comment by tgoyne** [comment] 2018-11-26 18:17
Same crash does happen on the iPhone XS.

https://github.com/wordpress-mobile/WordPress-iOS/pull/10400 is an example of other people running into the exact same crash with no Realm involved.

**Comment by tgoyne** [comment] 2018-11-26 22:13
I reduced the crash to the following code and filed a radar (46256354):
```swift
@objc class SwiftBase: NSObject {
    @objc dynamic var value = 0
}
func test() {
    let obj = SwiftBase()
    let subClass: AnyClass = objc_allocateClassPair(SwiftBase.self, "ObjcSubclass", 0)!
    objc_registerClassPair(subClass)
    object_setClass(obj, subClass)
    obj.addObserver(obj, forKeyPath: "value", options: .new, context: nil)
}
```

**Comment by yixiaojichunqiu** [comment] 2018-11-27 07:41
thank you,I got it

**Comment by Fab1n** [comment] 2018-12-05 11:58
@tgoyne is there any progress on Apple's side regarding this issue? 
Is there a proper workaround for this scenario? Not use KVO anymore or what can we do?

**Comment by tgoyne** [comment] 2018-12-05 16:22
My radar was closed as a dupe. AFAICT it only happens with Xcode 10.1, so you can just use 10.0 until apple fixes it.

**Comment by jsflax** [comment] 2021-01-21 17:46
This was a bug with Xcode 10.1 that we no longer support.

**Closed by jsflax** 2021-01-21 17:46 UTC
Labels: O-Community, T-Bug-Crash
