### ISSUE TITLE
Object has been deleted or invalidated when swiping fast between viewcontrollers

### ISSUE THREAD

**Issue by CedricVanAsch** [realm/realm-cocoa#3789] opened 2016-06-22 10:40 UTC
## Goals
I have two viewControllers. I can swipe between them, and both show their own content (from the Realm database)

## Expected Results
When I swipe fast between the two controllers, data etc. should be fine.

## Actual Results
Terminating app due to uncaught exception 'RLMException', reason: 'Object has been deleted or invalidated.'

## Steps to Reproduce
Make two viewcontrollers where you can swipe between (I used the CarbonKit swift one)

## Code Sample
Both my classes are the same, this is an example of one of them. The only difference is that In the other class I do a makeString?.article.append(item) (other column in the same Model). 
```swift
class SearchFolderResultFetcher {
    
    static let shared = SearchFolderResultFetcher()  // singleton object
    
    internal func fetchAllData(searchString: String) {
        
        //guard that user doesn't do an empty search
        guard searchString != "" else {
            return
        }
        let encodeURL = searchString.stringByAddingPercentEncodingWithAllowedCharacters(NSCharacterSet.URLQueryAllowedCharacterSet())
        
        let URL = "searchFolderURL".localized + encodeURL!
        // get all the folders that need to be added to the AutoComplete Model
        Alamofire.request(.GET, URL).responseObject { (response: Response<Folders, NSError>) in
            if response.result.isSuccess {
                let mappedObject = response.result.value
                let realm = try! Realm()
                let openAutoComplete = realm.objects(AutoComplete)
                try! realm.write {
                    if let everythingUnderResult = mappedObject?.result {
                        //open AutoComplete model and filter the search column, where searchString == search
                        let searchifExists = openAutoComplete.filter("search == %@", searchString)
                        
                        // if the count is 0, item doesn't exist, and needs to be added.
                        if searchifExists.count == 0 {
                            let myNewSearch = AutoComplete()
                            myNewSearch.search = searchString
                            realm.add(myNewSearch)
                        }
                        
                        let makeString = searchifExists.first
                        // if folder column isn't empty, delete it and replace with newest data
                        if makeString?.folder != nil {
                            realm.delete((makeString?.folder)!)
                        }
                        
                        let getSearchColumn = makeString?.search
                        
                        for item in everythingUnderResult {
                            if searchString == getSearchColumn {          
                                //item exists, now add the folder to the autocomplete DB
                                realm.add(item, update: true)
                                makeString?.folder.append(item)
                            } else {
                                
                                let searchifExists = openAutoComplete.filter("search == %@", searchString)
                                let makeString = searchifExists.first
                                //item exists, now add the folder to the autocomplete DB
                                realm.add(item, update: true)
                                makeString?.folder.append(item)
                            }
                        }
                    }
                }
            
                // NS NOTIFICATION THAT IT HAS PUT IT ALL IN THE DB
                NSNotificationCenter.defaultCenter().postNotificationName(NotificationNames.AllFolderSearchResultsLoaded, object: nil)
                
            } else {
                print("couldn't get mobileapp data")
            }
        }
        
    }
    
}

```

My model is the following: 
```
class AutoComplete: Object {
    dynamic var search: String?
    var folder = List<Folder>()
    var article = List<Article>()
    var producer = List<Producer>()
    var brand = List<Brand>()
}

```
## Version of Realm and Tooling
Realm version: 1.0.1

Xcode version: 7.3

iOS/OSX version: 10.11.5

Dependency manager + version: CocoaPods 1.0.0

**Comment by JadenGeller** [comment] 2016-06-22 18:24
I'm having trouble determining the issue simply from the code snippet given. Specifically, it's hard to determine why a UI action might cause the crash without any code relating to the UI action. Does the `fetchAllData` function get invoked whenever the view controller becomes visible again, for example? If you could provide me with more information, that'd be superb.

**Comment by bdash** [comment] 2016-06-22 18:27
An exception breakpoint would also reveal exactly which object has been invalidated, which may help in tracking down the cause of the problem.

**Comment by CedricVanAsch** [comment] 2016-06-23 09:16
@JadenGeller The issue occurs when I reload my view very fast. The fetchAllData function gets invoked every time the view is refreshed (visible again). I do this with an NSNotification, which is triggered multiple times since I'm doing it quite fast. 
I tried doing an exception breakpoint and catch the error, but it goes to the Appdelegate class.

**Comment by JadenGeller** [comment] 2016-06-24 19:02
The exception is likely being thrown because some deleted object is being mutated. I see you delete `makeString!.folder` and then later try to append to it. I think this is the source of your error.

**Comment by JadenGeller** [comment] 2016-06-28 21:01
Did you end up figuring this out, @CedricVanAsch? If not, let me know what changed. 🙂

**Comment by CedricVanAsch** [comment] 2016-06-29 06:44
@JadenGeller I 'patched' it by making sure that that same function isn't called twice in a row (I think because of the Alamofire async call handling, the two requests overlap). This causes the code not to crash anymore.

**Comment by JadenGeller** [comment] 2016-06-29 06:48
Glad you were able to figure it out! I'll close this issue, but definitely reopen it and let me know if it happens again.

**Closed by JadenGeller** 2016-06-29 06:48 UTC
Labels: T:Help
