### ISSUE TITLE
schemaVersionAtURL() throwing errror

### ISSUE THREAD

**Issue by dmorrow** [realm/realm-cocoa#5118] opened 2017-07-12 16:03 UTC
Following up on https://github.com/realm/realm-cocoa/issues/5034
It was closed, so I'm re-adding my question here.

While I am doing a major change to my Realm, I have something like this set
```
var config = Realm.Configuration(
            schemaVersion: schemaVersion,
            migrationBlock: migrationBlock)
if let path = Realm.Configuration.defaultConfiguration.fileURL, try schemaVersionAtURL(path) < 100 {
    config.migrationBlock = nil
    config.deleteRealmIfMigrationNeeded = true
}
```

I update the schema version, but before setting `deleteRealmIfMigrationNeeded` it crashes when I check `schemaVersionAtURL`

> Directory at path '/Users/***/Library/Developer/CoreSimulator/Devices/42BFE373-4547-4B47-917B-7BCF874F54D6/data/Containers/Data/Application/9DEF2E22-0A58-4FB8-A1B7-4C49B71B6269/Documents/default.realm' does not exist."

Do I need to increment the `schemaVersion` even if I am always deleting the Realm?  Is that the only way to trigger a migration?

**Comment by jpsim** [comment] 2017-07-12 17:52
[`schemaVersionAtURL(_:)`](https://realm.io/docs/swift/latest/api/Functions.html#/s:F10RealmSwift18schemaVersionAtURLFzTV10Foundation3URL13encryptionKeyGSqVS0_4Data__Vs6UInt64) will throw an exception if no file exists at the URL you've passed it.

> Do I need to increment the `schemaVersion` even if I am always deleting the Realm? Is that the only way to trigger a migration?

I don't understand this. Which are you doing? Are you always deleting the Realm or are you triggering migrations?

Without really understanding what you're trying to achieve, here's a change that will make your code not crash:

```swift
var config = Realm.Configuration(
            schemaVersion: schemaVersion,
            migrationBlock: migrationBlock)
if let path = Realm.Configuration.defaultConfiguration.fileURL, FileManager.default.fileExists(atPath: path.path), try schemaVersionAtURL(path) < 100 {
    config.migrationBlock = nil
    config.deleteRealmIfMigrationNeeded = true
}
```

**Comment by dmorrow** [comment] 2017-07-12 18:21
@jpsim Thanks for the response.
I am trying to delete the Realm if the version is lower than a specific value, otherwise run migrations.  I had assumed that the fileURL returned by Realm.Configuration.defaultConfiguration pointed to a file.  
Why wouldn't the file exist however - I'm rebuilding on the sim, so wouldn't the Documents folder remain?
It seems that by incrementing the schemaVersion and deleteRealmIfMigrationNeeded = true cause an unstable state.

**Comment by jpsim** [comment] 2017-07-12 18:29
Without seeing more of your code, I can't tell you why the Realm file doesn't exist at that location. It might be that it's the first time the app is running on your simulator.

`Realm.Configuration.defaultConfiguration.fileURL` points to _where_ the Realm file will be created on first access, but simply creating a `Realm.Configuration` doesn't create that file.

> It seems that by incrementing the schemaVersion and deleteRealmIfMigrationNeeded = true cause an unstable state.

If you think you've found a bug in Realm, sharing a sample Xcode project that reproduces the issue is the best way for us to investigate.

**Comment by dmorrow** [comment] 2017-07-12 20:30
@jpsim here is the code.  I can confirm that the crashes are caused in new builds over old builds, so the Realm file should already be in place.
{code}

class AppDelegate {
    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
        ... //basic configuration methods that don't access Realm 
        MigrationManager.shared.migrate()
        ...
}

class MigrationManager {
    static let shared = MigrationManager()
    
    let schemaVersion: UInt64 = 20
    
    private var migrationBlock: MigrationBlock? {
        return { migration, oldSchemaVersion in
            ....
        }
    }
    
    func migrate() {
        var config = Realm.Configuration(
            schemaVersion: schemaVersion,
            migrationBlock: migrationBlock)
        do {
            if let path = Realm.Configuration.defaultConfiguration.fileURL, try schemaVersionAtURL(path) < 1000 { //force delete Realm if schema version is less than 9
                config.migrationBlock = nil
                config.deleteRealmIfMigrationNeeded = true
            }
        } catch {
            print(error)
        }
        
        Realm.Configuration.defaultConfiguration = config
        do {
            let _ = try Realm()
        } catch {
            print(error)
        }
    }
}
{code}

**Comment by jpsim** [comment] 2017-07-12 21:09
I don't think the code you shared is enough to reproduce the issue you're seeing. I've created a sample project with the code snippets you shared, which you can download here: https://static.realm.io/debug/GH5118.tgz

Could you please download that and add whatever code or steps are missing in order to reproduce the issue you're seeing?

Thanks.

**Comment by dmorrow** [comment] 2017-07-13 12:54
@jpsim 
Thanks for the sample.  I modified the AppDelegate to reproduce the crash.
[AppDelegate.swift.zip](https://github.com/realm/realm-cocoa/files/1145161/AppDelegate.swift.zip)

I added a subclass of Object so that we're persisting something to the Realm, and have something to migrate.

Run once, and then uncomment lines 27 and 72.  This will add a property to the `Object` subclass and also set a value to be persisted.  If I understand correctly, the Realm should be deleted and recreated and then the instance of `SampleObject` should be persisted.  Instead, there is a crash on `try! Realm` for no file or directory.  Is the deleteRealm an async method?

I assume this is user error, but I'm not clear on how to achieve what I want - I want to be able to selectively set `deleteRealmIfMigrationNeeded` depending on what previous version users had.  If they've already done the big migration and now there are just minor changes that can be auto migrated then I don't want to delete.

**Comment by jpsim** [comment] 2017-07-13 17:27
I still can't reproduce it.

![gh5118](https://user-images.githubusercontent.com/474794/28179111-c67c2adc-67b5-11e7-99be-75657cea88cb.gif)

All I did was add a call to `print(realm.objects(SampleObject.self))` to make it clear that everything runs successfully.

**Comment by dmorrow** [comment] 2017-07-13 22:46
@jpsim I've narrowed down the problem.  I am also using the Realm Browser while I am testing the app.  Without the Realm open in the Realm Browser, there is no crash.  However, if the Realm is open in the Realm Browser, the crash occurs.  This issue should probably be moved to the Realm Browser project.

![capture](https://user-images.githubusercontent.com/14465/28190953-87277f12-67fb-11e7-9557-fdd3a79c36f3.gif)

**Comment by jpsim** [comment] 2017-07-13 22:58
Ah, well that explains the problem then. Deleting a Realm file while Realm APIs are still accessing it (whether through your app, or through the Realm Browser), will inevitably lead to Realm crashing.

Perhaps you could file a feature request towards the Realm Browser to close the window & prompt an alert when the underlying file is deleted: https://github.com/realm/realm-browser-osx/issues/new

Closing this.

**Closed by jpsim** 2017-07-13 22:58 UTC
Labels: T:Help
