### ISSUE TITLE
Umbrella header for module 'Realm' does not include header '/core/realm.h'

### ISSUE THREAD

**Issue by OneSman7** [realm/realm-cocoa#7119] opened 2021-02-15 16:39 UTC
## Goals
Updated Realm Swift to 10.5.2. Trying to build our project with it.

## Expected Results
Project builds without errors or warnings concerning Realm library.

## Actual Results
A warning about umbrella  header is displayed: /<module-includes>:1:1: Umbrella header for module 'Realm' does not include header '/core/realm.h'

![Снимок экрана 2021-02-15 в 19 37 34](https://user-images.githubusercontent.com/4619076/107972937-9f7de300-6fc5-11eb-8bee-00918073ffe8.png)

## Steps for others to Reproduce
Just build any swift project with Realm pod having inhibit_all_warnings! and use_modular_headers! settings in Podfile.

### Podfile

```
platform :ios, '11.0'

source 'https://github.com/CocoaPods/Specs.git'

inhibit_all_warnings!
use_modular_headers!

target 'Mobile-Mos.ru' do
  
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Analytics'
  pod 'Socket.IO-Client-Swift', '< 16'
  pod 'gRPC-Swift', '1.0.0-alpha.20'
  
  pod 'Stencil'
  pod 'FLAnimatedImage'
  pod 'Kingfisher'
  pod 'YandexMapsMobile', '4.0.0-full'
  pod 'YandexMobileAds'
  pod 'YandexMobileMetricaPush'
  pod 'CardIO'
  
  pod 'Pulley'
  pod 'AXPhotoViewer/Core', :git => 'https://github.com/OneSman7/AXPhotoViewer.git', :branch => 'resources_bundle'
  pod 'AXPhotoViewer/Kingfisher', :git => 'https://github.com/OneSman7/AXPhotoViewer.git', :branch => 'resources_bundle'
  pod 'JTAppleCalendar', '~> 7.0'
  pod 'Chatto', :git => 'https://github.com/badoo/Chatto.git', :commit => '79f9e4091c23788a70421d434d966e223f205dea'
  pod 'ChattoAdditions', :git => 'https://github.com/badoo/Chatto.git', :commit => '79f9e4091c23788a70421d434d966e223f205dea'
  
  target 'Mobile-Mos.ruTests' do
      inherit! :search_paths
  end
  
end

post_install do |installer|

    pods_project = installer.pods_project
    
    # Determining minimal deployment target
    
    deployment_target_key = 'IPHONEOS_DEPLOYMENT_TARGET'
    deployment_targets = pods_project.build_configurations.map{ |config| config.build_settings[deployment_target_key] }
    minimal_deployment_target = deployment_targets.min_by{ |version| Gem::Version.new(version) }
    
    puts 'Minimal deployment target is ' + minimal_deployment_target
    puts 'Setting each pod deployment target to ' + minimal_deployment_target
    
    # Removing arm64 arch for simulator until all libraries support it
    
    simulator_excluded_archs_key = 'EXCLUDED_ARCHS[sdk=iphonesimulator*]'
    simulator_excluded_archs_value = 'arm64'
    aggregate_targets_names = installer.aggregate_targets.map{ |target| target.name }.to_set
    
    puts 'Removing arm64 arch for simulator'
    
    # Updating pods targets build configurations settings
    
    pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings[deployment_target_key] = minimal_deployment_target
        unless aggregate_targets_names.include?(target.name)
          config.build_settings.delete(simulator_excluded_archs_key)
          config.build_settings[simulator_excluded_archs_key] = simulator_excluded_archs_value
        end
      end
    end
    
    # Updating aggregate targets Xcode Configuration (.xcconfig) files
    
    installer.aggregate_targets.each do |aggregate_target|
      aggregate_target.xcconfigs.each do |config_name, config_file|
        config_file.attributes.delete(simulator_excluded_archs_key)
        config_file.attributes[simulator_excluded_archs_key] = simulator_excluded_archs_value
        xcconfig_path = aggregate_target.xcconfig_path(config_name)
        config_file.save_as(xcconfig_path)
      end
    end
    
    Dir.glob(installer.sandbox.target_support_files_root + "Pods-*/*.sh").each do |script|
        flag_name = File.basename(script, ".sh") + "-Installation-Flag"
        folder = "${TARGET_BUILD_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}"
        file = File.join(folder, flag_name)
        content = File.read(script)
        content.gsub!(/set -e/, "set -e\nKG_FILE=\"#{file}\"\nif [ -f \"$KG_FILE\" ]; then exit 0; fi\nmkdir -p \"#{folder}\"\ntouch \"$KG_FILE\"")
        File.write(script, content)
    end

end
```

## Code Sample
NA

## Version of Realm and Tooling

ProductName:	macOS
ProductVersion:	11.2.1
BuildVersion:	20D74

/Applications/Xcode.app/Contents/Developer
Xcode 12.4
Build version 12D4e

/usr/local/bin/pod
1.10.1
(not in use here)

/bin/bash
GNU bash, version 3.2.57(1)-release (arm64-apple-darwin20)

carthage not found
(not in use here)

/usr/bin/git
git version 2.24.3 (Apple Git-128)

**Comment by visdyn** [comment] 2021-02-15 17:54
I don't see Realm in the podfile. Was is added through some other means?

**Comment by OneSman7** [comment] 2021-02-15 18:17
Sorry, it is added as other pod dependency like this `s.dependency 'RealmSwift'` Maybe it is important.

**Comment by OneSman7** [comment] 2021-02-15 18:18
I found a similar issue which I did not spot at first.
https://github.com/realm/realm-cocoa/issues/7113

**Comment by dianaafanador3** [comment] 2021-02-16 11:44
Hi @OneSman7 we will try to reproduce this and get back to you as soon as possible.

**Comment by Arrcuas** [comment] 2021-02-23 11:01
I have the same problem. The realm.h is missing,  and got the error

<unknown>:0: error: unexpected input file: /Users /StorageManager.Swift
Command CompileSwiftSources failed with a nonzero exit code

**Comment by dianaafanador3** [comment] 2021-02-23 11:08
Hi @Arrcuas can you please clean the pod cache and then try a clean pod install (`pod deintegrate` and then `pod install`). Also clean the project and derived data associated to it before building it again.

**Comment by Arrcuas** [comment] 2021-02-24 14:48
thank you diana, I solved the. problem the file was .Swift and not .swift..
this little mistake took me 2 hours of search xD

Am Di., 23. Feb. 2021 um 12:08 Uhr schrieb dianaafanador3 <
notifications@github.com>:

**Comment by dianaafanador3** [comment] 2021-02-24 14:51
Hey @Arrcuas I'm so sorry, i didn't notice the error, if you have any more issues, do not doubt to ask.

**Comment by cltnschlosser** [comment] 2021-03-03 14:29
Copied from #7154 

I did a bit of investigation and the `realm.h` header was introduced with realm-core 10.4.0 (https://github.com/realm/realm-cocoa/pull/7063), which was the version updated to in 10.5.2. The Headers subspec is including `"include/**/Realm.h"`. I'm guessing that is doing a case insensitive match and pulling in the core header into the project incorrectly.

Does this need to use `**` in the include path for these headers?

**Comment by dianaafanador3** [comment] 2021-03-03 14:33
Hi @cltnschlosser thanks for the info, and taking the time to investigate this. We're checking why this warning is happening and any extra info is helpful.

**Comment by dianaafanador3** [comment] 2021-03-05 11:58
I'm going to close this, in favour of https://github.com/realm/realm-cocoa/issues/7113
Duplicate of #7113

**Closed by dianaafanador3** 2021-03-05 11:58 UTC
Labels: O-Community
