### ISSUE TITLE
Crash: happens on the app starts, when the user upgrade the app with a new Realm version on the board (f.e. 2.4.3 -> 2.5.1)

### ISSUE THREAD

**Issue by KovtunOleg** [realm/realm-cocoa#4879] opened 2017-04-19 17:43 UTC
## Crash log
[11311174093.log.zip](https://github.com/realm/realm-cocoa/files/936693/11311174093.log.zip)

## Steps to Reproduce
Upgrade the app with a new Realm version on the board (f.e. 2.4.3 -> 2.5.1).
This crash happens only on the first app start after the upgrade.
On the next launch everything works as expected.
It appears really rarely, so I think there should be a race condition somewhere.

## Version of Realm and Tooling

- Realm framework version: **2.5.1**
- Xcode version: **8.3.1**
- iOS version: **9.3.5, 10.3.1**
- Devices: **iPad 2, iPhone 5**
- Dependency manager: **CocoaPods 1.2.0**

**Comment by istx25** [comment] 2017-04-19 22:14
Hi @KovtunOleg. Thanks for filing this issue as I requested via email. I wanted to let you know that we've received your issue and that I'm going to escalate it to get some eyes on it. Cheers!

**Comment by TimOliver** [comment] 2017-04-19 22:53
Hi there @KovtunOleg! Sorry to hear you've been experiencing a crash in the app. Thanks for the crash log. If it's okay, I'd like to ask some questions to get some more context for the crashes.

It's interesting to note that this issue is occurring on iPad 2 and iPhone 5, both 32-bit devices. Do you have any record of it occurring on any 64-bit iOS devices?

Additionally, can you please provide us with the code for your Realm model objects and the code you're using to set up Realm on that initial run?

Thanks!

**Comment by KovtunOleg** [comment] 2017-04-20 12:17
Hi Tim,

Today we've got one crash from  iPad (4th gen, Wi-Fi) , and all other devices a really 32-bit. So, maybe the problem occurs only on the old devices.

I setup sample project for you attached to this email. You just need to run  pod update in the root directory.

Thank you.

**Comment by istx25** [comment] 2017-04-20 18:05
Hi @KovtunOleg. Unfortunately GitHub doesn't upload zip files that are sent in reply to comments on GitHub issues. Would you be able to upload the zip on GitHub.com so we can see it? Thanks!

**Comment by TimOliver** [comment] 2017-04-20 18:07
Haha thanks for that @istx25! I was just about to say that! XD

@KovtunOleg Or conversely, if you'd prefer for the code to remain private, please send it to `help@realm.io`. I can access it from there.

**Comment by KovtunOleg** [comment] 2017-04-20 19:12
Hello guys,

I uploaded sample project to GitHub  https://github.com/KovtunOleg/RealmSampleProject .

Thank you.

**Comment by jpsim** [comment] 2017-04-21 22:48
@KovtunOleg I haven't yet been able to reproduce the crash, but I also can't find the steps to reproduce that you sent. Where can I find those?

Here are the steps I'm following:

1. Set `pod 'Realm', '= 2.4.3'` in the `Podfile`
2. Run `pod install`
3. Build & Run the app for the first time on an iPhone 4S
4. Wait for the app to successfully show the table view with all data populated
5. App will crash because the Realm file format is for a later version than Realm 2.4.3. This is expected. Realm files made with versions 2.5.0 or later aren't compatible with previous versions of Realm.

Please include clear numbered steps to reproduce the assertion failure you're seeing.

**Comment by KovtunOleg** [comment] 2017-04-22 06:41
Hi guys,

sorry, I forgot to downgrade Realm data base to the lower version, so I recreate the data base with an old  Realm 2.4.4 .

To reproduce:

1. Remove the app from your device, to avoid migration problems.
2. Run ' git pull '
3. Run ' pod update ', currently it will use  Realm 2.4.4 version.
4. Run the app on your old device (f.e.  iPhone 4S ).
5. In the Podfile use the latest Realm version ( pod 'Realm' )
6. Run 'pod update', so now the app will use the latest Realm version (f.e.  Realm 2.6.2 ).
7. Run the app, and maybe you will see the crash.

Unfortunelty I can't reproduce this crash by myself, but we can see it happens on the Hockey App approximately 2 times per day.

**Comment by jpsim** [comment] 2017-04-24 22:17
I ran this 20 times each on both an iPhone 4S & an iPhone 5S, with no failures.

I automated my testing process to speed things up, which gives me the nice advantage of being able to share _exactly_ the steps I followed to attempt to reproduce this.

First, I created both an IPA archive for the Realm 2.4.4 version and the Realm 2.6.2 version:

```
$ xcodebuild -workspace SampleProject.xcworkspace -scheme SampleProject -archivePath app.xcarchive archive
$ xcodebuild -exportArchive -archivePath app.xcarchive -exportPath . -exportOptionsPlist exportOptions.plist
$ mv SampleProject.ipa realm244.ipa
$ cat exportOptions.plist
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>method</key>
    <string>development</string>
    <key>teamID</key>
    <string>...</string>
  </dict>
</plist>
```

I repeated this for Realm 2.6.2, saving the IPA at `realm262.ipa`.

I then programmatically installed the 2.4.4 version, launched it manually, confirmed it succeeded, quit the app, pressed enter to then install the 2.6.2 version, launch it manually, confirm it succeeded, quit the app, pressed enter again to programmatically uninstall the app. I repeated this process 20 times for each device I tested.

```bash
#!/bin/bash

COUNTER=0

while :; do
  ideviceinstaller -i realm244.ipa
  read -p "Run SampleProject with Realm 2.4.4, quit app & press enter to continue"
  ideviceinstaller -i realm262.ipa
  read -p "Run SampleProject with Realm 2.6.2, quit app & press enter to continue"
  ideviceinstaller -U Home.SampleProject
  COUNTER=$((COUNTER + 1))
  echo "Completed $COUNTER upgrade cycles"
done
```

**Comment by KovtunOleg** [comment] 2017-04-25 05:19
Hi,

I see, this crash is really really rare.

Any way, big thanks for your time guys, we really appreciate this.


Отправлено из мобильной Почты Mail.Ru


вторник, 25 апреля 2017 г., 1:17 +0300 от JP Simard  <notifications@github.com>:
>I ran this 20 times each on both an iPhone 4S & an iPhone 5S, with no failures.
>I automated my testing process to speed things up, which gives me the nice advantage of being able to share  exactly the steps I followed to attempt to reproduce this.
>First, I created both an IPA archive for the Realm 2.4.4 version and the Realm 2.6.2 version:
>$ xcodebuild -workspace SampleProject.xcworkspace -scheme SampleProject -archivePath app.xcarchive archive
$ xcodebuild -exportArchive -archivePath app.xcarchive -exportPath . -exportOptionsPlist exportOptions.plist
$ mv SampleProject.ipa realm244.ipa
$ cat exportOptions.plist
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>method</key>
    <string>development</string>
    <key>teamID</key>
    <string>...</string>
  </dict>
</plist>
>I repeated this for Realm 2.6.2, saving the IPA at realm262.ipa.
>I then programmatically installed the 2.4.4 version, launched it manually, confirmed it succeeded, quit the app, pressed enter to then install the 2.6.2 version, launch it manually, confirm it succeeded, quit the app, pressed enter again to programmatically uninstall the app. I repeated this process 20 times for each device I tested.
>#!/bin/bash

COUNTER=0

>while :; do
  ideviceinstaller -i realm244.ipa
  read -p "Run SampleProject with Realm 2.4.4, quit app & press enter to continue"
  ideviceinstaller -i realm262.ipa
  read -p "Run SampleProject with Realm 2.6.2, quit app & press enter to continue"
  ideviceinstaller -U Home.SampleProject
  COUNTER=$((COUNTER + 1))
  echo "Completed $COUNTER upgrade cycles"

**Comment by jpsim** [comment] 2017-04-25 18:18
I'll be closing this because as-is, it's not an actionable ticket. @KovtunOleg I encourage you to reach out again if you manage to make this more reproducible. Even if I knew that running 100x instead of 20x would make it more likely to trigger, I could try that, but as is, I feel that's just a waste of time.

**Closed by jpsim** 2017-04-25 18:18 UTC
Labels: T:Help

**Comment by KovtunOleg** [comment] 2017-04-25 19:00
Hello JP,
Of course,
Thank you for your effort.



Отправлено из мобильной Почты Mail.Ru


вторник, 25 апреля 2017 г., 21:19 +0300 от JP Simard  <notifications@github.com>:
