### ISSUE TITLE
Carthage-related: warning: Swift error in module RealmSwift when trying to debug/print an object in the console

### ISSUE THREAD

**Issue by ivan-konov** [realm/realm-cocoa#4643] opened 2017-02-07 19:46 UTC
## Expected Results

Be able to print the contents of let things = realm.objects(Thing.self) from the code sample(I know now there should be nothing in there but this is not relevant to the issue IMO).

## Actual Results

I get this warning:

warning: Swift error in module RealmSwift.
Debug info from this module will be unavailable in the debugger.## Steps to Reproduce

What are steps we can follow to reproduce this issue?

I just hit a breakpoint in an IBAction call. An then try `po things` in the console.

## Code Sample

```
import UIKit
import RealmSwift

class Thing: Object {
    dynamic var name = "Thing"
}

class SomeThing: Thing {
    dynamic var number = 0
}

class NoThing: Thing {
    dynamic var iAmEmpty = true
}

class ViewController: UIViewController {
    
    override func viewDidLoad() {
        super.viewDidLoad()
        let some = SomeThing()
        let no = NoThing()
        
        let realm = try! Realm()
        try! realm.write {
            realm.add(some)
            realm.add(no)
        }
    }
    
    @IBAction func tryStuff(_ sender: Any) {
        let realm = try! Realm()
        let things = realm.objects(Thing.self)
        
        for thing in things {
            print(thing.name)
        }
    }
}
```

## Version of Realm and Tooling

[In the CONTRIBUTING guidelines](https://git.io/vgxJO), you will find a script,
which will help determining these versions.

Realm version: 2.4.2

Xcode version: 8.2.1

iOS/OSX version: iOS 10.2 SImulator / iOS 10.2.1 Device

Dependency manager + version: Carthage 0.18.1

**Comment by austinzheng** [comment] 2017-02-07 21:39
Sorry to hear you're having problems. I tried replicating the problem with the setup you described above and couldn't reproduce it.

Could you try cleaning and rebuilding your project (Product menu while holding down Option --> Clean Build Folder), and seeing if you still run into the same problem?

**Comment by ivan-konov** [comment] 2017-02-07 21:53
The problem persists. Whatever I try to print if I break at let's say
`for thing in things {` in `tryStuff` prints this warning and then does the actual printing of the object.

**Comment by austinzheng** [comment] 2017-02-07 21:58
Is there any chance you can provide us with a sample project that reproduces the issue? Otherwise, I'm inclined to close this as a low-priority ticket, since it's not really interfering with your ability to debug. We've seen similar issues before, but they've all been transient.

**Comment by ivan-konov** [comment] 2017-02-07 21:59
Sure. Should I send it to and email or upload it somewhere?

**Comment by austinzheng** [comment] 2017-02-07 21:59
You can send it to help@realm.io. Thanks!

**Comment by ivan-konov** [comment] 2017-02-07 22:07
You should have and email :)

**Comment by austinzheng** [comment] 2017-02-07 22:18
Thanks for sending us a sample project. It seems to have something to do with Carthage. I'm going to repurpose this ticket to track this problem so we can investigate further. Thanks for reporting it!

**Comment by ivan-konov** [comment] 2017-02-07 22:59
Sure! I'd be glad to help make Realm better :)

**Comment by jpsim** [comment] 2017-02-15 02:07
@ivan-konov actually could you please file a Radar with Apple about this (https://bugreport.apple.com) or a Swift bug (https://bugs.swift.org) since this appears to be an LLDB issue.

**Comment by ivan-konov** [comment] 2017-02-22 03:16
Radar submitted.

**Comment by istx25** [comment] 2017-02-22 16:53
Awesome, thank you @ivan-konov. Mind sharing the Radar #?

**Comment by ivan-konov** [comment] 2017-02-22 19:35
radar# 30646008
Let me know if you think i should add more info or post corrections of my initial wording of the radar.

I also played a bit more with the sample project I sent you. It seems this warning appears only when trying to print Realm objects.

**Comment by istx25** [comment] 2017-02-27 17:37
Okay, thank you for sharing that.

**Comment by jpsim** [comment] 2017-03-09 01:16
@ivan-konov just so you know, radars aren't public, so we can't comment on the wording of your report, and also can't duplicate it or track its progress from Apple's side. There's a site called [Open Radar](http://www.openradar.me/) where many developers cross-post their Apple radars to maintain a public repository of them, so you could cross-post yours there and then we could duplicate and keep track.

**Comment by ivan-konov** [comment] 2017-03-09 07:10
There you go - [rdar://30646008](url)

**Comment by ivan-konov** [comment] 2017-03-13 01:23
@jpsim I have another  reply on the radar from Apple:

> Engineering has provided the following feedback regarding this issue: 
In current Swift releases, you’ll have to rebuild all Carthage Swift frameworks locally for debugging to succeed.

In that case I guess you would want to change the Carthage preferences of the project to fetch the code from GitHub and then build locally.

**Comment by jpsim** [comment] 2017-03-13 22:00
Alright, thanks for following up. This all but confirms that Realm isn't the culprit here, but rather current Carthage and Swift behaviors. Closing.

**Closed by jpsim** 2017-03-13 22:00 UTC
Labels: S:P2 Backlog, T:Bug

**Comment by ivan-konov** [comment] 2017-03-13 22:02
Sure. Does that mean that there will be upcoming changes on how Realm is installed through Carthage or it will still be distributed as a pre built framework?

**Comment by jpsim** [comment] 2017-03-13 22:34
We'll continue to distribute `Realm.framework` and `RealmSwift.framework` as binaries via Carthage, as Carthage offers a way to force to build from source (`--no-use-binaries`) for those who want it, while also retaining the advantages of prebuilt frameworks.
