### ISSUE TITLE
Fail to build Realm.frameowrk for watchOS from source code by Xcode 7 beta5

### ISSUE THREAD

**Issue by kishikawakatsumi** [realm/realm-cocoa#2368] opened 2015-08-10 12:33 UTC
It will fail to build Realm.frameowrk for watchOS from source code by Xcode 7 beta5 due to the following error. The failure occurred in linker phase. If using beta 4, the build succeeded without any errors. It will occur both `master` and `swift-2.0` branch. For iOS/OS X build also succeeded.

I think we should release new core library to fix this issue as soon as possible.

@tgoyne @jpsim @segiddins 

```
Ld build/DerivedData/Realm/Build/Products/Release-watchos/Realm.framework/Realm normal armv7k
    cd /Users/katsumi/Desktop/Realm/realm-cocoa
    export PATH="/Applications/Xcode-beta.app/Contents/Developer/Platforms/WatchOS.platform/Developer/usr/bin:/Applications/Xcode-beta.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/libexec:/usr/local/bin:/usr/bin:/bin:/usr/libexec:/usr/local/heroku/bin:/Users/katsumi/.rbenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/katsumi/Desktop/infer/infer/bin"
    export WATCHOS_DEPLOYMENT_TARGET=2.0
    /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -arch armv7k -dynamiclib -isysroot /Applications/Xcode-beta.app/Contents/Developer/Platforms/WatchOS.platform/Developer/SDKs/WatchOS2.0.sdk -L/Users/katsumi/Desktop/Realm/realm-cocoa/build/DerivedData/Realm/Build/Products/Release-watchos -Lcore -F/Users/katsumi/Desktop/Realm/realm-cocoa/build/DerivedData/Realm/Build/Products/Release-watchos -filelist /Users/katsumi/Desktop/Realm/realm-cocoa/build/DerivedData/Realm/Build/Intermediates/Realm.build/Release-watchos/watchOS.build/Objects-normal/armv7k/Realm.LinkFileList -install_name @rpath/Realm.framework/Realm -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -mwatchos-version-min=2.0 -dead_strip -fembed-bitcode-marker -lrealm-watchos -stdlib=libc++ -fobjc-arc -fobjc-link-runtime -fapplication-extension -single_module -compatibility_version 1 -current_version 1 -Xlinker -dependency_info -Xlinker /Users/katsumi/Desktop/Realm/realm-cocoa/build/DerivedData/Realm/Build/Intermediates/Realm.build/Release-watchos/watchOS.build/Objects-normal/armv7k/Realm_dependency_info.dat -o /Users/katsumi/Desktop/Realm/realm-cocoa/build/DerivedData/Realm/Build/Products/Release-watchos/Realm.framework/Realm
ld: in core/librealm-watchos.a(librealm-WatchOS-prelink.a.o), building for watchOS, but linking in object file built for iOS, for architecture armv7k
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **


The following build commands failed:
	Ld build/DerivedData/Realm/Build/Products/Release-watchos/Realm.framework/Realm normal armv7k
(1 failure)
```

**Comment by segiddins** [comment] 2015-08-10 15:23
Yes, I believe Thomas has gotten Beta 5 on CI and iirc there will be a patch release today with Beta 5 support.

**Comment by segiddins** [comment] 2015-08-10 18:26
This is actually a duplicate of https://github.com/realm/realm-cocoa/issues/2359, so I'm going to close this issue in favor of that one.

**Closed by segiddins** 2015-08-10 18:26 UTC
