### ISSUE TITLE
failure to build RealmSwift

### ISSUE THREAD

**Issue by danoctavian** [realm/realm-cocoa#2736] opened 2015-10-23 08:02 UTC
using

xcode 7.1 beta 3
CocoaPods 0.39
RealmSwift 0.96.1

it fails to compile Realm with 

```
object_store_exceptions.hpp file not found // in object_store_exceptions.cpp
```

How can i work around this?

**Comment by kishikawakatsumi** [comment] 2015-10-23 08:09
@danielpovlsen It will occur on the case-sensitive file system. Fixed at https://github.com/realm/realm-cocoa/pull/2675

The suggested workarounds are: 
- To use CocoaPods 0.38
- Copy your project to external disk formatted by case-insensitive file system. (Using disk image is the easiest way), then execute `pods install` there.
- That fix has been merged to master. So specify branch to install from `master`.
- Setup without CocoaPods. It will occur only CocoaPods install

**Comment by danoctavian** [comment] 2015-10-23 08:12
cheers dude, you're awesome.

**Comment by kishikawakatsumi** [comment] 2015-10-23 09:30
Sorry, I confirmed that it cannot resolve the issue to specify master branch.

The most reliable way is using case-insensitive file system temporarily for the setup.
1. Create case-insensitive formatted disk image with Disk Utility.
2. Then copy your project to the disk.
3. Execute `pod install` there.

If the project would be setup correctly, you can move anywhere the project.

**Comment by bdash** [comment] 2015-10-27 01:38
#2675 was included in 0.96.2, released earlier today. Given @kishikawakatsumi's comments above I'd expect this to be fixed with 0.96.2.

**Comment by nekonari** [comment] 2015-10-28 16:38
Still having issue here, even with 0.96.2. Anyone else?

**Comment by kishikawakatsumi** [comment] 2015-10-28 19:29
@nekonari This issue was fixed in 0.96.2. Could you try first removing cache then re-install like following:

```
rm -rf ~/Library/Caches/CocoaPods
rm -rf Pods
pod install
```

If you don't use a case-sensitive file system, there is a probability that the another problem will happen.

**Comment by nekonari** [comment] 2015-10-28 20:29
@kishikawakatsumi I'm linking them manually by downloading and adding the pre-built libraries into the project. If there is some cache that stores previous framework files, please let me know :(

**Comment by nekonari** [comment] 2015-10-28 22:42
I got it to work. In the build error, it was specifying a cache folder. Removing it solved this.

However, for some reason, I had Embed Frameworks build phase placed below Run Realm Script build phase, which was again creating a build error. I reordered these, and now it's compiling.

**Comment by kishikawakatsumi** [comment] 2015-10-28 23:22
> I had Embed Frameworks build phase placed below Run Realm Script build phase, which was again creating a build error.

@nekonari Because `strip-framework.sh` script assumes that the framework is in the app bundle. So the framework should be copied before running `strip-framework.sh`.

**Comment by nekonari** [comment] 2015-10-28 23:25
@kishikawakatsumi What puzzles me is why Xcode didn't simply replace the cached framework files with the new version..

**Comment by mrackwitz** [comment] 2015-11-06 16:18
@nekonari: That might happen especially if you change the way how you integrate stuff, Xcode reasons on base of what it would expect to see with the current setup, if there are built products left from a previous setup and those files wouldn't be created anymore or in a different way, it might happen, that they get stuck. For that reason, I'd generally recommend cleaning the build folder after making changes to the integration.

**Closed by mrackwitz** 2015-11-06 16:18 UTC
Labels: Help
