### ISSUE TITLE
Project with iOS and OS X targets fails to compile with "Undefined symbols"

### ISSUE THREAD

**Issue by dvor** [realm/realm-cocoa#3763] opened 2016-06-17 00:02 UTC
I have project with two targets - iOS and OS X. After adding Realm to it with CocoaPods it fails to compile for iOS target with `Undefined symbols for architecture x86_64`. For OS X everything works fine.

You can find sample project [here](https://github.com/dvor/ReproducingCocoaRealmIssue).

Realm version: 1.0.1
Xcode version: 7.3
CocoaPods: 1.0.1

**Comment by stel** [comment] 2016-06-17 09:19
Thanks for reporting this!

I can confirm this issue. Everything works with CocoaPods 0.39 though. There is a similar issues here: https://github.com/CocoaPods/CocoaPods/issues/5518

/cc @mrackwitz

**Comment by mrackwitz** [comment] 2016-06-28 14:31
I can confirm that this is a problem and could locate the root cause.

The problem here is that there is a name overlapping of the build product of the static library target generated by CocoaPods (`libRealm-iOS.a`) and the vendored static library used by the podspec (`librealm-ios.a`). Even though the name is not exactly identical, clang's linker is case-insensitive and uses the first matching according to the order of the `LIBRARY_SEARCH_PATHS`. As both are required changing the order doesn't help.

Usually the linter ensures that a pod can be built and included in a project. But it uses frameworks by default and doesn't additionally check whether a pod can be used in the integration mode with static libraries.

This must be fixed in CocoaPods. 

As an alternative workaround to what @stel proposed before, you could also declare `use_frameworks!` in your Podfile and use frameworks, while this will break backwards-compatibility to iOS 7.0 for distribution via the AppStore.

**Comment by bdash** [comment] 2016-06-28 15:12
Is it worth working around in Realm for now by using our core static libraries via different names with CocoaPods? We could easily rename them to `librealm-core-foo.a` within `build.sh cocoapods-setup`.

**Comment by jcmendez** [comment] 2017-03-21 00:06
Is this issue still open?  I cloned @dvor repo and updated it to current versions and my desired project structure with the shared code between iOS and OS X in a "Kit".  Here is the repo.  https://github.com/jcmendez/ReproducingCocoaRealmIssue

If I use `use_frameworks!` it builds, but I guess that's the same as @mrackwitz mentions above.  However on the actual project I'm trying to use this, even with `use_frameworks!`, I keep getting a bunch of undefined symbols (below) - any ideas?

````
Undefined symbols for architecture x86_64:
  "realm::BpTreeBase::replace_root(std::__1::unique_ptr<realm::Array, std::__1::default_delete<realm::Array> >)", referenced from:
      realm::Column<long long>::replace_root_array(std::__1::unique_ptr<realm::Array, std::__1::default_delete<realm::Array> >) in collection_notifier.o
      realm::BpTree<long long>::EraseHandler::replace_root_by_leaf(realm::MemRef) in collection_notifier.o
      realm::BpTree<long long>::EraseHandler::replace_root_by_empty_leaf() in collection_notifier.o
      realm::BpTree<long long>::clear() in collection_notifier.o
      realm::Column<long long>::replace_root_array(std::__1::unique_ptr<realm::Array, std::__1::default_delete<realm::Array> >) in external_commit_helper.o
      realm::BpTree<long long>::EraseHandler::replace_root_by_leaf(realm::MemRef) in external_commit_helper.o
      realm::BpTree<long long>::EraseHandler::replace_root_by_empty_leaf() in external_commit_helper.o
      ...
  "realm::BpTreeBase::write_subtree(realm::BpTreeNode const&, unsigned long, unsigned long, unsigned long, realm::BpTreeBase::SliceHandler&, realm::_impl::OutputStream&)", referenced from:
      realm::BpTree<long long>::write(unsigned long, unsigned long, unsigned long, realm::_impl::OutputStream&) const in collection_notifier.o
      realm::BpTree<long long>::write(unsigned long, unsigned long, unsigned long, realm::_impl::OutputStream&) const in external_commit_helper.o
      realm::BpTree<long long>::write(unsigned long, unsigned long, unsigned long, realm::_impl::OutputStream&) const in list.o
      realm::BpTree<long long>::write(unsigned long, unsigned long, unsigned long, realm::_impl::OutputStream&) const in list_notifier.o
      realm::BpTree<long long>::write(unsigned long, unsigned long, unsigned long, realm::_impl::OutputStream&) const in object.o
      realm::BpTree<long long>::write(unsigned long, unsigned long, unsigned long, realm::_impl::OutputStream&) const in object_notifier.o
      realm::BpTree<long long>::write(unsigned long, unsigned long, unsigned long, realm::_impl::OutputStream&) const in object_store.o
````

**Comment by jpsim** [comment] 2017-03-22 19:56
I cloned your project @jcmendez and couldn't reproduce the compilation failures with CocoaPods 1.2.0 and Xcode 8.2. Perhaps update your version of CocoaPods to confirm that the issue is still occurring there?

Deleting the CocoaPods cache, clearing derived data, cleaning your project, running `pod deintegrate && pod install --verbose` are also good things to try.

Looks like your repro case and real project are different enough to not produce the same results. Could you update your repro project to trigger the same undefined symbols errors?

Also keep in mind that Swift frameworks (such as the `RealmSwift` pod) _require_ `use_frameworks!`, so removing that line from your `Podfile` isn't _supposed_ to work.

**Comment by jcmendez** [comment] 2017-03-24 16:00
@jpsim - thanks so much for looking into this.  I think the easiest is for me to give you access to the actual repo where the issue happens.  I'll follow up with a private invite

**Comment by jcmendez** [comment] 2017-03-24 16:15
I had tried clearing derived data, cleaning your project.  I'll try deintegrating and reintegrating as you suggest

**Comment by jcmendez** [comment] 2017-03-24 17:33
Hey @jpsim - running `pod deintegrate && pod install --verbose` did it.  Thanks!

**Comment by jpsim** [comment] 2017-03-24 17:56
I'm glad to hear it! Going to close this now.

**Closed by jpsim** 2017-03-24 17:56 UTC
Labels: S:P2 Backlog, T:Bug

**Comment by quangcanh2975** [comment] 2020-07-28 03:32
> Hey @jpsim - running `pod deintegrate && pod install --verbose` did it. Thanks!

Thank you so much!
