### ISSUE TITLE
OS X - Swift 2.2 - 0.103.0 - dyld: Library not loaded: @rpath/libswiftIOKit.dylib

### ISSUE THREAD

**Issue by dmendis** [realm/realm-cocoa#3619] opened 2016-05-19 12:20 UTC
I am trying to embed RealmSwift in a Swift Mac OS X project. I keep getting this error:

```
dyld: Library not loaded: @rpath/libswiftIOKit.dylib
  Referenced from: <USER>/Library/Developer/Xcode/DerivedData/CaptainsLog-exgpwisccgkpbohjyqmlskafhwyg/Build/Products/Debug/CaptainsLog.app/Contents/Frameworks/RealmSwift.framework/Versions/A/RealmSwift
  Reason: image not found
```

I have followed the steps outlined in the Realm documentation, just like this person: https://stackoverflow.com/questions/37193121/installing-latest-realm-0-102-0-fails-for-swift-in-xcode-environment

Interestingly, I merely added the libraries as Embedded Libraries. I am not even using the libs in my code... Should I be attaching some extra libs maybe?

Still can't seem to make it work after playing around with Framework Search Paths etc. 
I noticed there is no example with osx/swift right now. Is RealmSwift supported in a OS X project?

I did notice there was another issue that was closed long time ago about this. None of the solution prescribed there seems to work for me.

RealmSwift VERSION: 0.103.0

Can someone help?

**Comment by mrackwitz** [comment] 2016-05-19 15:11
Do you have multiple versions of Xcode or Swift installed?
Could you share a reproducible sample project with us? As you have seen from the StackOverflow question, where you commented on, we've been unable so far (/c @TimOliver  was involved) to reproduce this error.

**Comment by dmendis** [comment] 2016-05-19 18:52
Hi @mrackwitz, here's more info:

I get the problem if I create a default Swift OSX application from Xcode and add the frameworks in. I've created a sample project here: https://github.com/dmendis/realm-test

As mentioned earlier, the app builds fine. It just failed immediately at runtime.

I ran `xcrun swift -version` on the Terminal and go this output:
```
Apple Swift version 2.2 (swiftlang-703.0.18.1 clang-703.0.29)
Target: x86_64-apple-macosx10.9
```

Xcode Version is `7.3 (7D175)`
I don't have any other version of Xcode installed in the system.

If I drop the framework from `0.103.0-objc/osx/Realm.framework` there is no runtime issue. (Note ObjC)

I will try to find more clues to diagnose this. Hope this helps to kick start something. Can you confirm the project works for you?

**Comment by dmendis** [comment] 2016-05-20 20:48
I have tested the `realm-test` project in a different Mac and gotten the exact same error message.

**Comment by jpsim** [comment] 2016-05-20 21:25
@dmendis could you please try again with Xcode 7.3.1? I can't reproduce it with that version of Xcode...

**Comment by theisegeberg** [comment] 2016-05-24 12:56
I had this exact problem and it was fixed by updating from Xcode 7.3 to 7.3.1

**Comment by dmendis** [comment] 2016-05-24 23:20
I believe this is fixed on 7.3.1 too. Let's close this. Thank you for the prompt replies!

**Closed** 2016-05-24 23:22 UTC
Labels: build, T:Help

**Comment by indieshack** [comment] 2016-09-23 18:48
Have this issue with XCode 8 GM, iOS10

**Comment by jpsim** [comment] 2016-09-23 23:32
@indieshack please file a new issue taking care to fill out the new issue template so we can investigate.
