### ISSUE TITLE
Testing upgrade to 10.7.6 and seeing a huge performance hit on queries compared to 5.5.2

### ISSUE THREAD

**Issue by duncangroenewald** [realm/realm-cocoa#7261] opened 2021-05-19 06:12 UTC
## Goals
Upgrade App to 10.7.x and MongoDB Realm

## Expected Results
We completed the transition to the new SDK and expected the same or at least similar database performance with queries etc.

## Actual Results
We are seems very large decrease in performance - 10x or 100x slower when performing complex queries compared to what we were used to getting with v5.5.1/2

## Steps for others to Reproduce
- we don't have a test app to reproduce this yet

## Code Sample
We don't have a test app with queries to reproduce this yet

## Version of Realm and Tooling

Realm framework version: SPM v10.7.6

Xcode version: 12.5

iOS/OSX version: macOS 11.3

Dependency manager + version: N/A

**Comment by duncangroenewald** [comment] 2021-05-19 06:54
OK I just downloaded the v10.7.6 binaries and am using them instead of the SPM version and performance is back to more or less like it was with 5.5.2.

Is there some Xcode/compiler setting that might help ensure the SPM version runs faster - particularly when running in debug mode ?

**Comment by leemaguire** [comment] 2021-05-19 08:48
@duncangroenewald because the binaries are not built with any debug code you will see a performance increase. With SPM because everything is built from source the compiler will inject any debug code it deems necessary and this is the cause of your slowdown. I don't believe there is any workaround to have your App's target in debug mode while having the SPM target in release.

**Comment by bmunkholm** [comment] 2021-05-19 09:11
@leemaguire do you know if we use debug versions of core in those debug builds? Because those are very slow.

**Comment by duncangroenewald** [comment] 2021-05-19 09:15
I guess I'll stick with the binaries then.

**Comment by leemaguire** [comment] 2021-05-19 09:38
@bmunkholm Core will be built from source with SPM so it will be a debug build.

**Comment by bmunkholm** [comment] 2021-05-19 10:51
Not knowing what flags are used for Core there, we could perhaps consider adjusting them. Core (at least used to) be built with abundant checking and 4-leaf tree instead of 1000. That's useful for testing, but not for any users using this.

**Comment by duncangroenewald** [comment] 2021-05-19 10:54
Well let me know if you fix that and I'll try the SPM again.

**Comment by tgoyne** [comment] 2021-05-19 15:38
We aren't doing anything particularly slow in the debug builds for SPM. It's just the lack of compiler optimizations being enabled and that's not something we can adjust.

**Comment by leemaguire** [comment] 2021-06-21 08:39
Closing as the answer Thomas provided explains the issue.

**Closed** 2021-06-21 08:39 UTC
Labels: O-Community
