### ISSUE TITLE
Cocoapods Swift 2.0 Xcode 7 Yosemite Cannot Find RealmSwift Framework File

### ISSUE THREAD

**Issue by mgreenw** [realm/realm-cocoa#2606] opened 2015-09-30 05:02 UTC
I just created a new project and used cocoa pods to add RealmSwift into the project. I am getting this error when building the project after adding Realm: 

> Error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool:  can't open file: /Users/username/Library/Developer/Xcode/DerivedData/Appnameenebvtvzasbomufbjybndavoepfh/Build/Products/Debug-iphoneos/Appname.app/Frameworks/RealmSwift (No such file or directory)

Any suggestions? Thanks!

**Comment by jpsim** [comment] 2015-09-30 16:30
Duplicate of #2607.

**Closed by jpsim** 2015-09-30 16:30 UTC
