### ISSUE TITLE
build error: Ns_error_domain attribute only valid on enum/struct/union/class

### ISSUE THREAD

**Issue by yijiasu** [realm/realm-cocoa#4164] opened 2016-09-29 15:17 UTC
Realm version: 2.0.0

Xcode version: 8.0

iOS/OSX version: Deploy Target at iOS 8

I installed realm with Static Framework to my project. When I try to build the entire project, i've got these compile-time errors:

`RLMConstants.h:100:1: Ns_error_domain attribute only valid on enum/struct/union/class
RLMSyncUtil.h:30:1: Ns_error_domain attribute only valid on enum/struct/union/class`
I tried using Cocoapods, but these error still occurs.

Is there anything I mis-configured for the Xcode?

Thanks!

**Comment by bdash** [comment] 2016-09-30 15:25
Can you please share the exact version of Xcode that you're using? You can find it in the About Xcode window (Xcode -> About Xcode). Mine is Version 8.0 (8A218a), for instance.

**Comment by yijiasu** [comment] 2016-09-30 17:18
Version 8.0 (8A218a). The same as yours :)

**Comment by bdash** [comment] 2016-09-30 17:25
Hmm. I think you'll need to share more information about what you're doing when you see the error.

Do you see the error if you do the following:

1. `git clone https://github.com/realm/realm-cocoa.git`
2. `sh build.sh ios-static`

Or does it only appear when compiling your project when it brings in a Realm header file?

**Comment by ch4ot1c** [comment] 2016-09-30 22:38
Present for me as well, with a Cocoapods installation, on current Master branch (2.0.1), on latest XCode 8. I have the same error, line 100 of RLMConstants.h and line 30 of RLMSyncUtil.h

**Comment by bdash** [comment] 2016-09-30 22:39
Are you seeing the error when building Realm, or when building something that uses Realm?

**Comment by ch4ot1c** [comment] 2016-09-30 22:41
Building an .xcworkspace with Realm as a Cocoapods dependency. 'Building _appname_: Realm' appears and seems to happen successfully in the XCode status bar ; the compiler error shows at the very end of the build process

**Comment by bdash** [comment] 2016-09-30 22:44
Can you please share a copy of the full build log that shows the failure? It's possible there are particular compiler flags or similar that are triggering this issue as we're not able to reproduce this in any of our demo projects. If you'd rather not share the build log publicly, please feel free to email it to help@realm.io.

**Comment by ch4ot1c** [comment] 2016-09-30 22:58
Sent

**Comment by bdash** [comment] 2016-09-30 23:13
Thanks. Which version of Realm were you previously using that was building successfully?

**Comment by ch4ot1c** [comment] 2016-09-30 23:32
Never seen the error before 2.0.0, appears in both 2.0.0 and 2.0.1

**Comment by bdash** [comment] 2016-09-30 23:33
Were you on v1.1.0 prior to attempting to update to v2.0.0?

**Comment by ch4ot1c** [comment] 2016-09-30 23:40
Yes, but we are still amidst the Swift3 conversion process, so I'm not certain and don't want to give you any false info =p. bacfaa4 is the last RLM commit ref in Podfile on our pre-Swift3 branch.

**Comment by ch4ot1c** [comment] 2016-09-30 23:41
That being said, the error only started appearing today upon moving to 2.0.0, and moments later 2.0.1

**Comment by bdash** [comment] 2016-09-30 23:50
I've managed to reproduce this. It appears to be specific to building Objective-C++ files with the C++98 language setting, as CoreFoundation defines `CF_ENUM` differently for older C++ versions.

**Comment by ch4ot1c** [comment] 2016-10-01 00:03
Fantastic - For now I'll adjust that in my project. Thanks a million, I'll keep an eye on this Issue as well

**Closed** 2016-10-01 00:46 UTC
Labels: build, S:P1 Backlog, T:Bug
