### ISSUE TITLE
CLANG_CXX_LANGUAGE_STANDARD merge problem with Instabug

### ISSUE THREAD

**Issue by mladjan** [realm/realm-cocoa#2663] opened 2015-10-13 11:42 UTC
When I want to install Instabug and Realm in the same project, I'm getting the warning:
[!] Can't merge user_target_xcconfig for pod targets: ["Instabug", "Realm", "Headers"]. Singular build setting CLANG_CXX_LANGUAGE_STANDARD has different values.

**Comment by mrackwitz** [comment] 2015-10-13 13:35
This is a duplicate of #2053. The setting is only required in `pod_target_xcconfig`. We hold back from updating the podspec in the recent releases, because it requires an update to CocoaPods 0.38.2, which introduced support for dedicated attributes. Anyhow I pushed the branch `mr-0.95.3-podspec`, which you can specify from your Podfile to workaround the issue for now.

**Closed by mrackwitz** 2015-10-13 13:35 UTC
Labels: Help
