### ISSUE TITLE
RLMObject.mm No known class method for selector 'className'

### ISSUE THREAD

**Issue by thanyalukj** [realm/realm-cocoa#2156] opened 2015-07-03 21:56 UTC
hello there,

I'm new to Realm and try to integrate realm swift with swift-2. I created the new project and use cocoapod to integrate to the project. I hit convert to swift2 and after that this is the error I got.

```objc
+ (NSString *)className {
    return [super className]; <- No known class method for selector 'className'
}
```

Thank you very much.

**Comment by jpsim** [comment] 2015-07-03 21:57
Hi @thanyalukj, could you try again? I just rebased that branch this morning to address that issue :smile:.

**Comment by thanyalukj** [comment] 2015-07-03 21:59
Ok. will do now.

**Comment by thanyalukj** [comment] 2015-07-03 22:14
I've tried by removing the Pods directory and run pod install. Unfortunately, I still have the same error.

**Comment by thanyalukj** [comment] 2015-07-03 22:16
I dont know much about Realm but this is how I get rid of warning.
@interface RLMObjectBase : NSObject

@property (nonatomic, readonly, getter = isInvalidated) BOOL invalidated;
@property (nonatomic, readonly) NSString *className;

- (instancetype)init;
+ (NSString *)className; <--- I added this line

@end

**Comment by jpsim** [comment] 2015-07-03 22:33
That's essentially undoing my commit 9d229652c7c38f846916d0a1c2ee1b32731bcf33 from this morning that "fixed" things. I can't claim that it makes sense, but it does fix a compilation warning (`ambiguous use of className`) in Realm Swift.

I feel like this is a regression in Xcode 7 Beta 2, and will file a radar if it's not fixed by Xcode 7 Beta 3.

All of our tests pass with the current state of `swift-2.0`, but I have yet to try using CocoaPods, so that may have something to do with it.

**Comment by segiddins** [comment] 2015-07-03 22:48
We've confirmed this is an iOS/OS X discrepancy, since Cocoa already has a `className` on `NSObject` and we've got a workaround coming.

**Comment by jpsim** [comment] 2015-07-03 22:52
Thanks for reporting this, @thanyalukj. I just pushed a workaround to the `swift-2.0` branch (d404ffd2c9abf5e2cbc3b0789052af803deda5bc), so if you pull from CocoaPods again, this should be resolved. I'll be filing a radar about this shortly.

**Comment by thanyalukj** [comment] 2015-07-03 23:01
Hooray! That's fixed the problem. Thanks very much @jpsim and @segiddins for you response and also a quick fix :)

**Comment by jpsim** [comment] 2015-07-03 23:10
:satellite: radar'd: [rdar://21672269](http://openradar.me/21672269)

**Closed by jpsim** 2015-07-03 23:10 UTC

**Comment by segiddins** [comment] 2015-07-03 23:22
@jpsim should probably update the radar and specify it only occurs when importing Cocoa.

**Comment by jpsim** [comment] 2015-07-03 23:22
ah, right I forgot to specify.

**Comment by jpsim** [comment] 2015-07-03 23:23
I attached an OS X project to Apple's radar though, so it should be fine.
