### ISSUE TITLE
After updating database, Results sorted incorrectly if sort is applied before filter

### ISSUE THREAD

**Issue by ahayman** [realm/realm-cocoa#2166] opened 2015-07-06 19:22 UTC
Running: RealmSwift v.93.2

I discovered this after running some Unit Tests on my own code. What I did was grab a Results object by applying a sort and then applying a filter:

    let models = realm.objects(ModelA)
      .sorted("doubleField", ascending: true)
      .filter("%K CONTAINS %@", "stringField", par)

Initially, there are no objects in the database, so `models` has nothing in it.  Once I write objects to the database, the objects are filtered correctly but they are not sorted correctly.

If I change the order of chain it works properly:

    let models = realm.objects(ModelA)
      .filter("%K CONTAINS %@", "stringField", par)
      .sorted("doubleField", ascending: true)

Note: This *only* happens after I update the database.  If I first write all the objects to the database, the Results object will be correctly sorted/filtered in both cases (no matter how I order the chain).  But once I update the database the sort is incorrect (if it's before the filter in the chain).

Full Disclosure:  Here's my model (for testing):

```
public class ModelA: Object {
  public dynamic var id: String = ""
  public dynamic var stringField: String? = ""
  public dynamic var dateField: NSDate? = NSDate()
  public dynamic var dataField: NSData? = NSData()
  public dynamic var int64Field: Int64 = 0
  public dynamic var boolField: Bool = false
  public dynamic var doubleField: Double = 0
  public dynamic var floatField: Float = 0
  
  public override static func primaryKey() -> String? {
    return "id"
  }
}
```

I'm also generating my ModelA objects using randomized values and write them:
```
  public func newModelA() -> ModelA {
    let model = ModelA()
    model.id = newID()
    model.stringField = randomStringWithLength(1) as String
    model.dateField = NSDate()
    model.int64Field = Int64(arc4random())
    model.boolField = Bool(Int(arc4random_uniform(1)))
    model.doubleField = Double(arc4random()) / Double(arc4random())
    model.floatField = Float(arc4random()) / Float(arc4random())
    return model
  }

  public func generateModelAs(no: Int) -> [ModelA] {
    var models:[ModelA] = []
    for i in 0..<no {
      models.append(newModelA())
    }
    return models;
  }

  public func writeModels(models: [ModelA]) {
    realm.beginWrite()
    self.realm.add(models, update: true)
    realm.commitWrite()
  }

```
I retrieve the Results like so:
```
  public func getAllModelsFirstSortedThenFilteredOnDouble(par:String) -> Results<ModelA> {
    let models = realm.objects(ModelA)
      .sorted("doubleField", ascending: true)
      .filter("%K CONTAINS %@", "stringField", par)
    
    return models
  }
```
I run the following test:
```
  func testSortedThenFiltered() {
    let models = persistence!.generateModelAs(1000)
    let queried = persistence!.getAllModelsFirstSortedThenFilteredOnDouble("a")
    
    self.persistence!.writeModels(models)

    var last: ModelA? = nil
    for object in queried {
      if let lastObject = last {
        XCTAssert(object.doubleField >= lastObject.doubleField, "Object Double '\(object.doubleField)' !>= Last '\(lastObject.doubleField)'")
      }
      XCTAssertEqual(object.stringField!, "a", "Object should have string field == a")
      last = object
    }
  }
```

Note: `persistence` is where the models are generated and retrieved.

**Comment by tgoyne** [comment] 2015-07-06 20:12
This appears to have been fixed by https://github.com/realm/realm-cocoa/pull/2125 (which also fixed sort-then-filter being slower than filter-then-sort), as I can reproduce it in 0.93.2 but not in master. Looks like there aren't any tests covering it though, so I'll fix that.

**Comment by ahayman** [comment] 2015-07-06 20:27
Thanks!  That's great news (about both, actually, as I also noticed issue #2125 occurring in my performance testing).  

Any idea when this will make it into the next version?

**Comment by tgoyne** [comment] 2015-07-06 20:34
We will hopefully have a new release of some sort out this week.

**Comment by ahayman** [comment] 2015-07-06 20:34
Excellent.  That's well before I'm placing this into our production app.  Thanks!

**Closed** 2015-07-06 20:54 UTC
Labels: pr
