### ISSUE TITLE
Unrecognized selector sent to RLMAccessor class when registering classes in a custom schema

### ISSUE THREAD

**Issue by kexoth** [realm/realm-cocoa#2494] opened 2015-09-08 03:04 UTC
Hey guys,

Out of the sudden I have this weird exception:
     *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[RLMStandalone_MyClass requiredProperties]: unrecognized selector sent to class 0x7fa62b56e190'

I simply don't get how this issue appeared, but the bad thing is that it crashes on main & I have no stack-trace.

After a lot of debugging I found what caused this issue, I was creating my custom Realm.Configuration & this is how it looked like:
      
    let config = Realm.Configuration(path: path, objectTypes: [MyClass.self])

This issue appears after defining my object types in the realm, if I remove it, everything works.
What is the purpose of defining the objectTypes & what is the correct way to be used?

Thanks!

**Comment by jpsim** [comment] 2015-09-11 16:42
Hi @kexoth, the `objectTypes` property of `Realm.Configuration` is meant to restrict which model classes should be included in that Realm's "schema". This is only really useful when using multiple Realms, and you have certain models that should only be in a subset of the Realms.

If `MyClass` is a Realm model (inheriting from `RealmSwift.Object`), then the configuration you've mentioned would configure a Realm that can only store and access objects of the class `MyClass`.

You can refer to our [API reference documentation](https://realm.io/docs/swift/latest/api/Extensions/Realm/Configuration.html#/s:vVC10RealmSwift5Realm13Configuration11objectTypesGSqGSaMCS_6Object__) or the [Class Subsets](https://realm.io/docs/swift/latest/#class-subsets) section of our documentation guide for more information.

As for the `unrecognized selector` exception you're getting, that looks like it could be a bug to me. Could you please share the class definition of `MyClass`? If `MyClass` doesn't subclass `RealmSwift.Object`, then it's probably a matter of us adding some validation and throwing a more descriptive error in there.

Thanks!

**Comment by TimOliver** [comment] 2015-09-24 05:28
@kexoth Just following this up! Aleksandar, could you please provide us with the model definition of `MyClass` so we can check to see what is causing that issue? :)

**Comment by kexoth** [comment] 2015-09-25 15:12
Sorry for the delay, but I needed some time to migrate the project to Swift 2.0.

I've created a [sample project](/pristap/realm-schema-issue) out of my own project replicating the issue .

The project has the 2 models that I use `KXEntry` & `KXEntryStats` & the manager for the Realms `KXRealm`. The issue is in `KXRealm`, i.e. if I add `objectTypes:` in the initializations it fails.

What are the pre-requirements & benefits of using `objectTypes` when initializing a Realm?

Check it out & thanks for the feedback @jpsim & @TimOliver :+1:

**Comment by jpsim** [comment] 2015-09-25 16:22
Thanks a lot for sharing that sample project, @kexoth. It really helps speed up our investigation and fixing a bug when we can see exactly what's no working.

In your case, you seem to be using `Realm.Configuration.objectTypes` correctly, but we had a bug in our schema building code that I've now issued a fix for in #2583.

**Comment by jpsim** [comment] 2015-09-25 16:53
Looks like this is a duplicate of #2534, for which we already have a fix in review (#2537).

**Closed by jpsim** 2015-09-25 16:54 UTC
Labels: bug, P1, Review

**Comment by kexoth** [comment] 2015-09-25 17:48
@jpsim just one last question, out of curiosity, does declaring the `objectTypes` on initialization has any performance benefits or it's used only for clearance, to make the usage of the given `Realm` to be more explicit?

Thanks!

**Comment by jpsim** [comment] 2015-09-25 18:16
Only including a subset of your schema per-realm likely won't have any significant performance implications, but rather will avoid creating unused tables and allow you to perform migrations only on the Realms containing the changed data.

**Comment by kexoth** [comment] 2015-09-25 18:20
Thanks for the intel :+1:
