### ISSUE TITLE
Infinite recursion in Table::register_row_accessor()

### ISSUE THREAD

**Issue by yushuyi** [realm/realm-cocoa#3425] opened 2016-04-12 13:58 UTC
http://crashes.to/s/e96982e7b42

**Comment by mrackwitz** [comment] 2016-04-12 14:07
With which version of Realm did that happen?

**Comment by yushuyi** [comment] 2016-04-12 14:13
@mrackwitz 0.98.5

**Comment by jpsim** [comment] 2016-04-12 20:41
@yushuyi could you please share more information about how this occurred? Can you reproduce this crash yourself? If so, could you share steps for us to reproduce this?

**Comment by yushuyi** [comment] 2016-04-13 01:56
我执行了一个删除某个Object的操作  我无法重现, 只出现了一次

**Comment by jpsim** [comment] 2016-04-13 23:23
Unfortunately @yushuyi, we can't make much sense of that stack trace. We'll need a reproduction sample to make progress on this.

**Comment by lhyhsx** [comment] 2016-04-14 01:49
@jpsim my english is poor#_#! i meet this bug, the below code  can reproduce this bug

```Objective-c
- (id)init {
    if (self = [super init]) {
        _dbThread = [[NSThread alloc] initWithTarget:self selector:@selector(threadEntryPoint) object:nil];
        _dbThread.name = NSStringFromClass(self.class);
        [_dbThread start];
    }
    return self;
}

- (void)threadEntryPoint {
    @autoreleasepool {
        NSRunLoop *runloop = [NSRunLoop currentRunLoop];
        [runloop addPort:[NSPort port] forMode:NSDefaultRunLoopMode]; 
        [runloop run];
    }
}

- (void)deleteAction {
    [self performSelector:@selector(_deleteAction) onThread:_dbThread withObject:nil waitUntilDone:NO];
}

- (void)_deleteAction {
    RLMRealm *realm = [RLMRealm defaultRealm];
    [realm beginWriteTransaction];
    [realm deleteObject:SomeRLMObject]; // Block at this, never return!
    [realm commitWriteTransaction];
}
```

**Comment by jpsim** [comment] 2016-04-14 04:40
@lhyhsx sorry I can't reproduce the problem with your code sample. Here's a complete iOS app that attempts to incorporate your code to trigger the problem:

```objc
#import <Realm/Realm.h>

@interface Person : RLMObject
@property NSString *name;
@end

@implementation Person
@end

@interface ThreadActor : NSObject

@property (nonatomic, strong) NSThread *dbThread;

@end

@implementation ThreadActor {
    Person *SomeRLMObject;
}

- (id)init {
    if (self = [super init]) {
        _dbThread = [[NSThread alloc] initWithTarget:self selector:@selector(threadEntryPoint:) object:nil];
        _dbThread.name = NSStringFromClass(self.class);
        [_dbThread start];
    }
    return self;
}

- (void)threadEntryPoint:(id)sender {
    @autoreleasepool {
        SomeRLMObject = [[Person allObjects] firstObject];
        NSRunLoop *runloop = [NSRunLoop currentRunLoop];
        [runloop addPort:[NSPort port] forMode:NSDefaultRunLoopMode];
        [runloop run];
    }
}

- (void)deleteAction {
    [self performSelector:@selector(_deleteAction) onThread:_dbThread withObject:nil waitUntilDone:NO];
}

- (void)_deleteAction {
    NSLog(@"_deleteAction started. number of persons: %lu", (unsigned long)[[Person allObjects] count]);
    RLMRealm *realm = [RLMRealm defaultRealm];
    [realm beginWriteTransaction];
    [realm deleteObject:SomeRLMObject];
    [realm commitWriteTransaction];
    NSLog(@"_deleteAction completed. number of persons: %lu", (unsigned long)[[Person allObjects] count]);
}

@end

@implementation AppDelegate {
    ThreadActor *threadActor;
}

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
    [[RLMRealm defaultRealm] transactionWithBlock:^{
        [Person createInDefaultRealmWithValue:@[@"John"]];
    }];

    threadActor = [[ThreadActor alloc] init];
    [threadActor deleteAction];

    return YES;
}

@end
```

But this succeeds, printing:

```
_deleteAction started. number of persons: 1
_deleteAction completed. number of persons: 0
```

**Comment by Kirow** [comment] 2016-04-14 13:20
I got similar crashes recently (I think it appeared first time on version 0.98.0). But it appeared because of retain cycles I've made.

I did not investigate this problem deeply, I just fix retain cycles. But here is approximate steps:
1) Write bad code with retain cycle
2) Open realm file
3) addNotification on RLMResults (which will never be stopped/dealloced because of **1** )
4) Open realm file again, or maybe update some data.

If I see it again, I will try to share

**Comment by jpsim** [comment] 2016-10-19 18:15
Has anyone here seen this in recent Realm versions? Like 2.0.x?

**Comment by Kirow** [comment] 2016-10-20 13:58
I don't think that I saw this issue after 1.x was released

**Comment by jpsim** [comment] 2016-10-20 16:25
Thanks for sharing @Kirow. I'm closing this under the presumption that this issue no longer manifests itself in recent versions of Realm.

**Closed by jpsim** 2016-10-20 16:25 UTC
Labels: Blocked On Core, Reproduction Required, S:On Hold, T:Bug-Crash
