### ISSUE TITLE
realm::SharedGroup::BadVersion crash

### ISSUE THREAD

**Issue by hermanolsson** [realm/realm-cocoa#3427] opened 2016-04-12 21:00 UTC
We're seeing a production crash:

```
Fatal Exception: realm::SharedGroup::BadVersion: std::exception
```

which I can't reproduce, and I can't find any useful info regarding this, so I'm turning to you guys. We've seen this issue for the past few weeks.

I'm sorry that I don't have any more information.

Realm version: 0.98.6

Xcode version: 7.3

iOS/OSX version: iOS 9.3.1

Dependency manager + version: CocoaPods

**Comment by tbaranes** [comment] 2016-04-12 21:11
+1, we started to get that issue with the last version. Really not a lot Graham's, but some anyway... Any ideas why / how is it happening.

**Comment by jpsim** [comment] 2016-04-12 21:12
Sorry to see you're affected by this crash @hermanolsson! Could you share the complete backtrace for this crash? That could help us identify where this issue is happening.

Also, any insight into what your query looks like, or your model definitions, would help.

Given that this has to do with thread handover of results, it's quite possible that this is caused by a race condition between threads, which would also make it more difficult for you or us to reproduce the problem.

I just saw @tbaranes chime in, same goes to you, if you can share more about the issue, that's the only way we'll be able to make progress on this.

**Comment by hermanolsson** [comment] 2016-04-13 05:24
I'll do my best to give you as much as possible. We have a bit messy implementation with multiple realm files, and this particular crash happens when accessing the non default realm the first time. Not sure if that helps or not. I'll be back later today. Hopefully with some new info.

**Comment by tbaranes** [comment] 2016-04-13 06:15
On my side, I don't have that much information, but here the crash logs from crashlytics:

```
Fatal Exception: realm::SharedGroup::BadVersion: std::exception

Thread : Crashed: com.twitter.crashlytics.ios.exception
0  KaraFun                        0x1005002d8 CLSProcessRecordAllThreads + 98384
1  KaraFun                        0x1005002d8 CLSProcessRecordAllThreads + 98384
2  KaraFun                        0x1005006f8 CLSProcessRecordAllThreads + 99440
3  KaraFun                        0x1004f13bc CLSHandler + 37172
4  KaraFun                        0x1004fea00 __CLSExceptionRecord_block_invoke + 92024
5  libdispatch.dylib              0x180cf947c _dispatch_client_callout + 16
6  libdispatch.dylib              0x180d04728 _dispatch_barrier_sync_f_invoke + 100
7  KaraFun                        0x1004fe4ac CLSExceptionRecord + 90660
8  KaraFun                        0x1004fe030 CLSTerminateHandler() + 89512
9  libc++abi.dylib                0x180906f44 std::__terminate(void (*)()) + 16
10 libc++abi.dylib                0x180906b10 __cxa_rethrow + 144
11 libobjc.A.dylib                0x180914120 objc_exception_rethrow + 44
12 CoreFoundation                 0x18118cdb8 CFRunLoopRunSpecific + 552
13 GraphicsServices               0x182a74088 GSEventRunModal + 180
14 UIKit                          0x186461f70 UIApplicationMain + 204
15 KaraFun                        0x1001397d8 main (main.m:14)
16 libdispatch.dylib              0x180d2a8b8 (Missing)

Thread : RLMRealm notification listener
0  libsystem_kernel.dylib         0x180e31528 kevent + 8
1  KaraFun                        0x1002d9900 realm::_impl::ExternalCommitHelper::listen() (external_commit_helper.cpp:199)
2  KaraFun                        0x1002d9afc std::__1::__async_func<realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0>::operator()() (future:2335)
3  KaraFun                        0x1002d9a84 std::__1::__async_assoc_state<void, std::__1::__async_func<realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0> >::__execute() (future:1029)
4  KaraFun                        0x1002d9c4c std::__1::__thread_proxy<std::__1::tuple<void (std::__1::__async_assoc_state<void, std::__1::__async_func<realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0> >::*)(), std::__1::__async_assoc_state<void, std::__1::__async_func<realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0> >*> >(void*, void*) (memory:2459)
5  libsystem_pthread.dylib        0x180f13b28 _pthread_body + 156
6  libsystem_pthread.dylib        0x180f13a8c _pthread_body + 154
7  libsystem_pthread.dylib        0x180f11028 thread_start + 4
```

That version is using Realm 0.95.3. 
What kind of information could help?

**Comment by hermanolsson** [comment] 2016-04-13 06:29
It looks a little bit different for us, but I guess the difference is related to swift + realm version.

```
Fatal Exception: realm::SharedGroup::BadVersion: std::exception

Thread : Crashed: com.twitter.crashlytics.ios.exception
0  Narrative                      0x1004fb278 CLSProcessRecordAllThreads + 102716
1  Narrative                      0x1004fb278 CLSProcessRecordAllThreads + 102716
2  Narrative                      0x1004fb698 CLSProcessRecordAllThreads + 103772
3  Narrative                      0x1004ec54c CLSHandler + 42000
4  Narrative                      0x1004f9b9c __CLSExceptionRecord_block_invoke + 96864
5  libdispatch.dylib              0x182e5147c _dispatch_client_callout + 16
6  libdispatch.dylib              0x182e5c728 _dispatch_barrier_sync_f_invoke + 100
7  Narrative                      0x1004f9648 CLSExceptionRecord + 95500
8  Narrative                      0x1004f91cc CLSTerminateHandler() + 94352
9  libc++abi.dylib                0x182a5ef44 std::__terminate(void (*)()) + 16
10 libc++abi.dylib                0x182a5eb10 __cxa_rethrow + 144
11 libobjc.A.dylib                0x182a6c120 objc_exception_rethrow + 44
12 CoreFoundation                 0x1832e4db8 CFRunLoopRunSpecific + 552
13 GraphicsServices               0x184bcc088 GSEventRunModal + 180
14 UIKit                          0x1885b9f70 UIApplicationMain + 204
15 Narrative                      0x100186e6c main (AppDelegate.swift:13)
16 libdispatch.dylib              0x182e828b8 (Missing)

Thread : RLMRealm notification listener
0  libsystem_kernel.dylib         0x182f89528 kevent + 8
1  Realm                          0x100bf1fa8 realm::_impl::ExternalCommitHelper::listen() (external_commit_helper.cpp:199)
2  Realm                          0x100bf21a4 std::__1::__async_func<realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0>::operator()() (future:2331)
3  Realm                          0x100bf212c std::__1::__async_assoc_state<void, std::__1::__async_func<realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0> >::__execute() (future:1025)
4  Realm                          0x100bf22f4 std::__1::__thread_proxy<std::__1::tuple<void (std::__1::__async_assoc_state<void, std::__1::__async_func<realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0> >::*)(), std::__1::__async_assoc_state<void, std::__1::__async_func<realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0> >*> >(void*, void*) (memory:2516)
5  libsystem_pthread.dylib        0x18306bb28 _pthread_body + 156
6  libsystem_pthread.dylib        0x18306ba8c _pthread_body + 154
7  libsystem_pthread.dylib        0x183069028 thread_start + 4
```

**Comment by chml** [comment] 2016-04-21 12:45
I got the same exception;
I am using v0.98.8 in ObjC
```
* thread #1: tid = 0xec3a80, 0x0000000107c29c6b libc++abi.dylib`__cxa_throw, queue = 'com.apple.main-thread', stop reason = breakpoint 1.2
    frame #0: 0x0000000107c29c6b libc++abi.dylib`__cxa_throw
  * frame #1: 0x0000000102af341c houseqm`void realm::SharedGroup::advance_read<(anonymous namespace)::TransactLogValidator>(this=0x00007fe0b9852e00, observer=0x00007fff5d5dfde8, version_id=(version = 95, index = 25))::TransactLogValidator*, realm::SharedGroup::VersionID) + 220 at group_shared.hpp:924
    frame #2: 0x0000000102af332b houseqm`void realm::_impl::SharedGroupFriend::advance_read<(anonymous namespace)::TransactLogValidator>(sg=0x00007fe0b9852e00, obs=0x00007fff5d5dfde8, ver=(version = 95, index = 25))::TransactLogValidator*, realm::SharedGroup::VersionID) + 59 at group_shared.hpp:1097
    frame #3: 0x0000000102af32db houseqm`void realm::LangBindHelper::advance_read<(anonymous namespace)::TransactLogValidator>(sg=0x00007fe0b9852e00, observer=0x00007fff5d5dfde8, version=(version = 95, index = 25))::TransactLogValidator&&, realm::SharedGroup::VersionID) + 59 at lang_bind_helper.hpp:352
    frame #4: 0x0000000102af3205 houseqm`auto realm::_impl::transaction::advance(this=0x00007fff5d5dfdd8, args=0x00007fff5d5dfde8)::$_0::operator()<(anonymous namespace)::TransactLogValidator&>((anonymous namespace)::TransactLogValidator&&&) const + 69 at transact_log_handler.cpp:438
    frame #5: 0x0000000102af2e42 houseqm`(anonymous namespace)::TransactLogObserver::TransactLogObserver<realm::_impl::transaction::advance(this=0x00007fff5d5dfde8, context=0x00007fe0bb0eafe0, sg=0x00007fe0b9852e00, func=0x00007fff5d5dfdd8, validate_schema_changes=true)::$_0>(realm::BindingContext*, realm::SharedGroup&, realm::_impl::transaction::advance(realm::SharedGroup&, realm::BindingContext*, realm::SharedGroup::VersionID)::$_0&&, bool) + 1106 at transact_log_handler.cpp:222
    frame #6: 0x0000000102af25de houseqm`(anonymous namespace)::TransactLogObserver::TransactLogObserver<realm::_impl::transaction::advance(this=0x00007fff5d5dfde8, context=0x00007fe0bb0eafe0, sg=0x00007fe0b9852e00, func=0x00007fff5d5dfdd8, validate_schema_changes=true)::$_0>(realm::BindingContext*, realm::SharedGroup&, realm::_impl::transaction::advance(realm::SharedGroup&, realm::BindingContext*, realm::SharedGroup::VersionID)::$_0&&, bool) + 62 at transact_log_handler.cpp:204
    frame #7: 0x0000000102af258a houseqm`realm::_impl::transaction::advance(sg=0x00007fe0b9852e00, context=0x00007fe0bb0eafe0, version=(version = 95, index = 25)) + 90 at transact_log_handler.cpp:437
    frame #8: 0x0000000102944816 houseqm`realm::_impl::RealmCoordinator::advance_to_ready(this=0x00007fe0bb039dd0, realm=0x00007fe0b8c7d7a0) + 966 at realm_coordinator.cpp:438
    frame #9: 0x0000000102aec639 houseqm`realm::Realm::notify(this=0x00007fe0b8c7d7a0) + 329 at shared_realm.cpp:381
    frame #10: 0x000000010291873f houseqm`realm::_impl::CachedRealm::CachedRealm(this=0x00000001029186d0, info=0x00007fe0b8ddf580)::$_0::operator()(void*) const + 79 at cached_realm.cpp:38
    frame #11: 0x00000001029186e8 houseqm`realm::_impl::CachedRealm::CachedRealm(info=0x00007fe0b8ddf580)::$_0::__invoke(void*) + 24 at cached_realm.cpp:36
    frame #12: 0x0000000103b5a301 CoreFoundation`__CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
    frame #13: 0x0000000103b5022c CoreFoundation`__CFRunLoopDoSources0 + 556
    frame #14: 0x0000000103b4f6e3 CoreFoundation`__CFRunLoopRun + 867
    frame #15: 0x0000000103b4f0f8 CoreFoundation`CFRunLoopRunSpecific + 488
    frame #16: 0x0000000108f4bad2 GraphicsServices`GSEventRunModal + 161
    frame #17: 0x000000010563df09 UIKit`UIApplicationMain + 171
    frame #18: 0x000000010273425f houseqm`main(argc=7, argv=0x00007fff5d5e1588) + 111 at main.m:14
    frame #19: 0x0000000107d6992d libdyld.dylib`start + 1
    frame #20: 0x0000000107d6992d libdyld.dylib`start + 1
```

**Comment by jpsim** [comment] 2016-04-21 15:34
Hi all, this appears to be the same issue as originally reported in #3412, so I'll be closing this one as a duplicate just to keep the conversation in one place. Please report any additional information in that issue, and bonus points if you can help us reproduce it!

**Closed by jpsim** 2016-04-21 15:34 UTC
Labels: Reproduction Required, S:P2 Backlog, T:Bug-Crash
