### ISSUE TITLE
addOrUpdateObject: for arrays.

### ISSUE THREAD

**Issue by pjebs** [realm/realm-cocoa#3296] opened 2016-03-05 02:37 UTC
I have a  field in my model that stores a collection of other models.
I would like to know how to update objects inside a collection. I get this error:
`Can't set primary key property 'id' to existing value '9'.`

                RealmEvent *re = [[RealmEvent alloc] init];
                re.date = event.timeStart;
                re.id = event.id;

                [[RLMRealm defaultRealm] beginWriteTransaction];
                    [p.events addOrUpdateObject:re];  //What I want now
                    // [p.events addObject:re];  //OriginalCode
                [[RLMRealm defaultRealm] commitWriteTransaction];

**Comment by pjebs** [comment] 2016-03-05 02:40
`addOrUpdateObject` doesn't work for RLMArray

**Comment by jrpinteno** [comment] 2016-03-05 10:57
I can confirm same situation.

**Comment by mrackwitz** [comment] 2016-03-05 16:56
Are you perhaps rather looking for a more expressive property type `RLMSet` instead `RLMArray`, which doesn't allow to contain duplicates at all, independent from how you modify it? That's something we have on our backlog with #1501.

**Comment by mrackwitz** [comment] 2016-04-05 14:04
@jpsim: I saw that you added the label `T:Enhancement` here. Do we want to add this? Not sure, if it's worth it in the long-term. I think it would be confusing to have a method like that once a type with proper set semantics exists instead.

**Comment by jpsim** [comment] 2016-04-05 22:56
I also don't think this is something we should add, but this is an enhancement request, so I labeled it as such pending a more comprehensive discussion considering whether or not this is desired functionality.

We're still waiting to hear back from @jrpinteno and @pjebs on this, until then I think it's appropriate to keep the conversation open.

**Comment by pjebs** [comment] 2016-04-05 23:23
There is nothing more I can say really. It would be a nice worthwhile feature if I could update or add (if non existent) a rlmobject into another rlmobject's field which takes an array (relationships)

Right now I have to manually check if the entry is there. If it is, query for it and update. If not, then add.

**Comment by jpsim** [comment] 2016-04-05 23:31
@pjebs that comment doesn't address @mrackwitz's question:

> Are you perhaps rather looking for a more expressive property type `RLMSet` instead `RLMArray`, which doesn't allow to contain duplicates at all, independent from how you modify it? That's something we have on our backlog with #1501.

**Comment by pjebs** [comment] 2016-04-06 00:29
To be honest, I just want to be able to do what I stated ;-)

I don't have the foresight into whether the RLMSet type would be overall or in the long-term more advantageous.

**Comment by jpsim** [comment] 2016-04-06 01:14
Ok, so just to be clear, what behavior are you thinking this method would have?

Would it be equivalent to this?

```objc
id dict = @{@"date": event.timeStart, @"id": event.id};
RealmEvent *re = [RealmEvent createOrUpdateInDefaultRealmWithValue:dict];
[p.events addObject:re];
```

or this?

```objc
id dict = @{@"date": event.timeStart, @"id": event.id};
RealmEvent *re = [RealmEvent createOrUpdateInDefaultRealmWithValue:dict];
if ([p.events indexOfObject:re] == NSNotFound) {
  [p.events addObject:re];
}
```

or something else?

If it's either of these, I'd be inclined to say that we shouldn't be adding methods to Realm that could already be done by composing two simple Realm APIs.

If it's something else, please clarify so we can better assess what you're after.

Thanks!

**Comment by pjebs** [comment] 2016-05-02 10:30
Would the code above have to be within a beginWriteTransaction?

**Comment by jpsim** [comment] 2016-05-02 15:43
@pjebs yes, writing to Realm objects must always be done from a write transaction.

**Comment by pjebs** [comment] 2016-05-02 23:34
Since Realm doesn't have unique keys, if `RealmEvent` doesn't have a primary key, how would `indexOfObject` work? Is that when the prospective RLMSet is required?

**Comment by jpsim** [comment] 2016-05-03 09:42
> Since Realm doesn't have unique keys, if `RealmEvent` doesn't have a primary key, how would `indexOfObject` work? Is that when the prospective RLMSet is required?

`RealmEvent` has a primary key, and therefore has unique values for that property across all its objects.

`createOrUpdate:` is not a valid operation for objects without primary keys.

However, `indexOfObject:` is valid *iff* you pass it a persisted Realm object because it will search for that exact Realm object, not just something with the same values. Think of this as pointer equality within Realm.

**Comment by mrackwitz** [comment] 2016-05-21 10:35
As it seemed from the further discussion like the requested semantics can be already achieved by composing two simple Realm APIs, which seem to be overall more expressive and avoid confusion about when such a method would be applicable, I'm closing this issue now.

**Closed by mrackwitz** 2016-05-21 10:35 UTC
Labels: S:Idea Backlog, T:Enhancement

**Comment by pjebs** [comment] 2016-10-12 04:07
Actually this solution is not quite right. Maybe you have a nice solution in latest version (I use v0.102.1 because computer not powerful enough to run compatible xcode).

`createOrUpdate` requires object to have primary key.
I'm trying to insert object into a model's relationship array ONLY if it doesn't already exist already. If it does exist, then don't add.

```
RealmEvent *re = [[RealmEvent alloc] init];
            re.date = event.timeStart;
            re.id = event.id;

            [[RLMRealm defaultRealm] beginWriteTransaction];
                [p.events addOrUpdateObject:re];  //What I want now
                // [p.events addObject:re];  //OriginalCode
            [[RLMRealm defaultRealm] commitWriteTransaction];
```

`re` doesn't have primary key. It should only be added to `p.events` iff there is no value already in `p.events` with same value(s).
