### ISSUE TITLE
Carthage pulls v0.0.24b when an invalid version is specified in the Cartfile

### ISSUE THREAD

**Issue by alec-c4** [realm/realm-cocoa#1949] opened 2015-05-16 14:11 UTC
I have following error on attempt to build realm via carthage

```
Project "TightDbObjcDyn.xcodeproj" has no shared schemes

If you believe this to be an error, please file an issue with the maintainers at https://github.com/realm/realm-cocoa/issues/new
```

How can i fix it?

**Comment by bdash** [comment] 2015-05-16 18:37
The reference to TightDbObjcDyn.xcodeproj indicates you're attempting to build a very old version of Realm. Would you mind sharing the Cartfile you're using?

**Comment by segiddins** [comment] 2015-05-16 18:43
I think I might've accidentally re-pushed the deleted tags :(

**Comment by segiddins** [comment] 2015-05-16 18:50
So sorry, should be fixed now!

**Comment by pietbrauer** [comment] 2015-05-21 11:39
I had the same issue. One can reproduce by using a tag that does not exist:

```bash
$ carthage update
*** Fetching realm-cocoa
*** Checking out realm-cocoa at "v0.0.24b"
*** xcodebuild output can be found in /var/folders/9v/9z2qkhhx57zbdn9876mq__497d7w_y/T/carthage-xcodebuild.QGEpwj.log
Project "TightDbExample.xcodeproj" has no shared schemes

If you believe this to be an error, please file an issue with the maintainers at https://github.com/realm/realm-cocoa/issues/new
$ cat Cartfile
github "realm/realm-cocoa" ~> 0.96.0
```

**Comment by segiddins** [comment] 2015-05-22 16:37
@pietbrauer can you check if this is now fixed?

**Comment by pietbrauer** [comment] 2015-05-26 06:26
Hey @segiddins I think it is a communication issue right now.
This problem only happens if you specify a version that does not exist, e.g. `0.96.0` then carthage tries to install `v0.0.24b`.

I will open an issue on their side as this is confusing and they should fail in another way.

**Comment by pietbrauer** [comment] 2015-05-26 06:34
@segiddins I tried with SSKeychain and Carthage fails gracefully with an error message:

```
$ carthage update
*** Fetching sskeychain
No available version for github "soffes/sskeychain" satisfies the requirement: ~> 2.0.0
$ cat Cartfile
github "soffes/sskeychain" ~> 2.0.0
```

**Comment by jpsim** [comment] 2015-05-26 17:59
@pietbrauer did you open an issue with Carthage? This seems to be strictly on that side since those tags are parsed before even pulling down Realm. So somehow, Carthage resolves `~> 0.96.0` to `v0.0.24b`.

**Comment by pietbrauer** [comment] 2015-05-26 18:02
@jpsim That was also my hypothesis but I couldn't reproduce it with SSKeychain so I stopped filing an issue.

**Comment by jpsim** [comment] 2015-05-26 18:04
Well it'll be different for every project with a different set of git tags, so to compare in a clean environment, you could copy the same tags the realm-cocoa repo has, although I'd expect just `0.92.4` and `v0.0.24b` to be sufficient. Or you could just add some failing tests to [VersionSpec.swift](https://github.com/Carthage/Carthage/blob/master/Source/CarthageKitTests/VersionSpec.swift).

**Comment by pietbrauer** [comment] 2015-05-26 19:44
@jpsim The SemanticVersion stuff seems to be fine, it is somehow deep in the resolver and I was not able to reproduce in a unit test. I opened https://github.com/Carthage/Carthage/issues/494 instead.

**Comment by jpsim** [comment] 2015-05-26 21:10
Let's wait to see what the recommendation from https://github.com/Carthage/Carthage/issues/494 ends up being.

**Comment by segiddins** [comment] 2015-05-27 20:18
Seems that conversation concluded it was a carthage issue?

**Comment by pietbrauer** [comment] 2015-05-27 20:40
Yep, conversation moved to https://github.com/Carthage/Carthage/issues/469.

**Closed** 2015-05-27 20:45 UTC
